### ISSUE TITLE
Docs about Negroni middleware

### ISSUE THREAD

**Issue by slava-vishnyakov** [kataras/iris#10]
The docs are saying that one can use Negroni middleware, I tried to to so:

```go
import (
	"github.com/goincremental/negroni-sessions"
	"github.com/goincremental/negroni-sessions/cookiestore"
)

...
	store := cookiestore.New([]byte(auth), []byte(enc))
	iris.Use(sessions.Sessions("session", store))
	iris.Get("/", handleMain)
	iris.Listen(":7000")
...
```

But as soon as I try to get the main page I get `*http.response is not negroni.ResponseWriter: missing method Before`

```go
2016/03/14 23:26:09 http: panic serving 127.0.0.1:64769: interface conversion: *http.response is not negroni.ResponseWriter: missing method Before
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc820228500)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1389 +0xc1
panic(0x46e9000, 0xc820202700)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/goincremental/negroni-sessions.Sessions.func1(0x4f915b0, 0xc820204680, 0xc820230460, 0xc82020e980)
	/Users/user/gopath/src/github.com/goincremental/negroni-sessions/sessions.go:92 +0x19a
github.com/kataras/iris.MiddlewareHandlerFunc.ServeHTTP(0xc820200330, 0x4f915b0, 0xc820204680, 0xc820230460, 0xc82020e980)
	/Users/user/gopath/src/github.com/kataras/iris/middleware.go:58 +0x44
github.com/kataras/iris.Middleware.ServeHTTP(0x4f90250, 0xc820200330, 0xc82020e5e0, 0x4f915b0, 0xc820204680, 0xc820230460)
	/Users/user/gopath/src/github.com/kataras/iris/middleware.go:69 +0xaa
github.com/kataras/iris.(*Route).ServeHTTP(0xc820218280, 0x4f915b0, 0xc820204680, 0xc820230460)
	/Users/user/gopath/src/github.com/kataras/iris/route.go:282 +0x65
github.com/kataras/iris.(*MemoryRouter).ServeHTTP(0xc82020e0e0, 0x4f915b0, 0xc820204680, 0xc820230460)
	/Users/user/gopath/src/github.com/kataras/iris/router_memory.go:62 +0x40a
github.com/kataras/iris.(*Station).ServeHTTP(0xc82020a070, 0x4f915b0, 0xc820204680, 0xc820230460)
	<autogenerated>:78 +0x70
net/http.(*ServeMux).ServeHTTP(0xc8202005a0, 0x4f915b0, 0xc820204680, 0xc820230460)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820228000, 0x4f915b0, 0xc820204680, 0xc820230460)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820228500)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2137 +0x44e
```

I think the docs would benefit from a few popular Middleware usage examples, such as `sessions` and maybe `secure`?

Thanks!

**Comment by kataras** [comment]
@slava-vishnyakov  You have absolute right but I am working at this project more than 15 hours per day for the last month... I am hurry up to keep up these kind of things you are suggesting. The next steps now are to create/or convert Plugins and Middleware for Iris. You can use any middleware you want parse it with iris.ToHandlerFunc and it should works. If you want open a topic here at github and we will discuss how to convert all popular middleware to Iris in order to define them without bugs.

Now, as you can see my english lang is not my best  for examples xD
Why don't you try to help me a little?. your name will be shown up as a contributor ofcourse !( Iris is on the global github trending list as we speaking  https://github.com/trending !!!)

**Comment by slava-vishnyakov** [comment]
Impressive! Sure, I can help with something, but I don't understand - are you telling me that currently `sessions` won't work with `iris` and needs to be re-written?

**Comment by slava-vishnyakov** [comment]
I tried this as you recommended

```sh
iris.HandlerFunc(sessions.Sessions("session", store))
```

doesn't seem to work 

```sh
panic: Error on Iris -> convertToHandler handler is not TypicalHandlerFunc or ContextedHandlerFunc, is negroni.HandlerFunc Point to: 0x42128e0:
```

**Comment by kataras** [comment]
No, iris.ToHandlerFunc exists , you getting the panic message from there, I forgot to remove the 'TypicalHandlerFunc' text but ok.

The particular middleware you show me, it is especially designed for negroni and only for negroni.. it uses it's specific type of function and the hardest is that it uses special ResponseWriter with buffer, Sessions are important, is this the only middleware exists for session?

**Comment by slava-vishnyakov** [comment]
Just to be clear - I'm showing output of `iris.HandlerFunc`, not `iris.ToHandlerFunc` (note there is no `To` in name) :)

I don't know if there's other middleware - I actually followed a link from https://github.com/kataras/iris#third-party-middleware

I'll try to find other sessions Middleware and tell you if it works.

**Comment by kataras** [comment]
iris.ToHandlerFunc calls imediatly the ToHandler because are the same at the moment,

Yes readme is updated

**Comment by slava-vishnyakov** [comment]
Ok, after `git pull` I've got the method :)

so,

```go
	store := cookiestore.New([]byte("123"), []byte("123"))
	iris.Use(iris.ToHandlerFunc(sessions.Sessions("session", store)))
```

```sh
cannot use iris.ToHandlerFunc("github.com/goincremental/negroni-sessions".Sessions("session", store)) (type iris.HandlerFunc) as type iris.MiddlewareHandler in argument to iris.Use:
	iris.HandlerFunc does not implement iris.MiddlewareHandler (wrong type for Serve method)
		have Serve(*iris.Context)
		want Serve(*iris.Context, iris.Handler)
```

**Comment by slava-vishnyakov** [comment]
Also tried `github.com/gin-gonic/contrib/sessions`

```go
	store := sessions.NewCookieStore([]byte("secret"))
	iris.Use(iris.ToHandlerFunc(sessions.Sessions("session", store)))
```

The result is the same

```sh
	iris.HandlerFunc does not implement iris.MiddlewareHandler (wrong type for Serve method)
		have Serve(*iris.Context)
		want Serve(*iris.Context, iris.Handler)
```

Sorry, I don't understand iris well enough yet to help with fixing this :)

**Comment by kataras** [comment]
Did you try ?

```
 iris.UseFunc(func(c *iris.Context, next iris.Handler) {
		//run the middleware here
		next.Serve(c)
	})
```
Again this sessions can't run because it uses special objects from negroni... but give a try to see yourself

**Comment by slava-vishnyakov** [comment]
This compiled, but gave runtime error.

```go
	iris.UseFunc(func(c *iris.Context, next iris.Handler) {
		f := sessions.Sessions("session", store)
		f(c.ResponseWriter, c.Request, func(rw http.ResponseWriter, r *http.Request) {})
		next.Serve(c)
	})
```

```sh
2016/03/15 03:28:39 http: panic serving 127.0.0.1:51453: interface conversion: *http.response is not negroni.ResponseWriter: missing method Before
```

Seems that negroni's sessions is a dead-end.

**Comment by kataras** [comment]
Yes... I told you it uses the negroni.ResponseWriter, we use the http.ResponseWriter to as simple as possible, negroni is too slow because of that kind of decisions. This middleware surely can be ported to Iris or more general to standar http middleware, because that I add a README note on the middleware section, if you want check it

**Comment by kataras** [comment]
@slava-vishnyakov Check examples for sessions I added a ported (low-level) access for sessions I am building a middleware also

**Comment by slava-vishnyakov** [comment]
Yep, LGTM! Thanks! :)

https://github.com/kataras/iris/blob/master/_examples/sessions/lowlevel.go

**Comment by kataras** [comment]
I made the middleware but I don't like its performance ... I will find a way to have a general store to the station and Get/Set values from the *Context which will communicate with the station's store to get/set values foreach *http.Request
