### ISSUE TITLE
How to get * http.Request?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#100]
Hi @kataras I have a custom file upload function, want to switch to Iris, but how to get * http.Request ?

**Comment by kataras** [comment]
Iris doesn't uses the net/http package. For uploading files take a look [here](https://github.com/iris-contrib/examples/tree/master/file_upload_simple) and you will understand what you have to do

**Comment by dxvgef** [comment]
@kataras Ok! Thank you!

**Comment by kataras** [comment]
Ask again here if you have any related problems in the course, thanks!

**Comment by dxvgef** [comment]
@kataras Thank you! the problem has been resolved.

**Comment by oscar-lopez** [comment]
I was wondering the same. I intend to use the `unrolled/secure` middleware, and for that I need to call `Process(w http.ResponseWriter, r *http.Request)`. Where can I obtain appropriate response and request objects from `iris.Context`? (BTW: the examples for using `secure` are outdated and won't compile)
