### ISSUE TITLE
Using Pug engine, but no default func?

### ISSUE THREAD

**Issue by DjLeChuck** [kataras/iris#1003]
Hi,

When using the Pug engine `tmpl := iris.Pug("./templates", ".pug")` I can not use iteration in my templates:

```pug
          .dropdown-menu
            each value in [1, 2, 3]
              a.dropdown-item(href="#")= value
```

The log says: `[ERRO] 2018/05/16 22:25 template: layouts/default.pug:17: function "each" not defined`

It's a normal behaviour? I must configure something special?

The engine is registred like this:

```go
	tmpl := iris.Pug("./templates", ".pug")
	tmpl.Reload(true) // reload templates on each request (development mode)

	app.RegisterView(tmpl)
```

**Comment by DjLeChuck** [comment]
Oh I think I got it!

It's normal, engines only do the parsing and I should use [html/template](https://golang.org/pkg/html/template/) functions instead?

**Comment by DjLeChuck** [comment]
Hi @kataras 

Thank you for your answer, I am aware of the `addFunc` :)

I was thinking that native Pug functions will be available, but it's not the case. I must use html/template loops and so on, right?

**Comment by kataras** [comment]
Ok, take a look another one:

### ./main.go

```go
// Package main shows an example of pug actions based on https://github.com/Joker/jade/tree/master/example/actions
package main

import (
	"github.com/kataras/iris"
)

type Person struct {
	Name   string
	Age    int
	Emails []string
	Jobs   []*Job
}

type Job struct {
	Employer string
	Role     string
}

func main() {
	app := iris.New()

	tmpl := iris.Pug("./templates", ".pug")
	app.RegisterView(tmpl)

	app.Get("/", index)

	// http://localhost:8080
	app.Run(iris.Addr(":8080"))
}

func index(ctx iris.Context) {
	job1 := Job{Employer: "Monash B", Role: "Honorary"}
	job2 := Job{Employer: "Box Hill", Role: "Head of HE"}

	person := Person{
		Name:   "jan",
		Age:    50,
		Emails: []string{"jan@newmarch.name", "jan.newmarch@gmail.com"},
		Jobs:   []*Job{&job1, &job2},
	}

	ctx.View("index.pug", person)
}
```
### ./templates/index.pug
```pug

doctype html
html(lang="en")
	head
		meta(charset="utf-8")
		title Title
	body
		p ads
		ul
			li The name is {{.Name}}.
			li The age is {{.Age}}.

		each _,_ in .Emails
			div An email is {{.}}

		| {{ with .Jobs }}
			each _,_ in .
				div
				 An employer is {{.Employer}}
				 and the role is {{.Role}}
		| {{ end }}
```

**Comment by kataras** [comment]
We need to upgrade the jade vendor in Iris, you can do it manually but I'll push a commit that does that, and adds those examples on the `_examples/view/template_pug_0` and _pug_1 folders :)

**Comment by DjLeChuck** [comment]
I don't know what's wrong with my configuration but I always get `function "each" not defined` :-/

```pug
ul
  each _,_ in .Tr.Links
  li {{ .Label }} - {{ .Link }}
```

Using range works:

```pug
ul
  {{range $l := .Tr.Links}}
    li
      | {{ .Label }}
      a(href={{.Link}})  {{ .Link }}
  {{end}}
```

**Comment by kataras** [comment]
`each` works too but in the newer version of jade parser, I've just pushed a commit with pug examples and the updated jade parser (provided by Joker/jade in the kataras/iris/vendor folder), you just need to `go get -u github.com/kataras/iris` and try again :)

**Comment by DjLeChuck** [comment]
Thank you for the update!

Now, I must go in all of my file to prefix `{{ .Something }}` with pipe `| {{ .Something }}` 😄 But that's OK!

**Comment by kataras** [comment]
The default html expressions still works inside pug, because the jade parser is based on the html/template package but yes it's better to use the same text language

**Comment by DjLeChuck** [comment]
Hum... I don't know what's wrong but since the update, my templates can not be compiled anymore. 🤔 

For example, this code which worked in previous version:
```pug
        {{ $url := urlpath "home" }}
        a.navbar-brand(href={{$url}}) {{ .RecalboxManagerTitle }}
```

must now be like this:
```pug
        | {{ $url := urlpath "home" }}
        a.navbar-brand(href=$url) {{ .RecalboxManagerTitle }}
```

It's because of the update of Joker/Jade?
