### ISSUE TITLE
formatCookieDomain return a wrong value when the domain has a region suffix like www.sina.com.cn

### ISSUE THREAD

**Issue by somethinghero** [kataras/iris#1004]
[in file cookie.go](https://github.com/kataras/iris/blob/master/sessions/cookie.go)
the function formatCookieDomain return a wrong value when the domain has a region suffix like www.sina.com.cn
expect return is .sina.com.cn but return .com.cn

**Comment by somethinghero** [comment]
I can not find out a good way to solve this problem that consider all kind of domain yet
for example the input maybe:
www.sina.com.cn
www.sina.com
sina.com
sina.com.cn
xxx.sina.com
xxx.sina.com.cn
emmm...

**Comment by kataras** [comment]
/cc @chengyumeng 

relative to: https://github.com/kataras/iris/pull/964
