### ISSUE TITLE
Pass data from middleware

### ISSUE THREAD

**Issue by tMathaiou** [kataras/iris#101]
First of all well done for your fantastic work,i just started to learn golang and saw your framework so i created a simple project but i have a problem im trying to pass data from one middleware to the next in line.Right now im using something like this to handle the data so i dont have to call the db two times to return me the user

```go
func IsAdmin(c *iris.Context) {	
	data, _ := json.Marshal(c.Get("user"))
	s := string(data)
	bytes := []byte(s)
    var user userModel.Users
    json.Unmarshal(bytes, &user)

	if user.Role != "" && user.Role == "admin" {		        
	   c.Next() 
	   return	    	        		
	}
	
	c.JSON(401, map[string]string{"error": "Unauthorized"})
	return	

}
```

Also if you have any tips here is my starter project [https://github.com/tMathaiou/ServerStarter](https://github.com/tMathaiou/ServerStarter).

**Comment by kataras** [comment]
@tMathaiou Thanks for your nice words, I hope you good luck with golang you will like it more and more!
It's a good option to pass the data via `c.Set()` and get it by `c.Get()` 
what's the problem you're dealing with this?

**Comment by tMathaiou** [comment]
Im just asking if there is a better way to get the data because what im getting back from the c.Get is an interface so i cant access user.Roles without first encoding and then decoding.Like add it to the request as it is a struct.

**Comment by kataras** [comment]
Golang doesn't supports `generics`for that reason I can't make a good injector for these cases, I'm sorry. You don't have to encode and decode it again? why you're doing that? Just pass the user struct with `c.Set("user",&User{})` and get it by `c.Get("user").(User)`

**Comment by tMathaiou** [comment]
ok that i didnt know thank you very much.

**Comment by kataras** [comment]
Yes take a look at [type assertions](https://golang.org/ref/spec#Type_assertions) , you're welcome, ask anything anytime! I'm waiting for your project to be completed :)

**Comment by kataras** [comment]
@tMathaiou After v2.2.4 you don't need to do `ctx.Set("user", nil)` the values are auto-reseting now, but can I ask you if you saw the [sessions](https://github.com/kataras/iris/tree/development/sessions) package? I think you don't need to set the user inside the context, you can use redis store with sessions..

**Comment by tMathaiou** [comment]
Nice thank you.I will give it a try tomorrow.

**Comment by ParadeTo** [comment]
@tMathaiou Which version are you using? Why can't I find 'Get' or 'Set' functions?

**Comment by liguoqinjim** [comment]
@ParadeTo 
ctx.Values().Set("m","123")
