### ISSUE TITLE
how can I config js 

### ISSUE THREAD

**Issue by itgeniusshuai** [kataras/iris#1013]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

I want to use js file ,how can I config js path

**Comment by itgeniusshuai** [comment]
I find result on [https://github.com/kataras/iris/issues/621](https://github.com/kataras/iris/issues/621)

**Comment by kataras** [comment]
Sorry for the delay @itgeniusshuai, usually I don't late to answer more than a couple of hours, I apologize to you.

```go
// static-files.go
package main

import "github.com/kataras/iris"

func main() {
	app := iris.New()

	// first parameter is the request path
	// second is the operating system directory
	app.StaticWeb("/static", "./assets")

	app.Run(iris.Addr(":8080"))
}
```

```
$ tree assets/
assets/
└── css
    └── styles.css
```
```sh
$ go run static-files.go

$ curl -s http://localhost:8080/static/css/styles.css
body {
    background-color: black;
}
```

**Comment by itgeniusshuai** [comment]
That's all right, your answer is better than I find,thank you
