### ISSUE TITLE
How to create Dynamic Path Request

### ISSUE THREAD

**Issue by luynt** [kataras/iris#1016]
I wanna to create a request like this:
```

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.URL.Path)
}

func main() {
	http.HandleFunc("/person/", handler)
	http.ListenAndServe(":8080", nil)
}
```
`curl  -X GET http://localhost:8080/persion/abc/xyz/jqk`
respone: /persion/abc/xyz/jqk
`curl  -X GET http://localhost:8080/persion/it/done/with/base/pkg`
respone: /persion/it/done/with/base/pkg
I know about litte with iris framework.Can someone help me ?

**Comment by long25vn** [comment]
I've this err, same you
```
curl -X GET http://localhost:9000/persion/abc/xyz/jqk
respone: /persion/abc/xyz/jqk
curl -X GET http://localhost:9000/persion/it/done/with/base/pkg
respone: /persion/it/done/with/base/pkg
I know about litte with iris framework.Can someone help me ?
```

**Comment by kataras** [comment]
```
func handler(ctx iris.Context) {
	ctx.WriteString(ctx.Request().URL.Path)
}

func main() {
	app := iris.New()
        app.Any("/person/{p:any}", handler)
	app.Run(iris.Addr(":8080"))
}
```

Another way is to use a `Route Wrapper` (it runs like your `net/http` codesnippet), look there: https://github.com/kataras/iris/tree/master/_examples/routing#wrapping-the-router

Read more at `Dynamic Path Parameters` document and examples: https://github.com/kataras/iris/tree/master/_examples/routing#dynamic-path-parameters

**Comment by luynt** [comment]
I resolved it ,but thanks for your help
