### ISSUE TITLE
Logging with full QueryString

### ISSUE THREAD

**Issue by andr33z** [kataras/iris#1017]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

====================================

❓ How to put full query string into custom log file?
i have following [this](https://github.com/kataras/iris/blob/master/_examples/http_request/request-logger/request-logger-file/main.go) reference to put custom file.
then i try to fire with this format : 
http://localhost:9092/user/profile?name=andre&token=123123

then i check to my log file, it is not showing full request.
![screen shot 2018-05-30 at 22 13 57](https://user-images.githubusercontent.com/20933631/40729546-d06dfb12-6456-11e8-8745-5e2c11e54a12.png)

can anyone help me? 
thank you

**Comment by kataras** [comment]
Iris' request logger can communicate with the handlers to build and print a custom `Message`:

```go
        logQueryMiddleware := func(ctx iris.Context) {
	    ctx.Values().Set("URL Query", ctx.Request().URL.Query().Encode())
	    ctx.Next()
        }

	loggerConfig := logger.Config{
                // ...
		MessageContextKeys: []string{"URL Query"}, // <-- here
	}

        loggerMiddleware := logger.New(loggerConfig )

       app.Use(logQueryMiddleware, loggerMiddleware)
```

Although I'll push a commit to display the full url if `logger.Config{ Query: true }` was passed as true. Star the github repository and stay tuned!

**Comment by andr33z** [comment]
BEST! Thank you
