### ISSUE TITLE
Failed to load http://localhost:54321/config/configs: Request header field token is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by itgeniusshuai** [kataras/iris#1021]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

	app.UseGlobal(func(ctx iris.Context){
		ctx.Header("Access-Control-Allow-Origin", "*")
		ctx.Header("Access-Control-Request-Headers","Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,token")
		ctx.Header("Access-Control-Request-Method","*")
		ctx.Header("Access-Control-Expose-Headers","token")
		ctx.Next()
	})
	crs := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "HEAD", "POST", "PUT", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "content-type", "X-Requested-With", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization", "token"},
	})
	app.AllowMethods(iris.MethodOptions)
	// 全局控制器
	mvc.New(app).Handle(new(controller.Controller))
	mvc.New(app).Party("/config",crs).Handle(new(controller.ConfigController))

![image](https://user-images.githubusercontent.com/18460477/40953738-999c90ec-68b3-11e8-927c-5496d5487fe6.png)

I try UseGlobal and cors，but it doesn't support my self-defined header

**Comment by itgeniusshuai** [comment]
I find why it doesn't support.When OPTIONS request received , a global middleware end it.But if I want to intercept a unlogined request ,how I do ???

**Comment by kataras** [comment]
Hey @itgeniusshuai, 

First of all please consider posting third-party and experimental middleware questions at their repository: https://github.com/iris-contrib/middleware in the future.
  
No, the global middleware does not end it, you have `ctx.Next` there.

I think you should try clear your browser's cache before retry.

The cors middleware has a working example at: https://github.com/iris-contrib/middleware/blob/master/cors/_example/main.go

However, for your use-case this one should do the job: 
```go
app.AllowMethods(iris.MethodOptions)
app.Use(func(ctx iris.Context){
	ctx.Header("Access-Control-Allow-Origin", "*")
	ctx.Header("Access-Control-Request-Headers","Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,token")
	ctx.Header("Access-Control-Request-Method","*")
	ctx.Header("Access-Control-Expose-Headers","token")
	ctx.Next()
})

app.Get("/", func(ctx iris.Context){ ctx.WriteString("Hello World!") }) // test.

mvc.New(app).Handle(new(controller.Controller))
mvc.New(app).Party("/config").Handle(new(controller.ConfigController))
```

**Comment by itgeniusshuai** [comment]
ok,  I will post at right location.
I have an another middleware like below:
`func loginFilter(ctx iris.Context) {
	path := ctx.Path()
	if ctx.Request().Method == iris.MethodOptions{
		ctx.Next()
		return
	}
	if path == "/index" || path == "/user/login"{
		ctx.Next()
		return
	}
	token := ctx.GetHeader("token")
	fmt.Println("token ",token)
	v := global.TokenMap.Get(token)
	if v == nil{
		fmt.Println("some error")
		ctx.JSON(global.Result{Code:-1})
		return
	}
	fmt.Println("right token pass")
	ctx.Next()
}`

when get get a wrong token ,it will return, and don't do ctx.Next() ,actually I wan't to return a json result,but the json can't be returned

**Comment by kataras** [comment]
What token?, this is something different, please explain me your code flow because I can't understand what it doesn't work, 99.9% of the times is not Iris problem but the design you've choosed to work with, pelase open a new issue if you still have problems
