### ISSUE TITLE
Crash when downloading with IDM

### ISSUE THREAD

**Issue by arjndr** [kataras/iris#1024]
Server crashes on `ctx.SendFile()` only if [Internet Download Manager](https://en.wikipedia.org/wiki/Internet_Download_Manager) is enabled. Nothing's logged on the console, just `exit status 1`. The file I'm passing to SendFile is a mp3 file. I've set the Header `Content-Type` to `audio/mpeg` too, hoping that would somehow fix the issue.

Chrome downloads it without any problems, as long as IDM is disabled

also, jQuery seems to log this warning.

![warning](https://s33.postimg.cc/o27pschzz/err-iris.png)

**Comment by kataras** [comment]
`ctx.SendFile` is a server-side function, iris web framework is a back end framework, except the websocket client library I did for the websocket side for Iris nothing else could prove that, the `jquery` error you get is propably by a browser's plugin/extension.

About the error, did you try something like `http.ServeFile` with `ctx.ResponseWriter()` and `ctx.Request()` as its parameters to see if it has the same behavior?

**Comment by arjndr** [comment]
Yes, I know Iris is back end and no, I haven't tried them, will try and post an update on it ASAP.
P.S: Thanks for such an amazing framework :')

**Comment by arjndr** [comment]
Sorry about the delay, same results with `http.ServeFile`, Btw I'm submitting the form using jQuery `$('form').submit();` , could this possibly be the cause of that random jQuery warning?

**Comment by arjndr** [comment]
Well, I guess it's safe to say that this issue is related to the `net/http` module. I ended up sending binary data to the front end, converted that data to blob and then downloaded it.

**Comment by kataras** [comment]
I don't have windows to test the IDM right now, but it's strange that it exits without any message, Iris never panics or exit, always returns an error (this is a design choice) and if you use the [recover](https://github.com/kataras/iris/tree/master/middleware) middleware it recovers from any panics you may added to your handler manually. This is why I want to ask you if you can join to our [chat](https://chat.iris-go.com) and talk with me in private window so I can review your code (if possible) and solve the issue together, even if it's `net/http`'s error I can fix it if I have the correct debug process.
