### ISSUE TITLE
AutoTLS and Wildcard subdomains

### ISSUE THREAD

**Issue by marcetin** [kataras/iris#1032]
As the following example for wildcard subdomains:
https://github.com/kataras/iris/blob/master/_examples/subdomains/wildcard/main.go
Using:
app.Run(iris.AutoTLS(":443", "example.com", "mail@example.com")) 
it only get certificate for the main domain.

Usage of * (star) as the wildcard is not working:
app.Run(iris.AutoTLS(":443", "*.example.com", "mail@example.com")) 

The case of entering subdomains by manual is working:
app.Run(iris.AutoTLS(":443", "sub1.example.com sub2.example.com sub3.example.com", "mail@example.com")) 

If subdomains are deleted and if there is cert file on host subdomain will work although it is not listed whitelist field.
app.Run(iris.AutoTLS(":443", "sub3.example.com", "mail@example.com")) 

By manually adding subdomains it gets a certificate for each subdomain which means it will get only 20 per week. 
Letsencrypt allows 20 certificates per registered domain per week, but it allows combining up to 100 Names into a single certificate.
So there should be some function which will allow wildcard usage, placing each new subdomain in a certificate until 100 subdomains. 
As in example  " username := ctx.Subdomain()" , the function should run through usernames and use them as subdomains, or maybe better, if possible, to insert subdomain into a certificate once subdomain is a first time called.
Anyhow, the function should fill one certificate with subdomains until reach 100 and then request a new certificate which will be filed until 100 and so on. In that way, it can get 2000 subdomains per week, 100 names by 20 certificates per week. This should be implemented in Iris as there are AutoTLS and Wildcard subdomains but they are not working together in a full manner.

**Comment by kataras** [comment]
The `ctx.Subdomain` has nothing to do with the letsencrypt's registered subdomains, please read the `core/context.go#Subdomain` code, you will understand.

The `AutoTLS` is independent, it does not touch something without your knowedge, i.e routes or other configuration, this is a design choice to make things clearer, you should do manually listening for subdomains, this is a security choice.

`So there should be some function which will allow wildcard usage, placing each new subdomain in a certificate until 100 subdomains.` <- https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L301, please search it, do some tests with your iris server and tell me what we need to change or push a PR, I think we have all we need there.
