### ISSUE TITLE
Option to log all HTTP requests to a file?

### ISSUE THREAD

**Issue by kirandasika98** [kataras/iris#1035]
Is there a way to log all HTTP requests to a file instead of ```os.Stdout``` ? I saw there was a way to do it using golog, but I was wondering if there was a way to configure that while setting up the server.

**Comment by kataras** [comment]
Please look the examples, I spent many hours creating them for you guys, here you are my friend: https://github.com/kataras/iris/blob/master/_examples/http_request/request-logger/request-logger-file/main.go

**Comment by kirandasika98** [comment]
Thanks.
