### ISSUE TITLE
AutoTLS not working on GCP VM.

### ISSUE THREAD

**Issue by jaggerwang** [kataras/iris#1039]
## Problem

As the title. I'm using docker on GCP VM to run iris app.

Open `https://aiart.app/` in Chrome, got the following server log. `118.112.59.122` is client's ip, `35.194.139.245` is server's ip.

```
Now listening on: https://localhost
Application started. Press CTRL+C to shut down.
[HTTP Server] http: TLS handshake error from 118.112.59.122:49862: 202 : {
  "id": 38019606,
  "key": {
    "kty": "EC",
    "crv": "P-256",
    "x": "YiviAj3Jgsmnhs2F0IpI6v7jLQJWR2LUKoTxB7SilXo",
    "y": "xCsumtqVjdIBF7qfHn2meGXZirgIGQMwPdTsCCJYFAE"
  },
  "contact": [
    "mailto:jaggerwang@gmail.com"
  ],
  "agreement": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
  "initialIp": "35.194.139.245",
  "createdAt": "2018-07-09T04:15:00Z",
  "status": "valid"
}
[HTTP Server] http: TLS handshake error from 118.112.59.122:52612: acme/autocert: missing certificate
```

## Code

```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Favicon("./public/favicon.ico")

	app.Use(iris.Gzip)

	app.StaticWeb("/", "./public")

	app.Run(iris.AutoTLS("0.0.0.0:443", "aiart.app aiattack.app", "jaggerwang@gmail.com"))
}
```

**Comment by kataras** [comment]
Seems that this is coming from the go `autocert` library for letsencrypt, the code is fairly simple for that:  https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L291-L345 , try to play with the [CurvePreferences](https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L337) by removing the lowest, rebuild using your own iris fork and comment back here, I remember letsencrypt had a security issue some months ago, they removed one of their old methods for handshake but I did the same with Iris, the same day they push the fix, iris was updated too.

Don't know what else can be wrong there, I'm using the Iris' AutoTLS and Caddy in many cases, you can try my steps above, but if you really don't have time to investigate it just go with mholt/caddy as a proxy for your Iris server, it provides auto tls as well maybe it suits you better if you have more than one web server on the same machine, we have [caddy example](https://github.com/kataras/iris/tree/master/_examples/tutorial/caddy) as well. Keep me updated please.

**Comment by kataras** [comment]
Seems that this is coming from the go `autocert` library for letsencrypt, the code is fairly simple for that:  https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L291-L345 , try to play with the [CurvePreferences](https://github.com/kataras/iris/blob/master/core/host/supervisor.go#L337) by removing the lowest, rebuild using your own iris fork and comment back here, I remember letsencrypt had a security issue some months ago, they removed one of their old methods for handshake but I did the same with Iris, the same day they push the fix, iris was updated too.

Don't know what else can be wrong there, I'm using the Iris' AutoTLS and Caddy in many cases, you can try my steps above, but if you really don't have time to investigate it just go with mholt/caddy as a proxy for your Iris server, it provides auto tls as well maybe it suits you better if you have more than one web server on the same machine (but what am I telling you, you're using docker so you're totally fine :P) , we have [caddy example](https://github.com/kataras/iris/tree/master/_examples/tutorial/caddy) as well. Keep me updated please.

**Comment by jaggerwang** [comment]
I switched to Caddy. I used it before, and it seems it getting more and more powerful. Thanks!
