### ISSUE TITLE
Mixed line endings in the Iris source files

### ISSUE THREAD

**Issue by IRuslan** [kataras/iris#1041]
Hi,

I'm new to the Iris, sorry if make report is not relevant.

I've encountered problems with installing Iris via dep.
Digging into the details of the problem I've found that if you simply checkout the github.com/kataras/iris,
'git status' will show a bunch of changes while you didn't modify anything.

From what I see, changes come from the fact that the repo contains .gitattributes with '* text=auto' option, which is ok.
But this option tells GIT to change line endings in the case of a mismatch during checkout.
And it usually will work, but repo already contains files of mixed line endings.
That's why no matter if you are on Linux/Mac or Windows you will have some files with different line endings than yours. And GIT will try to make it consistent (because of .gitattributes).

Example of a file with CRLF:
CONTRIBUTING.md

Example of a file with LF:
go19.go

I think it makes sense to apply a single line ending to all files (and again because of .gitattributes it will remain consistent).

**Comment by kataras** [comment]
Hello @IRuslan!

I am switching between linux and windows all the time, the `text=auto` solution on `.gitattributes` file did the job for me, I don't see a reason to change that(1), and how do I apply a single line ending to all files on different operating system?

(1) How `vgo` or `dep` are relative to the `.gitattributes` file and how did you fix it, relative issues of dep issues: https://github.com/kataras/iris/issues/1040, https://github.com/kataras/iris/issues/1029 but they are all solved by the users, how did you solve it? by cloning and changing the `.gitattributes` ?


Sincerely,
Gerasimos Maropoulos

**Comment by IRuslan** [comment]
Hello @kataras 

> I am switching between linux and windows all the time, the text=auto solution on .gitattributes file did the job for me, I don't see a reason to change that(1), and how do I apply a single line ending to all files on different operating system?

Maybe it works for you because you do checkout before `.gitattributes` has been introduced.
Just to test, can to make a clean checkout of Iris on Linux? What `git status` tell for you in the case of that new clone?
In my case, it's a bunch of modifications. And it's not about dep - I did pure `git clone`.

> (1) How vgo or dep are relative to the .gitattributes file and how did you fix it, relative issues of dep issues: #1040, #1029 but they are all solved by the users, how did you solve it? by cloning and changing the .gitattributes ?

Thanks for the references, I'll check them closely.
Regarding workaround for my case, what exactly I did:
1. Forked Iris repo
2. Clone the fork repo
3. In the same way as Iris, forked repo contains mixed line endings
4. So `git status` show a lot of changes
5. Those changes - auto-replacement of CRLF with LF (I have no any git specific settings, only .gitattributes from the repo)
6. I push those changes to my fork
7. I install the fork via dep and it works

**Comment by kataras** [comment]
![git_clone_iris](https://user-images.githubusercontent.com/22900943/42734344-dfd2bcc4-884a-11e8-9605-8b1ab4edff27.png)

My global git configs:
```
core.autocrlf=input
core.filemode=false
```

**Comment by IRuslan** [comment]
@kataras I would love to help. 
But I'm not able to modify `.gitattributes` because once I'm doing checkout - source files modified already.
I think we could try this if you create some test branch with the values you mentioned and I will checkout it.

**Comment by IRuslan** [comment]
btw, I'vee tried the same on MacOS - the same problem, pure `git clone` leads to modified files.

**Comment by tensor146** [comment]
Same problem, looks like there is something to fix on iris side.
