### ISSUE TITLE
web template

### ISSUE THREAD

**Issue by skyqinsc** [kataras/iris#1042]
view: template:   function "each" not defined

**Comment by skyqinsc** [comment]
https://github.com/kataras/iris/tree/master/_examples/view/template_pug_1

This example doesn't work

**Comment by kataras** [comment]
Yes it does
![yesitdoes](https://user-images.githubusercontent.com/22900943/42893440-fab649b0-8abc-11e8-9cd0-b1f191365129.png)

**Comment by kataras** [comment]
Yes, the `pug` engine has been updated since then, you can upgrade your iris using `go get -u github.com/kataras/iris`, if you can't upgrade but you want the latest syntax, I can help you on chat: https://chat.iris-go.com
