### ISSUE TITLE
Go 1.11beta2 compatibility issues

### ISSUE THREAD

**Issue by dmarko484** [kataras/iris#1049]
I have upgraded to Go 1.11beta2 recently and today tried to get iris using 
> go get -u github.com/kataras/iris

Haven't seen such issue when running Go 1.10. Any idea whats going on here?

> go get -u github.com/kataras/iris
# runtime
C:\Go\src\runtime\map.go:64:2: bucketCntBits redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:64:18
C:\Go\src\runtime\map.go:65:2: bucketCnt redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:65:23
C:\Go\src\runtime\map.go:69:2: loadFactorNum redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:69:18
C:\Go\src\runtime\map.go:70:2: loadFactorDen redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:70:18
C:\Go\src\runtime\map.go:76:2: maxKeySize redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:76:17
C:\Go\src\runtime\map.go:77:2: maxValueSize redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:77:17
C:\Go\src\runtime\map.go:82:2: dataOffset redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:85:4
C:\Go\src\runtime\map.go:91:2: empty redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:91:19
C:\Go\src\runtime\map.go:92:2: evacuatedEmpty redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:92:19
C:\Go\src\runtime\map.go:93:2: evacuatedX redeclared in this block
        previous declaration at C:\Go\src\runtime\hashmap.go:93:19
C:\Go\src\runtime\map.go:93:2: too many errors

**Comment by kataras** [comment]
Hello @dmarko484, I was able to install iris on go 1.11beta2 without issues and you will never have issues with it, the error messages you represent have nothing to do with Iris, you just mess up with it, try to clean your GOPATH (or better set a new one for your go 1.11beta2 version) and try again, here you are:
![noitworks](https://user-images.githubusercontent.com/22900943/43255305-2a1f8e26-90d2-11e8-81c9-a307d91f4e36.png)


If cleaning your GOPATH does not work, then try to re-install go 1.11beta2

**Comment by kataras** [comment]
You're welcome, if you have any further issues in the future don't hesitate to ask! Glad we have you here
