### ISSUE TITLE
Path parameters and wildcards cannot be used together

### ISSUE THREAD

**Issue by jiankunking** [kataras/iris#1052]
For example:
`func AgentInstall(app *iris.Application) {
	rp.Get("/clusters/{cluster}/cat/*", ListClusterAgents)
}`
This path cannot be routed to
`clusters/qd/cat/list`

**Comment by kataras** [comment]
It can but it seems you didn't even bother any example, we don't have `*` for any aprameter....

Use the `path` parameter type, here you are:
```go
func AgentInstall(app *iris.Application) {
 rp.Get("/clusters/{cluster:string}/cat/{p:path}", ListClusterAgents) 
}
```

**Comment by jiankunking** [comment]
1、 I configure the "/clusters/{cluster}/cat/*" path,When i request the "clusters/qd/cat/list" path,Back to 404.
2、 I configure the "/clusters/{cluster:string}/cat/{p:path}" path,When i request the "clusters/qd/cat/list" path,Back to 404.

+------------------------+
| {param:path}           |
+------------------------+
path type
anything, should be the last part, more than one path segment,
i.e: /path1/path2/path3 , ctx.Params().Get("param") == "/path1/path2/path3"

**Comment by jiankunking** [comment]
I want when I request path "clusters/qd/cat/list", I can request the corresponding processing method

**Comment by kataras** [comment]
@jiankunking  the `*` does not exist in Iris I don't know where you got this misinformation, but it is not valid, please read our examples, I have written more than 100 for that reason, for you, please do not dissapoint me:)

I already gave you the code you need above for that request pattern you're asking.

**Comment by jiankunking** [comment]
Thank you for your reply.
I have read the examples in the source code.
I found the route invalid when there were two parameters in the path.
For example:
` rp.Get("/clusters/{cluster:string}/cat/{p:path}", ListClusterAgents) `
When i request the "clusters/qd/cat/list" path,Back to 404.

**Comment by kataras** [comment]
You are welcome, check that:

![it_works_man](https://user-images.githubusercontent.com/22900943/43455588-0934e710-94c9-11e8-8551-d0b7135da9db.png)

Maybe you have something invalid on other routes of your server?
