### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by cfanboy** [kataras/iris#1055]
I am using Iris MVC to develop a website. When I use 'rizla main.go' or 'iris run main.go', will receive the error 'too many open files' message. But the website can work finely.

My OS is MacOS system and I watched the system files limits, all are ok

`ulimit -a`
--------------------
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

--------------------
I also checked the proc open files with command `lsof -p 1049 | wc -l`, it only opened 28 files.
So any suggestion?
Thanks

**Comment by kataras** [comment]
First of all,  the issue has nothing to do with Iris @cfanboy . We don't have `iris ...` command anymore, so you probably use a very old version (1 year ago++), the [rizla](https://github.com/kataras/rizla) lives on its own repository, and yes it is a watcher, it's the expected behavior.
