### ISSUE TITLE
How to use Session in none mvc project controller?

### ISSUE THREAD

**Issue by cfanboy** [kataras/iris#1057]
My project is APIs type, not MVC, I init the session in main function, but how can I use it in single controller methods? 
I saw the session examples, all are using in the same main.go files and there is no any method in Context to get session instance like the previous version.
Thanks

**Comment by kataras** [comment]
How much experience with Go do you have? This is not an iris question... you can:

- just delcare the variable outside of `func main`
- create a service structure and have the `sessions.Sessions` instance there
- pass the `sessions.Sessions` on the functions which create an iris handler
- Iris can use dependency injection outside of MVC as well, take a look at `hero` package, like `mvc` : `hero.Register(mySessions.Start)` `handler := hero.Handler(func(ctx iris.Context, session sessions.Session){{ /* use the session.Get/Set...*/})` <- magic? https://github.com/kataras/iris/tree/master/_examples/hero/basic

**Comment by kataras** [comment]
I just created an example for you @cfanboy although you can just read the mvc examples, the mvc it uses the `hero` under the hoods. Here you are: https://github.com/kataras/iris/tree/master/_examples/hero/sessions . Have fun!

**Comment by cfanboy** [comment]
Thank you !! It's very helpful for me

**Comment by kataras** [comment]
You are welcome! Don't hesitate to ask more!!
