### ISSUE TITLE
Sessions.ShiftExpiration() does not shift redis TTL accordingly

### ISSUE THREAD

**Issue by akiraho** [kataras/iris#1061]
Hi there,

In Sessions.ShiftExpiration(), it calls Provider.UpdateExpiration() which updates the corresponding provider.sessions[sid] entry.

However, should it also update the underlying db? Otherwise the corresponding redis key gets expired unexpectedly as the redis TTL isn't updated.

Thanks.

**Comment by kataras** [comment]
Hello @akiraho, it is done by: https://github.com/kataras/iris/commit/fe04a27865f9a29f4037c6b30b8b1be654283dc6.

The `UpdateExpiration` now can return a non-nil error too, `NotFound` and `ErrNotImplemented`(for bolt and badger, at the moment).

The example has been tested with redis 4.0.11 and updated to include those error checks: https://github.com/kataras/iris/blob/master/_examples/sessions/database/redis/main.go#L120

Thank you for the report and have fun!

**Comment by kataras** [comment]
Hello @akiraho, it is done by: https://github.com/kataras/iris/commit/fe04a27865f9a29f4037c6b30b8b1be654283dc6.

The `UpdateExpiration` now can return a non-nil error too, `NotFound` and `ErrNotImplemented`(for bolt and badger, at the moment).

The example has been tested with redis 4.0.11 and updated to include those error checks: https://github.com/kataras/iris/blob/master/_examples/sessions/database/redis/main.go#L120

Thank you for the report and have fun, do not forget to star or/and watch Iris to get further updates!

**Comment by akiraho** [comment]
Hi @kataras thx for the quick fix;

However there's still an issue with Sessions.ShiftExpiration(); while the underlying lifetime object would reset its timer upon Shift() it missed to also shift its own "Time" property.

It's a one-line fix and I've created a pull request; please review. 

Thanks.

**Comment by akiraho** [comment]
Hi there,

Thanks for fixing the issue quickly; however there's one more issue in the
lifetime object where it missed to update its "Time" property upon
"Shift()".

For some reason the redis TTL would still not be updated upon
Sessions.ShiftExpiration() until I also fixed this issue. (adding "lt.Time
= time.Now().Add(d)" into the lifetime object)

I"ve created a pull request; I'd really appreciate if you'd review and
accept the commit soon.

This is a critical issue in our project and without this we can't really go
live.
(otherwise I'd have to update all references in our code to my own branch
instead of your official branch, which would be lots of hassles)

Thanks,
Akira

**Comment by kataras** [comment]
I thank you, I left a review on your fix, that line is incorrect, it shouldn't "add" it should "reset", you missunderstood it but I will give you time to fix it :P
