### ISSUE TITLE
Live Video Stream on a Iris Server

### ISSUE THREAD

**Issue by majidbigdeli** [kataras/iris#1065]
Can I use Live Streaming with Iris Web Socket?

**Comment by kataras** [comment]
Hello,

Why not? Iris' websocket supports raw bytes direct websocket communication, even protobuf etc.. See https://github.com/kataras/iris/blob/master/_examples/websocket/native-messages/main.go#L31-L47. However if for some reason you have already a working live streaming web application you can still use the same library for websocket+live streaming, iris is compatible with `net/http` 100%. You are not forced to use something in particular.

Thanks,
Gerasimos Maropoulos

**Comment by majidbigdeli** [comment]
thank you very much . I used Iris and made it very well.
I Love Iris framework ;

**Comment by kataras** [comment]
You are very welcomed! Do not hesitate to ask for further support when you need it, I thank you for using Iris, we are all together in this.
