### ISSUE TITLE
Reconnect WebSocket on disconnection

### ISSUE THREAD

**Issue by kickbox** [kataras/iris#1066]
How to reconnect the iris websocket on disconnection, without refreshing the client page?

**Comment by speedwheel** [comment]
Hello @kickbox, I guess this is more of a javascript question, but anyway, here is a quick example of how I would do it (you need to have the iris-ws.js included inside your page): 

```js
let websocket = new Ws('wss:yourwebsocketurl');
let wsTimeout;
let timeoutInterval = 5000;
websocket.OnConnect(function() {
	clearTimeout(wsTimeout);
});

websocket.OnDisconnect(function() {
	wsTimeout = setTimeout(function() {
		StartWebsocket();
	}, timeoutInterval);
});
```

Basically on disconnect you just try to reconnect again every 5 seconds, until it connects and it resets the timeout interval, this can be extended according to your needs.

**Comment by kickbox** [comment]
Thank you!

**Comment by hbaiyu** [comment]
How to implement the go language
