### ISSUE TITLE
Debug Profiler writing escaped HTML?

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#107]
I may not understand how the debug profiler is supposed to work, but as far as I can tell its writing escaped HTML which isn't entirely useful.

```go
config := &iris.IrisConfig{
		Profile:            true,
		ProfilePath:        iris.DefaultProfilePath,
}
api := iris.New(config)
```

Browser: /debug/pprof
Response: escaped html written to screen.

Is this correct behaviour? If so, please close this issue.

**Comment by kataras** [comment]
No it's not the normal behavior, just fixed it , thanks!

**Comment by jjhesk** [comment]
what is the correct setup?
