### ISSUE TITLE
websocket count connections/clients

### ISSUE THREAD

**Issue by jjhesk** [kataras/iris#1070]
in websocket, are there such method to call for how many clients that are subscribed? are there such demo code for references?

**Comment by kataras** [comment]
Yes, `GetTotalConnections()` will return the number of connected clients.

The `GetConnectionsByRoom(roomName string) []Connection ` will give you the connections connected to a specific room. However, you can manually track however you want the connected client; you can just make a counter or "a" feature inside the `OnConnection` or your websocket handler's body.

**Comment by jjhesk** [comment]
according to 

> "a" feature inside the OnConnection or your websocket handler's body.

i found that there is the emit message function in the handleConnection. how do I pass in the` ws *websocket.Server ` into this callback function? do u suggesting to use chan *websocket.Server to get back the number digit?

**Comment by jjhesk** [comment]
@kataras hi, what is the maximum connections that iris can up held? I have tested on my local mac machine and I have reached successfully on 236 connections made from nodejs.

**Comment by kataras** [comment]
`GetTotalConnections` from https://github.com/kataras/neffos as of Iris 11.2: https://dev.to/kataras/iris-version-11-2-released-22bc
