### ISSUE TITLE
app.SPA vs non app.SPA

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1072]
I saw "Single page application" example and was surprised to see, what's the benefit of using below code - 

```
assetHandler := app.StaticHandler("./public", false, true)
app.SPA(assetHandler)
```

One can setup SPA application without above code too. What is difference or benefit in using `app.SPA` code?

**Comment by kataras** [comment]
It is just a helper, ofc you can serve anything using a root wildcard: `/{paramName:path}` but the `app.SPA` returns the `*router.SPABuilder` which contains some interesting properties that you can customize like `AssetValidators` and  `IndexNames`, the godocs of the `core/router/spa.go` explains them.

See 
https://github.com/kataras/iris/blob/master/iris.go#L476 and
https://github.com/kataras/iris/blob/master/core/router/spa.go#L93
