### ISSUE TITLE
middleware cors problem

### ISSUE THREAD

**Issue by xiusin** [kataras/iris#1077]
## route
```go
	app := mvc.New(app.Party("/api/v1", cors.AllowAll()).AllowMethods(iris.MethodOptions))
	app .Handle(new(api.UserApiController))
```

## controller 
```go
type UserApiController struct {
	Orm *xorm.Engine
	Ctx iris.Context
}

func (c *UserApiController) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle(iris.MethodPost, "/user/login", "UserLogin")
	b.Handle(iris.MethodGet, "/user/center", "UserCenter")
}

func (c *UserApiController) UserLogin() {

}

func (c *UserApiController) UserCenter() {
}
```

## test
![image](https://user-images.githubusercontent.com/36065131/44780368-60b90000-abb4-11e8-8171-7ee6f3583ad9.png)

>I found the file `github.com/iris-contrib/middleware/cors/cors.go` 's method `handleActualRequest`
```go
func (c *Cors) handleActualRequest(ctx context.Context) {
	origin := ctx.GetHeader("Origin")
	if ctx.Method() == http.MethodOptions { // Is there any mistake here?
		c.logf("  Actual request no headers added: method == %s", ctx.Method()) 
		ctx.StatusCode(http.StatusMethodNotAllowed)
		ctx.StopExecution()
		return
	}

...
```
 Is there any mistake here?

```go
func (c *Cors) handleActualRequest(ctx context.Context) {
	origin := ctx.GetHeader("Origin")
	//if ctx.Method() == http.MethodOptions {
	//	c.logf("  Actual request no headers added: method == %s", ctx.Method()) 
	//	ctx.StatusCode(http.StatusMethodNotAllowed)
	//	ctx.StopExecution()
	//	return
	//}

```
That's the way to do it.
![image](https://user-images.githubusercontent.com/36065131/44780776-50555500-abb5-11e8-82c2-2a0c3fbec959.png)

**Comment by kataras** [comment]
Hello, @xiusin  you posted code from `iris-contrib/middleware` but you posted the issue on `kataras/iris` repo, I am not the only one contributor to the iris-contrib/middleware repository, this is why you must post your issues to the correct repo so you can get more support, your recommendation is not correct for cors handling, the existing code should work (at least it does here), also the snippet you shared here it is not the real one, you use the `app` variable for `iris.Application` and `mvc.Application` instances; this must throw a compile error).

If you have any issues with the `cors ` middleware, you can  just remove the `cors.AllowAll()` and instead do:

```go
v1:= app.Party("/api/v1").AllowMethods(iris.MethodOptions)
v1.Use(func(ctx iris.Context){
	ctx.Header("Access-Control-Allow-Origin", "*")
	ctx.Header("Access-Control-Request-Headers","Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,token")
	ctx.Header("Access-Control-Request-Method","*")
	// ctx.Header("Access-Control-Expose-Headers","token")
	ctx.Next()
})

mvcApp:= mvc.New(v1)
mvcApp.Handle(new(api.UserApiController))
```

**Comment by xiusin** [comment]
@kataras i see , thanks

**Comment by g0194776** [comment]
@xiusin 

I've met the same situation here.

It seems like a mistake but I have no way to skip it. Do u have any solutions?

**Comment by xiusin** [comment]
@g0194776  temporary annotation vendor source code. I have no better solution.  sorry.

**Comment by g0194776** [comment]
@xiusin 

ahh...nothing.
I have no any better ideas too. So nice of you, thanks a lot.

**Comment by mbecker** [comment]
Hi,
any news on that? My foolowing code snippet doesn't work as well:

```go
crs := cors.New(cors.Options{
		AllowCredentials: true,
		AllowedHeaders:   []string{"*"},
		AllowedMethods:   []string{"*"},
		AllowedOrigins:   []string{"*"}, // allows everything, use that to change the hosts.
	})
v1 := app.Party("/api/v1", crs).AllowMethods(iris.MethodOptions) // <- important for the preflight.
	{
		// Upload the file to the server
		// POST: http://localhost:8080/upload
		v1.Post("/upload", iris.LimitRequestBodySize(10<<20), func(ctx iris.Context) {
			....
		})
	}
```

The following code snippet as shown in a comment aboe doesn't work too:
```go
v1.Use(func(ctx iris.Context) {
		ctx.Header("Access-Control-Allow-Origin", "*")
		ctx.Header("Access-Control-Request-Headers", "Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,token")
		ctx.Header("Access-Control-Request-Method", "*")
		// ctx.Header("Access-Control-Expose-Headers","token")
		ctx.Next()
	})
```

Would be nice to give a hint where to look at. Thanks and best regards!

**Comment by kataras** [comment]
Hello @mbecker I am 99% sure that it is a client-side issue, for example the `fetch` (documentation: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_request_options) has default the "same-origin" option for cors, you have to change to "cors":

```js
    fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        mode: "cors", // other options: no-cors and same-origin which is the default
    // [...]
```

If you don't use the "fetch" and you use other ajax, there is an option there as well if you search. It is not an iris issue but I am happy to help you, please respond if that worked for you. Thank you.

**Comment by mbecker** [comment]
HI @kataras , thanks for replying! Actually I'm using your dropzone example:
- Server 1: Upload Endpoint as defined above
- Server 2: Upload form with your example implementation; additionaly I've added the following config options:
```javascript
<script type="text/javascript">
        Dropzone.options.dropzoneForm = {
            // paramName: "file", // The name that will be used to transfer the file
            maxFilesize: 2, // MB
            headers: {
                "Accept": null,
                'Authorization': null,
                // remove Cache-Control and X-Requested-With
                // to be sent along with the request
                'Cache-Control': null,
                'X-Requested-With': null
            },
            accept: function (file, done) {
                if (file.name == "justinbieber.jpg") {
                    done("Naha, you don't.");
                }
                else { done(); }
            }
        };
    </script>
```
(Pull request to dropzone at the following url: https://github.com/enyo/dropzone/pull/685)

The browser's console logs as follows:
```
Access to XMLHttpRequest at 'http://localhost:8080/api/v1/upload' from origin 'http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I've slightly modified the "Access-Control-Request-Headers" in the second code block from above and added "Cache-Control" as follows:
```go
v1.Use(func(ctx iris.Context) {
		ctx.Header("Access-Control-Allow-Origin", "*")
		ctx.Header("Access-Control-Request-Headers", "Cache-Control,Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,token")
		ctx.Header("Access-Control-Request-Method", "*")
		// ctx.Header("Access-Control-Expose-Headers","token")
		ctx.Next()
	})
```
(No success)

From my understanding I've added all relevant "Access-Control-*" settings in the backend and have configured dropzone to send the correct preflight headers (bascially it shouldn't send anything).

Am I missing anything? Thank for your help!

**Comment by kataras** [comment]
Sorry, you have to add to the allowed header the `Access-Control-Allow-Origin` itself, see: https://github.com/kataras/iris/issues/1122#issuecomment-436100323
