### ISSUE TITLE
Session Question

### ISSUE THREAD

**Issue by stefanwuthrich** [kataras/iris#1078]
Hi

I'm using Boostrap Structure example and first tried to find out, how to set/get Session from handlers, using the Sessions which are setup in bootstrap.go.No idea...
So I tried to use own Session Init, with Redis example.
When I set a Session key value in on handler and try to get the value in another, i get empty string with .Get. But Cookie is set and If i print in same handler storage.SessionStorage.Start(ctx) i get something like

`&{0a8cedf9-0526-41a3-8415-cc2beb960360 false map[] {{0 0} 0 0 0 0} 2018-08-31 16:33:24.119503987 +0200 CEST m=+2704.572051512 0xc4201fc800}
`
0a8cedf9-0526-41a3-8415-cc2beb960360 corresponds with sessionid in Browser

any idea what can be wrong with what I do ? I already checked examples and did go through Issues

**Comment by kataras** [comment]
Hi, you need to setup sessions with the 'AllowReclaim' config field set to true in order to see the stored sessions in the same request that is stored.

**Comment by stefanwuthrich** [comment]
Tks for fast answer.
O already have this set

sess := sessions.New(sessions.Config{
		Cookie:       "sessionscookieid",
		Expires:      45 * time.Minute, // <=0 means unlimited life. Defaults to 0.
		AllowReclaim: true,

**Comment by kataras** [comment]
Hey, can you please post your go code? I can't help you right now, I don't have the information I need, because the example and other's code working fine.

**Comment by stefanwuthrich** [comment]
I tested the same code, removing UseDatabase(db) and that way it works fine.
Then I tried with using Badger. That way I get a "Trace send on close channel" on first .Start(ctx) in handler.

This is InitSession func, called in main.go
`
var SessionStorage *sessions.Sessions


func InitSession() {




	db, err := badger.New("./data")
	if err != nil {
		panic(err)
	}

	iris.RegisterOnInterrupt(func() {
		db.Close()
	})

	defer db.Close() // close the database connection if application errored.

	sess := sessions.New(sessions.Config{
		Cookie:       "sessionscookieid",
		Expires:      45 * time.Minute, // <=0 means unlimited life. Defaults to 0.
		AllowReclaim: true,
	},
	)

	//
	// IMPORTANT:
	//
	sess.UseDatabase(db)

	SessionStorage=sess
	log.Info().Msg("Session Storage initialized")
}
`
I init in handler that way:
`
// GetIndexHandler handles the POST: /
func PostLoginHandler(ctx iris.Context) {
	user := ctx.FormValue("login-username")
	pw := ctx.FormValue("login-password")
	ctx.Application().Logger().Info("User:", user)
	ctx.Application().Logger().Info("PW:", pw)

	token := &authResponse{}

	token, err := Auth(user, pw)

	if (token.Status != "OK" || err != nil) {
		ctx.ViewData("Title", "LOGIN FAILED")
		ctx.ViewLayout("shared/account.html")
		ctx.View("account/login.html")
	} else {


		ctx.SetCookieKV("refresh",token.Refresh)
		ctx.SetCookieKV("access",token.Access)

		//session := storage.GetSession(ctx)
		session:=storage.SessionStorage.Start(ctx)
		session.Set("user",user)

		ctx.Redirect("/", iris.StatusSeeOther)

	}

}`

and get eg here:

`
// GetIndexHandler handles the GET: /
func GetIndexHandler(ctx iris.Context) {

	session := storage.GetSession(ctx)
	u:=session.GetString("user")

	fmt.Println(session)



	ctx.ViewData("Title", u)
	ctx.View("index.html")
}
`
repeating. 
- This works fine with not using Database.
- No error with Redis, but also empty on Get "user" but session object is there somehow (&{0a8cedf9-0526-41a3-8415-cc2beb960360 false map[] {{0 0} 0 0 0 0} 2018-08-31 16:33:24.119503987 +0200 CEST m=+2704.572051512 0xc4201fc800})
- error mentioned above using Badger as Session Storage

**Comment by kataras** [comment]
Man please re-edit your post to be more readable.

**Comment by stefanwuthrich** [comment]
tks for the link ;-)
about **what in the hell is that**.... that's code I copied from one of your examples.
```golang
// GetSession to return the session
func GetSession(ctx iris.Context) *sessions.Session {
	return SessionStorage.Start(ctx)
}
```
If I do it the direct way it's exactly same problem.

**Comment by stefanwuthrich** [comment]
don't worry. My markdown is not perfect, but I know perfectly that you don't need to give support for free 7/24 hours :-)
I wish you success with the interview.

**Comment by kataras** [comment]
OK, it was simple... on the `InitSession` you `defer db.Close()` so the session database is closed after calling the `InitSession`, the `defer` should go to your `main func` so it will be called on application exit only.

**Comment by kataras** [comment]
This is an alternative you can use for your `InitSession`:

```go
func main(){
   closer := InitSession()
   defer closer() // or just defer InitSession()

  // [...]
}

// [...]
func InitSession() func() error {
	db, err := badger.New("./data")
	if err != nil {
		panic(err)
	}

	iris.RegisterOnInterrupt(func() {
		db.Close()
	})

	sess := sessions.New(sessions.Config{
		Cookie:       "sessionscookieid",
		Expires:      45 * time.Minute, // <=0 means unlimited life. Defaults to 0.
		AllowReclaim: true,
	},
	)
	sess.UseDatabase(db)

	SessionStorage=sess
	log.Info().Msg("Session Storage initialized")

       return db.Close // <- IMPORTANT
}

```

**Comment by kataras** [comment]
Thanks for the nice words @stefanwuthrich , it is possible to provide 24/7 free support, I am doing it for the last 2 years, I was in the interview but not for self-hiring, I was just an adviser for the job interviewer :P

**Comment by stefanwuthrich** [comment]
Thanks so much :-) really kind of a beginner's error from my side.

**Comment by kataras** [comment]
You are very welcomed, thanks for the endorsement at my linked profile as well :)
