### ISSUE TITLE
How to integrate swagger-ui?

### ISSUE THREAD

**Issue by zhuxiujia** [kataras/iris#1080]
How to integrate swagger-ui?

**Comment by apehub** [comment]
you can refer to this url: https://juejin.im/post/5b05138cf265da0ba7701a37

**Comment by kataras** [comment]
What do you mean? You have access to the `Request` and `ResponseWriter` via `ctx.Request()` and `ctx.ResponseWriter()`, do it like you do with `net/http`, there are some examples for api documentation, see the `apidoc` example.
