### ISSUE TITLE
the "hero" component not installed when using "dep" to manage project dependencies

### ISSUE THREAD

**Issue by apehub** [kataras/iris#1081]
Hi, i am using "dep" for dependency management in my project, and i add iris in Gopkg.toml like this:

![image](https://user-images.githubusercontent.com/42964918/45131320-f9580d00-b1be-11e8-8373-54c0f8950f32.png)

![image](https://user-images.githubusercontent.com/42964918/45131037-c06b6880-b1bd-11e8-8685-e49e84ba95b4.png)

and later i use "dep ensure -v" to download all the dependencies. 
after the "ensure" command finished,  i check the downloaded files in "vendor/github.com/kataras/iris/hero" folder, i found there is no source code files were downloaded, refer to the screen capture bellow: 

![image](https://user-images.githubusercontent.com/42964918/45131147-3bcd1a00-b1be-11e8-8bd7-d5a71904b6cb.png)

so i cannot use "hero" component in my project.

![image](https://user-images.githubusercontent.com/42964918/45131237-a1210b00-b1be-11e8-89f2-69d3104857f6.png)

could anybody tell me how to solve this issue?

thanks ~

**Comment by kataras** [comment]
Sorry, I don't use `dep` and will never do, you can post that issue to their repository and if you find a solution then post it back here. However I recommend you to test it on a clean gopath (if you use gopath), Iris is OK with the new `go mod` and for go versions lower than 1.11 iris is coming with the `vendor` folder. This cannot be an Iris issue at all.
