### ISSUE TITLE
Support zerolog for Logger

### ISSUE THREAD

**Issue by codenamoo** [kataras/iris#1083]
Hello,
It would be nice If could be use [zerologger](https://github.com/rs/zerolog) by default Logger. (and/or I hope golog support JSON output.)
Or is there a good way to print out log as JSON like   {"level":"info","time":"2018-09-07T16:55:15.379094292+09:00","message":"Now listening on: http://localhost:8080"} ?

Thanks.

**Comment by kataras** [comment]
Hello, yes you can output `JSON form` or any other you want using the `golog#Handle` function to handle the log message and customize the output, an example can be found [there](https://github.com/kataras/golog/tree/master/_examples/customize-output). [golog](https://github.com/kataras/golog) can use integrations with the `golog#Install` function, see for example the [logrus integration](https://github.com/kataras/golog/blob/master/_examples/integrations/logrus/main.go). However, if you need to use any other logger that is not compatible with `golog` or `io.Writer` then you can just disable the iris' logger and make use of an external logger by yourself.
