### ISSUE TITLE
master branch bug -- party.go:252: no new variables on left side of :=

### ISSUE THREAD

**Issue by kabutoL** [kataras/iris#109]
I want to get iris,find this bug.develop branch is right,but master branch has error.like that:
![pic](https://cloud.githubusercontent.com/assets/18158195/15206892/08993772-1855-11e6-9128-edba2039544d.jpg)
![pic2](https://cloud.githubusercontent.com/assets/18158195/15207035/e598b314-1855-11e6-989a-547616b09183.jpg)

**Comment by kataras** [comment]
Yes I know this, changes are maden from master to development branch. I will update it right now, thanks for the report !

**Comment by kataras** [comment]
Fixed, old master renamed to `v2.3.2`, old development renamed to `master` . master branch was only exists for backup no for stability, so I just rename them in order to be not confused, use the master branch now, which is the old development

**Comment by kabutoL** [comment]
Good job.And I have already stared now.It's very good.

**Comment by kataras** [comment]
Nice! I'm waiting to post your features & ideas, this is a community-driven framework Maybe I am the only code contributor  but you're the mind
