### ISSUE TITLE
No matter what I do, I cant seem to send POST content / POSTed JSON to this program

### ISSUE THREAD

**Issue by streetlist** [kataras/iris#1091]
I have no idea why it does not show values for "t","v","p","h","w","l" values

It will never show anything in return. I cant get the raw request body too. Any help please.

i've used Postman too.

https://pastebin.com/raw/H1rZ9LBi

**Comment by kataras** [comment]
Try to capitalize the struct's fields. Also read this post as well: https://github.com/kataras/iris/issues/1043
