### ISSUE TITLE
hello ，My friends and I started a Chinese iris community

### ISSUE THREAD

**Issue by BreathYu** [kataras/iris#1093]
Hey again Our developers are developed by Aiarron of the frontend developer, Desmond and ZRothschild and Yusn of the backend developer. We have jointly developed the Go Web Iris Chinese community using the go Iris framework.

And for https://docs.iris-go.com/ this document is translated from English to Chinese, and we will also translate other documents and promote it in the go development community in China, so that more people It's easier to learn Iris, and we hope that more people will use it than it is to be good with Iris.

**Comment by breathYu** [comment]
The website address is https://www.studyiris.com/

**Comment by MarkHoo** [comment]
> 网址是https://www.studyiris.com/

注册过于繁琐，应该这样。一个邮箱，输入图形验证码发送邮箱验证码，两次密码。注册完成。用户名看用户自己是否想设置，可以在登录后设置，要是不设置就默认邮箱登录。

**Comment by venjiang** [comment]
> The website address is https://www.studyiris.com/

支持

**Comment by dempsey-ycr** [comment]
got it. stared

**Comment by pihao** [comment]
@BreathYu @MarkHoo @venjiang @dempsey-ycr 
https://github.com/julienschmidt/httprouter/issues/148

**Comment by colorworlds** [comment]
The document needs to be updated.
https://www.studyiris.com/doc/irisDoc/Installation.html

This commond is out of date:
$ go get -u github.com/kataras/iris
It will cause the issues:
https://github.com/kataras/iris/issues/1421
like this:
go/src/github.com/kataras/iris/view/jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion

**Comment by kataras** [comment]
Yes @colorworlds, the Chinese documentation is not updated yet (you can help  by forking the https://github.com/kataras/iris/wiki). However, the english one is available and you can request a PDF and EPUB formats from: https://bit.ly/iris-req-book

**Comment by colorworlds** [comment]
the @snowlyg contribute a chinese  documentation for new version at:
https://learnku.com/docs/iris-wiki/v12/
he has finished half of it  recently,I think he's translation will be completed eventually .
And I will provide a simple login demo with chinese comment in future

**Comment by PCanyi** [comment]
> Hey again Our developers are developed by Aiarron of the frontend developer, Desmond and ZRothschild and Yusn of the backend developer. We have jointly developed the Go Web Iris Chinese community using the go Iris framework.
> 
> And for https://docs.iris-go.com/ this document is translated from English to Chinese, and we will also translate other documents and promote it in the go development community in China, so that more people It's easier to learn Iris, and we hope that more people will use it than it is to be good with Iris.

赞同，IRIS的文档写得太差了。问个问题，GetByWildard如何使用？找不到示例，也用不成功。

**Comment by snowlyg** [comment]
> > Hey again Our developers are developed by Aiarron of the frontend developer, Desmond and ZRothschild and Yusn of the backend developer. We have jointly developed the Go Web Iris Chinese community using the go Iris framework.
> > And for https://docs.iris-go.com/ this document is translated from English to Chinese, and we will also translate other documents and promote it in the go development community in China, so that more people It's easier to learn Iris, and we hope that more people will use it than it is to be good with Iris.
> 
> 赞同，IRIS的文档写得太差了。问个问题，GetByWildard如何使用？找不到示例，也用不成功。

@PCanyi  看我翻译的 v12 版本的中文文档，如果还不清楚可以加我的 qq 交流群交流 ：676717248
https://learnku.com/docs/iris-wiki/v12/mvc/7013

**Comment by BreathYu** [comment]
什么例子，跑不同



发自我的iPhone


------------------ Original ------------------

**Comment by kataras** [comment]
https://github.com/snowlyg/iris/wiki
