### ISSUE TITLE
MVC routing path name

### ISSUE THREAD

**Issue by edwinchana** [kataras/iris#1094]
I want to implement uppercase character like this path "${hostname}/organization/bulkLicense"
How to do it In MVC structure? thanks.

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here](https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
func (c *MyController) BeforeActivation(b BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //    keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.
}

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *myController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here])(https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
func (c *MyController) BeforeActivation(b BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //    keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.
}

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *myController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here](https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37)) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
func (c *MyController) BeforeActivation(b BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //   keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.
}

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *myController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here](https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37)) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
func (c *MyController) BeforeActivation(b BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //   keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.
}

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *MyController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here](https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37)) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
func (c *MyController) BeforeActivation(b mvc.BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //   keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.

   // The `BeforeActivation` will be fired automatically by the framework, 
   // you just add this and the `AfterActivation` to your controller and it will take care of your controller.
}

func (c *MyController) AfterActivation(a mvc.AfterActivation) { /* keep it empty if you don't need this*/ }

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *MyController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by kataras** [comment]
You mean: 

```go
app.Get("/{hostname}/organisation/bulkLicense")
```

To:

```go
// it will be: {hostname}/organisation/bulklicense (note the lowercase "l")
func (c *MyController) GetByOrganisationBulklicense(hostname string) {
    // [...]
}
```

If you don't like this behavior you can always inject the controller with `BeforeActivation` (example [here](https://github.com/kataras/iris/blob/master/mvc/controller_handle_test.go#L37)) and add your own naming convesion per route, i.e:

**(read the code snippet's comments)**
```go
import (
   // [...]
   "github.com/kataras/iris/mvc"
)

// [...]

func (c *MyController) BeforeActivation(b mvc.BeforeActivation) {
    b.Handle("GET", "/{hostname}/organisation/bulkLicense", "HostnameOrganisationBulkLicense")
    // - first parameter is the HTTP method, to catch all you can use the "ALL" or "ANY".
    // - second parameter is the request path, like you always do, 
    //   keep note that {hostname} is same as {hostname:string}.
    // - third parameter is the CONTROLLER's FUNCTION NAME WHICH WILL HANDLE THIS REQUEST
    //   you can put any name you want here.

    // The `BeforeActivation` will be fired automatically by the framework, 
    // you just add this and the `AfterActivation` to your controller and 
    // Iris will take care of your controller.
}

func (c *MyController) AfterActivation(a mvc.AfterActivation) { 
    // keep it empty if you don't need this.
}

// naming is up to you when you manually register the function with a route via 
// `BeforeActivation#Handle` (look above)
func (c *MyController) HostnameOrganisationBulkLicense(hostname string) {
    // [...]
}
```

Hope that was helpful enough, if not please post again and I will answer you pretty fast:)

> Pleas star the [iris github repository](https://github.com/kataras/iris/stargazers), I am working on version 11 at "v11" branch and I need support for my time, a star will cost you just 2 seconds. Thank you a lot!

**Comment by edwinchana** [comment]
Got It! This helped me a lot. Thanks
