### ISSUE TITLE
The runtime error showing on terminal is not showing on VS Code's console.

### ISSUE THREAD

**Issue by jaggerwang** [kataras/iris#1097]
## Problem

This makes difficult to debug when run iris app in VS Code.

Error showed on terminal:

![image](https://user-images.githubusercontent.com/1255011/46567039-6d700700-c95d-11e8-9f7e-933ecdc844ac.png)

But not showed on VS Code's console:

![image](https://user-images.githubusercontent.com/1255011/46567062-f9822e80-c95d-11e8-82b2-619472600f59.png)

launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "args": [
                "web"
            ],
        },
    ]
}
```

## ENV

macOS: 10.14
VS Code: 1.26.2
Iris: 10.6.6

**Comment by kickbox** [comment]
This is not related to iris. This is related to vs code and how you have setup your debugger. Try running in regular mode in vs code, you will see the same output..

**Comment by jaggerwang** [comment]
ok
