### ISSUE TITLE
how to get the http multipart/form-data  data format?

### ISSUE THREAD

**Issue by ZRothschild** [kataras/iris#1099]
when i use the http send request  Content-Type is multipart/form-data  example code 
```
package main

import (
	"fmt"
	"net/http"
	"io/ioutil"
	"log"
	"bytes"
	"mime/multipart"
	"os"
	"io"
)
func main()  {
	//创建一个 bytes Buffer   &bytes.Buffer 
	//也可以  buf := &bytes.Buffer{}
	buf := new(bytes.Buffer)
	
	//将bytes Buffer  *Writer
	wr := multipart.NewWriter(buf)
	defer wr.Close()

	//往*Writer写入数据  字符串数据
	wr.WriteField("lang","go")
	wr.WriteField("web","iris")
       //文件上传
	filePath := "/home/zrothschild/testWeb/main.go"
	cf,_ := wr.CreateFormFile("fileName",filePath)
	//打开文件
	of,_ := os.Open(filePath)
	defer of.Close()
	//把文件数据复制进 cf
	io.Copy(cf,of)
	//设置请求数据类型
	ct := wr.FormDataContentType()
	resp, err := http.Post("https://studyiris.com/doc",ct,buf)
	if err != nil {
		log.Printf("resp %s \n",err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Printf("body %s \n",err)
	}
	fmt.Println(string(body))
}
```
Then ，How to receive requested data on the requested interface in the iris framework.
Original use **resp.Body**  to process requests.
but iris i try to use ctx.FormValue,ctx.ReadForm that return empty
so My question is how to get request data with a Content-Type of form-data/multipart/form-data
thanks a lot!

**Comment by syssam** [comment]
please read the document https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go

**Comment by ZRothschild** [comment]
> please read the document https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go

I am sorry to tell you that I have used the example you said and the result is futile.i  mean multipart/form-data.if you not believe you can try

**Comment by syssam** [comment]
@ZRothschild my mistake.
how about this?
https://github.com/kataras/iris/blob/master/_examples/http_request/upload-file/main.gohttps://github.com/kataras/iris/blob/master/_examples/http_request/upload-files/main.go
