### ISSUE TITLE
Please fix this - it causes compilation errors on Travis-ci

### ISSUE THREAD

**Issue by pbberlin** [kataras/iris#110]
There is a syntax error in the master branch.

A simple duplication of code in party.go - Line 252

```
	// Create request handler for serving static files.
	h := fs.NewRequestHandler()

	// Create request handler for serving static files.
	h := fs.NewRequestHandler()

```

I am building an app based on iris.

I know the project is still under development - 
I only beg for syntax correctness.

By the way: I appreciate the overall design of the project.

Kind regards
  Peter

**Comment by kataras** [comment]
Peter, really I can't see the snippet in the code you wrote ... development branch is the main branch that you should use, the master branch( which has no build errors also) is for backup only, no build errors , please try again with ` go get -u github.com/kataras/iris` 

I Thanks you for your interest !!

**Comment by kataras** [comment]
Lol, you have right, the problem is inside master branch, I update it and it remeains.. I will fix it right now , I thanks you for the report! and sorry for the pr also I didn't see it  before
