### ISSUE TITLE
add http method

### ISSUE THREAD

**Issue by ddatsh** [kataras/iris#1102]
postman , http method include

```
COPY/LINK/UNLINK/PURGE/LOCK/UNLOCK/PROPFIND/VIEW
```

```
package main
import (
	"github.com/kataras/iris"
)
func main(){
	app := iris.New()
	app.Any("/", handler)
	app.Run(iris.Addr(":8080"))
}
func handler(ctx iris.Context){
	ctx.Writef("method: %s and path: %s", ctx.Method(), ctx.Path())
}
```

```
curl -X LINK http://127.0.0.1:8080/
Not Found
```

**Comment by syssam** [comment]
These are not standard HTTP METHODS.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by Dexus** [comment]
It's not standard HTTP METHODS but webdav and this may usefull if you build apps that need it. So I would like to vote for an option to enable webdav methodes and other methods that are non standard - but need for special cases.

Regards, Josef

**Comment by kataras** [comment]
Maybe a better feature request before a PR is to initialize support for modifying the HTTP methods that Iris will allow you to register a handler? They live at: https://github.com/kataras/iris/blob/master/core/router/api_builder.go#L25

**Comment by kataras** [comment]
@syssam when version 11 will be released you can do it by:

```go
package main

import (
	"github.com/kataras/iris"
         // import that package as well:
        routing "github.com/kataras/iris/core/router"
)

func init() {
       // or inside your main func, just register them before your `app.Any` call:
        var myCustomMethods :=  []string{"COPY",
		"LINK",
		"UNLINK",
		"PURGE",
		"LOCK",
		"UNLOCK",
		"PROPFIND",
		"VIEW",
        }

        // available for all iris instances.
        routing.AllMethods = append(routing.AllMethods, myCustomMethods)
}

func main() {
	app := iris.New()
	app.Any("/mypath", func(ctx iris.Context) { /*[...]*/})
	app.Run(iris.Addr(":8080"))
}
```
