### ISSUE TITLE
pls fix this bug for 355 line server.go file

### ISSUE THREAD

**Issue by rubinus** [kataras/iris#1107]
[https://github.com/kataras/iris/blob/master/websocket/server.go](https://github.com/kataras/iris/blob/master/websocket/server.go)

this file  355 line  use s.room[to]  ,you are forget to lock

for we test :  concurrent map read and map write，
we modify after ，but for you fix souce code

                 s.mu.Lock()
		room := s.rooms[to]
		s.mu.Unlock()
		if room != nil {

**Comment by kataras** [comment]
Yes, I let it like that because previously we used channel for that. I am so sorry, there is an open PR for that.

Fixed with: https://github.com/kataras/iris/commit/c1bef0919626408844ca16b7753ad8e7ec4ccd25
