### ISSUE TITLE
Can't run under win7 32bit?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#1112]
I run an example. my computer is under win7 ,32bit.

it shows wrong as the following:
 \memstore.go:272:12: constant 18446744073709551615 overflows uint
\memstore\memstore.go:440:19: constant 4294967295 overflows int
\core\memstore\memstore.go:468:9: constant 18446744073709551615 overflows uint

**Comment by kataras** [comment]
Did you want to run a webserver from x32 bit machine? Fine(I highly don't recommend this path) but don't use the methods that requires x64 bit machine. This error is not a surprise for you, read more at: https://golang.org/ref/spec#Numeric_types

**Comment by xpbliss** [comment]
I run every example under the iris's _examples.  It always shows the error.

**Comment by kataras** [comment]
Fixed @xpbliss , see https://github.com/kataras/iris/issues/1118
