### ISSUE TITLE
is there a way to change the prefix of the websocket message tag

### ISSUE THREAD

**Issue by jjhesk** [kataras/iris#1113]
found from `	websocketMessagePrefix          = "iris-websocket-message:"`
as seen in here [the prefix](https://github.com/kataras/iris/search?q=iris-websocket-message&unscoped_q=iris-websocket-message)
What is the best way to change it?

**Comment by kataras** [comment]
This is not shown to your users, I don't understand why you want to change them. There is no easy way for that because both server and client-side uses this prefix,  we have to `fmt.Sprintf` the result of the `websocket.ClientSource` and that will require more time to be executed, there is really no  need for this. If you want to change the prefix, just clone the repository, do your changes and use your repo instead.

**Comment by kataras** [comment]
Update:

I am working on this, we can do it globally but this will affect all your Iris apps (if you have more than one) so I will make the needed changes per-server. Please stay tuned. If you need it I will do it.

**Comment by kataras** [comment]
With the latest Iris version 11.0.1, you can use the `EvtMessagePrefix` webscocket configuration field. In order the client-side to have the same rule you use the `ctx.Write(yourWsServer.ClientSource)`. I've done it without any performance penalties so you should be fine. Thank you @jjhesk 


```go
package main

import (
	"fmt"

	"github.com/kataras/iris"
	"github.com/kataras/iris/websocket"
)

func main() {
	app := iris.New()

	app.Get("/", func(ctx iris.Context) {
		ctx.ServeFile("websockets.html", false) // second parameter: enable gzip?
	})

	setupWebsocket(app)

	// x2
	// http://localhost:8080
	// http://localhost:8080
	// write something, press submit, see the result.
	app.Run(iris.Addr(":8080"))
}

func setupWebsocket(app *iris.Application) {
	// create our echo websocket server
	ws := websocket.New(websocket.Config{
		ReadBufferSize:   1024,
		WriteBufferSize:  1024,
		EvtMessagePrefix: []byte("my-custom-prefix:"), // <- HERE
	})
	ws.OnConnection(handleConnection)

	// register the server on an endpoint.
	// see the inline javascript code in the websockets.html, this endpoint is used to connect to the server.
	app.Get("/echo", ws.Handler())

	// serve the javascript built'n client-side library,
	// see websockets.html script tags, this path is used.
	app.Any("/iris-ws.js", func(ctx iris.Context) {
		ctx.Write(ws.ClientSource) // <- HERE
	})
}

func handleConnection(c websocket.Connection) {
	// Read events from browser
	c.On("chat", func(msg string) {
		// Print the message to the console, c.Context() is the iris's http context.
		fmt.Printf("%s sent: %s\n", c.Context().RemoteAddr(), msg)
		// Write message back to the client message owner with:
		// c.Emit("chat", msg)
		// Write message to all except this client with:
		c.To(websocket.Broadcast).Emit("chat", msg)
	})
}


```

**Comment by jjhesk** [comment]
got it
