### ISSUE TITLE
Dynamic routing issue

### ISSUE THREAD

**Issue by ZRothschild** [kataras/iris#1115]
i need  /test/a-b url how to set format to url . i try /test/{a:string regexp(^[a-z])-b:string regexp(^[a-z])} but that can't work.

**Comment by kataras** [comment]
Here it seems that it is working, I think your mistake is `-b:string regexp(...)` what is that? a typo?

![itworks](https://user-images.githubusercontent.com/22900943/47493586-4c158300-d858-11e8-9404-4ef677c17190.png)
