### ISSUE TITLE
Overflows when build 32 bit app on 64 bit system

### ISSUE THREAD

**Issue by bouroo** [kataras/iris#1118]
Iris-go 11
go version go1.11.1 linux/amd64
When run `GOOS=windows GOARCH=386 go build -ldflags "-H windowsgui" -o dist/apps_x86.exe`
This error appear on terminal
```
# github.com/kataras/iris/core/memstore
/home/kawinv/go/src/github.com/kataras/iris/core/memstore/memstore.go:272:12: constant 18446744073709551615 overflows uint
/home/kawinv/go/src/github.com/kataras/iris/core/memstore/memstore.go:440:19: constant 4294967295 overflows int
/home/kawinv/go/src/github.com/kataras/iris/core/memstore/memstore.go:468:9: constant 18446744073709551615 overflows uint
```

So I try to workaround that with
memstore.go:270
from
```
var maxValue uint = math.MaxUint32
```
to
```
var maxValue uint64 = math.MaxUint32
```

memstore.go:439
from
```
case int:
	if vv < 0 || vv > math.MaxUint32 {
		return def, errFindParse.Format("uint32", e.Key)
	}
	return uint32(vv), nil
}
```
to
```
case int32:
	return uint32(vv), nil
case int64:
	if vv < 0 || vv > math.MaxUint32 {
		return def, errFindParse.Format("uint32", e.Key)
	}
	return uint32(vv), nil
}
```

memstore.go:469
remove
```
case uint:
	if vv > math.MaxUint64 {
		return def, errFindParse.Format("uint64", e.Key)
	}
	return uint64(vv), nil
```

Hope that someone have better solution for this problems.

**Comment by kataras** [comment]
Hello @bouroo, you have right about x32, although the above solution is not the best one but I will accept it because it sovles the issue and it doesn't hurt anyone, these functions are used for the parameter types and most, if not all of the times it is defined as `string` by end-dev or as its type, i.e `{p::uint64}`  for `memstore#Uint64Default`.
