### ISSUE TITLE
render.IsDevelopment parameter has no effect

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#112]
@kataras render.Config of IsDevelopment parameter is True, when I modify the template file, I can not see the new rendering, this is a bug or intentional?

**Comment by kataras** [comment]
@dxvgef No you should see the changes,  I 'm seeing the changes on browser refresh, show me your code in order to help you

**Comment by dxvgef** [comment]
Is app.Config ().Render improper use of it?
``` go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/render"
)

func main() {
	app := iris.New()
	var renderOptions render.Config
	renderOptions.IsDevelopment = true
	app.Config().Render = &renderOptions

	app.Get("/", func (ctx *iris.Context) {
		ctx.Render("index", nil)
	})
	app.Listen(":8080")
}
```

**Comment by dxvgef** [comment]
@kataras Can you reproduce the problem?

**Comment by qskousen** [comment]
@dxvgef try this way instead of using the render.config struct:

```
app.Config().Render.IsDevelopment = true
```

Just tested and it worked for me.

**Comment by dxvgef** [comment]
@kataras Sorry, I did not seriously look at the new version of the changes, copy the old version to the new version of the code, this issue is resolved.
@qskousen Thank you!

**Comment by kataras** [comment]
I gave you an example my friend from my first comment you should take look that :P Welcome, happy codding !
