### ISSUE TITLE
update layout output without restart

### ISSUE THREAD

**Issue by goldalworming** [kataras/iris#1123]
Hi, how do I update output when I change layout.
this is how I usually make rerender without restart. I still didn't found in context how to do this using iris.

func (c *MainController) Rerender() {
        beego.BuildTemplate(beego.BConfig.WebConfig.ViewsPath)
        c.Redirect("/", 302)
}

**Comment by kataras** [comment]
Hi @goldalworming , too much code for that, Iris has a simple function for this. Actually, it is on the **first view example**, I wonder how you couldn't find it but anyway, here it is: https://github.com/kataras/iris/blob/master/_examples/view/template_html_0/main.go#L17

```go
	tmpl := iris.HTML("./templates", ".html")
	tmpl.Reload(true) // reload templates
```

**Comment by goldalworming** [comment]
ok, thank you so much
