### ISSUE TITLE
cannot use jade.Parse

### ISSUE THREAD

**Issue by mlboy** [kataras/iris#1126]
../../../../go/pkg/mod/github.com/kataras/iris@v10.7.0+incompatible/view/pug.go:21:15: cannot use jade.Parse (type func(string, []byte) (string, error)) as type func(string, string) (string, error) in assignment

**Comment by kataras** [comment]
Yes, the author of Jade changed its API, but on iris v11.0.3 we have updated the code for the view engine to accept []byte on the second argument, so just upgrade to latest iris and you will be fine, other solution is to let the iris' vendor directory on v10.7.0 as it is (it contains the old jade lib).
