### ISSUE TITLE
Suggestion: Logging to console on template rebuild?

### ISSUE THREAD

**Issue by qskousen** [kataras/iris#113]
Using the `iris.Config().Render.IsDevelopment = true` option makes it great for working with templates in development, but would it be possibly an aid to log out to the console when a template is rebuilt, similar to how 404's are? This would be able to give a confirmation that your changes were actually rebuilt, and possibly save some hair-pulling.

**Comment by kataras** [comment]
yes you can just do:  ` err :=  ctx.Render("yourfile", yourstruct{})` Render and HTML returns error which are useful if the rebuild fails :)

**Comment by dxvgef** [comment]
@qskousen When ctx.Render () returns an error, you can use ctx.Panic () and return the handler is triggered iris.OnError () processor

**Comment by kataras** [comment]
@qskousen Please close the issue or provide more information if you still having trouble with it
