### ISSUE TITLE
why can't install v11?

### ISSUE THREAD

**Issue by marshalys** [kataras/iris#1132]
I use go get -u github.com/kataras/iris
and the version installed is: github.com/kataras/iris v10.7.0+incompatible

so I use: go get -u github.com/kataras/iris@v11.0.4
and I get this error:
```
go: finding github.com/gavv/monotime latest
go: finding github.com/juju/loggo latest
go: finding github.com/flosch/pongo2 latest
go: finding github.com/kataras/golog latest
go: finding github.com/xeipuuv/gojsonschema latest
go: finding github.com/gopherjs/gopherjs latest
go: finding github.com/iris-contrib/formBinder latest
go: finding github.com/ajg/form latest
go: finding github.com/k0kubun/colorstring latest
go: finding github.com/iris-contrib/httpexpect latest
go: finding github.com/juju/testing latest
go: finding github.com/Joker/hpp latest
go: finding github.com/xeipuuv/gojsonreference latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/crypto latest
go: gopkg.in/russross/blackfriday.v2@v2.0.1+incompatible: go.mod has non-....v2 module path "github.com/russross/blackfriday/v2" at revision v2.0.1
go: finding github.com/juju/errors latest
go: finding gopkg.in/mgo.v2 latest
go: finding github.com/yudai/golcs latest
go: finding github.com/iris-contrib/i18n latest
go: finding github.com/Shopify/goreferrer latest
go: finding github.com/xeipuuv/gojsonpointer latest
go get: error loading module requirements
```
and my go version is:

go version go1.11.2 darwin/amd64

**Comment by kataras** [comment]
@mlboy since you [pushed this change](https://github.com/kataras/iris/pull/1128) to blackfriday, please take a look ^.

**Comment by kataras** [comment]
@marshalys you can install v1 but you must add it inside your `go.mod` file, I am not sure why default go get installs the v10.7.0 instead of the v11 but if you just add the `github.com/kataras/iris v11.0.4+incompatible` inside your **go.mod** file it will work:

```go
module $INSERT_YOUR_MODULE_NAME_HERE

require (
  github.com/kataras/iris v11.0.4+incompatible
  $OTHER_PACKAGES_THAT_YOU_MAY_USE
)
```

**Comment by kataras** [comment]
@marshalys open your `go.mod` file and add the require of `github.com/kataras/iris v11.0.3+incompatible` and run `go build` or `go mod tidy`, it is tested and working, see https://github.com/the-benchmarker/web-frameworks/blob/master/go/iris/go.mod for example.

**Comment by kataras** [comment]
I fixed the issue, so we will not have things like this in the future again, thank you @marshalys for the report. I did test with a test release to a remove, clean machine and my fixes are working for a future release. stay tuned.

**Comment by marshalys** [comment]
ok! thank you
