### ISSUE TITLE
TestMVC

### ISSUE THREAD

**Issue by kingwangboss** [kataras/iris#1134]
![323b437b-d207-4e41-8dd7-b6c060ac5fc6](https://user-images.githubusercontent.com/15963193/48358338-85157a80-e6d5-11e8-9d71-2aa816224476.png)

**Comment by kingwangboss** [comment]
Why not GET?

**Comment by kataras** [comment]
@kingwangboss There is `GET` function, check your editor's settings and try to clear your $GOPATH (if you use)`. We have plenty of examples like [this one](https://github.com/kataras/iris/blob/master/_examples/mvc/session-controller/main_test.go#L9), try to run that.

**Comment by kingwangboss** [comment]
![image](https://user-images.githubusercontent.com/15963193/48417205-201d5b80-e78d-11e8-8498-9573379e3edc.png)
@kataras

**Comment by kingwangboss** [comment]
I need to delete GOPATH?
@kataras

**Comment by kataras** [comment]
I don't know, try to backup your gopath, create a new folder with the same name and re-install iris because the API is there for the last 5 versions of iris, try to run one of the examples I show you as well.
