### ISSUE TITLE
How to bind multi-domain with different router, ssl, and proxies?

### ISSUE THREAD

**Issue by UnionMexicanaDelNorte** [kataras/iris#1135]
Hi guys.

First of all, congratulations for the web framework, is great.

I have 4 domains, and I need a different router for each domain. 

I need it to work with ssl, and port 80 redirect to the secure address. I based on: https://github.com/kataras/iris/issues/482  for the multidomain, and in: https://github.com/kataras/iris/blob/master/_examples/http-listening/listen-tls/main.go#L22 to redirect port 80, however, multidomain works well with ssl, but port 80 always redirects to the same domain, that is:

https://<span></span>one.org   works fine
https://<span></span>two.org   works fine
https://<span></span>three.org   works fine
https://<span></span>four.org   works fine

http://<span></span>one.org   works fine
http://<span></span>two.org   redirect to one.org, must redirect to two.org
http://<span></span>three.org   redirect to one.org, must redirect to three.org
http://<span></span>four.org   redirect to one.org, must redirect to four.org

here my code:

```go

defSubdomain2:= app.Party("two.")
{
   defSubdomain2.Get("/", func(ctx iris.Context) {
		ctx.HTML("<h1>Hello two.org</h1>")
	})
}

defSubdomain3:= app.Party("three.")
{
   defSubdomain3.Get("/", func(ctx iris.Context) {
		ctx.HTML("<h1>Hello three.org</h1>")
	})
}

defSubdomain4:= app.Party("four.")
{
   defSubdomain4.Get("/", func(ctx iris.Context) {
		ctx.HTML("<h1>Hello four.org</h1>")
	})
}

target, _ := url.Parse("https://one.org:443")
go host.NewProxy("one:80", target).ListenAndServe()


targetTWO, _ := url.Parse("https://two.org:443")
targetTHREE, _ := url.Parse("https://three.org:443")
targetFOUR, _ := url.Parse("https://four.org:443")
go host.NewProxy("two.org:80", targetTWO).ListenAndServe()
go host.NewProxy("three.org:80", targetTHREE).ListenAndServe()
go host.NewProxy("four.org:80", targetFOUR).ListenAndServe()

appConf := iris.Configuration{
	DisablePathCorrection: true,
}

app.Run(iris.TLS(":443", "somefile.pem", "otherfile.pem"), iris.WithConfiguration(appConf))
```
Thanks in advance

**Comment by Dexus** [comment]
To make this work, you would have to have an entry with the domain (incl. subdomain) and your own IP address on the system (here Linux /etc/hosts) as far as I remember it correctly.

Note: You have to enter the public IP or the local IP which is to be used for the public IP match.

Example:
```
10.10.0.101    one.org www.one.org
10.10.0.102    two.org www.two.org
10.10.0.103    three.org www.three.org
10.10.0.104    four.org www.four.org

# same for IPv6
```

But it's also possible that I'm wrong, I tried it about 1 year ago, when everything was still smaller.
