### ISSUE TITLE
How to get Context Response Body

### ISSUE THREAD

**Issue by edenzhong7** [kataras/iris#1138]
Hey guys. I want to log the response body. I was using `iris v5` before, at that moment I can use `ctx.Response.Body()` to get. But now I convert to `iris v11`, the `ctx.ResponseWriter()` returns a `context.responseWriter` which without `Body()` method. I found `context.Response_Recorder` has `Body() `method, but I can't convert `context.responseWriter`  to this.

**Comment by kataras** [comment]
Hey @edenzhong7 you can get the response body using the `ResponseRecorder` as you correctly pointed out, you must call the `ctx.Record()`  before you write the body and you can get the response body by `ctx.Recorder().Body()` or ` w := ctx.Recorder()` and `w.Body()` if you set and get the body from the same handler. 

You can also intercept response body, read more at: https://github.com/kataras/iris/issues/1092

**Comment by edenzhong7** [comment]
> Hey @edenzhong7 you can get the response body using the `ResponseRecorder` as you correctly pointed out, you must call the `ctx.Record()` before you write the body and you can get the response body by `ctx.Recorder().Body()` or ` w := ctx.Recorder()` and `w.Body()` if you set and get the body from the same handler.
> 
> You can also intercept response body, read more at: #1092

All right, it works. Thank you very much.

**Comment by kataras** [comment]
You are welcome @edenzhong7 , happy to help!
