### ISSUE TITLE
Can't call Ctx.Exec in mvc

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1141]
I can trigger GetTest and GetTest2 by visiting routes directly, but the Exec seems no effects.

```go
func (c *controller) GetTest() interface{} {
	println("get test")
	c.Ctx.Exec("GET", "/api/v1/example/test2")
	return iris.StatusNoContent
}

func (c *controller) GetTest2() interface{} {
	println("get test2")
	return iris.StatusCreated
}
```

One more question, can we distinguish the visitor is come from between by outside internet visiting and by inside handler calling?

**Comment by kataras** [comment]
@zheeeng You can't because it is not supposed to be used like this inside MVC. You probably want to navigate to `/example/test2`. call `ctx.Redirect` instead, that is the correct way. The `Exec` is created for advanced scenarios.

**Comment by kataras** [comment]
About your second question, yes it is very easy. For example, you can use the `ctx.Values()` to set a status between handlers, so if you call it from inside other handler you fill a key with a "true" value, and make the check on the next executed handler.

**Comment by zheeeng** [comment]
@kataras Actually I want to call another service which is registered in another MVC route. Consider iris has no built-in service concept, I'm seeking a way to call another route's controller and call its service and prevent outside calling.

**Comment by zheeeng** [comment]
I'm building a structure-fractal API service project, each project has their own MVC structure and sub-routes, they are managed autonomous, sometimes I want to call services cross projects.

**Comment by kataras** [comment]
It's done, now you can call `ctx.Exec` from mvc, the issue was the handler index of the middlewares.
