### ISSUE TITLE
iris.Context.Exec doesn't work after adding middleware

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1142]
There is a minimum demo, if replace the default app with a fresh new app, `ctx.Exec` gets work.
```go
func main() {
        // app := iris.New()    works!
	app := iris.Default()

	app.Get("/go", func(ctx iris.Context) {
		ctx.Exec("GET", "/go2")
	})
	app.Get("/go2", func(ctx iris.Context) {
		ctx.JSON(iris.Map{"hello": "world"})
	})

	app.Run(iris.Addr(":8080"))
}
```

**Comment by kataras** [comment]
Both https://github.com/kataras/iris/issues/1142 and this issue was fixed @zheeeng, you found the source of your previous issue by posting this one :)
