### ISSUE TITLE
Hello World example fails for go 11.2 and dep installation

### ISSUE THREAD

**Issue by Yevs** [kataras/iris#1143]
I've installed go via dep:
```
dep ensure -add github.com/kataras/iris
```

Copy pasted an example to `main.go`:
```
package main

import "github.com/kataras/iris"

func main() {
	app := iris.Default()
	app.Get("/ping", func(ctx iris.Context) {
		ctx.JSON(iris.Map{
			"message": "pong",
		})
	})
	// listen and serve on http://0.0.0.0:8080.
	app.Run(iris.Addr(":8080"))
}
```

Then I ran `go run main.go` and received error:
```
# hello/vendor/github.com/kataras/iris/view
vendor/github.com/kataras/iris/view/django.go:225:27: pongo2.RegisterTag(tagName, fn) used as value
vendor/github.com/kataras/iris/view/django.go:253:19: undefined: pongo2.NewLocalFileSystemLoader
vendor/github.com/kataras/iris/view/django.go:258:22: too many arguments in call to pongo2.NewSet
vendor/github.com/kataras/iris/view/django.go:311:22: too many arguments in call to pongo2.NewSet
	have (string, *tDjangoAssetLoader)
	want (string)
```

`go version` prints `go version go1.11.2 linux/amd64`

`Gopkg.toml` content:
```
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kataras/iris"
  version = "11.1.0"
```

[Gopck.lock link](https://pastebin.com/kitEs1kS)

**Comment by kataras** [comment]
Yes, if you remove `go dep` and use `go modules` it is working, if you still using `dep` for whatever reasons you can fix it by copy-pasting these two files inside your $GOPATH/src/github.com/kataras/iris folder: [Gopkg.toml](https://raw.githubusercontent.com/kataras/iris/5bdbffebc8a4a525a9ec8f9d6425fc22f615f03c/Gopkg.toml) & [Gopkg.lock](https://raw.githubusercontent.com/kataras/iris/5bdbffebc8a4a525a9ec8f9d6425fc22f615f03c/Gopkg.lock) and run `dep ensure` again.

**Comment by GustavsR** [comment]
This still keeps failing. Can we expect a fix to use this together with `dep`?
<img width="804" alt="screenshot 2019-02-12 at 10 50 59" src="https://user-images.githubusercontent.com/13051632/52623096-1e5e5380-2eb4-11e9-8319-577280accda7.png">

**Comment by kataras** [comment]
Normally these type of errors is out of my scope with iris, it is indeed external problem but if you have issues with installing iris even with an external tool such as dep I must provide a fix(although, at some point you will have to move forward and use the go modules feature). The fix to this issue would be to fork the external repo to our iris-contrib github organisation and push a custom version of it, this had downsides of users that already use the pongo library for custom functionality(they will have to change the import lath to the iris-contrib/pongo2). If you are ok with this I could start the proccess. Thanks.

**Comment by dongtianyi** [comment]
> Yes, if you remove `dep` and use `go modules` it is working, if you are still using `dep` for whatever reasons you can fix it by copy-pasting these two files inside your $GOPATH/src/github.com/kataras/iris folder: [Gopkg.toml](https://raw.githubusercontent.com/kataras/iris/5bdbffebc8a4a525a9ec8f9d6425fc22f615f03c/Gopkg.toml) & [Gopkg.lock](https://raw.githubusercontent.com/kataras/iris/5bdbffebc8a4a525a9ec8f9d6425fc22f615f03c/Gopkg.lock) and run `dep ensure` again.

@kataras  I still can reproduced this issue after copy-pasting the files you provided

go version:
localhost:sparrow_user tt$ go version
go version go1.11.5 darwin/amd64

localhost:sparrow_user tt$ dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false

![image](https://user-images.githubusercontent.com/2805621/53153436-37bd7900-35f3-11e9-8dbc-6ad0adb57062.png)

![image](https://user-images.githubusercontent.com/2805621/53153462-486def00-35f3-11e9-9a33-0b2c2f1f2247.png)

**Comment by mcsakoff** [comment]
@dongtianyi, this fixed the issue for me:
```toml
[[override]]
  name = "github.com/flosch/pongo2"
  branch = "master"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "11.1.1"

[prune]
  go-tests = true
  unused-packages = true
```

**Comment by phucvinh52** [comment]
@mcsakoff working thank you <3
