### ISSUE TITLE
Html template render to string

### ISSUE THREAD

**Issue by kastmgnru** [kataras/iris#1147]
Hello! Your framework is wonderful!

I had a little problem.
Is there a way to render a page to a variable (string)?

I found this: ctx.RenderStr (https://github.com/kataras/iris/issues/130), but this does not work and gives an error.

So far I can only do so through the standard library "html / template":
`var pageBuff bytes.Buffer`
`if err := testTemplate.Execute(&pageBuff, pageData); err != nil {
    fmt.Println(err)
}`
`res := pageBuff.String()`
, but I have to duplicate all the functions for this (template.FuncMap, etc..)

Is there a standard solution?

**Comment by kataras** [comment]
Hello @kastmgnru , you can use the `app.View` for that.

SExample:  https://github.com/kataras/iris/blob/master/_examples/view/write-to/main.go#L31.

For string you can use a `bytes.Buffer` as the writer and get its `.String()`. Example Code:

```go
        buf := new(bytes.Buffer)
	err := app.View(buf, "email/simple.html", "shared/email.html", mailData{
		Title:    "This is my e-mail title",
		Body:     "This is my e-mail body",
		RefTitle: "Iris web framework",
		RefLink:  "https://iris-go.com",
	})
        stringContents := buf.String()
```

**Comment by kastmgnru** [comment]
Yes, this is exactly what I need. Sorry for not noticing this in the examples. Thank you!

**Comment by kataras** [comment]
Don't worry, you are very welcomed @kastmgnru, don't hesitate to open an issue for further suggestions/bug reports or question!
