### ISSUE TITLE
context.Context interface implementation

### ISSUE THREAD

**Issue by plonter** [kataras/iris#1149]
Hey,
Sorry if this is a dumb one.
As much as I can figure from the documentation, iris/context.Context interface should implement the standard library interface.
However, the standard interface [https://golang.org/pkg/context/#Context](url) seems to define four functions, which are not implemented in Iris's version:
```go
Deadline() (deadline time.Time, ok bool)
Done() <-chan struct{}
Err() error
Value(key interface{}) interface{}
```
What do I miss?
Thanks,
Aviv

**Comment by kataras** [comment]
They did implemented but not in the recent versions after `http/2`. You don't need these after `go 1.8`, **use the ** `ctx.Request().WithContext` (or the deprecated `ctx.Request().Cancel channel ` to forcely close the connection and notify about it on the [ctx.OnConnectionClose[(https://github.com/kataras/iris/blob/master/context/context.go#L232-L251)). 

What do you want to achieve? We have examples for this subject as well.

**Comment by plonter** [comment]
Hey,

I just wanted to use a third party package, [https://github.com/coreos/go-oidc](url), and they used the context interface in their functions.
I know I could just embed types and so on, just was afraid I'm missing something.

Thanks!
