### ISSUE TITLE
Example with custom config not working

### ISSUE THREAD

**Issue by massanchik** [kataras/iris#115]
```
package main

import "github.com/kataras/iris"

func main() {
	config := iris.IrisConfig{
		Profile:            true,
		ProfilePath:        "/mypath/debug",
	}

	api := iris.New(config)
	api.Listen(":8080")
}
```

> ./main.go:11: cannot use config (type iris.IrisConfig) as type *iris.IrisConfig in argument to iris.New

`api := iris.New(&config)`

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x6a097]
> 
> goroutine 1 [running]:
> panic(0x5a71c0, 0xc82000a0c0)
>         /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
> github.com/kataras/iris.(*Iris).DoPreListen(0xc820011d00, 0x65c758, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7)
>         /Users/User/go/src/github.com/kataras/iris/iris.go:232 +0x5f7
> github.com/kataras/iris.(*Iris).openServer(0xc820011d00, 0x65c758, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /Users/User/go/src/github.com/kataras/iris/iris.go:274 +0x83
> github.com/kataras/iris.(*Iris).Listen(0xc820011d00, 0x65c758, 0x5)
>         /Users/User/go/src/github.com/kataras/iris/iris.go:293 +0x8f
> main.main()
>         /Users/User/go/src/treenode/first_iris/main.go:12 +0x108
> exit status 2

`fmt.Println(iris.Version)`

> v3.0.0-alpha.1

**Comment by kataras** [comment]
Please , wait

**Comment by massanchik** [comment]
This works fine:
```
config := iris.DefaultConfig()
config.Profile = true
config.ProfilePath = "/debug"
api := iris.New(config)
api.Get("/", func(c *iris.Context) {
	c.Write("hello %s", "world")
})
api.Listen(":8080")
```
But on /debug page, links (/debug/goroutine, /debug/block, etc) showing content of /debug route

**Comment by kataras** [comment]
It's fixed now, you can use it like you wanted
``` 
config := iris.IrisConfig{
        Profile:            true,
        ProfilePath:        "/mypath/debug",
    }

    api := iris.New(config)
    api.Listen(":8080")


```

**Comment by massanchik** [comment]
you fast as lightning)

**Comment by kataras** [comment]
Nothing special, it was simple but it could take time to code all if else for .(type)  so I decided to search for a third party package, mergo.

Open a new issue for the debug problem you telling me, because I tested it yesterday

**Comment by massanchik** [comment]
ok

**Comment by kataras** [comment]
Thanks you for your issue report !

**Comment by kataras** [comment]
@massanchik  

>But on /debug page, links (/debug/goroutine, /debug/block, etc) showing content of /debug route 

Fix the problem with the debug path also, it was new bug because of the config preparation. Upgrade with `go get -u github.com/kataras/iris`
