### ISSUE TITLE
about ctx.JSON

### ISSUE THREAD

**Issue by CuteLilTwo** [kataras/iris#1153]
When I write the api,and interaction using JSON strings,I want to encrypt the request body,but in "ctx.JSON()",I can't find how to add the encrypt func to encrypt my request body.Could you please tell me how to do this.

**Comment by kataras** [comment]
You are right, in fact, I am working on signing/verification and optional encryption/decryption for Iris' HTTP responses and requests, it will be there on the next version. 

But you don't have to wait me, currently you can't do that from the `ctx.JSON` but you have access to your request body by: `ctx.Request().Body`, take the data, encrypt them and after send them to the client using `ctx.JSON` or `ctx.ContentType("..."); ctx.Write(b)` -- `ctx.JSON` **is not for request body, it is for response**, plesae read the examples.
