### ISSUE TITLE
Gracefully test shutting down

### ISSUE THREAD

**Issue by fduxiao** [kataras/iris#1154]
I've read your example about gracefully shutting down and it works, but I have trouble testing with it. It seems that httptest [starts the application without asking for configuration](https://github.com/kataras/iris/blob/master/httptest/httptest.go#L81) fed to [App.Run](https://github.com/kataras/iris/blob/master/iris.go#L804). 
I've found it impossible to triggle the cleaning up process so I could not test the shutting down process within the unit tests. Neither could this part of code be covered. 
I even tried calling app.Shutdown, making the server run in a goroutine and using a channel waiting for App.Run, but it turned out that I had to press Ctrl+C to send a signal to truely trigger the cleaning up, and it did cover the lines when an error occurred as in the following.
```go
go func() {
	// see its code to see how you can manually create a new file listener, it's easy.
	l, err := netutil.UNIX("./server.sock", 0666)
	if err != nil {
		panic(err)
	}
	wait <- app.Run(iris.Listener(l), iris.WithoutInterruptHandler)
}()

ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
defer cancel()
err := app.Shutdown(ctx)
if err != nil {
	panic(err)
}
// if I have these two lines uncommented, then `<- wait` will never return unless I press Ctrl+C
err = <- wait
t.Logf("%s\n", err)
```
However after I solved the error, it was no longer worked and I'm unable to reproduce the error again(Maybe it could give you several hints about how to give an explicit API to triggle the shutting down process gracefully). Also if I removed these waiting channel, those lines(from shutting down) would never be covered.

What should I do to handle this problem i.e. triggling shutting down process and testing it with coverage ?

P.S.
What if I need the app running in the background so that I can test on the websocket for a long session.

**Comment by kataras** [comment]
> It seems that httptest starts the application without asking for configuration fed to app.Run

Yes, because you can configure it before`app.Run`, see [app.Configure](https://github.com/kataras/iris/blob/master/iris.go#L232).

About the shutdown, look at this test which tests that (i believe) you want: https://github.com/kataras/iris/blob/master/core/host/supervisor_task_example_test.go#L111
