### ISSUE TITLE
Dynamic Path Parameters

### ISSUE THREAD

**Issue by ali-arabshahi** [kataras/iris#1155]
hello
thank you in advanced for great framework.
how can i achieve this:
```
app.Get("/category", GetAllCategory)
app.Get("/category/{catid:int}", GetCategory)
app.Get("/category/{catid:int}/product", GetAllProduct)
app.Get("/category/{catid:int}/product/{pid:int}", GetProduct)
```
i want my routes be link above.for "/category" i get all and for "/category/10" i can get cat by id(10) and so on.if this is not a good a way,is there a better way?
thank you

**Comment by kataras** [comment]
Hello @ali-arabshahi , thank you for your nice words, you are so polite!

There are many examples for dynamic path, including `Parties/Groups` at: https://github.com/kataras/iris/tree/master/_examples/routing/dynamic-path

One way is: `app.Party`: 

```go
cat := app.Party("/category")
cat .Get("/", GetAllCategory)
cat .Get("/{catid:int}", GetCategory)
cat .Get("/{catid:int}/product", GetAllProduct)
cat .Get("/{catid:int}/product/{pid:int}", GetProduct)
```

Another way is: `app.PartyFunc`:

```go
app.PartyFunc("/category", func(r iris.Party){
  r.Get("/", GetAllCategory)
  r.Get("/{catid:int}", GetCategory)
  r.Get("/{catid:int}/product", GetAllProduct)
  r.Get("/{catid:int}/product/{pid:int}", GetProduct)
})

```

**Comment by ali-arabshahi** [comment]
thank you for your answer.
my mistake.should have read examples more carefully

**Comment by kataras** [comment]
No worries @ali-arabshahi , thanks for using Iris!
