### ISSUE TITLE
Websockets Broadcast outside a On() handler?

### ISSUE THREAD

**Issue by howesteve** [kataras/iris#1159]
Hello,

I can't find a way to broadcast a message using websockets outside a Connection.On() handler.

Use case: what if I need to broadcast a server status like every second to some or all clients? That wouldn't be inside a handler because the message wouldn't be inside a Connection.On() handler. 

I think there should be Server.To() function as well. Or am I missing something?

Thanks,
Howe

**Comment by kataras** [comment]
Hi,

Of course there is a `To`, on the [chat example](https://github.com/kataras/iris/blob/master/_examples/websocket/chat/main.go#L58) you can see: 
```go
// where c is the Connection inside `Server#OnConnection`
c.To(websocket.Broadcast).Emit("chat", msg)
```

Yours,
Makis

**Comment by dibyendu** [comment]
Yes this feature would be quite useful in view of the use case @howesteve mentioned. I also felt in need of this once but eventually worked around it by some dirty hack. In fact, the other popular web-socket wrapper library **socket.io** has that too. There are multiple (I found 3) ways of broadcasting/multicasting messages in socket.io:

1. using [socket.broadcast.emit](https://socket.io/docs/#Broadcasting-messages), where `socket` is a connected client socket.

```javascript
var io = require('socket.io')(80);
io.on('connection', function (socket) {
  socket.broadcast.emit('user connected');
});
```
2. [io.sockets.emit](https://socket.io/docs/server-api/#server-sockets), where `sockets` represents a collection of all connected sockets. This is equivalent to `ws.GetConnections()` as mentioned by @howesteve 

```javascript
io.sockets.emit('hi', 'everyone');
```

3. finally there is [io.emit](https://socket.io/docs/#Room-support), where we don't need to rely on any connected socket at all. The server (`io`) silently ignores the broadcasting in case there is no client connected.

```javascript
io.on('connection', function(socket){
  socket.emit('request', /* */); // emit an event to the socket
  io.emit('broadcast', /* */); // emit an event to all connected sockets
  socket.on('reply', function(){ /* */ }); // listen to the event
});
```

This `io.emit('broadcast', 'message');` block could be placed outside the io.on('connection', function(socket){ /* */ })` callback as well.

**Comment by kataras** [comment]
# Update

As of Iris 11.2, this is possible and extreme fast among other libraries. The new websocket module was re-designed. Using the `server.Broadcast` and `server.Ask`. Read its wiki: https://github.com/kataras/neffos/wiki/Broadcast
