### ISSUE TITLE
IRIS support for longer connections is how?

### ISSUE THREAD

**Issue by insionng** [kataras/iris#116]
Fasthttp may exist on the support connection problems, and the IRIS is based on fasthttp.

A friend says that valyala/fasthttp is only suitable for HTTP short connecting scenes, not suitable for the longer connection, or the websocket support.

Then, Iris support for the longer connection in practice how is it?

**Comment by kataras** [comment]
The opossite my friend, check the benchmark suite in the Readme you will see huuuge difference!

**Comment by insionng** [comment]
Yes,  i mean long-pool-connections. Thank you for your explanation.

**Comment by kataras** [comment]
I read a lot of valyala's code but again it's better to ask that in the fasthttp repository [here](https://github.com/valyala/fasthtp/issues), you will get the best answer
