### ISSUE TITLE
concurrency problem on the logger

### ISSUE THREAD

**Issue by chentaosheng** [kataras/iris#1160]
```go
// github.com/kataras/pio/printer.go
func (p *Printer) WriteTo(v interface{}, w io.Writer, appendNewLine bool) ([]byte, error) {
	// ...
	// ...
	_, err = w.Write(b)
	if appendNewLine && err == nil {
		w.Write(NewLine) // we don't care about this error.
	}
	return b, err
}
```

This code calls Write() twice, but it doesn't use mutex.lock(), so it causes concurrency problem.
Sometimes we can get this output:
```
lineline\n\nline\n
```
The correct output should be:
```
line\nline\nline\n
```

**Comment by kataras** [comment]
Yes I see that, thanks for the report however the caller uses mutexes, but if you get this error I will fix it tomorrow. Please the next time try to report bugs on the correct repo, https://github.com/kataras/pio or golog, thanks.

Yours,
Makis

**Comment by kataras** [comment]
Fixed with: https://github.com/kataras/pio/commit/ea782b38602d1e5df3c2b891978a1f80d917a6bd & update gomod with: https://github.com/kataras/iris/commit/b94cb6009fc6c2708d47c507861194faa0c225db.
