### ISSUE TITLE
[Question] Using plain WebSockets with Iris?

### ISSUE THREAD

**Issue by sh7dm** [kataras/iris#1161]
As I have seen, `github.com/kataras/iris/websocket` requires client library for JS. How can I use plain WebSockets (vanilla JS `WebSocket`) with Iris without client-side libraries?

> PS: This framework is really cool!

**Comment by chentaosheng** [comment]
use golang.org/x/net/websocket
see [https://github.com/kataras/iris/tree/master/_examples/websocket/custom-go-client](https://github.com/kataras/iris/tree/master/_examples/websocket/custom-go-client)

**Comment by sh7dm** [comment]
@chentaosheng Thanks a lot! I've also found [this example](https://github.com/iris-contrib/examples/blob/master/websocket/native-messages/main.go)

**Comment by kataras** [comment]
Exactly, nice @sh7dm !
