### ISSUE TITLE
about redis 

### ISSUE THREAD

**Issue by jax1090** [kataras/iris#1163]
I'm try to use redis as session database, but I get an error : 
cannot find module for path github.com/gomodule/redigo/redis

**Comment by kataras** [comment]
That's strange, I've just tested Iris + redis session database on a clean machine and it's working like a charm, the repository of the module is alive as well: https://github.com/gomodule/redigo/ (although we have vendor for safety against upstream deletions too)

**Comment by jax1090** [comment]
hi, I update golang and it' works!
