### ISSUE TITLE
This example Lack of close parenthesis

### ISSUE THREAD

**Issue by liov** [kataras/iris#1164]
app.Get("/static_validation/{name:string has**([kataras,gerasimos,maropoulos]**//there
}", func(ctx iris.Context) {
		name := ctx.Params().Get("name")
		ctx.Writef(`Hello %s | the name should be "kataras" or "gerasimos" or "maropoulos"
    otherwise this handler will not be executed`, name)
	})

**Comment by liov** [comment]
haokeng

**Comment by kataras** [comment]
Thanks @liov, fixed, although you can push a PR, it's OK! Happy new year my friend
