### ISSUE TITLE
Feature: Add `Context#Request#FullRequestPath`

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1167]
Here request having an API that gets the `FullRequestURI` and `FullRequestPath` from `context::Request` for giving the client some hypermedia link information, e.g. the next and previous page link in pagination fields.

I made something to achieve it by myself for reference:

```go
package reqpath

import "net/http"

func GetFullRequestURI(r *http.Request) string {
	scheme := "http://"
	if r.TLS != nil {
		scheme = "https://"
	}

	return scheme + r.Host + r.RequestURI
}

func GetFullRequestPath(r *http.Request) string {
	scheme := "http://"
	if r.TLS != nil {
		scheme = "https://"
	}

	return scheme + r.Host
}
```

```go
import 'reqpath'

// blabla codes

func (c *controller) GetPage2() interface{} {
	return struct {
		next string
		prev string
	}{
		next: reqpath.GetFullQuestURI(c.Ctx.Request()) + "?page=1",
		prev: reqpath.GetFullQuestURI(c.Ctx.Request()) + "?page=3",
	}
}
```

**Comment by kataras** [comment]
Hello @zheeeng, if you are using templates we already have the `{{ url }}` template function which can be more useful and more safe to use for providing full urls to the view, example: https://github.com/kataras/iris/blob/master/_examples/view/template_html_4/templates/page.html#L4.

However, I am not big fun of depend on the `domain` or the `scheme` for your application's actions, instead prefer to use relative paths.

**Comment by zheeeng** [comment]
Ok, I understand your pick.

My situation is that my APIs is not for websites, it is for mobile clients and  I want to provide users with some hyperlinks.

In the website environment, the client can call hyperlink without domain and schema directly coz browser will add them, if the API and website are under the same domain, but mobile won't. Either client have to concatenate domain, schema, and the relative link comes from the response togather, or a reponse comes from servers contains the full heuristic hyperlink.

I personally prefer the later. And in the snippet, the `domain` and `scheme` are calculated from `request`, they are dynamically rather than hardcoding.

**Comment by zheeeng** [comment]
@kataras I found that [Github API v3#link-header](https://developer.github.com/v3/#link-header) response user the full link address with schema and host, it is what I want to achieve as well.

**Comment by zheeeng** [comment]
It seems that the proxy is transparent, even if the user accesses the server through a proxy, the responded full path is a proxied path. It is also ok no matter what the root level domain or subdomain is, it is not bound fixedly.

The example code runs at distributed production servers and QA and testing servers, the parsed path is as expected.

**Comment by kataras** [comment]
Aa I see, you want it at request-time, yes... Sorry, yes we can do that, we already have ctx.Host and ctx.Subdomain and ctx.RequestPatg(parsed bool) or ctx.Path and also ctx.Request().IsTLS() as I remember, I will add this FullRequestURI() feature request.

**Comment by kataras** [comment]
@zheeeng I added this for the next, upcoming `v11.2.0` version but you could already do it by-yourself, Iris is 100% compatible with the `net/http`, therefore here is the small code snippet:

```go
func FullRequestURI(ctx iris.Context) string {
	scheme := ctx.Request().URL.Scheme
	if scheme == "" {
		if ctx.Request().TLS != nil {
			scheme = "https:"
		} else {
			scheme = "http:"
		}
	}

	host := ctx.Host()
	path := ctx.Path()

	return scheme + "//" + host + path
}
```

```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Get("/mypath", func(ctx iris.Context) {
		fullpath := ctx.FullRequestURI()
		ctx.Writef("Request URI is: %s\n", fullpath)
	})

	app.Run(iris.Addr(":8080"))
}

```
