### ISSUE TITLE
Feature: Quicktemplate

### ISSUE THREAD

**Issue by kataras** [kataras/iris#117]
Just finished with html/template & pongo and I'm thinkining to add 
build'n support for [quicktemplate](https://github.com/valyala/quicktemplate) also.

###### Write below your comments, ideas, how you'ld like to use quicktemplate through Iris...

**Comment by peppage** [comment]
I'm looking at using iris with quicktemplates and there are examples that send the fasthttp.RequestCtx to the write func and it works. I tried this but I just get back a page with all the HTML printed as a string. Can I use the write func but get HTML?

```go
iris.Get("/", func(ctx *iris.Context) {
	p := &view.BasePage{}
	view.WritePageTemplate(ctx.GetRequestCtx(), p)
})

iris.Listen(":8000")
```

Thanks.

**Comment by egorsmkv** [comment]
looks like good

**Comment by peppage** [comment]
I forgot the browser doesn't know how to interpret the response without setting the content type. Here is the code people should use if they want to use quicktemplates.

```go
iris.Get("/", func(ctx *iris.Context) {
		p := &view.BasePage{}
		ctx.SetStatusCode(200)
		ctx.SetContentType("text/html")
		view.WritePageTemplate(ctx.GetRequestCtx(), p)
})

iris.Listen(":8000")
```

**Comment by kataras** [comment]
@peppage Correct, you can create a middleware named `htmlMiddleware`and pass the `ctx.SetStatusCode(200);ctx.SetContentType("text/html");ctx.Next()`,a simple snippet of that, exists at the /router.go OR just `ctx.WriteHTML(200,"")` before or after the WritePageTemplate .
