### ISSUE TITLE
Feature: Add applying rules on middleware

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1170]
Can we have a simple way to use a middleware on a specific handler? I made a custom middleware but only want to apply it on `PostUser` handler. Hope there is an approach/ built-in rules configuration to simplify codes below:

```go
func Middleware(ctx iris.Context) {
    ctx.Next()
}

func CreateMiddleware(when func(ctx iris.Context) bool) func(ctx iris.Context) {

	return func(ctx iris.Context) {
		use := when(ctx)

		if use {
			Middleware(ctx)
		} else {
			ctx.Next()
		}
	}
}
```

```go
// In route party 

m := middleware.CreateMiddleware(func(ctx iris.Context) bool {
	handlerNameChunks := strings.Split(ctx.GetCurrentRoute().MainHandlerName(), ".")
	hLen := len(handlerNameChunks)

	return hLen > 0 && handlerNameChunks[len(handlerNameChunks)-1] == "PostUser"
})

app.Router.Use(m)
```

**Comment by kataras** [comment]
A middleware is just a function, if you want to call it you can refer to its variable and call it as you do on the first example: `myMiddleware(ctx); return` <- executed, done.

You think it all wrong my friend, do not depend on the handler name to decide if you want to execute a middleware or not, design your app smarter or make checks based on the `request url, parameters, form data, anything`. Show me more so I can help you, what conditions do you have for executing a middleware or not in that case?

**Comment by zheeeng** [comment]
My controller implemented `GET`, `POST`, `PUT` and `DELETE` method handlers, I want to deny some external network request to access part APIs of them, e.g. modifying operations.
I made a middleware check whether the remote address is of A class network, I want the middleware only be applied to the `POST` and `PUT` methods on `user` route, only allow internal network to change the user status and leave the `GET` method for all requests no matter what kind of network  they are.

**Comment by kataras** [comment]
@zheeeng this doesn't work for you?:

>  Does I have only one way to use a middleware that partyApp.Router.Use(middleware)? 
No, mvc depends on a `Party`, add the middleware there as you normally do, but you can also do it inside your controller, I will show you an example that is doing that thing you want to do:
```go
app := iris.New()
//  @zheeeng I want the middleware only be applied to the POST, PUT and DELETE
// methods on user route...
userRouter := app.Party("/users", func(ctx iris.Context) {
    if method:= ctx.Method(); method == iris.MethodPost || method == iris.MethodPut || method == iris.MethodDelete {
    ctx.Next()
    return
  }
}))
mvc.New(catsRouter).Handle(new(UserController))

app.Run(iris.Addr(":8080"))
```

**Comment by zheeeng** [comment]
Made a high order func helper

```go
package irisutils

import "github.com/kataras/iris"

func CreateConditionalMiddleware(
	middleware func(ctx iris.Context),
	condition func(ctx iris.Context) bool,
) func(ctx iris.Context) {

	return func(ctx iris.Context) {
		pass := condition(ctx)

		if pass {
			middleware(ctx)
		} else {
			ctx.Next()
		}
	}
}
```

**Comment by kataras** [comment]
OK I will name this 'Filter': func(Context) bool, sounds good?

**Comment by zheeeng** [comment]
I'm not good at naming. `filter` or `predicate ` is better than the exampled.
