### ISSUE TITLE
Modular structure similar to Revel modules 

### ISSUE THREAD

**Issue by hypervalley** [kataras/iris#1171]
Is it possible to create a modular structure with Iris Framework similar to the Revel modules, that would share the same configuration and routes? For example, I would like to separate gormcrud and admin "modules" from the core project.
https://revel.github.io/modules/index.html

**Comment by kataras** [comment]
Revel is based on configuration and does not run with `go run main.go` it needs a revel-cli to run an application, this is a design decision that I don't agree in the first place. Iris is a low-level web framework, it is the fastest, modular and you can extend it as much as you want, it is compatible with `net/http` and runs simple as any go program, easy to learn and develop.
