### ISSUE TITLE
data race issue

### ISSUE THREAD

**Issue by jjhesk** [kataras/iris#1173]
WARNING: DATA RACE
Read at 0x00c0002e1378 by goroutine 105:
  github.com/kataras/iris/websocket.(*connection).startPinger.func2()
   ...
 ...

Looks like the error coming from having the request starting from ws upgrade.

**Comment by kataras** [comment]
Modules like websockets are tested on production for over than a year, I don't think we have a data race anywhere, however, can you give me the code that you're using that produces that data race you are saying?

**Comment by jjhesk** [comment]
```go
	// defer common.TryE()
	app := iris.New()
	app.RegisterView(iris.HTML(staticRootPath(), ".html").Reload(false))
	// Register custom handler for specific http errors.
	app.OnErrorCode(iris.StatusInternalServerError, func(ctx iris.Context) {
		// .Values are used to communicate between handlers, middleware.
		errMessage := ctx.Values().GetString("error")
		if errMessage != "" {
			ctx.Writef("Internal server error: %s", errMessage)
			return
		}
		ctx.Writef("Hello world this now..")
	})
	app.Use(func(ctx iris.Context) {
		ctx.Application().Logger().Infof("Begin request for path: %s", ctx.Path())
		ctx.Next()
	})
	//app.Get("/users", ltc.AccountAddressReq)
	apiRoute := app.Party("api.", logThisMiddleware)
	{
		apiRoute.Any("/iris-ws.js", websocket.ClientHandler())
	}
	assetHandler := app.StaticHandler(staticRootPath(), false, false)
	app.SPA(assetHandler)
	//var token_hit = 0
	//token_user := make(chan chatbot.ReferralCode, token_hit)
	app.Get("/", open_file)
	//app.Get("/login", open_file)
	//app.Get("/test_bigbang", open_file)
	app.Get("/index", open_file)
	//app.Get("/about", open_file)
	//app.Get("/buycoin", open_file)
	common.Info("Server is up & running, open two browser tabs/or/and windows and navigate to ")
	// Listen for incoming HTTP/1.x & HTTP/2 clients on localhost port 8080.
	ws_core := websocket.New(websocket.Config{
		ReadBufferSize:    1024,
		WriteBufferSize:   1024,
		EnableCompression: true,
		PingPeriod:        30 * time.Second,
		BinaryMessages:    false,
	})
	//TestSub(app, ws_core)
	StartWebsocket(app, ws_core)
	app.Get("/ws", ws_core.Handler())
	app.Any("/iris-ws.js", open_ws_source)
	app.Get("/_count", getGoroutinesCountHandler)
	app.Get("/_tracestack", getStackTraceHandler)
	app.Run(iris.Addr(portListenAddress()), iris.WithCharset("UTF-8"))
```

StartWebsocket
```

func StartWebsocket(app *iris.Application, ws *websocket.Server) {

	ws.OnConnection(func(c websocket.Connection) {
		var user = &Profile{}
		// go pingConJob(c)
		c.OnDisconnect(func() {
			threadPoolGame.RemoveUserProfile(c.ID())
			test_account_logs(fmt.Sprintf("ID: %s has been disconnected!", c.ID()))
		})
		c.OnPong(func() {
			var m sync.RWMutex
			m.Lock()
			defer m.Unlock()
			c.To(c.ID()).Emit("pong", "")
		})
		c.OnPing(func() {
			var m sync.RWMutex
			m.Lock()
			defer m.Unlock()
			c.To(c.ID()).Emit("ping", "")
		})
}
```

having this and request the client back and forth and it will appears on the race detection.

**Comment by jjhesk** [comment]
@kataras i dont if i have done anything wrong..

**Comment by kataras** [comment]
@jjhesk Can you join to the [iris chat room](https://chat.iris-go.com)? I want to give you a new `websocket/connection.go` to test against, I may found the source of the issue.

**Comment by jjhesk** [comment]
@kataras my connection is really bad here. got email?

**Comment by kataras** [comment]
Yes, my e-mail is public: `kataras2006@hotmail.com`, if you have a reproducable program send it over, otherwise send me your hello and I will send you a modified `websocket/connection.go` to try out @jjhesk

**Comment by kataras** [comment]
@jjhesk does my latest e-mail solves your issue? ( I pushed the same fix for the upcoming v11.2.0)

**Comment by jjhesk** [comment]
@kataras wait a moment. After a series of investigations, I confirmed that there is a bug from using connection that another connection ID is in the middle of emitting message. For example, connection A is emiting message and there is another gorountine occurred the event and need to pick up the connection A to emit message. The race condition will raised in this situation.

**Comment by jjhesk** [comment]
@kataras checked #1175

**Comment by jjhesk** [comment]
WARNING: DATA RACE
Write at 0x00c001439200 by goroutine 698:
  runtime.slicecopy()
      /usr/local/Cellar/go/1.11.4/libexec/src/runtime/slice.go:221 +0x0
  github.com/kataras/iris/websocket.(*messageSerializer).serialize()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/vendor/github.com/valyala/bytebufferpool/bytebuffer.go:73 +0x17b
  github.com/kataras/iris/websocket.(*emitter).Emit()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/emitter.go:37 +0xcf
  github.com/kataras/iris/websocket.(*connection).Emit()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/connection.go:525 +0x8a
  _/Users/hesk/Documents/bigbangsurvivalrun/backendc/main/core_x.EmitToAllSubbed()
      /Users/hesk/Documents/bigbangsurvivalrun/backendc/main/core_x/ws_core.go:418 +0x23d

Previous read at 0x00c001439200 by goroutine 32:
  runtime.slicecopy()
      /usr/local/Cellar/go/1.11.4/libexec/src/runtime/slice.go:221 +0x0
  compress/flate.(*compressor).fillStore()
      /usr/local/Cellar/go/1.11.4/libexec/src/compress/flate/deflate.go:521 +0xe6
  compress/flate.(*compressor).write()
      /usr/local/Cellar/go/1.11.4/libexec/src/compress/flate/deflate.go:552 +0xf8
  compress/flate.(*Writer).Write()
      /usr/local/Cellar/go/1.11.4/libexec/src/compress/flate/deflate.go:709 +0x5c
  github.com/kataras/iris/websocket/vendor/github.com/gorilla/websocket.(*flateWriteWrapper).Write()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/vendor/github.com/gorilla/websocket/compression.go:102 +0x85
  github.com/kataras/iris/websocket/vendor/github.com/gorilla/websocket.(*Conn).WriteMessage()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/vendor/github.com/gorilla/websocket/conn.go:749 +0xe5
  github.com/kataras/iris/websocket.(*connection).Write()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/connection.go:304 +0x103
  github.com/kataras/iris/websocket.(*connection).writeDefault()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/connection.go:316 +0x73
  github.com/kataras/iris/websocket.(*Server).emitMessage()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/server.go:373 +0x254
  github.com/kataras/iris/websocket.(*emitter).EmitMessage()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/emitter.go:32 +0x11e
  github.com/kataras/iris/websocket.(*emitter).Emit()
      /Users/hesk/go/src/github.com/kataras/iris/websocket/emitter.go:41 +0x140
  _/Users/hesk/Documents/bigbangsurvivalrun/backendc/main/core_x.AnnounceProfileUpdate()
