### ISSUE TITLE
How generate static page?

### ISSUE THREAD

**Issue by andyzhou** [kataras/iris#1177]
Now, i use ctx.View(tplFile) for dynamic content, if i want generate static html page from dynamic content with template, what's kind of api support this, thanks.

**Comment by kataras** [comment]
See the `view` examples at: https://github.com/kataras/iris/tree/master/_examples#view. Iris parses the files at initilization, if you don't have any bindings then it's like a static page.

If you want to generate a **static disk file** based on a template then you need a generator, not Iris for this. You can make one of yourself as well using the std package `html/template` or search for generators online, there are plenty of them which can do the job, it's a simple task, see `hugo` for example. Iris is not an "executable application"/cli, is a webframework, a toolkit of packages that you wrote your web app based on.

Yours, Gerasimos.
