### ISSUE TITLE
View problem makes iris not working

### ISSUE THREAD

**Issue by XingFang** [kataras/iris#1179]
vendor/github.com/kataras/iris/view/django.go:225:27: pongo2.RegisterTag(tagName, fn) used as value
vendor/github.com/kataras/iris/view/django.go:253:19: undefined: pongo2.NewLocalFileSystemLoader
vendor/github.com/kataras/iris/view/django.go:258:22: too many arguments in call to pongo2.NewSet
vendor/github.com/kataras/iris/view/django.go:311:22: too many arguments in call to pongo2.NewSet
	have (string, *tDjangoAssetLoader)
	want (string)

I installed iris, but it can't run. Is this a version compatibility issue?
mac os 10.13.6
iris 11.1.1
go 1.11

**Comment by kataras** [comment]
Do a clean of your `go mod cache` and your problem will dissapear, this is not only iris-specific. Your cache is on `$GOPATH/src/pkg/mod/cahe`, if that doesn't work try to backup your `$GOPATH/src` and delete the original folder, do a `go get -u github.com/kataras/iris` or `go build` and you are fine.
