### ISSUE TITLE
Invalid content on links on debug page when custom ProfilePath is set

### ISSUE THREAD

**Issue by massanchik** [kataras/iris#118]
With this setup, links on /debug/pprof works fine
```
	config := &iris.IrisConfig{
		Profile: true,
	}
	api := iris.New(config)
	api.Listen(":8080")
```
But with custom ProfilePath, routes(/debug/block, /debug/goroutine, etc.) not renering. Instead, the contents of /debug page is shown.
```
	config := &iris.IrisConfig{
		Profile: true,
		ProfilePath: "/debug",
	}
	api := iris.New(config)
	api.Listen(":8080")
```
And /debug/pprof/ route is still working, despite the fact that ProfilePath was updated.

**Comment by kataras** [comment]
Should be fixed, upgrade Iris and confirm if that works now please, thanks for the issue report!

**Comment by massanchik** [comment]
Yes, it already fixed! Well done!
I have already told that you fast as lightning?)

**Comment by kataras** [comment]
Ahah yes! But you are faster, you report two bugs, we solve two bugs that exists on iris for more than a week+ !
