### ISSUE TITLE
After replay attack check Need to forward the request to another server

### ISSUE THREAD

**Issue by Wall-ee** [kataras/iris#1181]
hello,every one.
I'm a fresh man of iris user.
recently, we want to use iris as  a  api gatway to host our SaaS service. 
IRIS need to check the Auth and use the information in Http Header to pervent reply attack.

after check the auth and security check, Is there any methods to forward the request to another worker server?
This could be called as a reverse proxy in Nginx.  

The link below showed a proxy example. but hot to use it  in the ctx context ?
Documentation for the Iris project can be found at
https://stackoverflow.com/questions/41143044/golang-reverseproxy-with-iris-go-framework

```
app.Post("/", func(ctx iris.Context){
     check auth and security

      forward (reverse proxy )the request here 
}
```

**Comment by Wall-ee** [comment]
i see. so, is there any method in iris to forward the http request instead of using "net/http" package?

**Comment by kataras** [comment]
We have `Proxy` and `NewRedirection` as well, check more at: https://github.com/kataras/iris/blob/eba6adbd78bb547b220f7fe7fbda331532134e87/core/host/proxy.go#L26-L113
