### ISSUE TITLE
benchmark add koa2

### ISSUE THREAD

**Issue by skyitachi** [kataras/iris#1183]
benchmark examples use express, as we know, in nodejs community, koa is another competitive web framework, I strongly suggest add koa2 benchmark example.
I can add the example, but the benchmark should run in the same hardware

**Comment by kataras** [comment]
I totally agree, but new bevchmarks should contain a new medium article as well. I support your idea, on the benchmarks README.md you can read the steps to reproduce the benchmarks in your own hardware, add the koa framework and write an article with ur account, then, push a PR here with the numbers and I will add the benchmark image. If you dont have time I will do it over the weekend, thanks!!

**Comment by kataras** [comment]
@skyitachi I made some benchmarks locally and it seems that it has almost the same performance as the expressjs which is a lot poorer than Iris or .Net Core, `koa` doesn't come with router but I see the documentation so I used the `koa-router` with `koa`, do you suggest me something else that it's maybe faster? or someone else?

Thanks.
