### ISSUE TITLE
About Session's Path

### ISSUE THREAD

**Issue by live-xy** [kataras/iris#1186]
Now I 'm do a project like google analytics .
it use js to send http request to server.
And server would Set Session for client.
the js's path is like this .   xxxx.com/siteid/1.js
Then... if the visitor visits other website use the js, he also have session .
so ... xxxx.com/1111/  's cookie can't share with xxxx.com/222/

**Comment by kataras** [comment]
So you want to pass the `Cookie{Path:...` by your own, as you tried to do with [this PR](https://github.com/kataras/iris/pull/1185) by changing the current API. We can do it by two ways without introducing a breaking change:

1. Use optional parameters on the `sessions#Start`  to set the cookie, we have already cookie configurations such as `iris.CookiePath, iris.CookieExpires, iris.CookieEncode, iris.CookieDecode` and etc.
2. Make a new function such as `sessions#StartWithPath(.... , path string)`

I see that nobody else did put a comment or ideas, (at least yet), but if you really want it I'll pick it up for the [v11.2](https://github.com/kataras/iris/pull/1175) release which is coming soon. Stay tuned!

Thanks,
Gerasimos Maropoulos

**Comment by live-xy** [comment]
Good! Seems `2\. sessions#StartWithPath(.... , path string)` is the best method for this !
Thx for your work

**Comment by kataras** [comment]
I've added both of them on [v11.2](https://github.com/kataras/iris/pull/1175) :) on `Start` and `Update/ShiftExpiration` as well, examples:

**1.**
```go
sess := sessions.New(sessions.Config{Cookie: "mycustomsessionid"})

func(ctx iris.Context) {
  s := sess.Start(ctx, iris.CookiePath("/yourpath"))
  // [...]
}
```

**2.**
```go
sess := sessions.New(sessions.Config{Cookie: "mycustomsessionid"})

func(ctx iris.Context) {
  s := sess.StartWithPath(ctx, "/yourpath")
  // [...]
}
```

Thank you for your feature request, if you wouldn't mind test it by fetching the `v11.2` PR and give us more feedback if needed
