### ISSUE TITLE
Error handling in MVC mapper functions

### ISSUE THREAD

**Issue by pantonov** [kataras/iris#1187]
Consider the following example:
```go
func (c *TodoController) BeforeActivation(b mvc.BeforeActivation) {
    b.Dependencies().Add(func(ctx iris.Context) (items []todo.Item) {
        ctx.ReadJSON(&items)
        return
    })
}
```
There is no way to process e.g. JSON conversion errors here. What about supporting second `error` return argument (or `int` HTTP error code), just like in normal mapped MVC methods, e.g.:
```go
func (c *TodoController) BeforeActivation(b mvc.BeforeActivation) {
    b.Dependencies().Add(func(ctx iris.Context) (items []todo.Item, err error) {
        err = ctx.ReadJSON(&items)
        return
    })
}
```
when err != nil, status code 400 (+ err.Error() as body) should be sent as HTTP response and MVC method(s) not called.

**Comment by kataras** [comment]
Hello,

This will change the internal dependency injection container I've did a year+ ago but I am open to this proposal and challenge:)  Will try to pick it up for the [v11.2](https://github.com/kataras/iris/pull/1175) release. Stay tuned!

**Comment by kataras** [comment]
@pantonov , I've just **added support for second output of error type for the dynamic dependencies ^** for the upcoming v11.2. Although you could already do that by:

```go
	b.Dependencies().Add(func(ctx iris.Context) (v testCustomStruct) {
		err := ctx.ReadJSON(&v)
		if err != nil {
			ctx.StatusCode(iris.StatusBadRequest)
			ctx.WriteString(err.Error())
                        ctx.StopExecution() // this will stop the execution of a controller's method.
		}
		return
	})
```

**Comment by pantonov** [comment]
@kataras, that was a first thing I've tried, but ctx.StopExecution() by some reason did not work for me in this context. Controller function was called anyway despite ctx.StopExecution(). So I the only options were to pass error in context (or unexported field of testCustomStruct) and check it later in controller method.

**Comment by kataras** [comment]
Yes, this will work on the new version so you should be fine, if you don't mind you could try out the upcoming release by installing the v11.2.0 branch and give me more feedback if needed ( I added a  `_test` for that case though)
