### ISSUE TITLE
Set cookie

### ISSUE THREAD

**Issue by monopollly** [kataras/iris#119]
Hi,

Whats the right way to set cookie?
I need to set unlimited time, secure cookie...
I tried to make this%

```
var cookie fasthttp.Cookie
	cookie.SetKey("token")
	cookie.SetValue("khbdskjdsg.sdgkjhsdfk.sdkghsdgk")
	cookie.SetSecure(true)
	
	c.SetCookie(&cookie)
```

but its not working...
any help?
thank you

**Comment by kataras** [comment]
Hello, did you try to the `cookie.SetExpire()` ?

```go

// SetExpire sets cookie expiration time.
//
// Set expiration time to CookieExpireDelete for expiring (deleting)
// the cookie on the client.
//
// By default cookie lifetime is limited by browser session.
func (c *Cookie) SetExpire(expire time.Time) 
```

**Comment by monopollly** [comment]
@kataras I don't need it, because
 `// By default cookie lifetime is limited by browser session.`

but I need secure cookie, and it doesn't set at all

iris `c.SetCookieKV` is work well, but I think you should make it lifetime by default;)

**Comment by monopollly** [comment]
nope, still nothing

```
cookie := fasthttp.AcquireCookie()
cookie.SetKey("token")
cookie.SetExpire(timee)
cookie.SetValue("khbdskjdsg.sdgkjhsdfk.sdkghsdgk")
cookie.SetSecure(true)
c.SetCookie(cookie)
fasthttp.ReleaseCookie(cookie)
```

**Comment by kataras** [comment]
> iris c.SetCookieKV is work well,
But this function is calling the c.SetCookie, how is that working and the c.SetCookie itself is not? maybe you have to ask this to the fasthttp repository, sessions are based on secure cookies and are working... maybe you have to show me the rest of your code
