### ISSUE TITLE
Possibility to get rid of "Now listening on [...]"

### ISSUE THREAD

**Issue by odiferousmint** [kataras/iris#1191]
Hello. Is it possible to get rid of the following text on startup?

```
Now listening on: http://localhost:8080
Application started. Press CTRL+C to shut down.
```

It would be nice if it could return a type `error` instead and based on that the user could just print whatever he wants as needed.

**Comment by kataras** [comment]
Hey,

> Is it possible to get rid of the following text on startup?

Yes, instead of `app.Run(iris.Addr(...))` you could add the `iris.WithoutStartupLog`. Example:
```go
app.Run(iris.Addr(":8080"), iris.WithoutStartupLog)
```

> It would be nice if it could return a type `error` instead....

The `app.Run` already returns an error as well :)

**Comment by odiferousmint** [comment]
Oh. Thank you! I'll close it then, my bad!
