### ISSUE TITLE
new feature - integrate MQTT

### ISSUE THREAD

**Issue by jjhesk** [kataras/iris#1196]
adding a usable MQTT for better adoptions with the current iris features

design 1 src: https://github.com/VolantMQ/volantmq
design 2 src: https://github.com/hb-go/micro-mq

testing frontend: https://github.com/ssrs100/link2iot

**Comment by jjhesk** [comment]
this is a good idea to help scaling this app to work across many other servers.. lets add this to some point in the future or we can recruit someone who wants to contribute to this project. thanks.

**Comment by kataras** [comment]
This can be done by a higher-level module @jjhesk, it's not a web framework job to implement such this feature. It's better to do it per-functionality, i.e on websocket module we support redis and nats for scaling out (v11.2+). I think we can close this issue, open a github repository and start working there instead, I can provide some help too.
