### ISSUE TITLE
[MVC] Can we use dependencies in middleware?

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1198]
I want to add a session validation middleware for some specific routes, seems the middleware can only access the `Context` not other registered  dependencies.

BTW: MVC route registered `sessons.Sessions::Start` as service. And I want to check a field 'authenticated' if fails middleware redirect client to another route.

1. I have no idea how to use a service outside a controller.
2. I tried registering service in controller's BeforeActivation hook, but failed.

```go
type controller struct {
	Ctx     iris.Context
	Session *sessions.Session
}

func (c *controller) BeforeActivation(b mvc.BeforeActivation) {
	b.Router().Use(func (ctx iris.Context) {
	        fmt.Println(c.Session)    // it's nil
	        ctx.Next()
        })
}

func (c *controller) Get() interface{} {
	fmt.Println(c.Session)  // it's not nil
	return 200
}

```

**Comment by kataras** [comment]
Hello @zheeeng, if a dependency is dynamic, such as session (requires the http context) then it is only filled on the `mvc handler` itself, not the whole route cycle. You are doing it wrongly, use the **BeginRequest** and **EndRequest** to control the serve flow inside a controller.

```go
// [...]

func (c *controller) BeginRequest(ctx iris.Context) {
	fmt.Println(c.Session) // it's NOT nil.
	// Use ctx.StopExecution() to interrupt and not procceed with the 'Get' method.
}

func (c *controller) EndRequest(ctx iris.Context) {}

// [...]
```

Other way, could be to register middleware before the mvc registration, after all the `b.Router()` is just the `Party` that this controller was registered to but I assume that you already know that.

**Comment by kataras** [comment]
However, if all those information above does not satisfy you. I am open to introduce a way in the upcoming [v11.2](#1175) to wrap the existing `b.Router` to something else or create a new method that would be able to register middleware with all controller's dependencies inside (this will have performance cost though, because it will have to execute the binder on every handler at any way)

**Comment by zheeeng** [comment]
`BeginRequest` and `EndRequest` works. I switched to use it as the controller interceptor.

I expected to have the fully featured AOP(aspect-oriented programming) MVC dev experience. 

Above controller level, inject pre-handler and post-handler for all controller methods. in controller level, inject pre-handler and post-handler for some specific methods. And I expected the injected dependencies are accessible in these pre/post-handlers.

**Comment by kataras** [comment]
Injection works inside controller's methods and inside any other regular handler and middleware through [hero](https://github.com/kataras/iris/wiki/dependency-injection), to understand your request, you want controller's router to be able to accept the mvc application's dependencies? You can already do that by:

``go
hero.Register(..dependencies)
```

```go
func (c *Controller) BeforeActivation(b iris.BeforeActivation) {
    b.Router.Use(hero.Handler(mymiddleware))
}
```

^ if that's the case we can "automative" it but I need to understand exactly the request before start coding it @zheeeng 

If you mean that you wants to inject those deps at  `BeginRequest` and `EndRequest` functions input arguments, that's not possible and not recommended at all. The controller's fields-dependencies are available, use them instead.

**Comment by kataras** [comment]
More info at : https://github.com/kataras/iris/issues/1031
