### ISSUE TITLE
can't open /xxx/ path

### ISSUE THREAD

**Issue by sanqi** [kataras/iris#120]
hi,my route code` iris.Get("/xxx/", XXX)`
iris.Config().PathCorrection = false
open the /xxx/ is 404,if open /xxx is ok
how open /xxx/ path?
thank you

**Comment by kataras** [comment]
I shouldn't reply to fake profiles but ok... give me the time to test it

**Comment by sanqi** [comment]
Why not to let user designate to use route path,  "/" or "not /", no default?

**Comment by kataras** [comment]
You mean `http://yourdomain.com` with `PathCorrection = false ` ?

**Comment by sanqi** [comment]
I need my column "news" use "/news/" path, "/api/" not last "/"

**Comment by kataras** [comment]
so you need to manually do it, you can do that I fixed your issue isn't worked?

**Comment by sanqi** [comment]
yes,"/api" not worked,"/news/" is ok

**Comment by kataras** [comment]
seriously? wait then I will fix it now

**Comment by kataras** [comment]
Design your api and don't worry when I finish that I 'm doing right now I will fix it too and commit all the changes, ok?

**Comment by sanqi** [comment]
OK,I will not be worried, Thank you

**Comment by kataras** [comment]
@sanqi Your issue has been solved from the previous commit, please clear your browser history and retry, confirm here if the problem disappears and close the thread, thanks!
