### ISSUE TITLE
websocket: (Default)EvtMessageKey is fixed and can't be changed

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1203]
Hi, the DefaultEvtMessageKey is a fixed value.

But you it should be set by the config of the server, with the option `EvtMessagePrefix`

Thx

**Comment by Dexus** [comment]
To be more clear:

```go
	ws := websocket.New(websocket.Config{
		HandshakeTimeout:  time.Duration(2 * time.Second),
		EnableCompression: true,
		EvtMessagePrefix:  []byte("lss-tools:"),
		MaxMessageSize:    512000,
	})

	// register the server on an endpoint.
	// see the inline javascript code i the websockets.html, this endpoint is used to connect to the server.
	app.Get("/lssws", ws.Handler())

	// serve the javascript built'n client-side library,
	// see websockets.html script tags, this path is used.
	app.Any("/ws.js", func(ctx iris.Context) {
		ctx.Write(ws.ClientSource)
	})
```

the called `ws.js` have always the wrong `EvtMessagePrefix`

**Comment by kataras** [comment]
Hi. Are you sure? I see that it is changed here

**Comment by Dexus** [comment]
yes, i'm sure.

I use it local while developing and with clean cache, and when i'm open the ws.js direct it shows the default. but not the changed as in my code snippet.

**Comment by Dexus** [comment]
I'm sorry, now we found the problem, a thirdparty tool download the script and use it from internal. So it does not got the change.

Problem solved.

**Comment by liuxiaojin93** [comment]
How was the problem solved,I have the same problem,(Default)EvtMessageKey is fixed and can't be changed
