### ISSUE TITLE
how can I set tow single application app.

### ISSUE THREAD

**Issue by robert7git** [kataras/iris#1204]
there is tow "spa" project under go projects 
project directory structure likes below:

goprojectRootDir
  -- app
  -- -- web
   -- -- -- admn
   -- -- -- -- build
   -- -- -- -- -- index.html
   -- -- -- fe
   -- -- -- -- build
   -- -- -- -- -- index.html

how can I set view engin for eath of tow directory(app/web/admin/build/index.html and app/web/fe/build/index.html ).

thanks.

**Comment by kataras** [comment]
In Iris you can register more than one views but in your it is just `HTMLEngine`. The `ctx.View` can map each View Engine based on their extension (i.e `.html` for `HTMLEngine`, `.pug` for `PugEngine`). On your case you just need one `RegisterView` on your `/app/web/`.

You can use many view engines with the same extension/suffix but not with the `ctx.View`, it is not possible, how can it knows what folder to render if you just ask for their `/build.index.html`? . Each View Engine has its own methods for rendering. See [here](https://github.com/kataras/iris/blob/master/view/engine.go#L24)

**Comment by robert7git** [comment]
em, all right.
But I don't want to run registerView on /app/web/,
Its looks Looks weird.
Because, the web directory conents some other uncompiled files,
and golang program just need to run compiled files.
Is there any other way to resolve my problem。
thanks kataras.

**Comment by kataras** [comment]
@robert7git Sorry for the delay but I thought that I covered this. Don't worry about uncompiled files or other type of files, iris is smart enough to cache only templates based on a `extension`, this is why you pass the second argument at `RegisterView(... , ".html")`.

**Comment by robert7git** [comment]
ok, thanks for your answer.
