### ISSUE TITLE
[Request] hybride client browser/nodejs client for websocket

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1206]
Hello @kataras would it be possible to get also a nodejs client for the websocket?
Maybe you can create the iris-ws.js as a hybride for browser and nodejs.

Thx and regards, Dexus

**Comment by majidbigdeli** [comment]
It is very good

**Comment by kataras** [comment]
@Dexus take a look at: https://github.com/kataras/neffos.js, this library will be used inside Iris on the upcoming `v11.2.0` release.
