### ISSUE TITLE
[Context API Request] Add `ReadQuery` for convenient obtain query struct.

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1207]
example code:

```go
type Query structure {
    Foo *string `url:"foo"`
    Bar *int `url:"bar"`
}

// in handler, assume the path is: api.example.com/path?foo=hello&bar=42

func (c iris.Context) {
    q := Query{}
    err := c.ReadQuery(&Query) 
    fmt.Println(c.foo == "hello")  // true
    fmt.Println(c.bar == 42)  // true
}
```

**Comment by Dexus** [comment]
This would be nice if it also support multiple same key values like `?a=car&a=motorcycle`

**Comment by zheeeng** [comment]
> This would be nice if it also support multiple same key values like `?a=car&a=motorcycle`

Yeah, it should depend on that is the structure with 'a' is slice type or not.

**Comment by kataras** [comment]
Hello @zheeeng and @Dexus did you try the `ReadForm`? if it is a get request it should be reading from queries.

**Comment by zheeeng** [comment]
> Hello @zheeeng and @Dexus did you try the `ReadForm`? if it is a get request it should be reading from queries.

Seems that we can't rule the case conversion by tags? I tried `github.com/gorilla/schema` and it satisfies my demands.

**Comment by kataras** [comment]
Done @zheeeng and @Dexus on 11.2.1 as you exactly requested:

```go
ReadQuery // with "url" tag name, strictly as you requested.
ReadForm // stays with "form" tag name, strictly.
```

We have the option which will be able to select either "url" or "form" or "schema" on a new `Context.Bind` as well in order to be able to use the struct for any of those.
