### ISSUE TITLE
html/template: "hello/index.html" is undefined

### ISSUE THREAD

**Issue by vpc123** [kataras/iris#1209]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by vpc123** [comment]
please help!

**Comment by kataras** [comment]
Hello @vpc123, don't worry, help is coming!

We may know what's going on here, it is a general go template thing when you are loading templates from disk files( you can use StaticEmbedded for binary), **so maybe the files are not in the directory of the executable program?** i.e if you register view based on `./templates` then you have to copy that folder near to your executable file. However, If that didn't help you please paste the code snippet below so I can provide you deeper support.

Thanks,
Gerasimos Maropoulos

**Comment by vpc123** [comment]
Hello @kataras 
thank you!  i'am sorry, i use  go1.9,but my  development environment is out of order，so  this is not iris
error.  i am happy you help me so fast. thank you  very much!
