### ISSUE TITLE
route parameter in party error: Method Not Allowed

### ISSUE THREAD

**Issue by superhjw** [kataras/iris#1212]
App = iris.New()
apiV1Routes := App.Party("/api/v1")
apiV1Routes.Post("/{modular}/condition/get", api.ApiUserConditionGet) 

so, error when http.post: http://localhost:1234/api/v1/box/condition/get by chrome: Method Not Allowed
can you check the fucking stupid error

**Comment by kataras** [comment]
Hello @superhjw, I can't re-produce your case, it is working fine here as expected of course.

![1212](https://user-images.githubusercontent.com/22900943/53951685-b2989080-40d7-11e9-819d-faf643849ceb.png)

Please check your code again, maybe you try to send a GET request by accident?
