### ISSUE TITLE
[MVC] using session info in middleinfo and parameters passing among handlers

### ISSUE THREAD

**Issue by bluesky1024** [kataras/iris#1216]
### background
I need to add some public operation before and after every request, which is depended on the session.
### example
I Read the example about middleware giving as follows.
<https://github.com/kataras/iris/tree/master/_examples/mvc/middleware>.
```go
func OverviewBeforeMiddleware(ctx iris.Context){
	fmt.Println("use")
	ctx.Next()
}
func OverviewDoneMiddleware(ctx iris.Context){
	fmt.Println("done")
	ctx.Next()
}
```
```go
app.Use(middleware.OverviewBeforeMiddleware)
app.Done(middleware.OverviewDoneMiddleware)
```

### question
* the middleware handler can only accept the input iris.Context. Is there any possibility the public session be used in the middleware?
* sometimes i want to pass the data handled in the middleware to the controllers' handlers or pass the data handled in the controllers' handlers to the DoneMiddleware. Maybe I can pass param with context, but I don't know if the context used in middleware and controllers' handler is the same one.  Besides, is mvc in iris support to do it with other method?

**Comment by bluesky1024** [comment]
supplement:
according to this issue as follows, the question to passing parameter among handlers is sovled.
<https://github.com/kataras/iris/issues/1180>.

about the first question:
should i register the global  *sessions.Sessions in the middleware package?

**Comment by kataras** [comment]
Hello @bluesky1024 , sorry for the delay.

Yes, the question is already answered on the issue you posted with v11.2.
At your first question, you can register the same `*sessions.Session` in your controller as a field and bind it, we have the [_examples/mvc/session-controller](https://github.com/kataras/iris/tree/master/_examples/mvc/session-controller) example.

**Comment by bluesky1024** [comment]
hello @kataras, thanks for your reply and sorry for not replaying immediately.
As the example shows, the session is registerd in the controllers.  Iris provide the function as follows for registering *sessions.session in UserController.
```go
SessManager = sessions.New(sessions.Config{
	Cookie:  "my_session",
	Expires: 24 * time.Hour,
})
app.Register(SessManager.Start)
app.Handle(new(controllers.UserController))
```
However, i want to use the sessions in the middleware. Is middleware before the controller able to register the same session with some function in iris?

**Comment by kataras** [comment]
You can call `.Start` many times, you can store the variables in the `Context.Values().Set/Get`, you can create a middleware which accepts a `Session` dependency using the [hero dependency container](https://github.com/kataras/iris/tree/master/_examples/hero/sessions), so yes you can pass it in middleware as well.
