### ISSUE TITLE
Binding to 0.0.0.0 always defaults to localhost.

### ISSUE THREAD

**Issue by Anruin** [kataras/iris#1217]
All my tries to add 0.0.0.0 as a listen address led to nothing. Iris counts it as loopback address and replaces it with localhost. Because of that I can not use the web server in docker container, where I do not know public IP. I want to listen to the 0.0.0.0. Because IRIS makes it loopback, I can not reach it from public networks. I tried to override it somehow, but all possible tries led to nothing. I'm very dissapointed with the framework. In the documentation you have plenty of examples where you bind to 0.0.0.0, but it just does not work.

**Comment by kataras** [comment]
@Anruin You can by-pass the Iris' defaults and use a custom `http.Server` with `iris.Server(srvInstance)` or even a custom `net.Listener` with `iris.Listener(netListener)` as well, check the [_examples/http-listening](https://github.com/kataras/iris/tree/master/_examples/http-listening) examples. i.e:

```go

// create any custom tcp listener, unix sock file or tls tcp listener.
l, err := net.Listen("tcp4", "0.0.0.0")
if err != nil {
	panic(err)
}

// use of the custom listener.
app.Run(iris.Listener(l))
```

If you are running behind unix you can also make use of the port reuse feature, check [here](https://github.com/kataras/iris/blob/master/_examples/http-listening/custom-listener/unix-reuseport/main.go).

**Comment by Anruin** [comment]
Thank you, but what is the logic behind such a design to default everything to a "localhost", even 0.0.0.0? And why in every bit of example and documentation you are saying that empty address will be count as 0.0.0.0?

**Comment by kataras** [comment]
@Anruin Why you'd say something like this? It doesn't bind everything to localhost, it works exactly like the `net/http`.... `:80` or `:http` is the same as `0.0.0.0:80`. Maybe you are confusing it with the log output `Now listening on: domain` ? I tested your case on docker and it works as expected. Please give me more info, did you really try to request a docker local ip and you couldn't because of the log output..?
