### ISSUE TITLE
Is it possible to make app.Run blocking?

### ISSUE THREAD

**Issue by odiferousmint** [kataras/iris#1218]
Hello.

Is it possible to make app.Run blocking? If not, how do I know if it started? Checking the return value of app.Run isn't sufficient. :/

**Comment by kataras** [comment]
Hello @odiferousmint  `app.Run` is blocking, it is always running if it does not return with an error immediately, like the `net/http#Server.ListenAndServe` you already familiar.

**Comment by kataras** [comment]
Note: Sorry for the delay but I am very sick as I wrote in the [chat](https://chat.iris-go.com).
