### ISSUE TITLE
URL Path related question

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#122]
My objective is to somehow make the following URL examples work:
```
http://localhost:1234/details/Gyakuten Saiban: Sono "Shinjitsu", Igi Ari!
```

```
http://localhost:1234/details/Sakamoto desu ga?
```
The route is defined as:
```go
iris.Get("/details/:Name", routeDetails)
```
Since they have characters like " and ? I am a little confused as to what would be the best approach to get the parameter value without it getting damaged?

I've tried QueryEscape and QueryUnescape from net/url lib and it seems to work.

Ps. I know this is a side question, but can anyone of you or @kataras tell me how I should sanitize this parameter value without losing important details?

Thanks

**Comment by kataras** [comment]
Thanks for the issue and thanks for solving it also!  It's a special-case issue, this is the way URIs works, **but if someone has a better solution write below please!**
