### ISSUE TITLE
does iris supports for GlobalHandle,just likes java struct2 filters?

### ISSUE THREAD

**Issue by sanqingshan** [kataras/iris#1221]

**Comment by WuJiY** [comment]
using middleware?

**Comment by kataras** [comment]
Hello, sorry for the delay I am very sick. It is the [app.UseGlobal](https://github.com/kataras/iris/blob/master/core/router/api_builder.go#L488).

**Comment by sanqingshan** [comment]
> Hello, sorry for the delay I am very sick. It is the [app.UseGlobal](https://github.com/kataras/iris/blob/master/core/router/api_builder.go#L488).

thanks very much,I want to send you my best wishes for your quick return to good health.
