### ISSUE TITLE
How do I keep data (iris.Map) to next request via "redirect"?

### ISSUE THREAD

**Issue by hypervalley** [kataras/iris#1222]
Dear friend. I have studied Golang and tested the excelent Iris framework and found a problem, possibly trivial. I need to redirect a record update request to edit page, after field validation error occurrence. However, when using mvc.Response{Path: /admin//user/"+id+"/edit"} , I can not pass the error messages. I tried to put it in the "iris.Context", however, as you would expect, it gets lost from one request to another. What must I do?

Code (partial):
<pre>
func (c UserController) Edit(id string, ctx iris.Context) mvc.Result {	
    data := make(iris.Map) 
    var user gormmodels.User
    var userDao gormmodels.UserDao    
    (...)    
    dbGorm := ctx.Values().Get("db")
    db := dbGorm.(*gorm.DB)
    userDao.SetDb(db)
    userDao.First(&user, id)
    data["user"] = user    
    (...)    
    return mvc.View{
        Name: "admin/user/edit.html",
        Data: data,
    }    
}

func (c UserController) Update(id string, ctx iris.Context) mvc.Result {	
    data := make(iris.Map) 
    request := ctx.Request()
    request.ParseForm()
    var user gormmodels.User
    var userDao gormmodels.UserDao
    var userRequest requests.UserRequest       
    (...)    
    if messages, err := userRequest.ValidateAndPop(&user, request); err != nil { 
        _ = err
        data["user"] = user 
        data["messages"] = messages
        return mvc.Response{Path: /admin//user/"+id+"/edit"}  
        // HOW DO I KEEP DATA (iris.Map) TO NEXT REQUEST VIA "REDIRECT"?
    }    
    (...)    
    dbGorm := ctx.Values().Get("db")
    db := dbGorm.(*gorm.DB)
    userDao.SetDb(db)
    userDao.Update(&user)    
    return mvc.Response{Path: "/admin/user/page/1"}     
}
</pre>

Regards.

**Comment by kataras** [comment]
Redirect is a new http request, you can't save it to context's temp request storage as you already mention, if the data are needed only to the next request then you should use **flash messages**, if you want the data to be alived until user logoff then you should use cookies or sessions. I suppose you want to use flash messages, I am sure you heard those in your previously experience (i.e PHP). 

Iris' session managment supports flash messages. See the [_examples/sessions/flash-messages](https://github.com/kataras/iris/blob/master/_examples/sessions/flash-messages/main.go), you can do the same with controllers*.
