### ISSUE TITLE
Possible to define custom websocket Connection ID and use same after reload page?

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1223]
Hi, 

I can not find documentation, so asking.

Is it possible to provide self-created "ConnectioID" for the user in WebSocket?

Like:-
```
ws.OnConnection(func(c websocket.Connection) {
    c.ID = 'UserB' // or any unique username
})
```

**Purpose**: To check "2nd user" in "2 user room" is online.

**_UserA_** and **_UserB_** has one chat room => **ABRoom**

Now **_UserA_** sends a message in **ABRoom** => How to find if **_UserB_** HasJoined "**ABRoom**" and listening to message?

**Possible** = `c.server.IsJoined("ABRoom", "UserB")` ?? 

( source - https://sourcegraph.com/github.com/kataras/iris@8a34743b0002e1ee600b3b387ec1e9a496e0ddde/-/blob/websocket/connection.go#L545 )

**Comment by rebootcode** [comment]
How is Connection ID generated in "web socket"?

Can we override that?

**Comment by StarMonk** [comment]
+1 very much needed

**Comment by rebootcode** [comment]
@kataras - Possible to set "**Custom**" IDGenerator on Fly **For Each** Connection?

something like this:-
```
Username := sess.Start(ctx).GetString("username") // getting this from Username

ws := websocket.New(websocket.Config{
	IDGenerator: UserName // here Username is taken from Session?
	EnableCompression: true,
})
```
 
Possible something like above?

**Comment by kataras** [comment]
It's already there, even in the current v11.1.1 version of websocket module: https://github.com/kataras/iris/blob/6c054a9b5516583c03454c649143917444507bd8/websocket/config.go#L55

The [new](https://github.com/kataras/neffos.js) library that it's coming with Iris [v11.2.0](https://github.com/kataras/iris/tree/v11.2.0/_examples/websocket/basic) has that too.
