### ISSUE TITLE
Iris is the fastest web framework

### ISSUE THREAD

**Issue by andersfylling** [kataras/iris#1225]
![Go web framework comparison](https://i.imgur.com/tgv7I8i.png)

To avoid confusion and being misleading it would help to update the README with the new picture to correctly display performance numbers. And update the GitHub project description.

**Comment by kataras** [comment]
Hello @andersfylling 

The current github's README shows exactly the same information. Your screenshot shows exactly the same thing, Iris is the fastest **web framework** written in Go. Muxie (created by me as well it's router, and fasthttprouter is a router based on fasthttp, not `net/http` so these two are not considered as web frameworks). Please try to put your hate somewhere else, you are not missleading developers like this, we can see the picture :)
