### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#123]
Hi, @kataras  

Firstly, thank you for a good project!
And now for the problem.

Now the framework sends the wrong file type header, are examples:

```
curl --head http://127.0.0.1:8080/assets/css/bootstrap-theme.min.css

HTTP/1.1 200 OK
Server: iris
Date: Sun, 15 May 2016 22:06:53 GMT
Content-Type: text/html; charset=UTF-8
```

And

```
curl --head http://getbootstrap.com/dist/css/bootstrap.min.css
HTTP/1.1 200 OK
Date: Sun, 15 May 2016 22:07:09 GMT
Content-Type: text/css
Connection: keep-alive
Set-Cookie: __cfduid=df44a897753c29c6b6bd8867e74f797651463350029; expires=Mon, 15-May-17 
...
```

Header `Content-Type` is incorret.

**Comment by kataras** [comment]
yes, the first content type is wrong, can you show me the code you're serving the css?

**Comment by egorsmkv** [comment]
```
// Register static folder
iris.Static("/assets", "./resources", 1)
```

**Comment by kataras** [comment]
Go to the examples, download it and tell me if that works on you ( I just test it) , if that works then you should give me your project structure in order to help you

**Comment by egorsmkv** [comment]
I looked through the browser inspector, in it correct type. So the error due to the ``HEAD``-send request.

![screen02](https://cloud.githubusercontent.com/assets/7875085/15277255/43747bc2-1b07-11e6-8c82-03b88ea7d5b6.png)

**Comment by kataras** [comment]
Yes because the Static func add this only to the Get method, do you suggest provide both GET and HEAD methods to the Static func also?

**Comment by egorsmkv** [comment]
I think yes, this is the logic.

**Comment by kataras** [comment]
You're right, 'fixed'. 
Thanks for your comments, don't hesitate to post another, 
 hope you the best experience with Iris!

**Comment by egorsmkv** [comment]
I'm writing it on the rating of mobile sites. Therefore, the experience becomes more and more.

**Comment by egorsmkv** [comment]
Where a mistake.

When the ``HEAD`` request begins to increase memory.

**Comment by kataras** [comment]
what do you mean, it was a mistake we add HEAD to static ? Should I revert/remove the changes for static serving +HEAD ?

**Comment by egorsmkv** [comment]
See code in the archive.

I'm use this command for test.

```
curl http://127.0.0.1:8080/assets/css/style.css
```

[head-iris-bug.zip](https://github.com/kataras/iris/files/265349/head-iris-bug.zip)

See screenshot.
![screen03](https://cloud.githubusercontent.com/assets/7875085/15277633/dbbdfb3c-1b12-11e6-9dfc-b27f0896f18c.png)

**Comment by kataras** [comment]
OK I removed the HEAD, update with ` go get -u github.com/kataras/iris` and  test it again on your pc , I'm waiting for the results.

**Comment by egorsmkv** [comment]
Now there is no problem. Thank you!

**Comment by kataras** [comment]
I thanks you, good job
