### ISSUE TITLE
When can it provide a response interceptor?

### ISSUE THREAD

**Issue by BambooZhang** [kataras/iris#1230]
When can it provide a response interceptor?
It currently provides some request interceptor(BefoureRequest,EendRequest.etc), but when we need to intercept the returned data, it does not provide a corresponding method. Therefore, I modified the source code by myself. I added a property in the router to save the interceptor instance I wrote for the context. It used the callback interception method in the JSON method in the context and wrote it back to the io.writer.

i just modify thos files:
github.com/kataras/iris/
|-core/router
|-------router.go
|-context
|-------context.go
|-------handler.go

**Comment by kataras** [comment]
Iris gives you the tools to modify any `context`'s methods without touching its source code. Take a look at: https://github.com/kataras/iris/tree/master/_examples/routing/custom-context
