### ISSUE TITLE
Integration with swag

### ISSUE THREAD

**Issue by lightglitch** [kataras/iris#1231]
It would be nice to integrate with https://github.com/swaggo/swag like other frameworks.

**Comment by kataras** [comment]
Hello @lightglitch, I see that the same author is responsible for its integration to various web frameworks. Therefore, can you ask this feature on the `swaggo/swag` repository maintainer instead? If you get no answer in a week I will implement it by looking how he made other framework's integrations.

**Comment by kataras** [comment]
Hello @lightglitch , as promised, here you are: https://github.com/iris-contrib/swagger

**Comment by lightglitch** [comment]
Thx, I also did an integration this weekend and was going to release it. No need now. Thanks, again.

**Comment by kataras** [comment]
You are very welcomed!
