### ISSUE TITLE
Where do you buy your github stars?

### ISSUE THREAD

**Issue by jash11** [kataras/iris#1233]
Hello, I am looking to start my own github project, but I need some stars.

Just out of curiosity, where do you buy your github stars from?

**Comment by majidbigdeli** [comment]
@jash11  Do not you think that you are disrespectful to this project?
I'm really sorry for you.

**Comment by deeper-x** [comment]
Hi @jash11 

every question deserves an answer. This is what you're searching for:
 
[https://bit.ly/K304Lp](url)

Enjoy your stars!

**Comment by deeper-x** [comment]
Hi @jash11

every question deserves an answer. This is what you're searching for:

https://bit.ly/K304Lp

Enjoy your stars!

**Comment by kataras** [comment]
It seems that you have a lot of fantasy by reading fake news about Iris. There is no way to buy those things, but you can build a community by building something unique and useful to others. Hard work is the only  way you can achieve something close to projects like Iris and moby.

**Comment by abteilung6** [comment]
There are several shops like [Github24](https://github24.com) (proofed) and gimhub where you can get followers and Stars.. 

But this ist disrespectful for this project.

**Comment by baddhidurgarao** [comment]
[Buy Github Stars](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop, they're providing high quality service with speed delivery.

**Comment by linta-cat** [comment]
[Buy GitHub Stars](https://github24.com/) from Github24. Look at my hairs they don't lie <3

**Comment by baddhid** [comment]
[Buy Github Followers](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop, they give non drop guaranteed followers and stars.

**Comment by AJLyf** [comment]
[Buy Github Stars](https://likesmagic.com/product/buy-github-stars-forks-watchers-and-followers/) from Likes Magic, they're providing high quality service with speed delivery.

**Comment by danyalahmed1995** [comment]
How about building something useful ?

**Comment by dumbasPL** [comment]
> There is no way to buy those things

That's a lie, I've seen multiple empty (no actual code) repos over the past few weeks that only had a readme pretending to be a video game cheat and linking to malware EXEs. They gained like 100-200 stars in a few hours, diffidently not botted. So it is technically possible, but not recommended since these repos usually don't last more than a few days.

**Comment by mauro-balades** [comment]
Lmfao, what's going on

**Comment by myudak** [comment]
hello reddit

**Comment by mauro-balades** [comment]
How did I end up here

**Comment by crispmfc** [comment]
Lol, github stars man. Its like the nerds gold. Ya cant buy em, but dang, we all want em. Theyre pretty much the Insta likes of the dev world. Quick ego boost but still aint gonna pay the bills. If only I could swap em for some coffee, thatd be a game changer.

**Comment by mauro-balades** [comment]
they may be useless. but in a way, it's also a confidence boost and a "semi-advertiser"

**Comment by YassinEldeeb** [comment]
>There is no way to buy those things

unfortunately, it is possible. A research with real experiments have been done here confirming it: https://the-guild.dev/blog/judging-open-source-by-github-stars

Iris is an amazing project, and I'd never accuse it for such a thing. I fully support the project and the maintainers!

**Comment by sndeshmukh00** [comment]
Elon musk wants to know your location.

**Comment by Vulwsztyn** [comment]
http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html

**Comment by tausifcreates** [comment]
![image](https://github.com/kataras/iris/assets/93582436/0f2a0af1-d01a-4e9d-aca9-f0c8a31e19e9)
