### ISSUE TITLE
How to write a transaction at the function level by iris

### ISSUE THREAD

**Issue by pingkui** [kataras/iris#1237]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by pingkui** [comment]
Like java spring, if iris can write a transaction at the function level, I will like it more!

**Comment by kataras** [comment]
Hello @pingkui, 

Iris has transactions for the writer, an example can be found at [/_examples/http_responsewriter/transactions](https://github.com/kataras/iris/blob/master/_examples/http_responsewriter/transactions/main.go) but if that doesn't help you please write down an example of usage so I can implement something that suits your needs.

Thanks!
