### ISSUE TITLE
How to bind multiple json request body on two or more struct ?

### ISSUE THREAD

**Issue by renjiza** [kataras/iris#1238]
for example i have 2 struct like this

`type A struct {
A string 'json:"a"'
B string 'json:"b"'
}`

and 2nd struct 
`type B struct {
B string 'json:"b"'
C string 'json:"c"'
}`

i try bind using 

`ctx.ReadJSON(&A); ctx.ReadJSON(&B);`

 it say "unexpected end of JSON input"

thanks for reply

**Comment by kataras** [comment]
You should embed those in one struct, there is no possible to bind twice the same body in a different result.
