### ISSUE TITLE
Can iris support this kind of regex match pattern routes?

### ISSUE THREAD

**Issue by Mrhyuan** [kataras/iris#1239]
Hi @kataras ,

I am willing to use iris as web framework. Is there a way to do pattern route matching like below?

app.Get("/users/{id:uint64}.html", func)

Thanks

**Comment by kataras** [comment]
Hello @Mrhyuan,

Absolutely yes, check the `routing/_examples/dynamic-path` example below: https://github.com/kataras/iris/blob/master/_examples/routing/dynamic-path/main.go#L259

You can use the `regexp` macro of the `string` parameter type or you can create [your own macro for a parameter type](https://github.com/kataras/iris/blob/master/_examples/routing/dynamic-path/main.go#L194-L203).

**Comment by Mrhyuan** [comment]
Thank you very much. I will dig into it.
