### ISSUE TITLE
Render template in error handlers

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#124]
Faced with such a problem.

There are two error handler ``iris.OnNotFound`` and ``iris.OnPanic``.
When you try to deduce the pattern of the function ``ctx.Render``, it returns a status code of 200, although this is wrong, it should be 404 and 500.

This is understandable, because the code in the feature:

```go
return ctx.HTML(StatusOK, name, binding, layout...)
```

But I would like some kind of interactivity that framework he understood the context in which the function is called ``ctx.Render``.

Now the problem is solved by a trivial change to the function ``ctx.HTML``.

```go
iris.OnNotFound(func(ctx *iris.Context) {
		ctx.HTML(iris.StatusNotFound, handlers.F(ctx, "errors/404"), nil)
})
```

Also I notice that if we define in advance the other handler, for example:

```go
iris.UseFunc(func(ctx *iris.Context) {
		ctx.Set("foo", "bar")
		ctx.Next()
})
```

That variable will not be available in the error handler ``iris.OnNotFound`` and ``iris.OnPanic``.

**Comment by kataras** [comment]
@egorsmkv  You have to provide manually the status code for your error, I made this choice because someone maybe want to render a page with status 200 like something happens.

> But I would like some kind of interactivity that framework he understood the context in which the function is called ctx.Render

The render sends 200 status code, so
you have to send the error code manually ( I have examples on this) 
```go
ctx.SetStatusCode(iris.StatusNotFound)
```
> That variable will not be available in the error handler iris.OnNotFound and iris.OnPanic.
Yes the error handlers have their own context, if you want to set a variable try something else like flash message ` ctx.SetFlash/ctx.GetFlash`

**Comment by egorsmkv** [comment]
I got it. I take advantage of the second embodiment.

**Comment by egorsmkv** [comment]
As for the second question. I'll try not to do after flash messages, and after the session.

**Comment by kataras** [comment]
I will recommend you use just the `.HTML() if you want to render ` 

if you don't want to render a template ( after the commit I did before 2 minutes)  you don't have to do `ctx.SetStatusCode(iris.StatusNotFound)` the status now is defaulted to the http status code error, if you want you can change it

**Comment by egorsmkv** [comment]
I got it. I use your option.

**Comment by kataras** [comment]
Nice!
