### ISSUE TITLE
Is it possible to hot reload a executable iris file?

### ISSUE THREAD

**Issue by CGDF-Github** [kataras/iris#1240]
For example, I built a executable file named "server1.exe" and launched it. Then, I built "server2.exe". Is it possible to hot load the newer executable file?

I have read README.md of `rizla`, and I think it just works with "*.go". Is there something that I misunderstood?

Thanks.

**Comment by kataras** [comment]
`rizla` can accept any file pattern matcher, you can do it for `.html`, `.css` too but it does not keep the connections open, it will restart your app on file changes, it works with two different features, the OS signals for file changes and the go's filepath watcher.

**Comment by CGDF-Github** [comment]
Okay, thank you!

**Comment by DevopsDood** [comment]
Rizla is currently broken
