### ISSUE TITLE
mime type of response body

### ISSUE THREAD

**Issue by ithemant09** [kataras/iris#1241]
Hi @kataras ,

Would you please help me with adding mimetype to response body ? 

Thanks.

**Comment by kataras** [comment]
Hello @ithemant09, here you are:

```go
func(ctx iris.Context) {
   ctx.ContentType("audio/mpeg") // or ctx.ResponseWriter().Header(),Set("Content-Type", "...")
   // write after...
}
```

If you want to get a mime type by extension or a filename you can also use the `kataras/iris/core/router#TypeByExtension/TypeByFilename`: https://github.com/kataras/iris/blob/master/core/router/mime.go#L566

For static file serving, Iris has all known mime types so they are added automatically, you can check the list from: https://github.com/kataras/iris/blob/master/core/router/mime.go#L8

**Comment by ithemant09** [comment]
Thanks for your quick response.
