### ISSUE TITLE
Question: MVC Custom Error Handler?

### ISSUE THREAD

**Issue by lightglitch** [kataras/iris#1244]
I wanted to have a unique error handler for all errors returned by MVC functions that would be responsible for how the error should be sent as response.

Can I register my own error handler? Couldn't find it anywhere.

**Comment by kataras** [comment]
Hey, we have the `app.OnErrorCode` which fires if response body is not written yet and `DisableAutoFireStatusCode` configuration field is not true, i.e:

```go
app.OnErrorCode(400, func(ctx iris.Context) {
	println("here") // this will be executed on http(s)://$host/error request path.
})

app.Get("/error", func(ctx iris.Context){
  ctx.StatusCode(400)
 // no ctx.Write/WriteString/JSON and so on...
})
```

This works on MVC with empty error text too, the only thing that `OnErrorCode` or `OrAnyErrorCode` cares is the status code >=400.

You are proposing to somehow register a `mvc-application-level` function which will take the `iris.Context` and an `error` as its input arguments(`func(ctx iris.Context, err error)`) which will be fired when an mvc function returns an `error`?

**Comment by lightglitch** [comment]
That is what I'm proposing. For example you allow:
```
func (c *MyController) GetList() []Items, error {
     return nil,error
}
```
but I don't know how that error is handle.
I would like to have a handler `func(ctx iris.Context, err error)` where the error would be handle and converted to html as I see fit based on the type of error.

**Comment by kataras** [comment]
The error is handled: if `<T>, error` then it writes status code 400 and the error's text as body to response, if `int, error` then the `int` is the specific status code and the error's text as body too. OK let me implement it locally and will come back later on, probably it will available on v11.2.

**Comment by kataras** [comment]
@lightglitch, You want it per-controller or per-application?

**Comment by lightglitch** [comment]
I only need it per-application, I don't a see a reason to be necessary per-controller.

**Comment by kataras** [comment]
I am writing it for both, if application-level error handler is nil then it will try to see if the controller implements a function of `HandleError(ctx iris.Context, err error)`.

**Comment by kataras** [comment]
It's done @lightglitch  :)

[Example](https://github.com/kataras/iris/blob/v11.2.0/_examples/mvc/error-handler/main.go):

```go
package main

import (
	"fmt"

	"github.com/kataras/iris"

	"github.com/kataras/iris/mvc"
)

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	mvcApp := mvc.New(app)
	// To all controllers, it can optionally be overridden per-controller
	// if the controller contains the `HandleError(ctx iris.Context, err error)` function.
	//
	mvcApp.HandleError(func(ctx iris.Context, err error) {
		ctx.HTML(fmt.Sprintf("<b>%s</b>", err.Error()))
	})
	//
	mvcApp.Handle(new(myController))

	// http://localhost:8080
	app.Run(iris.Addr(":8080"))
}

func basicMVC(app *mvc.Application) {
	// GET: http://localhost:8080
	app.Handle(new(myController))
}

type myController struct {
}

// overriddes the mvcApp.HandleError function.
// func (c *myController) HandleError(ctx iris.Context, err error) {
// 	ctx.HTML(fmt.Sprintf("<i>%s</i>", err.Error()))
// }

func (c *myController) Get() error {
	return fmt.Errorf("error here")
}
```

**Comment by lightglitch** [comment]
Looks good, thx

**Comment by lightglitch** [comment]
When are you planning to release 11.2?

**Comment by kataras** [comment]
I want to finish the websocket first, it contains a tons of features and fixes, it's totally new, I spent my 90% of time there and still not finished and you know how fast I am...

**Comment by lightglitch** [comment]
It's possible to had this as patch to 11.1? It would really useful for me right now in a project I'm working.

**Comment by kataras** [comment]
I can't add new features to v11.0, but you are totally free to use the `v11.2` if you want to, it has its own [branch](https://github.com/kataras/iris/tree/v11.2.0/), just download it and copy to your $GOPATH or your go mod's cache folder (if you use go modules) (this is a temp solution)
