### ISSUE TITLE
how to match "http://domain/module/xxx.json" in mvc

### ISSUE THREAD

**Issue by sootma** [kataras/iris#1246]
hi, 

mvc.Configure(Module).Handle(&controller{})

func (this *controller) PostXxx() interface{} {
....
}
it's ok that  the PostXxx match with "http://domain/module/xxx", NO ".json" suffix.
how to match "http://domain/module/xxx.json"

**Comment by kataras** [comment]
Hello @sootma ,

There is no pattern for MVC naming for such these things, you can imagine the limitations of that, instead you can use the `BeforeActivation` on your controller to add more advanced routing features, see examples at: https://github.com/kataras/iris/tree/master/_examples/routing and _examples/mvc . 

Example of your case:

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/mvc"
)

func main() {
	app := iris.New()

	mvcApp := mvc.New(app)
	mvcApp.Handle(new(myController))

	app.Run(iris.Addr(":8080"))
}

type myController struct{}

func (m *myController) BeforeActivation(b mvc.BeforeActivation) {
	// b.Dependencies().Add/Remove
	// b.Router().Use/UseGlobal/Done // and any standard API call you already know

	// 1-> Method
	// 2-> Path
	// 3-> The controller's function name to be parsed as handler
	// 4-> Any handlers that should run before the MyCustomHandler

	// "^[a-zA-Z0-9_.-]+.json$)" to validate file-name pattern and json
	// or just:  ".json$" to validate suffix.

	b.Handle("GET", "/{file:string regexp(^[a-zA-Z0-9_.-]+.json$))}", "HandleJSON")
}

func (m *myController) HandleJSON(file string) string {
	return "custom serving of json: " + file
}

```

**Comment by kataras** [comment]
Hello @sootma ,

There is no pattern for MVC naming for such these things, you can imagine the limitations of that, instead you can use the `BeforeActivation` on your controller to add more advanced routing features, see examples at: https://github.com/kataras/iris/tree/master/_examples/routing and [_examples/mvc](https://github.com/kataras/iris/tree/master/_examples/mvc) . 

Example of your case:

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/mvc"
)

func main() {
	app := iris.New()

	mvcApp := mvc.New(app)
	mvcApp.Handle(new(myController))

	app.Run(iris.Addr(":8080"))
}

type myController struct{}

func (m *myController) BeforeActivation(b mvc.BeforeActivation) {
	// b.Dependencies().Add/Remove
	// b.Router().Use/UseGlobal/Done // and any standard API call you already know

	// 1-> Method
	// 2-> Path
	// 3-> The controller's function name to be parsed as handler
	// 4-> Any handlers that should run before the HandleJSON

	// "^[a-zA-Z0-9_.-]+.json$)" to validate file-name pattern and json
	// or just:  ".json$" to validate suffix.

	b.Handle("GET", "/{file:string regexp(^[a-zA-Z0-9_.-]+.json$))}", "HandleJSON",
        /* optionalMiddleware*/)
}

func (m *myController) HandleJSON(file string) string {
	return "custom serving of json: " + file
}

```

You can also create your own `macro`, i.e: `/{file:json}` or macro function of a specific parameter type i.e: (`/{file:string json()}`). Read the routing examples and you will gain a deeper view, there are all covered.

Thanks,
Gerasimos Maropoulos

**Comment by sootma** [comment]
thanks
