### ISSUE TITLE
undefined iris.Context

### ISSUE THREAD

**Issue by tonyhsiang** [kataras/iris#1247]
hi, i am noob guy for iris, there is a question as title says:
i download the newest code on github and go run a example, why it tells me undefined iris.Context, thanks!

**Comment by kataras** [comment]
Hello @tonyhsiang , there is a section for newcomers in the FAQ, the `kataras/iris.Context` type alias of `kataras/iris/context.Context` is explained as well, take a look at: https://github.com/kataras/iris/blob/master/FAQ.md#common-errors-that-new-gophers-may-meet. 

At short, to use type aliases and `iris.Context` you need to install `go version >=1.9` (the latest go release is `1.12.4`). 

Just update your golang software in your host (the machine you built your Iris Web App from): https://golang.org/dl/

**Comment by tonyhsiang** [comment]
ohyes i use go 1.8.6 ... it must be the reason as you said 
thank you so much for giving me advice and i will read FAQ before i ask questions :)

**Comment by kataras** [comment]
No problem @tonyhsiang , glad to serve!

You're welcome to our community.
