### ISSUE TITLE
Processing access error

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#125]
If you enable access to static files, for example:

```go
iris.Static("/assets", "./resources", 1)
```

And do not refer to a file and a directory (for example, if you want to see a list of files), you will get the correct error:

```
Directory index is forbidden
```

But if you write a handler for this error:

```go
iris.OnError(iris.StatusForbidden, func(ctx *iris.Context) {
		ctx.HTML(iris.StatusForbidden, "errors/403.html", nil)
})
```

**That he will not be executed.**

**Comment by kataras** [comment]
@egorsmkv  Tell me the true, do you read the docs?... to have an index page use `iris.StaticFS("/assets", "./resources", 1)`

**Comment by egorsmkv** [comment]
Just I do not need to. I want to make 403 error handler successfully worked.

**Comment by kataras** [comment]
Ok, just update iris then :P

**Comment by egorsmkv** [comment]
Thanks!

**Comment by kataras** [comment]
Is worked? I thanks you for your reports!!

**Comment by egorsmkv** [comment]
Yes, it works with a bang!

**Comment by kataras** [comment]
nice, I made some updates also, for templates if you `just` want to edit the Template.`Engine` and no other configuration you `don't need to import the config` package, you can use that instead `iris.Config().Render.Template.Engine = iris.Pongo`

**Comment by egorsmkv** [comment]
Yes, that is more convenient. Thank you!
