### ISSUE TITLE
white page on posted page 

### ISSUE THREAD

**Issue by ehsanrocket** [kataras/iris#1252]
Hi ever body
I have these routes 

`app.Get("/x", HandleX)`
`app.Post("/x", HandleXPost)`
and this is my html form tag
`<form action="x" method="post" >`
`...`
`<button type="submit"">send</button>`

after I hit the send button I see a white page 
why it is not show the content of the page: http://localhost:8090/x
I want to know is there anything like PHP_SELF 

this is HandleX function : 
`func HandleX(ctx iris.Context) {`
` ctx.ViewData("c", 0)`
`        if err := ctx.View("x.html"); err != nil {`
`                 ctx.Application().Logger().Infof(err.Error())`
`        }`
`}`

**Comment by ehsanrocket** [comment]
I found the solution
at the end of the HandleXPost functions I used: 
`ctx.Redirect("x")`
it will redirect the page to the http://localhost:8090/x hit

note : 
when I hit the http://localhost:8090/x the content of the page "x" is being shown to me
that has a HTML form with  
`<form action="x" method="post" >...`. 
"action" refers to itself.(it will not happen)
when I hit the send , it will go to the page "x" that is white and it is completely a separate page from page "x" that has HTML forms.
`app.Get("/x", HandleX)`
`app.Post("/x", HandleXPost)`
these "/x" pages are completely different pages. 
first one /x with method GET
second one /x with method POST
just their name are the same, as I said I use ctx.Redirect("x") at the end of the HandleXPost function (posted page) 
`func HandleXPost(ctx iris.Context){`
`...`
`ctx.Redirect("x")`
'}'
so it goes to the "x" (page with HTML forms)

I think somehow it is a way to implement PHP_SELF in iris

**Comment by kataras** [comment]
Hello, you can get the current path by 'ctx.Path()' or 'ctx.Request().Path', it is the same as PHP_SELF. About the redirect from POST to GET and GET to POST, it's the standard behavior, the http specification requires different 3XX status code for the redirection, read more at the comments of the ctx.Redirect function.
