### ISSUE TITLE
Error on use Godep

### ISSUE THREAD

**Issue by lucasmdomingues** [kataras/iris#1255]
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/cfg
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/client
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/client/rule
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/entry
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/ruleset
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/cache/uri
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/context
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/errors
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/handlerconv
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/host
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/memstore
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/netutil
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/core/router
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro/handler
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro/interpreter/ast
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro/interpreter/lexer
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro/interpreter/parser
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/macro/interpreter/token
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/middleware/logger
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/middleware/recover
godep: dirty working tree (please commit changes): /home/lucas/Workspace/go/src/github.com/kataras/iris/view
godep: error loading dependencies

**Comment by lucasmdomingues** [comment]
I want use godep but dont fun

**Comment by lucasmdomingues** [comment]
?

**Comment by kataras** [comment]
Hello @lucasmdomingues, check this answer: https://github.com/kataras/iris/issues/1143#issuecomment-472035292
