### ISSUE TITLE
sessions database redis keys delimeter

### ISSUE THREAD

**Issue by hunternsk** [kataras/iris#1256]
At this moment keys delimeter is hardcoded:
const delim = "_"

need some configurable option like Delimeter: ":" 

it's little uncomfortable and messy now
![image](https://user-images.githubusercontent.com/9771209/57772706-59388780-7740-11e9-9b26-11f8f366bc4b.png)

**Comment by kataras** [comment]
Hello @hunternsk, I am so so sorry for this huge delay, this is not my usual, I was very sick and working in the new websocket module for Iris v11.2, excuse me.

I accept this as a feature request for the upcoming v11.2, you will have this soon. Thank you a lot!
