### ISSUE TITLE
Done @shenkaige , the updated [example](https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go#L30) looks like this (note the new `IsErrPath`):

### ISSUE THREAD

**Issue by shengbox** [kataras/iris#1257]
Done @shenkaige , the updated [example](https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go#L30) looks like this (note the new `IsErrPath`): 

```go
	app.Post("/form_action", func(ctx iris.Context) {
		visitor := Visitor{}
		err := ctx.ReadForm(&visitor)
		if err != nil && !iris.IsErrPath(err) { // it will ignore error if client sends unexpected fields.
			ctx.StatusCode(iris.StatusInternalServerError)
			ctx.WriteString(err.Error())
		}

		ctx.Writef("Visitor: %#v", visitor)
	})
```

_Originally posted by @kataras in https://github.com/kataras/iris/issues/1157#issuecomment-451397572_

It will lost the field you need sometime

**Comment by shengbox** [comment]
```
order== {0    0 44444 33333        }
form: not found the field "title"
order== {0  22222  0 44444 33333        }
form: not found the field "title"
order== {0 11111 22222  0 44444 33333 666666       }
form: not found the field "title"
order== {0  22222  0 44444 33333        }
form: not found the field "title"
order== {0 11111 22222  0 44444 33333        }
form: not found the field "title"

```
client sends the same , the server print the order like this

**Comment by kataras** [comment]
Hello @shengbox, this is a basic golang question, `maps doesn't support order like slices, each time you may get different order of the data, no matter what is added first or last`. 

The `net/http#Request.Form, PostForm, MultipartForm` is a type of `Values` which is a `map-based` type which `ctx.ReadForm` depends on.
