### ISSUE TITLE
How to implement request asynchronous waiting

### ISSUE THREAD

**Issue by shehuaqigai** [kataras/iris#1258]
If 100 requests are concurrently come in, how to make 99 requests wait, release a request to get data, and after getting the data, then 99 requests to response get the data, in order to solve the cache breakdown problem, at the moment of updating the cache, Request to block the release one by one until the data is terminated, in response to all requests

**Comment by kataras** [comment]
Check the https://godoc.org/golang.org/x/sync/semaphore package, you can search over the internet about other patterns that you can use to achieve that. It's out of Iris' scope.
