### ISSUE TITLE
[ISSUE] config of TOML and YAML can't show error if the config item wrong

### ISSUE THREAD

**Issue by feiyangxiaomi** [kataras/iris#1260]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
1. https://github.com/kataras/iris/blob/master/configuration.go#L89
2. https://github.com/kataras/iris/blob/master/configuration.go#L123

As you can see, it does, if you mean something else please post an example and we can see if that's a `yaml` or `toml` parser library issue or an Iris one.
