### ISSUE TITLE
Multi response was sent to one request ?

### ISSUE THREAD

**Issue by chenPengXu** [kataras/iris#1262]
Has someone has seen this bug ?
Like this: 

A request and B request were sent at the same time,  then A or B may be received A and B's response(json) like this "{ret: true, data:"a data"}{ret: true, data"b data"}"。 I has seen this issue times, but when i try review it, it gone ...  So Has someone has seen this issue ?

**Comment by kataras** [comment]
You mean the chrome's `favicon.ico` request that is done automatically by the browser itself?
