### ISSUE TITLE
Can not read JSON body on different middleware functions

### ISSUE THREAD

**Issue by kalmecak** [kataras/iris#1265]
I'm working on a project that needs use many handler functions for a single path, this is because we reuse some functions in others paths, for example: making validations. In many cases we need to work with the body, but for some reason when we use **ctx.ReadJSON**  function for second time it throws **unexpected end of JSON input**

Is there a way to pass the body betwen the handlers or these error is a bug?
I'm letting a litte example snipet of the way we are working:

    
    package main

    import (
	    "github.com/kataras/iris"

	    validator "gopkg.in/go-playground/validator.v9"
	    "log"
    )
    
    // This is the spected structure of the JSON body
    type niceStruct struct {
	    name  string `json:"name" validate:"required"`
	    phone string `json:"phone" validate:"required"`
    }

    // This function make validations to the body
    // and continues the process
    func verifyBody(ctx iris.Context) {

	    var body niceStruct
	    if err := ctx.ReadJSON(&body); err != nil {
		    log.Println("Error on reading body")
		    log.Println(err)
		    return
	    }

	    validate := validator.New()
	    err := validate.Struct(body)
	    if err != nil {
		    log.Println("Error on validating body")
		    log.Println(err)
		    return
	    }
	    ctx.Next()
    }

    // This function use the body info
    func sayHello(ctx iris.Context) {

	    var body niceStruct
	    if err := ctx.ReadJSON(&body); err != nil { // this is where throws errors
		    log.Println("Error on reading body")
		    log.Println(err)
		    return
	    }
	    hello := "Hello " + body.name
	    ctx.HTML(hello)

    }
    func main() {

	    app := iris.New()

	    app.Handle("GET", "/hello", verifyBody, sayHello)

	    app.Run(iris.Addr(":8080"), iris.WithoutServerError(iris.ErrServerClosed))
    }

**Comment by kataras** [comment]
Hello,

By-default, the `ctx.ReadJSON` and all read functions will read the body until EOF (io.ReadAll **consumes** the data readen, the whole body like the `net/http` and all web frameworks in Go, this is a basic thing to know). 

However, Iris has a [DisableBodyConsumptionOnUnmarshal](https://github.com/kataras/iris/blob/master/configuration.go#L440) option: `app.Run(iris.Addr(...), iris.WithoutBodyConsumptionOnUnmarshal)`. This will give your handlers the opportunity to read the body again and again without consuming it by the first `ReadJSON`.

**Comment by kalmecak** [comment]
Ufff, I see now, thanks a lot for you help I'll read the whole net/http documentation.

**Comment by kataras** [comment]
You're welcome @kalmecak, don't hesitate to ask again.
