### ISSUE TITLE
dep ensure -add  github.com/kataras/iris

### ISSUE THREAD

**Issue by Terminators** [kataras/iris#1266]
how can I use golang  dep add iris
1.dep ensure -add  github.com/kataras/iris
2.go build main.go

# project_dep/vendor/github.com/kataras/iris/context
vendor/github.com/kataras/iris/context/context.go:27:2: imported and not used: "project_dep/vendor/github.com/Shopify/goreferrer" as referrer
vendor/github.com/kataras/iris/context/context.go:1623:9: undefined: goreferrer
vendor/github.com/kataras/iris/context/context.go:1627:9: undefined: goreferrer
vendor/github.com/kataras/iris/context/context.go:1645:12: undefined: goreferrer

**Comment by kataras** [comment]
Hello @Terminators, check this answer: https://github.com/kataras/iris/issues/1143#issuecomment-472035292
