### ISSUE TITLE
route error - possibly regex

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1268]
I am using the latest version of Iris and my app doesn't use any MVC architecture.

I had a similar problem in my previous IRIS app as well, but having an issue the second time makes me think, whether this issue is in the IRIS framework or my code.

I have a few routes like:

```
... other code

app.Get("/do/something", func(ctx iris.Context) {
    // Process other code here
    ctx.WriteString("do something here")
})

app.Get("/ok/something", func(ctx iris.Context) {
    // Process other code here
    ctx.WriteString("ok something here")
})

.. other code
```

Now, there is time, when even though I am calling for `/do/something` path in my browser, My code process the code and prints text from function `/ok/something`.

This doesn't happen in the first go, it happens after some time like SAY:-

I open `/do/something` 5 times and then open `/ok/something` - 2-3 time

And now, even after calling `/do/something`, I am getting value from `/ok/something`. This is really annoying as my `/do/something` and `/ok/something` are register and login page.

Now, when calling register, I get password error from login function. 

I am unable to find the real issue, and I believe this could be because of IRIS routing issue.

any help would be appreciated.

**Comment by kataras** [comment]
@rebootcode I think you are missing something, I tested this and it works as expected, we never had issues like this, I am sure that you do something else that didn't provide on the issue body.

**Comment by rebootcode** [comment]
Hi, @kataras Thanks for the reply.

I have created sample code from my code -- https://kopy.io/vpmCk 

As you can see, it is a very basic app and I am using "AWS server" with `nginx` as a reverse proxy.

Now, when I send "register" it works great but after doing some repeated register and then after a couple of "login" route calling.

When I call "register" again after some time, then I started getting a response as "wrongPassword" and if you see "wrongPassword" response is only provided in "login" function, Yet I get this response on "register" route.

But after changing a route from "/process/register" to "/do/process/register" - It's now more than 24 hours and I haven't got a mixed response from login or other route.

If I switch back to "/process/register" - back to 2nd level route just like "/process/login" - After some time, I again start getting login response error while calling register response.

**Comment by kataras** [comment]
In the example code I don't see any `/process/login`, just a `/make/login/` (also you should remove the last "/" there). I can't re-produce the issue with the given example, please post a re-producable example... if you don't have time just make a simple program witch behaves incorrectly just use `println` calls, boltdb is unnecessary here.

**Comment by rebootcode** [comment]
I will share a live website URL and server access if you want them to look via your mail after a couple of days to test it out live.

**Comment by kataras** [comment]
It's better to just post an example, if it's a router match issue then the handler's body can be fairly simple -- just different output on each route. However, I am available for you of course, e-mail me at: `<kataras2006@hotmail.com>`.
