### ISSUE TITLE
Don't serialize MVC return nil

### ISSUE THREAD

**Issue by lightglitch** [kataras/iris#1273]
```
func (c *Controller) Get() *iris.Map {
return nil
}
```
Should be a way to not serialize nil as null, because sometimes we don't want to write anything to the output.

**Comment by kataras** [comment]
I understand, however, it should be optional so I will introduce an optional mvc/hero configuration  for the upcoming `v11.2.0` which you will be able pass to declare "rules", it will be useful for any future request as well, sounds good?

**Comment by kataras** [comment]
Fixed with https://github.com/kataras/iris/commit/56754d78ed8cc7b3395ad32a957db3d0c3a588ab thanks for the report @lightglitch !

**Comment by lightglitch** [comment]
Thx

**Comment by kataras** [comment]
You're welcome, community and support are the two most important things for a project like this.
