### ISSUE TITLE
Why not add a mighty Bind method of iris.Context instead of Readform?

### ISSUE THREAD

**Issue by focusonline** [kataras/iris#1274]
I really think iris should add the mighty Bind method instead of ReadForm or ReadJSON?
Just like what Gin does, Gin knows what request method is going and drive the bind method on right way. if it is GET, bind the parameter object with query url or POST, bind the parameter with query url and form body and so forth per the content type. 
It is very convenient for processing parameters.
Anyway, ReadFrom is good as well, but it needs the parameter must be in request form-data, terminiate the decoding and report error when missing corresponding field in form,  it needs special tag name "form" in struct tag, although there is same JSON tag mapping field name there, basically, they are same. for RESTful API or Web request. It is unnecessary to redefine another struct tag like form.
And, bind really needs a global configuration to skip any missing field mapping, not only in request form but also in mapping object. unstrict mode is useful.
Thank you for reading.

**Comment by kataras** [comment]
Yes I know that feature but I didn't though it will be useful, at other side I think this is not "safe" and may produce unexpected results for a big web application, when you expect X but got Y because of client's "accept content type" but if you really need this I can do it on the minor v11.2.1 @focusonline

**Comment by focusonline** [comment]
thank you so much, dear Mr Kataras. It is good enough for now, I found the method ReadJSON to parse application/json, anyway, these two ways , readform and readjson, could cover most situations.
if json tag could be reused by merging variable name mapping or validation, it will be more convenient, actually, most front-end developers are accustomed to naming variable in camel case. it is just a suggestion. Thank you again for kindly reply.

**Comment by kataras** [comment]
@focusonline 

- `ReadJSON` with `json` field tag to change the name, .e.g to camelCase, reads body
- `ReadForm` with `form` field tag

**Comment by kataras** [comment]
@focusonline Thanks, if you need anything please don't hesitate to ask.

- `ReadJSON` with `json` field tag to change the name, .e.g to camelCase, reads body as JSON
- `ReadForm` with `form` field tag , reads multipart post data or query
- `ReadQuery` with `url` field tag, reads query string only, all methods.
