### ISSUE TITLE
cannot find module providing package github.com/kataras/iris

### ISSUE THREAD

**Issue by saschat** [kataras/iris#1278]
I would love to use iris but go just refuses to find it. I am aware of similar issues posted in the past but the solution usually seemed to be "update the iris version" and I am using the newest version of iris and go. The following commands replicate my issue:

```bash
$ go version
go version go1.12.5 linux/amd64
$ mkdir test
$ cd test
$ go mod init test.com/test
$ cat <<EOF >main.go
package main

import "github.com/kataras/iris"

func main() {
	app := iris.New()
	app.Run()
}
EOF
$ go build
build test.com/test: cannot load github.com/kataras/iris: cannot find module providing package github.com/kataras/iris
$ cat go.mod 
module test.com/test

go 1.12
$ cat go.sum 
github.com/kataras/iris v11.1.1+incompatible h1:c2iRKvKLpTYMXKdVB8YP/+A67NtZFt9kFFy+ZwBhWD0=
$ go get github.com/kataras/iris
$ go build
build test.com/test: cannot load github.com/kataras/iris: cannot find module providing package github.com/kataras/iris
$ cat go.mod 
module test.com/test

go 1.12

require github.com/kataras/iris v11.1.1+incompatible // indirect
$ cat go.sum 
github.com/kataras/iris v11.1.1+incompatible h1:c2iRKvKLpTYMXKdVB8YP/+A67NtZFt9kFFy+ZwBhWD0=
github.com/kataras/iris v11.1.1+incompatible/go.mod h1:ki9XPua5SyAJbIxDdsssxevgGrbpBmmvoQmo/A0IodY=
```

**Comment by kataras** [comment]
Hello @saschat, I tested it on an external clean machine with `go1.12.6` and both `go build` and `go mod init && go build` worked as expected. Here are the results:

`go build`

![gobuild_works](https://user-images.githubusercontent.com/22900943/59370642-a4e44e00-8d4b-11e9-9369-1f57413eefbd.png)

`go mod init && go build` including **go.mod, go.sum**:

![gomodsubworks](https://user-images.githubusercontent.com/22900943/59370674-b6c5f100-8d4b-11e9-887b-7ef516d2ead9.png)
 
I need more information, i.e have you already installed Iris or made a modification to its gopath folder? Did you try to clean your `pkg/mod` cache folder before?

Thanks!

**Comment by saschat** [comment]
I wiped the downloaded iris package and the cache and the problem went away. Not sure why this happend in the first place as I did not have iris installed before.

**Comment by kataras** [comment]
OK no problem @saschat you did well commenting it out, don't hesitate to ask for any help here
