### ISSUE TITLE
fasthttp.FS not allowing configuration of `IndexNames`

### ISSUE THREAD

**Issue by ontsysmattholcomb** [kataras/iris#128]
Do you have a recommended way to setup a FS handler with an IndexName set?  In my case it would just be `IndexNames: []string{"index.html"}`.  This may be a bug since the documentation for `iris.StaticWeb` says "if index.html exists and request uri is '/' then display the index.html's contents", so potentially it is intended to just default it to this?

**Comment by kataras** [comment]
You can use the `iris.StaticHandlerFunc`to make your own customizations if you need them, StaticWeb uses this also you can see it's code. I didn't understand well your question, if you can give me an example in order to show you how to

**Comment by ontsysmattholcomb** [comment]
I am just using `iris.StaticWeb("/", ...)` but when it sets up the FS handler it does not set the fastHttp's `IndexNames` to anything, which is `[]` by default.  This results in the error "cannot access directory without index page" when attempting to g to the "/" route (even if there is an index.html page present.

**Comment by kataras** [comment]
Try this https://github.com/kataras/httpserver/blob/master/httpserver.go#L70 and tell me the results, or write down your code snippet

**Comment by ontsysmattholcomb** [comment]
This is the code that I am referring to that does not set the IndexNames option:

https://github.com/kataras/iris/blob/db01b18ea870a396eaf24a03a87f93f2d6b7177f/party.go#L210

**Comment by kataras** [comment]
Yes I understand this, I asked you two times if you want to set this:
```go
	// List of index file names to try opening during directory access.
	//
	// For example:
	//
	//     * index.html
	//     * index.htm
	//     * my-super-index.xml
	//
	// By default the list is empty.
	IndexNames []string

```
 via the StaticHandlerFunc function

**Comment by kataras** [comment]
https://github.com/kataras/iris/blob/master/party.go#L246 now better?

**Comment by ontsysmattholcomb** [comment]
Yes, that change is great.  Thanks.
