### ISSUE TITLE
Wrong Doc about RegisterFunc

### ISSUE THREAD

**Issue by kilik52** [kataras/iris#1286]
In **Do It Yourself** section, the line of code:

`app.Macros().Get("string").RegisterFunc("coordinate", latLonRegex.MatchString)
` is wrong, it should be:

    app.Macros().Get("string").RegisterFunc("coordinate", func() func(string) bool { 
        return latLonRegex.MatchString
    })

I've tried the first one, it won't work.

**Comment by kataras** [comment]
Hello @kilik52 thank you for trying to report a bug but this works just fine, that code sample is not only in the **Do It YourSelf**, all code samples are running inside the examples, take a look: 

https://github.com/kataras/iris/blob/6564922661686d43954b8bcf1d4f469a3d2c3fa3/_examples/routing/dynamic-path/main.go#L193-L205

Here is how it runs here:

![issue1286](https://user-images.githubusercontent.com/22900943/59970995-3a69b400-957c-11e9-8caf-9e9372c96f22.png)

However, If you have an issue in your iris app, please post a reproducable code below so I can be more helpful.

Thanks!

**Comment by kataras** [comment]
Hello @kilik52 thank you for your time but this works just fine, that code sample is not only in the **Do It YourSelf**,  it's a running example as well, take a look and run it by yourself: 

https://github.com/kataras/iris/blob/6564922661686d43954b8bcf1d4f469a3d2c3fa3/_examples/routing/dynamic-path/main.go#L193-L205

**run**:

![issue1286](https://user-images.githubusercontent.com/22900943/59970995-3a69b400-957c-11e9-8caf-9e9372c96f22.png)

However, If you have an issue in your iris app, please post a reproducable code below so I can be more helpful.

Thanks!

**Comment by kilik52** [comment]
@kataras Thank you for your reply. I don't know if i got this wrong, but here's the reproducable code:

````
package main

import (
	"regexp"

	"github.com/kataras/iris"
)

func main() {
	app := iris.Default()

	latLonRegex, _ := regexp.Compile("^-?[0-9]{1,3}(?:\\.[0-9]{1,10})?$")

	// Register your custom argument-less macro function to the :string param type.
	// MatchString is a type of func(string) bool, so we use it as it is.
	app.Macros().Get("string").RegisterFunc("coordinate", latLonRegex.MatchString)

	app.Get("/coordinates/{lat:string coordinate()}/{lon:string coordinate()}", func(ctx iris.Context) {
		ctx.Writef("Lat: %s | Lon: %s", ctx.Params().Get("lat"), ctx.Params().Get("lon"))
	})

	// listen and serve on http://0.0.0.0:8080.
	app.Run(iris.Addr(":8080"))
}

````

when I visit the route using this link: `localhost:8080/coordinates/aaa/12.3`, the correct return i think should be **404 not found**. But the response is **Lat: aaa | Lon: 12.3**. 

Then, I changed the **RegisterFunc** to 

````
app.Macros().Get("string").RegisterFunc("coordinate", func() func(string) bool {
    return latLonRegex.MatchString
})
````

Then visiting `localhost:8080/coordinates/aaa/12.3` will give me 404 not found

**Comment by kataras** [comment]
OK, now you have a point, it wasn't a doc issue, it was a bug that came after the v11.1 changes to how macros are registered. I've just fixed it for the `v11.2.0` and I will push it to the master repository because it was a serious bug although an easy one to fix. Thank you a lot @kilik52 it was the most improtant bug report we had for a long time.

**Comment by kilik52** [comment]
Great, glad i can help.

**Comment by gongchao** [comment]
+1
