### ISSUE TITLE
Header not Set while sending Token request to external URL

### ISSUE THREAD

**Issue by StarMonk** [kataras/iris#1289]
I am sending "API request" to external URL and I am getting error - `You need to provide an API token to access the API.`

As per API, it asks me to send API Authorization header like -
```
curl -H "Authorization: Bearer {MY_API_TOKEN_HERE}" https://api.envato.com/v3/market/author/sale?code={PURCHASE_CODE_HERE}
```

**It works perfect from command line**, but when I am sending via "iris" app like below -

```
app.Get("/verify/envato/{purchaseCode}", func(ctx iris.Context) {
        pcode := ctx.Params().Get("purchaseCode")
	ctx.Header("Authorization", "Bearer {API_TOKEN_HERE}")
	ctx.Header("User-Agent", "CUSTOM User Agent")
	var netClient = &http.Client{
		Timeout: time.Second * 10,
	}
	resp, err := netClient.Get("https://api.envato.com/v3/market/author/sale?code=" + pcode)
	if err != nil {
		ctx.WriteString("Failed")
		return
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	var dat map[string]string
	_ = json.Unmarshal(body, &dat)

	ctx.HTML("<b>Error: </b>" + dat["error"] + "<br><br>")
	ctx.HTML("<b>Missing Token: </b>" + dat["reason"])
})
```

It throws an error - 

```
Error: Missing or malformed API token: You need to provide an API token to access the API. The token must be a 32 character long alphanumeric string. See https://build.envato.com/api/#token

Missing Token: missing-token
```

I confirm, I am using same "TOKEN" that i am using command line. it looks like - It is not just sending "Authorization" header in GET request. 

Can someone please help me find the right way to pass header request.

Thanks

**Comment by kataras** [comment]
Hello @StarMonk. Iris is a server, back-end application framework, you set a response header through `ctx.Header`, this will pass to the client that will ask for `/verify/envato/{purchaseCode}` on your server machine.

**I think you want to pass the Authorization and User-Agent headers to your CLIENT instead (`netClient`)**. Read the documentation of the `net/http.Client` and you'll find how you can set headers, it's very easy.

**Comment by StarMonk** [comment]
oh! Thank you! I got you! <3

**Comment by kataras** [comment]
No problem, I am glad to help you out!
