### ISSUE TITLE
Middleware for minify HTML

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#129]
You can add this library https://github.com/tdewolff/minify as middleware?

**Comment by kataras** [comment]
We have a better solution using Static handlers which if you add the option compress can create .zip files and serve them with gzip compression also, BUT this works only on static files, it doesn't works for templates so your suggestion has a point if you mean this: https://github.com/tdewolff/minify#templates I can add it as optional option in the iris.Config().Render.Template configuration, alright?

**Comment by egorsmkv** [comment]
Yes, it will be more convenient.

**Comment by kataras** [comment]
Although you can already add this by yourself using the ìris.Config().Render.Template.Asset() which returns the bytes to render, but no problem I already started the minify

**Comment by egorsmkv** [comment]
Okay

**Comment by kataras** [comment]
@egorsmkv  Done, tested and worked :) Thanks for your nice suggestion https://github.com/kataras/iris/commit/8dce87b3ffccb5d95a29880bf24cfea16012a5cb

**Comment by egorsmkv** [comment]
@kataras you test pongo2 templates?

**Comment by kataras** [comment]
The minifier works great, it prints the minified pongo2 string BUT  after `pongo's .FromString()` unminifies it... lol

**Comment by egorsmkv** [comment]
So it works

pongo.go

```go
func (p *Engine) Execute(ctx context.IContext, name string, binding interface{}, layout string) error {
	// get the template from cache, I never used pongo2 but I think reading its code helps me to understand that this is the best way to do it with the best performance.
	tmpl, err := p.Templates.FromCache(name)
	if err != nil {
		return err
	}
	// Retrieve a buffer from the pool to write to.
	out := buffer.Get()

	err = tmpl.ExecuteWriter(getPongoContext(binding), out)

        // Start minimize html code
	var minifier *minify.M
	if p.Config.Minify {
		minifier = minify.New()
		minifier.AddFunc("text/html", htmlMinifier.Minify)
	}
	if p.Config.Minify {
		data, _ := minifier.Bytes("text/html", out.Bytes())
		out = buffer.Get()
		out.Write(data)
	}

	if err != nil {
		buffer.Put(out)
		return err
	}
	w := ctx.GetRequestCtx().Response.BodyWriter()
	out.WriteTo(w)

	// Return the buffer to the pool.
	buffer.Put(out)
	return nil
}
```

**Comment by kataras** [comment]
No no man, this way we minify it in every request, we don't want to do that!

**Comment by kataras** [comment]
Currently, I just removed the Minify from the Pongo and added it only to the HTMLTemplate

**Comment by egorsmkv** [comment]
Well, it is not effective every time it regenerate. It also does not include by default, but to make as an option.

**Comment by kataras** [comment]
@flosch is here maybe he could help us :)

**Comment by egorsmkv** [comment]
In fact pongo2 not caches minimized html code. You need to add it and then the problem will be solved.

**Comment by kataras** [comment]
I didn't understand can you explain it? flosch should answer to this he just starred iris :P ....

**Comment by kataras** [comment]
Wait You have a point I see wait

**Comment by egorsmkv** [comment]
Ok

**Comment by kataras** [comment]
No, I can't do anything, .FromCache takes only filename as parameter, this is correct but  .FromString() doesn't cache it and the cache set is private I can't add manually the filename to the minified string... so we wait for a fix

**Comment by egorsmkv** [comment]
Okay. Let's wait @flosch

**Comment by egorsmkv** [comment]
@kataras how to use ``ìris.Config().Render.Template.Asset()``?

**Comment by kataras** [comment]
@egorsmkv  Don't bother I made pongo2 works with minifier :) upgrade to v3.0.0-alpha.4

**Comment by egorsmkv** [comment]
Great!

**Comment by kataras** [comment]
Happy codding, I must go to sleep now!

**Comment by egorsmkv** [comment]
Yesterday I also did caching of templates on the same idea. But faced with a problem: if you add "include" in the template, it will not minimize **all** HTML code.

**Comment by egorsmkv** [comment]
@kataras ping

**Comment by kataras** [comment]
@egorsmkv pong 

I did my best on pongo2, if the includes are not minified I have to see it but it is not the priority  I have right now

**Comment by egorsmkv** [comment]
Okay

**Comment by kataras** [comment]
I hope that you're understand I have to do a lot of things I can't spend all my time for pongo2's includes minification..sorry

**Comment by egorsmkv** [comment]
Oh sure. When it is possible, and then continue. I'll try to do this function, when you have time.

**Comment by kataras** [comment]
Yes when I finish these tasks I'm doing ofc I will continue with this also, I'm not give up so easy :P
