### ISSUE TITLE
Tornado List index out of range

### ISSUE THREAD

**Issue by lucasteng123** [kataras/iris#1290]
Hi,
I have a new install of mopidy and iris on Raspbian Buster 4.19

It errors whenever a client is connected saying 
```
ERROR    Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 721, in _accept_connection
    self.selected_subprotocol = self.handler.select_subprotocol(subprotocols)
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy_iris/handlers.py", line 28, in select_subprotocol
    return subprotocols[0]
IndexError: list index out of range

```
Thanks

**Comment by kataras** [comment]
Hello @lucasteng123,  I am using Iris on a PI 3 B model to test how it performs on low-end machines!

However, I think you asked for a help on the wrong project, the logs you provide are pointing to something like `handlers.py` which is a python source file. Iris is written and used by people who write using the [Go](https://golang.org) programming language. So...we can't really help you, I don't even know what is it, many people use the "Iris" name to promote their projects after the success of Iris web framework.

However, if you are a backend developer, give Iris a try, you will be suprised about how much things you are missing that you don't even be aware of!

Thanks,
Gerasimos Maropoulos. Author of Iris.
