### ISSUE TITLE
Apm/Tracing Support

### ISSUE THREAD

**Issue by dragonyui** [kataras/iris#1293]
So i'm wondering do iris have built in middleware/library for tracing?
I want to use apm for tracing and monitoring my iris web app, but it doesn't support iris yet. And i realize that iris do have support for using standart handler for net/http package. 
So could i use net/http implementation in iris? 
thanks

**Comment by kataras** [comment]
What do you mean "it doesnt support iris yet"? What's the middleware that supports `net/http` and not Iris?
