### ISSUE TITLE
why /v1/hosts/ will be forced to redirect to /v1/hosts

### ISSUE THREAD

**Issue by Near-Zhang** [kataras/iris#1294]
iris config：
``` json
{
    "disablePathCorrection": false,
    "disablePathCorrectionRedirection": true
}
```

why only `/v1/hosts/` will be forced to redirect to `/v1/hosts`，before through warpRouter

`/v2/hosts/` or `/v1/host/` or other urls do not happen this way

whether `/v1/hosts/` is a reserved route or has other special operations？

**Comment by kataras** [comment]
Hello @Near-Zhang,

This is explained on the routing section of the _examples. In short: the most common and recommeneded APIs are designed that way so Iris by defaults handles both /api/user and /api/user/ using the same handler by redirecting the last one to the first. However if you read the examples you will see that we have a **setting** for that called _DisablePathCorrection_ ehich you can set through functional way like this: **app.Run(..., iris.WithoutPathCorrection)**. However I recommend to not do that and let the default behavior if you design a new modern API or site from scratch.

**Comment by kataras** [comment]
Maybe you tested it without clear your browser's cache? Because I cant reproduce this issue, thanks.

**Comment by Near-Zhang** [comment]
Thx for your detailed explanation

After I cleaned up the browser's cache， the route got the expected situation.

**Comment by kataras** [comment]
You're welcome @Near-Zhang, glad to help
