### ISSUE TITLE
ctx.ReadJSON - readObjectStart: expect { or n, but found ", error found in #1 byte of

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1296]
Hi, 

I am sending some HTML-Form data by Ajax and trying to read them using `ctx.ReadJSON`, but I am getting an error as :

```
{"error":"readObjectStart: expect { or n, but found \", error found in #1 byte of ...|\"{\\\"usernam|..., bigger context ...|\"{\\\"username\\\":\\\"iris\\\",\\\"name\\\":\\\"Kataras Iris\\\",\\|..."}
```

data, I am sending via Ajax is - 

```
JSON.stringify({ "username": username, "name": name, "password": password, "cpassword": cpassword })
```

and data that goes to the URL is as below:

```
{"username":"iris","name":"Kataras Iris","password":"abcdef","cpassword":"abcdef"}
```

and I am reading the data in IRIS using below code:

```
var register Register
if err := ctx.ReadJSON(&register); err != nil {
	ctx.StatusCode(iris.StatusBadRequest)
	ctx.JSON(map[string]string{"error": err.Error()})
	return
}
```
My Register struct is:

```
type Register struct {
	FullName  string `json:"name" vaild:"required,length(3|100)"`
	Username  string `json:"username" valid:"required,length(3|100)"`
	Password  string `json:"password" valid:"required,length(8|30)~Password should be between 8-30 characters"`
	Cpassword string `json:"cpassword" valid:"required,length(8|30)~Password should be between 8-30 characters"`
}
```

The full error message is:

```
{"error":"readObjectStart: expect { or n, but found \", error found in #1 byte of ...|\"{\\\"usernam|..., bigger context ...|\"{\\\"username\\\":\\\"iris\\\",\\\"name\\\":\\\"Kataras Iris\\\",\\|..."}
```

**Comment by kataras** [comment]
The `ctx.ReadJSON` uses the standard `encoding/json` package of the Go programming language, except when `iris.WithOptimizations` is set - then it uses the jsoniter package instead. Your question is a general golang question and the problem I see here is that you send an **Escaped JSON form with extra quotes**, so either fix it on your client-side or use the `strconv.Unquote(original)` in the server-side.

Thanks.

**Comment by rebootcode** [comment]
Thanks bro @kataras 

I got that fixed using `JSON.parse(JSON.stringify(~form~array))`

**Comment by 1157467793** [comment]
I also encountered the same problem as the landlord, but I don't know how to solve it

**Comment by kataras** [comment]
@1157467793 can you post both client and server side code so I can fix it for you?
