### ISSUE TITLE
question about websocket'connectionID Generator

### ISSUE THREAD

**Issue by bluesky1024** [kataras/iris#1299]
according to the code source. The default id generator is as follows
```go
type Config struct {
	// IDGenerator used to create (and later on, set)
	// an ID for each incoming websocket connections (clients).
	// The request is an input parameter which you can use to generate the ID (from headers for example).
	// If empty then the ID is generated by DefaultIDGenerator: randomString(64)
	IDGenerator func(ctx context.Context) string
        ...
}
```

It seems that it's not so convenient to use the connection id in distribute enviroment. Is it possible to transform "randomString(64)" to some distribute IDgenerator such as "snowflake" algorithm?

**Comment by kataras** [comment]
Yes, why not? Just generate it based on configuration and return it there, you can override this func. Please chech the [neffos project](https://github.com/kataras/neffos) instead, as it will replace the existing websocket module at the upcoming release as Readme.md noticed.

**Comment by bluesky1024** [comment]
Thanks for your replay. I'm learning go by constructing service by iris these days. Your project source code is very helpful. And I'm looking forward the new websocket module.

**Comment by kataras** [comment]
Thanks @bluesky1024 , you can read the discussions on the neffos project, you are not the only one learning Go through Iris' code, I am pushing myself to the limits every single time and I am still learning.
