### ISSUE TITLE
Request: Rendering html template to string

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#130]
I would like to use the Renderer in a string format instead of writing directly to the ResponseWriter. Doing so would allow me to write template strings to a database, implement a cache system, or to send html/text email.

Ideally, this would work very similar to how we do it now:

`str, err := ctx.RenderStr("myTemplate.html", "layout.html", interface{})`

**Comment by kataras** [comment]
What about a more 'freedom' choice like 
```go
var myWriter io.Writer

myWriter,err := ctx.ExecuteTemplate("myTemplate.html", interface{} ,"layout.html") 

```
?

**Comment by kataras** [comment]
Done,
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	iris.Get("/", func(ctx *iris.Context) {
		if str, err := ctx.RenderString("page1.html", nil); err != nil {
			panic(err)
		} else {
			println(str)
			ctx.Write("The plain content of the template is: %s", str)
		}

	})

	// you can do the same without context also using iris.Templates() :
	if str, err := iris.Templates().RenderString("page1.html", nil); err != nil {
		panic(err)
	} else {
		println(str)
	}

	//

	println("Server is running at: 8080")
	iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
> implement a cache system, or to send html/text email.

Iris have already cache system, you don't need to do this.  Send e-mails is a good usage, thanks for the suggestion!

**Comment by ryanbyyc** [comment]
Pulled, tested, looks great!

What might be a good idea is to default `RenderString` to not use templates rather than inherit the template. Creating a "blank.html" template with just `{{yield}}` seems excessive.

Alternatively, allow `ctx.RenderString("page1.html", "", nil)`

Or leave it as is and just document the limitations. Thanks for the help!

**Comment by kataras** [comment]
I don't understand, layout and context are already optional parameters, no need to have {{ yield }}

**Comment by kataras** [comment]
the structure is ` page.html,context interface{},layout ... string` you can call Render/RenderString just only with: ` 'page.html',nil`

**Comment by ryanbyyc** [comment]
If my app is already configured with a layout in main.go:
`cfg.Render.Template.Layout = "layouts/default.html"`

Then RenderString tries to use that layout. Resetting the layout to: `iris.Config().Render.Template.Layout = ""` Doesn't seem to work either.

**Comment by kataras** [comment]
Yes of course you can't change that at runtime, so you need a way to disable layout for a particular template file ?

**Comment by ryanbyyc** [comment]
> Edit2: Done 

Looks wicked! NoLayout is definitely the way to go.

**Comment by kataras** [comment]
## Update

See `app.View`, example:  https://github.com/kataras/iris/blob/master/_examples/view/write-to/main.go#L31.

For string you can use a `bytes.Buffer` as the writer and get its `.String()`.
