### ISSUE TITLE
can I set a middleware jwt globally, but escape some url checking?

### ISSUE THREAD

**Issue by robert7git** [kataras/iris#1300]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by robert7git** [comment]
maybe like this:

```go
	jwtHandler := jwtMd.New(jwtMd.Config{
		ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {return []byte(jwtSecret), nil},
		SigningMethod: jwt.SigningMethodHS256,
		IgnoreUrls: ignorePaths,
	})
```

**Comment by kataras** [comment]
You dont need this, jwt middleware has a 'Serve' and 'CheckJWT'  methods. Register a middleware by app.Use, make ur checks there, if ignored url then just ctx.Next and return otherwise call the jwt's .Serve and return or CheckJWT and do ctx.Next if returned nil error othereise handle the error.

**Comment by robert7git** [comment]
Good, Solved the problem.
