### ISSUE TITLE
How to get int or array from form?

### ISSUE THREAD

**Issue by TheCGDF** [kataras/iris#1301]
`ctx.FormValue("foo")` return string.
What should I do if I want to get int32 or []string?

When I use `http://localhost/test?foo=one&foo=two`,
 `ctx.FormValue("foo")` return `one` only.

Must I use `ctx.ReadForm( struct{} )` ?

**Comment by kataras** [comment]
No, look. 

The standard net/http#Request.FormValue returns a `string` as well, but it does it by returning the first element of its **parsed-once form[0]**. 

Iris has similar behavior, the `ctx.FormValues()` returns a `map[string][]string`, from there you can take your value as `[]string` based on the key, e.g. `values := ctx.FormValues(); fooSlice := values["foo"]`. The values **are parsed once**, nil-checks are necessary of course.

**Comment by TheCGDF** [comment]
Thanks. I followed your words and it works.

**Comment by kataras** [comment]
Glad to help!
