### ISSUE TITLE
uuid.NewV4() build error in url-shortener 

### ISSUE THREAD

**Issue by mnoster** [kataras/iris#1303]
`uuid.NewV4()`  does not return two assignments, which is throwing an error upon build.

`id, _ := uuid.NewV4()`

**Should be changed to:**

`id := uuid.NewV4()`

https://github.com/kataras/iris/blob/master/_examples/tutorial/url-shortener/factory.go#L14

**Comment by mnoster** [comment]
https://github.com/kataras/iris/pull/1304

**Comment by kataras** [comment]
Already fixed on the [v11.2.0 PR](https://github.com/kataras/iris/pull/1175) but thanks!
File: https://github.com/kataras/iris/blob/v11.2.0/_examples/tutorial/url-shortener/factory.go#L14
