### ISSUE TITLE
routes overriding and matching

### ISSUE THREAD

**Issue by amrnt** [kataras/iris#131]
I wrote a simple app:

```go
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/posts", func(c *iris.Context) {
		c.JSON(200, "/posts")
	})

	iris.Get("/posts/:id", func(c *iris.Context) {
		c.JSON(200, "/posts/show")
	})

	iris.Get("/posts/new", func(c *iris.Context) {
		c.JSON(200, "/posts/new")
	})
	iris.Listen(":8080")
}
```

Going to `/posts/123` or `/posts/new` will show `/posts/show`.

If I put the `/posts/new` router before `/posts/:id`,  `/posts/new` will show `/posts/new`, but `/posts/123` will return 404 error.

**Comment by kataras** [comment]
@amrnt You cannot do that with Iris, :id is a dynamic parameter. Use a different pattern. I decided this 'limitation' for good reason.I had bad experience with old web frameworks which allows you to set dynamic parameters and static parameters within the same pattern ( /posts/:id and /posts/news) (nodejs,java and more). Use of more described route helps you. When/if your app will be big you will remember my words.

**Comment by amrnt** [comment]
@kataras Hi, thanks for pointing this out. Is this limitation for a performance concerns? I'm just wondering. I'm trying to implement an application thats a reflection of a Phoenix/Rails app.

The default routes for a resource/restful is as shown in this page: http://www.phoenixframework.org/docs/routing#section-resources

To have a diff pattern I tried to implement this, but still have the same issues!

```go
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/posts", func(c *iris.Context) {
		c.JSON(200, "/posts")
	})
	iris.Get("/posts/_/new", func(c *iris.Context) {
		c.JSON(200, "/posts/new")
	})
	iris.Get("/posts/:id", func(c *iris.Context) {
		c.JSON(200, "/posts/:id")
	})
	iris.Get("/posts/:id/edit", func(c *iris.Context) {
		c.JSON(200, "/posts/:id/edit")
	})

	iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
> Is this limitation for performance concerns?
Yes , and the reason I 'explained' before

if you want to have `posts:id, posts/new/` a solution exists but again...

```go
	iris.Get("/posts/*action", func(ctx *iris.Context){
		action := ctx.Param("action")
		if action == "new" {
			// it's posts/new page
                         ctx.JSON(200, "/posts/new")
		}else{
			// it's posts/:id page OR the /posts/:id/edit, you have to find out now action will be the rest path AFTER the localhost/posts/
			//doSomething with the action which is the id
                       c.JSON(200, "/posts/:id")
		}
	})

```

The problem with your previous example was the '_'. I I wrote you have to be more described with your routes `/posts/_/new`  is not. Delete it and your code runs perfectly
