### ISSUE TITLE
Is ctx.FormValues() works correctly now?

### ISSUE THREAD

**Issue by r3eg** [kataras/iris#1310]
Good afternoon!

Today after release Iris v 11.2.2 I have problem with parsing POST request throught ctx.FormValues method with  iris.WithoutBodyConsumptionOnUnmarshal option. 

https://github.com/kataras/iris/commit/bf3f3065645606c4b51f2382eff0c6dcd334547d#diff-15cce7299aae8810bcab9b0bf9a2fdb1

The problem I think is that request body read before ParseMultipartForm

`if keepBody {
		// on POST, PUT and PATCH it will read the form values from request body otherwise from URL queries.
		if m := ctx.Method(); m == "POST" || m == "PUT" || m == "PATCH" {
			body, err := ioutil.ReadAll(ctx.request.Body)
			if err != nil {
				return nil, false
			}

			bodyCopy = body
		} else { // else we don't need this behavior.
			keepBody = false
		}
	}`

And here ctx.request.Body is empty...
`ctx.request.ParseMultipartForm(ctx.Application().ConfigurationReadOnly().GetPostMaxMemory())`

There was no problem with ctx.FormValues before release. Could you help me?

**Comment by kataras** [comment]
You are correct @r3eg give me some time

**Comment by kataras** [comment]
Thanks @r3eg, you are correct, fixed by replaced with `ctx.GetBody`, sorry for that. You can use the patch by:

`go get github.com/kataras/iris@master`

Or/and wait for the 11.2.3 minor version which will contain a small new feature too.

**Comment by r3eg** [comment]
Thanks! @kataras Works now, and I usually get changes from master branch

**Comment by kataras** [comment]
You're welcome @r3eg , I thank you for the report, can you send me your e-mail so I can give you PDF and online access to the Iris e-book?

**Comment by r3eg** [comment]
@kataras Yes of course, r3eg@yandex.ru
