### ISSUE TITLE
How can i set the token at the websocket's request header?and i use client.go of example.

### ISSUE THREAD

**Issue by l306287405** [kataras/iris#1317]
Just like it:
`

	ctx.SetHeader("Authorization","bar")

	c, err := client.Connect(ctx, namespace)

	if err != nil {

		panic(err)

	}
`

**Comment by kataras** [comment]
Hello @l306287405,

First of all the [websocket](https://github.com/kataras/neffos)'s `client.Connect(ctx, namespace)` excepts a **Go std contet.Context for timeouts and deadlines, not an iris.Context**, `iris.Context` is for Iris (server-side).

The `client configuration` is done on the [client, err := neffos.Dial](https://github.com/kataras/neffos/wiki/Upgraders-and-dialers) function (before the `client.Connect(ctx, namespace)`).

So, if you want to set headers on client you do it based on the `neffos.Dialer` you are using (gorilla or gobwas), both of them support header setting by-default, so you don't have to do anything with neffos itself. **Actually, we have an [example](https://github.com/kataras/neffos/blob/c6806f19261108fbc1281e21faa79d7193b36097/_examples/scale-out/main.go#L282-L292) of this**.

If you use [gobwas dialer](https://github.com/kataras/neffos/blob/master/gobwas/dialer.go#L17): `gobwas.Dialer(gobwas.Options{Header: gobwas.Header{"X-Username": []string{username}}}),`

```go
import "github.com/kataras/neffos"
import "github.com/kataras/neffos/gobwas"

client, err := neffos.Dial(
// Optional context cancelation and deadline for dialing.
nil,
// The underline dialer, can be also a gobwas.Dialer/DefautlDialer or
// a gorilla.Dialer/DefaultDialer.
//
// Here we wrap a custom gobwas dialer in order to send the
// username among, on the handshake state.
gobwas.Dialer(gobwas.Options{Header: gobwas.Header{"X-Username": []string{username}}}),
// The endpoint.
"ws://localhost:8080/path",
// The namespaces and events, can be optionally shared with the server's.
namespaces)
```


If you use [gorilla dialer](https://github.com/kataras/neffos/blob/master/gorilla/dialer.go#L17):  `gorilla.Dialer(&gorilla.Options{}, http.Header{"X-Username": []string{username}}),`

```go
import "net/http"
import "github.com/kataras/neffos"
import "github.com/kataras/neffos/gorilla"


client, err := neffos.Dial(
nil,
// Here we wrap a custom gorilla dialer in order to send the
// username among, on the handshake state.
gorilla.Dialer(&gorilla.Options{}, http.Header{"X-Username": []string{username}})
"ws://localhost:8080/path",
namespaces)
```

**Comment by l306287405** [comment]
Thank you for your help.
My english is so bad,and i saw the jwt auth,but how can i use the func `jwt.FromAuthHeader()` on iris.

**Comment by kataras** [comment]
No worries about english, it's fine!

`jwt.FromAuthHeader` is an iris-specific function, it's a `TokenExtractor`.

A `TokenExtractor` is just a `func(ctx context.Context) (string, error)` type.

Any custom TokenExtractor  can be passed to the [jwt middleware](https://github.com/iris-contrib/middleware/tree/master/jwt)'s configuration.

The **default** token extractor is FromAuthHeader already (Authorization: Bearer $TOKEN), so you **don't really need to set it**.

We have also an example of this case too, it can be found [here](https://github.com/iris-contrib/middleware/blob/5f3a20f489c42276e74d54c49393b521945a8c02/jwt/_example/main.go#L48).

```go
import "github.com/iris-contrib/middleware/jwt"

j := jwt.New(jwt.Config{
	Extractor: jwt.FromAuthHeader, // <- here
	SigningMethod: jwt.SigningMethodHS256,
})
```

Now, if you only want "Authorization: $TOKEN" (without the "Bearer") then you can pass a **custom TokenExtractor** like:

```go
import "github.com/iris-contrib/middleware/jwt"

j := jwt.New(jwt.Config{
    Extractor: func(ctx context.Context) (string, error) {
        authHeader := ctx.GetHeader("Authorization")
        return authHeader ,nil
    }, // <- here
    SigningMethod: jwt.SigningMethodHS256,
})
```

Hope these helped @l306287405

**Comment by l306287405** [comment]
I got it,Thank you again,and you are hansome.
