### ISSUE TITLE
Problem with Broadcasting

### ISSUE THREAD

**Issue by majidbigdeli** [kataras/iris#1318]
@kataras  I have Issue with

```
server.Broadcast(nil,neffos.Message{
To: userID,
Namespace: variable.Agent,
Event:     "notif",
Body:      neffos.Marshal(nf),	
})
```
i use gobwas.DefaultUpgrader

when i use  server.Broadcast in loop it is work but But not very good.
You can test yourself.
 i open multiple browser tap with same userId(socketId) 

server.brodacast not send all message in loop;

you can see cron example .

```
c.write(neffos.Message{
To: userID,
Namespace: variable.Agent,
Event:     "notif",
Body:      neffos.Marshal(nf),	
})

```

write() mthod  work very very good
 but it send message to one tap (last) with same userId .

I'm going to send it to all the tabs. with same userId

**Comment by majidbigdeli** [comment]
For example in my test i have 58 message ,
i broadcast messages in loop with `server.Brodacast `   tap 1 get 17 messages from 58 messages !!!!!!!! 
![image](https://user-images.githubusercontent.com/26275762/62331259-aa9b1c00-b4d0-11e9-8d67-7ba8fdf23d86.png)

tap 2 get 16 messages see  

![image](https://user-images.githubusercontent.com/26275762/62331423-209f8300-b4d1-11e9-9775-978390386127.png)

tap 3 get 20 messages 

finally 25 messages from 58 messages not send .

![image](https://user-images.githubusercontent.com/26275762/62331665-d4087780-b4d1-11e9-8b54-5512dcdd2de2.png)
  

with write method in cron example all messages from 58 messages send with success 
but it send message to one tap (last) with same userId .
I'm going to send it to all the tabs. with same userId

**Comment by kataras** [comment]
Hello @majidbigdeli I am sure something is going on, I am checking it as we speak, but meanwhile, could you please transfer this issue to the correct repository? https://github.com/kataras/neffos/issues/new

Thanks!

**Comment by majidbigdeli** [comment]
@kataras  Hello.
Kataras I'm sure. server broadcast in loop send 30 message from 58 mes

**Comment by majidbigdeli** [comment]
@kataras  I send message [neffos chat](https://gitter.im/neffos-framework/community)

**Comment by majidbigdeli** [comment]
@kataras  I am sure Server.Brodacast dont work  in loop  with two sokect Id

```
	for k, m := range output {
		uID := strconv.Itoa(k)
		server.Broadcast(nil, neffos.Message{
			To:        uID,
			Namespace: variable.Agent,
			Event:     "notif",
			Body:      neffos.Marshal(m),
		})
	}
```
 my result with picture 
user 1 get notif but user2 dont get notif
![image](https://user-images.githubusercontent.com/26275762/62376567-28553b00-b556-11e9-861e-ffd2af6fb415.png)

**Comment by kataras** [comment]
@majidbigdeli I made a test on that case and it seems that it works here...need more details on your app.

Here is the code I used, which simulates your case with 1000 clients (u have 57) and 1000 messages every 2 seconds, total of 10000 messages:

```go
package main

import (
	"log"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	"github.com/kataras/neffos"
	"github.com/kataras/neffos/gorilla"

	"github.com/robfig/cron"
)

/*
	stress-test broadcasting every 2seconds (10 times, 10000 messages)
	to 1000 clients with the same ID.
*/

const (
	namespace    = "agent"
	clientEvent  = "notify"
	serverEvent  = "ackNotify"
	clientConnID = "client"
	every        = "2s"

	clientsCount  = 1000
	messagesCount = clientsCount * 10
)

type notification struct {
	Title   string `json:"title"`
	Subject string `json:"subject"`
	Message string `json:"message"`
}

var message = neffos.Message{
	To:        clientConnID,
	Namespace: namespace,
	Event:     clientEvent,
	Body: neffos.Marshal(notification{
		Title:   "master notification",
		Subject: "master",
		Message: "a notification message",
	}),
}

var (
	serverEvents = neffos.WithTimeout{
		Namespaces: neffos.Namespaces{
			namespace: neffos.Events{
				serverEvent: func(ns *neffos.NSConn, msg neffos.Message) error {
					return nil
				},
			},
		},
	}

	received uint32

	clientEvents = neffos.Namespaces{
		namespace: neffos.Events{
			clientEvent: func(ns *neffos.NSConn, msg neffos.Message) error {
				n := atomic.AddUint32(&received, 1)
				log.Printf("Total Received: %d", n)
				return nil
			},
		},
	}
)

func main() {

	// connect all and then start cron.
	server := startServer()
	time.Sleep(200 * time.Millisecond)

	wg := new(sync.WaitGroup)
	wg.Add(clientsCount)
	wgClose := new(sync.WaitGroup)
	wgClose.Add(clientsCount)

	now := time.Now()

	for i := 0; i < clientsCount; i++ {
		go startClient(wg, wgClose)
	}

	wg.Wait()
	startCron(server)

	wgClose.Wait()
	log.Printf("Done in: %s", time.Since(now))
}

func startServer() *neffos.Server {
	server := neffos.New(gorilla.DefaultUpgrader, serverEvents)
	server.IDGenerator = func(w http.ResponseWriter, r *http.Request) string {
		username := r.Header.Get("X-Username")
		if username == "" {
			log.Fatalf("expected a username but got nothing")
		}

		return username
	}

	go func() {
		log.Fatal(http.ListenAndServe(":8080", server))
	}()

	return server
}

func startCron(server *neffos.Server) {
	c := cron.New()
	_, err := c.AddFunc("@every "+every, func() {
		if atomic.LoadUint32(&received) == messagesCount {
			c.Stop()
			server.Close()
			return
		}

		pushNotifications(server)
	})

	if err != nil {
		log.Fatal(err)
	}

	c.Start()
}

func pushNotifications(server *neffos.Server) {
	server.Broadcast(nil, message)
}

var dialer = gorilla.Dialer(&gorilla.Options{}, http.Header{"X-Username": []string{clientConnID}})

var connectedN uint32

func startClient(wg *sync.WaitGroup, wgClose *sync.WaitGroup) {
	client, err := neffos.Dial(nil, dialer, "ws://localhost:8080", clientEvents)
	if err != nil {
		log.Fatal(err)
	}

	_, err = client.Connect(nil, namespace)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Total Connected: %d", atomic.AddUint32(&connectedN, 1))
	wg.Done()

	<-client.NotifyClose

	wgClose.Done()
}
```

**Comment by majidbigdeli** [comment]
@kataras it is not my case . you send message every  2 seconds.

please test this . non stop

```
var message = neffos.Message{
	To:        clientConnID,
	Namespace: namespace,
	Event:     clientEvent,
	Body: neffos.Marshal(notification{
		Title:   "master notification",
		Subject: "master",
		Message: "a notification message",
	}),
}

	for i := 0; i < userCount; i++ {
		server.Broadcast(nil, message)
	}
```

**Comment by kastmgnru** [comment]
I have the same problem.
If you send two messages at once, the client will receive only the last:

`
server.Broadcast(nil, websocket.Message{To: connId, IsNative: true, Body: []byte("test;huest")})
server.Broadcast(nil, websocket.Message{To: connId, IsNative: true, Body: []byte("test2;huest2")})
`

Only one of these messages will be received.
![image](https://user-images.githubusercontent.com/44933947/62505263-9757bb80-b804-11e9-9ce6-ae6fed82ea87.png)

**Comment by kataras** [comment]
Now I see, you mean simultaneously @majidbigdeli @kastmgnru, I though the problem was sending to the same ID over different sockets, that's why I tested that case. Now it's much more clear, expect a fix soon.

**Comment by kataras** [comment]
OK the problem is not appearing when broadcasting using redis or nats, so the issue is inside the local single-machine broadcaster channel. I found something but need to investigate it more, expect a fix until tomorrow.

**Comment by majidbigdeli** [comment]
@kataras  Did you find the problem?

**Comment by kataras** [comment]
@majidbigdeli you have two ways to fix that now:

- Now the `server.Broadcast` accepts more than one message at once
- A new `server.SyncBroadcaster` field is added, which if set to true then changes the default behavior and any Broadcast is in-sync (therefore, **if set to true each broadcast sends its own messages to the current alive connections**). Update to neffos 0.0.10 and set `server.SyncBroadcaster = true` before server start and you should be fine, if not please comment below.

Thanks a lot!

**Comment by majidbigdeli** [comment]
@kataras  thank you . 
I'm testing it tonight.

**Comment by majidbigdeli** [comment]
@kataras  Thanks a lot! 
yes . `server.SyncBroadcaster = true`   it is fine in my test . 

Why is server.UseStackExchange okay but server.Broadcast no?

I've read your code. But I not found  problem,
Did you find a problem?

**Comment by kataras** [comment]
You are welcome @majidbigdeli !!

Yes I know the problem and fixed it but to answer your question why when use redis or nats this does not raise - it's because I made the API for a `StackExchange` to manage Broadcast messages by their own for better performance, so these messages are directly handled by redis or nats and they work like our local `SyncBroadcaster = true` already.
