### ISSUE TITLE
Recommend a compatible websocket library

### ISSUE THREAD

**Issue by insionng** [kataras/iris#132]
https://github.com/igm/sockjs-go/
https://github.com/sockjs/sockjs-client

**Comment by kataras** [comment]
But they are not  compatible...

**Comment by qskousen** [comment]
I believe @kataras is planning on building his own simple web socket
library, similar to socket.io but with only web socket support, no
fallback. This is per the stated goals for v3 in the readme.

**Comment by insionng** [comment]
Its support for  IE 6, 7, 8, 9, 10,Chrome,Firefox,Safari,Opera,Konqueror..

**Comment by insionng** [comment]
@kataras ，@qskousen Well, I just recommend a good thing!

**Comment by kataras** [comment]
Yes I know but you write a false title, please change it, these libraries are NOT compatible with Iris, but don't worry I will found a solution for this too :) Your help is appreciated !

**Comment by insionng** [comment]
Well, the title might not be quite right. I mean support for websocket, but could be interpreted to support IRIS. I only recommend an interesting library if you can't use it, ignore it.

**Comment by kataras** [comment]
Yes but you can't just throw links, it says net/http , we are using fasthttp and I am making my best to make my own implementions for fasthttp, no other framework based on fasthttp have so many things as Iris, I will try to do my own pure but fast easy websocket library, as usual, if I failed then I will try to conver someone else code until then you suggest and wait for the results :P

**Comment by insionng** [comment]
Very good, I'm looking forward to the progress of the iris.

**Comment by borag** [comment]
+1 for a good websocket client

**Comment by kataras** [comment]
We have a client side library with the same functionality as the server's side (send,receive, join, leave room and so on)
