### ISSUE TITLE
method with lower case was ignored

### ISSUE THREAD

**Issue by WingGao** [kataras/iris#1320]
Method with lower case such as `get` was ignored with `404`.
I found this when a client try to send requests with all lower headers.

**Comment by kataras** [comment]
@WingGao This seems perverse, since HTTP requires that the method be sent in uppercase.

**Comment by kataras** [comment]
`net/http` does not uppercase that for routing, so Iris. However, there is other way to accept both lowercase and uppercase without touch the `Method()` there (which underline router uses and will have a slight, but again, performance cost).

**Comment by kataras** [comment]
For anyone who may want this:

```go
import "strings"
import "github.com/kataras/iris"
// [...]

app := iris.New()
app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
    r.Method = strings.ToUpper(r.Method)
    router(w,r)
})

// [...]
```
