### ISSUE TITLE
alphabetical is there any omission？

### ISSUE THREAD

**Issue by bibibi-bug** [kataras/iris#1322]
alphabeticalEval = MustRegexp("^[a-zA-Z ]+$")

app.Get("/{firstname:alphabetical}", func(ctx iris.Context) {
   ctx.Writef("firstname: %s\n", ctx.RouteName())
   ctx.Next()
}, func(ctx iris.Context) {
   ctx.Writef("firstname (string): %s\n", ctx.Params().Get("firstname"))
})

$ curl -XGET http://localhost:8080/hello%20world
firstname: GET/{firstname:alphabetical}
firstname (string): hello world

**Comment by kataras** [comment]
@bibibi-bug If I accept your proposal something like this: `http://localhost:8080/hello world` will not match to alphabetical. **Space is there not by mistkake**. If you want something else just make a new regexp function on the `string` type or register a new macro as shown at: https://github.com/kataras/iris/wiki/Routing-path-parameter-types

**Comment by bibibi-bug** [comment]
Ok, I see

**Comment by kataras** [comment]
Tell me your issue @bibibi-bug maybe I can help you more, what do you want to do exactly?
