### ISSUE TITLE
My websocket Package has not this struct(websocket.Config)

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1326]
I can't use websocket with iris even if I import the package called iris/websocket
Please help me...QAQ

**Comment by CulionBEAR** [comment]
![1365](https://user-images.githubusercontent.com/35328438/62440136-536fa280-b781-11e9-80a5-83d0b14e1ec0.png)

**Comment by kataras** [comment]
@CulionBEAR we wrote a whole article about it,

- https://dev.to/kataras/iris-version-11-2-released-22bc
- https://github.com/kataras/iris/wiki/Websockets
- https://github.com/kataras/iris/tree/master/_examples/websocket
- https://github.com/kataras/iris/blob/master/HISTORY.md#tu-23-july-2019--v1120

**Comment by Laotanling** [comment]
I also do not know how to configure the websocket without websocket.Config{} ?
