### ISSUE TITLE
Just curious about the China phrase everywhere

### ISSUE THREAD

**Issue by fangli** [kataras/iris#1329]
I'm a Chinese no offense but just curious, is the "I love China" phrase a meme or something unusual happened to this project? :)

**Comment by kataras** [comment]
47% of the feedback and almost 60% of bug reports are coming from Chinese people. Chinese and Vietnamese people are the only who translated the whole Iris Book to their native language.

It is not "unusual" think for me to publically tell  "thank you Chinese people, we love you for the support". People are rarely helped me in my entire life so, and I learnt to say thank you when needed.

**Comment by fangli** [comment]
I see, so you mean it literally, thanks anyway you did a great job!
Actually golang is so popular in China and I used this project a lot, I'd like to donate you a coffee☕️

**Comment by kataras** [comment]
Thank you @fangli. I really appreciate it, that was totally unexpected! Your github username:link will be visible in https://iris-go.com index page (If you have any privacy issues, send me an [e-mail](mailto:iris-go@outlook.com)).

**Comment by pihao** [comment]
@fangli 
https://github.com/julienschmidt/httprouter/issues/148
