### ISSUE TITLE
Incompatible with jquery.form.js

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#133]
I use jquery.form.js send post in the template file requests to Iris, Iris receiving any post parameter values,if I do not use jquery.form.js submit no problem.
``` html
<form id="form" method="post" action="/handler">
    <p><input type="text" name="name" value="test"></p>
    <p><button type="submit">Submit</button></p>
</form>

<script>
    $(function () {
        $('#form').submit(function () {
            var options = {
                type: 'post',
                dataType: 'json',
                resetForm: false
            };
            $(this).ajaxSubmit(options);
            return false;
        });
    })
</script>
```

``` go
func Handler(ctx *iris.Context) {
    log.Println(ctx.FormValue("name"))
}
```

**Comment by kataras** [comment]
Can I ask you? you think Iris provides jquery automatically?

Your example is working: 
```html
<form id="form" method="post" action="/form_action">
    <p><input type="text" name="name" value="test"></p>
    <p><button type="submit">Submit</button></p>
</form>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#form').submit(function () {
            var options = {
                type: 'post',
                dataType: 'json',
                resetForm: false
            };
            $(this).ajaxSubmit(options);
            return false;
        });
    })
</script>


```
```go
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("form.html", nil)
	})
	iris.Post("/form_action", func(ctx *iris.Context) {
		println(string(ctx.FormValue("name")))
	})
	println("Server is running at: 8080")
	iris.Listen(":8080")
}

```

**Comment by dxvgef** [comment]
I imported jquery.js and jquery.form.js files, removing them only to show here, but I try to not get the parameter values, then I now try again.

**Comment by kataras** [comment]
Can you post me the full source code ? this example you saw me is working

**Comment by dxvgef** [comment]
waiting, I finally try again.

**Comment by kataras** [comment]
jquery.form.js is not necessary now, as you see I didn't imported it lol

**Comment by kataras** [comment]
@dxvgef jquery.form.js is not necessary now (2016) , as you see I didn't imported it... If your problem solved close this issue or post the source code in order to help you further, thanks !

**Comment by dxvgef** [comment]
@kataras Thank you for your reply, but your sample code is not ajax submitted, because after I clicked "Submit" button to trigger the page jump, it should not jump page, so print out the value of this parameter is not ajax submission.

**Comment by dxvgef** [comment]
@kataras  AJAX submit should be like,

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form id="form" method="post" action="/form_action">
    <p><input type="text" name="name" value="test"></p>
    <p><button type="submit">Submit</button></p>
</form>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#form').submit(function () {
            var options = {
                type: 'post',
                dataType: 'json',
                success: function (response) {
                    alert(JSON.stringify(response));
                },
                error: function (response) {
                    alert(JSON.stringify(response));
                },
                resetForm: false
            };
            $(this).ajaxSubmit(options);
            return false;
        });
    })
</script>
</body>
</html>
```

``` go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	iris.Config().Render.IsDevelopment = true
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("form", nil)
	})
	iris.Post("/form_action", func(ctx *iris.Context) {
		println(string(ctx.RequestURI()))
		println(string(ctx.FormValue("name")))
	})
	println("Server is running at: 8080")
	iris.Listen(":8080")
}
```

**Comment by raitucarp** [comment]
@dxvgef can you print the content-type? Because I have the same issue when posting via postman with incorrect content-type

**Comment by dxvgef** [comment]
@raitucarp @kataras  The content-type is "application/x-www-form-urlencoded; charset=UTF-8"

``` go
iris.Post("/form_action", func(ctx *iris.Context) {
	println(string(ctx.RequestURI()))
	println(string(ctx.Request.Header.ContentType()))
	println(string(ctx.FormValue("name")))
})
```

**Comment by dxvgef** [comment]
@kataras This bug also exists in Iris 3.0-alpha version.

**Comment by kataras** [comment]
```go
iris.Post("/form_action", func(ctx *iris.Context) {
    println(string(ctx.PostBody())) // prints name=test
})
```
You have acccess to the whole post body, its your application's responsibility to manage it, each case has different method of using this PostBody.

**Comment by raitucarp** [comment]
@dxvgef what about ```go ctx.PostFormValue("name")```?

**Comment by dxvgef** [comment]
@raitucarp This function also does not work.

**Comment by dxvgef** [comment]
@raitucarp I define the ajax contentType option to "application / json" or , but `ctx.FormValue()` does not work.

``` html
<form id="form" method="post" action="/form_action">
    <p><input type="text" name="name" value="test"></p>
    <p><button type="submit">Submit</button></p>
</form>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#form").submit(function(e) {
            var postData = $(this).serializeArray();
            $.ajax({
                url : $(this).prop("action"),
                type: $(this).prop("method"),
                data : postData,
//                contentType: "application/x-www-form-urlencoded",
                contentType: "application/json"
            });
            e.preventDefault();
            e.unbind();
            $(this).submit();
        });
    });
</script>
```

**Comment by raitucarp** [comment]
@dxvgef Few days ago I had the same issue as you describe here, but I encounter it when playing with postman. And I handle application/json data such that with this:
```go
data := ctx.PostBody()
err := json.Unmarshal(data, &myType)
```

**Comment by dxvgef** [comment]
@raitucarp Thank you! But jquery is not a XML or JSON format after the form serialization(serializeArray()).

**Comment by raitucarp** [comment]
@dxvgef yeah I do agree, but actually the main point of ajax is its content type. We need to ensure and strict the content type before handle the data.Therefore, the api endoint should be well designed at the first place.

**Comment by kataras** [comment]
@dxvgef  what about PostBody? it worked for me, just take it and parse yourself the content of the particular form, do not lazy.

**Comment by dxvgef** [comment]
@kataras I have only myself to resolve ctx.PostBody () return value, this is the only way?

**Comment by kataras** [comment]
for your case use, yes I suppose.. did you try with $.post ?

**Comment by dxvgef** [comment]
No, I just try to the $.ajax and jquery.form plugin,I'm ready to try the $.post

**Comment by kataras** [comment]
@dxvgef I will create a different function for your case use after, ok? I will write here the name of the function when I finish

**Comment by dxvgef** [comment]
@kataras Thank you very much! I was watching Tango source is how to solve this problem.

**Comment by kataras** [comment]
Then why you can't solve it? are these frameworks they exists yet? :P

**Comment by dxvgef** [comment]
Tango and other frameworks does not have this problem, I think Iris would not be such this problem.
I used Iris development projects to the half, now, because of this issue to stop the.
I now want to seriously look at a variety of framework code how to parse the post data, I can not focus on the business processes of the project :(

**Comment by dxvgef** [comment]
I can not use jquery.form, but jquery's $.ajax() or $.post() the same can not let Iris's ctx.FormValue() to get the parameter values

**Comment by dxvgef** [comment]
@kataras I tested was found, form tag enctype attribute value is "multipart/form-data", ctx.FormValue() will work.

**Comment by dxvgef** [comment]
I read httpfast source code, find a way to solve the problem, because the content-type value is "application / x-www-form-urlencoded; charset = UTF-8", which is unanticipated.

I tried to change the value of the content-type:
``` html
<script type="text/javascript">
    $(function () {
        $("#form").submit(function( event ) {
            $.ajax({
                type: "POST",
                url: "/form_action",
                contentType: "application/x-www-form-urlencoded",
                data: $(this).serialize()
            });
            event.preventDefault();
        });
    });
</script>
```
But FormValue still not working, so I was wrong to think that is not "content-type" reasons .

I try to change the github.com/valya/fasthttp/string.go file of 66 lines, now everything is normal!
So I think we should write a plugin to modify the content-type value,you do not need to do about it, because I know how to solve :P
Thanks @kataras and @raitucarp!

**Comment by dxvgef** [comment]
Now, I just need to change the $ .ajax of "contentType" parameter is "application/x-www-form-urlencoded" , everything is normal, no need to write plugin
I'm sorry to bother you, and thank you again

**Comment by kataras** [comment]
@dxvgef So do we need to do something, you told something about /fasthttp/string.go:66 is that the fix? if yes then maybe we should write a middleware or something.. or you solve it without any iris/fasthttp core changes?

**Comment by dxvgef** [comment]
Yes,now i solve it without any iris or fasthttp core changes, just change the contentType parameter value of $.ajax, write Iris middleware can solve this problem, but now I feel no need of, cause here [https://github.com/valyala/fasthttp/issues/100](https://github.com/valyala/fasthttp/issues/100) LOL

**Comment by kataras** [comment]
This was the problem? lol I couldn't imagine it anyway, we wait for fasthttp fix, when it does just upgrade fasthttp and you should be ok

**Comment by dxvgef** [comment]
Ok, Wait for fasthttp fix it, I think it is very easy to do changes, my time is 4:40, I'm going to bed, good night~

**Comment by kataras** [comment]
Good night my friend, thanks for your contribution

**Comment by kataras** [comment]
Fixed with: https://github.com/valyala/fasthttp/issues/100#issuecomment-220634100 
Full Upgrade with ` go get -u github.com/kataras/iris`
