### ISSUE TITLE
ctx.ViewData not work with JetEngine

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1330]
Hi @kataras,

I'm testing the JetEngine as a view. Unfortunately, the default ctx.ViewData is not passed to JetEngine. In my opinion this would be a Braking Change.

Wouldn't it make sense to make this usable in the same way as with the other engines?

Example:
```GO
ctx.ViewData("demo", 123)
ctx.View("pages/index.jet")
```

Returns in Logs: `[ERRO] 2019/08/07 12:38 Jet Runtime Error("pages/index.jet":4): identifier "demo" is not available in the current scope map[]`

**Comment by kataras** [comment]
Hello @Dexus,

This is Jet parser's thing. It accepts only `jet.Ranger` and `jet.Renderer`. 
The `ViewData` does work here if you set the key to empty, and call once `ctx.ViewData("", Ranger or Renderer implementations)` or just pass it to the `ctx.View`'s last input argument.

- To set runtime template variables use the `jet.AddRuntimeVars(ctx context.Context, vars jet.JetRuntimeVars)`

**Comment by kataras** [comment]
@Dexus, it's fixed. Please test it by yourself, example updated as well.

https://github.com/kataras/iris/blob/fe9bfbceced520fb253b03f6db1d99c7a859a2b1/_examples/view/template_jet_0/main.go#L125-L137
