### ISSUE TITLE
Hi，can you helpe me about the iris's log?

### ISSUE THREAD

**Issue by wyanlord** [kataras/iris#1331]
Hello, I want to use iris's log function to split log files by day.
But I didn't find a good way.

**Comment by kataras** [comment]
There is an example on the _examples folder for that but it start saving by day on the application run, you can modify it to run every day change (count manually or use external solutions like CRON). It's not so hard and not relative to Iris, general golang. If you still have problem @wyanlord you can write down your code so  I can be more helpful.

**Comment by wyanlord** [comment]
I resolved it with "github.com/lestrrat-go/file-rotatelogs"
```go
	// 创建文件日志，按天分割，日志文件仅保留一周
	w, err := rotatelogs.New("runtime/logs/iris_web.%Y%m%d.log")
	checkErr("CreateRotateLog", err)

	// 设置日志
	logrus.SetOutput(w)
	logrus.SetFormatter(&logrus.JSONFormatter{})
	logrus.SetReportCaller(true)
```
