### ISSUE TITLE
iris11.2.3 install error 

### ISSUE THREAD

**Issue by imandarava** [kataras/iris#1334]
hi I have a error 
 when I  use  

go get -u github.com/kataras/iris@v11.2.3

then:
G:\go\api-rent\src\go.mod:26: invalid module version "v11.2.3": invalid character 'o' in literal null (expecting 'u')

why? 
GO11MODULE=on
golang version 12.7

**Comment by kataras** [comment]
@imandarava I copy-pasted and it works on a clean machine, maybe you made a mistake on your shell? No idea, try copy-paste that in your terminal window and press <enter>:

```sh
go get github.com/kataras/iris/@v11.2.3
```
