### ISSUE TITLE
When I use middleware, I use hero to inject the session and find that the session for each request is new, not unique, and I can't get the data I stored when I logged in.

### ISSUE THREAD

**Issue by doCore** [kataras/iris#1338]
When I use middleware, I use hero to inject the session and find that the session for each request is new, not unique, and I can't get the data I stored when I logged in.

Code example：
 
  func Configure(s *startup.Startup) {
	ssManager :=s.Sessions.Start

	admin := mvc.New(s.Party("/admin"))
	{
		hero.Register(ssManager)
		admin.Router.Use(hero.Handler(middleware.Authentication))

		repo := repository.NewPostRepository(s.Xorm)
		postService := services.NewPostService(repo)

		admin.Configure(func(app *mvc.Application) {
			app.Register(postService)
			app.Handle(new(adminCtr.HomeController))
		})

		//post
		admin.Party("/post").Configure(func(app *mvc.Application) {
			app.Register(postService)
			app.Handle(new(adminCtr.PostController))
		})
	}

	tourist := mvc.New(s.Party("/admin/login"))
	tourist.Configure(func(app *mvc.Application) {
		repo := repository.NewUserRepository(s.Xorm)
		userService := services.NewUserService(repo)
		app.Register(userService,ssManager)
		app.Handle(new(adminCtr.UserController))
	})
}

func Authentication(ctx iris.Context, session *sessions.Session){
	i := session.Get("User")
	user,ok:= i.(entitys.User)
	if ok && user.ID > 0 {
		ctx.Next()
	}else {
		ctx.Redirect(fmt.Sprintf("/admin/login?returnurl=%s", url.QueryEscape(ctx.Request().RequestURI)))
	}
}

**Comment by kataras** [comment]
Hello @doCore,

I see that you are binding the session manager twice, first in the `hero` package-level default registry at:

```go
hero.Register(ssManager)
```

And the second spot is in your mvc app at:
```go
app.Register(userService,ssManager)
```

I want you to know that **mvc by-default shares the global dependencies you register at `hero.Register`** so there is no need to re-bind it (to disable that behavior just set [mvc.HeroDependencies](https://github.com/kataras/iris/blob/master/mvc/mvc.go#L28) to false).

The code you posted is not a reproducible to us, so I can't run it to give you an answer, as far as I see you didn't do anything wrong and it should work. My example is working fine. Can you post a code that I can copy-paste-run and see your issue please?

**Comment by doCore** [comment]
hello @ @kataras 
Can you write an example of MVC?  

The routing code is as follows：
`func Configure(s *startup.Startup) {
	admin := mvc.New(s.Party("/admin"))
	{
		hero.Register(s.Sessions.Start)
		admin.Router.Use(hero.Handler(middleware.Authentication))

		repo := repository.NewPostRepository(s.Xorm)
		postService := services.NewPostService(repo)

		admin.Configure(func(app *mvc.Application) {
			app.Register(postService)
			app.Handle(new(adminCtr.HomeController))
		})

		//post
		admin.Party("/post").Configure(func(app *mvc.Application) {
			app.Register(postService)
			app.Handle(new(adminCtr.PostController))
		})


	}

	tourist := mvc.New(s.Party("/login"))
	tourist.Configure(func(app *mvc.Application) {
		repo := repository.NewUserRepository(s.Xorm)
		userService := services.NewUserService(repo)
		app.Register(userService)
		app.Handle(new(adminCtr.UserController))
	})
}

func Authentication(ctx iris.Context, session *sessions.Session){
	i := session.Get("User")
	user,ok:= i.(entitys.User)
	if ok && user.ID > 0 {
		ctx.Next()
	}else {
		ctx.Redirect("/admin/login")
	}
}

type UserController struct {
	Ctx iris.Context
	Session *sessions.Session
	UserService *services.UserService
}

const userIDKey = "User"

func (this *UserController) PostLogin() interface{} {
	var loginViewModel model.LoginViewModel
	if err := this.Ctx.ReadForm(&loginViewModel); err != nil {
		return mvc.View{
			Name:"admin/views/user/login.html",
			Layout:iris.NoLayout,
			Data:iris.Map{"errormsg": "error"},
		}
	}
	u, b,s := this.UserService.Login(loginViewModel.UserName, loginViewModel.PassWord)
	if !b {
		return mvc.View{
			Name:"admin/views/user/login.html",
			Layout:iris.NoLayout,
			Data:iris.Map{"errormsg": s},
		}
	}

	this.Session.Set(userIDKey,u)
	return mvc.Response	{
		Path: "/admin",
	}
}

`
Can you tell me whether the Session in UserController and Authentication is the same? When I test it, I redirected to /admin in the PostLogin function. When I went to the Authentication middleware, I found that the Session could not get the value of set in PostLogin.

**Comment by kataras** [comment]
Ah ok no problem @doCore, I'll set that issue as invalid, it's fine. Don't hesitate to ask in the future!
