### ISSUE TITLE
Would you like to support redis cluster in session?

### ISSUE THREAD

**Issue by woody712** [kataras/iris#1339]
Though the connection pool of inner built is enough in most conditions, I still want to use sessions with redis cluster, because of my company's existing cluster

**Comment by kataras** [comment]
Hello @woody712,

If your company uses redis and redis clusters then you can just create your custom redis sessiondb (see: https://github.com/kataras/iris/tree/master/sessions/sessiondb/redis for implementation) or edit the existing one, test and push a PR, I [can do](https://github.com/kataras/neffos/blob/a9ba1acf254d77ecf9ee2aaded93716e50a181b3/stackexchange/redis/stackexchange_redis.go#L25) it but I can't directly test it, so i think it's better to let that for you or a co-worker of yours.

**Comment by majidbigdeli** [comment]
@woody712  , @kataras  

I can do it with radix but does redigo support it?

**Comment by kataras** [comment]
redigo does not support cluster, it has another library for it. Radix can support and I already did it locally but it is slow on scan with prefix (the method that sessiondb uses to fetch values)...I will see what I can do and we can convert our versions and push the better implementation one into Iris.

**Comment by kataras** [comment]
@woody712 You can use clusters now with `Config.Clusters` field but only if `Config.Driver` is `sessiondb/redis.Radix()` ( at least for now).

**Comment by majidbigdeli** [comment]
@kataras 
yes. Sometimes radix has some problems too.
for example  

when I Use "SET" Action to store a large number of key - values at a time. it is slow

or can not use "MSET" Action  to store  Struct 
[Link](https://github.com/mediocregopher/radix/issues/79)

for example
```
err := client.Do(radix.FlatCmd(nil, "MSET","Key", Struct{
    firstname"val1",
    lastname: "val2",
})
```

but radix code is clean with good feature for example
it is very good Support for pubsub,

**Comment by kataras** [comment]
Yes this is why it's used on `neffos` that pubsub was requirement as I explained back then, but in Iris session databases we don't need this feature. However, about my above comment on slow on get keys of `radix`, I found the issue: https://github.com/kataras/iris/issues/1328#issuecomment-522952979

**Comment by majidbigdeli** [comment]
@kataras  for #1328  
 i found this https://github.com/mediocregopher/radix/blob/master/scanner.go

```
// ScanOpts are various parameters which can be passed into ScanWithOpts. Some
// fields are required depending on which type of scan is being done.
type ScanOpts struct {
	// The scan command to do, e.g. "SCAN", "HSCAN", etc...
	Command string

	// The key to perform the scan on. Only necessary when Command isn't "SCAN"
	Key string

	// An optional pattern to filter returned keys by
	Pattern string

	// An optional count hint to send to redis to indicate number of keys to
	// return per call. This does not affect the actual results of the scan
	// command, but it may be useful for optimizing certain datasets
	Count int
}
```
for 100000 key
 Just enough  Set count to 100000

**Comment by majidbigdeli** [comment]
I saw [this](https://github.com/kataras/iris/issues/1328#issuecomment-522952979) comment. 
Bravo . it is true

**Comment by kataras** [comment]
Yeah @majidbigdeli thank you, I pushed the commit. The COUNT is 300 thousand and it iterates until cursor returned by redis is `0` (when iteration is done/ it's full iter) I also added an improvement on the `redigo` driver one (before it was limited to nine billion nine hundred ninety nine million nine hundred ninety nine thousand nine hundred ninety nine).

**Comment by woody712** [comment]
Thx all above
