### ISSUE TITLE
GZip for files

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#134]
Now GZIP compression occurs for html-templates. You can add it to the files?

**Comment by kataras** [comment]
It's already for files, if you use the iris.StaticFS -> it compress your files before serviring, and serve compressed files(the fastest method to serve files, only on fasthttp and iris)

**Comment by egorsmkv** [comment]
Okay. How to close the output folder content if using ``iris.StaticFS``?

**Comment by egorsmkv** [comment]
I need to give the compressed files of styles and icons (images).
``StaticFS`` does not suit me, it creates files **.fasthttp.gz** and ``StaticWeb`` not support GZIP.

**Comment by kataras** [comment]
you want to gzip the file on each request? this is not faster , better to make it without gzip. I'm not here to answer general golang , iris is not a tutorial but I will give you an example.
First you need to import
```go
import "compress/gzip"
```
create a gzip writer: 
```go
	out = gzip.NewWriter(io.Writer) // it takes the original writer, you can use the ctx.Response.BodyWriter())
```
read the file you want to serve with gzip compression with package io, and write the readed bytes to the gzipwriter
```go
out.Write(theReceivedbytes []byte)
```
close the gzip writer
```go
out.Close()
```

and last step is add the response header which allows client to know that it will receive a compressed response
```go
	ctx.Response.Header.Add("Content-Encoding", "gzip")
```

**Comment by egorsmkv** [comment]
Okay.

Thanks!

**Comment by kataras** [comment]
You dissapointed but this is the truth my friend, anyway thanks for your comments!

**Comment by kataras** [comment]
```go
// StaticServe serves a directory as web resource
// it's the simpliest form of the Static* functions
// Almost same usage as StaticWeb
// accepts only one required parameter which is the systemPath ( the same path will be used to register the GET&HEAD routes)
// if second parameter is empty, otherwise the requestPath is the second parameter
// it uses gzip compression (compression on each request, no file cache)
StaticServe(systemPath string, requestPath ...string) 
```go

## Examples

```go
func main() {
  iris.StaticServe("./assets")
  // Serves all files inside this directory to the GET&HEAD route: 0.0.0.0:8080/assets
  // using gzip compression ( no file cache, for file cache with zipped files use the StaticFS)
  iris.Listen(":8080")
}

```

```go
func main() {
  iris.StaticServe("./static/myfiles","/assets")
  // Serves all files inside filesystem path ./static/myfiles to the GET&HEAD route: 0.0.0.0:8080/assets
  iris.Listen(":8080")
}

```

I don't want to dissapoint anyone, happy iris coding my friend @egorsmkv

**Comment by egorsmkv** [comment]
Awesome! Thanks, @kataras!

**Comment by kataras** [comment]
If you want test it for any case, I just made one test for it, post here  if any issue appears, you're welcome  ;)

**Comment by egorsmkv** [comment]
Okay!
