### ISSUE TITLE
Websocket缺少了ConnectionFunc怎么办？

### ISSUE THREAD

**Issue by czl0325** [kataras/iris#1340]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/2100549/63315356-78e1dc00-c33d-11e9-9e68-543e1f1ceb54.png">
这段代码缺少了ConnectionFunc,Config,OnConnection,ClientSource等参数，要怎么办？
<img width="552" alt="image" src="https://user-images.githubusercontent.com/2100549/63315386-9a42c800-c33d-11e9-8415-e6fc999a32bd.png">

**Comment by majidbigdeli** [comment]
What is your Iris version?

I think you've updated Iris.
 it is a breaking change in web socket in iris  v 11.2.

you can downgrade your iris version or it is better to use the new version of iris Web Socket. 
It has a lot of features with better performance.

**Comment by czl0325** [comment]
install by.     go get -u github.com/kataras/iris

how can I look version???

**Comment by czl0325** [comment]
> What is your Iris version?
> 
> I think you've updated Iris.
> it is a breaking change in web socket in iris v 11.2.
> 
> you can downgrade your iris version or it is better to use the new version of iris Web Socket.
> It has a lot of features with better performance.

install by. go get -u github.com/kataras/iris

how can I look version???

**Comment by majidbigdeli** [comment]
> install by. go get -u github.com/kataras/iris



install by. go get -u github.com/kataras/iris 
with it command you get last version  of iris .
So your Iris version is 11.2



> how can I look version???

Check VERSION file in
GOPATH\src\github.com\kataras\iris 

or if you have go module you can  check in go.mod file

**Comment by majidbigdeli** [comment]
My suggestion is to modify your code based on these examples 
https://github.com/kataras/iris/tree/master/_examples/websocket

**Comment by kataras** [comment]
Follow @majidbigdeli 's guidelines and you will be fine @czl0325. If you need to convert ur whole webscoket API, just send me an e-mail with your code attached and I can do it absolutely free.
