### ISSUE TITLE
_examples/mvc/login/ run error

### ISSUE THREAD

**Issue by lmq1117** [kataras/iris#1341]
when i copied all file from _examples/mvc/login/ and run : go run main.go ,Error appears，
.\main.go:31:5: app.HandleDir undefined (type *iris.Application has no field or method HandleDir)
main.go:31 should be 
app.StaticWeb("/public", "./web/public")
instead of app.HandleDir("/public", "./web/public")

**Comment by kataras** [comment]
You need to upgrade to the latest Iris version @lmq1117. A simple `go get -u` will not do the work, you need to put the `@v11.2.8` or `@master` in the end, read the [Installation page](https://github.com/kataras/iris/wiki/Installation)
