### ISSUE TITLE
MVC: service injecting fails

### ISSUE THREAD

**Issue by zheeeng** [kataras/iris#1343]
```go
package parse

import (
	"github.com/kataras/iris/mvc"
)

type Parser interface {
	Parse() string
}

type parser struct {
	inner string
}

func InitParser() Parser {
	return &parser{
		inner: "hello",
	}
}

func (p *parser) Parse() string {
	return p.inner
}

func App(app *mvc.Application) {
	parser := InitParser()

	app.Register(parser)

	app.Party("/parse").Configure(ParseApp)
}

func ParseApp(app *mvc.Application) {
	service := NewService()
	app.Register(service)

	app.Handle(new(controller))
}

type Service interface {
}

type service struct{}

func NewService() Service {
	return &service{}
}

type controller struct {
	Service Service
	Parser  Parser
}

func (c *controller) Get() string {
	return c.Parser.Parse()
}
```

This code will throw Internal Server Error:
```
Trace: runtime error: invalid memory address or nil pointer dereference
```
cos the `c.Parser` is `nil`

If we change the controller to
```go
type controller struct {
	Parser  Parser
}
```
There is no problems.

**Comment by kataras** [comment]
@zheeeng The problem here is that `*parser implements the Service` too as `Service` does not contain any method and it's just an `interface{}` which binds to everything.

**Comment by kataras** [comment]
This is the same as you posted before: https://github.com/kataras/iris/issues/1342.

These works:

```go
type controller struct {
	Parser  Parser
}

type controller struct {
	Parser  Parser
        Service Service // (or interface {}, it's the same in your case)
}
```

And that's because it tries to match it by order of registering, because the `Service` field accepts anything, and you bind the `*parser` so it does bind to it and stops there, all binding values are registered so it does not continue to the `Parser` field (in Iris controllers, a binding value cannot be binded to more than one field of struct or input parameter of a function)

**Comment by kataras** [comment]
Hello @zheeeng,

With the recent commit we have added the ability to customize and change the order of fields and their valid available registered values (if more than one) through the `mvc.Application.Sorter` field. It defaults to nil but you can change it. We have a builtin sorter(SortByNumMethods) which does exactly what you want here.


```go
func App(app *mvc.Application) {
        app.SortByNumMethods()

	parser := InitParser()
	app.Register(parser)
	app.Party("/parse").Configure(ParseApp)
}
```
