### ISSUE TITLE
[Question] Params implementation

### ISSUE THREAD

**Issue by xXLokerXx** [kataras/iris#1348]
Hi all, i have some questions: 
1.- Theres a way to get all the params into a structure/interface?

- i like to use some function to get all params (query, url) in some structure or interface.
  i know theres a function to get the url params (ctx.URLParams()) and function to get the query ones (ctx.ReadJSON(&interface)) but i cant find one that catch both.

2.- Theres a way to send json params to GET route?
 - i only can obtain the url params and i want to send as json in body part the params

i really apreciate the help.

**Comment by kataras** [comment]
1. `ctx.ReadQuery`
2. `ctx.ReadQuery(&obj)` and `ctx.JSON(obj)`.
