### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cstraightOLM** [kataras/iris#1350]
On "go get" I am receiving two errors from pulling the master branch. The errors are
..github.com/kataras/iris/context/problem.go:274:15: undefined math.Round
..github.com/kataras/iris/context/problem.go:286:34: undefined math.Round

1. go get master branch

I expect to be able to pull the master branch without issues.

 - OS: Ubuntu 16.04 LTS

**Comment by cstraightOLM** [comment]
Never mind, this has to do with running a go version below 1.10 when math.Round was introduced. I will just need to upgrade go.

**Comment by kataras** [comment]
Exactly @cstraightOLM. Installation section: https://github.com/kataras/iris/wiki/Installation. It requires at least Go version 1.12. Download link: https://golang.org/dl.
