### ISSUE TITLE
Why not upgrade bindata tool?

### ISSUE THREAD

**Issue by yuyi98** [kataras/iris#1351]
It can not install from "go get github.com/kataras/bindata/cmd/bindata", when i compile it, i found it genatate the same result as go-bindata tool, without GzipAsset() and GzipAssetNames() function, and it coundn't work!

**Comment by kataras** [comment]
I don't see the problem, you `go get` but `GzipAssetXXX` don't exist? Use any `bindata` alternative you want as they implement the `Asset, AssetNames and AssetInfo` functions you will be more than OK to use the [iris.FileServer](https://github.com/kataras/iris/issues/1283).

**Comment by yuyi98** [comment]
Sorry, It's my fault, I download all the source file and compile it, it can work correctly!

**Comment by kataras** [comment]
No problem @yuyi98, don't hesitate to ask in the future!
