### ISSUE TITLE
https://github.com/kataras/iris/blob/master/core/router/path.go 存在缺陷

### ISSUE THREAD

**Issue by 2017RXL** [kataras/iris#1352]
**Describe the bug**
![Uploading image.png…]()
`https://github.com/kataras/iris/blob/master/core/router/path.go`
在242、 243行中的strings.RepacesAll，我在查strings中没有该方法。请核实

**To Reproduce**

**Comment by kataras** [comment]
Please upgrade your Golang version to the latest one, `strings.ReplaceAll` is a valid Go function. Go to: https://golang.org/dl
