### ISSUE TITLE
github.com\kataras\iris\core\router\path.go:242:10: undefined: strings.ReplaceAll[BUG]

### ISSUE THREAD

**Issue by 2017RXL** [kataras/iris#1354]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33270841/64093105-9aa18100-cd89-11e9-9c99-fc13b1299295.png)

**To Reproduce**
1. [...]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**Additional context**

**Comment by kataras** [comment]
@2017RXL Please read the Installation section: https://github.com/kataras/iris/wiki/Installation. It requires at least Go version 1.12. Download link: https://golang.org/dl.

---------------

DUPL: https://github.com/kataras/iris/issues/1352

**Comment by 2017RXL** [comment]
谢谢了

**Comment by kataras** [comment]
别客气 @2017RXL
