### ISSUE TITLE
How can I mock an iris.Context for use in tests?

### ISSUE THREAD

**Issue by MichaelSnowden** [kataras/iris#1357]
I have some methods that use an iris.Context as input, and I'd like to mock the context so I can test those methods outside of production. How can I mock an iris Context?

**Comment by kataras** [comment]
Hello @MichaelSnowden, you can mock context's methods you want to test through overriding their implementations, read more at: https://github.com/kataras/iris/wiki/Routing-override-context.

But why you want to mock the whole `iris.Context` and not your handlers or the `iris.Context.ResponseWriter` (which is an `http.ResponseWriter`) instead?

By the way, you can also check this one: https://github.com/kataras/iris/wiki/Testing

**Comment by MichaelSnowden** [comment]
Thanks!
