### ISSUE TITLE
set Template Engine and program got exit.

### ISSUE THREAD

**Issue by zyanho** [kataras/iris#136]
my program got exit without any error msg. i could not debug it.

my env:
go 1.6.2
iris: just now run go get -u -v github.com/kataras/iris

some code like, this code run success and waiting to accept request.
```
api := iris.New()
api.Config().Render.Template.Engine = iris.HTMLEngine
api.ListenWithErr(":8080")
```

but when i change iris.HTMLEngine to iris.PongoEngine, like this.
and i run this code,  my program got exit without any error msg
```
api := iris.New()
api.Config().Render.Template.Engine = iris.PongoEngine
api.ListenWithErr(":8080")
```

thanks for help.

**Comment by kataras** [comment]
@zyanho  This is strange, can you test 
```go
iris.Config().Render.Template.Engine = iris.PongoEngine
iris.ListenWithErr(":8080")
``` 

and tell me if that works on your machine?

**Comment by kataras** [comment]
@zyanho Your example is working, I just tested it

```go

package main

import (
	"github.com/kataras/iris"
)

func main() {
	api := iris.New()

	api.Config().Render.Template.Engine = iris.PongoEngine

	api.Get("/", func(ctx *iris.Context) {

		err := ctx.Render("index.html", map[string]interface{}{"username": "iris", "is_admin": true})
		// OR
		//err := ctx.Render("index.html", pongo2.Context{"username": "iris", "is_admin": true})

		if err != nil {
			panic(err)
		}
	})

	println("Server is running at :8080")
	api.ListenWithErr(":8080")
}
```

Please try again,  @zyanho  maybe you didn't close the server from the previous process ?
