### ISSUE TITLE
[v11.2.8] I found one question when used `context.Context.Redirect` to Redirect.

### ISSUE THREAD

**Issue by conero** [kataras/iris#1361]
In my project I want to make simple check for the database connect, then go redirect to url(`/~/install`) if error directly. And there is not global method to redirect in iris but only  `context.Context.Redirect` I found. Maybe there has way to it, but I want just simple and lightweight like there is error then go to `/~/install`. Anyway codes like:

```go
// codes ...
server := iris.New()
engine, err := xorm.NewEngine(vtype, dsn)
if err != nil{
	server.Get("/~/install", func(ctx context.Context){
		// codes ...
	})


	//[Notice] I want to use some iris globe method to redirect,
	//         so made `OnErrorCode` to handler
	server.OnErrorCode(iris.StatusNotFound, func(ctx context.Context) {
		ctx.Redirect("/~/install")
		//[Notice] In fact before go to the page print a link [<a href="/~/install">Not Found</a>], 
		//       I don't hope the standstill but go to url. So what I shold do?
		return
	})
}else{
	// checking pass
	innerRouterM1()
	innerRouterM2()
	innerRouterM3()
}
// codes ...
```

**In brief, there are two questions**:
- If possible that Iris has a global way to redirect but not only `context.Context`?
- How to rediect the url without staying by `a` tag page when use `server.OnErrorCode`?

**Comment by kataras** [comment]
Server-side redirect is done by just sending an HTTP header (`Location`) and a status code, see [context.Redirect](https://github.com/kataras/iris/blob/df882273e21952a316236174123fc09096b49aad/context/context.go#L2431) and RFC https://tools.ietf.org/html/rfc7231#section-6.4.

I dont understand the questions, redirect is part of http request-response cycle == request handler == func(ctx iris.Context) { ...}.

However, if you mean that you want a service that will do redirections, you can use iris proxy or iris redirect server. See [NewProxy(hostAddr string, target *url.URL) *Supervisor](https://github.com/kataras/iris/blob/df882273e21952a316236174123fc09096b49aad/core/host/proxy.go#L70) and [NewRedirection(hostAddr string, target *url.URL, redirectStatus int) *Supervisor](https://github.com/kataras/iris/blob/df882273e21952a316236174123fc09096b49aad/core/host/proxy.go#L86).

Please provide a usecase, example or an net/http alternative so I can help you further.

Thank you @conero

**Comment by conero** [comment]
@kataras Thank a lot. Now I can handler the case by using `ctx.Redirect("/~/install", 302)`. The Others I should think about more.
