### ISSUE TITLE
Two connects how to join the same room?

### ISSUE THREAD

**Issue by l306287405** [kataras/iris#1362]
https://github.com/kataras/neffos/wiki/Rooms
This wiki is simple for me...
In the func: OnNamespaceConnected , I make them to join this room, the name is "test".
I guess it my way is wrong:
```
websocket.OnNamespaceConnected: func(nsConn *websocket.NSConn, msg websocket.Message) error {
	room,err:=nsConn.JoinRoom(nil,"test")
	if err!=nil{
		nsConn.Conn.Close()
		return errors.New("加入房间失败,关闭连接")
	}

	room.Emit("chat",[]byte(fmt.Sprintf("welcome [%s] join this room [%s]",user["nickname"],room.Name)))

}
```

And i write these codes in "chat" action:
```
"chat": func(nsConn *websocket.NSConn, msg websocket.Message) error {
	room:=nsConn.Room("test")
	msg_body:=fmt.Sprintf("[%s] in [%s,%s] sent: %s", user["nickname"],room.Name,room, string(msg.Body))
	room.Emit("chat",[]byte(msg_body))
}
```

It is not work...
Unable send messages both them...

**Comment by kataras** [comment]
Hello @l306287405,

This is working here, example at: https://github.com/kataras/neffos/tree/master/_examples/basic. Could you please send me a code snippet that I can simply copy-paste and reproduce the issue?

**Comment by l306287405** [comment]
I run the example, typed nickname and room, but when i was send a message, it throw an error from html:
`Uncaught ReferenceError: toID is not defined at HTMLButtonElement.f.onclick (bundle.js:1)`

**Comment by l306287405** [comment]
`go run main.go client`
This command is running. Thank you for your help.
