### ISSUE TITLE
[BUG] html/template: "movie/index.html" is undefined

### ISSUE THREAD

**Issue by yyccQQu** [kataras/iris#1363]
i have some problem,please help me,thanks~~~
https://github.com/mini-docker/secondsKill/tree/master/yyccQQu-iris
```
http://localhost:8080/hello
html/template: "movie/index.html" is undefined
```

**Comment by kataras** [comment]
Hello @yyccQQu, if you run the program using go build and copy-paste the executable outside of this folder then you need to copy yours `web/views` directory too like any resource in Go. If you want to **embed** the assets inside your executable program then you may want to try out the `.Binary(Asset, AssetNames)` of the view engine. Learn more at: https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app

**Comment by yyccQQu** [comment]
thanks,my god! my goversion is 10.x => 13.x and goland`s mod  2problem ==> your example is ok!
thank you very much~~ 
                                         -- golang a beginner

**Comment by yyccQQu** [comment]
> Hello @yyccQQu, if you run the program using go build and copy-paste the executable outside of this folder then you need to copy yours `web/views` directory too like any resource in Go. If you want to **embed** the assets inside your executable program then you may want to try out the `.Binary(Asset, AssetNames)` of the view engine. Learn more at: https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app

when I use mvc example, it`s also error at localhost:8000/hello !
![image](https://user-images.githubusercontent.com/32674176/66288627-1734fb80-e904-11e9-89f2-33fc1bc9b1ea.png)

**Comment by kataras** [comment]
@yyccQQu MVC example is OK as well, please run it with `go run main.go`, if you move the executable move the `./web/views` folder as well otherwise use the `Binary` method as explained above. Screenshot:

![iss44](https://user-images.githubusercontent.com/22900943/66403623-92271080-e9ef-11e9-8f22-d17a52e453a3.png)

**Comment by yyccQQu** [comment]
Thank you very much! It`s goland`s problem! Only handwritten `go run main.go`. I don`t konw Why did the start button of the editor get a compile error, and the related path 'movie/index.html' could not be found.The example you gave me can run directly with the compiler!~~~~~~~~
