### ISSUE TITLE
[BUG] when method is post, route path is invalid with dynamic route

### ISSUE THREAD

**Issue by wyanlord** [kataras/iris#1365]
POST /api/login/{version:string}/base

It is not work.

**Comment by BenLampson** [comment]
I think this is your bug...
First one:
Is that Iiris binding? Or Iris.mvc binding?
And give us some demo we can review this bug.

**Comment by wyanlord** [comment]
> I think this is your bug...
> First one:
> Is that Iiris binding? Or Iris.mvc binding?
> And give us some demo we can review this bug.

POST /api/login/{version:string}/base

**Comment by wyanlord** [comment]
> I think this is your bug...
> First one:
> Is that Iiris binding? Or Iris.mvc binding?
> And give us some demo we can review this bug.

Router: POST /api/login/{version:string}/base
If you request the api with "/api/login/v1/base", the iris web framework cann't parse the router conrrectly.

**Comment by BenLampson** [comment]
![image](https://user-images.githubusercontent.com/15414750/65745939-f2849b00-e12f-11e9-9868-51084c63c6d4.png)
There haven't error or bug in your case.

**Comment by wyanlord** [comment]
真的有bug啊，兄弟。请看下面的代码

```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Post("/api/login/{version:string}/base", func(ctx iris.Context) {
		ctx.WriteString("login base")
	})

	app.Post("/api/login/v1/google", func(ctx iris.Context) {
		ctx.WriteString("login google")
	})

	app.Run(iris.Addr(":8080"))
}
```

如果你使用这个路径 `/api/login/v2/base` 来请求，是没有问题的
但是你换个路径 `/api/login/v1/base` 来请求，问题就出现了

这就无法解析了，会报404，有时候啥都不报。

我想这个应该是个bug吧。

**Comment by BenLampson** [comment]
.......................................................................................
你还是关了你的issue吧..
你的代码是这个样子的..意味着,你的route路径存在一个歧义.
你应该是不明白route是怎么实现的吧.
你简单以最基本的方式理解的话,可以认为他是一个正则匹配........
然而你的两次绑定,其中一次告诉URL的构造器,我其中有一个//中间是一个string的 parameter name是version的参数.
而另外一个你直接声明定义了这么一个v1,来约束.
从restful的定义结构上来讲,上面的叫匹配,下面的叫资源约束.
这两个事情完全就不可能出现的.
V1也属于version:string的匹配包含项中.....

**Comment by BenLampson** [comment]
赶紧关了吧,先去看看restful的约束定义...

**Comment by kataras** [comment]
@wyanlord Your code works.

```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Post("/api/login/{version:string}/base", func(ctx iris.Context) {
		ctx.WriteString("login base")
	})

	app.Post("/api/login/v1/google", func(ctx iris.Context) {
		ctx.WriteString("login google")
	})

	app.Run(iris.Addr(":8080"))
}
```
`POST: /api/login/parameter/base`

![iss](https://user-images.githubusercontent.com/22900943/65798334-0359fe80-e17a-11e9-9e4e-3797b84d8299.png)

`POST: /api/login/v1/google`

![iss2](https://user-images.githubusercontent.com/22900943/65798359-179dfb80-e17a-11e9-82ce-8aa7c6907719.png)
