### ISSUE TITLE
Does iris support hot reload?

### ISSUE THREAD

**Issue by chaseSpace** [kataras/iris#1366]
I dont want to use nginx to loading blance to support hot reload now, and i also haven't find out docs about that. thanks in advance!

**Comment by kataras** [comment]
Hello @chaseSpace,

Iris does not have a built'n tool for that. However I've built a simple solution for that at: https://github.com/kataras/rizla but if you need more than this or if you find issues with that please try searching online, any tool will work with Iris e.g. https://github.com/codegangsta/gin
