### ISSUE TITLE
using different Layout

### ISSUE THREAD

**Issue by ElhamAfshar** [kataras/iris#1368]
I need to use different Layout in my project

**Comment by ElhamAfshar** [comment]
how can I use two different Layout ?
`app.RegisterView(iris.HTML("web/view", ".html").Layout("layout.html"))`

**Comment by kataras** [comment]
Layout is single per view. You can change the `default` layout defined on your `iris.HTML(...).Layout(...)` from the handler itself, through `context.ViewLayout("other_layout.html")` method.

https://github.com/kataras/iris/blob/c8e73f4f4df2c725f91f8aa659f9f60a7154c039/context/context.go#L717-L728
