### ISSUE TITLE
session of redis storage problems

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#137]
In Iris version 2.3.2, sessions of redis storage configuration Addr parameter is `iris.Config ().Addr ="127.0.0.1:6379 "`, now Addr parameter is not present, how to configure it?
And I did not find `github.com/kataras/iris/config` package in version 2.3.2.

**Comment by kataras** [comment]
I am not recommending of using 2.3.2 now any more ( book is updated to v3.0.0-alpha6) , v3.0.0-alpha6 at the current features is the most stable version, update to the current version and after do an upgrade when final v3  arrives.

Anyway with v2.3.2 we hand't config package, you have to do it from the `github.com/kataras/iris/sessions/providers/redis' `redis.Redis.Config`

**Comment by dxvgef** [comment]
Are you sure recommend 3.0? It is still alpha state, if update framework, my code will be great changes in it?

**Comment by kataras** [comment]
> Are you sure recommend 3.0? It is still alpha state

Yes I know its alpha but it 's the most stable version iris has, for the current features. Do this upgrade to alpha-6 and then wait for final v3 (it will take long)

> if update framework, my code will be great changes in it?

Yes your code will have many changes( but you are not the only person who did this upgrade on production, it will take you 10-15 minutes)  but e-book is very good written , you can also read the [HISTORY](HISTORY.md) which will help you to the conversions, do it and if you can't fix something just speak me on gitter

**Comment by dxvgef** [comment]
Okay, I'm going to modify the code to be compatible with 3.0.

**Comment by kataras** [comment]
@dxvgef  How is that goes?

**Comment by dxvgef** [comment]
@kataras I have to change the code compatible with Iris version 3.0, and now everything is working, no problem.

**Comment by kataras** [comment]
Okay, nice I'm happy about this

**Comment by dxvgef** [comment]
Thank you! :)
