### ISSUE TITLE
I want to build/mock iris.Context for unit test

### ISSUE THREAD

**Issue by dablyo** [kataras/iris#1371]
i've read the #1357,but it cann't meet my requirement

//i register handler for url
regis.Get("/api/get", getTheOne)
//the handler
func getTheOne(ctx iris.Context){
  para1 := ctx.URLParamDefault("para1", "")
  businessRecord := ctx.Values().Get("business_record")
  rec,ok := businessRecord.(*TheBusinessRecord)
  ......
  ctx.StatusCode(200)
  ctx.JSON(......)
  ...
}

//the fake ResponseWriter
type myResponseWriter struct {
	io.Writer
}
func (r *myResponseWriter) Header() http.Header  { 
	return http.Header{"Content-Type": {"application/json"}}
}
func (r *myResponseWriter) WriteHeader(int) {
	fmt.Println("write header") 
}
//the unit test
func TestGetTheOne(t *testing.T){
  app := iris.New()
  ctx := context.NewContext(app)
  req, err := http.NewRequest("GET", 
	  "http://127.0.0.1:8080/api/get?para1=para1", nil)
  //
  businessRecord := &TheBusinessRecord{......}
  p := ctx.Values()
  p.Set("business_record",businessRecord)
  
  resp := &myResponseWriter{}
  ctx.BeginRequest(resp,req)

  getTheOne(ctx)
  assert.Equal(t,200,ctx.GetSatusCode())
  //other assert....
}

//go test -v -run TestGetTheOne, then errored
//begin with this line
  ctx.JSON(......)

//error info

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xaca369]

goroutine 30 [running]:
testing.tRunner.func1(0xc0004c2700)
        D:/go1.12.5.windows-amd64/src/testing/testing.go:830 +0x399
panic(0xd83020, 0x17a0e60)
        D:/go1.12.5.windows-amd64/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/context.(*responseWriter).Header(0xc0002a3500, 0xec4336)
        <autogenerated>:1 +0x39
github.com/kataras/iris/context.(*context).ContentType(0xc000126510, 0xec4336, 0x10)
        D:/gopath/pkg/mod/github.com/kataras/iris@v11.1.1+incompatible/context/context.go:1695 +0xf7
github.com/kataras/iris/context.(*context).JSON(0xc000126510, 0xd706c0, 0xc0002bf840, 0x0, 0x0, 0x0, 0x1, 0x1, 0xc000458000)
        D:/gopath/pkg/mod/github.com/kataras/iris@v11.1.1+incompatible/context/context.go:2870 +0xc4
..........................

**Comment by dablyo** [comment]
//the Write method of interface iris.Context  must be implement
func (r *myResponseWriter) Write(in []byte)(int,error){
	return len(in),nil
}

//and order of statement must be fined
// url parameter and  business value in Values() *memstore.Store MUST be set after ctx.BeginRequest(resp,req)

**Comment by kataras** [comment]
@dablyo https://github.com/kataras/iris/issues/1357
