### ISSUE TITLE
install error (connected host has failed to respond)?

### ISSUE THREAD

**Issue by nsknsl** [kataras/iris#1372]
Go version 1.13
cmd has set GO111module=on
```
C:\Users\xxx\Desktop\XXXX\YYYYY>go get github.com/kataras/iris@master
go: finding github.com master
go: finding github.com/kataras master
go: finding github.com/kataras/iris master
go: downloading github.com/kataras/iris v0.0.0-20191005193354-55afd07befa8
verifying github.com/kataras/iris@v0.0.0-20191005193354-55afd07befa8: github.com/kataras/iris@v0.0.0-20191005193354-55afd07befa8: Get https://sum.golang.org/lookup/github.com/kataras/iris@v0.0.0-20191005193354-55afd07befa8: dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
I'm ok to visit google but can not install iris by go get. (Is this problem related to the network?)

**Comment by kataras** [comment]
@nsknsl you still have this issue? It is related to your or github's network.

**Comment by nsknsl** [comment]
After reading the [Are there "always on" module repositories and enterprise proxies?](https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies)
I set
`GOPROXY=https://goproxy.cn`
It's ok now.

**Comment by kataras** [comment]
OK thank you @nsknsl, this information added on the installation section as well.
