### ISSUE TITLE
how much is the test coverage of this project

### ISSUE THREAD

**Issue by sinkcup** [kataras/iris#1374]
There are some testing files in this repo, but no test coverage badge. 

it's very worrying for production. #1048

Name | Stars | Test coverage
-- | -- | --
gin | 32k | 98%
beego | 22k | 0
iris | 16k | 0?
echo | 15k | 84%
kit | 15k | 79%

![image](https://user-images.githubusercontent.com/4971414/66557751-f9c29480-eb84-11e9-96a9-e002c5d97c59.png)

**Comment by kataras** [comment]
Iris is tested through its examples for blackbox testing and its subpackages for internal impl. You wrote a table (0%?) which is falsy, yourself posted an mvc test. Reasons are obvsiously. Iris is fully tested and used in production for more than 3 years now, more than gin or other framework, just take a look of problems and bugs of other software of the same size.

**Comment by kataras** [comment]
Iris is tested through its examples for blackbox testing and its subpackages for internal impl. You wrote a table (0%?) which is falsy, yourself posted an mvc test. Reasons are obvsiously. Iris is fully tested and used in production for more than 3 years now, more than gin or other framework, just take a look of problems and bugs of other software of the same size.

However, you are free to push any test that you think is missing, we are always open to improvements in this project.

Please open issues per missing test(if any) so we can resolve them one by one. This one leads people to wrong direction.

**Comment by sinkcup** [comment]
Thanks, @kataras . I didn’t say it clearly.

I mean: this repo has many testing files, but don't calculate test coverage, so I use "0?" not "0".

I suggest adding the badge, like other frameworks.

![image](https://user-images.githubusercontent.com/4971414/66566026-80cc3880-eb96-11e9-9cd0-50c28106ffbf.png)

**Comment by kataras** [comment]
Test coverage does not mean that a software or library is working as expected, there is no need for such thing here, if you see the travis logs you can overview the test cov seperated by feature and example, it is usually useful for small projects like gin or microservices but thanks for the suggestion, if you see older versions when iris was just a tiny framework we had test cov because it was useful back then, right now its not.

**Comment by kataras** [comment]
General/global Test coverage does not mean that a software or library is working as expected, there is no need for such thing here, if you see the travis logs you can overview the test cov seperated by feature and example, it is usually useful for small projects like gin or microservices but thanks for the suggestion, if you see older versions when iris was just a tiny framework we had test cov because it had a meaning back then. I am not saying that test cov is not a good practise but as I said it means nothing for production. You may have 100% but a broken functionality.

**Comment by kataras** [comment]
I don't want to add more badges to README, you see it's simple as possible but if we wanna add, take a look below and share your opinion with us:

## Iris Web Framework

[![](https://sloc.xyz/github/kataras/iris?category=code)](https://sloc.xyz/github/kataras/iris?category=code) [![](https://sloc.xyz/github/kataras/iris?category=cocomo)](https://sloc.xyz/github/kataras/iris?category=cocomo)

# VS

## Gin Web Framework

[![](https://sloc.xyz/github/gin-gonic/gin?category=code)](https://sloc.xyz/github/gin-gonic/gin?category=code) [![](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)

**Comment by kataras** [comment]
I don't want to add more badges to README, you see it's simple as possible but if we wanna add, take a look below and share your opinion with us. 

## Iris Web Framework

[![](https://sloc.xyz/github/kataras/iris?category=code)](https://sloc.xyz/github/kataras/iris?category=code) [![](https://sloc.xyz/github/kataras/iris?category=cocomo)](https://sloc.xyz/github/kataras/iris?category=cocomo)

The below will confirm my point of the above post as well. Gin:

[![](https://sloc.xyz/github/gin-gonic/gin?category=code)](https://sloc.xyz/github/gin-gonic/gin?category=code) [![](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)

**Comment by kataras** [comment]
There is no need to add more badges to README, we try to keep it as simple as possible, but if we wanna add more, take a look below and share your opinion with us. 

## Iris Web Framework

[![](https://sloc.xyz/github/kataras/iris?category=code)](https://sloc.xyz/github/kataras/iris?category=code) [![](https://sloc.xyz/github/kataras/iris?category=cocomo)](https://sloc.xyz/github/kataras/iris?category=cocomo)

The below will confirm my point of the above post as well. Gin:

[![](https://sloc.xyz/github/gin-gonic/gin?category=code)](https://sloc.xyz/github/gin-gonic/gin?category=code) [![](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)](https://sloc.xyz/github/gin-gonic/gin?category=cocomo)

**Comment by sinkcup** [comment]
Wow! Iris has many more codes than Gin.

I am looking for a Heavyweight Go framework, just like Laravel framework of PHP. 

It seems that Iris just meets the needs, thanks @kataras

**Comment by kataras** [comment]
@sinkcup Yes, Iris is a complete web framework but it also gives you all the "low-level" tooling just like `net/http` std library. It is the "perfect balance". Read our [wikis](https://github.com/kataras/iris/wiki) and [examples](https://github.com/kataras/iris/tree/master/_examples), if you have any further question please don't hesitate to fill a github issue or [talk with us](https://chat.iris-go.com).

You are welcome to Iris Community!
