### ISSUE TITLE
remote ip limit !  tollbooth no support iris (new version),help me !!!

### ISSUE THREAD

**Issue by foxcorpady** [kataras/iris#1379]
didip/tollbooth

**Comment by kataras** [comment]
What do you mean, the middleware is working here, is there a new version breaks integration with Iris @didip?
@foxcorpady the maintainer is not active atm, er have 2 PRs that are not yet seen by @didip, but we have a middleware at iris-conttib/middleware that is working with the latest versions, see /_examples/experimental-handlers.

**Comment by foxcorpady** [comment]
thx, i see it
