### ISSUE TITLE
Url escape unescape mess Part 2

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#138]
This in in reference to #135 

The implementation is well and works, however, it breaks the following:
Suppose I have the same route as defined earlier in this issue and the following is the request url:
```
http://localhost:1234/details/Project%2FDelta?sort=name
```
I use the config:
```go
iris.Config().PathEscape = false
```
When I try to fetch c.Param("projectName") it gives me "Project%2FDelta?sort=name"
I know it is because the url is not escaped.

Another Example URL I need working is :
```
http://localhost:1234/details/Sakamoto+desu+ga%3F?highlight=text
```

So my question is, How can I make it possible for Path to be unescaped, and yet allow query and param separation without any complications?
---
**Here is my end-goal for easier understanding(sorry I didn't have breakfast my head is not working well as I write this):**
Request URL:
```
http://localhost:1234/details/Sakamoto+desu+ga%3F?highlight=text
```
Serverside:
```go
log.Println(url.QueryUnescape(c.Param("projectName"))) // will print "Sakamoto desu ga?"
log.Println(c.QueryArgs()) // will print "highlight=text"
```

Thanks, I know made a noodle here, very messy? Sorry :)

**Comment by kataras** [comment]
@kryptodev If unescaped is impossible from me to know what is url parameter and what is unescaped named parameter but I will give a shot( on 1hour+)

**Comment by kryptodev** [comment]
@kataras I know it's probably VERY difficult, but maybe there is some algorithm to do it efficiently.

**Comment by kataras** [comment]
I will try to fix it but I can't right now, please wait an hour or so we will find solution

**Comment by kryptodev** [comment]
Closing this because I manually fixed this inelegantly.

Changed that
```
http://localhost:1234/details/Sakamoto+desu+ga%3F?highlight=text
```
to 
```
http://localhost:1234/Sakamoto+desu+ga%3F/details?highlight=text
```

And then I manually checked for '?' proceeding region portion to ignore to my URLs resolve properly. Needed this for only one route so I guess in my case, it's not that bad.

**Comment by kataras** [comment]
@kryptodev I made a lot of tests, I was ready to commit a very bad code, but I don't. For these cases you can use url parameters only, no path parameters, path parameters are exists for other reasons, I'm sorr...
