### ISSUE TITLE
Reject iris session to schedule job func

### ISSUE THREAD

**Issue by schooltech** [kataras/iris#1382]
Hi，
I am going to use the schedule lib in my app, and the repository url is [https://github.com/bamzi/jobrunner](https://github.com/bamzi/jobrunner)，how to register iris session to the jobrunner func?
Thanks

**Comment by kataras** [comment]
@schooltech This is not an Iris question, please open an issue to the external repository. The jobrunner repository has examples, there is nothing that you have to change or care when migrating it with Iris, use it as you know.
