### ISSUE TITLE
[BUG]One request executed twice

### ISSUE THREAD

**Issue by hxfighting** [kataras/iris#1384]
**Describe the bug**
I am doing a QQ login function, but when QQ jumps to my interface, there is only one request, but it has been executed twice. How can I solve this bug, please help me.
**To Reproduce**
1. [...]

**Expected behavior**
expect executed once
**Screenshots**
![image](https://user-images.githubusercontent.com/26914712/67554236-8fdbea80-f741-11e9-8b64-8e6cca385f4a.png)
![image](https://user-images.githubusercontent.com/26914712/67553862-b3526580-f740-11e9-84ea-83956a4c2f85.png)
my route is
![image](https://user-images.githubusercontent.com/26914712/67553942-f01e5c80-f740-11e9-85c5-f53416057c28.png)
![image](https://user-images.githubusercontent.com/26914712/67553996-09270d80-f741-11e9-80c5-9d442cd98dc4.png)
**Desktop (please complete the following information):**
 - OS: [centos]

**Additional context**

**Comment by hxfighting** [comment]
here is my version 
![image](https://user-images.githubusercontent.com/26914712/67554476-1395d700-f742-11e9-844c-e8910f4d5f96.png)

**Comment by hxfighting** [comment]
sorry，its my fault，I have the wrong configuration

**Comment by kataras** [comment]
No problem @hxfighting, it was filled nicely with images and steps, good job. Don't hesitate to ask or fill any bug even if you are not sure!
