### ISSUE TITLE
[BUG]github.com/kataras/iris/v12/sessions.GetInt64Default when gives uint value 6 then got 0 return

### ISSUE THREAD

**Issue by lmq1117** [kataras/iris#1395]
**Describe the bug**
github.com/kataras/iris/v12/sessions.GetInt64Default gives uint value 6 and i got 0 return

**To Reproduce**
1. github.com/kataras/iris/v12/sessions.GetInt64Default call
github.com/kataras/iris/v12/sessions.GetInt64
when the v value is uint 6 t then the func GetInt64Default return the defaultValue

**Expected behavior**
1. github.com/kataras/iris/v12/sessions.GetInt64Default call
github.com/kataras/iris/v12/sessions.GetInt64
when the v value is uint 6 and the func GetInt64Default should return Int64 6 not the defaultValue given

**Desktop (please complete the following information):**
 - OS: [windows]

**Comment by kataras** [comment]
@lmq1117 this is not a bug, if you want to get an `uint X` value you should use `.GetUint64Default` instead of `GetInt64Default`.

**Comment by lmq1117** [comment]
Thanks Reply
sorry i didn't speak clearly what i mean

i mean that  when i set uint value to session,then i did have method to get the uint value from session
its the code 
```
package main
import (
	"fmt"
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/sessions"
)
func main() {
	sess := sessions.New(sessions.Config{
		Cookie: "sessioncookiename",
	})
	app := iris.New()
	app.Logger().SetLevel("debug")
	app.Get("/sess", func(ctx iris.Context) {
		session := sess.Start(ctx)
		var u uint
		u = 6
		session.Set("user_id", u)
		fmt.Println("================")
		fmt.Println(session.GetInt("user_id"))
		fmt.Println(session.GetIntDefault("user_id", 0))
		fmt.Println("================")
		fmt.Println(session.GetInt64("user_id"))
		fmt.Println(session.GetInt64Default("user_id", 0))
		//fmt.Println("================")
		//fmt.Println(session.GetUint("user_id"))
		//fmt.Println(session.GetUintDefault("user_id", 0))
	})
	app.Run(iris.Addr(":8080"))
}
```
when you run and visit http://localhost:8080/sess
the console will print
```
================
-1 not found: user_id as int
0
================
-1 not found: user_id as int64
0
```
how to get uint value from session?

**Comment by kataras** [comment]
You are welcome @lmq1117, yes I got it, by yesterday this [commit](https://github.com/kataras/iris/commit/f3d88b740e193f13f7d2fe48915c8e6b710731a6) fixes the above. It will be available for you to update and use at 23 Nov. as v12.0.2.
