### ISSUE TITLE
[BUG][HTTP Server] http: superfluous response.WriteHeader call from github.com/kataras/iris/v12/context.(*responseWriter).tryWriteHeader (response_writer.go:196)

### ISSUE THREAD

**Issue by ddesign84** [kataras/iris#1397]
Code:
```
package main

import (
	"github.com/kataras/iris/v12"
	"net/http/httputil"
	"net/url"
)

func main() {
	app := iris.New()
	app.Any("/{param:path}", func(ctx iris.Context) {
		hostUrl, _ := url.Parse("http://127.0.0.1:8081")
		proxy := httputil.NewSingleHostReverseProxy(hostUrl)
		proxy.ServeHTTP(ctx.ResponseWriter().Naive(), ctx.Request())
	})
	app.Run(iris.Addr(":8080"))
}
```

request: http://127.0.0.1:8080/proxy_url
control output:[HTTP Server] http: superfluous response.WriteHeader call from github.com/kataras/iris/v12/context.(*responseWriter).tryWriteHeader (response_writer.go:196)

golang version: go version go1.13.4 darwin/amd64
system: macOS

**Comment by kataras** [comment]
@ddesign84 This is wrong, you use the `Naive()` method, why? The iris Response Writer it's 100% compatible with `net/http.ResponseWriter` interface. `Naive()` should be used when you want to check the internal implementation i.e response recorder -> response writer -> http.ResponseWriter.

**The correct code**:

```go
package main

import (
	"net/http/httputil"
	"net/url"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()
	app.Any("/{param:path}", func(ctx iris.Context) {
		hostUrl, _ := url.Parse("http://127.0.0.1:8081")
		proxy := httputil.NewSingleHostReverseProxy(hostUrl)
		proxy.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
	})
	app.Run(iris.Addr(":8080"))
}


```

**Comment by kataras** [comment]
Also, check the [core/host/proxy.go](https://github.com/kataras/iris/blob/master/core/host/proxy.go) methods too, I think they meet your requirements.

**Comment by ddesign84** [comment]
thkThanks Reply

**Comment by ddesign84** [comment]
Thanks Reply
