### ISSUE TITLE
iris Compilation issues

### ISSUE THREAD

**Issue by junlorgithub** [kataras/iris#1398]
Hi :
I have a problem while debugging the project. I have the following log. Please help me. Thanks.

 go build
# go-iris/main/web/routes
web/routes/hub.go:31:6: cannot use cors.New(cors.Options literal) (type "github.com/kataras/iris/v12/context".Handler) as type "github.com/kataras/iris/context".Handler in assignment
web/routes/role_route.go:156:8: assignment mismatch: 1 variable but e.GetUsersForRole returns 2 values

**Comment by kataras** [comment]
@junlorgithub you have to update iris middlewares that they are using the new import path, execute  `$ go get -u github.com/iris-contrib/middleware/cors` inside your project's `go.mod`.

**Comment by junlorgithub** [comment]
@kataras Thanks so much for answering the question! I will test immediately
