### ISSUE TITLE
[BUG]Can't set file server in subdomain with request path is "/"

### ISSUE THREAD

**Issue by minhvh93** [kataras/iris#1399]
**Describe the bug**
Can't set file server in subdomain with request path is "/". 
There is error at /iris/v12@v12.0.1/core/router/path.go:240  with message is "panic: runtime error: slice bounds out of range "

**To Reproduce**
setting subdomain with file server have request path is "/" as bellow:
```
	staticDomain := app.Party("static.")
	{
		staticDomain.HandleDir("/", "public/dist/admin", iris.DirOptions{
			IndexName: "/index.html",
			Gzip: true,
			ShowList: true,
		})
	}
```

**Expected behavior**
 Be able to set file server in subdomain with request path is "/"

**Desktop (please complete the following information):**
 - OS: [windows]

**Additional context**
My resolution:
At /iris/v12@v12.0.1/core/router/path.go:233 add more code
```
	subdomainSplit := strings.Split(s, ".")
	if len(subdomainSplit) == 2 && subdomainSplit[1] == "" {
		return subdomainSplit[0], "/"
	}

```

**Comment by kataras** [comment]
Hello @minhvh93, will check it soon. I am preparing a new release with (thes best) i18n builtin support, minor fixes like this you posted and a sitemaps helper.

**Comment by kataras** [comment]
Merged.
