### ISSUE TITLE
How to define multiple templates function?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#140]
In Iris version 2.x, `Render.Funcs` is `[]template.FuncMap` type, I can define multiple templates function, but in Iris 3.0 this method does not exist, and now I use `iris.Config().Render.Template .Amber.Funcs` to define a template function, but it is not `[]template.FuncMap` type, what should I do?

**Comment by dxvgef** [comment]
Sorry, the problem is solved, because I forgot template.FuncMap the map [string] interface {} type. :p

**Comment by kataras** [comment]
Ahah ok but note that if you replace the default funcs you will lose the `render,yield,partial, current' you have to make a copy of ` iris.Config().Render.Template.HTMLTemplate.FuncMap ` and after add your functions to this copy and pass it to the  `iris.Config().Render.Template.HTMLTemplate.FuncMap = mycopyfuncs`
