### ISSUE TITLE
OnErrorCode help

### ISSUE THREAD

**Issue by schooltech** [kataras/iris#1402]
Hi, 
I use permission management in middleware and set forbidden code as below:
`ctx.StatusCode(http.StatusForbidden) // Status Forbiden
				ctx.WriteString("抱歉，你无权进行此操作")
				ctx.StopExecution();`
and the code to handle error， but it does not work:
`
app.OnErrorCode(iris.StatusForbidden, func(ctx context.Context) {
		ctx.View("errors/403.html")
})`

**Comment by kataras** [comment]
Hello @schooltech, it works like a charm. Could you please provide us with more information? Look below.

```go
// main.go

package main

import "github.com/kataras/iris"

func main() {
	app := iris.New()
	app.RegisterView(iris.HTML("./views", ".html"))

	app.OnErrorCode(iris.StatusForbidden, func(ctx iris.Context) {
		// ctx.Writef("on custom status forbidden handler")
		ctx.View("errors/403.html")
	})

	app.Get("/", func(ctx iris.Context) {
		ctx.StatusCode(iris.StatusForbidden)
		ctx.StopExecution() // You don't need that.
	})

	app.Run(iris.Addr(":8080"))
}
```

```html
<!-- ./views/errors/403.html -->

<h1>Custom 403</h1>
```

![1402](https://user-images.githubusercontent.com/22900943/70331979-42c35c00-1849-11ea-8337-7213aee75daf.png)

**Comment by schooltech** [comment]
hi @kataras , thank you for your reply.
I found the reason. After setting the `ctx.StatusCode(http.StatusForbidden)`, I set the `ctx.WriteString("xxx")` response message. After removing this, it can run normally, thanks

**Comment by kataras** [comment]
Yes @schooltech, in order to handle the status code automatically we expect no body written already, this prevents the server to send invalid responses to the clients. This is the  way-to-go.

https://github.com/kataras/iris/blob/3a02e5b48b52147f2714fe4ebbf58b4a3b9b7c59/context/context.go#L1133

You are welcome and don't hesitate to ask again!
