### ISSUE TITLE
Pion/webrtc integration request

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1403]
Is it ok to request for integration for one of the awesome webrtc package - https://github.com/pion/webrtc

It's quite an interesting package and is one of the awesome alternatives for pure WebSocket thing,

**Comment by kataras** [comment]
Hello @rebootcode,

WebRTC uses RTP and RTCP protocol for voice and video communication. HTTTP is another thing.
What do you mean by "integration" of WebRTC with a http/2 web framework?  You can already serve webrtc(peer) and Iris (server) depending on your application needs.

**Comment by rebootcode** [comment]
I mean webrtc package just like "websocket iris" or "tollbooth" or cache-bin" packages of iris.

**Comment by kataras** [comment]
websocket is an http single "upgraded" connection, webrtc is a different thing but maybe I missed something, could you please post me an example so I can see the usecase with Iris?

Thanks!

**Comment by rebootcode** [comment]
there is gorilla and gobwas package for WebSocket, but IRIS has cool middleware or packages to use.

same way "middleware" or package for pion webrtc for easy integration to use "webrtc technology" in iris package.
