### ISSUE TITLE
Tollbooth is bad to use

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1404]
i read this url https://www.studyiris.com/example/exper/limitHandler.html
but i find no matter what I do, it's only limited to one second.
what should i do?

**Comment by kataras** [comment]
Hello,

The studyiris.com is a Chinese community-based (refer to https://github.com/kataras/iris/issues/1093) documentation based on docs.iris-go.com but it's not up-to-date, please follow the [wiki](https://github.com/kataras/iris/wiki) and [examples](https://github.com/kataras/iris/tree/master/_examples). The source code of that example remains the same. The import paths are wrong, they are still using the Iris v11 there.

**Just follow this example**: https://github.com/iris-contrib/middleware/tree/master/tollboothic (see import path of github.com/kataras/iris/v12 and `go.mod`).

About the `only limited to one second`, The middleware passes the limit handler from the `didip/tollbooth`, it does not touch the arguments. So it has nothing to do with your issue, however, if you update the tollbooth package and read their docs you will find a lot of useful features.
