### ISSUE TITLE
[BUG] Broken AutoTLS ?

### ISSUE THREAD

**Issue by stefanwuthrich** [kataras/iris#1406]
**Describe the bug**
When I try to use AutoTLS I get:

`[HTTP Server] http: TLS handshake error from 127.0.0.1:35816: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
`

**To Reproduce**
`app.Run(iris.AutoTLS(":443", "example.com", "mail@example.com"))`

**Comment by kataras** [comment]
Hello @stefanwuthrich, will take look at this later on. In the meantime, as you probably already know , you can use [caddy](https://github.com/kataras/iris/tree/master/_examples/tutorial/caddy) in front of Iris which gives you more control on production usage with multiple Iris web applications and endpoints.

Thanks for the bug report, if you can find the origin of the issue it would be very helpful for me as I am preparing for the v12.1.0 release.

**Comment by kataras** [comment]
OK @stefanwuthrich the issue is fixed when you update the `golang.org/x/crypto`, which implementsthe RFC 8555 by-default. The iris `v12.1.0` will contain an updated `go.mod` file which will include this package latest version too.

**Comment by stefanwuthrich** [comment]
tks @kataras

**Comment by kataras** [comment]
Version 12.1.0 released (which contains the updated crypto pkg version), read more at: <https://github.com/kataras/iris/blob/master/HISTORY.md#fr-13-december-2019--v1210>. Happy weekend!
