### ISSUE TITLE
[BUG] view.HTMLEngine.Layout method doesn't work

### ISSUE THREAD

**Issue by bastengao** [kataras/iris#1408]
**Describe the bug**
`view.HTMLEngine.Layout` method doesn't work.

**To Reproduce**
```go
tmpl := iris.HTML("./templates", ".html").Layout("layouts/default.html")
app.RegisterView(tmpl)

// this only render index.html without layout.
ctx.View("index.html")
```

**Expected behavior**
Render view with default layout.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [mac]

**Additional context**
`Layout()` works on v12.0.1, not works on v12.1.0 and v12.1.1

**Comment by kataras** [comment]
Hello @bastengao, are you sure? It's working fine, run the [example](https://github.com/kataras/iris/blob/master/_examples/view/template_html_1/main.go#L15), I've tried it with `layouts/layout.html` as your code snippet and it still works as expected. Please provide a valid code snippet so we can reproducible the issue you are referring to.

Thanks,
Gerasimos Maropoulos
