### ISSUE TITLE
StaticWeb don't render index.html

### ISSUE THREAD

**Issue by xuehuizhang** [kataras/iris#1409]
i set b.StaticWeb("./public/","/public")

but http://localhost:8080/public

![image](https://user-images.githubusercontent.com/18264098/71396008-682ad500-2653-11ea-91d4-59b8e710b5ad.png)

![image](https://user-images.githubusercontent.com/18264098/71396045-809aef80-2653-11ea-8cb1-097bf30fb43f.png)

**Comment by kataras** [comment]
@xuehuizhang there is no `StaticWeb`. The last releases has the `HandleDir` instead which contains various fixes and improvements. Please upgrade your Iris, you are using old version.

Follow the documentation at: https://github.com/kataras/iris/wiki/Installation

**Comment by xuehuizhang** [comment]
Thank you

**Comment by kataras** [comment]
You are very welcomed, don't hesitate to ask if you need further assistance!
