### ISSUE TITLE
Favicon served from subdirectory

### ISSUE THREAD

**Issue by qskousen** [kataras/iris#141]
When a web page is loaded you can specify in your HTML where the favicon is, so you can load it from a static file directory, for instance: 
```
iris.Static("/favicons", "./static/favicons", 1)
```
would serve the file `/static/favicons/favicon.ico` from the request `/favicons/favicon.ico`, which is good. 

However, if a user requests a file by itself and not a web page, there is no way to tell the browser where the `favicon.ico` file is located, so it will try to load it from the root: `/favicon.ico`
This can be handled by using a special route like this:
```
iris.Static("/favicon.ico", "./static/favicons/",0)
```
However, since this is a thing that is common to all websites, it might be nice to do an automatic way of handling this route.

**Comment by kataras** [comment]
@qskousen  Done, example [here](https://github.com/iris-contrib/examples/blob/master/favicon)

```go
package main

import "github.com/kataras/iris"

func main() {
	err := iris.Favicon("./static/favicons/iris_favicon_32_32.ico")
	// This will serve the ./static/favicons/iris_favicon_32_32.ico to: localhost:8080/favicon.ico

	// err := iris.Favicon("./static/favicons/iris_favicon_32_32.ico", "/favicon_32_32.ico")
	// This will serve the ./static/favicons/iris_favicon_32_32.ico to: localhost:8080/favicon_32_32.ico

	if err != nil {
		iris.Logger().Panicf("Error when trying to set static favicon %s", err.Error())
	}

	iris.Get("/", func(ctx *iris.Context) {
		ctx.WriteHTML(iris.StatusOK, "You should see the favicon now at the side of your browser, if not please refresh or clear the browser's cache.")
	})

	println("Server is running at: 8080")
	iris.Listen(":8080")
}


```

Thanks for your contribution!
