### ISSUE TITLE
[BUG] function "substr" not defined

### ISSUE THREAD

**Issue by leluo** [kataras/iris#1410]
**Describe the bug**
template func not fount 
**To Reproduce**

tmpl.AddFunc("substr", func(s string, start, length int) string {
		bt := []rune(s)
		if start < 0 {
			start = 0
		}
		if start > len(bt) {
			start = start % len(bt)
		}
		var end int
		if (start + length) > (len(bt) - 1) {
			end = len(bt)
		} else {
			end = start + length
		}
		return string(bt[start:end])
	})

**Comment by kataras** [comment]
Hello @leluo, it's working fine. Take a look below:

```go
// file: main.go
package main

import "github.com/kataras/iris"

func main() {
	app := iris.New()

	tmpl := iris.HTML("./views", ".html")
	tmpl.AddFunc("substr", func(s string, start, length int) string {
		bt := []rune(s)
		if start < 0 {
			start = 0
		}
		if start > len(bt) {
			start = start % len(bt)
		}
		var end int
		if (start + length) > (len(bt) - 1) {
			end = len(bt)
		} else {
			end = start + length
		}
		return string(bt[start:end])
	})
	app.RegisterView(tmpl)

	app.Get("/", func(ctx iris.Context) {
		ctx.View("index.html")
	})

	app.Run(iris.Addr(":8080"))
}
```

```html
<!-- file: ./views/index.html -->
<h1>Home Page</h1>

Output: {{ substr "hello" 0 3}} (must print "hel")
```

Screenshot:

![image](https://user-images.githubusercontent.com/22900943/71411112-bab6c200-2650-11ea-84c8-085c6cb8cc2d.png)

-------

Please open a new issue, as this one is not valid, and post a reproducible code snippet.


Sincerely,
Gerasimos Maropoulos

**Comment by leluo** [comment]
when i use "github.com/kataras/iris/v12"  Report errors

**Comment by kataras** [comment]
@leluo Yes, the comment contains the old path (above comment is fixed now) but it works with the new one as well:

![image](https://user-images.githubusercontent.com/22900943/71439985-72f17280-2704-11ea-8bd1-142173ffd768.png)

I am 100% that you are doing something else, please post the full code snippet of your code so I can help you more.

**Comment by leluo** [comment]
First of all, thank you for your prompt reply
package routers

import (
	"blog/bridge"
	"blog/handlers/admin"
	"blog/handlers/home"
	"html/template"
	"time"

	"github.com/kataras/iris/v12"
)

// NewApp 生成application
func NewApp() *iris.Application {
	app := iris.Default()
	tmpl := iris.HTML("./templates", ".html")
	//tmpl.Reload(true)
	tmpl.AddFunc("index", func(data map[string]string, k string) string {
		if v, ok := data[k]; ok {
			return v
		}
		return ""
	})

	tmpl.AddFunc("timeformat", func(t time.Time, layout string) string {
		return t.Format(layout)
	})
	tmpl.AddFunc("find", func(data []admin.Option, k string) string {
		for _, v := range data {
			if v.Key == k {
				return v.Name
			}
		}
		return ""
	})
	tmpl.AddFunc("str2html", func(s string) template.HTML {
		return template.HTML(s)
	})

	tmpl.AddFunc("substr", func(s string, start, length int) string {
		bt := []rune(s)
		if start < 0 {
			start = 0
		}
		if start > len(bt) {
			start = start % len(bt)
		}
		var end int
		if (start + length) > (len(bt) - 1) {
			end = len(bt)
		} else {
			end = start + length
		}
		return string(bt[start:end])
	})
	tmpl.Reload(true)
	app.RegisterView(tmpl)
	//app.RegisterView(iris.HTML("./templates", ".html").Reload(true))
	//app.StaticWeb("/static", "./static")
	app.HandleDir("/static","./static")
	app.Favicon("./favicon.ico")

**Comment by kataras** [comment]
Hello @leluo, as I suspected, the issue is on `iris.Default() -> Views.Register(engine)` which registers view engine on `./views` or `./templates` directory (if exists) so the new one is appended instead of replace as it should do when file extension and directory is registered twice. Will push a fix now.

**Comment by leluo** [comment]
thank you very much   It's my version. My version is wrong @kataras
