### ISSUE TITLE
[FEATURE REQUEST] Translate README to Russian language

### ISSUE THREAD

**Issue by koddr** [kataras/iris#1411]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

No problem, just translated Iris README to Russian for Go community 👍 

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Want to merge PR about it to master.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

No.

**Additional context**
> Add any other context or screenshots about the feature request here.

![Screenshot 2019-12-26 at 10 45 29](https://user-images.githubusercontent.com/11155743/71465168-e3fc5d00-27cc-11ea-935c-b04c742fe49e.png)

I am & Russia ❤️ Iris web framework.

**Comment by kataras** [comment]
Thanks @koddr we :heart: Russia too! Cheers!
