### ISSUE TITLE
Simple question. Can I use in my own software BSD-2-Clause license?

### ISSUE THREAD

**Issue by asyslinux** [kataras/iris#1414]
Dear developers. I write my custom specific web server for work with specific archive files, compression, encryption, etc. And i want to publish my web server under BSD-2-Clause license.

In my project i use Iris and Iris logger as basement.
I'm not going to use the name of your project to promote my project.

Can I publish my project under the BSD-2-Clause license?

Thanks.

**Comment by kataras** [comment]
@asyslinux Yes, you are granted of course, thanks for using Iris on your project. **Optional**: if you publish your project on github/gitlab you can add a simple link that points to our github repository here if and only if you want it, that will be great!

Happy holidays! If I can help you in that project please let me know, my e-mail is public.

**Comment by asyslinux** [comment]
Thank you very much. Happy new year.

**Comment by asyslinux** [comment]
Hello, i release [wZD Project](https://github.com/eltaline/wzd), and add a link to Iris at end of readme. For first time I use BSD-3 same your project.

**Comment by kataras** [comment]
Hello, good job @asyslinux especially with the architecture and performance you've got my star!

**Comment by asyslinux** [comment]
Oo, thanks :). I my cleanup code already :) not in one file now :)

--
Best Regards, Andrew Mind

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
понедельник, 20 января 2020 г., 19:17, Gerasimos (Makis) Maropoulos <notifications@github.com> написано:

**Comment by AlbinoGeek** [comment]
I think this issue may be "solved" :)

**Comment by kataras** [comment]
You think it's time to close that one?

**Comment by asyslinux** [comment]
Yes, thanks :)

--
Best Regards, Andrew Mind

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
пятница, 11 сентября 2020 г., 12:18, Gerasimos (Makis) Maropoulos <notifications@github.com> написано:
