### ISSUE TITLE
Iris serer disabled by self check

### ISSUE THREAD

**Issue by hdi200** [kataras/iris#1415]
Hello, when I run  sudo mopidyctl config it returns
[iris]
enabled = false  ; Extension disabled by self check.
Any idea what could be causing this?
Here is a paste bin link with the full mopidyctl info
https://pastebin.com/zzqqbHJ0

Thanks in advance!

**Comment by kataras** [comment]
Hello @hdi200 can you explain me what's this? Iris is a web framework written in Go, are you sure you posted your question in the correct repository?

Thanks!
