### ISSUE TITLE
[BUG] context.GetLocale raises a panic due to nil reference

### ISSUE THREAD

**Issue by tuxaanand** [kataras/iris#1416]
**Describe the bug**
I tried the latest version of iris 12.1.4 with the quick start code and modified it to get the Locale from the browser

**To Reproduce**
1. The code used - 

```go
        app := iris.Default()
	app.Get("/ping", func(ctx iris.Context) {
		ctx.JSON(map[string]interface{}{
			"message": "pong",
		})
		log.Println("Locale - %s", ctx.GetLocale())
	})

	app.Run(iris.Addr(":8080"))
```

2. Log excerpt - 

```
Trace: runtime error: invalid memory address or nil pointer dereference

/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:199
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/signal_unix.go:394
/Users/aanandn/go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/i18n/i18n.go:354
/Users/aanandn/go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/i18n/i18n.go:354
/Users/aanandn/go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1795
```

**Expected behavior**
The default locale should be returned.

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by kataras** [comment]
You are using GetLocale without load any locales: 'app.I18n.Load("./locales", "en-US*,...)'. If you do 'ctx.Tr' it will give you just the Sprintf result if no locales loaded but you try to get the locale itself thats why you hit an expected nil reference. See the _examples/i18n.

**Comment by tuxaanand** [comment]
Hi Kataras,

Thanks a lot for the explanation. I thought the GetLocale method will
provide the info from the HTTP request. I misunderstood..

And suppose if the app receives a request from a browser which has a
different locale set other than what is configured, will it return nil?

I'll give it a try today evening....

Thanks
Aanand

**Comment by kataras** [comment]
@tuxaanand It will provide the info from the HTTP request but it doesn't know where to search for the translations if are not loaded.

You are welcome, you can check the i18n source code, it's very simple, at: https://github.com/kataras/iris/tree/master/i18n
