### ISSUE TITLE
Multi server ports

### ISSUE THREAD

**Issue by rubinus** [kataras/iris#1417]
use the iris web app server
how can i use the go tool trace

**Comment by kataras** [comment]
Hello, this is a question. You can use it as you do on net/http. Whats the issue with it?

**Comment by rubinus** [comment]
start other port ? for example 
go func() {
		http.ListenAndServe("0.0.0.0:8181", nil)
	}()

**Comment by kataras** [comment]
You mean multi ports on the same Iris instance? We have an example for this, take a look at: https://github.com/kataras/iris/blob/master/_examples/http-listening/custom-httpserver/multi/main.go

```go
app := iris.New()
// [...]


// Build the app first so it will be ready to
// be passed as Handler in the custom http.Server instance.
app.Build() 

// start a server on its own go routine.
srv1 := &http.Server{Addr: ":8181", Handler: app}
go srv1.ListenAndServe()

// app.Run waits and serves.
app.Run(iris.Addr(":8080"))
```
