### ISSUE TITLE
Nested layouts

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#142]
Is there a way to have nested layouts?
I'd like to have a base layout, and under it some other layouts to use in different pages of my website.
The Render method takes multiple layouts values as argument, but it renders only the first one.
If this is already implemented and I'm doing something wrong please correct me.

**Comment by kataras** [comment]
@es-lab  

> The Render method takes multiple layouts

It just takes an **optional** layout, if you set this parameter, the `iris.Config().Render.Template.Layout` is overriden.

Html `{{ yield }}` used to render  a page but if you need to include more than one partial page, you can use the ` {{ render "./partials/page.html" }} ` anywhere you want.

**Comment by kataras** [comment]
@es-lab  

> The Render method takes multiple layouts

It just takes an **optional** layout, if you set this parameter, the `iris.Config().Render.Template.Layout` is overriden.

For example 'layout.html' will need the `{{ yield }}` to render  the page ( the first parameter on `ctx.Render` ), but if you need to include more than one partial page, you can use the ` {{ render "./partials/page.html" }} ` anywhere you want.

[Click here](https://github.com/iris-contrib/examples) to view templates examples

> Please close the issue if your question is answered, thanks for your comment
