### ISSUE TITLE
Could not install iris.

### ISSUE THREAD

**Issue by umairalii** [kataras/iris#1420]

**Comment by umairalii** [comment]
getting the error message: 
![image](https://user-images.githubusercontent.com/41395451/71772663-873d3700-2f70-11ea-807f-3f855c249035.png)

**Comment by kataras** [comment]
@umairalii Installation works, please follow the [installation](https://github.com/kataras/iris/wiki/Installation#install) section.

> `go get github.com/kataras/iris/v12@latest`
