### ISSUE TITLE
[BUG] error with iris/view/jet.go after update iris

### ISSUE THREAD

**Issue by bouroo** [kataras/iris#1422]
After I run `go get -u -v github.com/kataras/iris` result error message

> /home/user/go/src/github.com/kataras/iris/view/jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion

**Comment by kataras** [comment]
Hello @bouroo, why suddenly you use `go get -u github.com/kataras/iris` instead of **`go get github.com/kataras/iris/v12@latest`** ? Please read the [installation section](https://github.com/kataras/iris/wiki/Installation) and don't hesitate to ask again. **Happy new year**!

> Relative to: https://github.com/kataras/iris/issues/1420
