### ISSUE TITLE
ctx.ReadForm error

### ISSUE THREAD

**Issue by leluo** [kataras/iris#1424]
When I parse the data submitted by the form through readform

, error reporting schema: Invalid path "upload file", but I do not have this upload file field in struct

lesson := new(models.Lesson)
	if err := c.ReadForm(lesson); err != nil {
		if strings.Contains(err.Error(), "upload_file") == false {
			Fail(c, http.StatusCreated, err.Error())
			return
		}
	}

my struct:
type Lesson struct {
	ID           int       `xorm:"pk autoincr"`
	CategoryID   int       `xorm:"not null index" form:"category_id" validate:"required" message:"栏目不能为空"`
	Title        string    `xorm:"varchar(120) not null" form:"title" validate:"required" message:"标题不能为空"`
	Key          string    `xorm:"varchar(120) not null" form:"key" validate:"required" message:"关键词不能为空"`
	Description  string    `xorm:"varchar(255) not null" form:"description" validate:"required" message:"描述不能为空"`
	LessonFileID int       `xorm:"not null" form:"lesson_file_id"`
	Content      string    `xorm:"text not null" form:"content" validate:"required" message:"介绍不能为空"`
	DownLoadURL  string    `xorm:"varchar(255) not null" validate:"url" form:"down_load_url" message:"下载地址不是有效的url"`
	Secret       string    `xorm:"varchar(60) not null" validate:"required" form:"secret" message:"秘钥不能为空"`
	Price        float64   `xorm:"not null default(5.80)" form:"Price"`
	Hit          int       `xorm:"not null default(1)"`
	AddTime      time.Time `xorm:"datetime created not null"`
	UpdateTime   time.Time `xorm:"datetime updated not null"`
}

**Comment by kataras** [comment]
You opened the same yesterday saying that it was invalid issue because you did aomething wrong, why re-post it? Also, it is not a bug, read the examples...the ErrInvalidPath can be ignored.

**Comment by leluo** [comment]
After I remove the fields from the database, I can't read the data of the form in the same way

**Comment by leluo** [comment]
Sorry, I just saw the example. I know how to solve it. Thank you very much

**Comment by leluo** [comment]
Iris is very powerful and has been using this framework. Thank you very much!

**Comment by kataras** [comment]
Thanks @leluo, in short the error was coming because the user sends a field which is not known to your struct, you can skip this error if you want through [iris.IsErrPath](https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go#L30). 

Happy to help you and don't hesitate to ask anything, you can contribute by testing our new work-in-progress [iris command line interface](https://github.com/kataras/iris-cli) too!
