### ISSUE TITLE
jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion

### ISSUE THREAD

**Issue by relunctance** [kataras/iris#1425]
**Describe the bug**

github.com/kataras/iris/view/jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion

**To Reproduce**
1.  go get -u -v github.com/kataras/iris
2. QuickStart
```go
package main

import "github.com/kataras/iris"

func main() {
        app := iris.Default()
        app.Get("/ping", func(ctx iris.Context) {
                ctx.JSON(iris.Map{
                        "message": "pong",
                })

        })
        app.Run(iris.Addr(":7501"))
}
```
3. `go run main.go`

**Expected behavior**

**Screenshots**
```
# github.com/kataras/iris/view
../github.com/kataras/iris/view/jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion
```

**Desktop (please complete the following information):**
 - OS:  Linux  3.10.0-327.28.3.el7.x86_64   
 - go version : go version go1.13.5 linux/amd64

**Additional context**

**Comment by kataras** [comment]
@relunctance  this happens because you are using `github.com/kataras/iris` instead of `github.com/kataras/iris/v12`. Please read our [Installation section](https://github.com/kataras/iris/wiki/Installation), it's not a bug...
