### ISSUE TITLE
How to set a custom context in MVC?

### ISSUE THREAD

**Issue by bigBron** [kataras/iris#1430]
I didn't see the related introduction in the document, only found this part of examples: https://github.com/kataras/iris/blob/master/_examples/routing/custom-context , but it's not what I want, so how to set a custom context in MVC?

**Comment by kataras** [comment]
Hello @bigBron  the same Context is used on `MVC` controllers too, so if you follow the above tutorial you will be able to use that in your controllers too. If I don't correctly please provide an example of usage of your idea.

**Comment by bigBron** [comment]
Can I use dependency injection to customize context, like this :
```golang
import (
	"fmt"
	"github.com/kataras/iris/v12/context"
	"github.com/kataras/iris/v12/sessions"
)

type MyContext struct {
	context.Context
	// code
}

type UsersController struct {
	Session   *sessions.Session
	MyContext *MyContext
}

func (u *UsersController) Get() {
	fmt.Printf("MyContext: %+v \n", u.MyContext)
}

```

**Comment by kataras** [comment]
@bigBron the problem here is that you have `context.Context` as an embedded type, try this one:

```go
type MyContext struct {
	Context iris.Context // you do NOT need to import kataras/iris/v12/context.
	// code
}
```
