### ISSUE TITLE
[FEATURE REQUEST] Raw html output on Pug template

### ISSUE THREAD

**Issue by yansigit** [kataras/iris#1436]
**Is your feature request related to a problem? Please describe.**
I want to out html tags as a raw data to view

**Describe the solution you'd like**
```go
// main.go
func index(ctx iris.Context) {
	var buf bytes.Buffer
	source, _ := ioutil.ReadFile("test.md")
	if err := goldmark.Convert(source, &buf); err != nil {
		panic(err)
	}

	doc := Doc{
		Author: "Nada",
		Title: "Sub",
		// Body: buf.String(),
		Body: "<h1>html tag</h1>"
	}

	ctx.View("index.pug", doc)
}
```

```pug
// index.pug
h1 {{.Title}}
p {{.Author}}
| <h1>TEST</h1>
| {{.Body}}
```

```html
<!-- html currently rendered -->
<h1>Sub</h1>
<p>Nada</p>
<h1>TEST</h1>
(some hard-escaped html tag just as text)
```

```html
<!-- html rendered as i expected  -->
<h1>Sub</h1>
<p>Nada</p>
<h1>TEST</h1>
<h1>html tag</h1>
```

**Describe alternatives you've considered**
Maybe something like
```go
ctx.ViewWithRawData("index.pug", doc)
```

**Additional context**
I'm new on everything like on Go, Pug, Iris framework so I might just not have found proper solution 😅

**Comment by yansigit** [comment]
Found a solution, or work around at least.
You need to wrap string with `template.html()` to make it rendered as proper html tag.

**Comment by kataras** [comment]
Exactly @yansigit , as shown at https://github.com/kataras/iris/blob/040e453cdd0b16398a63f3b929066d206f217550/_examples/view/template_pug_2/main.go#L15 too.  Good job for finding it alone!
