### ISSUE TITLE
[question] how to create `json pretty` with iris?

### ISSUE THREAD

**Issue by ionutnechita** [kataras/iris#1437]
Hi Iris team,

I like this web framework and I have been working with these for 2 days.
But i would like to know how i can make json more visible.
I'm at the beginning and I would like some help.
By Godocs I did not understand very well how I could do this.

ctx.JSON(iris.Map{"message": "Hello Iris!"}, ???)
I would like to know what options can be put here?

I saw in another part a mod with enc.setIndent("", "    ")
can you give me an example with Iris?

thank you very much.

**Comment by kataras** [comment]
Hello @ionutnechita,

The `ctx.JSON` method's last variadic, optional argument accepts JSON options of `context.JSON`. See at: https://github.com/kataras/iris/blob/master/context/context.go#L3208. It contains a field named [Indent](https://github.com/kataras/iris/blob/master/context/context.go#L3123) (and more).

So you need to import the `/context` subpackage and use set `JSON.Indent` to  `true` and pass it. Example:

```go
import (
    "github.com/kataras/iris/v12"
    "github.com/kataras/iris/v12/context"
)

// [...code]

var jsonOptions = context.JSON {
    Indent: true,
}

func(ctx iris.Context) {
    var data = ...
    ctx.JSON(data, jsonOptions) 
}
```

**Comment by ionutnechita** [comment]
Hi @kataras, 

Thanks a lot for example.
It went very well, just with a simple change.

Indent: true => Indent: "    "

Everything now looks more beautiful.

Only as a suggestion, example above, can you put it in git - _examples?

Golang and Iris is beautiful.

**Comment by kataras** [comment]
Oh you are right, it's a string of chars for indentation! I will add the example later on as I am from mobile, out of my city & office until tomorrow. Again, welcome and give a star to the repository if you didn't already :)
