### ISSUE TITLE
group routers request?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [kataras/iris#144]
hi, is the any way to make group routers? i checked the wiki, and tried to code, but i could not found any way to make it.

**Comment by kataras** [comment]
@ziyouchutuwenwu Ofcourse there is a way for router groups and subdomains groups, it's a section on the e-book but propably you didn't read it, anyway [click here to read about group routes](https://kataras.gitbooks.io/iris/content/party.html).

**Comment by ziyouchutuwenwu** [comment]
yes, i found api Party, so i close it, thank you very much!
