### ISSUE TITLE
[BUG]Context.ServeFile send 'application/wasm' with a wrong extra field

### ISSUE THREAD

**Issue by rocket049** [kataras/iris#1440]
**Describe the bug**
Context.ServeFile send 'application/wasm' with a wrong extra field

**To Reproduce**
```
app.Get("/{key:path}", func(ctx iris.Context){
   ...  //get filename :  xx.wasm
    ctx.ServeFile(filename, ctx.ClientSupportsGzip())
})
```

**Expected behavior**

The content-type must be 'application/wasm'.

But it will be 'application/wasm; charset=UTF-8' now.

The problem is FireFox72 will report error 'unsupported mime type'.

Otherwise, chrome can work well.

**Comment by kataras** [comment]
@rocket049  thanks for the report! It's fixed now.
