### ISSUE TITLE
ReadJSON Ajax

### ISSUE THREAD

**Issue by colorworlds** [kataras/iris#1445]
**Describe the bug**
use `ctx.ReadJSON()` , I can't get the json that the browser post.
but use `json.Unmarshal()`, it works.

**browser post following json to server:**
{"email":"222@qq.com","password":"19"}
[screenshot](https://s2.ax1x.com/2020/02/09/1hQZKx.png)

It's my jquery code to post the json:
```
$.ajax({
	type : 'POST',
        url : '/register',
        data : JSON.stringify({
        'email' : $('#email').val(),
        'password' : $('#password').val(),
         }),
	dataType: "json",
	contentType: "application/json;charset=utf-8",
        success: function(data){
		console.log(data);
        }
})
```

**go struct of server side:**
```
type SubmitAccount struct {
	Email    string `json:"email" validate:"required,email" `
	Password string `json:"password" validate:"required"`
}
```

**post Handler v1:**
```
submitAccount2 := &SubmitAccount{}
body, err := ctx.GetBody()
json.Unmarshal(body, submitAccount2)
```
it works.
`ctx.GetBody() `can get the data,the `body` has data:
[screenshot](https://s2.ax1x.com/2020/02/09/1hlrkD.png)

**post Handler v2:**
```
submitAccount := &SubmitAccount{}
if err := ctx.ReadJSON(submitAccount); err != nil {
	ctx.StatusCode(iris.StatusOK)
	ctx.JSON(&Response{Status: false, Data: nil, Msg: "json解析错误：" + err.Error()})
	return
}
```
it doesn't work.
I find `ctx.GetBody()`can't get the data in `UnmarshalBody()` , the `rawData` doesn't has data:
[screenshot](https://s2.ax1x.com/2020/02/09/1h1ljI.png)
[screenshot](https://s2.ax1x.com/2020/02/09/1h1M3d.png)

**Desktop**
 - OS: [windows]

**Comment by kataras** [comment]
Hello @colorworlds,

There is no bug, it's working fine here. Take a look at the code and the **screenshots(postman and jquery ajax)** below.

```go
// main.go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")
	app.RegisterView(iris.HTML("./views", ".html"))

	app.Get("/", index)
	app.Post("/register", register)

	app.Run(iris.Addr(":8080"))
}

func index(ctx iris.Context) {
	ctx.View("index.html")
}

type SubmitAccount struct {
	Email    string `json:"email" validate:"required,email" `
	Password string `json:"password" validate:"required"`
}

func register(ctx iris.Context) {
	var acc SubmitAccount
	if err := ctx.ReadJSON(&acc); err != nil {
		ctx.StatusCode(iris.StatusBadRequest)
		ctx.JSON(iris.Map{"status": iris.StatusBadRequest, "message": err.Error()})
		return
	}

	ctx.Application().Logger().Debugf("Submited Account: %#+v\n", acc)
	ctx.JSON(iris.Map{"status": iris.StatusOK, "message": "OK"})
}
```

```html
<!-- ./views/index.html -->
<html>

<head>
    <title>Example 1445</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>

<body>
    <script type="text/javascript">
        $.ajax({
            type: 'POST',
            url: '/register',
            data: JSON.stringify({
                'email': "222@qq.com",
                'password': "my_password",
            }),
            dataType: "json",
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                console.log(data);
            }
        })
    </script>
</body>

</html>
```

### Postman
![1445_1](https://user-images.githubusercontent.com/22900943/74102529-dcaacc00-4b4c-11ea-8bec-2dc0f3739616.png)

### Ajax

![1445_2](https://user-images.githubusercontent.com/22900943/74102539-e3394380-4b4c-11ea-81ca-8923319787e9.png)

**Comment by kataras** [comment]
Hello @colorworlds,

There is no bug, it's working fine here. Take a look at the code and the **screenshots(postman and jquery ajax)** below.

```go
// main.go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")
	app.RegisterView(iris.HTML("./views", ".html"))

	app.Get("/", index)
	app.Post("/register", register)

	app.Run(iris.Addr(":8080"))
}

func index(ctx iris.Context) {
	ctx.View("index.html")
}

type SubmitAccount struct {
	Email    string `json:"email" validate:"required,email" `
	Password string `json:"password" validate:"required"`
}

func register(ctx iris.Context) {
	var acc SubmitAccount
	if err := ctx.ReadJSON(&acc); err != nil {
		ctx.StatusCode(iris.StatusBadRequest)
		ctx.JSON(iris.Map{"status": iris.StatusBadRequest, "message": err.Error()})
		return
	}

	ctx.Application().Logger().Debugf("Submited Account: %#+v\n", acc)
	ctx.JSON(iris.Map{"status": iris.StatusOK, "message": "OK"})
}
```

```html
<!-- ./views/index.html -->
<html>

<head>
    <title>Example 1445</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>

<body>
    <script type="text/javascript">
        $.ajax({
            type: 'POST',
            url: '/register',
            data: JSON.stringify({
                'email': "222@qq.com",
                'password': "my_password",
            }),
            dataType: "json",
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                console.log(data);
            }
        })
    </script>
</body>

</html>
```

### Postman
![1445_1](https://user-images.githubusercontent.com/22900943/74102529-dcaacc00-4b4c-11ea-8bec-2dc0f3739616.png)

### Ajax

![1445_2](https://user-images.githubusercontent.com/22900943/74102539-e3394380-4b4c-11ea-81ca-8923319787e9.png)

-----------

So, I assume that you are already **consume** body before `ctx.ReadJSON`. Go net/http does not allow to consume body more than once (because of ioutils.ReadAll).  To solve that with Iris you can pass the **iris.WithoutBodyConsumptionOnUnmarshal**. 

Example Code:

```go
app.Run(iris.Addr(":8080"), iris.WithoutBodyConsumptionOnUnmarshal)
```

This feature is documented at [_examples/http_request/read-many](https://github.com/kataras/iris/blob/master/_examples/http_request/read-many/main.go).


Please close this issue if it helped you solve it, or post below if you still having issues with this one.

Thanks,
Gerasimos Maropoulos

**Comment by colorworlds** [comment]
sorry @kataras   I didn't describe it clearly.
v1 and v2 in one handler,the whole code is like:
```
func register(ctx iris.Context) {
	submitAccount2 := &models.SubmitAccount{}
	body, err := ctx.GetBody()
	err = json.Unmarshal(body, submitAccount2)
	fmt.Printf("success：%s ", submitAccount2.Email)

	submitAccount := &models.SubmitAccount{}
	if err := ctx.ReadJSON(submitAccount); err != nil {
		ctx.StatusCode(iris.StatusOK)
		ctx.JSON(&Response{Status: false, Data: nil, Msg: "json解析错误：" + err.Error()})
		fmt.Printf("wrong：%s   %s", submitAccount.Email, submitAccount.Password)
		return
	}
}
```
it seems like a lock problem for ctx?

**Comment by kataras** [comment]
No worries @colorworlds.

Don't hesitate to ask in the future, even if you think it's easy, I am here to provide you my assistance at any circumstances. I thank you for using Iris, you will see how easy and performant is at the same time!
