### ISSUE TITLE
How to add a Globals of pongo2 template?

### ISSUE THREAD

**Issue by alanyang** [kataras/iris#145]
this is useful.

https://github.com/flosch/pongo2/issues/35

**Comment by kataras** [comment]
I could give access to Globals but you have to put them before iris.Listen, ok?

**Comment by kataras** [comment]
@alanyang  Done, if you want test it and tell me if really works, 

Thanks for your contribution!

**Comment by kataras** [comment]
@alanyang  Done, if you want test it and tell me if really works, 

Set globals **before** `iris.Listen` 

```go
myGlobals := make(map[string]interface{})
myGlobals["something"] = "anything"

iris.Config().Render.Template.Pongo.Globals = myGlobals


```

Thanks for your contribution!

**Comment by alanyang** [comment]
@kataras Great, this is work well.
