### ISSUE TITLE
I want to do log tracking

### ISSUE THREAD

**Issue by lhlyu** [kataras/iris#1452]
**Is your feature request related to a problem? Please describe.**
I need to keep track of all the relevant logs in one request.

**Describe the solution you'd like**
I need a unique ID of the request to track the log,Here's my implementation, but it's not simple enough.

```
// Add an traceId to the context
func WithLogger(ctx context.Context) context.Context {
	traceId := util.GetGID()
	entry := common.L
	if entry == nil {
		entry = logrus.NewEntry(logrus.StandardLogger())
	}
	return context.WithValue(ctx, loggerKey{}, entry.WithFields(logrus.Fields{
		"traceId": traceId,
	}))
}

func GetLogger(ctx context.Context) *logrus.Entry {
	entry := ctx.Value(loggerKey{})
	if entry == nil {
		return logrus.NewEntry(logrus.StandardLogger())
	}
	return entry.(*logrus.Entry)
}

// for iris context
func Log(ctx iris.Context) *logrus.Entry {
	funcName, _, line := util.CurrentInfo(2)
	entry := GetLogger(ctx.Request().Context())
	if common.Cfg.GetString("log.level") == "debug" {
		entry = entry.WithFields(logrus.Fields{
			"position": fmt.Sprintf("%s:%d", funcName, line),
		})
	}
	return entry
}
```

```
// log middleware
func Log() context.Handler {
	return func(ctx iris.Context) {
		context := logger.WithLogger(ctx.Request().Context())
		req := ctx.Request().WithContext(context)
		ctx.ResetRequest(req)
		ctx.Next()
	}
}
```

``` 
app.Get("/", func(ctx iris.Context) {
	name := ctx.URLParam("name")
	logger.Log(ctx).Infoln("hello", name)
	logger.Log(ctx).Infoln("hi", name)
	ctx.Text("hello %s", name)
})
```

**Describe alternatives you've considered**
I want the log to be integrated into the context,Use as follows：
```
ctx.Log("hello")
ctx.Info("hi")
ctx.GetLogger()
```

**Comment by kataras** [comment]
Hello @lhlyu, Iris' Context has a `ctx.Values().Set/Get` which will set and retrieve values per request lifecycle. No need to use the standard `context` package here, you can simplify all that to one function. Iris has also an `context.id` (unexported) field which is just an atomic-increment number per request. Use the google's UUID package to get unique IDs, simply set by `ctx.Values().Set("context_id", uuid)` and get it through `uuid := ctx.Values().GetString("context_id")` . You can do the same for the logrus instance (although you don't have to store it in the Context/request itself).

**Comment by lhlyu** [comment]
@kataras Thank you for your answer. I tried what you said, but I didn't think it was elegant enough

**Comment by kataras** [comment]
You are welcome @lhlyu, if you think that the solution is not elegant enough we can make it better if you give me an example of how you imagine the end-developer code to be like so I can implement it

**Comment by lhlyu** [comment]
@kataras ok,I need some time to think
