### ISSUE TITLE
How could "GetByWildard" be working?

### ISSUE THREAD

**Issue by PCanyi** [kataras/iris#1459]
Describe the issue you are facing or ask for help

For example, the "GetByWildard" I  only found just one line's description, no explains and no code examples.

So how could I make this function get working?  Is there anyone could help?

**Comment by kataras** [comment]
Hello @PCanyi, simply this: 

```go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()
	usersRouter := app.Party("/users")
	mvc.New(usersRouter).Handle(new(myController))
	app.Listen(":8080")
}

type response struct {
	Message string `json:"message"`
}

type myController struct{}

func (c *myController) GetByWildcard(wildcardPathParameter string) response {
	return response{
		Message: "The wildcard is: " + wildcardPathParameter,
	}
}
```
is the same as:

```go
usersRouter.Get("/{p:path}", func(ctx iris.Context) {
    wildcardPathParameter := ctx.Params().Get("p")
    ctx.JSON(response{
        Message: "The wildcard is: " + wildcardPathParameter,
    })
})
```

Example fire request:

```sh
curl --location --request GET 'http://localhost:8080/users/path_segment_1/path_segment_2'
```

**Output**

```json
{
  "message": "The wildcard is: path_segment_1/path_segment_2"
}
```

**Comment by PCanyi** [comment]
> Hello @PCanyi, simply this:
> 
> ```go
> package main
> 
> import (
> 	"github.com/kataras/iris/v12"
> 	"github.com/kataras/iris/v12/mvc"
> )
> 
> func main() {
> 	app := iris.New()
> 	usersRouter := app.Party("/users")
> 	mvc.New(usersRouter).Handle(new(myController))
> 	app.Listen(":8080")
> }
> 
> type response struct {
> 	Message string `json:"message"`
> }
> 
> type myController struct{}
> 
> func (c *myController) GetByWildcard(wildcardPathParameter string) response {
> 	return response{
> 		Message: "The wildcard is: " + wildcardPathParameter,
> 	}
> }
> ```
> 
> is the same as:
> 
> ```go
> usersRouter.Get("/{p:path}", func(ctx iris.Context) {
>     wildcardPathParameter := ctx.Params().Get("p")
>     ctx.JSON(response{
>         Message: "The wildcard is: " + wildcardPathParameter,
>     })
> })
> ```
> 
> Example fire request:
> 
> ```shell
> curl --location --request GET 'http://localhost:8080/users/path_segment_1/path_segment_2'
> ```
> 
> **Output**
> 
> ```json
> {
>   "message": "The wildcard is: path_segment_1/path_segment_2"
> }
> ```

I know what the problem is now. The "GetByWildard" in the doc is wrong. It should be GetByWildcard. 

Please modified it in the docs. 

Thank you for your example. It is very helpful and valuable.

**Comment by PCanyi** [comment]
https://github.com/kataras/iris/wiki/MVC

`If mvc.New(app.Party("/user")).Handle(new(user.Controller))

func(*Controller) Get() - GET:/user.
func(*Controller) Post() - POST:/user.
func(*Controller) GetLogin() - GET:/user/login
func(*Controller) PostLogin() - POST:/user/login
func(*Controller) GetProfileFollowers() - GET:/user/profile/followers
func(*Controller) PostProfileFollowers() - POST:/user/profile/followers
func(*Controller) GetBy(id int64) - GET:/user/{param:long}
func(*Controller) PostBy(id int64) - POST:/user/{param:long}
If mvc.New(app.Party("/profile")).Handle(new(profile.Controller))

func(*Controller) GetBy(username string) - GET:/profile/{param:string}
If mvc.New(app.Party("/assets")).Handle(new(file.Controller))

func(*Controller) GetByWildard(path string) - GET:/assets/{param:path}

Supported types for method functions receivers: int, int64, bool and string.

Optionally, response via output arguments, like we've shown at the Dependency Injection chapter. E.g.`

**Comment by kataras** [comment]
Ah so there is a typo in the docs, I see. I will fix it now. Thanks @PCanyi !

**Comment by kataras** [comment]
You are welcome @PCanyi!

Ah so there is a typo in the wikis, I see. I will fix it now. Thanks @PCanyi !
