### ISSUE TITLE
how to graceful restart iris? like nginx reload

### ISSUE THREAD

**Issue by godsoul** [kataras/iris#146]
Hi,I want kill -HUP iris pid,then reload iris service

**Comment by egorsmkv** [comment]
Supervisor?

**Comment by kataras** [comment]
@godsoul We have a graceful package and an [example here](https://github.com/iris-contrib/examples/tree/master/graceful). I t has not ability to 'restart' like nginx

**Comment by godsoul** [comment]
@kataras I see,I hope to achieve this function as soon as possible, like nginx reload command,thanks a lot
