### ISSUE TITLE
Need before/after middleware and timeout-control features

### ISSUE THREAD

**Issue by benjamin-yin001** [kataras/iris#1460]
Interesting , I found most micro web framework do not have before/after middleware support. A middleware can run before handler or after handler, not just before. It is very common in Java/.net frameworks.

And also, the time of processing a request should be controlled.  Time of uploading a big file and generating a html web page is very different. 

And the handler should also have before/after filters. Middleware is not a correct name, maybe filter/interception is more good.

Which one is the faster between iris and fasthttp based framework like atreugo, Fiber ?

**Comment by kataras** [comment]
@benjamin-yin001 I don't understand the question, we **have support for before/after middleware** and timeout-control with the Request's context.
