### ISSUE TITLE
How to create a empty iris.Context

### ISSUE THREAD

**Issue by lhlyu** [kataras/iris#1466]
like:
```
ctx := iris.Background() 
or
ctx := iris.TODO()
```

**Comment by lhlyu** [comment]
I have solved it.
```
ctx := context.NewContext(iris.Default())
```

**Comment by kataras** [comment]
It's better to create a new context through the context pool for better performance. Example Code:
https://github.com/kataras/iris/blob/a1e9813c610a61aba3e803a655cefc36c6efc3b2/_examples/routing/custom-wrapper/main.go#L43-L45
