### ISSUE TITLE
[BUG]Dependencies injection failed

### ISSUE THREAD

**Issue by rocinantex** [kataras/iris#1468]
**Dependencies injection failed**

**To Reproduce**
The following code will be reproduce  this bug
```go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
	"log"
)

type Service struct{}

func (s *Service) DoSomething(ctx iris.Context) {
	if _, err := ctx.WriteString("Foo bar"); err != nil {
		log.Println(err)
	}
}

type Controller struct {
	Ctx     iris.Context
	Service *Service
}

type FooController struct {
	Controller
}

type BarController struct {
	FooController
}

type FinalController struct {
	BarController
}

func (c *FinalController) Get() {
	// c.Ctx and c.Service are not injected
	// this action will trigger a panic
	c.Service.DoSomething(c.Ctx)
}

func main() {
	app := iris.New()
	m := mvc.New(app)
	m.Register(new(Service))
	m.Handle(new(FinalController))
	if err := app.Listen(":8080"); err != nil {
		log.Fatal(err)
	}
}
```

**Desktop:**
 - OS:  ubuntu 18.04

After debugging I found a possible cause of this bug
[struct.go](https://github.com/kataras/iris/blob/a1e9813c610a61aba3e803a655cefc36c6efc3b2/hero/di/struct.go#L229)
[reflect.go](https://github.com/kataras/iris/blob/a1e9813c610a61aba3e803a655cefc36c6efc3b2/hero/di/reflect.go#L229)
In my gist case, the `field.Index` of all fields returned by `LookupNonZeroFieldsValues` will be come the last `field.Index` value

Then I try to fix this bug, I added the following code in 
[reflect.go](https://github.com/kataras/iris/blob/a1e9813c610a61aba3e803a655cefc36c6efc3b2/hero/di/reflect.go#L232)
```go
tmp := make([]int, len(index))
copy(tmp, index)
field := field{
    Type:   f.Type,
    Name:   f.Name,
    Index:  tmp,
    CanSet: isExported,
}		
```
Then the bug disappeared, but I still don't know why.
Because `index` is a local variable, why does it cause all fields to be modified?

**Comment by kataras** [comment]
Hello @rocinantex, the dependency injection code is fully re-written in the upcoming version of Iris, see the [master branch](https://github.com/kataras/iris/tree/master). Try it, (see the new examples as well), and if your code still failing please post the code snippet in order to provide you more help, don't try to fix it alone, just share a re-producible code.

**Comment by rocinantex** [comment]
@kataras I just tried it with the same code in [master branch](https://github.com/kataras/iris/tree/master) and still injection failed.

**Comment by kataras** [comment]
Hello @rocinantex thanks for the example above.

I am tired at the moment but will check it later on, when I wake up. However,  I am 99% sure that the slice clone solution will fix the issue and not break anything. You can push a PR in the **master branch** and I will test it and merge it tomorrow.
