### ISSUE TITLE
not match route

### ISSUE THREAD

**Issue by sanqi** [kataras/iris#147]
Hi,I'm trying to customize the route directory ,But found not to run

it is okay
`iris.Get("/hello/:name", func(c *iris.Context) {
        name := c.Param("name")
        c.Write("Hello %s", name)
    })`

not work
`iris.Get("/:name", func(c *iris.Context) {
        name := c.Param("name")
        c.Write("Hello %s", name)
    })`

**Comment by kataras** [comment]
@sanqi  Please read the docs before posting any issue, if you want root ("/") to be anything use the ` *` 
```go
iris.Get("/*name", func(c *iris.Context) { name := c.Param("name") c.Write("Hello %s", name) })
```

**Comment by kataras** [comment]
@sanqi  Your example is working. If you .Get("/:name") you can't do that : .Get("/somethingelse)

```go

package main

import "github.com/kataras/iris"

func main() {

	iris.Get("/:name", func(ctx *iris.Context){
		ctx.Write("Hello %s" ,ctx.Param("name"))
	})

	iris.Listen(":8080")

}

```

**Comment by sanqi** [comment]
@kataras thank you,i try add some code ,would not work
```
package main

import "github.com/kataras/iris"

func main() {

    iris.Get("/admin", func(ctx *iris.Context){
        ctx.Write("admin")
    })

    iris.Get("/:name", func(ctx *iris.Context){
        ctx.Write("Hello %s" ,ctx.Param("name"))
    })

    iris.Listen(":8080")

}
```
