### ISSUE TITLE
[BUG] Session Redis is not establishing a connection

### ISSUE THREAD

**Issue by austin-barrington** [kataras/iris#1476]
**Describe the bug**
Redis connection for session management does not connect or error

**To Reproduce**
1. After following the example code you are not able to connect to a redis service for session management
2. No error is returned or raised in the session code

**Expected behavior**
Expected to have working redis connection

**Screenshots**
```
// Can't use shared libs here as it's bespoke to IRIS framework
	db := redis.New(redis.Config{
		Network:   "tcp",
		Addr:      "10.100.10.10:6379",
		Timeout:   time.Duration(30) * time.Second,
		MaxActive: 10,
		Password:  "",
		Database:  "",
		Prefix:    "",
		Delim:     "-",
		Driver:    redis.Redigo(), // redis.Radix() can be used instead.
	})

	// close connection when control+C/cmd+C
	iris.RegisterOnInterrupt(func() {
		db.Close()
	})

	defer db.Close() // close the database connection if application errored.

	sessionManager := sessions.New(sessions.Config{
		Cookie:       "PingSphereSessions",
		Expires:      0, // <=0 means unlimited life. Defaults to 0.
		AllowReclaim: true,
	})

	sessionManager.UseDatabase(db)
```

1) Application started, login requested redis state:
![Screenshot 2020-03-23 at 10 22 56](https://user-images.githubusercontent.com/31205926/77306955-53acb600-6cf0-11ea-8cdc-594e1899a2cc.png)

2) Connecting from external server via redis-cli
![Screenshot 2020-03-23 at 10 22 46](https://user-images.githubusercontent.com/31205926/77306981-5e674b00-6cf0-11ea-8534-05ed92af1135.png)

**Desktop (please complete the following information):**
 - Desktop OS: Mac OSX
 - Server Debian 9
 - Go version `go version go1.14 darwin/amd64`

**Additional context**

**Comment by Dexus** [comment]
It looks like it's no bug, for me it works.

did you tried to set `Database:  "1",` for the connection settings? Also try to log your network and look to the firewall settings if you allow to access it.

From my side I cant see any problems, have checked with multiple OS as "client" and "server". Only sometimes my Firewall blocks requests.

**Comment by austin-barrington** [comment]
Hey,

> did you tried to set Database: "1", 

I have only set it to 0 why would 1 make a difference in this case?

> Also try to log your network and look to the firewall settings if you allow to access it.

There are no firewalls in play here, iptables are disabled. I proved this in the original post with the redis cli client.

Yes this is working fine for me if I downgrade iris to version 11.1.1.

Extra info:
Redis version: Redis server v=5.0.8 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=b259580a79fcac48
OS: Debian 9 - Linux agent-core-1 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Comment by kataras** [comment]
Hello @austin-barrington, iris version 11.1.1 uses the same redis client which was `Redigo` and as I can see from your configuration you still use that client. I am not able to re-produce your issue on Mac OS but on Windows and Ubuntu it works fine, I've just re-ran it for any case. Please contact me at our [chat](https://gitter.im/iris_go/community) through private message so I can provide you personal assistance and if it's an Iris issue it will be fixed too.
