### ISSUE TITLE
Run websocket how to write response ? 

### ISSUE THREAD

**Issue by 23233** [kataras/iris#1477]
### Server is not warp irix context , server event like :
```
			"chat": func(c *websocket.NSConn, msg websocket.Message) error {
				if !c.Conn.IsClient() {
					// 客户端发送到服务器
					log.Printf("[%s]--client-side 发送消息  %s", c.Conn.ID(), msg.Body)
				return nil
			},
```
#### Maybe just don't know websocket libray principle , hope help ~ thanks!!!

**Comment by kataras** [comment]
Hello @23233, you have `iris.Context` access through `kataras/iris/v12/websocket.GetContext(websocketConnection)`. To wait for a response back  you have to use `nsConn.Ask(...)` method. Hope I answered your question

**Comment by 23233** [comment]
Yes just now run star ! thanks ~
