### ISSUE TITLE
Dynamic dependency injection failed

### ISSUE THREAD

**Issue by haoweitech** [kataras/iris#1478]
Why does my dynamic dependency injection fail

```golang
mvcApp := mvc.Configure(app).Register(Db)
mvcApp.Party("/", func(ctx iris.Context) {

    if ctx.GetHeader("X-Token") == "123456" {
        // Dynamic dependency injection failed
        mvcApp.Register(&model.User{
            UserId: 3,
        })
    }

}).Handle(new(controller.MainController))
```

Why only Db dependency injection succeeded, I want to implement dynamic injection in the middleware, so that I can implement other functions based on the requested token, can dynamic injection be implemented in routing middleware? Or is there another way to use it?

**Comment by kataras** [comment]
Hello @haoweitech,

You can't register dependencies like this, you have to register static or dynamic deps before controller registration but you register them on each request(!), I don't know where you see a code-snippet like that but please try to follow the examples and the e-book. For example, to register a request-scoped (dynamic) `*model.User` do that:

```go
mvcApp.Register(func(ctx iris.Context) *model.User {
    if ctx.GetHeader("X-Token") == "123456" {
          return &model.User{UserId:3}
    }

      // [...]
})
mvcApp.Handle(new(controller.MainController))

// [...}

func (c *MainController) Post(u *model.User) {
}
```

Thanks,
Gerasimos Maropoulos.

**Comment by haoweitech** [comment]
thinks! bro
