### ISSUE TITLE
upload file unexpected EOF

### ISSUE THREAD

**Issue by JeffreyBool** [kataras/iris#1479]
the upload file error unexpected EOF

**Comment by kataras** [comment]
Please post us the code-snippet you are using and the filesize you try to upload. I think if you google it you will find the solution but I am here to help you as well, probably it's not even a bug.

Thanks,
Gerasimos Maropoulos

**Comment by JeffreyBool** [comment]
upload file size 3kb

**Comment by kataras** [comment]
Are you sure? What `context.` method do you use?

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/77718478-02693300-701e-11ea-9d91-9d1e0c594967.png)


ctx.FormFile("file")

**Comment by JeffreyBool** [comment]
Do you need to set the size ？ Where to change the size configuration

**Comment by maxzhang** [comment]
the case is upload 3GB file, not 3KB

is it `PostMaxMemory` problem ?

like configuration.go#471
```
	// PostMaxMemory sets the maximum post data size
	// that a client can send to the server, this differs
	// from the overral request body size which can be modified
	// by the `context#SetMaxRequestBodySize` or `iris#LimitRequestBodySize`.
	//
	// Defaults to 32MB or 32 << 20 if you prefer.
	PostMaxMemory int64 `json:"postMaxMemory" yaml:"PostMaxMemory" toml:"PostMaxMemory"`
```

**Comment by kataras** [comment]
> Do you need to set the size ？ Where to change the size configuration

Please read the examples before opening a new issue, here you are: https://github.com/kataras/iris/blob/master/_examples/http_request/upload-file/main.go#L127. Example Code: 

```go
const maxSize = 100 << 20 // 100MB

app.Listen(":8080" /* 0.*/, iris.WithPostMaxMemory(maxSize))
```
