### ISSUE TITLE
Routing cannot match character with slashes

### ISSUE THREAD

**Issue by juan-chan** [kataras/iris#1480]
It seems that iris cannot match wildcards like `**`:

```
// can only match "/api/whatever/end", can't match "/api/whatever/ever/end"
app.Get(`/api/{name:string}/end`, func)

// not found
app.Get(`/api/{name:string regexp(^([a-zA-Z\d\/]{1,32})$)}/end`, func)
```

What I want is:

```
/api/abc/end
/api/abc/def/end
/api/abc/.../xxx/end
```

all the requests above go into a same router, something like:

```
/api/**/end
```

`path` doesn't work because it must be at the end of the expression.

Is there any good idea? Thanks a lot!

**Comment by kataras** [comment]
@cxy777 This is not a bug, you cannot regexp with slashes, you should use the `{p:path}` path parameter and check for its prefix for `"end"` word. However, if I were you I would just register two routes (/end and /end/{p:path}) in one with `HandleMany`:

```go
app.HandleMany("GET", "/end /end/{p:path}", handler)
```

**Comment by cxy777** [comment]
@kataras Yeah, maybe `{p:path}` works, I can check the prefix and suffix. But it is not convenient, the `/end` suffix (and the prefix) may be complex, like `/api/prefix/abc/def/a/su/ff/i/x`, and I'm not sure how many slashes there.

I have many other routes, so is it possible to get a new path parameter type? Something like `/api/{name:subpath}/other/names/here`. It will check the prefix and suffix, the rest parts are `name`.

Thanks for the reply :)

**Comment by kataras** [comment]
Hello @juan-chan, i think there is no need for an extra builtin path parameter. However, you **can create your own** [!](https://github.com/kataras/iris/blob/master/_examples/routing/macros/main.go) https://github.com/kataras/iris/blob/3c526c00676ef526b0be539651910f9b27d51e09/_examples/routing/macros/main.go#L19-L37

Use it as: 

```go
app.Get("/path/{myparam:slice contains([value1,value2])}", func(ctx iris.Context) {
    myparam := ctx.Params().GetEntry("myparam").ValueRaw.([]string)
    ctx.Writef("myparam's value (a trailing path parameter type) is: %#v\n", myparam)
}
```

**Comment by juan-chan** [comment]
@kataras I see, thank you very much !
