### ISSUE TITLE
Embed TLS certificate

### ISSUE THREAD

**Issue by lockbraek** [kataras/iris#1481]
Hello,

I want to embed the certificate and its key in the binary. The function `TLS` requires the path to the file instead the content of it.

It is possible to do that with go-bindata or similar?

It is a self-signed certificate for local testing (can't use `AutoTLS`) and I don't want to hassle the users to copy the certificate to the correct path.

Thanks.

**Comment by alvr** [comment]
Hello,

you can create two constants, one for the certificate and one for the private key and then use the functions of `crypto/tls` to create a new x509 key pair.

```go
package tls

const (
	certificate = `
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
`

	privateKey = `
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
`
)

func loadCertificate() (tls.Certificate, error) {
	if cert, err := tls.X509KeyPair([]byte(certificate), []byte(privateKey)); err != nil {
		return tls.Certificate{}, err
	} else {
		return cert, nil
	}
}

func Config() *tls.Config {
	certs := make([]tls.Certificate, 1)
        cert, err := loadCertificate()

       if err != nil {
		panic(err)
       }

	certs[0] = cert

	return &tls.Config{
		Certificates: certs,
		NextProtos:   []string{"h2", "http/1.1"},
	}
}
```

Then, in the creation of the server you need to use a `host.Configurator` function and initialize the `TLSConfig` variable:

```go

app.Run(
    iris.TLS(":443", "", "", func(su *host.Supervisor) {
        su.Server.TLSConfig = tls.Config()
    }),
)
```
