### ISSUE TITLE
[v12.1.8] how to use the http.Handler in context.Context when I need captcha image.

### ISSUE THREAD

**Issue by conero** [kataras/iris#1484]
_how to use the http.Handler in context.Context when I need captcha image. Code like:_
```go
//@todo 如何实现生成图片
// 验证图片
server.Get("/images/captcha/{type}", func(ctx context.Context) {
       var vType = ctx.Params().Get("type")			// 类型
       captcha.New()
       fmt.Println(vType)
       //ctx.StreamWriter(func(w io.Writer) bool {
       //	captcha.WriteImage(w, vType, captcha.StdWidth, captcha.StdHeight)
       //	return true
       //})
       
      
       captcha.WriteImage(ctx.ResponseWriter(), vType, captcha.StdWidth, captcha.StdHeight)
              captcha.Server(captcha.StdWidth, captcha.StdHeight)
       })
```
_But the all try is failed, and I also search method on net. Can find a way, so I have to ask for the that. What I should do, use the [dchest/captcha](https://github.com/dchest/captcha).

**Comment by kataras** [comment]
@conero I first use this library and I successfully ran it on 1 minute, the problem I think is that you use the second parameter of `WriteImage` as `vType`(what's this?) but this SHOULD be the **id generated by the captcha.New()**. Example Code:

```go
package main

import (
	"github.com/kataras/iris/v12"

	"github.com/dchest/captcha"
)

func main() {
	app := iris.New()

	app.Get("/images/captcha", handler)
	app.Listen(":8080")
}

func handler(ctx iris.Context) {
	id := captcha.New()
	captcha.WriteImage(ctx /*or ctx.ResponseWriter, same thing */, id, captcha.StdWidth, captcha.StdHeight)
}

```

Result:

![image](https://user-images.githubusercontent.com/22900943/79050506-2be7a880-7c33-11ea-9fcc-9bd5b89528ac.png)

**Comment by conero** [comment]
@kataras Thank u a lot. This is a huge help for me. `vType`  just a test sentence. From the these maybe I need more time to learn.

**Comment by kataras** [comment]
You are welcome @conero!
