### ISSUE TITLE
[QUERY] : How to set various fields of tls.Config with custom values?

### ISSUE THREAD

**Issue by BharathB23** [kataras/iris#1486]
Hello @kataras ,
    
      I hope you're doing well :)

      Please let me know, if it's possible to set various fields of crypto/tls.Config such as, CipherSuites,  MinVersion, MaxVersion ... with custom values through some method?
      
      Thanks in advance.

Regards,
Bharath B

**Comment by kataras** [comment]
Hello @BharathB23 , I am doing fine how about you?

Yes, it's easy, just use a custom http.Server with tls config and pass it at app.Run(iris.Server(myServer)). If you search on examples and issues you will find plenty code snippets

**Comment by BharathB23** [comment]
Hi @kataras,

    I am doing good too.
    Thank you for the quick response. 
    Should have done basic check of APIs provided, instead was searching with particular keywords, my bad.

Regards,
Bharath B

**Comment by kataras** [comment]
No problem @BharathB23, you are very welcomed! Post if you need anything
