### ISSUE TITLE
Issue for reading request headers

### ISSUE THREAD

**Issue by TimothyYe** [kataras/iris#149]
Hi, I tried to use iris for the first time, and I wrote a simple demo:

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/logger"
	"github.com/kataras/iris/middleware/recovery"
)

func main() {
	iris.Use(logger.Default())
	iris.Use(recovery.Recovery())

	iris.Config().Render.Template.Directory = "./app/views"

	iris.Get("/hi", hi)
	iris.Listen(":8888")
}

func hi(ctx *iris.Context) {
	ctx.Render("hi.html", map[string]interface{}{"Name": "iris"})
}

```

Then I build and run it, access http://localhost:8888 from Chrome.
Iris shows following error message:

```
2016/05/26 16:27:10 error when serving connection "[::1]:8888"<->"[::1]:64121": error when reading request headers: headers exceed 4096 bytes. Increase ReadBufferSize. buf="GET /hi HTTP/1.1\r\nHost: localhost:8888\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nUpgrade-Insecure-Requests:"..."tMlU4QjRjdGFTRFBwMEI2Nmk2NnJ2R1M1MXlPcEhBPT0tLVdKd1NmK1AvUm1vU1ljbGNSd3kwNmc9PQ==--z1Lhhb9RsT5C6ZAdAVirWBbTyww=; "
```

If I use Safari to access the same URL,  it returns "Hi iris" as expected.
Is Chrome passes too much info and makes request header too large? I'm not sure whether it is an issue...

**Comment by kataras** [comment]
@TimothyYe I just test your example, I create a simple template to view this, firefox and chrome both succed without problem. **I think you should check your browser's settings, this seems to be not iris' problem**

> If your problem is solved please close the issue, if not don't hesitate to ask again!

**Comment by TimothyYe** [comment]
Sorry, it's the problem of my Chrome, after I cleanup the session, it's OK now.

**Comment by kataras** [comment]
I know, anyway thanks for posting it! if you have any issues or ideas please don't hesitate to post again! Thanks for using iris
