### ISSUE TITLE
[FEATURE REQUEST] Socket.io Support?

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#1491]
Socket.io support?

https://socket.io/

**Comment by kataras** [comment]
Hello @rebootcode, you can already use socket.io with Iris if you don't want to use the [iris websocket/ neffos](https://github.com/kataras/neffos) package. Take a look at: https://github.com/kataras/iris/tree/v12/_examples/websocket/socketio. I think you did ask for that in the past, am I right?

**Comment by rebootcode** [comment]
[websocket/neffos](https://github.com/kataras/neffos) 

=> It's a complex app and there is no benchmark - Without a benchmark, it's hard to start.
=> Iris has got a lot many competitive "https://github.com/gofiber/fiber" and "https://github.com/savsgio/atreugo".

I am only now maintaining OLD app with IRIS 😢

**Comment by majidbigdeli** [comment]
@rebootcode  
I before used Socket.io  in my company .  socket.io is good but it have many issue in complex  logic.
but neffos is complete then socket.io . also neffos support pure gorilla and gobwas websoket So soket.io has slow performance  then neffos.  I promise neffos will give you better performance

[https://github.com/gofiber/fiber](https://github.com/gofiber/fiber)  yes fiber project is very clean and good project .i support this .  i know  @kataras  has pull request in fiber project .
but fiber use fasthttp for router another thing It does not have the features of Iris for example Di 

[https://github.com/savsgio/atreugo](https://github.com/savsgio/atreugo) it use fasthttp .
its good project but  i prefer fiber then atreugo .

**another thing fasthttp some time is slow then standard  net/http library** .

**Comment by rebootcode** [comment]
@majidbigdeli - Yes, https://github.com/gofiber/fiber is very clean and high performance. 

Golang is for Performance. If non-performance developers prefer Nodejs over golang

**Comment by majidbigdeli** [comment]
@rebootcode  it is not true golang is just for performance . golang is system  language but node js is runtime . I use go for robotic  . my company use go for os programing  that you can not use node js.  I support Iris in go web frameworks because it has many feature then other framework in go .
please you compare asp.net  core feature  with go frameworks features . most of go web framework 
are just router that  you can implement yourself . I Love Iris  like the asp.net core because it is not just router you can use iris for complex Project .

**Comment by rebootcode** [comment]
@majidbigdeli 

https://github.com/kataras/neffos is complex to understand to create basic room based chat room.

**Comment by kataras** [comment]
@rebootcode Both fiber and atreugo do not support HTTP/2 and gRPC as they are built with fasthttp. Also they use reflect on their handlers, they seem clean but they are not quite, they are just small. Iris does support HTTP/2 and gRPC out of the box, Iris is the fastest http/2 web framework you ever meet. Do you want to use http/1 on your future projects? Go ahead. About the neffos, there are stress-tests, just run them and see the difference between others like socketio.

I answer your question, you can use socketio with Iris, we have an example of that at: https://github.com/kataras/iris/tree/v12/_examples/websocket/socketio

**Comment by kataras** [comment]
@rebootcode I support fiber, it's made by one of my online friends and Iris fan. But the true is that both fiber and atreugo do not support HTTP/2 and gRPC as they are built with fasthttp. Also they use reflect on their handlers, they seem clean but they are not quite, they are just small. Iris does support HTTP/2 and gRPC out of the box, Iris is the fastest http/2 **real web framework** you ever meet. As @majidbigdeli said, others are mostly just routers and insecure tp use if you don't know the internals. Do you want to use http/1 on your future projects? Go ahead. About the neffos, there are stress-tests, just run them and see the difference between others like socketio.

I answer your question, you can use socketio with Iris, we have an example of that at: https://github.com/kataras/iris/tree/v12/_examples/websocket/socketio
