### ISSUE TITLE
if want create custom libary to iris how do write router?

### ISSUE THREAD

**Issue by 23233** [kataras/iris#1495]
#### My libray want to use iris warp router ~ but I'm has a little problem 
* How to just define router and throw routers give use libray people~ demo just like this :
```
my libray 
	app:= iris.New()
	app.Get("user",handler)
	app.Post("user",handler)

use my libray people just 

        app:= iris.New()
        app.Any("admin",MyLibrayThrowRoutersList)

```

### Thanks you ~ Can you give me some pointers?

**Comment by kataras** [comment]
Hello @23233, that's great news. It's easy, your users will register your library as:

```go
app.PartyFunc("/admin", MyLibrayThrowRoutersList)
```

When the `MyLibrayThrowRoutersList` is a `func(router iris.Party)`, e.g.:

```go
func MyLibrayThrowRoutersList(router iris.Party) {
   // register routes inside "router".
   router.Get("/user", getHandler)
   router.Post("/user", postHandler)
}
```

**Comment by kataras** [comment]
You are welcome @23233, don't forget to share your library when you release it! Also, chech the HISTORY.md of this master branch to see what will change on the upcoming Iris release, your library can take advantage of those

**Comment by 23233** [comment]
Yes we do it~ thanks for you help @kataras
