### ISSUE TITLE
var _ Party = (*APIBuilder)(nil) var _ RoutesProvider = (*APIBuilder)(nil) // passed to the default request handler (routerHandler)

### ISSUE THREAD

**Issue by Code-Fight** [kataras/iris#1497]
Thanks for you share.
I found this code on api_build.go
```
var _ Party = (*APIBuilder)(nil)
var _ RoutesProvider = (*APIBuilder)(nil) // passed to the default request handler (routerHandler)
```

Would you tell me what it's mean

**Comment by kataras** [comment]
Hello @Code-Fight, you will see a lot of those when a struct implements an interface. It is a check "hack" at compile time to make sure that a struct(right side) implements correctly the interface (left side). The nil thing you see it is another "hack" to not allocate any memory for these empty structs. Iris is written using the best Go practise and patterns, if you continue reading the library you will learn a lot.

**Comment by Code-Fight** [comment]
Hi @kataras I got it,thank you very much!

**Comment by kataras** [comment]
You are welcome @Code-Fight, please consider follow Iris in social networks and me as well in order to always be notified for more amazing things in Go language.
