### ISSUE TITLE
Middleware for HTTP-Auth

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#150]
It would be great to add this feature. Just write in the config list `login=password` and enable authentication on all pages.

**Comment by kataras** [comment]
Yes I though it too, it was a feature until many people told me ( and myself) that this is developer's only job to secure the user's authentication but I can add a simple sessions username/pass authentication if this is what you ask

**Comment by qskousen** [comment]
I think he meant HTTP auth,
https://en.wikipedia.org/wiki/Basic_access_ahttps://en.wikipedia.org/wiki/Basic_access_authenticationuthentication
<https://en.wikipedia.org/wiki/Basic_access_authentication> this doesn't
require sessions as the user agent sends the authentication with every
request.

**Comment by kataras** [comment]
This is the simple auth, it is not fully secure, I have already this on typescript editor plugin, I can create this middleware with ease if you mean this, decide and tell me :)

**Comment by qskousen** [comment]
I think as it is being accessed over HTTPS then it should be not too bad, but I think this would be a useful middleware to have in any case

**Comment by kataras** [comment]
Ok I'll do this then, no problem, it is easier than sessions auth :P

**Comment by egorsmkv** [comment]
Yes, I meant https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by egorsmkv** [comment]
Users settings, for example:
```go

type Users struct {
  Login        string
  Password string
}

iris.Config().Auth.Users := []Users{ {"foo", "bar"}, {"foo2", "bar2"} }
```

**Comment by egorsmkv** [comment]
Yet it would be convenient to develop a closed API.

**Comment by kataras** [comment]
@egorsmkv , @qskousen  Done. Examples [here](https://github.com/iris-contrib/examples/tree/master/middleware_basicauth_1) and [here](https://github.com/iris-contrib/examples/tree/master/middleware_basicauth_2) .

First approach
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/basicauth"
)

func main() {
	authentication := basicauth.Default(map[string]string{"myusername": "mypassword", "mySecondusername": "mySecondpassword"})

	// to global iris.UseFunc(authentication)
	// to party: iris.Party("/secret", authentication) { ... }

	// to routes
	iris.Get("/mysecret", authentication, func(ctx *iris.Context) {
		username := ctx.GetString("auth") // this can be changed, you will see at the middleware_basic_auth_2 folder
		ctx.Write("Hello authenticated user: %s ", username)
	})

	println("Server is running at: 8080")
	iris.Listen(":8080")
}




```

Second approach
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
	"github.com/kataras/iris/middleware/basicauth"
)

func main() {
	authConfig := config.BasicAuth{
		Users:      map[string]string{"myusername": "mypassword", "mySecondusername": "mySecondpassword"},
		Realm:      "Authorization Required", // if you don't set it it's "Authorization Required"
		ContextKey: "user",                   // if you don't set it it's "auth"
	}

	authentication := basicauth.New(authConfig)

	// to global iris.UseFunc(authentication)
	// to routes
	/*
		iris.Get("/mysecret", authentication, func(ctx *iris.Context) {
			username := ctx.GetString("user") //  the Contextkey from the authConfig
			ctx.Write("Hello authenticated user: %s ", username)
		})
	*/

	// to party

	needAuth := iris.Party("/secret", authentication)
	{
		needAuth.Get("/", func(ctx *iris.Context) {
			username := ctx.GetString("user") //  the Contextkey from the authConfig
			ctx.Write("Hello authenticated user: %s from localhost:8080/secret ", username)
		})

		needAuth.Get("/profile", func(ctx *iris.Context) {
			username := ctx.GetString("user") //  the Contextkey from the authConfig
			ctx.Write("Hello authenticated user: %s from localhost:8080/secret/profile ", username)
		})

		needAuth.Get("/settings", func(ctx *iris.Context) {
			username := ctx.GetString("user") //  the Contextkey from the authConfig
			ctx.Write("Hello authenticated user: %s from localhost:8080/secret/settings ", username)
		})
	}

	println("Server is running at: 8080")
	iris.Listen(":8080")
}




```

**Comment by egorsmkv** [comment]
Thanks, Gerasimos!

**Comment by xpbliss** [comment]
oop!
After ```go get -u github.com/kataras/iris```, and ```go get -u github.com/iris-contrib/examples```, the above two samples is crashed.
why?

**Comment by kataras** [comment]
Fixed

**Comment by retorquere** [comment]
Is there a way to use basic auth without having the passwords in cleartext? I'd prefer to store hashed passwords.

**Comment by kataras** [comment]
Currently, no but you can implement something like this if you want to help go [there](https://github.com/iris-contrib/middleware/basicauth)
