### ISSUE TITLE
About url path filter problem use HandlerDir

### ISSUE THREAD

**Issue by linanh** [kataras/iris#1500]
function "toWebPath" filter url path when using "HandlerDir", see [https://github.com/kataras/iris/blob/b939405441d0932e229848e7c352941a819af13b/core/router/fs.go#L503](url)
But it is normal that the url path has dot character.
In my opinion, we only need filter the url path with only dot characters between slashes in function "toWebPath" for security.

**Comment by kataras** [comment]
You are absolute correct, that line should be removed. Version 12.2.0 contains the fix and a test for that. Thank you a lot @linanh
