### ISSUE TITLE
i18n in iris

### ISSUE THREAD

**Issue by jellybobbin** [kataras/iris#1502]
> I have these language files:

```
locales/
    en-US/
        a.yaml
        b.yaml
    zh-CN/
        a.yaml
        b.yaml
    DA/
        a.yaml
        b.yaml
```

> set default  language:

```
app.I18n.SetDefault("en-US")
```

> How to set language dynamically according to `l` parameter:

```
www.sete.com/xx/xxx?l=en => set en-US
www.sete.com/xx/xxx?l=cn => set zh-CN
www.sete.com/xx/xxx?l=da => set DA

www.sete.com/xx/xxx?l=NotFound => default en-US
```

> In addition, whenI set a language that doesn't exist:
```
www.sete.com/xx/xxx?l=NotFound 
```
I get an error in response like this:

```json
{
    "user": "yaml%!(EXTRA string=Tom....)"
}
```

**Comment by kataras** [comment]
Hello @jellybobbin 

> How to set language dynamically according to l parameter:

```go
app.I18n.URLParameter = "l"
```

> I get an error in response like this:

This error is occurred, you must see your message arguments, your YAML content should expecting them.

I really can't help you more due to lack of information, could you please post us the **code snippet**, including the example translation files so I can be more helpful to you?

Thanks,
Gerasimos Maropoulos

**Comment by jellybobbin** [comment]
@kataras  Thanks for your help..

### I used almost the same code as you:
```golang
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	err := app.I18n.Load("./locales/*/*.yaml", "en-US", "zh-CN", "zh-TW");
	if err != nil {
		panic(err)
	}

	// > How to set language dynamically according to "l" parameter:
	app.I18n.URLParameter = "l"

	app.Get("/", func(ctx iris.Context) {

		ctx.JSON(iris.Map{"user": ctx.Tr("yaml", "Jelly Bobbin")})
	})

	app.Listen(":8080")
}
```
### en-US/a.yaml:
```
yaml: hi- %s by en-US
```

### zh-CN/a.yaml:
```
yaml: hi- %s by zh-CN
```

### zh-TW/a.yaml:
```
yaml: hi- %s by zh-TW
```

### It's normal when I use Chrome:
<img width="344" alt="屏幕快照 2020-05-04 13 38 02" src="https://user-images.githubusercontent.com/28227644/80938725-c3907f00-8e0c-11ea-8eeb-7b9f05fa8280.png">
<img width="340" alt="屏幕快照 2020-05-04 13 38 18" src="https://user-images.githubusercontent.com/28227644/80938730-c8553300-8e0c-11ea-8908-abc9efdbb3fe.png">
<img width="331" alt="屏幕快照 2020-05-04 13 38 31" src="https://user-images.githubusercontent.com/28227644/80938737-cdb27d80-8e0c-11ea-9f72-0233f10e03bc.png">
<img width="362" alt="屏幕快照 2020-05-04 13 38 45" src="https://user-images.githubusercontent.com/28227644/80938744-d2773180-8e0c-11ea-9c62-3b1dbd4a66fc.png">
<img width="371" alt="屏幕快照 2020-05-04 13 41 12" src="https://user-images.githubusercontent.com/28227644/80938781-f5094a80-8e0c-11ea-9041-0409567ba819.png">

### When I use postman, it is normal for me request  `http://localhost:8080?l=` `l=en` `l=zh` `l=zh-TW`

### But when I request `http://localhost:8080?l=NotFound` , i get this response, I don't know if it's good:

<img width="457" alt="屏幕快照 2020-05-04 13 58 48" src="https://user-images.githubusercontent.com/28227644/80939494-65b16680-8e0f-11ea-9630-c565785ab615.png">

### Another question:when i request `http://localhost:8080?l=tw` , I want to set language to `zh-TW`, `http://localhost:8080?l=zh-TW` is not my expected,becuse the URL looks too long , What can I do?

Thanks again 👍

**Comment by jellybobbin** [comment]
@kataras 
### In order to achieve when I request `http://localhost:8080?l=tw`, set set language to zh-TW, I have these middleware:
```golang
package middleware

import (
	"github.com/kataras/iris/v12"
)
func LangMiddleware(ctx iris.Context)  {
	langKey := ctx.Application().ConfigurationReadOnly().GetLocaleContextKey()
	
	language := ctx.URLParam("l")

	switch language {
		case "en":
			ctx.Values().Set(langKey, "en-US")
		case "tw":
			ctx.Values().Set(langKey, "zh-TW")
		default:
			ctx.Values().Set(langKey,  "zh-CN")
	}

	ctx.Next()
}
```

> But it not work.
### I don't want to change dir-name `zh-TW` to `TW` , Although it works

**Comment by kataras** [comment]
Hello @jellybobbin,

`GetLocaleContextKey()` returns the context key which the `i18n.Locale` value is stored (this is used to cache the Locale on many `ctx.Tr` calls in the same request), not the language itself. In order to change the way a language is set by request, you have to use the `app.I18n.ExtractFunc` function, example (tested & worked):

```go
app.I18n.URLParameter = "l"
app.I18n.ExtractFunc = func(ctx iris.Context) string {
	language := ctx.URLParam("l")
	switch language {
	case "tw":
		return "zh-TW"
	case "cn":
		return "zh-CN"
	}

	return "" // if empty then it will continue with the rest.
}
```

**Comment by jellybobbin** [comment]
@kataras 
## Thank you very much for your help. I am using iris happily... 💯

**Comment by kataras** [comment]
You are welcome @jellybobbin! Just to know, on the next release (v12.2.0) you will also have a new method `ctx.SetLanguage(langCode string)` to change the language code anywhere you want.

**Comment by jellybobbin** [comment]
That's a good idea. It has another choice for dynamic setting language.
