### ISSUE TITLE
Feature Request: Add callback on Listen / Server Startup

### ISSUE THREAD

**Issue by azzuwan** [kataras/iris#151]
Hi it would be nice to have Iris to allow us to specify a callback upon listening. In a complex environment it will give us a point to signal other processes to start such as central logging or monitoring or cluster management. Imagine a scenario where server start and stop is fully automated and scripted

**Comment by kataras** [comment]
Please read the docs before posting an issue,
It's already there, read about [plugins](https://kataras.gitbooks.io/iris/content/plugins.html).

simple example [here](https://github.com/iris-contrib/examples/blob/master/plugin_simple/main.go)
