### ISSUE TITLE
Suggest It can be reload when the template html file is changed.

### ISSUE THREAD

**Issue by linyouhappy** [kataras/iris#1510]
Edit the template html file.It need restart iris?

**Comment by kataras** [comment]
No you don't need to restart the whole Iris[*](https://github.com/kataras/iris-cli). You just need to set the `Reload` option to true.

https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/_examples/view/template_html_0/main.go#L10-L11
