### ISSUE TITLE
Can you provide an implementation for websocket that does not need to connect to the namespace?

### ISSUE THREAD

**Issue by hjzCy** [kataras/iris#1512]
The weksocket client must connect to a namespace of the server before the server can receive the response. However, if you need to start the client in another way, how should you connect to the namespace corresponding to the server?

For example, the websocket client of pyqt5:

```go
self.websocket = QWebSocket()
self.websocket.connected.connect(self.setupWidget)
self.websocket.disconnected.connect(self.onDisconnected)
self.websocket.textMessageReceived.connect(self.onMessageReceived)
self.websocket.open(QUrl(f"ws://localhost:8080/login?token={cbc.CBCEncrypt(f'{self.username.text()}, {self.password.text()}')}"))
```

Or python's websocket client:

```go
import asyncio
import websockets

async def hello(uri):
    async with websockets.connect(uri) as websocket:
        await websocket.send("Hello world!")
        await websocket.recv()

asyncio.get_event_loop().run_until_complete(hello('ws://localhost:8080/login'))
```

Using these two methods to connect to neffos' websocket server, the client can receive the signal that it is connected to the server, the server receives the request log, but does not respond to the method body:

```go
package main

import (
	"log"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/websocket"
	"github.com/kataras/neffos"
)

func main() {
	app := iris.Default()

	ws := neffos.New(websocket.DefaultGorillaUpgrader, neffos.Namespaces{
		"default": neffos.Events{  // No response
			"login": func(ns *neffos.NSConn, msg neffos.Message) error {
				ctx := websocket.GetContext(ns.Conn)
				log.Println("token:", ctx.URLParam("token"))
				return nil
			},
		},
	})

	app.Get("/login", websocket.Handler(ws))

	app.Listen(":8080")
}
```

Server logs:

```shell
PS C:\Users\78081\OneDrive\Go\go_study> go run "c:\Users\78081\OneDrive\Go\go_study\iris\01 Getting started\test\main.go"
Now listening on: http://localhost:8080
Application started. Press CTRL+C to shut down.
[INFO] 2020/05/11 17:30 200 966.2µs ::1 GET /login
```

`neffos.Events` cannot receive a response, because the client must connect to the namespace corresponding to the server! But what if other clients cannot, and do not provide the ability to connect to the namespace? what can we do about it?

**Comment by kataras** [comment]
You can have an empty namespace. The client cannot connect because it does not understand the neffos(iris ws) events. If you want to communicate through a native websocket client your server must register the OnNativeMessage with empty namespace or just Events object. Wr already have an example of this at: https://github.com/kataras/neffos/blob/f1431864185db0b334b82e3817eb03bd957f9fda/_examples/native-messages/native.go#L43

**Comment by hjzCy** [comment]
My python client cannot set the namespace to connect to the server:

```python
self.websocket = QWebSocket()
self.websocket.connected.connect(self.setupWidget)
self.websocket.disconnected.connect(self.onDisconnected)
self.websocket.textMessageReceived.connect(self.onMessageReceived)
self.websocket.open(QUrl(f"ws://localhost:8080/login"))
```

Because there is no api to set。I cannot use go, the server does not respond:

```go
package main

import (
	"log"
	"net/http"

	"github.com/kataras/neffos"
	"github.com/kataras/neffos/gorilla"
)

var pongMessage = []byte("pong")

var events = neffos.Events{
	neffos.OnNativeMessage: func(c *neffos.NSConn, msg neffos.Message) error {
		log.Printf("Got: %s", string(msg.Body))
		if !c.Conn.IsClient() {
			return c.Conn.Socket().WriteText(pongMessage, 0)
		}
		return nil
	},
}

func main() {
	websocketServer := neffos.New(gorilla.DefaultUpgrader, events)
	websocketServer.OnConnect = func(c *neffos.Conn) error {
		log.Println(c.Namespace(neffos.OnNativeMessage))
		return nil
	}
	router := http.NewServeMux()
	router.Handle("/login", websocketServer)
	log.Fatal(http.ListenAndServe(":8080", router))
}
```

Is there any other way?

**Comment by kataras** [comment]
I don't know the python's `QWebSocket` implementation, is it a custom library, is it the python's standard library? I have no idea. It works with C#, Java, Node.js and browser natively, easy as:

```js
 w = new WebSocket("ws://localhost:8080/login");
 w.send('message');
```

What's the equivalent of python to that?

**Comment by hjzCy** [comment]
Okay, the client will respond to the server event after sending a message, thank you!
