### ISSUE TITLE
URLParam() and URLParams() only return the first param? 

### ISSUE THREAD

**Issue by SalleryWang** [kataras/iris#1514]
?pageNumber=1&pageSize=wxasd
just return the pagenumber

**Comment by kataras** [comment]
`URLParam("pageNumber")` will return the "1", `URLParam("pageSize")` will return the "wxasd" value. `URLParams` will a `map[string]string`, if more than one values with the same key then the values are separated by comma `,`. e.g. in your case `URLParams()` will return `{pageNumber: 1", pageSize: "wxasd"}`. Whats the problem @SalleryWang? Show me some code so I can help you

**Comment by SalleryWang** [comment]
i think so！but just return the first！ it is confuzed




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/16/2020 01:47, Gerasimos (Makis) Maropoulos wrote:

URLParam("pageNumber") will return the "1", URLParam("pageSize") will return the "wxasd" value. URLParams will a map[string]string, if more than one values with the same key then the values are separated by comma ,. e.g. in your case URLParams() will return {pageNumber: 1", pageSize: "wxasd"}. Whats the problem @SalleryWang? Show me some code so I can help you

**Comment by SalleryWang** [comment]
i use the version 11




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

在2020年05月16日 11:03，SalleryWang 写道：
i think so！but just return the first！ it is confuzed




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/16/2020 01:47, Gerasimos (Makis) Maropoulos wrote:

URLParam("pageNumber") will return the "1", URLParam("pageSize") will return the "wxasd" value. URLParams will a map[string]string, if more than one values with the same key then the values are separated by comma ,. e.g. in your case URLParams() will return {pageNumber: 1", pageSize: "wxasd"}. Whats the problem @SalleryWang? Show me some code so I can help you

**Comment by kataras** [comment]
Why you don't upgrade to the v12 in order to check if that fixes your issue?

**Comment by SalleryWang** [comment]
i have upgrade to v12. it doesn‘t work




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/17/2020 04:44, Gerasimos (Makis) Maropoulos wrote:

Why you don't upgrade to the v12 in order to check if that fixes your issue?

**Comment by kataras** [comment]
@SalleryWang I've just tried it and it works here, could you please share us the code snippet you use and the url value so I can test it locally?

**Comment by SalleryWang** [comment]
thx
