### ISSUE TITLE
[FEATURE REQUEST] TLS for Redis.

### ISSUE THREAD

**Issue by heyt0ny** [kataras/iris#1515]
**Is your feature request related to a problem? Please describe.**
I'm transferring to DO managed Redis and it only supports TLS, while in current Iris there is no way to enable TLS for Redis (for sessions).

**Describe the solution you'd like**
I'm using Redigo. I guess that adding `redisRAW.DialUseTLS(true)` to [`options`](https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/sessions/sessiondb/redis/driver_redigo.go#L282) will solve this problem. So adding additional filed `TLS` to `RedigoDriver` struct will be perfect. 

**Describe alternatives you've considered**
Is it possible to add this flag in current version of iris? I tried to override `func (r *TLSRedisDriver) Connect(c redis.Config) ` , but because `pool` field is private it's not possible.  I also tried to completely copy and reimplement `iris/session/sessiondb/redis` - but  it freezes on launch. Any suggestions?

Thank you.

**Comment by heyt0ny** [comment]
I was able to solve this using [stunnel](https://docs.objectrocket.com/redis_stunnel.html). But implementing this inside Iris would be much preferable way to solve this problem✌️

**Comment by kataras** [comment]
@heyt0ny I don't have much experience with this subject, I will do my research and try to implement this but I will need ur help on testing and e.t.c.

**Comment by kataras** [comment]
@heyt0ny eventually both redis drivers support TLS on their clients (as they should), it was easy to add it. However, is that you asked for?

https://github.com/kataras/iris/blob/23286225d263c6e2638fc2230d83d5ae5a03e880/sessions/sessiondb/redis/database.go#L52

**Comment by heyt0ny** [comment]
wow, thank you. It's what I was looking for 🚀

**Comment by kataras** [comment]
> wow, thank you. It's what I was looking for 🚀

Sounds great, you can use it by `go get github.com/kataras/iris/v12@master` and when the v12.2.0 released u can just edit your go.mod

**Comment by heyt0ny** [comment]
Cool! Never seen such a sped 💪
