### ISSUE TITLE
How to use the filesystem to store the session?

### ISSUE THREAD

**Issue by bigBron** [kataras/iris#1517]
I've been following iris. It's great. Is there any out of the box method to use filesystem store session?

**Comment by kataras** [comment]
Hello @bigBron, thank you!

We don't provide a file storage for sessions anymore, it's unproductive and it's quite slow on concurrent requests. We support redis, boltdb and badger that are really fast and you can scale up horizontally through redis. However, you can implement your own `sessions.Database`: https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/sessions/database.go#L24-L53

I have plans to add a cookie database through cookie serialization and encryption (that can live in the client side and u don't need a server database between server restarts), although still I don't recommend saving sensitive data in session values.

**Comment by bigBron** [comment]
@kataras Thank you for your reply, I try to use badger, It looks good, and I have more question, I set int type variable，but I got float64 type variable, I don't understand.

```golang
code:
        val := 10
	fmt.Printf("type：%T val：%+v \n", val, val)

	sess.Set("uid", val)

	uid := sess.Get("uid")
	fmt.Printf("type：%T val：%+v \n", uid, uid)

output:
        type：int val：10 
        type：float64 val：10 
```

**Comment by bigBron** [comment]
@kataras I'm here again😂,In the process of development, services are often restarted, and an error prompt is encountered: `unable to initialize the budget based session database: value log truncate required to run dB`. This might result in data loss. Do you have any good practical suggestions?

**Comment by kataras** [comment]
> @kataras Thank you for your reply, I try to use badger, It looks good, and I have more question, I set int type variable，but I got float64 type variable, I don't understand.
> 
> ```go
> code:
>         val := 10
> 	fmt.Printf("type：%T val：%+v \n", val, val)
> 
> 	sess.Set("uid", val)
> 
> 	uid := sess.Get("uid")
> 	fmt.Printf("type：%T val：%+v \n", uid, uid)
> 
> output:
>         type：int val：10 
>         type：float64 val：10 
> ```

You have right, memory store retrieves the value with the correct number type but both badger and boltdb don't. Working for a fix as we speak.

**Comment by kataras** [comment]
> @kataras I'm here again😂,In the process of development, services are often restarted, and an error prompt is encountered: `unable to initialize the budget based session database: value log truncate required to run dB`. This might result in data loss. Do you have any good practical suggestions?

About that, I think it's better to ask this on the badger repository itself, here you are: https://github.com/dgraph-io/badger/issues

**Comment by bigBron** [comment]
@kataras Thank you very much for your patience to reply, the iris is a very enthusiastic community. I will try to solve these problems myself and continue to use iris in the next project.

**Comment by kataras** [comment]
> @kataras Thank you very much for your patience to reply, the iris is a very enthusiastic community. I will try to solve these problems myself and continue to use iris in the next project.

Thanks @bigBron, I've added a note on the examples about this issue (I totally forgot it). You are welcome, every time, don't hesitate to ask!
