### ISSUE TITLE
I want to make a mp3 online player，but when i use it to listen music, i found it can't jump to the specified point in time that I want it to jump to. 

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1519]
```
func main(){
	x:=iris.New()
	x.Get("/",getFile)
	x.Run(iris.Addr(":8080"))
}

func getFile(ctx iris.Context){
	str,err:=ioutil.ReadFile("xxx.mp3")
	if err!=nil{
		_, _ = ctx.Write([]byte(""))
		return
	}
	_, _ = ctx.Write(str)
}
```
English:
i write a easy demo，but it can only listen or download the music . it can not jump the specified time point. How can i do?
中文：
我写了一个简单的例子，但是它只能播放或者下载音乐。但我并不能像其他在线播放器一样，时间戳从00：00跳转到00：15，有什么好的解决办法吗？

**Comment by kataras** [comment]
@CulionBEAR this is general Go question, you need to "seek" to a specific point. There are many ways you can do that, please search that online as it has nothing to do with Iris or a web framework at general :/

**Comment by CulionBEAR** [comment]
@kataras emmmmmmm okok，thanks
