### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by bd4k** [kataras/iris#152]
Book include example of "streaming out", what about "streaming in"? Can i use iris  streaming in opposite direction (io.Reader || bufio.Reader)? I have tons incoming long data.

**Comment by kataras** [comment]
They are many ways of doing that (If I understand your question).

Please provide me an example of how **you used to do** it with net/http and I can convert it to Iris.

> Don't forget to star Iris if you liked it!

**Comment by kataras** [comment]
@bd4k  Make use of the `context.StreamReader`

``` go
// StreamReader sets response body stream and, optionally body size.
//
// bodyStream.Close() is called after finishing reading all body data
// if it implements io.Closer.
//
// If bodySize is >= 0, then bodySize bytes must be provided by bodyStream
// before returning io.EOF.
//
// If bodySize < 0, then bodyStream is read until io.EOF.
StreamReader(bodyStream io.Reader, bodySize int)
```


Note that: .Stream will be deprecated at the final v3 release, please use the `StreamWriter` instead, thanks you!

> Don't forget to star Iris if you liked it!
