### ISSUE TITLE
Failed to set version on github.com/kataras/iris to c8e73f4f4df2c725f91f8aa659f9f60a7154c039: Unable to update checked out version: exit status 1

### ISSUE THREAD

**Issue by ssk199441** [kataras/iris#1520]
For the longer period of time we are using the we are using this package.

//This is how it configured it in glide.yaml file
- package: github.com/kataras/iris
  version: c8e73f4f4df2c725f91f8aa659f9f60a7154c039

When trying to give glide install we are getting the following error

Failed to set version on github.com/kataras/iris to c8e73f4f4df2c725f91f8aa659f9f60a7154c039: Unable to update checked out version: exit status 1

we have used errors modules in most of the go files. so it is very hard to switch to latest version and make changes in all our code.

Is there any specific version that core/errors package that we can use

**Comment by kataras** [comment]
Hello @ssk199441, I don't know what's going on with glide as I am not using it at all. I only use go modules and you/your team should too. go-dep users had the same issue, which is solved by: https://github.com/kataras/iris/issues/1143#issuecomment-472035292

The correct way to install Iris is using go modules though: https://github.com/kataras/iris/wiki/Installation

About:

> we have used errors modules in most of the go files. so it is very hard to switch to latest version and make changes in all our code.

I just want you to know that If you have a public/private repo (or you are able for a real-time call) I can help you upgrading everything to the latest version, it will not take more than 1 day.

**Comment by ssk199441** [comment]
I need you version v11 to be installed 
Can you guide how to install that

**Comment by kataras** [comment]
Yes, of course, here you are:

```sh
go get github.com/kataras/iris@d466f8cd92e19a766a87d0ab22f2d6269cff5dec
```

![image](https://user-images.githubusercontent.com/22900943/82292651-ee093d00-99b3-11ea-8ded-fffa46365f07.png)

**Comment by ssk199441** [comment]
i tried to install you version 11.2.0
//
- package: github.com/kataras/iris
  version: 11.2.0

I am getting the following error
[ERROR]	Failed to set version on github.com/kataras/iris to de9904ff6d387d4f80ae0c99c98af1d6ffa64a96: Unable to update checked out version: exit status 1

go version go1.8.7 linux/amd64

**Comment by ssk199441** [comment]
Is there any dependency between the kataras and go version

**Comment by kataras** [comment]
@ssk199441 Yes, the minimum go version is 1.13 as defined at the [Installation Section](https://github.com/kataras/iris/wiki/Installation)

![image](https://user-images.githubusercontent.com/22900943/82955508-ac7e2080-9fb7-11ea-8e29-1c5c5ec615ab.png)
