### ISSUE TITLE
[FEATURE REQUEST/BUG] allow Party from Party

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1522]
**Is your feature request related to a problem? Please describe.**
I'm working on an API with many path, sometimes it would be nice to have the option to use the Party for a Party and not on the base Application.

**Describe the solution you'd like**
I would like to use Party like:

```
r := app.Party("/api")
// ... many r.Get/Post...
ticket := r.Party("/ticket")
// ... many ticket.Get/Post...
location := r.Party("/location")
// ... many location.Get/Post...
```

This would help to use a more clean and sperated structure.

**Describe alternatives you've considered**
I have no Idear, currently I give each function call the iris.Application with it... but its... not cool.

**Additional context**

**Comment by kataras** [comment]
Hello @Dexus I've just seen this, you can already do that, or ?

**Comment by Dexus** [comment]
Yes when I open it, I hade some missconfigurations that triggers me and after open the ticket I found my problem 🥵

Von meinem iPhone gesendet

**Comment by kataras** [comment]
Oh I see, ok no problem just confirming it. Stay safe and have fun!
