### ISSUE TITLE
[BUG] Implicit license issue with github.com/gavv/httpexpect 

### ISSUE THREAD

**Issue by shivacharanms** [kataras/iris#1526]
I see that "github.com/gavv/httpexpect" module is being used in iris which in turn uses "github.com/fasthttp-contrib/websocket" module, and the websocket module has no LICENSE tied to it which causes an implicit license issue for anyone using iris.
Can we remove  "github.com/gavv/httpexpect" module from iris repo?
Also i see that the owner for "github.com/fasthttp-contrib/websocket" module is Makis Maropoulos i am just wondering if this is the same @kataras ? if so could you add the license to the same?

**Comment by kataras** [comment]
Hello @shivacharanms, there is no license issue at all. First of all we use the [iris-contrib/httpexpect](https://github.com/kataras/iris/blob/22de33f057a34cfb4356534a0f58e7fcde8dfed0/go.mod#L18) which is a modified version of "gavv/httpexpect" **without the fasthttp and fasthttp-contrib/websocket** and secondly... yes I am the first who created a complete web framework on top of fasthttp, almost everything u see about fasthttp is originally created by me.

**Comment by shivacharanms** [comment]
hi @kataras 
As you can see here [https://github.com/kataras/iris/search?q=gavv%2Fhttpexpect&unscoped_q=gavv%2Fhttpexpect](url) gav.httpexpect is being used so it will cause implicit license issues for anyone who uses iris.
could you please add the license to fasthttp repo? which will avoid these implicit issues.

**Comment by kataras** [comment]
@shivacharanms I think you have no idea what you talking about, and you didn't even read our LICENSE or NOTICE file.

Your search results is about the v12 branch. The master one does use [iris-contrib/httpexpect](https://github.com/iris-contrib/httpexpect) which is a modified version **without any fasthttp** imports that gavv/httpexpect uses for their fasthttp users(also note that I was the guy who told gavv to add support for fasthttp too :)). **For the v12 branch, we already have a LICENSE NOTICE AT:** https://github.com/kataras/iris/blob/v12/NOTICE#L48

If you see master branch (the under-development, which will be released as version 12.2) you will get it, all necessary step are already taken don't worry about LICENSE here, I add license notices even on my own libraries.

**Comment by kataras** [comment]
@shivacharanms I think you have no idea what you talking about, and you didn't even read our LICENSE or NOTICE file.

Your search results is about the v12 branch. The master one does use [iris-contrib/httpexpect](https://github.com/iris-contrib/httpexpect) which is a modified version **without any fasthttp** imports that gavv/httpexpect uses for their fasthttp users(also note that I was the guy who told gavv to add support for fasthttp too :)). **For the v12 branch, we already have a LICENSE NOTICE AT:** https://github.com/kataras/iris/blob/v12/NOTICE#L48

If you see master branch (the under-development, which will be released as version 12.2) you will get it, all necessary steps are already taken don't worry about LICENSE here, I add license notices even on my own libraries. 

**EDIT**

Your account has only one issue, this one.

![image](https://user-images.githubusercontent.com/22900943/82884779-e36b1c80-9f4c-11ea-9813-22d340d02864.png)

Man I think you are catfish-ing here, sorry but I have to delete the issue, you take advantage of my kindness and my love to answer questions about Iris just to be noticed. That sucks. If you like Iris use it, if you don't then it's fine, but you can't spread lies and missinforming our users here.

**Comment by shivacharanms** [comment]
Since we are seeing these license issues we are approaching you, big thanks for this wonderful software. I see that the new iris-contrib/httpexpect has MIT license and this should solve our problems. Can you give us the tentative release date for the new version?

**Comment by kataras** [comment]
Hello @shivacharanms, the upcoming version should be released until June 01 2020. However, you can already play with the `master` branch by:

```
$ go get github.com/kataras/iris/v12@master
```

May I ask, who is asking (who is "us") ? ( You can contact me in private through [chat](https://chat.iris-go.com) as well).

Thanks,
Gerasimos Maropoulos
