### ISSUE TITLE
Modify the usage of cors 

### ISSUE THREAD

**Issue by hanyue2019** [kataras/iris#1527]
I use the middleware cors,But the way is very strange。
AllowMethod makes me confused

your example

```go
	app := iris.New()
	crs := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"}, // allows everything, use that to change the hosts.
		AllowCredentials: true,
	})
	v1 := app.Party("/api/v1", crs).AllowMethods(iris.MethodOptions) 
        ...... 
```
I think you can change the way like

```go
	app := iris.New()
	crs := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"}, // allows everything, use that to change the hosts.
		AllowCredentials: true,
	})
        app.Use(crs())  //donot use allowMethod
```
also I found the middleware cors doesnot work，
i got one which works https://studygolang.com/articles/25389, I am not so familiar with http protocol，maybe u can consider it

**Comment by kataras** [comment]
@hanyue2019 cors is a community-based middleware, please open this issue on https://github.com/iris-contrib/middleware instead, so contributors can look it up.

**Comment by kataras** [comment]
@hanyue2019 just use something like that and you will be fine:

https://github.com/kataras/iris/blob/deb044ee66c963538b7e45c039f5d9af229cbed6/_examples/experimental-handlers/cors/simple/main.go#L1-L55

Example: https://github.com/kataras/iris/tree/master/_examples/experimental-handlers/cors/simple

**Comment by kataras** [comment]
Another solution, using the native middleware:

https://github.com/kataras/iris/blob/3c526c00676ef526b0be539651910f9b27d51e09/_examples/auth/cors/main.go#L1-L63
