### ISSUE TITLE
Unable to read request body with gzip content using iris.Context in post method

### ISSUE THREAD

**Issue by fivjagetiya** [kataras/iris#1528]
**Describe the bug**
I have a app which accepts a post request with gzip content in request body as buffer. unable to read such request body using iris.Context c , c.GetBody()

**To Reproduce**
iris.Context c , c.GetBody()

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**Additional context**

**Comment by kataras** [comment]
Hello @fivjagetiya, what's your client code you use to read gzip body?

**Comment by kataras** [comment]
Hello @fivjagetiya, where is the code snippet you used?

**Comment by fivjagetiya** [comment]
`api.Post("/", func(c iris.Context) {

		// start := time.Now()
		// c.Set("start", start)

		// addr := c.RemoteAddr()
		addr := c.GetHeader("Cf-Connecting-Ip")

		glog.Infof("Request headers: %s", c.Request().Header)

		var req Req
		err := c.ReadJSON(&req)
		if err != nil {
			buf, err := c.GetBody() **//fails here while getting body, sets err as EOF**
			if err != nil {
				glog.Warningf("Error creating zlib reader: %s", err)
			}
			buff := bytes.NewBuffer(buf)
			gz, err1 := gzip.NewReader(buff)
			if err1 != nil {
				glog.Warningf("Error creating zlib reader: %s", err)
			}
			res, err := ioutil.ReadAll(gz)
			gz.Close()
			err = json.Unmarshal(res, &req)
			if err != nil {
				glog.Infof("Another error reading JSON: %s", err)
				c.StatusCode(iris.StatusOK)
				c.JSON(map[string]interface{}{"error": "Undeserializable"})
				return
			}
		}
}`

**Comment by kataras** [comment]
Try `ctx.Request().Body` and wrap it with a `gzip.Reader`, and use `json.NewDecoder`.

**Comment by kataras** [comment]
@fivjagetiya The upcoming version (12.2) contains a new `iris.GzipReader` middleware which will do the job for you automatically, when client sends gzip-compressed data, example at: https://github.com/kataras/iris/blob/90cf1f0a2d4f1adc289aa54410c623e9f19bdde9/_examples/http_request/read-gzip/main.go#L29-L37

You can test it out today using `go get -u github.com/kataras/iris/v12@master`.
