### ISSUE TITLE
[QUESTION] how to force the request to HTTPS by redirection

### ISSUE THREAD

**Issue by supermqB** [kataras/iris#1529]
I'm trying to establish a web app using Iris framework. and used below code to start a TLS listener
```go
app.Run(iris.TLS(":8443", "server.pem", "server.key"))
```

I got messge "Client sent an HTTP request to an HTTPS server." when access the app by `http://localhost:8443`.

Is that possible to handle the "http" requests and redirect it to "https" addess. I see there is the example for redirecting a request by monitoring a specific port. just like if user access the app through 80, we forward it to port 443. 

How to implement the similar behavior for the same port number, please advice.

**Comment by kataras** [comment]
Hello @supermqB, the current release (12.1.8) do auto-redirect from http to https only when using `AutoTLS`. To do that with `TLS` you should check out the [examples](https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/_examples/http-listening/listen-tls/main.go#L22-L28): https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/_examples/http-listening/listen-tls/main.go#L22-L28

However, the upcoming (12.2) does the same on `TLS` too unless `iris.TLSNoRedirect` host Configurator is provided on iris.TLS (or iris.AutoTLS), e.g. `app.Run(iris.TLS("127.0.0.1:443", "mycert.cert", "mykey.key", iris.TLSNoRedirect))`.

**Comment by supermqB** [comment]
Thanks. I have added the forwarding from http port to https port.

Looking forward the identical port https forwarding will work in 12.2 release.

Another finding in the example, we'd better remove the IP from the listening address. otherwise, we can't access the application through public IP.  Struggled a couple of days on it.

```go
 app.Run(iris.TLS(":443", "mycert.cert", "mykey.key")) 
```

**Comment by kataras** [comment]
Yeap, I know. This is just an example, you can remove the 127.0.0.1 and keepjust the pott of :80 and :443

**Comment by mcoo** [comment]
You can use this:
```golang
func before(ctx iris.Context) {
	if !strings.Contains(ctx.FullRequestURI(),"https") && conf.Sysconfig.Tls {
		ctx.Redirect(strings.ReplaceAll(ctx.FullRequestURI(),"http","https"),302)
		return
	}
...
}
```

**Comment by kataras** [comment]
@mcoo you can use `ctx.Request().TLS != nil` to check for that as well
