### ISSUE TITLE
Contribute: New website and logo for Iris

### ISSUE THREAD

**Issue by kataras** [kataras/iris#153]
Hello to everyone who use and love Iris, you already see that I'm trying to keep up with your feature requests , bug fixes and more, almost alone.

I'm designing the final v3 so I don't have plenty of time to do these:

It's the first time Iris needs your help,

we have a logo which I found it from google images by searching tag 'iris greek mythology' , I think it's time having our own logo

- create a logo and  PR it with a folder by your github username [here](https://github.com/iris-contrib/logo/tree/contribs) for example the final path should be `https://github.com/iris-contrib/logo/tree/contribs/kataras/` , see an example [here](https://github.com/iris-contrib/logo/tree/contribs/google-images)

The gitbook is good, but I think that users/developers are boring reading the docs from there, I think they/you are more comfortable to read docs and examples by a static website, so

- Design a static, website for documentation, use a template or anything you like, PR it with a folder by your github username [here](https://github.com/iris-contrib/website/tree/contribs) for example the final path should be `https://github.com/iris-contrib/website/tree/contribs/kataras/website/` .

Edit 2:

for website docs, this approach may helps: ` http://www.chartjs.org/docs/` looks **like gitbook** but its not 

## Results

OK. 
Website created by @kujtimiihoxha . Visit our new site: http://iris-go.com .
Logo created by @OneebMalik .

**Comment by egorsmkv** [comment]
If we translate the name into the Russian language, you get a plant with the same name. See images: https://goo.gl/Kg5HLL

You can choose a beautiful flower and make it a logo :white_flower:

**Comment by kataras** [comment]
I know its a flower also, I searched that on wikipedia before selecting the name:P  but the meaning is the the beautiful phenomenon after rain...

I just want something **unique** made by iris' user/developer

**Comment by vadimyer** [comment]
@egorsmkv The idea with flower is nice, I will try to make a nice looking modern concept of this in a logo.

**Comment by raitucarp** [comment]
@kataras could you split the gitbook related discussion in its own issue?

**Comment by kataras** [comment]
@raitucarp open it by yourself! it's 100% yours repository too, this framework is a community-driven I dont make decisions alone, you make it so nice framework you have the same rights as I do!

**Comment by kataras** [comment]
@raitucarp You mean the website discussion, can you tell me why, did you find something?

**Comment by insionng** [comment]
![irislogo](https://cloud.githubusercontent.com/assets/2784837/15627049/2ac0b2e6-250a-11e6-8eed-64e85d401375.png)

![irislogo2](https://cloud.githubusercontent.com/assets/2784837/15627051/37616dce-250a-11e6-843d-a705fde8b1d5.png)


This is my design, inspired by code(</>) and iris.

**Comment by oknoorap** [comment]
My suggestion is curren golang logo as a female goddess, i thought it will be funny.

**Comment by qskousen** [comment]
Iris should definitely stick with the Iris goddess meaning, and here's why:

- It was @kataras intention when he named the framework in the first place.

- Iris the goddess is the "personification of the rainbow and messenger of the gods" and Iris brings many things together into one (like a rainbow brings colors together) and sends messages back and froth between server and client, as Iris carries messages between the gods and mortals.

- Iris "travels with the speed of wind from one end of the world to the other", and Iris is the fastest web framework.

- "As a goddess, Iris is associated with communication, messages, the rainbow and new endeavors." I think the parallels in that to Iris framework are pretty clear.

- Iris the goddess has golden wings. I don't know how that relates to Iris the framework, but it's pretty awesome.

@oknoorap that would be pretty amusing. 

@egorsmkv it is also a flower in english :)

Sadly I am really really terrible with drawing so I can't contribute much to the logo, haha.

**Comment by kataras** [comment]
@qskousen Totally agreewith you, I tried to describe it to the gitbook but I couldn't, you did it with the best words!! Your answer with your name in front will be at the index page of the new iris' website !! Excellent.

I hope someone here will help iris, I don't have plenty of time because I'm coding the [cmd](https://github.com/kataras/iris/tree/master/iris) !!

**Comment by monopollly** [comment]
maybe something [simple, dynamic & stable](https://gyazo.com/696c1aff04a559fd5df681d843eea346)?

**Comment by kataras** [comment]
@monopollly Nice but we need a fresh icon also:) 

The community doesn't want to contribute to the new website so far ...I can wait...

**Comment by MeetThePatel** [comment]
as @qskousen mentioned, we should stick with Iris the goddess, and maybe we can use a rainbow as the icon, or something of that sort.

**Comment by kataras** [comment]
@MeetThePatel  This is used now but I found that from the google images, we need something special for us I think :)

**Comment by tieubao** [comment]
@insionng @kataras your design and the repo description made me think of The Flash from DC Comic and Iris West is Barry girlfriend 😛

https://en.wikipedia.org/wiki/Iris_West_Allen

Some people from Golang Vietnam Community (https://www.facebook.com/golang.org.vn/posts/1411204229178579) have the same thought

**Comment by OneebMalik** [comment]
I don't have push access so I assume I just upload my take on the logo here?
![iris logo with txt and bg](https://cloud.githubusercontent.com/assets/3179918/16334458/19eb10ea-39cf-11e6-81e0-2a0fe14d0183.jpg)
![iris logo without bg](https://cloud.githubusercontent.com/assets/3179918/16334457/19eaf560-39cf-11e6-97a2-fc6fdbcc087b.jpg)
![iris logo with bg](https://cloud.githubusercontent.com/assets/3179918/16334459/19ec2ef8-39cf-11e6-9c7e-057367f4db95.jpg)

**Comment by kataras** [comment]
@OneebMalik Did you made these? wonderful!

> I don't have push access

Go [here](https://github.com/iris-contrib/logo), fork the repo, create a new folder under your name 'OneebMalik' , upload the logos there, go back to the [iris-contrib/logo(https://github.com/iris-contrib/logo) and on the top page you will see a button says ' Pull request' press that and I will approve your pull request immediatly!! ( Do this please because I don't want to get the credits for your work:) )

**Comment by kataras** [comment]
@OneebMalik Did you made these? wonderful!

> I don't have push access

Go [here](https://github.com/iris-contrib/logo), fork the repo, create a new folder under your name 'OneebMalik' , upload the logos there, go back to the [iris-contrib/logo](https://github.com/iris-contrib/logo) and on the top page you will see a button says ' Pull request' press that and I will approve your pull request immediatly!! ( Do this please because I don't want to get the credits for your work:) )

**Comment by OneebMalik** [comment]
@kataras Glad you like it! Thanks for the instructions. :) I just made a pull request.

**Comment by kataras** [comment]
@OneebMalik Just approved, thanks you very very very much!!! you 're the first!

**Comment by metaheap** [comment]
how about some kind of iris folding shapes for inspiration?

![iris_fold_heart_3](https://cloud.githubusercontent.com/assets/1987232/16411446/af12a99c-3cec-11e6-8b53-5d4233daadbe.jpg)

**Comment by coreyworrell** [comment]
Possible rough ideas based off current and others suggestions, icon could be made from just the rainbow as current one is.

<img src="https://cloud.githubusercontent.com/assets/162595/16779944/3fbb7c34-4829-11e6-96c0-8cb9678bf02f.png" width="200" height="158" alt="iris">

<img src="https://cloud.githubusercontent.com/assets/162595/16779945/3fec2654-4829-11e6-8663-85b6c6138eab.png" width="200" height="158" alt="iris">

**Comment by kataras** [comment]
@coreyworrell 

Very nice!!
Do a pr and push your work to the logo's [repo](https://github.com/iris-contrib/logo), the next version v4 will have one of these logos.

**Steps** 
Go [here](https://github.com/iris-contrib/logo), fork the repo, create a new folder under your name 'OneebMalik' , upload the logos there, go back to the [iris-contrib/logo](https://github.com/iris-contrib/logo) and on the top page you will see a button says ' Pull request' press that and I will approve your pull request immediatly!! ( Do this please because I don't want to get the credits for your work:) )

**Comment by kujtimiihoxha** [comment]
@kataras How about using [this](https://github.com/digitalcraftsman/hugo-material-docs) for the docs, it looks pretty good and is easy to use.

**Comment by kataras** [comment]
Yeah, I know material-docs but they don't have auto-generated from markdown, and I really don't have time to do it myself, I'm coding the new iris release and mantain the iris-contrib packages... so If you could do that it will be very helpful

**Comment by kataras** [comment]
Yeah, I know material-docs but they don't have [auto-generated ready-to-use from markdown](http://themes.gohugo.io/theme/material-docs/adding-content/), and I really don't have time to do it myself, I'm coding the new iris release and mantain the iris-contrib packages... so If you could do that it will be very helpful

**Comment by kujtimiihoxha** [comment]
@kataras I will see what I can do and submit a pull request ;).

**Comment by kujtimiihoxha** [comment]
@kataras  I am working on it , you can see the progress [here](https://github.com/kujtimiihoxha/iris-docs)   as soon as I finish it I will build it and create the static files.

**Comment by kataras** [comment]
@kujtimiihoxha I don't know how to thanks you man, you really care about iris, more people want ready things without contribute or donate or something, you are very good, thank you!

**Comment by kujtimiihoxha** [comment]
@kataras  You have done a great thing with iris ;) props to you. Thanks for the help with the docs. I will add the missing links as soon as possible.

**Comment by kataras** [comment]
OK. Website created by @kujtimiihoxha . Visit our new site: http://iris-go.com

**Comment by kataras** [comment]
OK. 
Website created by @kujtimiihoxha . Visit our new site: http://iris-go.com .
Logo created by @OneebMalik .
