### ISSUE TITLE
Iris router auto suffix question

### ISSUE THREAD

**Issue by aveyuan** [kataras/iris#1532]
Describe the issue you are facing or ask for help
Hi,I Hope use routers will auto add ".html" suffix.
Is there such a solution? It is said that there is a configuration, but I did not find

demo

```
	app.Get("/ping", func(ctx iris.Context) {
		ctx.WriteString("pong")
	})
```
I wangt visit /ping.html ,not be /ping

**Comment by mcoo** [comment]
```golang
	app.Get(`/ping.html`,func(ctx iris.Context) {
		ctx.WriteString("pong")
	})
```

**Comment by mcoo** [comment]
```golang
	app.WrapRouter(func(w http.ResponseWriter, r *http.Request, firstNextIsTheRouter http.HandlerFunc) {
		r.URL.Path = strings.ReplaceAll(r.URL.Path,".html","")
		firstNextIsTheRouter.ServeHTTP(w, r)
		return
	})
```

**Comment by aveyuan** [comment]
> ```go
> 	app.WrapRouter(func(w http.ResponseWriter, r *http.Request, firstNextIsTheRouter http.HandlerFunc) {
> 		r.URL.Path = strings.ReplaceAll(r.URL.Path,".html","")
> 		firstNextIsTheRouter.ServeHTTP(w, r)
> 		return
> 	})
> ```

Thanks ,the function it's ok. but `ping.html` and `ping` both can be visite, i wangt just only visite `ping.html`,`/ping` can't visite . should that ok?

**Comment by mcoo** [comment]
```golang
	app.WrapRouter(func(w http.ResponseWriter, r *http.Request, firstNextIsTheRouter http.HandlerFunc) {
		m,err := regexp.MatchString(`\.html$`,r.URL.Path)
		if err != nil {
			fmt.Println(err.Error())
		}
		if m && r.Method=="GET" {
			r.URL.Path = strings.ReplaceAll(r.URL.Path,".html","")
			firstNextIsTheRouter.ServeHTTP(w, r)
		}else{
			// return some information or set some whitelist
		}
		return
	})
```

**Comment by aveyuan** [comment]
Thanks
