### ISSUE TITLE
How to make `context.ReadQuery()` ignore undefined filed

### ISSUE THREAD

**Issue by axetroy** [kataras/iris#1533]
**Is your feature request related to a problem? Please describe.**

The query in url should be variable

If the client passes in an undefined field, then `context.ReadQuery()` should not throw an error

**Describe the solution you'd like**

ignore undefined field

```go
type Query struct {
  Limit int `url: "limit"`
}

var query Query

// pass `true` for ignore undefined field
context.ReadQuery(&query, true)

// pass the path `/example?limit=10&undefined_field=123`
```

**Describe alternatives you've considered**

**Additional context**

**Comment by kataras** [comment]
Hello @axetroy,

Iris returns a special error on unknown incoming fields, you can use the `iris.IsErrPath` to ignore that error on read query/form.

Example: https://github.com/kataras/iris/blob/3fae2c31c613dca7fa355642d4db5d24e208407f/_examples/request-body/read-query/main.go#L17-L22

**Comment by kataras** [comment]
There are examples for that, but the `ReadQuery` method missed a comment documentation. I've just added it there too.

If you are OK with the solution provided above, close the issue, if not, please post an idea for an alternative solution that will not require a breaking change of the `ReadQuery` usage.

Thanks,
Gerasimos Maropoulos

**Comment by axetroy** [comment]
This is a solution for me, thanks @kataras
