### ISSUE TITLE
[BUG/Feature] MVC Dependency authentication example 

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1536]
**Describe the bug**
on the master branch "https://github.com/kataras/iris/blob/master/_examples/mvc/authenticated-controller/main.go" an authentication is used to show how it is done when you search for an authenticated user.
But how can I find an unauthenticated user who can call the same route but from a different controller?

**To Reproduce**
1. [...]

**Expected behavior**
Let's take two controllers that are both registered for the same route, but one of them has no authentication feature. Now when I call the route, I want the call without authentication to return a different value than if I were authenticated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**Additional context**
I don't think it's a bug, but a feature request, although I think others do as well, that the same route should call a different controller under different circumstances.

**Comment by kataras** [comment]
Each Controller's method creates a new route, so two controllers can't share the same route with the current implementation. If I am going to change the MVC again, the v12.2.0 release will be delayed even more, I will think of it and come back to you with a solution.

**Comment by Dexus** [comment]
Thanks for the feedback. I look forward to your proposed solution.
It is sometimes bewitching that it is possible with basic functions, again in the MVC something difficult or not at all. But doing it this way will always make things a bit better.

**Comment by kataras** [comment]
Hello @Dexus, I did it without any changes. This feature is available across Iris application, not just MVC. You just `Party.SetRegisterRule(iris.RouteOverlap)`. Updated user authenticated controller [example](https://github.com/kataras/iris/blob/master/_examples/mvc/authenticated-controller/main.go) https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L27-L32

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L54-L68

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L41-L42

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L73-L77

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L102-L108

**Comment by kataras** [comment]
Hello @Dexus, I did it without any changes (however you could do it by checking the Authenticated integer value (`if == 0` then unauthenticated) on the `UserController.GetMe`). This feature is available across Iris application, not just MVC. You just `Party.SetRegisterRule(iris.RouteOverlap)`. Updated user authenticated controller [example](https://github.com/kataras/iris/blob/master/_examples/mvc/authenticated-controller/main.go). Please tell me if that suits your needs.

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L27-L32

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L54-L68

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L41-L42

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L73-L77

https://github.com/kataras/iris/blob/abd6ed4d40983ab13bdbce6dd74db7bfc38e7db8/_examples/mvc/authenticated-controller/main.go#L102-L108

**Comment by Dexus** [comment]
Hi @kataras,

thank you, it works perfectly, just as I imagined it would. That makes things a lot easier now.

**Comment by kataras** [comment]
I am glad it helped, do you think it would be easier to default this rule on mvc apps?

**Comment by Dexus** [comment]
That's a good question. I think it always depends on the use case.

If I just relate it to my work and the projects I've done in the past, it might fit quite well as a default.

Just for websites with frontend I would prefer it as default. For API Entpoints, it does not always make sense.

I think a warning with debug might be helpful there depending on the setting of the SetRegisterRule. So you know why a route was not registered, but that's just a thought that would help me, because I had the problem ;)

**Comment by kataras** [comment]
> I think a warning with debug might be helpful there depending on the setting of the SetRegisterRule. So you know why a route was not registered, but that's just a thought that would help me, because I had the problem ;)

Yes, now this new route registration rule is described in the example too. The `RouteError` rule will force the app to stop with an error on duplicate errors, the `RouteSkip` will just silent skip duplicate, the `RouteOverride` (the default one) will replace the old one with the new one and `RouteOverlap` as described in the previous comment. So, you think it's better to add `Warning` messages on `RouteSkip` and `RouteOverride`?

**Comment by Dexus** [comment]
I think that's good. It's so right for me.

**Comment by Dexus** [comment]
Hi @kataras 

while i code for the certification, i found a crazy problem

`[HTTP Server] http: panic serving 127.0.0.1:62225: reflect: Call using *controller.CustomerPrivateController as type *controller.CustomerController`

Here a bit code:

```
// BaseController desc
type BaseController struct {
	Session       *sessions.Session
	CurrentUserID Authenticated
	Ctx           iris.Context
}

// CustomerController serves the "public" Customer API.
type CustomerController struct {
	Ctx iris.Context
}

// Get desc
// Route /category/ [GET]
func (cuc *CustomerController) Get() {
	cuc.Ctx.JSON(data)
	return
}


// CustomerPrivateController serves the "public-private" Customer API.
type CustomerPrivateController struct{ BaseController }

// Get desc
// Route /category/ [GET]
func (cupc *CustomerPrivateController) Get() *models.Category {
	return new(models.Category)
}
```

Do you know what is happening here?

**Comment by kataras** [comment]
Hello @Dexus,

Thanks for the report! It should be fixed, update to the master one.

**Comment by Dexus** [comment]
@kataras 
Thank you, works now as expected.

**Comment by Dexus** [comment]
@kataras 
One question, is there a way to register dependencies global, so it would not need to repeat all the registrations for each route?

**Comment by kataras** [comment]
> @kataras
> One question, is there a way to register dependencies global, so it would not need to repeat all the registrations for each route?

Hello @Dexus,

The `mvc/Application.Register` registers the dependencies for all routes and controllers on that mvc Application. Do you mean for all MVC application instances? If so, then, yes you can:

- Each `iris.Party` has its dependencies ( parent Party's are inherited). They are used to register route handlers with dependency injection (previously named as "hero handlers") with the [Party.ConfigureContainer(... func(api *iris.APIContainer))](https://github.com/kataras/iris/blob/80384f32b25abf03b3f99329795099929b6c4f24/core/router/api_container.go#L70) 

> https://github.com/kataras/iris/tree/master/_examples/dependency-injection

- On `mvc.New/Configure` you get a new mvc Application instance for a target Party, as we already know. All dependencies from that target `iris.Party` are inherited to that mvc Application.

- So, if you do:

```go
app := iris.New()
app.ConfigureContainer(func(api *iris.APIContainer){
  api.RegisterDependency(%yourdep%)
  // [...]
})

m := mvc.New(app /* or any other iris.Party */)
m.Handle(new(myController))
// no need to m.Register the %yourdep%,
// it's inherited from the parent party (the root app in this case)

// The %yourdep% dependency is registered to that mvc Application
// and its controllers automatically as well.
m2 := mvc.New(app.Party("/user"))
m2.Handle(new(userController))

// [...]
```

**Comment by kataras** [comment]
> @kataras
> One question, is there a way to register dependencies global, so it would not need to repeat all the registrations for each route?

Hello @Dexus,

The `mvc/Application.Register` registers the dependencies for all routes and controllers on that mvc Application. Do you mean for all MVC application instances? If so, then, yes you can:

- Each `iris.Party` has its dependencies ( parent Party's are inherited). They are used to register route handlers with dependency injection (previously named as "hero handlers") with the [Party.ConfigureContainer(... func(api *iris.APIContainer))](https://github.com/kataras/iris/blob/80384f32b25abf03b3f99329795099929b6c4f24/core/router/api_container.go#L70) 

> https://github.com/kataras/iris/tree/master/_examples/dependency-injection

- On `mvc.New/Configure` you get a new mvc Application instance for a target Party, as we already know. All dependencies from that target `iris.Party` are [cloned and passed](https://github.com/kataras/iris/blob/80384f32b25abf03b3f99329795099929b6c4f24/mvc/mvc.go#L73) to that mvc Application.

- So, if you do:

```go
app := iris.New()
app.ConfigureContainer(func(api *iris.APIContainer){
  api.RegisterDependency(%yourdep%)
  // [...]
})

m := mvc.New(app /* or any other iris.Party */)
m.Handle(new(myController))
// no need to m.Register the %yourdep%,
// it's inherited from the target party (the root app in this case)

// The %yourdep% dependency is registered to that mvc Application
// and its controllers automatically as well.
m2 := mvc.New(app.Party("/user"))
m2.Handle(new(userController))

// [...]
```

**Comment by Dexus** [comment]
Thanks for the reminder. I don't know why I forgot that again, use it in a project like this.

**Comment by Dexus** [comment]
Ok, can be closed, the names need to start with a uppercase char.

```

const (
	ascending  = "ASC"
	descending = "DESC"
)

// MyLimiter sort of mysql
type MyLimiter struct {
	Offset  int    `url:"offset"`
	Limit   int    `url:"limit"`
	Order   string `url:"order"`
	OrderBy string `url:"orderBy"`
}

// GetOffset desc
func (ml *MyLimiter) GetOffset() int {
	if ml.Offset > 0 {
		return ml.Offset
	}
	return 0
}

// GetLimit desc
func (ml *MyLimiter) GetLimit() int {
	if ml.Limit > 10 && ml.Limit < 100 {
		return ml.Limit
	}
	return 25
}

// GetOrder desc
func (ml *MyLimiter) GetOrder() string {

	ml.Order = strings.TrimSpace(ml.Order)
	if len(ml.Order) >= 4 {
		if strings.HasPrefix(strings.ToUpper(ml.Order), descending) {
			return descending
		}
	}

	return ascending
}

// GetOrderBy desc
func (ml *MyLimiter) GetOrderBy(s []string) string {
	ml.OrderBy = strings.TrimSpace(ml.OrderBy)
	i := sort.SearchStrings(s, ml.OrderBy)
	if i < len(s) && s[i] == ml.OrderBy {
		return s[i]
	}
	return "id"
}
```

**Comment by kataras** [comment]
No worries @Dexus, you can also check the [database/mysql](https://github.com/kataras/iris/tree/master/_examples/database/mysql) new example for some kind of "help" as well.

 Also, I have just pushed another new cool feature: **versioned controllers**, example at: https://github.com/kataras/iris/tree/master/_examples/mvc/versioned-controller

**Comment by Dexus** [comment]
> Also, I have just pushed another new cool feature: **versioned controllers**, example at: https://github.com/kataras/iris/tree/master/_examples/mvc/versioned-controller

Thats a very cool feature!

**Comment by Dexus** [comment]
Are you sure you register the items and already upload your app to beta/alpha state?

Von meinem iPhone gesendet

**Comment by kataras** [comment]
Yes @Dexus!

I've added another example that may be helpful for you as well: https://github.com/kataras/iris/tree/master/_examples/mvc/overview

```sh
                                         +-------------------+
                                         |  Env (DEV, PROD)  |
                                         +---------+---------+
                                         |         |         |
                                         |         |         |
                                         |         |         |
                                    DEV  |         |         |  PROD
-------------------+---------------------+         |         +----------------------+-------------------
                   |                               |                                |
                   |                               |                                |
               +---+-----+        +----------------v------------------+        +----+----+
               | sqlite  |        |         NewDB(Env) DB             |        |  mysql  |
               +---+-----+        +----------------+---+--------------+        +----+----+
                   |                               |   |                            |
                   |                               |   |                            |
                   |                               |   |                            |
      +------------+-----+     +-------------------v---v-----------------+     +----+------+
      |  greeterWithLog  |     |  NewGreetService(Env, DB) GreetService  |     |  greeter  |
      -------------+-----+     +---------------------------+-------------+     +----+------+
                   |                                       |                        |
                   |                                       |                        |
                   |           +-----------------------------------------+          |
                   |           |  GreetController          |             |          |
                   |           |                           |             |          |
                   |           |  - Service GreetService <--             |          |
                   |           |                                         |          |
                   |           +-------------------+---------------------+          |
                   |                               |                                |
                   |                               |                                |
                   |                               |                                |
                   |                   +-----------+-----------+                    |
                   |                   |      HTTP Request     |                    |
                   |                   +-----------------------+                    |
                   |                   |  /greet?name=kataras  |                    |
                   |                   +-----------+-----------+                    |
                   |                               |                                |
+------------------+--------+         +------------+------------+           +-------+------------------+
|  model.Response (JSON)    |         |  Response (JSON, error) |           |  Bad Request             |
+---------------------------+         +-------------------------+           +--------------------------+
|  {                        |                                               |  mysql: not implemented  |
|    "msg": "Hello kataras" |                                               +--------------------------+
|  }                        |
+---------------------------+
```
