### ISSUE TITLE
[FEATURE REQUEST] make reuseport/reuseaddress as Listener option.

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1544]
**Is your feature request related to a problem? Please describe.**
I would like to make my app always up to date but without any losing requests. So i would like to have the option with reuseport/reuseaddress to use the already used Port and address form the currently running instance. So that I can start the updated Server and kill after it the old server.

**Describe the solution you'd like**
https://github.com/libp2p/go-reuseport

**Describe alternatives you've considered**
Own Listener but why I should make it my own? Ngnix and other Server also have this option included.

**Additional context**

**Comment by kataras** [comment]
Hello @Dexus there is already an example. ~We can't make it a **builtin** feature, Iris targets all platforms, not just unix-based.~ Did you test that package, if it works with Windows too? Because if it does then we can add it.

The Example using the **"github.com/valyala/tcplisten"** package (with ReusePort to true): https://github.com/kataras/iris/tree/master/_examples/http-server/custom-listener/unix-reuseport

**Comment by kataras** [comment]
Hello @Dexus, 

For Unix-based systems there is an example already at: https://github.com/kataras/iris/tree/master/_examples/http-server/custom-listener/unix-reuseport using the `github.com/valyala/tcplisten` package:

```go
// +build linux darwin dragonfly freebsd netbsd openbsd rumprun

package main

import (
	"github.com/valyala/tcplisten"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()

	app.Get("/", func(ctx iris.Context) {
		ctx.HTML("<b>Hello World!</b>")
	})

	listenerCfg := tcplisten.Config{
		ReusePort:   true,
		DeferAccept: true,
		FastOpen:    true,
	}

	l, err := listenerCfg.NewListener("tcp4", ":8080")
	if err != nil {
		panic(err)
	}

	app.Run(iris.Listener(l))
}
```

I didn't know about the `libp2p/go-reuseport` package, so I tested the windows syscall to create a "reuseport" on windows machines:

```go
package main

import (
	"context"
	"net"
	"syscall"
	"time"

	"github.com/kataras/iris/v12"

	"golang.org/x/sys/windows"
)

func main() {
	app := iris.New()
	startup := time.Now()

	app.Get("/", func(ctx iris.Context) {
		s := startup.Format(ctx.Application().ConfigurationReadOnly().GetTimeFormat())
		ctx.Writef("this server started at: %s\n", s)
	})

	app.Get("/path", func(ctx iris.Context) {
		ctx.Writef("path: %s\n", ctx.Path())
	})

	ln, err := ReusePort("tcp4", ":8080")
	if err != nil {
		panic(err)
	}

	app.Run(iris.Listener(ln))
}

func control(network, address string, c syscall.RawConn) (err error) {
	return c.Control(func(fd uintptr) {
		err = windows.SetsockoptInt(windows.Handle(fd), windows.SOL_SOCKET, windows.SO_REUSEADDR, 1)
	})
}

func ReusePort(network, addr string) (net.Listener, error) {
	cfg := net.ListenConfig{
		Control: control,
	}
	return cfg.Listen(context.Background(), network, addr)
}
```

The windows behavior is: you can start as many servers as you want pointing to the same port however, all requests will listen the first server started, if the first server is terminated, then the requests will listen the second server one (try to change the http responses to test it) and so on..

**Comment by kataras** [comment]
Hello @Dexus, 

For Unix-based systems there is an example already at: https://github.com/kataras/iris/tree/master/_examples/http-server/custom-listener/unix-reuseport using the `github.com/valyala/tcplisten` package:

```go
// +build linux darwin dragonfly freebsd netbsd openbsd rumprun

package main

import (
	"github.com/valyala/tcplisten"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()

	app.Get("/", func(ctx iris.Context) {
		ctx.HTML("<b>Hello World!</b>")
	})

	listenerCfg := tcplisten.Config{
		ReusePort:   true,
		DeferAccept: true,
		FastOpen:    true,
	}

	l, err := listenerCfg.NewListener("tcp4", ":8080")
	if err != nil {
		panic(err)
	}

	app.Run(iris.Listener(l))
}
```

I didn't know about the `libp2p/go-reuseport` package, so I tested the windows syscall to create a "reuseport" on windows machines:

```go
package main

import (
	"context"
	"net"
	"syscall"
	"time"

	"github.com/kataras/iris/v12"

	"golang.org/x/sys/windows"
)

func main() {
	app := iris.New()
	startup := time.Now()

	app.Get("/", func(ctx iris.Context) {
		s := startup.Format(ctx.Application().ConfigurationReadOnly().GetTimeFormat())
		ctx.Writef("this server started at: %s\n", s)
	})

	app.Get("/path", func(ctx iris.Context) {
		ctx.Writef("path: %s\n", ctx.Path())
	})

	ln, err := ReusePort("tcp4", ":8080")
	if err != nil {
		panic(err)
	}

	app.Run(iris.Listener(ln))
}

func control(network, address string, c syscall.RawConn) (err error) {
	return c.Control(func(fd uintptr) {
		err = windows.SetsockoptInt(windows.Handle(fd), windows.SOL_SOCKET, windows.SO_REUSEADDR, 1)
	})
}

func ReusePort(network, addr string) (net.Listener, error) {
	cfg := net.ListenConfig{
		Control: control,
	}
	return cfg.Listen(context.Background(), network, addr)
}
```

The windows behavior is: you can start as many servers as you want pointing to the same port however, all requests communicate with the first server started only, if the first server is terminated, then the requests will be fired to the second server one (try to change the http responses to test it) and so on..

**Comment by Dexus** [comment]
I know the example, but it would be nicer if you just used the module, because it runs on all systems, and if you are familiar with the ReUse theme, you know the pitfalls that arise. But it would make it easier if you had the box ready to use. Without the detour to do it yourself.

But it's up to you whether you consider it integrable.

**Comment by Dexus** [comment]
And nobody should expect it to be a "loadbalancer" if you use the same port multiple times...

**Comment by kataras** [comment]
OK, I agree. I must go to a meeting now. Will take a closer look in order to add a feature like this for all supported platforms easy.

**Comment by kataras** [comment]
Hello @Dexus, there is a `iris.WithSocketSharding` option now. Works with all registered servers (.Addr/.Listen, .TLS, .AutoTLS, .NewHost, .Server) Example:

https://github.com/kataras/iris/blob/09fd38c38d7f9e7105e5fee2bfb9532d5404fd9d/_examples/http-server/socket-sharding/main.go#L20

**Comment by kataras** [comment]
Hello @Dexus, there is a `iris.WithSocketSharding` Configurator and `Configuration.SocketSharding bool` setting now. Works with all registered servers (.Addr/.Listen, .TLS, .AutoTLS, .NewHost, .Server) Example:

https://github.com/kataras/iris/blob/09fd38c38d7f9e7105e5fee2bfb9532d5404fd9d/_examples/http-server/socket-sharding/main.go#L20

**Comment by Dexus** [comment]
Thank you very much, that will help us to kick out old server without lost requests now.
