### ISSUE TITLE
how can i get a iris.Context copy?

### ISSUE THREAD

**Issue by sado0823** [kataras/iris#1547]
hello,  i wanna get a copy from iris.Context,  when i begin a new goroutine in my func , pass it as a param, actually i want all of the things from the original iris.Contex, like Values...  , is there a easy way help to do this in iris? thanks

```go
func TX(c iris.Context) {

        app := iris.New()
	ctx := app.ContextPool.Acquire(c.ResponseWriter(),c.Request())
	defer app.ContextPool.Release(ctx)

        originalV := c.Values().GetInt64Default("myKey",0)
        newV := ctx.Values().GetInt64Default("myKey",0)
       
}
```

i can't get the same value

**Comment by kataras** [comment]
Please read how http works with Go language before start with a web framework. Give me a full example sk I can provide you the solution. You never need to copy the context. Handlers already work inside their own goroutines.

**Comment by sado0823** [comment]
thanks , i get ur point . 
i wrote go a month ago, compare with some web framework, i choose iris finally
like this situation, what should i do?

```go
func TX(c iris.Context) {

      // do something

     // in this goroutine here , wanna use c ( iris.Context ), i cant not decide how long it will take      
     go func() {

	// do somethin else
        // ...
 
     }()
        
       
}

```

i cant not decide how long it will take, so when the func TX done , the goroutine in this func will get context cancel error

**Comment by kataras** [comment]
You cannot do that in Go, if you fire a go function inside a handler, it will be fired after the response sent to the client, so Context, http.Request or http.ResponseWriter are not usable at all. The correct way to do, if you really need a goroutine inside the handler (which is already a goroutine itself(!)) is to wait until it's finished.

```go
func TX(ctx iris.Context) {

      // do something

     // in this goroutine here , wanna use c ( iris.Context ), i cant not decide how long it will take      
     wg := sync.WaitGroup{}
     wg.Add(1)
     go func() {
        you can use ctx here.

	// do somethin else
        // ...
 
     wg.Done()
     }()
        
     wg.Wait()
}
```

Please give me more information, that's wrong way of doing that, you maybe want to see an example with async code inside your handlers, take for example the [Server-Sent Events](https://github.com/kataras/iris/blob/master/_examples/response-writer/sse/main.go) example.

**Comment by kataras** [comment]
@sado0823 If you `go get -u github.com/kataras/iris/v12@master` you have access to `c.Clone()` which will copy the current context for use outside of the request-scope. Although, you rarely really need it.

**Comment by sado0823** [comment]
thanks for your patience ! thank you very vary much !

**Comment by kataras** [comment]
You are very welcomed @sado0823 !
