### ISSUE TITLE
context.Params().Get() could not get right parameter

### ISSUE THREAD

**Issue by juan-chan** [kataras/iris#1549]
**Describe the bug**

I have two routers, one `HandleMany` with a `suffix(.html)`, another one `Get` with a `suffix(.zip)`, everything goes right when I request to `/api/*.html`, but when I request to `/api/*.zip`, I couldn't get the parameter `{name}` that I have defined! Instead, I got a `{page}`. This confused me.

**Expected behavior**

Got right parameter `{name}` when I request to the second router

**Screenshots**

![image](https://user-images.githubusercontent.com/49066821/86321654-01bee900-bc6c-11ea-8659-51e66fc591f2.png)

**Desktop**

 - OS: Ubuntu 18.04.4.LTS

**Other**

- Iris version: v12.1.8

**Comment by kataras** [comment]
@juan-chan this is already fixed on master branch. Execute the following:

```go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	app.HandleMany(iris.MethodGet, "/ /api/{page:string suffix(.html)}", handler1)
	app.Get("/api/{name:string suffix(.zip)}", handler2)

	app.Listen(":8080")
}

func handler1(ctx iris.Context) {
	ctx.Writef("from handler1: %#+v", ctx.Params().Store)
}

func handler2(ctx iris.Context) {
	ctx.Writef("from handler2: %#+v", ctx.Params().Store)
}
```

**Output handler1**

![image](https://user-images.githubusercontent.com/22900943/86392989-05bb2d00-bca5-11ea-9e49-ce24a9fc8797.png)


**Output handler2**

![image](https://user-images.githubusercontent.com/22900943/86393037-19669380-bca5-11ea-86ba-811d4b5d50ef.png)

**Comment by juan-chan** [comment]
@kataras Wow brilliant!

**Comment by kataras** [comment]
Thanks @juan-chan !!
