### ISSUE TITLE
[FEATURE REQUEST] Implement Iris with Bugsnag

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#1550]
**Is your feature request related to a problem? Please describe.**
I am trying to implement this error reporting tool called **Bugsnag** as middleware with Iris.

On there page they have many [examples](https://docs.bugsnag.com/platforms/go/) with different GO frameworks, but not with Iris.

This is what I've tried so far:
```go
package middleware

import (
	"context"

	"github.com/bugsnag/bugsnag-go"
	"github.com/bugsnag/bugsnag-go/device"
	"github.com/kataras/iris"
)

const FrameworkName string = "Iris"

func AutoNotify(rawData ...interface{}) iris.Handler {

	for _, datum := range rawData {
		if c, ok := datum.(bugsnag.Configuration); ok {
			bugsnag.Configure(c)
		}
	}

	device.AddVersion(FrameworkName, iris.Version)
	state := bugsnag.HandledState{
		SeverityReason:   bugsnag.SeverityReasonUnhandledMiddlewareError,
		OriginalSeverity: bugsnag.SeverityError,
		Unhandled:        true,
		Framework:        FrameworkName,
	}
	rawData = append(rawData, state)
	return func(c iris.Context) {
		r := c.Request().Clone(context.Background())
		notifier := bugsnag.New(append(rawData, r)...)
		ctx := bugsnag.AttachRequestData(r.Context(), r)
		if notifier.Config.IsAutoCaptureSessions() {
			ctx = bugsnag.StartSession(ctx)
		}

		// in the past I could have done this, but now this methos id gone
		c.ResetRequest(r.WithContext(ctx))

		notifier.FlushSessionsOnRepanic(false)
		defer notifier.AutoNotify(ctx)
		c.Next()
	}
}
```
But `ResetRequest(r *http.Request)` method doesn't exists anymore to set the context's request.

Any thoughts?

**Comment by kataras** [comment]
Hello @speedwheel,

> But ResetRequest(r *http.Request) method doesn't exists anymore to set the context's request.

It does exist my friend on master: https://github.com/kataras/iris/blob/789f0a186e7d0e89cd22426369b61ad242d7e743/context/context.go#L177 and on v12.1.8: https://github.com/kataras/iris/blob/a1e9813c610a61aba3e803a655cefc36c6efc3b2/context/context.go#L129

Let me add this middleware to the [iris-contrib/middleware](https://github.com/iris-contrib/middleware). Please do open an issue or contact with them to add an `Iris` example too.

**Comment by speedwheel** [comment]
@kataras Wow that was fast, thanks, you are awesome!

**Comment by kataras** [comment]
Thanks @speedwheel :heart: did you manage to get it working?

**Comment by speedwheel** [comment]
@kataras Yes it worked, thanks <3
Regarding the `ResetRequest` method, my bad, I imported `"github.com/kataras/iris"` instead of `"github.com/kataras/iris"/v12`.
