### ISSUE TITLE
[FEATURE REQUEST] Update Jet to v4.0.0.

### ISSUE THREAD

**Issue by pipe01** [kataras/iris#1551]

**Comment by kataras** [comment]
Hello @pipe1, [jet](https://github.com/CloudyKit/jet) released version 4, three days ago. I am working on it!

**Comment by pipe01** [comment]
Glad to hear, thank you!

**Comment by kataras** [comment]
OK @pipe01, it's [done](https://github.com/kataras/iris/commit/657bce96d4eec0eade165261f0c0ea39d82b7a56#diff-88dc7475eedf918122374be6d7c2c151R374-R378). I pushed some fixes to cloudykit's repository as well, thank you a lot for opening this issue!

**Comment by pipe01** [comment]
Awesome, thank you too!
