### ISSUE TITLE
[BUG] use staticWeb function cause loop crycle.

### ISSUE THREAD

**Issue by andyzhou** [kataras/iris#1555]
I upgrade iris to v11.1.1 and go version v1.14.2.
I use StaticWeb function for static html service, root page and any one detail html page can be visit, but the sub dir index.html can't be visit, give me " redirected you too many times.",  all work fine before upgrade to new version.

`
this.app.StaticWeb(staticUrl, staticPath)
`
Is my usage problem or others?

**Comment by andyzhou** [comment]
I switch iris code to master branch, this bug gone.

**Comment by kataras** [comment]
Yes I know, you used a very old version, the staticweb has been removed a year ago.
