### ISSUE TITLE
dependency injection question

### ISSUE THREAD

**Issue by xiaozhuai** [kataras/iris#1558]
**Is your feature request related to a problem? Please describe.**
```
func handler(ctx *iris.Context, xxx AService){
		
}

// register xxx here
xxx := NewAService()
hero.Register(xxx)

// inject xxx here
app.Handle("GET", "/api/list", hero.Handler(handler))
```

Is there a solution to simplify `hero.Handler(handler)` ?

eg `app.HeroHandle("GET", "/api/list", handler)`

**Comment by kataras** [comment]
Yes @xiaozhuai,

```go
app.ConfigureContainer(designAPI)

func designAPI(api *iris.APIContainer) {
    xxx := NewAService()
    api.RegisterDependency(xxx)

    api.Get("/api/list", handler)
}

func handler(ctx iris.Context, xxx AService) {

}
```

Read more at: https://github.com/kataras/iris/blob/master/HISTORY.md#next

**Comment by xiaozhuai** [comment]
@kataras Awesome! That's what I need!

**Comment by kataras** [comment]
That's good @xiaozhuai, you can use all things you see in the Next history section by `go get github.com/kataras/iris/v12@master` on your current project's directory.
