### ISSUE TITLE
Suggest support react server render in 3.0 release.

### ISSUE THREAD

**Issue by alanyang** [kataras/iris#156]
[Go react](https://github.com/toscale/go-react-example)

react is so popular，suggest add server render to iris. If add this, it should be the first native support react server render the go web framework, it will be very beneficial to the promotion of.

Instead I would think that jade is not very necessary support

**Comment by kataras** [comment]
Hello @alanyang ,
The project you linked to is deprecated.

Iris has already many features that are unique compared to the rest of the (go,...) web frameworks.

Just to know: I use reactjs in production for many years, the feature you requested for is one of the best requests which I agree 100%, someday Iris will support server-side reactjs, but not yet.

This is a feature for v3.5+/4.x ( which will not take too long, you can see that I am adding new features to iris every day).

Server-side reactjs is currently supported by  nodejs and this is for a reason. Until v3 release I do not have much time to deep into this, more important things must be done.

 > Instead I would think that jade is not very necessary support

The jade support will be upgraded until the final v3, it will be more useful, I am not willing to remove it, its syntax is one of the most famous.

**Comment by CasperHK** [comment]
I suggest making an **iris-react-starter-kit** before implemented the native react server-side render. This will help me pick it up quickly.

**Comment by sebastianmacias** [comment]
I suggest replacing react with [InfernoJS](https://infernojs.org/) it's modelled after react but with way better performance.
