### ISSUE TITLE
Incorrect comment ?

### ISSUE THREAD

**Issue by joewongex** [kataras/iris#1574]
The comment of the method `context.SetCookieKV` is:
> By default it expires at 2 hours and it's added to the root path,..

But in fact it expires after 1 year because it uses the variable `SetCookieKVExpiration` as the default `Expires` value, and the value of `SetCookieKVExpiration` is:

```go
var SetCookieKVExpiration = time.Duration(8760) * time.Hour  // It is 1 year 
```

**Comment by kataras** [comment]
Yes @joewongex you are right, the godoc has been updated. Thank you a lot!
