### ISSUE TITLE
Is it possible to integrate pkger for embeded resources?

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1575]
[pkger](https://github.com/markbates/pkger) is a tool for embedding static files into Go binaries. It can integrate with Gin, but I dont know how to integrate with Iris. If possible, can you give some example code?

**Comment by kataras** [comment]
Of coruse it can @tuhao1020, give me some time and I will provide you an example.

**Comment by kataras** [comment]
Of coruse it can @tuhao1020 ~give me some time and I will provide you an example.~

Actually, it's easy the `pkger.Dir` is a compatible `http.FileSyste`, with the latest Iris (master branch) you can just pass it to your `.HandleDir` method:

```go
app := iris.New()
// ...
app.HandleDir("/", pkger.Dir("./public"))
```


**However** as I can see, this library converts the files in-fly, the files should be available in your current directory. **Iris can do it using the `Cache` Option, you don't need pkger**:

```go
app.HandleDir("/", iris.Dir("./public"), iris.DirOptions{
	Cache: iris.DirCacheOptions{
		Enable:true,
	},
})
```

Indeed, Iris provides even more features here, take a look the full options of `DirCacheOptions`:
```go
type DirCacheOptions struct {
	// Enable or disable cache.
	Enable bool
	// Minimum content size for compression in bytes.
	CompressMinSize int64
	// Ignore compress files that match this pattern.
	CompressIgnore *regexp.Regexp
	// The available sever's encodings to be negotiated with the client's needs,
	// common values: gzip, br.
	Encodings []string

	// If greater than zero then prints information about cached files to the stdout.
	// If it's 1 then it prints only the total cached and after-compression reduced file sizes
	// If it's 2 then it prints it per file too.
	Verbose uint8
}
```

Thanks.

**Comment by tuhao1020** [comment]
thanks for your relpy!

the second parameter of app.HandleDir is `string`, so I  change the code as below to eliminate syntax error:
```
app := iris.New()
app.HandleDir("/", string(pkger.Dir("./public")))
app.Listen(":8080")
```
everything seems ok, but resources in `public` directory were not packed into app, when I removed the `public` directory I got a `Not Found` error page

Compare the usage of Gin with pkger:
```
router := Gin.Default()
router.StaticFs("/", pkger.Dir("/public"))
router.Run(":8080")
```
the second parameter of router.StaticFs is `http.FileSystem`

do you consider adding a method that accept a `http.FileSystem` type for `HandleDir`/`iris.HTML`/...?

**Comment by kataras** [comment]
Hello @tuhao1020, you don't use the `master` version of Iris, that's why it accepts a `string` here. Update Iris with:

```sh
$ cd your_project
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

Now, are you ready for a real comparison?

**gin**:
```go
router := Gin.Default()
router.StaticFs("/", pkger.Dir("/public"))
router.Run(":8080")
```

That's all, you cannot customize it further.

**iris**:
```go
app := iris.New()
app.HandleDir("/", pkger.Dir("/public")
app.Listen(":8080")
```

`app.HandleDir` can accept a third parameter with these options!

```go
// DirListFunc is the function signature for customizing directory and file listing.
// See `DirList` and `DirListRich` functions for its implementations.
type DirListFunc func(ctx *context.Context, dirOptions DirOptions, dirName string, dir http.File) error

// Attachments options for files to be downloaded and saved locally by the client.
// See `DirOptions`.
type Attachments struct {
	// Set to true to enable the files to be downloaded and
	// saved locally by the client, instead of serving the file.
	Enable bool
	// Options to send files with a limit of bytes sent per second.
	Limit float64
	Burst int
	// Use this function to change the sent filename.
	NameFunc func(systemName string) (attachmentName string)
}

// DirCacheOptions holds the options for the cached file system.
// See `DirOptions`structure for more.
type DirCacheOptions struct {
	// Enable or disable cache.
	Enable bool
	// Minimum content size for compression in bytes.
	CompressMinSize int64
	// Ignore compress files that match this pattern.
	CompressIgnore *regexp.Regexp
	// The available sever's encodings to be negotiated with the client's needs,
	// common values: gzip, br.
	Encodings []string

	// If greater than zero then prints information about cached files to the stdout.
	// If it's 1 then it prints only the total cached and after-compression reduced file sizes
	// If it's 2 then it prints it per file too.
	Verbose uint8
}

// DirOptions contains the settings that `FileServer` can use to serve files.
// See `DefaultDirOptions`.
type DirOptions struct {
	// Defaults to "/index.html", if request path is ending with **/*/$IndexName
	// then it redirects to **/*(/) which another handler is handling it,
	// that another handler, called index handler, is auto-registered by the framework
	// if end developer does not managed to handle it by hand.
	IndexName string
	// PushTargets filenames (map's value) to
	// be served without additional client's requests (HTTP/2 Push)
	// when a specific request path (map's key WITHOUT prefix)
	// is requested and it's not a directory (it's an `IndexFile`).
	//
	// Example:
	// 	"/": {
	// 		"favicon.ico",
	// 		"js/main.js",
	// 		"css/main.css",
	// 	}
	PushTargets map[string][]string
	// PushTargetsRegexp like `PushTargets` but accepts regexp which
	// is compared against all files under a directory (recursively).
	// The `IndexName` should be set.
	//
	// Example:
	// "/": regexp.MustCompile("((.*).js|(.*).css|(.*).ico)$")
	// See `iris.MatchCommonAssets` too.
	PushTargetsRegexp map[string]*regexp.Regexp

	// Cache to enable in-memory cache and pre-compress files.
	Cache DirCacheOptions
	// When files should served under compression.
	Compress bool

	// List the files inside the current requested directory if `IndexName` not found.
	ShowList bool
	// If `ShowList` is true then this function will be used instead
	// of the default one to show the list of files of a current requested directory(dir).
	// See `DirListRich` package-level function too.
	DirList DirListFunc

	// Files downloaded and saved locally.
	Attachments Attachments

	// Optional validator that loops through each requested resource.
	AssetValidator func(ctx *context.Context, name string) bool
}
```

Have fun :)

**Comment by kataras** [comment]
Hello @tuhao1020, you are not watching me. You don't use the `master` version of Iris, that's why it accepts a `string` here. Update and you should be able to see that we already have the second input argument as `http.FileSystem` as explained above. Here you are:

```sh
$ cd your_project
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

Now, are you ready for a real comparison?

**gin**:
```go
router := gin.New()
router.StaticFs("/", pkger.Dir("/public"))
router.Run(":8080")
```

That's all, you cannot customize it further.

**iris**:
```go
app := iris.New()
app.HandleDir("/", pkger.Dir("/public"))
app.Listen(":8080")
```

`app.HandleDir` can accept a third parameter with these options!

```go
// DirListFunc is the function signature for customizing directory and file listing.
// See `DirList` and `DirListRich` functions for its implementations.
type DirListFunc func(ctx *context.Context, dirOptions DirOptions, dirName string, dir http.File) error

// Attachments options for files to be downloaded and saved locally by the client.
// See `DirOptions`.
type Attachments struct {
	// Set to true to enable the files to be downloaded and
	// saved locally by the client, instead of serving the file.
	Enable bool
	// Options to send files with a limit of bytes sent per second.
	Limit float64
	Burst int
	// Use this function to change the sent filename.
	NameFunc func(systemName string) (attachmentName string)
}

// DirCacheOptions holds the options for the cached file system.
// See `DirOptions`structure for more.
type DirCacheOptions struct {
	// Enable or disable cache.
	Enable bool
	// Minimum content size for compression in bytes.
	CompressMinSize int64
	// Ignore compress files that match this pattern.
	CompressIgnore *regexp.Regexp
	// The available sever's encodings to be negotiated with the client's needs,
	// common values: gzip, br.
	Encodings []string

	// If greater than zero then prints information about cached files to the stdout.
	// If it's 1 then it prints only the total cached and after-compression reduced file sizes
	// If it's 2 then it prints it per file too.
	Verbose uint8
}

// DirOptions contains the settings that `FileServer` can use to serve files.
// See `DefaultDirOptions`.
type DirOptions struct {
	// Defaults to "/index.html", if request path is ending with **/*/$IndexName
	// then it redirects to **/*(/) which another handler is handling it,
	// that another handler, called index handler, is auto-registered by the framework
	// if end developer does not managed to handle it by hand.
	IndexName string
	// PushTargets filenames (map's value) to
	// be served without additional client's requests (HTTP/2 Push)
	// when a specific request path (map's key WITHOUT prefix)
	// is requested and it's not a directory (it's an `IndexFile`).
	//
	// Example:
	// 	"/": {
	// 		"favicon.ico",
	// 		"js/main.js",
	// 		"css/main.css",
	// 	}
	PushTargets map[string][]string
	// PushTargetsRegexp like `PushTargets` but accepts regexp which
	// is compared against all files under a directory (recursively).
	// The `IndexName` should be set.
	//
	// Example:
	// "/": regexp.MustCompile("((.*).js|(.*).css|(.*).ico)$")
	// See `iris.MatchCommonAssets` too.
	PushTargetsRegexp map[string]*regexp.Regexp

	// Cache to enable in-memory cache and pre-compress files.
	Cache DirCacheOptions
	// When files should served under compression.
	Compress bool

	// List the files inside the current requested directory if `IndexName` not found.
	ShowList bool
	// If `ShowList` is true then this function will be used instead
	// of the default one to show the list of files of a current requested directory(dir).
	// See `DirListRich` package-level function too.
	DirList DirListFunc

	// Files downloaded and saved locally.
	Attachments Attachments

	// Optional validator that loops through each requested resource.
	AssetValidator func(ctx *context.Context, name string) bool
}
```

Have fun :)

**Comment by tuhao1020** [comment]
I got master branch and `HandleDir` worked perfect. That's awesome!
Another question is: why `iris.HTML()` method still has a `directory` parameter with `string` type not `http.FileSystem`?
Thanks for your patience！

**Comment by kataras** [comment]
No worries @tuhao1020, I was thinking about it too but when you use templates inside bindata you usually have more data than the template files, or the bindata.go file may contain more templates that should be rendered using different parsers and engines. So, the `iris.HTML/Django/Pug/Handlebars/Amber/Jet/Ace/Blocks` all have a `string` for its directory for system files **and embedded data (using HTML("/views", ".html").Binary(Asset, AsssetNames)** because you can register more than one and they should point to a different directory **inside** the embedded file system itself. However if you think that it should be changed (by keeping the same functions for compability in the same time) let me know so I can start thinking how to support all cases.

**Comment by tuhao1020** [comment]
All my projects use [pkger](https://github.com/markbates/pkger) to package static resources, so I prefer to use a `http.FileSystem`  compatible type in `iris.HTML/Django/Pug/Handlebars/Amber/Jet/Ace/Blocks`.  Other  libraries such as [go.rice](https://github.com/GeertJohan/go.rice), [esc](https://github.com/mjibson/esc) also provides an `http.FileSystem` interface.

On the other hand, `HTML("/views", ".html").Binary(Asset, AsssetNames)` is the usage of binding with go-bindata, that's less flexibility for developers who want to use a different library.

**Comment by kataras** [comment]
Indeed you can convert anything to `Asset func(string) ([]byte, error)` and `AssetNames func() []string` but yes `http.FileSystem` can be useful on templates too, it will be ready soon. Don't forget that Iris was the first Go web framework supporting embedded data (as far as I remember) with functions like that, years ago, things are moving on and we become better.

**Comment by kataras** [comment]
Indeed you can convert anything to `Asset func(string) ([]byte, error)` and `AssetNames func() []string` (probably that's why this is the first issue about thi ssubject), but yes `http.FileSystem` can be useful on templates too - I totally agree and I was thinking of it myself - it will be ready soon. Don't forget that Iris was the first Go web framework supporting embedded data (as far as I remember) with functions like that, years ago, things are moving on and we become better.

**Comment by tuhao1020** [comment]
I got it, thank you! @kataras

**Comment by kataras** [comment]
@tuhao1020 It's done, now you can pass `http.FileSystem` on all view engines instead of string. The `.Binary` method was also removed as it's now useless. Upgrade to the latest master commit.
