### ISSUE TITLE
AutoTLS with non-80 HTTP Port?

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1577]
Hello there!

This is a purely documentation / example question:

- How can I start an AutoTLS server, where the HTTP port is 8080 and not 80?

#### Why?
Because there is NAT in front of iris that routes `internal:8080` to `external:80`

### Current Code
```go
if err := app.Run(iris.AutoTLS(":443", "my.domain.here", "me@my.domain.here")); err != nil {
  log.Error("failed to set-up HTTP server", "error", err)
}
```
---
Looking through the code some I the two ways to create a Runner that conflict here:
https://github.com/kataras/iris/blob/da029d6f37228c7c0fed685187a2bd4ef35b5b3e/iris.go#L658-L667
https://github.com/kataras/iris/blob/da029d6f37228c7c0fed685187a2bd4ef35b5b3e/iris.go#L584-L590

They are simply too abstracted for me to know what I'd be changing without a thorough deep-dive into iris code.

**Comment by kataras** [comment]
Hello @AlbinoGeek,

First of all, just for your knowedge the `app.Run/Listen` logs the incoming error already.

Now let's deep into your question, you can do it through `app.Run(iris.AutoTLS(":8080"....))` but the problem you have is the secondary `:http` server which redirects to the `:https` one. There is a Host option called `iris.NoTLSRedirect` which disables that default behavior e.g. `app.Run(iris.AutoTLS(":8080", "...", "...", iris.TLSNoRedirect)).`

After that, you have **two options to handle the http to https redirection**:

1. can register your own server to do redirections, Iris contains a helper for that [example](https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/_examples/http-listening/listen-tls/main.go#L22-L25):

```go
import "github.com/kataras/iris/v12/core/host" // import that package.

 // to start a new server listening at :8080 and redirects 
 // to the secure address, then: 
 target, _ := url.Parse("https://127.0.0.1:8080") 
 go host.NewRedirection("127.0.0.1:8080", target, iris.StatusMovedPermanently).ListenAndServe()

app := iris.New()
// ...
app.AutoTLS(...., iris.TLSNoRedirect)
```
2. Using a **middleware** OR using a handler that **wraps the router**, in your main server.
2.1 middleware:
```go
func redirectToHTTPS(ctx iris.Context) {
  if !ctx.Request().TLS != nil  /* or ctx.Request().ProtoMajor != 2 */  {
    ctx.Redirect(strings.Replace(ctx.FullRequestURI(),"http","https",1), iris.StatusMovedPermanently)
    return
  }

  ctx.Next()
}

app.Use(redirectToHTTPS)
```
2.2 wrapper:
```go
app.WrapRouter(func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc){
   // checks here, if it's not https then redirect and return otherwise run the router with router(w,r )
})
```

You can always modify hosts through `app.ConfigureHost(func(su *iris.Supervisor){ /* .... */ ))`.

Please tell me if that helped you.

**Comment by AlbinoGeek** [comment]
@kataras In these examples it is unclear which is the HTTP port and which is the HTTPS port, as you only use one port within each of the examples. It is my understanding that they cannot be on the same port, but perhaps this is old knowledge.

**Comment by kataras** [comment]
@AlbinoGeek yes sorry, it was a copy-paste from an iris example, just change the port you are using for the HTTP server, here is the one:
```go
target, _ := url.Parse("https://127.0.0.1:8080") // PORT FOR HTTPS
go host.NewRedirection("127.0.0.1:OTHERPORT_FOR_HTTP", target, iris.StatusMovedPermanently).ListenAndServe()
```

**Comment by AlbinoGeek** [comment]
@kataras I cannot use `iris.TLSNoRedirect` in the context of `app.Run` because:
```
./main.go:191:22: cannot use iris.TLSNoRedirect (type func(*host.Supervisor)) as type iris.Configurator in argument to app.Run
```

**Comment by kataras** [comment]
@AlbinoGeek That's why I am asking the Iris version, you don't use the `master` one. 

Please always try replicate your issue using the `master` branch because an "x" bug may be fixed months ago:

```sh
$ cd your_project
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Comment by AlbinoGeek** [comment]
It is worth noting that `AutoTLS` internally binds to port 80, causing this issue:

```
	target, _ := url.Parse("https://127.0.0.1:8443")
	go host.NewRedirection("127.0.0.1:8080", target, iris.StatusMovedPermanently).ListenAndServe()

	app.Run(iris.AutoTLS(":8443", "my.domain.here", "me@my.domain.here"), iris.WithSocketSharding)
```

results in:
```
listen tcp :80: bind: permission denied
```

All of this was tested with what was master, as of:
`github.com/kataras/iris/v12@v12.1.9-0.20200809192844-da029d6f3722`

After updating to master again, the results are still reproducable.

**Comment by kataras** [comment]
OK that's a good start, let me see what's wrong here, will get back to you soon!

**Comment by AlbinoGeek** [comment]
And for sanity sake, to exclude the NAT from the issue, the following code works:
```go
var (
  plainHost    = pflag.String("host", "0.0.0.0", "HTTP Hostname")
  plainPort    = pflag.Int("port", 8080, "HTTP Port")
)

func main() {
  pflag.Parse()
  
  app := iris.Default()
  app.Use(requestid.New())
  app.Use(iris.Compression)
  
  app.Get("/health", func(c iris.Context) {
    c.JSON(map[string]interface{}{
      "time":      time.Now().Unix(),
    })
  })
  
  app.Logger().SetLevel("debug")
  app.Run(iris.Addr(fmt.Sprintf("%s:%d", *plainHost, *plainPort)))
}
```

Means the site can be reached at `127.0.0.1:8080` and `external:80` successfully.

**Comment by kataras** [comment]
@AlbinoGeek, did you try using letsencrypt with raw `net/http` and you succeed with your current configuration? Because the `iris.AutoTLS` just uses the acme/autocert package to provide letsencrypt.

The only code you should check:
https://github.com/kataras/iris/blob/da029d6f37228c7c0fed685187a2bd4ef35b5b3e/core/host/supervisor.go#L342-L349

And autocert.Manager: https://github.com/golang/crypto/blob/123391ffb6de907695e1066dc40c1ff09322aeb6/acme/autocert/autocert.go#L368-L383

**Comment by AlbinoGeek** [comment]
Totally fair, this makes it an upstream bug (for acme/autocert) -- because my particular setup requires a non-80 HTTP port, due to NAT. [And hey, the exhaustion of IPv4 addresses seems like reason enough to support this.]

**Comment by kataras** [comment]
@AlbinoGeek sorry for confusion, all that happens because `iris.TLSNoRedirect` is not an Iris configurator but a host one and it **SHOULD be passed to the AutoTLS function, not the Run method**:

The correct: 	`app.Run(iris.AutoTLS(":8443", "example.com", "example@example.com"), iris.TLSNoRedirect)` please test.

**Comment by kataras** [comment]
@AlbinoGeek sorry for confusion, all that happens because `iris.TLSNoRedirect` is not an  `iris.Configurator` but a `host.Configurator` one and it **SHOULD be passed to the AutoTLS function, not the Run method**.

The correct: 	`app.Run(iris.AutoTLS(":8443", "example.com", "example@example.com", iris.TLSNoRedirect))` please test.

Example file: https://github.com/kataras/iris/blob/c4843a4d82aae53518bb7c247923007d1d99893c/_examples/http-server/listen-letsencrypt/main.go#L28-L31

**Comment by AlbinoGeek** [comment]
The following code:
```golang
target, _ := url.Parse("https://my.domain/")
go host.NewRedirection("0.0.0.0:8080", target, iris.StatusMovedPermanently).ListenAndServe()
app.Run(iris.AutoTLS("0.0.0.0:8443", "my.domain", "me@my.domain", iris.TLSNoRedirect), iris.WithSocketSharding)
```

Results in:
```
...
Now listening on: http://localhost:8443
Application started. Press CTRL+C to shut down.

[HTTP Server] http: TLS handshake error from 192.168.0.1:57048: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/REDACTED" for domain "my.domain": no viable challenge type found
[HTTP Server] http: TLS handshake error from 34.209.232.166:53742: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 192.168.0.1:57050: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 64.78.149.164:44484: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 192.168.0.1:57054: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 52.28.236.88:11904: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 192.168.0.1:57060: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 192.168.0.1:57056: acme/autocert: missing certificate
[HTTP Server] http: TLS handshake error from 192.168.0.1:57058: acme/autocert: missing certificate
```

That's a partial fix at least, the redirect "worked", but ACME failed.

Also worth noting, I can't create a bug upstream because `golang/crypto` doesn't have issues.

**Comment by kataras** [comment]
@AlbinoGeek That's a letsencrypt issue and wouldn't work on raw `net/http` too. It tells you that `for domain "my.domain": no viable challenge type found`.

> By the way, this above code didn't bind on port :80
Yes, it didn't bind to :80 because you passed the `iris.TLSNoRedirect` correctly this time :D

**Comment by kataras** [comment]
OK now we solve that this is not an Iris problem and I can rest in peace, let's see how we can help you on that, do you prefer continueing that through a private room on our [chat](https://chat.iris-go.com)?

**Comment by AlbinoGeek** [comment]
Effectively that "solves" the original post ask, but still `no viable challenge type found` does not make a usable LetsEncrypt implementation. What causes this / what do I do about it?

I know LetsEncrypt supports my domain/computer because nginx and certbot works, but AutoTLS does not.

And yes, I'll sign on to the chat.

**Comment by kataras** [comment]
Yes I had some issues with letsencrypt too, had to pass a real domain that directly binds to my remote computer, if you have a test domain we can run it together and see that it's working without erorrs.

**Comment by AlbinoGeek** [comment]
I'm on chat. I've been trying to do this using real domains, just don't want them showing up here (SEO and such, an unreleased product, etc.) And yes, I have some other domains we can test with as well.

**Comment by kataras** [comment]
That's fine, I know that I was being there. That's why I asked for a private room :) I am in.

**Comment by AlbinoGeek** [comment]
For those that might find this issue later, here is the current solution:

```golang
// Use your externally accessible HTTPS port here
target, _ := url.Parse("https://my.domain/")

// Use your internally accessible HTTP port here
go host.NewRedirection("0.0.0.0:8080", target, iris.StatusMovedPermanently).ListenAndServe()

// Use your internally accessible HTTPS port here
app.Run(iris.AutoTLS("0.0.0.0:8443", "my.domain", "me@my.domain", iris.TLSNoRedirect))

// Note however, because of golang/crypto's implementation of certmanager,
// it is NOT currently possible to change the external port 80.
```
