### ISSUE TITLE
[FEATURE REQUEST] add handlers to app.HandleDir

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1581]
I can't attached basicauth, cache or any other handlers to an `app.HandleDir`
```golang
authentication = basicauth.New(basicauth.Config{
  Users: map[string]string{
    "Foo": "Bar",
  },
  Realm:   "Authorization Required",
  Expires: time.Duration(30) * time.Minute,
})

app.Get("/", authentication, cache.Handler(time.Minute), func(ctx iris.Context) {
  ctx.HTML("Hello, World!")
})

// But no way to attach either here?
app.HandleDir("/assets", iris.Dir("./public"), iris.DirOptions{/*...*/})
```

**Why do I want to?**
Well, basicauth primarily.

**Comment by kataras** [comment]
@AlbinoGeek No need to add something here extra, there are already exist two ways you can do that:

**1.** Use the `DirOptions.AssetValidator` + the `ctx.Proceed(handler) bool)`
https://github.com/kataras/iris/blob/ff5e43f341cce0cf79be9e68edcb58a1c13efda4/core/router/fs.go#L108

```go
assetValidator := func(ctx *context.Context, name string) bool {
    return ctx.Proceed(authentication(ctx))
}
```

**2.** Use a Party to host the `HandleDir` + `Party.Use`:

```go
assets := app.Party("/assets")
assets.Use(authentication)
assets.HandleDir("/", iris.Dir("./public"))

```

**Comment by AlbinoGeek** [comment]
## Code Sample 1
```golang
		AssetValidator: func(ctx iris.Context, name string) bool {
			return ctx.Proceed(authentication(ctx))
		},
```

Results in the error:
```golang
authentication(ctx) used as value
```

And while the following meets the expected signature, it results in 404s for all resources:
```golang
		AssetValidator: func(ctx iris.Context, name string) bool {
			return ctx.Proceed(authentication)
		},
```

Yes, #2 would work.

**Comment by kataras** [comment]
Yes @AlbinoGeek. Yes `ctx.Proceed(authentication)` is the correct (my comment edited), as it accepts a Handler. It results on 404? that's a problem, let me find out.

**Comment by kataras** [comment]
I found the issue. Proceed reports true if the given handler executed `ctx.Next`, and it founds out using the before and after HandlerIndex of the request. Because we don't have a next handler, it returns false. The basicauth middleware reports if the middleware must stop using `ctx.StopXXX` methods, we can just check `ctx.IsStopped` instead but other middlewares may not report that, let me find a solution and get back with a fix.

**Comment by kataras** [comment]
That's fixed also @AlbinoGeek :)

**Comment by AlbinoGeek** [comment]
Wonderful!

It just turns out Chrome doesn't send credentials along a HTTP/2 Push resource request, nor when accessing the `site.webmanifest` file... great... (401s all around.)

That being said, it's not iris fault, and this ill behaviour isn't seen with regular files (media).

Thank you for your vigilant updates!
