### ISSUE TITLE
You have installed an invalid version. 

### ISSUE THREAD

**Issue by mywalter2020** [kataras/iris#1582]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://pkg.go.dev/github.com/kataras/iris/v12@v12.2.0>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
Hello @mywalter2020, the message tells you that you have to use Iris with the `/v12` import path suffix, as of go1.11 Iris is a go module.

```sh
$ cd your_project
$ go mod init app
$ go get -u github.com/kataras/iris/v12@master # or @latest or @v12.1.8
```

```go
import "github.com/kataras/iris/v12"
```

**Comment by FlyingOnion** [comment]
Hi, we have met the same problem, and we are using a lower version. Is it possible to solve this problem without changing to the latest version?
