### ISSUE TITLE
[BUG] `DirList` alias missing from the main package

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1583]
## Summary
https://github.com/kataras/iris/blob/6fee09f11ed192aa31b46432eaeb722f06d15952/core/router/fs.go#L495

While looking for alternatives to `DirListRich` I found this `DirList`, but it has a different signature entirely.

### Code Attempted
Attempting to use the following code fails, even though in theory it should not:
```golang
	app.HandleDir("/assets", iris.Dir("./public"), iris.DirOptions{
		IndexName: "/index.html",
		Compress:  true,
		ShowList:  false,
		Cache: iris.DirCacheOptions{
			Enable:          true,
			CompressIgnore:  iris.MatchImagesAssets,
			CompressMinSize: 300,
			Encodings:       []string{"gzip" /*"br", "deflate", "snappy"*/},
		},
		DirList: iris.DirList, // iris.DirListRich() // note the signature change
	})
```

### Result
```
./main.go:2874:12: undefined: iris.DirList
```

I've even tried wrapping it to match the signature, but that won't solve a `undefined` error...

```golang
		DirList: iris.DirListFunc(iris.DirList),
```

## Expected Behaviour
That there would be some `DirListBasic`, `DirListPlain` or `DirList` type as alternative to `DirListRich`

## Versions, etc

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

**Comment by kataras** [comment]
@AlbinoGeek The `DirList` alias is missing from the `iris` package (it exists on its /core/router) but I didn't put it there in the first place because it's the default value. It is compatible with `DirListFunc`, just pushed a commit to add this to aliases.

**Comment by AlbinoGeek** [comment]
Worth noting, there is a syntax disparity now:

`DirListRich()` vs `DirList` (without the `()`)

**Comment by kataras** [comment]
No, the `DirList` is a `DirListFunc` the `DirListRich` **returns** a `DirListRich`, this is always the case. Because `DirListRich` optionally accepts `DirListRichOptions`, so it's `DirList DirListFunc` and `DirListRich(opts DirListRichOptions) DirListFunc`.

**Comment by kataras** [comment]
@AlbinoGeek. No, the `DirList` is a `DirListFunc` the `DirListRich` **returns** a `DirList`, that always the case. Because `DirListRich` optionally accepts `DirListRichOptions`, so it's `DirList DirListFunc` and `DirListRich(opts DirListRichOptions) DirListFunc`.

**Comment by kataras** [comment]
@AlbinoGeek. No, the `DirList` is a `DirListFunc` the `DirListRich` **returns** a `DirListFunc`. Because `DirListRich` optionally accepts `DirListRichOptions`, so it's `DirList DirListFunc` and `DirListRich func(opts DirListRichOptions) DirListFunc`.

**Comment by AlbinoGeek** [comment]
Ahh, so this is intentional because of the options, I see. Thank you for explaining that. My point was basically that if it were to be considered an API, the usage would be inconsistent -- but I now see why, and how it wouldn't make sense to wrap it to match considering it wouldn't take the same options.

**Comment by kataras** [comment]
Exactly @AlbinoGeek, the [new docs](https://docs.iris-go.com/iris/file-server/listing) (not yet finished) explains that too.
