### ISSUE TITLE
[BUG] Logger is not thread-safe?

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1585]
## Summary
Loading resources in parallel (such as with HTTP/2 push, or `<meta rel="preload" ...>` tags causes interspersed log lines.

## Reproduction
1. Load up Chrome (latest) on linux/amd64
2. Open devtools to Network tab, check "Disable Cache"
3. Sample could should trigger this after only a few tries

## Expected Behaviour
Honestly, I'm torn. I wouldn't want logging to slow down a production application, however, in `debug` mode, I would expect the logs order to be exact, as they are often used to diagnose the request flow. Logs not being thread-safe would make debugging a request flow issue difficult.

## Screenshot
![image](https://user-images.githubusercontent.com/1910461/90234313-552c6700-ddd4-11ea-9089-26c0ffdf4ba5.png)

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master 5f23599|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code
```golang
func main() {
	app := iris.Default()
	app.Logger().SetLevel("debug")
	app.Favicon("./public/favicons/favicon.ico")

	assets := app.Party("/assets")
	assets.HandleDir("/", iris.Dir("./public"), iris.DirOptions{
		IndexName: "/index.html",
		Compress:  true,
		ShowList:  false,
		Cache: iris.DirCacheOptions{
			Enable:          true,
			CompressIgnore:  iris.MatchImagesAssets,
			CompressMinSize: 1,
			Encodings:       []string{"gzip", "br", "deflate", "snappy"},
		},
		DirList: iris.DirList,
	})

	pages := app.Party("/")
	pages.Use(iris.Compression)
	pages.Get("/", func (ctx iris.Context) {
		ctx.HTML(`
<!DOCTYPE html>
<link rel="stylesheet" href="/assets/core.css">
<link rel="preload" href="/assets/fonts/open-sans-v17-latin-300.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/open-sans-v17-latin-600.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/open-sans-v17-latin-regular.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/open-sans-v17-latin-700.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/open-sans-v17-latin-800.woff2" as="font" type="font/woff2" crossorigin>
<p>Hello, World!`)
	})
	
	app.Serve(":8080")
}
```

### Web Fonts Used

https://google-webfonts-helper.herokuapp.com/fonts/open-sans?subsets=latin

**Comment by kataras** [comment]
Lol just fixed that on `kataras/golog`, and pushed a commit here @AlbinoGeek
