### ISSUE TITLE
[BUG] Increased Time To First Byte with HTTP/2 Push

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1586]
## Summary

The TTFB for the average HTML request in my test project is nearly 10x the length of the rest of the request breakdown.

## Reproduction

1. Serve a rendered HTML page using `cache.Handler(time.Minute)`
2. Watch your TTFB skyrocket to 3-10x higher than without cache

## Screenshot

![image](https://user-images.githubusercontent.com/1910461/90237532-45635180-ddd9-11ea-8ee9-abaea3e8b311.png)

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master 558d6d4|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code

This one was a lot harder to decouple from my program so, I apologize about the messy example.

### `main.go`

```golang
var (
	domain             = pflag.String("domain", "example.com", "Canonical domain for URL generation")
	templatesDir       = pflag.String("templates-dir", "templates", "Relative path to templates")

	staticPageCacheTime = time.Minute

	supportedLanguages = []string{"en-ca", "en-gb", "en-us"}
)

// demonstration purposes
var baseTitle = "Example Website"
var devMode = false

func mountStatic(routeFN func(string, ...iris.Handler) *router.Route, langCode, path, tmplName string) {
	routeFN(path, cache.Handler(staticPageCacheTime), func(ctx iris.Context) {
		ctx.ViewData("canon", fmt.Sprintf("%s/%s%s", *domain, langCode, path))
		ctx.ViewData("domain", *domain)
		ctx.ViewData("langCode", langCode)
		ctx.ViewData("pageURL", fmt.Sprintf("/%s%s", langCode, path))
		ctx.ViewData("title", baseTitle)
		if err := ctx.View(tmplName); err != nil {
			ctx.StatusCode(iris.StatusInternalServerError)
			ctx.Writef(err.Error())
		}
	})
}

func main() {
	app := iris.Default()
	app.Use(requestid.New())

	pages := app.Party("/")
	pages.Use(iris.Compression)

	tmpl := iris.HTML("./templates", ".tmpl")
	tmpl.Layout("layouts/base.tmpl")
	pages.RegisterView(tmpl.Reload(devMode))

	for _, langCode := range supportedLanguages {
		lang := pages.Party(fmt.Sprintf("/%s", langCode))
		{
			mountStatic(lang.Get, langCode, "/", "index.tmpl")
		}
	}

	app.Serve(":80")
}
```

### `templates/layouts/base.tmpl`

```html
<!DOCTYPE html>
<html lang="{{ .langCode }}">
<meta charset="utf-8">
<title>{{ .title }}</title>

<link rel="canonical" href="https://{{ .canon }}">
<link rel="shortlink" href="https://{{ .canon }}">

{{ yield }}
```

### `templates/index.tmpl`

```html
<h1>{{ .title }}</h1>
<p>This is a loading speed test. Please consult your browser's devtools implementation for details.</p>
<pre>   canon = {{ .canon }}
  domain = {{ .domain }}
langCode = {{ .langCode }}
 pageURL = {{ .pageURL }}</pre>
```

**Comment by kataras** [comment]
@AlbinoGeek Can you share a repository for that too? It would help me a lot

**Comment by AlbinoGeek** [comment]
While that would be a wonderful addition for people using Angular and other SPA purposes, I am not one of those people. It would not particularly benefit the above case, where the issue appears to be sometime in template rendering (but I'm not sure. I need to add more timing logs to check for this.)

Okay, after further investigation, it turns out the issue is specific to **HTTP/2 Push**. Even if I finish sending HTML before sending the Push resources, it's completely stalled (showing as TTFB) until all the Push resources have completed going over the wire.

So, interestingly enough, as Push is currently implemented (either due to Google Chrome's client impl. or iris server impl.), it's **currently slower than serving the resources with** `<meta rel="preload" ...>`. I have to chock this up to either the Push impl. or Google Chrome's, since the issue is almost gone when I comment out all the push code.

I say **almost** because the TTFB is still 2+ms (which seems excessive for HTML that's being served directly out of RAM if that's how `cache.Handler` is implemented?)

## Screenshots With Push
### HTML Breakdown:
![image](https://user-images.githubusercontent.com/1910461/90240914-f6b8b600-ddde-11ea-992a-577e405a94ad.png)
### Full Waterfall:
( Blue line on the bottom right hand side is 58.142ms )
![image](https://user-images.githubusercontent.com/1910461/90240967-0a641c80-dddf-11ea-9289-c63dbc819445.png)

## Screenshots Without Push
### HTML Breakdown:
![image](https://user-images.githubusercontent.com/1910461/90240622-72fec980-ddde-11ea-96dc-30764c4604dd.png)
### Full Waterfall:
( Blue line on the bottom right hand side is 45.016ms )
![image](https://user-images.githubusercontent.com/1910461/90240708-a2add180-ddde-11ea-8156-c236b7e5afeb.png)

---

I can try and make a repository with the push issue if you'd like, and I'm renaming this issue, as I've now found it's specific to Push and not just cache in general as I thought originally.

**Comment by AlbinoGeek** [comment]
Yeah... there's something really fishy with this HTTP/2 Push thing...
![image](https://user-images.githubusercontent.com/1910461/90241474-f8cf4480-dddf-11ea-8d11-163bc39d628b.png)

**Comment by AlbinoGeek** [comment]
Well, since I won't be using HTTP/2 Push anymore (since you can't push assets crossing a subdomain even with CORS implemented server-side, and the same authority across them all (... Chrome... why you go against your documentation?)) -- I won't be able to diagnose this issue anymore, so I'll close it off.

**Comment by kataras** [comment]
I have bookmarked this issue @AlbinoGeek, it's not really a high-priority but will take look of it when I finish fixing some other issues you've opened, that are more important and affects more people.
