### ISSUE TITLE
[BUG] Layout not rendered for Subdomain `OnErrorCode`

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1588]
## Summary
If you have a `Layout` defined, but put an `OnErrorCode` on a `Party` or `Subdomain`, you get ONLY the view rendered, without any `Layout` respected. Whereas if the `Layout` is defined on the `app`, a `Layout` is rendered as expected.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master d0d7679|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code

```golang
func main() {
// ...
	your := app.Subdomain("your")

	tmpl := iris.HTML("./templates", ".html")
	tmpl.Layout("layouts/base.html")
	your.RegisterView(tmpl.Reload(true)) // <-- does not render, because Layout is registered on a Subdomain
	your.OnErrorCode(iris.StatusNotFound, error404handler1)

	pages := your.Party("/")
	tmpl2 := iris.HTML("./templates", ".html")
	tmpl2.Layout("layouts/base2.html")
	pages.RegisterView(tmpl.Reload(true)) // <-- does not render, because Layout is registered on a Party
	pages.OnErrorCode(iris.StatusNotFound, error404handler2)
// ...
}

func error404handler1(ctx iris.Context) {
	ctx.ViewData("title", fmt.Sprintf("%s - Not Found", *baseTitle))
	ctx.StatusCode(iris.StatusNotFound)
	if err := ctx.View("404.html"); err != nil {
		ctx.StatusCode(iris.StatusInternalServerError)
		ctx.Writef(err.Error())
	}
}

func error404handler2(ctx iris.Context) {
	ctx.ViewData("title", fmt.Sprintf("%s - Not Found", *baseTitle))
	ctx.StatusCode(iris.StatusNotFound)
	if err := ctx.View("404.html"); err != nil {
		ctx.StatusCode(iris.StatusInternalServerError)
		ctx.Writef(err.Error())
	}
}
```

**Comment by kataras** [comment]
Hello @AlbinoGeek, yes you get a `view engine is missing, use 'RegisterView'` error because when an error is not fired by the end-developer but by router, like 404, the middlewares are not running to error handlers (e.g. if you app.Use, it doesn't mean that this middleware will be fired on errors, it's only registered to the app's routes). And `Party.RegisterView` works by using a special middleware to provide the view engine per party.

**Comment by kataras** [comment]
OK, it should be fixed now @AlbinoGeek thanks. A new `UseError` was introduced too, which will be fired only one `OnErrorCode/OnAnyErrorCode` routes.

**Comment by AlbinoGeek** [comment]
Yes, this is now fixed, thank you again.
