### ISSUE TITLE
[BUG]  `OnErrorCode` doesn't fire `app.Use` and friends

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1589]
## Summary

I tried to set an the result of `requestid.Get(ctx)` into `ViewData` globally using `app.Use(...)` -- however, it turns out that neither of these `app.Use(...)` functions are actually being called when triggered by an `OnErrorCode` as seen in the screenshot / example code.

## Screenshots

![image](https://user-images.githubusercontent.com/1910461/90305310-059e7780-de76-11ea-9ac7-e1dca1255129.png)

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master d0d7679|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code

```golang
// ... during app initialization
	app.Use(requestid.New())
	app.Use(func(ctx iris.Context) {
		ctx.ViewData("domain", *domain)
		ctx.ViewData("requestID", requestid.Get(ctx))
		ctx.Next()
	})

// ... when attaching the OnErrorCode
	your := app.Subdomain("your")
	your.Get("/", slashHandler)
	your.OnErrorCode(iris.StatusNotFound, slashHandler)

// ... later in the 404 handler
			ctx.ViewData("canon", fmt.Sprintf("%s%s", *domain, path))
			ctx.ViewData("langCode", lang)
			ctx.ViewData("pageURL", path)
			ctx.ViewData("title", fmt.Sprintf("%s - Not Found", *baseTitle))
			ctx.StatusCode(iris.StatusNotFound)
			if err := ctx.View("404.html"); err != nil {
				ctx.StatusCode(iris.StatusInternalServerError)
				ctx.Writef(err.Error())
			}
```

**Comment by kataras** [comment]
Yes that's not a BUG, it's behaving like that because we want to. The `Party.Use/Done` handlers are not running to error codes. This is why the new `Party.UseError` was introduced a minute ago, this is the same exact issue of #1588. @AlbinoGeek

**Comment by AlbinoGeek** [comment]
`UseError` has done exactly what I needed here, thank you -- such as protecting error pages of otherwise protected subdomains and parties.

**Comment by kataras** [comment]
You are welcome, always!!
