### ISSUE TITLE
JSON response panic when testing

### ISSUE THREAD

**Issue by pyr0hu** [kataras/iris#159]
When testing responses with fasthttpexpect, when I want to write a JSON to the output, the test panics. It works if I start listening and send a GET request.

Code:
```go
func HealthCheckHandler(c *iris.Context) {
	c.JSON(iris.StatusOK, map[string]string{"hello": "json"})
}

func TestHealthCheck(t *testing.T) {
	router := iris.New()
	router.HandleFunc("GET", "/health", HealthCheckHandler)
	router.PreListen(config.Server{ListeningAddr: ""})

	e := httpexpect.WithConfig(httpexpect.Config{
		Reporter: httpexpect.NewAssertReporter(t),
		Client:   fasthttpexpect.NewBinder(router.ServeRequest),
	})

	e.Request("GET", "/health").
		Expect().
		Status(http.StatusOK).Body().Equal(`{"status":"ok"}`)
}
```

The panic I receive:

panic: runtime error: invalid memory address or nil pointer dereference.

It says the error is on the c.JSON line, and the panic shows the the Render obj is actually nil

EDIT:

If I modify the handler to this:
```go
func HealthCheckHandler(c *iris.Context) {
	// c.JSON(iris.StatusOK, map[string]string{"hello": "json"})
	c.SetStatusCode(iris.StatusOK)
	responseData := map[string]string{"status": "ok"}
	marshalled, _ := json.Marshal(responseData)
	c.SetBodyString(string(marshalled))
}
```

then it works

**Comment by kataras** [comment]
@pyr0hu  Yes because you forgotten to call the ` router.PostListen()` do it after PreListen to your tests and this should works :)
