### ISSUE TITLE
[BUG] I18n - Default Language not respected when using Subdomain

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1591]
## Summary

It would appear the default language is not respected (and infact empty) when using Subdomains.

I would assume this is because language can be specified with a Subdomain, but we can't turn this off either. For e.g: if we only wanted to use the path-prefix language pattern, and utilize Subdomains for our own purposes.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master c22cb3a|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code

https://github.com/AlbinoGeek/issue-1591

**Comment by kataras** [comment]
Hello @AlbinoGeek,

> I would assume this is because language can be specified with a Subdomain, but we can't turn this off either. For e.g: if we only wanted to use the path-prefix language pattern, and utilize Subdomains for our own purposes.

There is the `app.I18n.Subdomain=false` this will turn it off.  And you have the `app.I18n.ExtractFunc(context) string` which you can use to extract the language by custom logic, e.g.

```go
app.I18n.ExtractFunc = func(ctx iris.Context) string { 
  // [custom logic here...]
  return "en"
}
```

And also, you can define the language in the handler-level:
```go
ctx.SetLanguage(langCode string) // this overrides the default extract methods and just sets the language directly.
```

The language is also get (and set for persistence) in a Cookie, which you can custom its name or disable it by setting to empty: `app.I18n.Cookie = "my_site_lang_code"`

**Comment by AlbinoGeek** [comment]
It would be nicer if the `DefaultLanguage` was respected (the core of the bug), where it is currently only as long as you're not using Subdomains. Even turning `app.I18n.Subdomain = false` did not restore the default. Instead, the default language is "" (which fails a lot of things.)

I can force a default, but this feels kludgey (I used to iterate through `Accept-Language` header in my 404 and `Get("/", ...` before using `I18n`, which felt even kludgey-er, so this is still quite an improvement.)

```golang
	app.I18n.Subdomain = false
	
	app.UseGlobal(func(ctx iris.Context) {
		if locale := ctx.GetLocale(); locale != nil {
			ctx.ViewData("langCode", locale.Language())
		} else {
			// force a default language
			ctx.SetLanguage("en-US")
			ctx.ViewData("langCode", ctx.GetLocale().Language())
		}
		ctx.ViewData("tr", ctx.Tr)
		ctx.Next()
	})
```

**Comment by kataras** [comment]
Let me check that @AlbinoGeek

**Comment by kataras** [comment]
@AlbinoGeek Why you set the `en-US` twice? (first and last) at: https://github.com/AlbinoGeek/issue-1591/blob/f2dae7f5f94a6561e9c09ca93172c3d3aa4f9324/main.go#L39

The example clearly registers that once, you don't need two slices, only one, comments says, first registered is the default language: https://github.com/kataras/iris/blob/ef7d365e8186394c4bc7af6565ffadc7d53006b1/_examples/i18n/main.go#L12-L13

**Comment by AlbinoGeek** [comment]
More so because I have configuration that has a list of `supportedLanguages`, and the variadic of the `I18n.Load` function required the `DefaultLanguage` be stated first. That's what resulted in the `en-US` language being listed twice.

For some reason, I get a `""` (blank) default language without the code I specified in my last reply. I will try and reproduce this behaviour in the issue repository and get back to you on this. It was specific to landing on the subdomain homepage with nothing special to indicate the language otherwise.

e.g: `your.example.com/` resulted in the language being `""` -- However, your images above show me that this should not be the case, so I will look into it more and close this if it's been remedied by your other changes. [but first, killing my editor, haha.]

**Comment by kataras** [comment]
>  [but first, killing my editor, haha.]

Hahaha I feel you, yes go for VS Code, you have a second option of Gogland but I really like VS Code and it's literally the only one code editor I have installed here for years.

> However, your images above show me that this should not be the case, 

Yes, the source code is that:

```go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/middleware/requestid"
)

var (
	devMode            = true
	localesDir         = "./locales/*/*.ini"
	supportedLanguages = []string{"en-US", "en-CA", "en-GB"}
	templatesDir       = "./templates"
)

func main() {
	app := iris.Default() // can be replaced with iris.New()
	// Load i18n.
	app.I18n.Subdomain = false
	if err := app.I18n.Load(localesDir, supportedLanguages...); err != nil {
		app.Logger().Fatal(err)
	}

	// Register views.
	app.RegisterView(iris.HTML(templatesDir, ".html").
		Layout("layouts/base.html").
		Reload(devMode))
	// All parties middlewares.
	app.UseGlobal(requestid.New())
	app.UseGlobal(func(ctx iris.Context) {
		// required, else you get some very ugly nil pointer reference errors from h2_bundler
		// I don't get it but let it as it's ^
		if locale := ctx.GetLocale(); locale != nil {
			ctx.ViewData("langCode", locale.Language())
		}
		ctx.ViewData("tr", ctx.Tr)
		ctx.ViewData("requestID", ctx.GetID())
		ctx.ViewData("pageURL", ctx.Request().URL.String())
		ctx.Next()
	})
	// Handle HTTP Errors.
	app.OnErrorCode(iris.StatusNotFound, func(ctx iris.Context) {
		ctx.View("404.html")
	})

	// Register the actual routes.
	app.Get("/", func(ctx iris.Context) {
		ctx.View("index.html")
	})

	// Register a "test.mydomain.com" subdomain:
	sub := app.Subdomain("test")
	sub.Get("/", func(ctx iris.Context) {
		ctx.View("index.html")
	})

	app.Listen("mydomain.com:80")
}

```

**Comment by kataras** [comment]
@AlbinoGeek  do you have `SubdomainRedirect` in that i18n real reproduce code of yours? If so, just to know if `app.I18n.PathRedirect`  is `true` (defaults to true) then it will register a wrapper which is always registered last (on build state), so it runs before the subdomain redirect.

**Comment by kataras** [comment]
@AlbinoGeek  do you have `SubdomainRedirect` in that i18n real reproducible code of yours? If so, just to know if `app.I18n.PathRedirect`  is `true` (defaults to true) then it will register a wrapper which is always registered last (on build state), so it runs before the subdomain redirect.

**Comment by kataras** [comment]
@AlbinoGeek I was able to re-produce that one with some tests. Let me find out what's wrong.

**Comment by AlbinoGeek** [comment]
@kataras Using the repository code as-is, the bug is reproduced.

Even adding `app.I18n.Subdomain = false` before line 37 did not remedy this.

Even removing the duplicate language reference at line 14 did not remedy this.

In all three cases, even loading `localhost:8080` produces a page without any langCode

That is, even before I add the complexity of Subdomains to the picture at all.

---

I have updated the repository with what I have tried so far.

**Comment by kataras** [comment]
Hello @AlbinoGeek ... Good morning from me, I have no words to thank you for your donation and the sponsorship 🥇 Will contact you for more through e-mail when we are done with these issues.

I pushed a commit which should fix the issue of `ctx.GetLocale` is nil some times (that happened here because the registered tags didn't match the language files, which could lead to a warning message if the loader.Strict option was enabled, but we allow this thing, so it's disabled by default. Now it should be fixed).

The subdomain redirect thing is also partially fixed, they always run first (or second if the ForceLowercaseRouting is enabled). But the problem is because each `SubdomainRedirect` has its own wrapper, it has no aware of the previous or next subdomain redirect rules and it can't decide well, e.g. when redirecting test. to your. subdomain with a request url of: el-gr.test.mydomain.com it will not redirect to el-gr.your.mydomain.com , because the el-gr is a language code subdomain and we can't just replace the 'test.' with 'your' because you may have more level of domains that naming can be the same, and as above, we don't know it upfront because each subdomain redirect is doing its own decisions(which was fine until now) <- that's the problem.

**Comment by AlbinoGeek** [comment]
Huzzah, Default Language is now respected!

Thank you again! I can simplify my mvc code further now.

---

Also, I'm about to commit a code generation project for `iris` :)  This should be fun.

**Comment by kataras** [comment]
That's great news @AlbinoGeek! You may want to take a look at https://github.com/kataras/iris-cli, it can build, run, watch and live reload html refresh on backend and frontend changes, it has also an option to "install" a "template" (see its registry.yml file). We may want to integrate our tools, let me know your thoughs!
