### ISSUE TITLE
[BUG] Inconsistant Request Logger with `HandleDir`

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1594]
## Summary

The Request Logger related to `HandleDir` doesn't seem to prefix the path it's mounted at in the generated logs.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|[master](https://github.com/kataras/iris/tree/master) commit ef7d365|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|

## Sample Code

```golang
	app.Party("/some/complex/path/to/assets").
		HandleDir("/", iris.Dir("./public"), iris.DirOptions{
			Compress:  true,
			DirList:   iris.DirList,
			IndexName: "/index.html",
			ShowList:  false,
			Cache: iris.DirCacheOptions{
				Enable:          true,
				CompressIgnore:  iris.MatchImagesAssets,
				CompressMinSize: 512,
				Encodings:       []string{"snappy", "br", "deflate", "gzip"},
			},
		})
```

### Results

```bash
[INFO] 2020/08/15 20:44 200 2.715115ms 192.168.0.1 GET /
[INFO] 2020/08/15 20:44 200 296.072µs 192.168.0.1 GET /fonts/open-sans-v17-latin-regular.woff2
[INFO] 2020/08/15 20:44 200 200.572µs 192.168.0.1 GET /fonts/open-sans-v17-latin-700.woff2
[INFO] 2020/08/15 20:44 200 26.06µs 192.168.0.1 GET /core.css
```

**Comment by kataras** [comment]
@AlbinoGeek Yes because the path is trimmed in order to find the resources relatively to the system/assets directory. Just like the `net/http.StripPrefix` does on that case. Do you really need to use the request logger on file serving? I think we all do register that middleware after the `app/Party.HandleDir` thing.

**Comment by AlbinoGeek** [comment]
I was treating the Request Logger like something I'd disable in production, that was more like the `Apache HTTP Access Log` in that it would print out full paths for all file requests, regardless of the Party/Subdomain/etc that registered it, so that it could aide me in debugging which thing actually served the request.

I totally understand if that's not it's purpose however. Good idea on attaching something to add the path back in, such as the `AssetValidator` or `UseGlobal` perhaps?

**Comment by kataras** [comment]
@AlbinoGeek fixed! Also the `iris.Default` now will register all of its default middlewares (recover, logger & compression) using the new `app.UseRouter`, so they are available everywhere. The logger now can log http errors as well (using a WARN level) when registered through `app.UseRouter(loggerMiddleware)` or `app.Use(loggerMiddleware) and app.UseError(loggerMiddleware)`.

**Comment by kataras** [comment]
@AlbinoGeek fixed! Also the `iris.Default()` now registers all of its default middlewares (recover, logger & compression) using the new `app.UseRouter`, so they are available everywhere. The logger now can log http errors as well (using a WARN level) when registered through `app.UseRouter(loggerMiddleware)` or `app.Use(loggerMiddleware) and app.UseError(loggerMiddleware)`.  Many thanks for that issue too!

**Comment by AlbinoGeek** [comment]
Thank you! That's awesome!

**Comment by kataras** [comment]
You are welcome @AlbinoGeek, I've just pushed a commit which adds a `TraceRoute bool` field on the logger's configuration (defaults to false), it will print debug information about the executed route too:

![logger middleware: TraceRoute screenshot](https://iris-go.com/images/github/logger-trace-route.png)

**Comment by AlbinoGeek** [comment]
Oooooooooo! I LOVE IT!
Thank you so much.

**Comment by AlbinoGeek** [comment]
@kataras Problem though:

With `TraceRoute` on, I can't see what file or URL was requested anymore. [unlike your screenshot.]

I'm missing `StatusCode IP Path` , have only `RequestTime`

![image](https://user-images.githubusercontent.com/1910461/90573513-78a43880-e16b-11ea-8db5-655b5e753a53.png)

**Comment by kataras** [comment]
Yeah @AlbinoGeek , if you need to keep boolean defaults and just set one or two fields you can do:

```go
cfg := logger.DefaultConfig()
cfg.TraceRoute = true
logger.New(cfg)
```

You liked it? I think it's useful and I dont know other framework supporting that kind of thing (in any language)

**Comment by AlbinoGeek** [comment]
Mhmm, I do like it. It's wonderful. And yes, thank you for the hint in `DefaultConfig`
