### ISSUE TITLE
How to alter response body in middlware?

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1596]
The web interface is usually implemented in the following form:
```
type Student struct {
  Name string
  Age int
}

app := iris.New()
app.Get("/test", func(ctx iris.Context) {
  ctx.JSON(Student{Name: "Tim", Age: 10})
})
```
when request `/test` it returns JSON like this:
```
{
  Name: "Tim",
  Age: 10
}
```

I want all the response results to be converted to the following form:
```
type ResponseEntity struct {
  Code int
  Data interface{}
  Message string
}
```

now the result should like this:
```
{
  Code: 200,
  Data: {
    Name: "Tim",
    Age: 10
  },
  Message: "OK"
}
``` 
how to do this?

**Comment by kataras** [comment]
Hello @tuhao1020, you have plenty of options:

**1.** Use dependency injection and use its "result handler" to inject each matched return value/output of a handler, examples: https://github.com/kataras/iris/blob/589c8c6242ceeb31068b07be7bf384530fbc9190/_examples/dependency-injection/basic/main.go#L20-L38 https://github.com/kataras/iris/blob/589c8c6242ceeb31068b07be7bf384530fbc9190/hero/container_test.go#L101-L131
**2.** Use recording through `ctx.Record` and register a `Done` middleware, read its body and change it: https://github.com/kataras/iris/wiki/Response-recorder
**3.** Wrap the `ctx.JSON` with your own function (it's the best solution if you dont want to use dependency-injection), e..g:

```go
type ResponseEntity struct {
  Code int
  Data interface{}
  Message string
}

func JSON(ctx iris.Context, data interface{}) (int, error) {
   responseCode := ctx.GetStatusCode() // returns the value set-ed by ctx.StatusCode(code)

   response := ResponseEntity{
     Code: responseCode 
     Data: data,
     Message: iris.StatusText(responseCode),
   } 

   return ctx.JSON(response)
}

func myHandler(ctx iris.Context) {
  JSON(ctx, Student{Name: "Tim", Age: 10})
}
```

Thanks,
Gerasimos Maropoulos.

**Comment by kataras** [comment]
Hello @tuhao1020, you have plenty of options:

**1.** Use dependency injection and use its "result handler" to inject each matched return value/output of a handler, examples: https://github.com/kataras/iris/blob/589c8c6242ceeb31068b07be7bf384530fbc9190/_examples/dependency-injection/basic/main.go#L20-L38 https://github.com/kataras/iris/blob/589c8c6242ceeb31068b07be7bf384530fbc9190/hero/container_test.go#L101-L131
**2.** Use recording through `ctx.Record` and register a `Done` middleware, read its body and change it: https://github.com/kataras/iris/wiki/Response-recorder
**3.** You don't need a middleware, just wrap the `ctx.JSON` with your own function (it's the best solution if you dont want to use dependency-injection), e..g:

```go
type ResponseEntity struct {
  Code int
  Data interface{}
  Message string
}

func JSON(ctx iris.Context, data interface{}) (int, error) {
   responseCode := ctx.GetStatusCode() // returns the value set-ed by ctx.StatusCode(code)

   response := ResponseEntity{
     Code: responseCode 
     Data: data,
     Message: iris.StatusText(responseCode),
   } 

   return ctx.JSON(response)
}

func myHandler(ctx iris.Context) {
  JSON(ctx, Student{Name: "Tim", Age: 10})
}
```

**4.** However, if you need a middleware you can just use the `ctx.Values().Set("data", jsonValue)` and make the conversion later on, example:

```go
app.Done(func(ctx iris.Context) {
   data := ctx.Values().Get("data")
   JSON(ctx, data) // See "3." above
}) // You can use app.Use(.... ctx.Next() and then the logic) or app.UseError to support error  handlers too.

func myHandler(ctx iris.Context) {
   ctx.Values().Set("data", Student{Name: "Tim", Age: 10})
   ctx.Next()
}
```

Thanks,
Gerasimos Maropoulos.

**Comment by tuhao1020** [comment]
I prefer the second solution because it's simple and not require modification of existing code. But, is the first solution the most recommended?

**Comment by kataras** [comment]
@tuhao1020 the second solution will require to use the `ctx.Recorder().Body()`, then unmarshal to your struct, then marshal to the new one and `ctx.Recorder().SetBody` too, which is NOT recommended for your use case, it would be if you used string or raw bytes data though. Choose the third or the first one, if I was you and the app is big, then will defintely go for the first solution (dependency injection).

**Comment by kataras** [comment]
@tuhao1020 the second solution will require to use the `ctx.Recorder().Body()`, then unmarshal to your struct, then marshal to the new one and `ctx.Recorder().SetBody` too, which is NOT recommended for your use case, it would be if you used string or raw bytes data though. Choose the third or the first one, if I were you and the app was huge, then will definitely go for the first solution (dependency injection).

**Comment by tuhao1020** [comment]
I will learn more about dependency injection. Thanks a lot @kataras

**Comment by kataras** [comment]
@tuhao1020 don't tell to everyone but here is a complete overview of the feature: https://docs.iris-go.com/iris/dependency-injection/dependency-injection, read the examples I sent you above and you will be ready :) You are welcome!

**Comment by kataras** [comment]
@tuhao1020 


```go
package main

import (
	"fmt"
	"time"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()
	app.RegisterView(iris.HTML("./views", ".html"))

	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

// Generic response type for JSON results.
type response struct {
	ID        uint64      `json:"id,omitempty"`
	Data      interface{} `json:"data,omitempty"` // {data: result } on fetch actions.
	Code      int         `json:"code,omitempty"`
	Message   string      `json:"message,omitempty"`
	Timestamp int64       `json:"timestamp,omitempty"`
}

func (r response) Preflight(ctx iris.Context) error {
	if r.ID > 0 {
		r.Timestamp = time.Now().Unix()
	}

	if code := r.Code; code > 0 {
		ctx.StatusCode(r.Code)
	}

	return nil
}

type user struct {
	ID uint64 `json:"id"`
}

func (c *controller) GetBy(userid uint64) response {
	if userid != 1 {
		return response{
			Code:    iris.StatusNotFound,
			Message: "User Not Found",
		}
	}

	return response{
		ID:   userid,
		Data: user{ID: userid},
	}
}

```

> http://localhost:8080/1 and http://localhost:8080/42.

You can use that `response` on non-mvc applications too, using handlers:

```go
c := app.ConfigureContainer()
c.Get("/{id:uint64}", getUserByID)
```

```go
func getUserByID(id uint64) response {
	if userid != 1 {
		return response{
			Code:    iris.StatusNotFound,
			Message: "User Not Found",
		}
	}

	return response{
		ID:   userid,
		Data: user{ID: userid},
	}
}
```
