### ISSUE TITLE
How to use the pongo2 template?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#16]
Good for iris!
But how to use the pongo2 template?
https://github.com/flosch/pongo2

Could you give a sample for it?

**Comment by kataras** [comment]
Hello @xpbliss  I am writing from the begin some components of the Iris, when I finish I will look at this, if it's good I will make a port to Iris or contact with the author of pongo2 to do it ( if it's not compatible by default) I will notice you. Do not hesitate to pull request if you have already a solution for this. Thanks for the issue !

**Comment by kataras** [comment]
Hello @xpbliss Iris uses the standar html/template package  for templating, you can use whatever you like. You can get the ResponseWriter and Request from context.ResponseWriter, context.Request and map it to the pongo2, I never used it before. If this doesn't works for you can you give me an example how you imagine it to work with Iris so I can write a middleware for that?

**Comment by xpbliss** [comment]
You are  easy to  update the iris for pongo2.   maybe  such as the following:

•	[macaron-pongo2](https://github.com/macaron-contrib/pongo2) - pongo2 support for Macaron, a modular web framework.
•	[ginpongo2](https://github.com/ngerakines/ginpongo2) - middleware for gin to use pongo2 templates
•	[pongo2gin](https://github.com/robvdl/pongo2gin) - alternative renderer for gin to use pongo2 templates
•	[pongo2-trans](https://github.com/fromYukki/pongo2trans) - trans-tag implementation for internationalization
•	[tpongo2](https://github.com/tango-contrib/tpongo2) - pongo2 support for Tango, a micro-kernel & pluggable web framework.


And I want to use pongo2 for iris!

**Comment by kataras** [comment]
Ok, I can create fast a middleware, but I want from you to test it on a real application, for me because I don't use pongo2 templates, check the repository  at 10 minutes :)

**Comment by xpbliss** [comment]
I am glad to test it!

**Comment by kataras** [comment]
@xpbliss  it's ready check _examples/pongo2_templates I didn't test it and I don't have time right now, please do it if any bug post an issue here,really  thanks you very much!

**Comment by xpbliss** [comment]
```
var aa map[string]interface{}
aa["bb"]=[]struct {
		Karma        int
		RegisterDate time.Time
		Biography    string
	}{
		{Karma: 10, RegisterDate: time.Now().Local(), Biography: "Smth here..."},
		{Karma: 100, RegisterDate: time.Now().Local(), Biography: "Smth else here..."},
	} 
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Set("template", "index.html")
		ctx.Set("data",aa )
	})
```

panic: assignment to entry in nil map

**Comment by kataras** [comment]
@xpbliss can you provide a more detail error stack? it's nil on the first ctx.Set ?

**Comment by xpbliss** [comment]
I just replace the sample of the pongo2 middleware.

**Comment by kataras** [comment]
with .Use(middleware.Pongo2()) and the index.html at the correct path ?
look again the examples folder I updated it to use a simple template

**Comment by xpbliss** [comment]
Yes. it work. 
 but ....
https://github.com/ngerakines/ginpongo2/issues/2
A better way may be like the [pongo2gin](https://github.com/robvdl/pongo2gin)

**Comment by kataras** [comment]
So you want to add a full Renderer to the Iris? I don't think so that's a good idea for now, Iris gives you freedom about renderer  why this middleware doesn't fit you? you sent me the links of the other middlewares I though you wanted something like that

**Comment by xpbliss** [comment]
the html is as following
```
<html>
<head>
    <title>test for pongo2</title>
</head>
<body> 
<div>
    {% for usr in users %} 
        {{  usr.Karma  }}--->>{{usr.RegisterDate}}-->>{{usr.Biography}} <br />	 
    {% endfor %}
	<h1>Is an Admin?--->>{{isAdmin}}</h1>
	<h1>5 add 6 eqaual:{{func_add(5,6)}}</h1>
</div>
</body>
</html>
```
the go code as following:
```
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware"
	"time"
)

//This example doesn't contain any real pongo2 templates, just the basic code  for the middleware

func main() {
	iris.Use(middleware.Pongo2())

	var aa map[string]interface{}
	aa = map[string]interface{}{
		"users": []struct {
			Karma        int
			RegisterDate time.Time
			Biography    string
		}{
			{Karma: 10, RegisterDate: time.Now().Local(), Biography: "Smth here..."},
			{Karma: 100, RegisterDate: time.Now().Local(), Biography: "Smth else here..."},
		},
		"isAdmin": true,
		"func_add": func(a, b int) int {
			return a + b
		},
	}
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Set("template", "index.html")
		ctx.Set("data", aa)
	})

	iris.Listen(":8080")
}

```
when refresh the browser , the "usr.RegisterDate" is not the updated, it's still the past datetime?  maybe the cache affect?

**Comment by kataras** [comment]
No the cache is only resposible to match the urls with the handler, the handler is always new and re-executing

**Comment by xpbliss** [comment]
thanks!

**Comment by kataras** [comment]
Do not hesitate to ask again, I'm here always :) thanks you
