### ISSUE TITLE
How should i handle this problem pls.

### ISSUE THREAD

**Issue by lichunqiang** [kataras/iris#160]
After run `go get github.com/kataras/iris`, I had got an error outputed:

```
D:\go\src\github.com\kataras\iris\party.go:424: unknown fasthttp.FS field 'Compr
essedFileSuffix' in struct literal
```

Env:

* win8
* go version go1.6.2 windows/amd64

**Comment by venliong** [comment]
看起来是fasthttp版本较旧，试试这个：
go get -u github.com/kataras/iris

**Comment by raitucarp** [comment]
iris is under active development, you have to made sure what the version is.

**Comment by insionng** [comment]
@lichunqiang 更新fasthttp包，或直接删了重新go get～

**Comment by kataras** [comment]
@lichunqiang  fasthttp's `Compr
essedFileSuffix` is a new option, suggest by me to the author of fasthtttp, so you should do: ` go get -u github.com/kataras/iris` to update all packages releated to Iris
