### ISSUE TITLE
[BUG] authenticated-controller - AuthDependency returns `401 Unauthorized` for undefined routes (should be `404`?)

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1602]
## Summary

I am attempting to implement the logic described in both the [goth example](../blob/master/_examples/auth/goth/main.go) and the [authenticated-controller example](../blob/master/_examples/mvc/authenticated-controller/main.go) and noticed an unusual way to trigger an `HTTP 401 Unauthorized` which did not show up in the logs.

This seems like a very peculiar behaviour, I expected almost literally any other 4xx error, not this one. I also expected it to be shown in the logs, so I could try and debug exactly which controller or route was throwing this error, but no new lines were generated.

## Simplified Reproduction

- Follow the examples, but only define `GetLogin` in `authenticated-controller`
- Submit a basic HTML form on the `GetLogin` route, which should trigger a non-existing `PostLogin`
- You are presented with an `HTTP 401 Unauthorized`

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|[master](https://github.com/kataras/iris/tree/master) commit 8e049d7|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|

## Sample Code

```golang
type Authenticated uint64

type AuthorizedUserController struct {
	CurrentUserID Authenticated
}

type UnauthorizedUserController {}

var sessionManager *sessions.Sessions

// To confirm the route missing is what triggers this funky behaviour, uncomment the following:
// func (c *UnauthorizedUserController) PostLogin(ctx iris.Context) mvc.Result {
// 	return mvc.Response{
// 		Text: "Hello, Login!",
// 	}
// }

func main() {
// ...
	your := app.Subdomain(viper.GetString("PrimarySubDomain"))

	// setup session manager
	hashKey := securecookie.GenerateRandomKey(64)
	blockKey := securecookie.GenerateRandomKey(32)
	sessionManager = sessions.New(sessions.Config{
		Cookie:       viper.GetString("SecureCookieName"),
		Encoding:     securecookie.New(hashKey, blockKey),
		AllowReclaim: true,
	})
	// NOTE: apparently using sessionManager.Start does not honour AllowReclaim or Encoding
	// making me wonder how I am supposed to use securecookie with authenticated-controller

	// register controllers on our site
	userRouter := your.Party("/user")
	userRouter.SetRegisterRule(iris.RouteOverlap)
	userApp := mvc.New(userRouter)
	userApp.Register(AuthDependency)
	userApp.Handle(new(AuthorizedUserController))
	userApp.Handle(new(UnauthorizedUserController))
// ...
}

func AuthDependency(ctx iris.Context) Authenticated {
	// using the authenticated-controller source verbatim leads to `sessions = nil` panic
	// So, I think this is what I have to do to make the goth example work?
	session := sessionManager.Start(ctx)
	// I have to assume this is generating the 401... but why?

	// also yes, I saw the note about "app.Use(sess.Handler) ... avoid calling manually"
	// but cannot figure out how to do so given the authenticated-controller example
	// and that `Use` won't trigger on error pages, as discussed in a previous issue

	userID := session.GetUint64Default("user_id", 0)
	if userID == 0 {
		// If execution was stopped
		// any controller's method will not be executed at all.
		ctx.StopWithStatus(iris.StatusUnauthorized)
		return 0
	}

	return Authenticated(userID)
}

func (c *AuthorizedUserController) Get() mvc.Result {
	return mvc.View{
		Code: iris.StatusOK,
		Name: "user/index.html",
	}
}

func (c *UnauthorizedUserController) GetLogin(ctx iris.Context) mvc.Result {
	return mvc.View{
		Code: iris.StatusOK,
		Name: "user/login.html",
	}
}
```

**Comment by AlbinoGeek** [comment]
Okay, the `without logs` part is because `app.Use(...)` doesn't fire errors, which then leads me to the question:

### What is the difference between `UseRouter` and `UseGlobal` ?

**Comment by AlbinoGeek** [comment]
GitHub wouldn't let me edit that last comment, so... new comment ---
I am making a new issue for `UseGlobal` vs `UseRouter` different log output

**Comment by AlbinoGeek** [comment]
I think this bug might go away when #1603 is handled, after digging into it further and updating the sample code repo.

**Comment by AlbinoGeek** [comment]
Effectively now a duplicate of #1603 -- more detailed there.

**Comment by kataras** [comment]
Yes @AlbinoGeek  they are actually the same issue, also I added some debug (at design state) messages for controller's methods too (their middlewares are shown in the API debug section):


![](https://camo.githubusercontent.com/e2f045231f97e955e35b894b8603360dd9455fe8/68747470733a2f2f697269732d676f2e636f6d2f696d616765732f7631322e322e302d64627567332e706e673f763d30)
