### ISSUE TITLE
[BUG] Logging registered on `UseRouter` vs `UseGlobal` entirely different output

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1604]
## Summary

Whether you choose to register the logger using `UseGlobal` or `UseRouter` (as `iris.Default()` would) gives you entirely different output, with entirely different consequences. This has made diagnosing #1602 and #1603 very difficult.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|[master](https://github.com/kataras/iris/tree/master) commit ef5685b|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|

#### Pros

- See Checkmarks (sometimes)
- Shows Middleware a `Controller` registers in `BeforeActivation`

#### Cons

- Extremely limited (almost no) output on 404s
- Doesn't show `HandleHTTPError` calls, for 400, 401 etc.

```golang
[WARN] 2020/08/23 16:56 400 106.426µs 192.168.0.1 POST /user/login
POST: /user/login controller (./main.go:134)
      • iris.request.id (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/requestid/requestid.go:70) ✓
      • iris.glob. (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/aliases.go:241) ✓
      • iris/core/router.(*APIBuilder).RegisterView (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/core/router/api_builder.go:1268) ✓
      • [redacted]/controllers/base.populateViewData (./controllers/base/populateViewData.go:10) ✓
      • [redacted]/controllers/base.populateViewData (./controllers/base/populateViewData.go:10) ✓
      • user.UnauthorizedUserController.PostLogin (./controllers/user/Unauthorized.go:29) ✓

[WARN] 2020/08/23 17:08 404 20.48µs 192.168.0.1 POST /user/login2
```

#### Pros

- Shows things like `overlapRoute` that aren't shown in `UseRouter`

#### Cons

- Never see the Checkmarks
- Doesn't show Middleware that `UseRouter` does
- Lies about `HandleHTTPError` in 404s (it was never called.)

```golang
[WARN] 2020/08/23 16:55 401 122.495µs 192.168.0.1 POST /user/login
400: /user/{tail:path} controller (./main.go:133)
     • iris/core/router.overlapRoute (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/core/router/api_builder.go:136)
     • iris.recover (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/recover/recover.go:30)
     • iris.logger (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/logger/logger.go:47)
     • iris.request.id (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/requestid/requestid.go:70)
     • iris.glob. (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/aliases.go:241)
     • iris/core/router.(*APIBuilder).RegisterView (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/core/router/api_builder.go:1268)
     • user.AuthorizedUserController.HandleHTTPError (./controllers/user/Authorized.go:22)

[WARN] 2020/08/23 17:12 401 181.097µs 192.168.0.1 POST /user/login2
404: /user/{tail:path} controller (./main.go:133)
     • iris/core/router.overlapRoute (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/core/router/api_builder.go:136)
     • iris.recover (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/recover/recover.go:30)
     • iris.logger (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/logger/logger.go:47)
     • iris.request.id (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/middleware/requestid/requestid.go:70)
     • iris.glob. (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/aliases.go:241)
     • iris/core/router.(*APIBuilder).RegisterView (/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200823145529-ef5685bf7eeb/core/router/api_builder.go:1268)
     • user.AuthorizedUserController.HandleHTTPError (./controllers/user/Authorized.go:22)
```

**Comment by kataras** [comment]
@AlbinoGeek Do you write content on other `UseRouter`? If that's the case that's why you never get `404` because the status code is sent already there. Look that test to check see order of execution:

```go
func TestWrapUseOrder(t *testing.T) {
	var (
		expectedBody         = "#1 .WrapRouter\n#2 .UseRouter\n#3 .UseGlobal\n#4 .Use\n#5 Main Handler\n"
		expectedNotFoundBody = "#1 Main Error Handler\n"
		makeMiddleware       = func(body string) iris.Handler {
			return func(ctx iris.Context) {
				if ctx.Path() == "/" {
					ctx.WriteString(body)
				}

				ctx.Next()
			}
		}

		handler = func(ctx iris.Context) {
			ctx.WriteString("#5 Main Handler\n")
		}

		errorHandler = func(ctx iris.Context) {
			ctx.WriteString("#1 Main Error Handler\n")
		}

		useHandler = makeMiddleware("#4 .Use\n")
		useGlobal  = makeMiddleware("#3 .UseGlobal\n")
		useError   = makeMiddleware("#3 .UseError\n")
		useRouter  = makeMiddleware("#2 .UseRouter\n")
		wrapRouter = func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) {
			if r.URL.Path == "/" {
				w.Write([]byte("#1 .WrapRouter\n"))
				// Note for beginners, reading this test:
				// if we write something here on a not found page,
				// in the raw net/http wrapper like this one,
				// then the response writer sends 200 status OK
				// (on first write) and so any error handler will not be fired as expected,
				// these are basic things. However, if you do the same in an Iris Handler
				// you will not have this problem, we record and keep the status code until
				// the request-response lifecycle is ended.
			}

			router(w, r)
		}
	)

	app := iris.New()
	app.Use(useHandler)
	app.UseGlobal(useGlobal)
	app.UseError(useError)
	app.UseRouter(useRouter)
	app.WrapRouter(wrapRouter)

	app.OnErrorCode(iris.StatusNotFound, errorHandler)
	app.Get("/", handler)

	e := httptest.New(t, app)
	e.GET("/NotFound").Expect().Status(iris.StatusNotFound).Body().Equal(expectedNotFoundBody)
	e.GET("/").Expect().Status(iris.StatusOK).Body().Equal(expectedBody)
}
```

**Comment by kataras** [comment]
The output is expected to be different between UseRouter and UseGlobal. They are doing a totally different thing.



The `UseGlobal` is registered on previous and next current Party's routes at the first position of their handlers chain. It is executed only on matched routes, by registration order. It is an Iris Handler `func(ctx iris.Context)` and it requires `ctx.Next` to proceed (unless execution rules changed).

The `UseRouter` is registered under a Party,  it runs on the path prefix of the Party. It is executed before the Iris Router, so it does not know the error code up-front (remember: it doesn't know if a route matched or not yet) and it is helpful because of that, you can change the path and e.t.c. to let router match or cancel a specific route you want. It's one level higher than the `WrapRouter` and one level lower than the `Use/UseGlobal`. Same as `Use and UseGlobal`, it's an `iris.Handler` and it requires `ctx.Next` to proceed to the next `UseRouter` or to the main `iris router` if it's the last one.

The `WrapRouter` wraps the main Server Handler, including any UseRouter and the Iris Router. Last registered wraps the previous ones, so last registered runs first. It's the lowest level. It is a `func(w http.ResponseWriter, r *http.Request, router http.HandlerFunc) and a call of its `router(w,r)` is required to run the main router (if you want, it depends the needs of your implenentation, e.g. you can chaneg the host, path to match a specific route, like `UseRouter` or just make a fast redirection or to disallow a specific IP/client before even any router or middleware is being executed).

**Comment by kataras** [comment]
@AlbinoGeek I posted an answer on https://github.com/kataras/iris/issues/1605 as they are both relative. I will explain why every of the above happens.

**Comment by AlbinoGeek** [comment]
Thank you for your explanation in #1605 -- that definitely answers this question.

However, it leads me to believe I need to attach a logger with both `UseRouter` and `UseError` for debugging, as otherwise errors won't provide a TracePath, or anything else to help me debug the process through which they were arrived at.

**Comment by AlbinoGeek** [comment]
After some testing, it seems:

```golang
	// requestid works with UseRouter
	your.UseRouter(requestid.New())

	auth := basicauth.New(basicauth.Config{
		Users:   viper.GetStringMapString("AuthorizedUsers"),
		Realm:   "Authorization Required", // defaults to "Authorization Required"
		Expires: time.Duration(30) * time.Minute,
	})

	// basicauth does not work with UseRouter
	your.Use(auth)
	your.UseError(auth)

	// compression works with UseRouter
	your.UseRouter(iris.Compression)
```

**Comment by kataras** [comment]
@AlbinoGeek, You don't want to register `Basic Auth` with `UseRouter` (it will be executed on 404s too). However I see that you use that on `UseError` so you want to use it on error requests and responses too. `UseRouter `should work, I'll take a look on that.

**Comment by AlbinoGeek** [comment]
Yeah, I want to protect even `404`s with this.

**Comment by kataras** [comment]
OK I am going for that right now!

**Comment by kataras** [comment]
Hmmm @AlbinoGeek it seems that it's working, at least here:

```go
	app := iris.New()
	users := map[string]string{
		"usr":   "pss",
		"admin": "admin",
	}

	app.UseRouter(basicauth.Default(users))

	app.Get("/", func(ctx iris.Context) {
		ctx.Writef("Hello, %s!", ctx.Request().URL.User.Username())
	})

```

If `localhost:8080/notfound` then it asks for credentials, if passed, then it returns 404 not found otherwise (cancel or invalid credentials) 401 unauthorized.

**Comment by kataras** [comment]
Hmmm @AlbinoGeek it seems that it's working, at least here:

```go
	app := iris.New()
	users := map[string]string{
		"usr":   "pss",
		"admin": "admin",
	}

	app.UseRouter(basicauth.Default(users))

	app.Get("/", func(ctx iris.Context) {
                // to get user details by the URL line:
                // username := ctx.Request().URL.User.Username()
                // more robust in most cases:
                username, _, _ := ctx.Request().BasicAuth() // username, password (string), ok (bool)
		ctx.Writef("Hello, %s!", username)
	})

```

If `localhost:8080/notfound` then it asks for credentials, if passed, then it returns 404 not found otherwise (cancel or invalid credentials) 401 unauthorized.

**Comment by AlbinoGeek** [comment]
It works on `app.` -- but then the `static.` Subdomain is also "protected" with `basicauth` , which then means those requests fail.

It doesn't work when applied to a `Subdomain` -- but since using `rewrite`, I'm now not using `Subdomain` for anything other than the public/assets.

**Comment by kataras** [comment]
Can I aks @AlbinoGeek, you use the `UseRouter` to register the basic auth middleware twice for `static.` and `app.` ?

**Comment by AlbinoGeek** [comment]
Just in `app.UseRouter` -- and it somehow was asking for basicauth on `static` too.

**Comment by kataras** [comment]
Yes this is supposed to do, that's why I ask (godoc):

https://github.com/kataras/iris/blob/1780d97d4458d2df73fd655ba61a70e1c07bd595/core/router/api_builder.go#L899-L901

https://github.com/kataras/iris/blob/1780d97d4458d2df73fd655ba61a70e1c07bd595/core/router/api_builder.go#L927-L931

**Comment by AlbinoGeek** [comment]
Thank you! Of course, once `app` becomes the de facto method of doing this, `Subdomain` can sort of be replaced by independent applications with their own Middleware stacks and such.

Yet again, thank you for all the work you put forward on these things.

**Comment by kataras** [comment]
OK @AlbinoGeek the `Reset` now will reset the router filders but if you only want to reset the `UseRouter` filters then you can use the new `ResetRouterFilters()` too, e.g. `app.Subdomain("static").ResetRouterFilters().HandleDir(...)`.

> once app becomes the de facto method of doing this, Subdomain can sort of be replaced by independent applications with their own Middleware stacks and such.

Yes, exactly my thoughts about the goal of the new `apps` subpackage, although you could just create new iris apps, build them and use them as raw `http.Handler` on any http.Server but that will require a lot of manual coding to map the apps to the requests (e.g. baesed on host, path, scheme and e.t.c.) that's the new `apps` package does.

**Comment by kataras** [comment]
OK @AlbinoGeek the `Reset` now will reset the router filters too, however, if you only want to reset the `UseRouter` filters then you can use the new `ResetRouterFilters()` too, e.g. `app.Subdomain("static").ResetRouterFilters().HandleDir(...)`.

> once app becomes the de facto method of doing this, Subdomain can sort of be replaced by independent applications with their own Middleware stacks and such.

Yes, exactly my thoughts about the goal of the new `apps` subpackage, although you could just create new iris apps, build them and use them as raw `http.Handler` on any http.Server but that will require a lot of manual coding to map the apps to the requests (e.g. baesed on host, path, scheme and e.t.c.) that's the new `apps` package does.

**Comment by kataras** [comment]
OK @AlbinoGeek the `Reset` now will reset the router filters too, however, if you only want to reset the `UseRouter` filters then you can use the new `ResetRouterFilters()` too, e.g. `app.Subdomain("static").ResetRouterFilters().HandleDir(...)`. [basicauth test](https://github.com/kataras/iris/commit/d44b69faed7538aeb4a05ec72ec664fbee7f5c04#diff-1985f5043cf57ab31989cef1d7efdd3d)

Also, don't forget that you can always wrap an existing middleware to add custom logic, e..g to make basic auth middleware (or any middleware) to skip static subdomain **without** `ResetRouterFilters`, you could just write:

### 1. Manual

```go
func main() {
    auth := basicauth.New(basicauth.Config{
		Users:   viper.GetStringMapString("AuthorizedUsers"),
		Realm:   "Authorization Required", // defaults to "Authorization Required"
		Expires: time.Duration(30) * time.Minute,
    })

    app.UseRouter(skipStaticSubdomain(auth))
    // [...]
}

func skipStaticSubdomain(handler iris.Handler) iris.Handler {
       return func(ctx iris.Context) {
            if ctx.Subdomain() == "static." {
                 ctx.Next()
                 return
            }

             handler(ctx)   
        }
}
```

### 2. Using [iris.NewConditionalHandler](https://github.com/kataras/iris/blob/d44b69faed7538aeb4a05ec72ec664fbee7f5c04/_examples/routing/conditional-chain/main.go#L40)

```go
func main() {
    auth := basicauth.New(basicauth.Config{
		Users:   viper.GetStringMapString("AuthorizedUsers"),
		Realm:   "Authorization Required", // defaults to "Authorization Required"
		Expires: time.Duration(30) * time.Minute,
    })

    //                                      (iris.Filter,         ...iris.Handler)
    app.UseRouter(iris.NewConditionalHandler(isNotStaticSubdomain, auth /* [ more handlers can be registered... */))
    // [...]
}

// func(ctx iris.Context) bool is an iris.Filter.
func isNotStaticSubdomain(ctx iris.Context) bool {
    return ctx.Subdomain() != "static."
}
```


> once app becomes the de facto method of doing this, Subdomain can sort of be replaced by independent applications with their own Middleware stacks and such.

Yes, exactly my thoughts about the goal of the new `apps` subpackage, although you could just create new iris apps, build them and use them as raw `http.Handler` on any http.Server but that will require a lot of manual coding to map the apps to the requests (e.g. baesed on host, path, scheme and e.t.c.) that's the new `apps` package does.

> Check this tweet whenever you are free, I couldn't find the twitter username of yours but if you have one I can tag you:

[![tw image](https://user-images.githubusercontent.com/22900943/91257120-c0c9e900-e771-11ea-9b16-74570964ac80.png)](https://twitter.com/MakisMaropoulos/status/1298471904429453312)

**Comment by AlbinoGeek** [comment]
Thank you for explaining how this would work!

Also yes, I don't use Twitter often, but:
https://twitter.com/AlbinoStoic
