### ISSUE TITLE
[QUESTION] Get Handler Result from `HandleHTTPError`

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1606]
## Summary

I would like to be able to get the Handler's Result (if any) from inside a `Controller.HandleHTTPError` , this would allow me to manipulate the result itself, and help in diagnosing things like #1603 -- where I really can't figure out why a `200 OK` would result in the error management function being called.

Also, when a `400` is shown because I set a `mvc.View.Err` field, I would like to be able to drive a page that shows this error message, but I cannot figure out how to get that `mvc.View` that was returned from the last executed Handler.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|[master](https://github.com/kataras/iris/tree/master) commit ef5685b|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|

## Code

```golang
type ExampleController struct {}

func (c *ExampleController) HandleHTTPError(ctx iris.Context, statusCode mvc.Code) mvc.Result {
	view := mvc.View{Code: int(statusCode)}

	// see #1603 as to why this check is even required atm
	if view.Code == 200 {
		// this causes no page to be rendered
		// because I don't know how to get the Handler's previous result and return that
		return nil
	}
	
	view.Name = fmt.Sprintf("error-%d.html", view.Code)
	switch view.Code {
	case 400:
		// likewise, a `mvc.View.Err` being set means this branch of code is called
		// but I don't know how to get the Handler's previous result, to extract the error in question
	default:
		golog.Warnf("error %d masked and shown to user as a 500", statusCode)
		view.Name = "error-500.html"
	}

	return view
}

func (c *ExampleController) Get(ctx iris.Context) mvc.Result {
	return mvc.View{
		Code: iris.StatusOK,
		Err: err, // could be nil, but might not be
		Name: "index.html",
	}
}
```

**Comment by kataras** [comment]
@AlbinoGeek the `Err: err` can be retrieved through `ctx.GetErr` so you can see if it's nil or not, as the #1603 was fixed, are you still want a feature like this?

**Comment by kataras** [comment]
@AlbinoGeek the `Err: err` can be retrieved through `ctx.GetErr` so you can see if it's nil or not, as the #1603 was fixed, are you still want a feature like this? E.g what access you want on your HandleHTTPError, to get the `mvc.View` the `Get` return and why you want something like that even if Get is not executed at all (e.g. 404)? I think it's better to return different responses on errors and others for succesful responses so you can debug your application easier later on.

**Comment by AlbinoGeek** [comment]
For whatever reason, the `Err` is always `<nil>` -- but so is `ctx.GetErr()` when called within `Controller.HandleHTTPError` -- so I'm currently unable to pull the error.

```golang
	user, err := CompleteUserAuth(provider, ctx)
	if err != nil {
		golog.Warn("GetCallbackBy - CompleteUserAuth", err)
		return mvc.View{
			Code: iris.StatusInternalServerError,
			Err: err, // can't seem to get this into an `HandleHTTPError`
		}
	}
```

**Comment by kataras** [comment]
Hello @AlbinoGeek,

Strange, the following prints the error as expected on http://localhost:8080/error

![image](https://user-images.githubusercontent.com/22900943/91718813-cde53e80-eb9c-11ea-8bf5-1369fdb12f4c.png)


```go
func main() {
     // [...]
     mvc.New(app).Handle(new(controller))

    // [...]
}

func (c *controller) GetError() mvc.Result {
	return mvc.View{
		Code: iris.StatusBadRequest,
		Err:  fmt.Errorf("custom error"),
	}
}

func (c *controller) HandleHTTPError(ctx iris.Context, statusCode mvc.Code) mvc.View {
	if err := ctx.GetErr(); err != nil {
		println("error:", err.Error())
	} else {
		println("error was nil")
	}

        return mvc.View{...}
}
```

**Comment by AlbinoGeek** [comment]
### Code
```golang
func (c *BaseController) HandleHTTPError(ctx iris.Context, code mvc.Code, mErr mvc.Err) mvc.Result {
	view := mvc.View{Code: int(code)}
	golog.Warnf("HandleHTTPError executed:\n\tmvc.Code = %d\n\tctx.StatusCode = %d", view.Code, ctx.GetStatusCode())

	if view.Code == 200 {
		return nil
	}

	golog.Warnf("ctx.GetErr() = %v, mvc.Err = %v", ctx.GetErr(), mErr)
}

func (c *UnauthorizedUserController) GetLogin(ctx iris.Context) mvc.Result {
	return mvc.View{
		Code: iris.StatusOK,
		Err:  errors.New("login error"),
		Name: "user/login.html",
	}
}
```

### Results
```
[WARN] 2020/08/31 15:16 HandleHTTPError executed:
        mvc.Code = 400
        ctx.StatusCode = 400
[WARN] 2020/08/31 15:16 ctx.GetErr() = <nil>, mvc.Err = <nil>
```

Errors always trigger 400s for me, with no error returned.

**Comment by AlbinoGeek** [comment]
Okay so...

Errors passed in via `errors.New(...)` work, but passing an error created by something else does not.

I cannot easily reproduce this anymore.

**Comment by kataras** [comment]
I see, but, if there is an Error on mvc.View and Code is not an http error code then it changes to 400, this is intentionally. Let me check that when I come back to my office

**Comment by AlbinoGeek** [comment]
This code always makes the error go through:

```golang
func ErrView(err error, reason string) mvc.Result {
	golog.Warnf("%s: %v", reason, err)
	return mvc.View{
		Code: iris.StatusInternalServerError,
		Err:  errors.New(reason),
	}
}
```

However, code such as this (passing errors directly), does not:
This results in the output: `ctx.GetErr() = <nil>, mvc.Err = <nil>`

```golang
	p, err := goth.GetProvider(provider)
	if err == nil {
		sess, err := p.BeginAuth(SetState(ctx))
		if err == nil {
			url, err := sess.GetAuthURL()
			if err == nil {
				session := sessionManager.Start(ctx)
				session.Set(provider, sess.Marshal())
				ctx.Redirect(url, iris.StatusTemporaryRedirect)
				return nil
			}
		}
	}

	return mvc.View{
		Code: iris.StatusBadRequest,
		Err:  err,
	}
```

**Comment by kataras** [comment]
@AlbinoGeek the problem is not Iris... it's inside the go code look:

```go
sess, err := p.BeginAuth(SetState(ctx))
url, err := sess.GetAuthURL()
```

**This lines override the p, err := and so err after the if statements is always nil even if u got an error inside your if statements...*

Change that to:

```go
	p, err := goth.GetProvider(provider)
	if err == nil {
		sess, authErr := p.BeginAuth(SetState(ctx))
		if err == nil {
			url, authErr := sess.GetAuthURL() // <- HERE
			if err == nil {
				session := sessionManager.Start(ctx)
				session.Set(provider, sess.Marshal())
				ctx.Redirect(url, iris.StatusTemporaryRedirect)
				return nil
			} else {
                               err = authErr // <-HERE
                        }
		} else { err = authErr } // <-HERE
	}

	return mvc.View{
		Code: iris.StatusBadRequest,
		Err:  err,
	}
```

I don't like the code of that, please exit on errors as soon as possible (recommended go style of writing code)

**Comment by kataras** [comment]
@AlbinoGeek the problem is not Iris... it's inside the go code look:

```go
sess, err := p.BeginAuth(SetState(ctx))
url, err := sess.GetAuthURL()
```

**These lines override the `err` on the `p, err :=...` which is used inside your `mvc.View` result. So err after the if statements is always nil even if u got an error inside them.**

Change that to:

```go
	p, err := goth.GetProvider(provider)
	if err == nil {
		sess, authErr := p.BeginAuth(SetState(ctx)) // <- HERE
		if authErr == nil {
			url, authErr := sess.GetAuthURL() // <- HERE
			if authErr == nil {
				session := sessionManager.Start(ctx)
				session.Set(provider, sess.Marshal())
				ctx.Redirect(url, iris.StatusTemporaryRedirect)
				return nil
			} else {
                               err = authErr // <-HERE
                        }
		} else { err = authErr } // <-HERE
	}

	return mvc.View{
		Code: iris.StatusBadRequest,
		Err:  err,
	}
```

I don't like the code of that, please exit on errors as soon as possible (recommended go style of writing code)

**Comment by kataras** [comment]
@AlbinoGeek the problem is not Iris... it's inside the go code look:

```go
sess, err := p.BeginAuth(SetState(ctx))
url, err := sess.GetAuthURL()
```

**These lines do NOT set the `err` on the `p, err :=...` which is used inside your `mvc.View` result. Instead they are used as temporary values internally,  you cannot re-initialize a variable inside another block and expect the outer block to respect that change. So err after the if statements is always nil even if u got an error inside them.**

Change that to:

```go
	p, err := goth.GetProvider(provider)
	if err == nil {
		sess, authErr := p.BeginAuth(SetState(ctx)) // <- HERE
		if authErr == nil {
			url, authErr := sess.GetAuthURL() // <- HERE
			if authErr == nil {
				session := sessionManager.Start(ctx)
				session.Set(provider, sess.Marshal())
				ctx.Redirect(url, iris.StatusTemporaryRedirect)
				return nil
			} else {
                               err = authErr // <-HERE
                        }
		} else { err = authErr } // <-HERE
	}

	return mvc.View{
		Code: iris.StatusBadRequest,
		Err:  err,
	}
```

I don't like the code of that, please exit on errors as soon as possible (recommended go style of writing code)

**Comment by AlbinoGeek** [comment]
Good catch.

Also, yeah... "idiomatic" go can be... very repetitive at times, which is why I end up doing this sometimes.

It becomes literally 3x longer -_-

```golang
	p, err := goth.GetProvider(provider)
	if err != nil {
		return mvc.View{
			Code: iris.StatusBadRequest,
			Err:  err,
		}
	}
	
	sess, err := p.BeginAuth(SetState(ctx))
	if err != nil {
		return mvc.View{
			Code: iris.StatusBadRequest,
			Err:  err,
		}
	}

	url, err := sess.GetAuthURL()
	if err != nil {
		return mvc.View{
			Code: iris.StatusBadRequest,
			Err:  err,
		}
	}

	session := sessionManager.Start(ctx)
	session.Set(provider, sess.Marshal())
	ctx.Redirect(url, iris.StatusTemporaryRedirect)
	return nil
```

I swear Golang defeats DRY sometimes. ( Don't Repeat Yourself ) -- with error checking, and still having no generics in 2020 , haha.

**Comment by kataras** [comment]
I agree @AlbinoGeek ... I'm waiting for those generics since 2016 🤕 but they will come eventually, Go team announced a good draft and examples some days ago.

About the code above, you can return an `err` directly, no need to wrap it through `mvc.View`
