### ISSUE TITLE
is CookieSameSite = context.CookieHTTPOnly right?

### ISSUE THREAD

**Issue by shengulong** [kataras/iris#1612]
1. file
https://github.com/kataras/iris/blob/master/aliases.go
2. line
402
3. question
is right below?	
CookieSameSite = context.CookieHTTPOnly
or below is right
CookieSameSite = context.CookieSameSite

**Comment by kataras** [comment]
It's `CookieSameSite` @shengulong, fixed with the latest commit. Thanks for that!
