### ISSUE TITLE
[Question] ReadForm error  

### ISSUE THREAD

**Issue by aveyuan** [kataras/iris#1618]
Hi, I found a bug,

Run the code 

```
package main

import (
	"fmt"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.Default()

	app.Get("/get", func(c iris.Context) {
		var form struct {
			Name string `form:"name" validate:"required"`
		}

		if err := c.ReadForm(&form); err != nil {
			c.WriteString("read is err" + err.Error())
			return
		}
		c.WriteString(fmt.Sprintf("name is :%v", form.Name))
	})

	app.Listen(":8099")
}

```

- Setup1:

![image](https://user-images.githubusercontent.com/10907648/92453839-55acf780-f1f2-11ea-9c77-8c43feb0f8aa.png)

- Setup2:
![image](https://user-images.githubusercontent.com/10907648/92453957-842ad280-f1f2-11ea-828f-b99cbb960b79.png)

Look at is OK, not Error.

- Setup3:
![image](https://user-images.githubusercontent.com/10907648/92454187-d3710300-f1f2-11ea-8340-ca39491004c4.png)
![image](https://user-images.githubusercontent.com/10907648/92454276-ea175a00-f1f2-11ea-9466-1864ba62e3ae.png)

can you see ?  I only read form field bind, but the error.

**Comment by tuhao1020** [comment]
@aveyuan you should use `ReadQuery` instead

```
app.Get("/get", func(ctx iris.Context) {
    var queryParams struct {
        Name string `url:"name,required"`
        Age int `url:"age"`
    }

    ctx.ReadQuery(&queryParams)
    ctx.JSON(queryParams)
})
```

**Comment by aveyuan** [comment]
> @aveyuan你应该`ReadQuery`改用
> 
> ```
> app.Get("/get", func(ctx iris.Context) {
>     var queryParams struct {
>         Name string `url:"name,required"`
>         Age int `url:"age"`
>     }
> 
>     ctx.ReadQuery(&queryParams)
>     ctx.JSON(queryParams)
> })
> ```

Thanks , I think form is right, becuse some times i will in url use some parm and form post value. url parse not right.

**Comment by kataras** [comment]
@aveyuan you can still use `ReadForm` but the error you receive is because on form (for **security reasons**) by-default we fire an error on unknown incoming data (e.g. age which was not part of your original struct). However, there is a way to just **ignore that error** and it's actually on the `read-form example`:

https://github.com/kataras/iris/blob/d6867e1f9e92c8c25314327b3a4174fd4a6f4d5c/_examples/request-body/read-form/main.go#L29-L36
