### ISSUE TITLE
[FEATURE REQUEST] will cli tools be released

### ISSUE THREAD

**Issue by lihaotian0607** [kataras/iris#1619]
A very good framework, I like it very much;
but every time I create a project, I have to plan it myself. Hope to release cli tool to create api or web mvc directory structure, similar to bee cli tool

**Comment by kataras** [comment]
Bet @lihaotian0607. Check out the: https://github.com/kataras/iris-cli 😇

**Comment by lihaotian0607** [comment]
ok, thank you very much for your answer  ☕️

**Comment by lihaotian0607** [comment]
> Bet @lihaotian0607. Check out the: https://github.com/kataras/iris-cli 😇
> 
> It has project templates too. Will push one with MVC structure too. Features Frondend (npm) and backend(go) live reload through automatic websocket too 💪Try it and share your feedback with us!!

ok, thank you very much for your answer ☕️

**Comment by kataras** [comment]
You are welcome @lihaotian0607 don't hesitate to ask for more features. Here we always take care of users requests and bug reports.

**Comment by lihaotian0607** [comment]
> 欢迎您@ lihaotian0607不要犹豫，要求更多功能。在这里，我们始终会处理用户的请求和错误报告。

We are using websocket to make games. The `actor` model is very useful;
 but the iris framework is used to develop the web, so I didn't mention it;
It's great if it can be used

**Comment by kataras** [comment]
@lihaotian0607 of course you can use websocket with Iris. You can keep your own implementation or use the Iris' one. See https://github.com/kataras/iris/_examples/websocket and https://github.com/kataras/neffos/wiki

**Comment by kataras** [comment]
@lihaotian0607 The MVC template is pushed to the CLI:

```sh
go get -u github.com/kataras/iris-cli
mkdir myapp
iris-cli run --module=myapp mvc
```
