### ISSUE TITLE
Commit history?

### ISSUE THREAD

**Issue by admiralobvious** [kataras/iris#162]
Hi,

What happened to the commit history? It seems like it was blown up by c26668a.

**Comment by kataras** [comment]
I do it once on a while because .git repo is gone big, it was 12MB now it's ¬800kb, what's the problem of it?

**Comment by kataras** [comment]
@admiralobvious  I did it because .git repo gone big, it was 12MB now it's ¬800kb,  is it a problem for you or for your project? Now the repo is cleaned (and faster go getable)

**Comment by kataras** [comment]
He should see the stars then, the project is active for the last 3 months ( I describe its(iris) birthday on the gitbook also ), don't hesitate to ask again, thanks you!

**Comment by raitucarp** [comment]
@kataras thanks for your explanation, but you should put your reason above in readme. Because usually commit count is another metric to measure how active an open source project is.

**Comment by kataras** [comment]
@raitucarp you have right, done
