### ISSUE TITLE
Views FileSystem (2)

### ISSUE THREAD

**Issue by bsed** [kataras/iris#1620]
**Describe the bug**
➜ go get -u -v   
the following error occurred

**Expected behavior**
```
github.com/kataras/iris/v12/view
# github.com/kataras/iris/v12/view
../pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200809192844-da029d6f3722/view/blocks.go:76:37: undefined: blocks.AssetFunc
../pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200809192844-da029d6f3722/view/blocks.go:76:66: undefined: blocks.AssetNamesFunc
../pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200809192844-da029d6f3722/view/blocks.go:77:10: s.Engine.Assets undefined (type *blocks.Blocks has no field or method Assets)
```

 - OS: [mac]

**iris.Version**
 v12 v12.1.8

**Comment by AlbinoGeek** [comment]
Could you please show the import lines for `blocks`, to know which version you are using?
Otherwise, the version lines referring to `iris` and `blocks` within your `go.mod` file?

**Comment by kataras** [comment]
@bsed duplicate of: https://github.com/kataras/iris/issues/1615

There is not bug, all view engines now can accept either a `string` like before or an `http.FileSystem`, so `Assets` functions are useless now that you can just bind the `AssetFile()` from latest go-bindata's release. (See details on the [examples](https://github.com/kataras/iris/tree/master/_examples/view) and the issue above.)

**Comment by kataras** [comment]
@bsed duplicate of: https://github.com/kataras/iris/issues/1615

There is no bug at all here. You using the `master` development branch, which is expected to have features going on until the final release (always read [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) file before upgrade) All view engines now can accept either a `string` like before or an `http.FileSystem`, so `Assets` functions are useless now that you can just bind the `AssetFile()` from latest go-bindata's release. (See details on the [examples](https://github.com/kataras/iris/tree/master/_examples/view) and the issue above.)

**Comment by bsed** [comment]
tks

**Comment by kataras** [comment]
You are welcome @bsed 🦾
