### ISSUE TITLE
[BUG] `cache.Handler` doesn't distinguish between methods on same path

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1621]
## Summary
`cache.Handler(time.Minute)` meant a `POST`ed Contact Form returned the empty/unfilled `GET` handler from cache!

The `POST` handler was not executed, if the `GET` handler has been reached within the same cache time (Minute)

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.7 linux/amd64|
|Iris|master 333be42|
|Kernel|5.8.4-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Console Output

```bash
[INFO] 2020/09/10 07:18 200 239.519µs [REDACTED] POST /contact
#    ------------------ ^^^
#    should have been a 500 if the POST handler was executed
```

## Code

```golang
func (c *PublicController) BeforeActivation(b mvc.BeforeActivation) {
	b.Router().Use(cache.Handler(time.Minute))
}

func (c *PublicController) GetContact(ctx iris.Context) mvc.Result {
	golog.Warn("Sanity Check: This is the GET Handler")
	return mvc.View{
		Code: iris.StatusOK,
		Name: "contact.html",
	}
}

func (c *PublicController) PostContact(ctx iris.Context) mvc.Result {
	golog.Warn("Sanity Check: This is the POST Handler")
	return mvc.View{
		Code: iris.StatusInternalServerError,
		Text: "It's a bug if you DON'T see this.",
	}
}
```

**Comment by kataras** [comment]
Oh thanks @AlbinoGeek, this is fixed now. Also, now you have the ability to set the cache entry key/identifier with `cache.WithKey(string) iris.Handler` (use as middleware) or `cache/client.SetKey(iris.Context, string)`. [Example](https://github.com/kataras/iris/blob/master/_examples/response-writer/cache/simple/main.go) has been updated too.
