### ISSUE TITLE
[IMPROVEMENT] Replace string concatenation with use of `strings.Builder`

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1622]
## Summary

There are multiple places (I only noticed because of the latest commit) within the framework that strings are concatenated, such as code in handlers and other hot paths. Not only can this cause extra allocations (and therefore memory leaks), but it's also a painfully slow way to marry said strings together.

## Benchmark

While this is a naive benchmark (extraneous function calls, etc.) -- I have made sure to treat each case equally, and the winner in all cases is using a `strings.Builder` that you immediately throw away upon competing use. It is not worth saving them for re-use (unlike `bytes.Buffer` saw benefit back before go version `1.10` did.)

### Result

```
goos: linux
goarch: amd64
pkg: rethunk.tech/website
BenchmarkConcatString2-8          	20119435	        65.5 ns/op	       2 B/op	       1 allocs/op
BenchmarkJoinString2-8            	28344862	        42.3 ns/op	       2 B/op	       1 allocs/op
BenchmarkBuilderString2-8         	25445076	        49.6 ns/op	       8 B/op	       1 allocs/op
BenchmarkSharedBuilderString2-8   	23063916	        50.7 ns/op	       8 B/op	       1 allocs/op
BenchmarkConcatString3-8          	11384996	        108 ns/op	       6 B/op	       2 allocs/op
BenchmarkJoinString3-8            	21939157	        54.9 ns/op	       3 B/op	       1 allocs/op
BenchmarkBuilderString3-8         	21813850	        55.6 ns/op	       8 B/op	       1 allocs/op
BenchmarkSharedBuilderString3-8   	22096008	        56.9 ns/op	       8 B/op	       1 allocs/op
BenchmarkConcatString4-8          	 7650967	        158 ns/op	      12 B/op	       3 allocs/op
BenchmarkJoinString4-8            	17535133	        67.2 ns/op	       4 B/op	       1 allocs/op
BenchmarkBuilderString4-8         	20214960	        60.4 ns/op	       8 B/op	       1 allocs/op
BenchmarkSharedBuilderString4-8   	19112235	        62.7 ns/op	       8 B/op	       1 allocs/op
BenchmarkConcatString5-8          	 6040909	        199 ns/op	      16 B/op	       4 allocs/op
BenchmarkJoinString5-8            	14912396	        82.5 ns/op	       5 B/op	       1 allocs/op
BenchmarkBuilderString5-8         	17076465	        69.6 ns/op	       8 B/op	       1 allocs/op
BenchmarkSharedBuilderString5-8   	16964444	        69.6 ns/op	       8 B/op	       1 allocs/op
PASS
ok
```

#### Reading Results

Let's break down the last set of results, where I compared 4 methods of bringing 15 independent strings together. I've highlighted the most optimal method given each performance metric, be it the nanoseconds each operation took, or the memory allocation per operation.

|Function Name|ops|ns/op|B/op|allocs/op|
|---|---|---|---|---|
|BenchmarkConcatString15|1492912|785 ns/op|144 B/op|14 allocs/op
|BenchmarkJoinString15|5680020|211 ns/op|**16 B/op**|**1 allocs/op**
|BenchmarkBuilderString15|6565437|**183 ns/op**|24 B/op|2 allocs/op
|BenchmarkSharedBuilderString15|5645655|211 ns/op|24 B/op|2 allocs/op

Here we find that if all the strings are known ahead of time, `strings.Join(..., "")` actually provides us with the most optimal memory allocations, while maintaining a very low time per operation (of only `211 ns`) --. In addition, even if the strings are not all known at one time, such as appending over the course of a function's body, we receive a further speed improvement (down to only `183 ns`) when using `strings.Builder`.

Concatenation is absolutely the slowest means, whether you are bringing 2 or 15 strings together.

### Code

```golang
package main

import (
	"strings"
	"testing"
)

func BuilderString(keys ...string) string {
	var b strings.Builder
	for i := 0; i < len(keys); i++ {
		b.WriteString(keys[i])
	}
	return b.String()
}

func ConcatString(keys ...string) string {
	var s string
	for i := 0; i < len(keys); i++ {
		s += keys[i]
	}
	return s
}

func JoinString(keys ...string) string {
	var s string
	s = strings.Join(keys, "")
	return s
}

func SharedBuilderString(keys ...string) string {
	Builder.Reset()
	for i := 0; i < len(keys); i++ {
		Builder.WriteString(keys[i])
	}
	return Builder.String()
}

var Builder strings.Builder
var Result string

func BenchmarkConcatString2(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = ConcatString("a", "b")
	}
	Result = result
}

func BenchmarkJoinString2(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = JoinString("a", "b")
	}
	Result = result
}

func BenchmarkBuilderString2(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = BuilderString("a", "b")
	}
	Result = result
}

func BenchmarkSharedBuilderString2(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = SharedBuilderString("a", "b")
	}
	Result = result
}

func BenchmarkConcatString3(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = ConcatString("a", "b", "c")
	}
	Result = result
}

func BenchmarkJoinString3(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = JoinString("a", "b", "c")
	}
	Result = result
}

func BenchmarkBuilderString3(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = BuilderString("a", "b", "c")
	}
	Result = result
}

func BenchmarkSharedBuilderString3(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = SharedBuilderString("a", "b", "c")
	}
	Result = result
}

func BenchmarkConcatString4(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = ConcatString("a", "b", "c", "d")
	}
	Result = result
}

func BenchmarkJoinString4(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = JoinString("a", "b", "c", "d")
	}
	Result = result
}

func BenchmarkBuilderString4(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = BuilderString("a", "b", "c", "d")
	}
	Result = result
}

func BenchmarkSharedBuilderString4(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = SharedBuilderString("a", "b", "c", "d")
	}
	Result = result
}

func BenchmarkConcatString5(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = ConcatString("a", "b", "c", "d", "e")
	}
	Result = result
}

func BenchmarkJoinString5(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = JoinString("a", "b", "c", "d", "e")
	}
	Result = result
}

func BenchmarkBuilderString5(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = BuilderString("a", "b", "c", "d", "e")
	}
	Result = result
}

func BenchmarkSharedBuilderString5(b *testing.B) {
	var result string
	for n := 0; n < b.N; n++ {
		result = SharedBuilderString("a", "b", "c", "d", "e")
	}
	Result = result
}
```

**Comment by kataras** [comment]
@AlbinoGeek  I am aware of all these but they are not used in `hot paths` as far as I know, can you point me some code's file:line links?

**Comment by kataras** [comment]
@AlbinoGeek  I am aware of all these e.g from latest commits:  https://github.com/kataras/iris/blob/b77227a0f965e031507701901eb0b375a6483386/middleware/accesslog/log.go#L94-L126

is written that way, router internals also don't use string concat at all, so they are not used in `hot paths` so much, except little places, as far as I know, can you point me some code's file:line links or better **prepare a Pull Request**? But please, mind the **readability** too before proceed with it.

**Comment by AlbinoGeek** [comment]
Because of the **4th** note on https://medium.com/@thuc/8-notes-about-strings-builder-in-golang-65260daae6e9 , the `strings.Builder` is even more efficient than `bytes.Buffer` -- which is used in some places. I will definitely have a look through and prepare PRs for things I find of significant improvement :)

**Comment by kataras** [comment]
Yes strings Builder introduced in the latest go versions. If you think good canditates for change please do so, and always test current examples/test code that uses a particular code to make sure we don't break anything hard to be found later on. Thanks @AlbinoGeek !

**Comment by kataras** [comment]
@AlbinoGeek did you find any spots for that one or we should close it?

**Comment by AlbinoGeek** [comment]
Will update this sometime in the near future (less than a week) -- wrote a program that analyzes Golang sources, finding variables that contain more than 2 non-const concatenations in the same scope (ignores const since those are inlined by the compiler) -- to analyze `iris` and a number of other projects I had -- does a benchmark w/ before and after, and shows a diff for easy implementation.

Just have to finish off the code generation part (there were some edge-cases with cross-package variables.)

**Comment by kataras** [comment]
That sounds amazing @AlbinoGeek, good job, let's see its usage!
