### ISSUE TITLE
The color in your website is not handsome for eyes

### ISSUE THREAD

**Issue by mankeheaven** [kataras/iris#1623]
https://www.iris-go.com/docs#/
Css colors are '#505d6b', '#34495e', '#525252', it's very uncomfortable for a long looking
could you change some color like '#000' or other eye-catching and comfortable colors, please ?

**Comment by kataras** [comment]
Yes I was thinking of using a more "darker" theme there. I am on it thanks for your comment @mankeheaven

**Comment by kataras** [comment]
OK Updated :) Do you like it now?

![image](https://user-images.githubusercontent.com/22900943/92863902-2d491700-f405-11ea-8141-075faee2f18a.png)

**Comment by AlbinoGeek** [comment]
I like, it's much closer to what my browser already displayed (I use DarkReader, haha.)

**Comment by kataras** [comment]
Yeah the funny part is that yesterday, when I went to sleep I was thinking of changing the colors, and when I woke up I saw that issue :P

**Comment by mankeheaven** [comment]
so cool !!!
I like it
and are there any other themes we can choose,  like sublime or material theme, maybe someone else like those classic themes

**Comment by kataras** [comment]
I would like to keep that page loading as fast as possible, by loading various themes (big css files) we will introduce unnecessary load time and let's keep things simple, I don't think someone will want to change that theme :smile:

**Comment by mankeheaven** [comment]
ok, it is great
looking forward new website theme

**Comment by kataras** [comment]
It's already live, hit control/cmd + F5 to reload without cache and you should be able to see the theme applied
