### ISSUE TITLE
request log performance

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1624]
I did a simple test using wrk.
The performance of the version with request log disabled is more than twice that of the version that is not disabled

**request log enabled (Async  = true)** 
```
➜  ~ wrk -t5 -c20 -d10s http://localhost:8080/test --latency
Running 10s test @ http://localhost:8080/test
  5 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.87ms    3.42ms  66.96ms   90.88%
    Req/Sec     4.70k     1.17k   21.82k    82.24%
  Latency Distribution
     50%  627.00us
     75%    1.87ms
     90%    4.91ms
     99%   16.83ms
  234343 requests in 10.10s, 27.04MB read
Requests/sec:  23202.61
Transfer/sec:      2.68MB
```

**request log disabled**
```
➜  ~ wrk -t5 -c20 -d10s http://localhost:8080/test --latency
Running 10s test @ http://localhost:8080/test
  5 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   722.19us    1.47ms  29.21ms   93.17%
    Req/Sec    10.23k     1.12k   17.15k    83.10%
  Latency Distribution
     50%  316.00us
     75%  553.00us
     90%    1.51ms
     99%    7.87ms
  511871 requests in 10.10s, 59.07MB read
Requests/sec:  50679.52
Transfer/sec:      5.85MB
```

**Comment by kataras** [comment]
Yes @tuhao1020 that's totally expected and acceptable, it's not Iris problem, accesslog is written to be as fast as possible but you have to understand if you have the `RequestBody, ResponseBody, BytesReceived, BytesSent` fields to true you will have to accept the cost of them, we read the request body and record response data sent, we also calculate all headers received and sent if these fields are enabled. If you read the documentation of the `accesslog.AccessLog` structure, it explicitly say that you must turn off these fields if you care about performance.

**Comment by kataras** [comment]
Yes @tuhao1020 that's totally expected and acceptable, it's not Iris problem, accesslog is written to be as fast as possible but you have to understand if you have the `RequestBody, ResponseBody, BytesReceived, BytesSent` fields to true you will have to accept the cost of them, we read the request body and record response data sent, we also calculate all headers received and sent if these fields are enabled. If you read the documentation of the `accesslog.AccessLog` structure, it explicitly say that you must turn off these fields if you care about performance. Also `Async == true` fires a new goroutine on each log and **clones the Context (this operation is expensive)** (also in godocs).

**Comment by kataras** [comment]
Yes @tuhao1020 that's totally expected and acceptable, it's not Iris problem, accesslog is written to be as fast as possible but you have to understand if you have the `RequestBody, ResponseBody, BodyMinify, BytesReceived, BytesSent` fields set to true you will have to accept the cost of them, we read the request body and record response data sent, we also calculate all headers received and sent if these fields are enabled. If you read the documentation of the `accesslog.AccessLog` structure, it explicitly say that you must turn off these fields if you care about performance. Also `Async == true` fires a new goroutine on each log and **clones the Context (this operation is expensive)** (also in godocs). Also if you wrap the **file with** the **third-party log roration library** it surely adds more delay, you may want to check the results without it for more acquirate results.

Here are my tests:

```go
ac := accesslog.File("./access.log")
// default values
ac.RequestBody = true
ac.ResponseBody = true
ac.BytesReceived = true
ac.BytesSent = true
ac.Async = false
```
```sh
Bombarding http://localhost:8080 for 10s using 20 connection(s)
[=================================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     69596.59    3761.50   80296.39
  Latency      285.66us    41.29us    14.85ms
  Latency Distribution
     50%     0.00us
     75%     1.00ms
     90%     1.00ms
     95%     1.00ms
     99%     1.00ms
  HTTP codes:
    1xx - 0, 2xx - 695920, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    11.95MB/s
```
```go
ac := accesslog.File("./access.log")

ac.RequestBody = true
ac.ResponseBody = true
ac.BytesReceived = true
ac.BytesSent = true

ac.Async = true
```
```sh
Bombarding http://localhost:8080 for 10s using 20 connection(s)
[=================================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     76889.50    4269.54   91050.46
  Latency      258.34us    36.98us     9.00ms
  Latency Distribution
     50%     0.00us
     75%     0.91ms
     90%     1.00ms
     95%     1.00ms
     99%     1.00ms
  HTTP codes:
    1xx - 0, 2xx - 768947, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    13.20MB/s
 ```
```go
ac := accesslog.File("./access.log")
ac.RequestBody = false
ac.ResponseBody = false
ac.BytesReceived = false
ac.BytesSent = false

ac.Async = false
```

```sh
Bombarding http://localhost:8080 for 10s using 20 connection(s)
[=================================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     93252.46    4666.22  105907.41
  Latency      212.64us    26.62us     8.47ms
  Latency Distribution
     50%     0.00us
     75%     0.00us
     90%     1.00ms
     95%     1.00ms
     99%     1.00ms
  HTTP codes:
    1xx - 0, 2xx - 932603, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    16.01MB/s
```

**Logger Disabled**

```sh
Bombarding http://localhost:8080 for 10s using 20 connection(s)
[=================================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec    119900.76    5651.55  138452.08
  Latency      165.20us    16.74us     6.97ms
  Latency Distribution
     50%     0.00us
     75%     0.00us
     90%     1.00ms
     95%     1.00ms
     99%     1.00ms
  HTTP codes:
    1xx - 0, 2xx - 1199092, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    20.58MB/s
```

**Comment by tuhao1020** [comment]
@kataras sorry for late reply! My idea is similar to yours，I tried to pass `bufio.NewWriter(rotatelogs)` to `accesslog.New` function yesterday, but there're some errors, I have upgraded to the latest commit,  it's ok now and performance has been improved.

**Comment by kataras** [comment]
Yes flushers were not recorded yesterday (because I was thinking to implement an internal buffer but there is no need for that). This is fixed now, happy to see that you see performance benefit, you should also check the updated JSON formatter, it's almost as fast as the raw one
