### ISSUE TITLE
Is there a way to "Read Text" - No unmarshalling?

### ISSUE THREAD

**Issue by chrismalek** [kataras/iris#1626]
I may have missed this in the documents and source code.

I have a handler that will accept variable data. It is XML but the contents will vary wildly. I really just want to the read the entire post body as `text` and write it to a file. I don't want IRIS to unmarshall it into a struct. The file contents will be handled out of the request/response lifecycle in a queue. I just want to accept whatever is posted and push it to cloud storage without any sort of processing on the body.

I can't figure out a way to just read the entire body as text and write it to a file. It seems the `ReadyBody` method defaults to JSON and I don't see a text branch of the code.    

Is there a method I am not seeing on `iris.Context`?

```GO
func inboundDataHandler(ctx iris.Context) {

	var payload string

	err := ctx.ReadBody(&payload)

	if err != nil {
		ctx.StopWithProblem(iris.StatusBadRequest,
			iris.NewProblem().Title("Parser issue").Detail(err.Error()))
		return
	}
// ....snip....
}
```

**Comment by kataras** [comment]
@chrismalek `ctx.GetBody()`

**Comment by chrismalek** [comment]
Thanks..I don't know how i missed that.

**Comment by kataras** [comment]
No worries @chrismalek, don't hesitate to ask for more in the future. Have a nice one!
