### ISSUE TITLE
[BUG] `schema: invalid path` for `PostValue*`

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1628]
## Summary

I'd like to have some paths that accept optional parameters via POST values, within an MVC controller.

Unfortunately, the MVC Controller itself is throwing the error to the user's browser, without me doing so.

And while I can pass an app-wide option to disable this check, I cannot do it per controller or route.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.7 linux/amd64|
|Iris|master 65b7983|
|Kernel|5.8.4-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Code

```golang
func (c *SampleController) PostTest(ctx iris.Context) mvc.Result {
	if b, err := ctx.PostValueBool("clear"); err == nil && b {
		// ...
	}
	if b, err := ctx.PostValueBool("start"); err == nil && b {
		// ...
	}
	
	return nil
}
```

### HTTP Result

```http
content-length: 28
content-type: text/plain; charset=utf-8
status: 400
x-request-id: af7e10f8-ab80-4ffa-9daa-59a25a77238f

schema: invalid path "clear"
```

**Comment by AlbinoGeek** [comment]
I actually couldn't find any MVC examples that showed how to take in `Post` data, other than `PostBy` params or form binding (non-MVC) -- nothing showing how to take up individual parameters that may or may not be provided (completely optional ones.)

**Comment by kataras** [comment]
@AlbinoGeek  The form is protected by default, and it does return an error on unknown incoming data, it can be ignored through `iris.IsErrPath(err)`: https://github.com/kataras/iris/blob/7431fcc9cf00d82fab726c19c0a73577032ce85d/_examples/request-body/read-form/main.go#L29-L36

> I actually couldn't find any MVC examples that showed how to take in Post data

You should be able to just accept the struct in your method's input arguments, just like a JSON request is binded in MVC. If the requested content-type is a form one, then it should bind, otherwise it's a bug but we [have tests](https://github.com/kataras/iris/blob/7431fcc9cf00d82fab726c19c0a73577032ce85d/hero/handler_test.go#L151-L154) and they are passing.

Maybe you try to read the body more than once without the [WithoutBodyConsumptionOnUnmarshal](https://github.com/kataras/iris/blob/7431fcc9cf00d82fab726c19c0a73577032ce85d/_examples/request-body/read-many/main.go#L32) option?

**Comment by kataras** [comment]
@AlbinoGeek I see that your real question is "how can I ignore the error as we do in handler with iris.IsErrPath". You know that you can handle binding and method errors through a `HandleError(Context, error)` controller method, however until now, you couldn't "skip an error", now you can, just don't `ctx.Stop/StopWithXXX` and the error will be ignored, example:


```go
func (c *controller) HandleError(ctx iris.Context, err error) {
	if iris.IsErrPath(err) {
		return // continue.
	}

	ctx.StopWithError(iris.StatusBadRequest, err)
}
```

Now you have a way to control all errors in one spot, and skip depending on the request and e.t.c.

**Comment by AlbinoGeek** [comment]
My example code does not seem very dissimilar from the example you used
```golang
// yours
func (c *controller) PostTest(form registerForm) string {}

// mine
func (c *SampleController) PostTest(ctx iris.Context, args struct{
	Clear bool `form:"clear",url:"clear"`
	Start bool `form:"start",url:"start"`
}) mvc.Result {}
```

Except that it was an anonymous struct (perhaps inhibiting binding?) I do not read the body anywhere, if I did, then the error itself would not show (ironically) because the body would be empty. However, I tried binding an actual struct just like in your example, and that also fails with the same error.

```golang
type test struct {
	Action string `form:"action"`
}

func (c *SampleController) PostTest(ctx iris.Context, args test) mvc.Result {}
```

`schema: invalid path "action"`

**Comment by AlbinoGeek** [comment]
In **a completely different application**, the following works:

```golang
type ContactForm struct {
	Name     string `json:"name" validate:"required,printascii,min=2"`
	Email    string `json:"email" validate:"required,email"`
	Company  string `json:"company" validate:"required,printascii,min=2"`
	Category uint8  `json:"category" validate:"gte=0,lte=11"`
	Message  string `json:"messages" validate:"required,min=4,max=16384"`
	Submit   string `json:"submit" validate:"-"`
}

func (c *PublicController) PostContact(ctx iris.Context) mvc.Result {
	form := ContactForm{}

	// decode POST request body and validate the input
	if err := ctx.ReadBody(&form); err != nil {
		if errs, ok := err.(validator.ValidationErrors); ok {
			// ...
}
```

I could make this using `ReadBody` too, but that's... it just seems like a very cumbersome pattern when you only want to read one or two optional values, in various parts of the Handler, v.s. taking in an actual form (think: action buttons, such as "edit", "enable", "disable", etc.)

**Comment by kataras** [comment]
@AlbinoGeek that should be fixed now based on the latest commit, the issue was that in your example you used a struct field, at my tests I used a method input argument.

**Comment by AlbinoGeek** [comment]
After updating to the latest commit, the following code now works (???)
```golang
func (c *DebugController) PostTest(ctx iris.Context) mvc.Result {
	if _, _, err := user.VerifyLogin(c.DB, ctx, c.Connection); err != nil {
		return err
	}

	if ctx.FormValue("action") == "clear" {
		// ...
	}
}
```

I have no idea why this works now, but it does, and I'm quite happy!
