### ISSUE TITLE
[FEATURE REQUEST] Add amber framework time

### ISSUE THREAD

**Issue by OpakAlex** [kataras/iris#1632]
Can you also add Amber framework time?) Just to be tolerant...

**Comment by kataras** [comment]
What is Amber framework time?

**Comment by OpakAlex** [comment]
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=json&c=6&d=9&o=e

**Comment by OpakAlex** [comment]
enjoy

**Comment by kataras** [comment]
What to enjoy and why did you open that issue here? If you want to advertise something please..at least pay us something

**Comment by kataras** [comment]
I see an irony here but let's move on. Please do not advertise things in Iris GitHub issue, at least show some love for the hard work we're doing. 

Nowo, to the point, If you are asking for benchmarks, you should open this issue or add PR about Iris MVC+ Amber MVC comparison at [TechEmpower/FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks) instead. If you don't do that, I am convinced that you are just trolling and that does not honor you as a human being.

**Comment by kataras** [comment]
I see an irony here but let's move on. Please do not advertise things in Iris GitHub issue, at least show some love for the hard work we're doing. 

**Now, to the point**, If you are asking for benchmarks, you should open this issue or add PR about Iris MVC+ Amber MVC comparison at [TechEmpower/FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks) instead. If you don't do that, I am convinced that you are just trolling and that does not honor you as a human being. 

I am waiting for your PR, enjoy :)
