### ISSUE TITLE
tunneling error: EOF

### ISSUE THREAD

**Issue by BruceChar** [kataras/iris#1634]
**Describe the bug**
I have install ngrok in my windows and set the path config.
When I run `app.Run(iris.Addr(":8081"), iris.WithTunneling)`, 
error occurs `Host: tunneling error: EOF`

I have run successfully sometime before(about month ago), this time it failed! Weried!
Is something problem with my local enviroment or? I have no idea!

**To Reproduce**
Just run the example.

**Expected behavior**
Expect the ngrok service up.

**Desktop (please complete the following information):**
 - OS: windows10 64bit

**iris.Version**
v12.1.9

**Additional context**
ngrok version: 2.3.35

**Comment by kataras** [comment]
Why closed so fast, didn't have ngrok in the $PATH?

**Comment by BruceChar** [comment]
> Why closed so fast, didn't have ngrok in the $PATH?

I have found the problem, I reset the authtoken it works!

**Comment by kataras** [comment]
Funny that didnt return a proper error, let's have that in mind. Thanks Bruce
