### ISSUE TITLE
jwt token refresh?

### ISSUE THREAD

**Issue by lihaotian0607** [kataras/iris#1635]
how to refresh the token

**Comment by kataras** [comment]
It's not hard, you just accept the existing token and set a new one.

**Comment by kataras** [comment]
If you still have trouble with that, just tell me what package you use, the iris-contrib/middleware/jwt (based on jwt-go) or the kataras/iris/middleware/jwt (based on go-jose, provides encryption too)? I can help you with an example.

**Comment by lihaotian0607** [comment]
🍺  thank you very much, I am using`kataras/iris/middleware/jwt`

**Comment by kataras** [comment]
Here you are: https://github.com/kataras/iris/blob/master/_examples/auth/jwt/refresh-token/main.go

**Comment by lihaotian0607** [comment]
> Here you are: https://github.com/kataras/iris/blob/master/_examples/auth/jwt/refresh-token/main.go

wow~~~;
 very efficient response, thank you very much, is there any way to sponsor it? I like this framework very much and I like the author’s attitude towards problems very much. I want to sponsor a little

**Comment by kataras** [comment]
Thanks @lihaotian0607, yes you can do it through https://www.iris-go.com/#ebookDonateForm or https://paypal.me/kataras or if you want to do monthly donations: https://github.com/sponsors/kataras

**Comment by lihaotian0607** [comment]
> 谢谢@ lihaotian0607，是的，您可以通过https://www.iris-go.com/#ebookDonateForm或[https://paypal.me/kataras进行，](https://paypal.me/kataras)或者如果您想每月进行捐赠：[https](https://github.com/sponsors/kataras) : [//github.com /赞助商/ kataras](https://github.com/sponsors/kataras)

ok

**Comment by lihaotian0607** [comment]
> > 谢谢@ lihaotian0607，是的，您可以通过[https://www.iris-go.com/#ebookDonateForm或[https://paypal.me/kataras进行，]（https://paypal.me/kataras）或者如果您想每月进行捐赠：[https]（https://github.com/sponsors/kataras）](https://www.iris-go.com/#ebookDonateForm%E6%88%96%5Bhttps://paypal.me/kataras%E8%BF%9B%E8%A1%8C%EF%BC%8C%5D(https://paypal.me/kataras)%E6%88%96%E8%80%85%E5%A6%82%E6%9E%9C%E6%82%A8%E6%83%B3%E6%AF%8F%E6%9C%88%E8%BF%9B%E8%A1%8C%E6%8D%90%E8%B5%A0%EF%BC%9A%5Bhttps%5D(https://github.com/sponsors/kataras))：[//github.com /赞助商/ kataras](https://github.com/sponsors/kataras)
> 
> 好

sorry, PayPal is temporarily unavailable in China! ! ! ☕️

**Comment by kataras** [comment]
@lihaotian0607 yes... I am aware of this, some Chinese people can donate from China through Paypal and some others can't. This is why I prepared this, can you try it? https://app.payhere.co/iris-go/e-book-1fba0f23-09a1-464d-b22f-453be7dc8efd

**Comment by lihaotian0607** [comment]
> @lihaotian0607 yes... I am aware of this, some Chinese people can donate from China through Paypal and some others can't. This is why I prepared this, can you try it? https://app.payhere.co/iris-go/e-book-1fba0f23-09a1-464d-b22f-453be7dc8efd

you may try a Bitcoin wallet, there are no restrictions anywhere! 🍮

**Comment by kataras** [comment]
@lihaotian0607 There is no restrictions in that form above, two people from China that couldn't donate before, like you, already donated using that link, I saw in my board that you tried to donate too, but failed 3 times, this is usually due to invalid form data. I don't have a BTC account anymore. But no worries my friend, I added you to the list to receive the book when it's ready and you can always contact me, in private, through https://chat.iris-go.com or [email](mailto:kataras2006@hotmail.com).

**Comment by lihaotian0607** [comment]
> @lihaotian0607 There is no restrictions in that form above, two people from China that couldn't donate before, like you, already donated using that link, I saw in my board that you tried to donate too, but failed 3 times, this is usually due to invalid form data. I don't have a BTC account anymore. But no worries my friend, I added you to the list to receive the book when it's ready and you can always contact me, in private, through https://chat.iris-go.com or [email](mailto:kataras2006@hotmail.com).

unfortunately, I tried several banks, but did not provide support!
