### ISSUE TITLE
[FEATURE REQUEST] jwt alternative

### ISSUE THREAD

**Issue by liuaiyuan** [kataras/iris#1637]
jwt has obvious defects, it cannot be controlled after being generated, cannot expire, and its length is too long.

Are there any plans to develop custom tokens (stored in redis memory database, etc.) to solve the problem of api sessions! can freely control the expiration time, the length will not be too long!

**Comment by kataras** [comment]
Hello @liuaiyuan I had working on a custom token protocol but in the end it looked exactly like JWT (without realazing it)...so I believe JWT is good for what it does. I think you want to use `sessions` instead, which you can save anything and without limits, you can also use **redis, memory database, badge, boltd** as you want :)

Examples: https://github.com/kataras/iris/tree/master/_examples/sessions/database

**Comment by liuaiyuan** [comment]
session can be used in web pages, but if used in mobile app, it will be a little difficult to operate!

**Comment by kataras** [comment]
But cookies can be stored within a webview similar to the way they are stored in a browser setting. What type of mobile application do you working on?

**Comment by tuhao1020** [comment]
@liuaiyuan  you can put the jwt into redis, and control the expiration in backend by your self.

**Comment by AlbinoGeek** [comment]
To be fair to both, `jwt` is a "classic" (old) methodology, but it still works quite well to this day. It is an industry standard when it comes to cloud orchestration and other Application Programming Interfaces used in the wild at major Enterprises and Small to Medium Businesses alike.

I, myself, prefer to use [encrypted sessions](https://github.com/iris-contrib/examples/blob/master/sessions/securecookie/main.go) that I control the references to within a shared database, such as [`redis`](https://docs.iris-go.com/iris/contents/sessions/database) or something else, which is cached between my web nodes using [`groupcache`](https://github.com/iris-contrib/examples/blob/master/database/mysql/cache/groupcache.go).

**Comment by liuaiyuan** [comment]
thanks everyone for answering @AlbinoGeek  @tuhao1020  @kataras

**Comment by kataras** [comment]
You are very welcomed @liuaiyuan. Dont hesitate to ask more here. Whats your final decision? Sessions with cookiejar attached to the client or JWT?

**Comment by liuaiyuan** [comment]
> You are very welcomed @liuaiyuan. Dont hesitate to ask more here. Whats your final decision? Sessions with cookiejar attached to the client or JWT?

```go
type Token struct {
	Ip        string `json:"ip"`
	UserId    int64  `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
}
```

```
prepared such a struct,the key is uuid v4,store to redis
```
