### ISSUE TITLE
access log content encoding error

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1638]
**code sample**
```go
log, _ := rotatelogs.New("./%Y%m%d%H.access.log", rotatelogs.WithRotationTime(time.Hour))
ac := accesslog.New(log)
ac.Async = true
ac.RequestBody = true
ac.ResponseBody = true
ac.BytesReceived = false
ac.BytesSent = false

app := iris.New()
app.UseRouter(ac.Handler)
app.UseRouter(recover2.New())

app.Get("/proxy", func(ctx iris.Context) {
      u, _ := url.Parse("http://p.3.cn/prices/mgets?skuId=100008146877")
      proxy := host.NewProxy("", u)
      proxy.Server.Handler.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
})

app.Run(iris.Addr(":8080"))
```
**log content:**
![image](https://user-images.githubusercontent.com/26807520/93583291-3b370300-f9d6-11ea-9e07-e7593f4d3451.png)

I guess the problem is that the reverse proxy uses gzip encoding, but it is not decoded when recording.

**Comment by AlbinoGeek** [comment]
Yeah, looks like it -- as the headers for the URL you showed look as follows:

```http
Content-Encoding: gzip
Content-Type: application/json;charset=utf-8
```

---

Also, what's `recover2` ?  I'm curious.

**Comment by tuhao1020** [comment]
@AlbinoGeek  it's an alias name for `recover` that auto generated by goland 😄

**Comment by kataras** [comment]
Hmm I tested it and un-compression was handled back then. Maybe this is caused because it's a proxy and it is not a compression added by Iris, so we have to check the request's Content-Encoding and un-compress? We also have to add a configuration field to allow end-developers to manage how the RequestBody is readen for any case too.

**Comment by kataras** [comment]
@tuhao1020 did you try to enable read compression?

```go
app.UseRouter(func(ctx iris.Context){
  ctx.CompressReader(true)
  ctx.Next()
})
```

**Comment by kataras** [comment]
OK I will add a proxy and accesslog example because I've seen some other mistakes in your code too.

**Comment by tuhao1020** [comment]
@kataras I add `ctx.CompressReader(true)` and then log content goes right. 
If I don't know the encoding of 3rd-party api,  can I always add this line of code?

**Comment by kataras** [comment]
Yes @tuhao1020 it's safe to add `app.Use(iris.Compression)` it will not compress if the client does not support it and it will not un-compress if the data (based on the sent header) are not compressed.

**Comment by tuhao1020** [comment]
@kataras totally understood! Thank you!

**Comment by kataras** [comment]
Yes, I am preparing an example and some new features for accesslog, currently you can skip or add fields to accesslog, to all instances of them but we don't have an easy way to pick one or more registered accessloggers in the same application to work on, at serve-time. Also you get an error if you try to read from closed body on accesslog, that is fixed too.

**Comment by kataras** [comment]
@tuhao1020 @AlbinoGeek Example of correct use of ProxyHandler. You should NOT create a new proxy instance on every request.: https://github.com/kataras/iris/blob/master/_examples/logging/request-logger/accesslog-proxy/main.go
