### ISSUE TITLE
func iris.Context.ReadForm unsupport get method

### ISSUE THREAD

**Issue by wtang-su** [kataras/iris#164]
The func BindForm in bindings/form.go line 390 confuse me. it visit query args on check post args block? plz check it, thanks!

**Comment by kataras** [comment]
No, query args are outside of the post arg's loop block  but inside if postargs > 0 block because we are searching for POST data, if we have post data then search for query args also ( its useful on some cases like ajax posting) did you understand or my eng are failed?

**Comment by max107** [comment]
> If your account is not fake, please star Iris if you liked so!

ROFL, bad strategy dude

**Comment by wtang-su** [comment]
I was thought the ReadForm func could read POST data AND GET data from request, but it's not read "GET data". change it to read the query args like postargs is work for me, thank you.

**Comment by wtang-su** [comment]
ohno, it's still unsupport read GET request. could you please add a func like ReadForm but search queryArgs only?

**Comment by kataras** [comment]
@wtang-su did you upgrade iris ` go get -u github.com/kataras/iris/iris` ?

**Comment by kataras** [comment]
@max107  You don't know whats happening and what propaganda some people do on Iris...anyway if I insulted someone I'm sorry...

**Comment by kataras** [comment]
@max107  If I insulted someone I'm sorry, believe me, this is not my intention

**Comment by wtang-su** [comment]
Yes i upgrade, 

> if reqCtx.PostArgs().Len() == 0 {
>      return ErrReadBody.With(ErrNoForm.Return())
> }

it doesn't work if i have a request only contains query args

**Comment by kataras** [comment]
You have absolute right, so you use method="GET" I will fix it right now
