### ISSUE TITLE
github.com/iris-contrib/swagger is too old 

### ISSUE THREAD

**Issue by ZRothschild** [kataras/iris#1640]
github.com/iris-contrib/swagger is too old ,Can't  adapt the iris v12, Please update it 。之前的swagger 已经不能适应现在的iris v12 版本了，希望可以更新一下，我需要您的帮忙，谢谢

**Comment by kataras** [comment]
It was updated 7 days ago: https://github.com/iris-contrib/swagger/blob/c8325a980f0fff30349f1999e1e3be1881e0698c/go.mod#L6. Compatible with v12.2.0-alpha. What do you mean?

**Comment by ZRothschild** [comment]
thanks it has been solved





------------------ Original ------------------
