### ISSUE TITLE
v12.2.0-alpha ctx.PostValueDefault bug

### ISSUE THREAD

**Issue by lb151** [kataras/iris#1645]
username = ctx.PostValueDefault("username", "")
password = ctx.PostValueDefault("password", "")
	
when params username and password is not send ,post form is empty ,bug:Trace: runtime error: index out of range [-1]

code:
values, err := ctx.PostValues(name)
	if err != nil {
		return def // it returns "def" even if it's empty here.
	}

	return values[len(values)-1]    <----------bug code

**Comment by kataras** [comment]
This is the same as https://github.com/kataras/iris/issues/1642. It's fixed. Try upgrade with `go get -u github.com/kataras/iris/v12@master`.

**Comment by lb151** [comment]
go get -u github.com/kataras/iris/v12@master
upgrade this version:
v12@v12.2.0-alpha.0.20200919221030-c2f9e57b84f9
the problem remained
