### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by lb151** [kataras/iris#1646]
![image](https://user-images.githubusercontent.com/44936369/94336837-b58c0680-0018-11eb-8085-fa3825caba09.png)

**Comment by lb151** [comment]
# github.com/kataras/iris/view
..\mod\rwx-api\pkg\mod\github.com\kataras\iris@v0.0.2\view\blocks.go:76:37: undefined: blocks.AssetFunc
..\mod\rwx-api\pkg\mod\github.com\kataras\iris@v0.0.2\view\blocks.go:76:66: undefined: blocks.AssetNamesFunc
..\mod\rwx-api\pkg\mod\github.com\kataras\iris@v0.0.2\view\blocks.go:77:10: s.Engine.Assets undefined (type *blocks.Blocks has no field or method Assets)

**Comment by AlbinoGeek** [comment]
Well, your version is the reason, you need to download it properly:

```golang
go get github.com/kataras/iris/v12@master
```

**Comment by kataras** [comment]
Hello @lb151,

You are using a feature that it's not available in your installed Iris version. Both [README.md](https://github.com/kataras/iris#-learning-iris) and https://www.iris-go.com/docs specifically gives the steps to download the latest version:

```sh
$ cd %YOUR_PROJECT%
$ go mod init %MODULE_NAME%
$ go get github.com/kataras/iris/v12@master # HERE, see the @master. It's important.
# OR if you want a tagged version:  @v12.2.0-alpha
```

It's not a bug, please read the [documentation](https://iris-go.com).

**Comment by lb151** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gerasimos (Makis) Maropoulos"<notifications@github.com&gt;; 
发送时间: 2020年9月26日(星期六) 下午5:21
收件人: "kataras/iris"<iris@noreply.github.com&gt;; 
抄送: "time flies"<120021382@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [kataras/iris] [BUG]why? (#1646)





 
Hello @lb151,
 
You are using a feature that it's not available in your installed Iris version. Both README.md and https://www.iris-go.com/docs specifically gives the steps to download the latest version:
 $ cd %YOUR_PROJECT% $ go mod init %MODULE_NAME% $ go get github.com/kataras/iris/v12@master # HERE, see the @master. It's important. # OR if you want a tagged version:  @v12.2.0-alpha
 
It's not a bug, please read the documentation.

**Comment by lb151** [comment]
when i install github.com/iris-contrib/middleware/cors or github.com/iris-contrib/middleware/jwt ,iris@master version also upgrade @v12.2.0-alpha

**Comment by lb151** [comment]
github.com/kataras/iris/view/blocks.go with github.com/kataras/blocks  version is inconsistent

**Comment by kataras** [comment]
> github.com/kataras/iris/view/blocks.go with github.com/kataras/blocks version is inconsistent

@lb151 Please import using `"github.com/kataras/iris/v12"`. With the **v12** suffix.

**Comment by DarkNeedle** [comment]
this issue still exist
