### ISSUE TITLE
yaag apidoc

### ISSUE THREAD

**Issue by ruanhanqin** [kataras/iris#1647]
**Describe the bug**
yaag apidoc can't work with v12 version

**iris.Version**
- e.g. v12.2.0-alpha or master

**Comment by kataras** [comment]
What's the problem @ruanhanqin? It runs fine here, go to [_examples/apidoc/yaag](https://github.com/kataras/iris/tree/master/_examples/apidoc/yaag), download the files and just run `go run main.go`, go to `http://localhost:8080/json` and you should see the `apidoc.html` `and apidoc.html.json` files generated:

![image](https://user-images.githubusercontent.com/22900943/94414012-7f6b9580-0184-11eb-9320-27c006da0050.png)
