### ISSUE TITLE
[BUG] misleading error messages on wrong layout path

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1650]
## Summary

Regarding either the `HTML` or `Blocks` template/view engines, if your `Layout` file could not be read, (such as a wrong path configured) the error delivered to the browser reads:

`layout 'index.html' does not exist`

Which is misleading, when it shows this regardless of what you have set (in my case, it was `base` for example.)

I would have expected to see: `layout 'base' does not exist` instead.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.9 linux/amd64|
|Iris|master f224ded|
|Kernel|5.8.10-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

**Comment by kataras** [comment]
@AlbinoGeek this only happens to the HTML Engine through a copy-paste of the error issue, which just solved locally, at the rest the correct name is shown up, are you sure it happens to Blocks? Can you copy-paste the code?

**Comment by AlbinoGeek** [comment]
The issue with `Blocks` was due to #1649 -- you are correct.

**Comment by kataras** [comment]
Fixed 👍
