### ISSUE TITLE
redis's "MacActive" affect the cocurrent of every request which need authorized

### ISSUE THREAD

**Issue by shengulong** [kataras/iris#1651]
OK the change has been done, redis has a `Timeout` option and a `MaxActive` connections for the pool now in-used, also fixed a bug on redis Clear() when it removed its session ID entry too which was an invalid oparation, the performance difference is still there, I can't do anything, this is redis' problem and probably advanced redis users can configure their services to overcome this problem, this has nothing to do with Iris and redis golang implementations.

_Originally posted by @kataras in https://github.com/kataras/iris/issues/1285#issuecomment-504659007_

**Comment by shengulong** [comment]
i use redis storing my session, but the "MaxActive" of redis configuration will limit my qps(query per second).

the maximal qps value is equal to the value of "MaxActive"

the key code:


`app.Use(Session)
db := redis.New(redis.Config{
		Network: "tcp",
		Addr:    config.RedisConfig.Addr,
		// Timeout:   time.Duration(30) * time.Second,
		MaxActive: 20,
		Password:  config.RedisConfig.Password,
		Database:  config.RedisConfig.Database,
		Prefix:    "sessionId:",
		Delim:     "-",
		Driver:    redis.Redigo(), // redis.Radix() can be used instead.
	})
	controllers.Sess.UseDatabase(db)`



`func Session(ctx iris.Context) {
	if ctx.Path() != "/api/user/login" {
		authorized := controllers.Sess.Start(ctx).Get(":authorized")
		privilege := controllers.Sess.Start(ctx).Get(":privilege")
		if authorized == nil || authorized == false {
			ctx.Application().Logger().Error(ctx.Path())
			ctx.StatusCode(401)
			return
		}
		{
			// 每次登录，会话持续的时间设置
			_ = controllers.Sess.UpdateExpiration(ctx, time.Duration(1)*time.Hour)
		}
	}
	ctx.Next()
}`

**Comment by shengulong** [comment]
realize it with pool will be better like below?


import "github.com/go-redis/redis/v8"
Rdb = redis.NewClient(&redis.Options{
		Addr:     config.RedisConfig.Addr,
		Password: config.RedisConfig.Password,
		DB:       cast.ToInt(config.RedisConfig.Database),
		PoolSize: datamodels.RedisPoolSize,
	})

**Comment by kataras** [comment]
> realize it with pool will be better like below?
> 
> import "github.com/go-redis/redis/v8"
> Rdb = redis.NewClient(&redis.Options{
> Addr: config.RedisConfig.Addr,
> Password: config.RedisConfig.Password,
> DB: cast.ToInt(config.RedisConfig.Database),
> PoolSize: datamodels.RedisPoolSize,
> })

Hello @shengulong,

This is entirely differnet library, we support redigo (most popular redis go package) and radix. They both support the `MaxActive` option, which is the **pool size** (if you see the [redigo](https://github.com/gomodule/redigo)'s codebase you will understand). Are you proposing of adding a **third driver as a builtin redis session database**?
