### ISSUE TITLE
iris can not start

### ISSUE THREAD

**Issue by lb151** [kataras/iris#1652]
![image](https://user-images.githubusercontent.com/44936369/94980948-bcf36880-0560-11eb-8868-05471484dc2a.png)
it awlays install this version github.com\kataras\iris@v0.0.2
![image](https://user-images.githubusercontent.com/44936369/94981033-8833e100-0561-11eb-8340-cd8e1d4f358a.png)
![image](https://user-images.githubusercontent.com/44936369/94981042-9da90b00-0561-11eb-8652-a43c087778e3.png)
version inconsistency,so can not start

**Comment by lb151** [comment]
![image](https://user-images.githubusercontent.com/44936369/94981080-dba62f00-0561-11eb-9a59-47f4435743a6.png)

**Comment by kataras** [comment]
@lb151 I told you, use `import "github.com/kataras/iris/v12"` NO `github.com/kataras/iris`

**Comment by kataras** [comment]
@lb151 This is the second time you forgot to use the correct import statement:/ use `import "github.com/kataras/iris/v12"` NO `github.com/kataras/iris`. I made a whole gif which is visible on README page too.

![](https://camo.githubusercontent.com/10a15dda451379f417c2c13560e02566f47d7179/68747470733a2f2f7777772e697269732d676f2e636f6d2f696d616765732f676966732f696e7374616c6c2d6372656174652d697269732e676966)

**Comment by lb151** [comment]
thanks!,i used your farmework nearly two years,maybe it's my version caching problem,waiting for stable version
