### ISSUE TITLE
Upgrade Error: websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by echobool** [kataras/iris#1654]
`
	ws := websocket.New(websocket.DefaultGorillaUpgrader, websocket.Events{
		websocket.OnNativeMessage: func(nsConn *websocket.NSConn, msg websocket.Message) error {
			log.Printf("Server got: %s from [%s]", msg.Body, nsConn.Conn.ID())

			ping := string(msg.Body)
			pong := strings.Replace(ping, "？", "！", len(ping))
			pong = strings.Replace(pong, "么", "", len(pong))

			mg := websocket.Message{
				Body:     []byte(pong),
				IsNative: true,
			}

			nsConn.Conn.Write(mg)

			return nil
		},
	})

	ws.OnConnect = func(c *websocket.Conn) error {
		log.Printf("[%s] Connected to server!", c.ID())
		return nil
	}

	ws.OnDisconnect = func(c *websocket.Conn) {
		log.Printf("[%s] Disconnected from server", c.ID())
	}

	ws.OnUpgradeError = func(err error) {
		log.Printf("Upgrade Error: %v", err)
	}

	// register the server on an endpoint.
	// see the inline javascript code i the websockets.html, this endpoint is used to connect to the server.
	app.Get("/answer", websocket.Handler(ws))

`

**Running error：Upgrade Error: websocket: request origin not allowed by Upgrader.CheckOrigin**

How should the code be configured

thanks

**Comment by kataras** [comment]
Hello @echobool, please take a look at this answer: https://github.com/kataras/neffos/issues/11#issuecomment-520689681
