### ISSUE TITLE
How do you registerView more different view engine ? 

### ISSUE THREAD

**Issue by 23233** [kataras/iris#1655]
### My project need django view engine and html engine , But now RegisterView just register one ?  If use more , Will prompt me : 
![image](https://user-images.githubusercontent.com/12870070/95472456-a496aa00-09b5-11eb-9124-bc7ba3aa3316.png)

**Comment by 23233** [comment]
Use v12.1.9 not problem , But I'm upgrade to v12.2.0 , this is problem!!!! @kataras 
Plz help me , thanks ~

**Comment by kataras** [comment]
@23233 This is not a bug, it has changed due to a recent **new** feature. Now you can register a View per Party(group of routes), so you don't need to register multi template under the same application in the same route level

**Comment by 23233** [comment]
God , this is so good, very good, thank you so fast reply my question , love you ~ so much !!!  @kataras

**Comment by kataras** [comment]
You are very welcomed @23233 don't hesitate to ask more in the future :heart:
