### ISSUE TITLE
How to parse b.handle ("get", "/ login.html ", "GetLogin").Name = "login"

### ISSUE THREAD

**Issue by 265525** [kataras/iris#1656]
I tried to parse the route name of the back-end route settings from Django's template language, but I failed {% URL "login"%} or {{urlpath "login"}}. What should I do?

**Comment by kataras** [comment]
Hello @265525,

Django has a different syntax to pass parameters inside a template function.

HTML:

```html
{{urlpath "my-page1"}}
```

Django:

```html
{{urlpath('my-page1')}}
```
