### ISSUE TITLE
[FEATURE REQUEST] Add RemoveHandler to Party

### ISSUE THREAD

**Issue by tuhao1020** [kataras/iris#1658]
I noticed that router can dynamically remove middleware, but `Party` has not this method.
```
func middleware(ctx iris.Context) {
    // [...]
}

func main() {
    app := iris.New()

    // Register the middleware to all matched routes.
    app.Use(middleware)

    // Handlers = middleware, other
    app.Get("/", index)

    // Handlers = other
    app.Get("/other", other).RemoveHandler(middleware)

   party := app.Party("/party)
   party.RemoveHandler(middleware)      // not supported
}
```

**Comment by kataras** [comment]
The `Route.RemoveHandler` added some days ago, I didn't find it useful for `Party` because Party has a `Reset` method too, but yes, if you just want to remove a single handler, it's a good idea to include that there. I am on it.

**Comment by kataras** [comment]
OK it's done :)
