### ISSUE TITLE
Email with Mail command

### ISSUE THREAD

**Issue by qskousen** [kataras/iris#166]
The new SMTP Email support in Iris is great, but it would also be good if we could send email through the Linux Mail command:
- If you have multiple programs that all send email, it is useful to have them all use the `mail` command so that you can change the configuration in one place if an SMTP password or address changes
- If you need to send just local mail instead of SMTP
- If the server that is running your Iris program is also your mail server

You should be able to do this with the exec.Command function (untested, thanks go to @ryanbyyc):

``` go
subject := "hallo from Iris"
to := "ryan@gmail.com"
message := "this is my test"
args := []string{"-s", subject, to}
cmd := exec.Command("mail", args...)
cmd.Stdin = bytes.NewBufferString(message)
stdout, err := cmd.Output()
if err != nil {
    panic(err)
    return
}
fmt.Printf("%s", stdout)
```

**Comment by kataras** [comment]
It's good idea but I have years to use linux in everyday jobs, 

I have only two questions:

- So the `iris.Config().Mail`it is not useful for linux when using `mail`command, right? because all configuration is already in your operating system's files.

 - Does the `mail` supports any type of message? (mime type in body for text/html encoding)[ I think yes but never tested it]

**Comment by kataras** [comment]
It's very good idea but I have years to use linux in everyday jobs, 

I have only two questions:

- So the `iris.Config().Mail`it is not useful for linux when using `mail`command, right? because all configuration is already in your operating system's files.

- Does the `mail` command supports any type of message? (mime type in body for text/html encoding)[ I think yes but never tested it]

**Comment by qskousen** [comment]
Correct, all of the configuration is in the system itself, so you don't need a config for that.

Second question: `mail -a "Content-type: text/html"`

**Comment by kataras** [comment]
Ok thanks you , a third question, so how should I know if user wants to use the linux command or smtp server? we should add a ` iris.Config().Mail.UseCommand = true`  or is there a way to detect it automatically ?

**Comment by qskousen** [comment]
There would be no way for automatic detection, since people might want to use SMTP even if they have the mail command set up on their server.

I guess I would suggest having a config option to use Mail command, and if it's set to that, then don't panic if they try to send an email without having the other options set as it does curently.

**Comment by kataras** [comment]
Yes that, ok then ` UseCommand ` will be the config field

**Comment by qskousen** [comment]
I have finally tested this. It does send the email, however:

- It does not use the FromAlias. It sends as the default user@server.

- It does not attach the body. It sends a blank message.

It looks like you intended to send the body through the buffer which makes sense but you never put the body into the buffer.

You can set a from address with mail by using:
`mail -aFrom:user@domain.tld`

**Comment by egorsmkv** [comment]
I do not understand why it should be added to Iris.Can you make some middleware popular library for sending mail?

**Comment by qskousen** [comment]
@egorsmkv I don't believe that would be a middleware... That would just be a library. Sending mail through the command line is a valid use case. 

@kataras I have finally got this working. I led you on the wrong path a little bit. Using just "mail" is a bad idea, the one to use is "sendmail". Once I figured that out, your suggested edit worked with a little tweaking:

```go
func (m *mailer) sendCmd(to []string, subject, body string) error {
        buffer := buf.Get()
        defer buf.Put(buffer)

        header := make(map[string]string)
        header["To"] = strings.Join(to, ",")
        header["Subject"] = subject
        header["MIME-Version"] = "1.0"
        header["Content-Type"] = "text/html; charset=\"utf-8\""
        header["Content-Transfer-Encoding"] = "base64"

        message := ""
        for k, v := range header {
                message += fmt.Sprintf("%s: %s\r\n", k, v)
        }
        message += "\r\n" + base64.StdEncoding.EncodeToString([]byte(body))
        buffer.WriteString(message)

        cmd := utils.CommandBuilder("sendmail", "-F", m.fromAddr.Name, "-f", m.fromAddr.Address, "-t")

        cmd.Stdin = buffer
        _, err := cmd.CombinedOutput()
        return err
}
```

Let me know what you think.

**Comment by kataras** [comment]
@qskousen if you tested that and it works, then this will be added on the next revision, thanks you!

@egorsmkv Mail is using the standard smtp package and has 2 funcs only, it is small no problem for iris. Useful because almost all web apps sends an e-mail, after registration for example

**Comment by qskousen** [comment]
@kataras sounds good, yes I tested it and it works good. Note again that it uses sendmail, and not mail.

**Comment by kataras** [comment]
@qskousen 

Done, remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

Read also the [HISTORY](https://github.com/kataras/iris/tree/master/HISTORY.md), thanks you!!
