### ISSUE TITLE
v12.1.8 package versioning func RegisterGroups not found

### ISSUE THREAD

**Issue by 2823669007** [kataras/iris#1663]
v12.1.8 package versioning func RegisterGroups not found

**Comment by kataras** [comment]
Hello @2823669007 The `RegisterGroups` function does exists in `v12.1.8` just take a look at the source file: https://github.com/kataras/iris/blob/v12.1.8/versioning/group.go#L159

I think you are not using `v12.1.8`. You are using the `master` branch which of, you don't need the `RegisterGroups` anymore, just `NewGroup` and that will return an instance which is a `Party` and you can register routes as usual. Just remove the `RegisterGroups` and you will be OK, the rest of your API should work as expected. Example at: https://github.com/kataras/iris/blob/master/_examples/routing/versioning/main.go
