### ISSUE TITLE
Zap question

### ISSUE THREAD

**Issue by ruanhanqin** [kataras/iris#1666]
v12.2.0-alpha   when use go.uber.org/zap log can't gracefully shutting down

**Comment by kataras** [comment]
Hello @ruanhanqin, can you share us a code example that can reproduce this issue please?

**Comment by ruanhanqin** [comment]
main.go :

var g errgroup.Group
var idleConnsClosed = make(chan struct{})

func startApp() error {
	app := iris.New()
	app.Use(recover.New())
	if conf.AppConfig.App.Debug {
		app.Use(logger.New())
		app.Logger().SetLevel("debug")
	}
	app.Validator = validator.New()

	iris.RegisterOnInterrupt(func() {
		timeout := 10 * time.Second
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		err := app.Shutdown(ctx)
		if err != nil {
			log.Logger.Error("Shutdown App Fatal", zap.Error(err))
		}

		close(idleConnsClosed)
	})

	api.SetupRouter(app)

	srv := &http.Server{
		Addr:           ":8080",
		Handler:        app,
		ReadTimeout:    10 * time.Second,
		WriteTimeout:   5 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}
	app.Configure(iris.WithPostMaxMemory(4096), iris.WithoutBodyConsumptionOnUnmarshal,
		iris.WithoutInterruptHandler, iris.WithoutServerError(iris.ErrServerClosed))

	err := app.Build()
	if err != nil {
		return err
	}

	return srv.ListenAndServe()
}

func main() {
	g.Go(startApp)
	<-idleConnsClosed
	if err := g.Wait(); err != nil {
		log.Logger.Fatal("Start App Server Fatal", zap.Error(err))
	}
}

log.go:

var Logger *zap.Logger

func init() {
	writeSyncer := getLogWriter()
	var core []zapcore.Core
	jsonEncoder := getJsonEncoder()
	jsonEncoderCore := zapcore.NewCore(jsonEncoder, writeSyncer, zapcore.DebugLevel)
	core = append(core, jsonEncoderCore)
	if conf.AppConfig.App.Debug {
		consoleEncoder := getJsonEncoder()
		consoleEncoderCore := zapcore.NewCore(consoleEncoder, zapcore.Lock(os.Stdout), zapcore.DebugLevel)
		core = append(core, consoleEncoderCore)
	}

	Logger = zap.New(zapcore.NewTee(core...), zap.AddCaller())
	cb, _ := json.Marshal(conf.AppConfig)
	Logger.Info("System Config", zap.String("configuration", string(cb)))
}

func getLogWriter() zapcore.WriteSyncer {
	directory, err := os.Getwd()
	if err != nil {
		panic(fmt.Errorf("get Directory Fatal, Err: %v", err))
	}

	logPath := directory + "/stream/logs/" + conf.AppConfig.Log.Base
	lumberJackLogger := &lumberjack.Logger{
		Filename:   logPath,
		MaxSize:    5,
		MaxBackups: 5,
		MaxAge:     30,
		Compress:   false,
	}
	return zapcore.AddSync(lumberJackLogger)
}

func getJsonEncoder() zapcore.Encoder {
	encoderConfig := zap.NewProductionEncoderConfig()
	encoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
	encoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder
	encoderConfig.EncodeCaller = zapcore.FullCallerEncoder

	return zapcore.NewJSONEncoder(encoderConfig)
}

**Comment by kataras** [comment]
@ruanhanqin You are not using `app.Run/Listen` methods, the `app.Shutdown` can't do anything if it's not aware of the http.Server.

If for some reason, you want http.Server instance, just do `app.Run(iris.Server(&http.Server{...}))` :)

**Comment by ruanhanqin** [comment]
hello, @kataras  Thank you for you answer. but it  run better when i remove the zap log ,  and how can i use errgroup with gracefull shutdown, thanks
