### ISSUE TITLE
Swagger For Iris Mvc Like Swashbuckle.AspNetCore [FEATURE REQUEST]

### ISSUE THREAD

**Issue by majidbigdeli** [kataras/iris#1667]
We need add comments to our api  to generate swagger in  [https://github.com/iris-contrib/swagger](https://github.com/iris-contrib/swagger) example

```

// @Summary Add a new pet to the store
// @Description get string by ID
// @Accept  json
// @Produce  json
// @Param   some_id     path    int     true        "Some ID"
// @Success 200 {string} string	"ok"
// @Failure 400 {object} web.APIError "We need ID!!"
// @Failure 404 {object} web.APIError "Can not find ID"
// @Router /testapi/get-string-by-int/{some_id} [get]
func GetStringByInt(ctx iris.Context) {
	err := web.APIError{}
	fmt.Println(err)
}
```

But in asp dotnet   we dont need comment for generate swagger .
[Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) use reflection for find params and body and return type of action (method) in controller.

in new iris mvc this

```
func (c *GreetController) Get(req model.Request) (model.Response, error) {
	message, err := c.Service.Say(req.Name)
	if err != nil {
		return model.Response{}, err
	}

	return model.Response{Message: message}, nil
}
```

Are you can Genereate swagger without comment ?
 you find Request type and Response Type and params ,... with reflection and generate swagger without comment in iris mvc .

**Comment by kataras** [comment]
@majidbigdeli the problem with GO is that reflection cannot give us **parameter names** neither has support for code annotations, without those, the only solution is code comments + generator, that's why the swagger go implementation (not only Iris, general Go) uses comments.
