### ISSUE TITLE
Can you use it directly in template language request.session Get data

### ISSUE THREAD

**Issue by 265525** [kataras/iris#1669]
Please,I tried to look through some of the materials and didn't find anything about it, like the Django framework{{ request.session.username }}

**Comment by kataras** [comment]
In Go, we don't have access to the request context directly, instead you must declare the values you want to use inside your template (it's better that way you have control over the data passed). **We have examples for that**. Take a look at the [_examples/view/context-view-data](https://github.com/kataras/iris/blob/master/_examples/view/context-view-data/main.go) and [_examples/sessions/basic](https://github.com/kataras/iris/blob/master/_examples/sessions/basic/main.go).

Let's help you more, to make the `session` available in all your handlers you can create a middleware which will bind the session to templates.

Example Code:

```go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/sessions"
)

func main() {
	app := iris.New()
	app.RegisterView(iris.HTML("./views", ".html"))

	sess := sessions.New(sessions.Config{Cookie: "session_cookie", AllowReclaim: true})
	app.Use(sess.Handler())
	// ^ use app.UseRouter instead to access sessions on HTTP errors too.

	// Register our custom middleware, after the sessions middleware.
	app.Use(setSessionViewData)

	app.Get("/", index)
	app.Listen(":8080")
}

func setSessionViewData(ctx iris.Context) {
	session := sessions.Get(ctx)
	ctx.ViewData("session", session)
	ctx.Next()
}

func index(ctx iris.Context) {
	session := sessions.Get(ctx)
	session.Set("username", "kataras")
	ctx.View("index")
	/* OR without middleware:
	ctx.View("index", iris.Map{
		"session": session,
		//   {{.session.Get "username"}}
		// OR to pass only the 'username':
		// "username": session.Get("username"),
		//   {{.username}}
	})
	*/
}

```

**Comment by 265525** [comment]
Thank you very much. I know what to do

**Comment by kataras** [comment]
You are welcome @265525!
