### ISSUE TITLE
why there is aways "unexpected end of JSON input"

### ISSUE THREAD

**Issue by flykarry** [kataras/iris#1670]
Describe the issue you are facing or ask for help
![image](https://user-images.githubusercontent.com/14309127/98093379-d3277800-1ec2-11eb-9218-61ad53170ac7.png)
![image](https://user-images.githubusercontent.com/14309127/98093465-f3efcd80-1ec2-11eb-8510-cf2e100fd8b0.png)
![image](https://user-images.githubusercontent.com/14309127/98093496-fbaf7200-1ec2-11eb-958b-a7ed2cc36c1f.png)

**Comment by flykarry** [comment]
![image](https://user-images.githubusercontent.com/14309127/98093630-239ed580-1ec3-11eb-9431-f7947065147a.png)

**Comment by kataras** [comment]
Hello @flykarry, can you just share the repository please? If you are getting unexpected JSON that means that the client sends malformed data.

Thanks

**Comment by flykarry** [comment]
Thanks for your reply, Here is my repository https://github.com/flykarry/iris-server
maybe cause of the service

**Comment by flykarry** [comment]
> Hello @flykarry, can you just share the repository please? If you are getting unexpected JSON that means that the client sends malformed data.
> 
> Thanks

I got the point, when I use Service name the variable in the Controller struct, the bug come out。the hService is ok

**Comment by kataras** [comment]
Yeah, and also keep in mind that you have to pointer your receiver, e.g.
```go
func (h *HomeService) ListUser() string { // note that *HomeServer
	return "success"
}
```

So your issue fixed?

**Comment by flykarry** [comment]
Ok, thank you for reminding， I have fixed it

**Comment by kataras** [comment]
Good job, let's close this one!
