### ISSUE TITLE
pprof question

### ISSUE THREAD

**Issue by ruanhanqin** [kataras/iris#1675]
1,  http://127.0.0.1:8080/debug/pprof/profile  get "Unknown profile"
2, when i click the sub-page linke , the url was change   https://xxx.cn/v1/appointment-stream/debug/pprof ---> https://xxx.cn/debug/pprof/allocs?debug=1

**Comment by kataras** [comment]
@ruanhanqin I can't reproduce that, 

```go
package main

import (
	"github.com/kataras/iris/v12"

	"github.com/kataras/iris/v12/middleware/pprof"
)

func main() {
	app := iris.New()

	app.Get("/", func(ctx iris.Context) {
		ctx.HTML("<h1> Please click <a href='/v1/appointment-stream/debug/pprof'>here</a>")
	})

	api := app.Party("/v1/appointment-stream")
	p := pprof.New()
	api.Any("/debug/pprof", p)
	api.Any("/debug/pprof/{action:path}", p)
	//                              ___________
	app.Listen(":8080")
}

```

This works as expected, the URL is correct. Can I ask you the version of Iris you use? Did you try `go get -u github.com/kataras/iris/v12@master` as the repository's README suggest?

Thanks

**Comment by ruanhanqin** [comment]
@kataras I use v12.2.0-alpha,

**Comment by kataras** [comment]
@ruanhanqin Always try master before posting an issue. The above code snippet I posted doesn't work for you?

**Comment by ruanhanqin** [comment]
@kataras the above code work the same problems at v12.2.0-alpha,  the github.com/kataras/iris/v12@master  seem didn't has  ctx.ReadHeaders(),  ctx.StopWithJson()... in my memory.  because i use this feature so i don't want to change it ,  I thinks the v12.2.0 release will come soon.

**Comment by kataras** [comment]
@ruanhanqin You are wrong, the master is a more recent version of v12.2.0-alpha, it contains all of its features plus more, the [ctx.ReadHeaders](https://github.com/kataras/iris/blob/master/context/context.go#L2326), [ctx.StopWithJSON](https://github.com/kataras/iris/blob/5b6802d00eaf820cb90fe2864620dfabb62ee0bc/context/context.go#L745) exist. The code snippet works on me so I assume the issue is somewhere else, can you post the full code snippet that I can reproduce the problem so I can be more helpful?

**Comment by ruanhanqin** [comment]
@kataras  1. I change to the master it work in localhost, but the sub-page(cmdline, profile)  didn't, it return "Unknown profile"
                 2. when I deploy to ECS, and the "/v1/appointment-stream" is the gateway path, all the sub page can't work, it return 404
                 i find that when i click the sub-page link  the url "https://testing.smartracing.cn/v1/appointment/streams/debug/pprof" was change to "https://testing.smartracing.cn/debug/pprof/"  it was not the real path ,  the "v1/appointment/streams" was lost

**Comment by kataras** [comment]
@ruanhanqin is that the full code you tested or you used a middleware or something else in between?

**Comment by ruanhanqin** [comment]
```go
package main

import (
	"io"
	"net/http"
	_ "net/http/pprof"
)

func handle(w http.ResponseWriter, r *http.Request)  {
	io.WriteString(w, "success")
}

func main()  {
	http.HandleFunc("/", handle)
	http.ListenAndServe(":8080", nil)
}```

@kataras 
1. I use the `net/http`  run in localhost the sub-page work well,  
2. but i deploy to ECS it  occured  the same problems, it may be the gateway redirect problems

**Comment by Ravlyon** [comment]
Same here. It work in localhost.
ECS: [WARN] 2021/01/13 13:26 404 162.234µs ::1 GET /debug/pprof/profile

**Comment by Ravlyon** [comment]
Same here. It works in localhost.
ECS: **[WARN] 2021/01/13 13:26 404 162.234µs ::1 GET /debug/pprof/profile**
