### ISSUE TITLE
[BUG]fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by fdsnsf** [kataras/iris#1676]
**Describe the bug**
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write

goroutine 27837564 [running]:
runtime.throw(0x1134f63, 0x21)
        /build/dependency/go1.13.10/src/runtime/panic.go:774 +0x72 fp=0xc008a17960 sp=0xc008a17930 pc=0x431112
runtime.mapaccess1_faststr(0xf7a480, 0xc00042ecc0, 0xc005643c43, 0x4, 0xc008642e58)
        /build/dependency/go1.13.10/src/runtime/map_faststr.go:21 +0x44f fp=0xc008a179d0 sp=0xc008a17960 pc=0x4146bf
github.com/kataras/iris/core/router.(*trieNode).getChild(...)
        /build/stage/cop.inke_owt.bpc_pdl.dt_servicegroup.api-gateway_service.hall-api-gateway-service_job.hall-api-gateway-service_cluster.ali-bj/src/github.com/kataras/iris/core/router/trie.go:51
github.com/kataras/iris/core/router.(*trie).search(0xc00042eb70, 0xc005643c34, 0x18, 0xc008cb5470, 0x6)
        /build/stage/cop.inke_owt.bpc_pdl.dt_servicegroup.api-gateway_service.hall-api-gateway-service_job.hall-api-gateway-service_cluster.ali-bj/src/github.com/kataras/iris/core/router/trie.go:196 +0x7ae fp=0xc008a17a98 sp=0xc008a179d0 pc=0x976f2e
github.com/kataras/iris/core/router.(*routerHandler).HandleRequest(0xc005d8e2a0, 0x132c8a0, 0xc00a258320)
        /build/stage/cop.inke_owt.bpc_pdl.dt_servicegroup.api-gateway_service.hall-api-gateway-service_job.hall-api-gateway-service_cluster.ali-bj/src/github.com/kataras/iris/core/router/handler.go:224 +0x2f1 fp=0xc008a17b90 sp=0xc008a17a98 pc=0x96f371
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0x1302640, 0xc008184fc0, 0xc00caca400)
        /build/stage/cop.inke_owt.bpc_pdl.dt_servicegroup.api-gateway_service.hall-api-gateway-service_job.hall-api-gateway-service_cluster.ali-bj/src/github.com/kataras/iris/core/router/router.go:84 +0x8f fp=0xc008a17bf0 sp=0xc008a17b90 pc=0x9786af
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc0001e0580, 0x1302640, 0xc008184fc0, 0xc00caca400)
        /build/stage/cop.inke_owt.bpc_pdl.dt_servicegroup.api-gateway_service.hall-api-gateway-service_job.hall-api-gateway-service_cluster.ali-bj/src/github.com/kataras/iris/core/router/router.go:161 +0x48 fp=0xc008a17c18 sp=0xc008a17bf0 pc=0x974538
net/http.serverHandler.ServeHTTP(0xc0063b6000, 0x1302640, 0xc008184fc0, 0xc00caca400)
        /build/dependency/go1.13.10/src/net/http/server.go:2802 +0xa4 fp=0xc008a17c48 sp=0xc008a17c18 pc=0x725f04
net/http.(*conn).serve(0xc00bab4960, 0x1307140, 0xc00a709980)
        /build/dependency/go1.13.10/src/net/http/server.go:1890 +0x875 fp=0xc008a17fc8 sp=0xc008a17c48 pc=0x7217f5
runtime.goexit()
        /build/dependency/go1.13.10/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc008a17fd0 sp=0xc008a17fc8 pc=0x4610e1
created by net/http.(*Server).Serve
        /build/dependency/go1.13.10/src/net/http/server.go:2928 +0x384

**To Reproduce**
1. Service in running,add route（app.Handle(httpMethod, url, handlers...)） and then  refresh router (app.RefreshRouter())

**Desktop (please complete the following information):**
 - OS: centos 6

**iris.Version**
- e.g.  master

**Comment by fdsnsf** [comment]
version is  `11.1.1`

**Comment by kataras** [comment]
@fdsnsf Code snippet?

**Comment by kataras** [comment]
@fdsnsf I can't help you without a code snippet and also if you used iris version 11.1.1 i would highly recommend you to upgrade to the latest v12.2.0-alpha or v12.1.8 at least.
