### ISSUE TITLE
How can i access react sub routing directly when using serving static files?

### ISSUE THREAD

**Issue by yuanzicheng** [kataras/iris#1679]
First, i created a react single page application with `create-react-app`, and then use the lib `react-router-dom` to control the routing.For testing, there are three pages("/", "/page1", "page2/"), "/page1" and "page2" are sub routing of "/". After everything is prepared, I executed the  command `npm run build` and got a `build` directory which contains all files of the react SPA project.

Second step, i created an iris web application and copy the `build` folder in the previous step to the iris project. The below is the project structure.
```
.
├── build
│   ├── asset-manifest.json
│   ├── favicon.ico
│   ├── index.html
│   ├── robots.txt
│   └── static
│       ├── css
│       │   ├── 2.e1b980e4.chunk.css
│       │   ├── 2.e1b980e4.chunk.css.map
│       │   ├── main.df9ccc9a.chunk.css
│       │   └── main.df9ccc9a.chunk.css.map
│       └── js
│           ├── 2.5199c733.chunk.js
│           ├── 2.5199c733.chunk.js.LICENSE.txt
│           ├── 2.5199c733.chunk.js.map
│           ├── main.a04880a4.chunk.js
│           ├── main.a04880a4.chunk.js.map
│           ├── runtime-main.a97cbf4f.js
│           └── runtime-main.a97cbf4f.js.map
├── go.mod
├── go.sum
├── main.go
└── rice-box.go
```
In the main.go file, i use `HandleDir` function to serve static files. Here is the code of main.go.
```go
func main() {
	app := iris.New()
	app.HandleDir("/", iris.Dir("./build"))
        // when compiling, using "github.com/GeertJohan/go.rice" to add all resource files to the executable file
	// app.HandleDir("/", http.FileSystem(rice.MustFindBox("build").HTTPBox()))
	app.Listen(":8080")
}
```

However, when i start the iris project, visit the home page with the url "http://localhost:8080", and switch pages to "page1" and "page2" by clicking buttons of the page itself, everything works ok! But, when i directly visit "http://localhost:8080/page1" and "http://localhost:8080/page2", or using refresh button of the browser to refresh the page1 and page2, "Not Found" occured！

I think this is because iris can not understand the sub routing of react application correctly. After all, in the main.go file, i only configured the router "/" with `app.HandleDir("/", iris.Dir("./build"))`. Is there any method to help iris understand the sub routing (e.g. "/page1", "/page2") of react app？Look forward to your reply，thanks!

**Comment by yuanzicheng** [comment]
```go
	app.HandleDir("/", iris.Dir("./build"), iris.DirOptions{
		IndexName: "index.html",
		ShowList:  false,
		SPA:       true,
	})
```
I tried to add the third parameter `iris.DirOptions`, and everything works ok! 

IRIS is really a great Web Framework!

**Comment by kataras** [comment]
@yuanzicheng sorry for the delay, I didn't receive any notification about this issue but glad you find out, you can read more file server examples at the [_examples/file-server](https://github.com/kataras/iris/tree/master/_examples/file-server) sub folder.
