### ISSUE TITLE
Watch for file changes

### ISSUE THREAD

**Issue by jonathandion** [kataras/iris#168]
Hi,

Is there a way to watch file changes and restart the server in Iris ?

Thanks.

**Comment by qskousen** [comment]
Not at this time, but possibly in the future.

**Comment by egorsmkv** [comment]
Use https://github.com/pilu/fresh

**Comment by xpbliss** [comment]
https://github.com/alkchr/goal

**Comment by jonathandion** [comment]
Thanks for info @qskousen. @egorsmkv I tried Gin but it was not working at all I will try that one.
