### ISSUE TITLE
jwt.HMAC undefined

### ISSUE THREAD

**Issue by Ja7adR** [kataras/iris#1680]
hi
example my sql i get error this

https://github.com/kataras/iris/tree/master/_examples/database/mysql

```
# myapp/api
api\api.go:18:8: undefined: "github.com/kataras/iris/v12/middleware/jwt".HMAC
api\api.go:76:20: undefined: "github.com/kataras/iris/v12/middleware/jwt".JWT
api\api.go:80:14: undefined: "github.com/kataras/iris/v12/middleware/jwt".Audience
api\api.go:87:21: undefined: "github.com/kataras/iris/v12/middleware/jwt".JWT
```

**Comment by kataras** [comment]
@Ja7adR You are right, I've already fixed that on [this PR](https://github.com/kataras/iris/pull/1677). Until it's pushed to master branch you can view the fixed example at: https://github.com/kataras/iris/tree/new-basicauth-features/_examples/database/mysql
