### ISSUE TITLE
同一个路由阻塞,呈现队列响应

### ISSUE THREAD

**Issue by hu19941107** [kataras/iris#1682]
同一个路由先后两次请求,前面的请求没有结束前,后面的请求被阻塞住
简单路由,MVC路由都出来这样的问题
简单示例:将某个路由对应的句柄函数中延时5秒,开两个web页面,先后请求两个,先请求的在5秒后响应,后一次请求,考虑请求的时间差,会在9-10秒后响应
造成的影响就是,例如某个api接口耗时比较长,单用户请求频繁,会导致后面请求的用户响应时间被拉长

**Comment by kataras** [comment]
@hu19941107 I can't understand :/ I tried to use google translation but the best translation is a code snippet (and a test file if that's  necessary)

Chinese: 我听不懂：/我尝试使用Google翻译，但最好的翻译是代码段（如果需要的话，还有测试文件）

**Comment by hu19941107** [comment]
![code](https://user-images.githubusercontent.com/74887349/100834603-28957b80-34a7-11eb-9d88-4e5f1c023ba7.png)
![eg](https://user-images.githubusercontent.com/74887349/100834619-2d5a2f80-34a7-11eb-811e-10ae30563116.png)

**Comment by hu19941107** [comment]
> @ hu19941107我听不懂：/我尝试使用Google翻译，但最好的翻译是代码段（如果需要的话还有一个测试文件）
> 
> 中文：我听不懂：/我尝试使用Google翻译，但最好的翻译是代码段（如果需要的话，还有测试文件）

![code](https://user-images.githubusercontent.com/74887349/100

**Comment by hu19941107** [comment]
> @ hu19941107我听不懂：/我尝试使用Google翻译，但最好的翻译是代码段（如果需要的话还有一个测试文件）
> 
> 中文：我听不懂：/我尝试使用Google翻译，但最好的翻译是代码段（如果需要的话，还有测试文件）

![code](https://user-images.githubusercontent.com/74887349/100834766-6eeada80-34a7-11eb-95a3-8c263b4a06dd.png)
![eg](https://user-images.githubusercontent.com/74887349/100834776-71e5cb00-34a7-11eb-843a-b88aa0c21d4b.png)

**Comment by kataras** [comment]
@hu19941107 the same behavior as the `net/http`:

```go
package main

import (
	"log"
	"net/http"
	"time"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/dev", func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(5 * time.Second)
		w.Write([]byte("OK"))
	})

	log.Printf("Listen and serve at: http://localhost:8080")
	http.ListenAndServe(":8080", mux)
}
```

**Comment by hu19941107** [comment]
Thank you very much

**Comment by kataras** [comment]
Wait @hu19941107, you don't have to ask there, I am so sorry. The problem is not Go, it's Google Chrome(Chronium), test the same on Postman and Firefox and you will see that the code is executed as expected.

**Comment by kataras** [comment]
@hu19941107, sorry forgot to mention. The problem is not Go, it's Google Chrome(Chronium), test the same on Postman, Firefox, `wrk`, `apache ab`, `bombardier` and you will see that the code is executed as expected and the problem disappears.
