### ISSUE TITLE
[BUG]iris.DirListRich has error

### ISSUE THREAD

**Issue by beluxx** [kataras/iris#1683]
**Describe the bug**

when i use django template engine, there has a problem with `iris.DirListRich`

there are my code:

```go
// ...

tmpl := iris.Django(views, ".html")

// Omit some codes
// ....

app.HandleDir("/fileslistrich", iris.Dir(filesPath), iris.DirOptions{
	Compress: true,
	ShowList: true,
	DirList: iris.DirListRich(iris.DirListRichOptions{
		// Optionally, use a custom template for listing:
		// Tmpl: dirListRichTemplate,
		TmplName: "pages/fileslistrich.html",
	}),
})
```

when i navigation http://localhost/fileslistrich , i got an error

```shell
interface conversion: interface {} is []handler.fileInfoData, not map[string]interface {}
/home/golang/go/src/runtime/panic.go:969
/home/golang/go/src/runtime/iface.go:260
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/view/django.go:272
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/view/django.go:298
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/view/view.go:76
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/iris.go:413
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:3011
/home/luzp/go_study/catT/handler/handler.go:98
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/fs.go:274
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/fs.go:436
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:611
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/sessions/sessions.go:151
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:476
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/handler.go:440
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/router.go:110
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:611
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/middleware/recover/recover.go:77
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:611
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/middleware/requestid/requestid.go:84
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:611
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/middleware/accesslog/accesslog.go:732
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/context/context.go:476
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/router.go:158
/home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/router.go:322
/home/golang/go/src/net/http/server.go:2807
/home/golang/go/src/net/http/server.go:1895
/home/golang/go/src/runtime/asm_arm64.s:1148

2020-12-03 16:53:48|5.20518ms|500|GET|/fileslistrich|::1|0 B|21 B|error(interface conversion: interface {} is []handler.fileInfoData, not map[string]interface {} /home/luzp/gocode/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201107104914-7b6a8f1e2646/core/router/fs.go:429)|
```

i found the error should be there: https://github.com/kataras/iris/blob/master/core/router/fs.go#L639

the `iris.DirListRich` ust golang template, so i got the error.

i try to override `iris.DirListRich`  in my local file, I modified like:

```go
if options.TmplName != "" {
	ctx.ViewData("data", pageData)
	return ctx.View(options.TmplName)
}
```

i can navigation http://localhost/fileslistrich has no error. but in my page , i got nothing.

the view page html is 

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% for d in data %}
    {{ d }}
    {% endfor %}
</body>

</html>
```

and i use chrome devtools to saw the page element, i got these infomations:

```html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 </head>

<body>
    
    <handler.fileinfodata value="">
    
    <handler.fileinfodata value="">
    
    <handler.fileinfodata value="">
    

</handler.fileinfodata>
</handler.fileinfodata>
</handler.fileinfodata>

</body>
</html>
```

Please forgive me, my English is not very good

Please help me to solve this problem

thanks!

**Comment by kataras** [comment]
Hello @beluxx,

I see, you want to use django engine instead of html for directory listing. Let me see what I can do, will come back to you in 1-2 hours (I have a meeting now).

**Comment by beluxx** [comment]
> Hello @beluxx,
> 
> I see, you want to use django engine instead of html for directory listing. Let me see what I can do, will come back to you in 1-2 hours (I have a meeting now). It's not a bug, it's more like a feature request, because in examples and documentation we explicitly say html/template contents for custom directory listing view.

ok

**Comment by kataras** [comment]
@beluxx sorry for the delay, can you post the django template (and the functions you may use) so I make sure that my local code will work for you too?

**Comment by beluxx** [comment]
> @beluxx sorry for the delay, can you post the django template (and the functions you may use) so I make sure that my local code will work for you too?

I found the problem after using your example.  https://github.com/kataras/iris/tree/master/_examples/file-server/file-server

You can use this example directly, and then replace golang template with django engine template.

I did not use any additional view functions, only the ones provided by iris.

**Comment by kataras** [comment]
Hello @beluxx,

With the modified version of fs.go on dirList (as you correctly found, which converts the struct to map too):

```go
		if options.TmplName != "" {
			ctx.ViewData("data", pageData)
			return ctx.View(options.TmplName)
		}
```

And the django template file:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{data.Title}}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% for file in data.Files %}
    <a href="{{ file.Path }}" title="{{ file.ModTime }}">{{ file.Name }}</a><br/>
    {% endfor %}
</body>

</html>
``` 

Everything works good, at least in my side (you need to force-refresh (control+F5) in order to see the changes):

![image](https://user-images.githubusercontent.com/22900943/101153164-ba7ac100-362c-11eb-91d8-36ec0ba0d055.png)


I pushed a commit with that fs.go change, please upgrade to master and check it by yourself.

Thanks

**Comment by kataras** [comment]
Hello @beluxx,

Below you will read two solutions, 

The first one looks like your local edited code one:

With the modified version of fs.go on dirList (as you correctly found, which converts the struct to map too):

```go
		if options.TmplName != "" {
			ctx.ViewData("data", pageData)
			return ctx.View(options.TmplName)
		}
```

And the django template file:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{data.Title}}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% for file in data.Files %}
    <a href="{{ file.Path }}" title="{{ file.ModTime }}">{{ file.Name }}</a><br/>
    {% endfor %}
</body>

</html>
``` 

The 2nd one is to keep setting the template data on the root key (ViewData("", data) or View(..., data)) and modify the `view/django.go` file and convert any struct to a compatible pongo2 context. This solution is better as it does NOT add breaking changes on the template/html templates. The django template file looks like this:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{Title}}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% for file in Files %}
    <a href="{{ file.Path }}" title="{{ file.ModTime }}">{{ file.Name }}</a><br/>
    {% endfor %}
</body>

</html>
```

Both solutions work (you need to force-refresh (control+F5) in order to see the changes):

![image](https://user-images.githubusercontent.com/22900943/101153164-ba7ac100-362c-11eb-91d8-36ec0ba0d055.png)

I pushed a commit with the 2nd solution, please upgrade to master and check it by yourself.

Thanks

**Comment by beluxx** [comment]
thanks @kataras 
i will try it

**Comment by beluxx** [comment]
In addition, I also found another problem 
 https://github.com/kataras/iris/blob/master/sessions/sessiondb/redis/driver_goredis.go#L50

it should be 

```go
opts.Password= c.Password
```

So, I submitted a fix request for this issue.  https://github.com/kataras/iris/pull/1686

**Comment by kataras** [comment]
Oh that's a good one thanks @beluxx
