### ISSUE TITLE
Dynamic routing can not input with empty

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1689]
`
x:=iris.New()
x.Get("/{f}", func(ctx iris.Context) {
	ctx.WriteString(ctx.Params().Get("f"))
})
x.Run(iris.Addr(":8080"))
`
hello~
when i access the web page "http://127.0.0.1:8080/a" , it can write "a" in the page.
but when i access the web page "http://127.0.0.1:8080/", it writes "Not Found".
why?

**Comment by kataras** [comment]
Hello @CulionBEAR,
Because you expect something after the `/` with the `{f}` parameter, imagine something like: `/api/user/{id}`, it should only serve `/api/user/42` not `/api/user`.

In order to serve both `/` and `/{f}` you can use two methods:

```go
app.Get("/", handler)
app.Get("/{f}", handler)

// OR app.HandleMany(iris.MethodGet, "/ /{f}", handler)
```

**Comment by CulionBEAR** [comment]
okk
thanks
