### ISSUE TITLE
Unable to update golang.org directory package

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#169]
Hi @kataras ! I can't connect golang.org server in China, can you change import code "golang.org/x/..." to  "github.com/golang/..."?

**Comment by kataras** [comment]
No this isn't working, but we have a solution at the README [Installation section](https://github.com/kataras/iris#installation), but in the final v3 I will remove the x/context's integration, it does not have meaning anymore here

**Comment by kataras** [comment]
@dxvgef golang.org/x/net/context is not used in Iris anymore, I removed it.

**Comment by kataras** [comment]
@dxvgef golang.org/x/net/context is not used in Iris anymore, I just removed it :)

**Comment by dxvgef** [comment]
@kataras Are you waiting for go 1.7?

**Comment by kataras** [comment]
Exactly :)

**Comment by kataras** [comment]
Exactly, but no for the reason you think, context , this doesn't touch us we have already all that goods  behind the scenes:)
