### ISSUE TITLE
the latest version can not run

### ISSUE THREAD

**Issue by CulionBEAR** [kataras/iris#1691]
Sorry to disturb you again...
yesterday i can not run after update iris version.
![20201215004222](https://user-images.githubusercontent.com/35328438/102109482-0fa9a480-3e6f-11eb-9801-94dff975db48.png)
please help...

**Comment by kataras** [comment]
@CulionBEAR I think you didn't upgrade to the latest one, your `GOPATH` seems to missing the `github.com/kataras/iris/v12` (note the **v12** suffix). The `Set.Delims`, just take a look at: https://github.com/kataras/iris/blob/master/view/jet.go#L33.

As the README and the installation section of the website note, if you have troubles during installation follow the steps below:

Open a command line window in your project's file, remove any `go.mod/vendor` files you may have and execute:

```sh
go env -w GOPROXY=https://goproxy.cn,https://gocenter.io,https://goproxy.io,direct
go mod init $your_app_name
go get -u github.com/kataras/iris/v12@master
go build
```

Plaese try, waiting for your response here and your previous opened issues.

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
@CulionBEAR I think you didn't upgrade to the latest one, your `GOPATH` seems to missing the `github.com/kataras/iris/v12` (note the **v12** suffix). The `Set.Delims` exists, just take a look at: https://github.com/kataras/iris/blob/master/view/jet.go#L33.

As the README and the installation section of the website note, if you have trouble during installation follow the steps below:

Open a command line window in your project's directory, remove any `go.mod/vendor` files you may have and execute:

```sh
go env -w GOPROXY=https://goproxy.cn,https://gocenter.io,https://goproxy.io,direct
go mod init $your_app_name
go get -u github.com/kataras/iris/v12@master
go build
```

Plaese try, waiting for your response here and your previous opened issues.

Thanks,
Gerasimos Maropoulos

**Comment by CulionBEAR** [comment]
Thanks,i solved the problem ：）
