### ISSUE TITLE
[Enhancement]Fix code quality issues

### ISSUE THREAD

**Issue by withshubh** [kataras/iris#1693]
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of iris repo, and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/iris/issues/?category=recommended).

I am opening a PR to fix a few of them.

**Comment by kataras** [comment]
Hello @withshubh,

Thanks for offering to help me out, please feel free to push a complete PR. Just one note of my behalf: please benchmark before changes in hot-paths, if the old code looks bad but it performs faster, keep it as it is. I am sure you will find interesting things, after all, it's a 24/24⌚ 5 years of work and personal sacrifice :)

Thanks,
Gerasimos Maropoulos.

**Comment by kataras** [comment]
Hello @withshubh do you want to continue this, can I leave it up for you or we should close this one?

**Comment by withshubh** [comment]
You can close this issue for now! 
I may or may not submit the PR with new fixes but I'll submit a new PR to add a DeepSource badge to your GitHub readme which will help project contributors to fix the issues in the repo.

**Comment by kataras** [comment]
@withshubh I tried to do that but it doesn't match the UI, we can't add more badges for now. Eventually I will fix all those issues alone I already know it (suddenly) :P  And I was thinking.... do you have editor plugin? (i.e VS Code, which I can navigate through the issues and fix those in-time, like go-vet/language server does)

**Comment by kataras** [comment]
@withshubh I tried to do that but it doesn't match the UI, we can't add more badges for now and we shouldn't, users who want to help they can just click the last commit, there they can find the DeepSource build, even in their PRs, so we are ok in that part. 

Eventually I will fix all those issues alone I already know it (suddenly) :P  And I was thinking.... do you have editor plugin? (i.e VS Code, which I can navigate through the issues and fix those in-time, like go-vet/language server does)

**Comment by kataras** [comment]
@withshubh I've already tried to do that but it doesn't match the UI, we can't add more badges for now and we shouldn't, users who want to help they can just click the last commit, there they can find the DeepSource build, even in their PRs, so we are ok in that part. 

Eventually I will fix all these issues alone I already know it (suddenly) :P  And I was thinking.... do you have editor plugin? (i.e VS Code, which I can navigate through the issues and fix those in-time, like go-vet/language server does), I found [that](https://marketplace.visualstudio.com/items?itemName=DeepCode.deepcode) but it doesn't support Go.

And one more, you are free to put Iris in your users list 👍🏽

**Comment by kataras** [comment]
Here it's: https://github.com/kataras/iris/pull/1701, now we can close this issue :)

**Comment by withshubh** [comment]
> do you have editor plugin? (i.e VS Code, which I can navigate through the issues and fix those in-time, like go-vet/language server does).

Sublime and VSCode plugin will be available by the end of the March. :tada: 

>  there should be an option for // lint: ignore type of thing somewhere.

You can use `// skipcq` at the end of that line or you can ignore issues directly from the DeepSource dashboard by clicking on `Ignore this issue`.

> And one more, you are free to put Iris in your users list 👍🏽

Thanks @kataras  :sparkling_heart: On it!

**Comment by kataras** [comment]
Thanks @withshubh yes, false alarms were ignored through dashboard but `skipcq` seems a smarter choice :)

Of course, tell me if you need more from my side too.

I am closing this issue as all current issues are fixed 12 days ago.

**Comment by kataras** [comment]
Thanks @withshubh yes, false alarms were ignored through dashboard but `skipcq` seems a smarter choice :)

Of course, tell me if you need more from my side too.

I am closing this issue as all current reported mistakes were fixed 12 days ago.
