### ISSUE TITLE
How to use Content Negotiation with mvc?

### ISSUE THREAD

**Issue by Ronbb** [kataras/iris#1697]
I tried the code below and it works, but looks not strange.

If I call `ctx.Negotiate(r)` without returning a blank error, I will get duplicate response body.

Or I should call `ctx.Negotiation().Build()` and fill in content-type and enable compression manually.

Though I do that, I must implement `func Preflight` for every struct what used as return. 

Is there any way to simplify the code in this situation?

```golang
package main

import (
	"errors"

	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
)

func main() {
	app := iris.New()

	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

func (r *user) Preflight(ctx iris.Context) error {
	println(r.ID)
	ctx.Negotiation().JSON().XML().YAML().EncodingGzip()
	ctx.Negotiate(r)
	return errors.New("")
}

// Or 
// 
// func (r *user) Preflight(ctx iris.Context) error {
// 	println(r.ID)
// 	contentType, charSet, encoding, _ := ctx.Negotiation().JSON().XML().YAML().EncodingGzip().Build()
// 	if encoding != "" {
// 		ctx.CompressWriter(true)
// 	}
// 	ctx.ContentType(contentType + ";" + charSet)
// 	return nil
// }

type user struct {
	ID string `json:"id"`
}

func (c *controller) GetUserBy(id string) *user {
	return &user{ID: id}
}

```

**Comment by kataras** [comment]
Hello @Ronbb,

I am really sorry for the delayed response, I usually answer faster.

To answer your question, no you don't have to fire the `Build` manually. Secondly, you can use content negotitation in MVC as well, same thing. To answer your important question: no you don't have to do that on every structure you want to use. 

The Negotiation` builder is intentionally splitted from the final response write part (`Negotiate` method), it allows you to register **middlewares** to decide what content type/encoding/charset your server can serve resource(s). With that in mind, you can simply do:

```go
func main() {
	app := iris.New()

        app.Use(func(ctx iris.Context){
            ctx.Negotiation().JSON().XML().YAML().EncodingGzip()
            ctx.Next()
        }) // or UseRouter to run before everything, even http errors.
	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

type user struct {
	ID string `json:"id"`
}

func (c *controller) GetUserBy(id string) *user {
	return &user{ID: id}
}
```

^ You should be fine with that. Waiting for your response!

**Comment by kataras** [comment]
Hello @Ronbb,

I am really sorry for the delayed response, I usually answer faster.

To answer your question, no you don't have to fire the `Build` manually. Secondly, you can use content negotitation in MVC as well, same thing. To answer your important question: no you don't have to do that on every structure you want to use. 

The Negotiation` builder is intentionally splitted from the final response write part (`Negotiate` method), it allows you to register **middlewares** to decide what content type/encoding/charset your server can serve resource(s). 

The MVC (and generally, dependency injection-based handlers in Iris) have the option to "hijack" the response for all return types inside a controller (or a function). That's where you will put your `Negotiate(v)` part.

With that in mind, you can simply do:

```go
func main() {
	app := iris.New()

        // 1. You can pass it as middleware, so all other handlers use that negotitation:
        // 2. or comment that and put it on the `UseResultHandler` you'll see below.
        app.Use(func(ctx iris.Context){
            ctx.Negotiation().JSON().XML().YAML().EncodingGzip()
            ctx.Next()
        }) // or UseRouter to run before everything, even http errors.
        
        app.ConfigureContainer().UseResultHandler(func(next iris.ResultHandler) iris.ResultHandler {
		return func(ctx iris.Context, v interface{}) error {
			ctx.Negotiate(v)
			// switch val := v.(type) { ... you can do more things here :) 
	        }})
		
	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

type user struct {
	ID string `json:"id"`
}

func (c *controller) GetUserBy(id string) *user {
	return &user{ID: id}
}
```

Examples:

1. https://github.com/kataras/iris/tree/master/_examples/response-writer/content-negotiation
2. https://github.com/kataras/iris/tree/master/_examples/mvc/error-handler-hijack

^ You should be fine with that. Waiting for your response!

**Comment by kataras** [comment]
Hello @Ronbb,

I am really sorry for the delayed response, I usually answer faster.

To answer your question, no you don't have to fire the `Build` manually. Secondly, you can use content negotitation in MVC as well, same thing. To answer your important question: no you don't have to do that on every structure you want to use. 

The Negotiation` builder is intentionally splitted from the final response write part (`Negotiate` method), it allows you to register **middlewares** to decide what content type/encoding/charset your server can serve resource(s). 

The MVC (and generally, dependency injection-based handlers in Iris) have the option to "hijack" the response for all return types inside a controller (or a function). That's where you will put your `Negotiate(v)` part.

With that in mind, you can simply do:

```go
func main() {
	app := iris.New()

        // 1. You can pass it as middleware, so all other handlers use that negotitation:
        // 2. or comment that and put it on the `UseResultHandler` you'll see below.
        app.Use(func(ctx iris.Context){
            ctx.Negotiation().JSON().XML().YAML().EncodingGzip()
            ctx.Next()
        }) // or UseRouter to run before everything, even http errors.
        
        app.ConfigureContainer().UseResultHandler(func(next iris.ResultHandler) iris.ResultHandler {
		return func(ctx iris.Context, v interface{}) error {
			_, err := ctx.Negotiate(v)
			return err
			// switch val := v.(type) { ... you can do more things here :) 
	        }})
		
	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

type user struct {
	ID string `json:"id"`
}

func (c *controller) GetUserBy(id string) *user {
	return &user{ID: id}
}
```

Examples:

1. https://github.com/kataras/iris/tree/master/_examples/response-writer/content-negotiation
2. https://github.com/kataras/iris/tree/master/_examples/mvc/error-handler-hijack

^ You should be fine with that. Waiting for your feedback!

**Comment by kataras** [comment]
Hello @Ronbb,

I am really sorry for the delayed response, I usually answer faster.

To answer your question no, you don't have to fire the `Build` manually. Secondly, you can use content negotiation in MVC as well, same thing. To answer your important question: no you don't have to do that on every structure you want to use. 

The `Negotiation builder` is intentionally splitted from the final response write part (`Negotiate` method), it allows you to register **middlewares** to decide what content type/encoding/charset your server can serve resource(s). 

The MVC (and generally, dependency injection-based handlers in Iris) have the option to "hijack" the response for all return types inside a controller (or a function). That's where you will put the `Negotiate(v)` part.

With that in mind, you can simply do:

```go
func main() {
	app := iris.New()

        // 1. You can pass it as middleware, so all other handlers use that negotiation:
        // 2. or comment that and put it on the `UseResultHandler` you'll see below.
        app.Use(func(ctx iris.Context){
            ctx.Negotiation().JSON().XML().YAML().EncodingGzip()
            ctx.Next()
        }) // or UseRouter to run before everything, even http errors.
        
        app.ConfigureContainer().UseResultHandler(func(next iris.ResultHandler) iris.ResultHandler {
		return func(ctx iris.Context, v interface{}) error {
			_, err := ctx.Negotiate(v)
			return err
			// switch val := v.(type) { ... you can do more things here :) 
	        }})
		
	m := mvc.New(app)
	m.Handle(new(controller))

	app.Listen(":8080")
}

type controller struct{}

type user struct {
	ID string `json:"id"`
}

func (c *controller) GetUserBy(id string) *user {
	return &user{ID: id}
}
```

Examples:

1. https://github.com/kataras/iris/tree/master/_examples/response-writer/content-negotiation
2. https://github.com/kataras/iris/tree/master/_examples/mvc/error-handler-hijack

^ You should be fine with that. Waiting for your feedback!

> Happy New Year 🎅🏽 🤶🏽

**Comment by Ronbb** [comment]
@kataras 

Thank you a lot! 

> Happy New Year ~ 🎇🎆🧨
