### ISSUE TITLE
PongoEngine panic bug create with this commit e40fe0a9f3c1e836d16e0b6bb6af336e81d2eb45 

### ISSUE THREAD

**Issue by zyanho** [kataras/iris#170]
iris version v3.0.0-beta.2

in iris.go file 
this line be add, but templateConfig.Pongo.Globals not be check and it was nil map.
```
 189 +                    // register it to the global context, no as Filter.
 190 +			templateConfig.Pongo.Globals["url"] = urlFunc
```

when app.Run(os.Args) it would got panic message "assignment to entry in nil map"

add some like this should be check and make it success run.

```
if templateConfig.Pongo.Globals == nil {
  templateConfig.Pongo.Globals = make(map[string]interface{}, 1)
}
// register it to the global context, no as Filter.
templateConfig.Pongo.Globals["url"] = urlFunc
```

or add this config to iris before run.
```
config.Render.Template.Pongo.Globals = make(map[string]interface{}, 1)
app := iris.New(config)
```

**Comment by kataras** [comment]
@zyanho  The default configuration has already initialize the map, you use custom configuration and propably is mergo's bug. Fixed upgrade with ` go get -u github.com/kataras/iris`
