### ISSUE TITLE
When MVC controller contains struct field，post request return: `schema: invalid path`

### ISSUE THREAD

**Issue by hjzCy** [kataras/iris#1704]
Simple test project，base on iris v12.2.0-alpha2：

```go
type String string

// It is not used as the structure of Post Body, but only defined as a controller。
type controller struct {
    Age    sql.NullString `json:"age" form:"age"`  // NO
   // Age    types.NullString `json:"age" form:"age"`  -- NO
   // Age    string `json:"age" form:"age"`  -- YES
   // Age    String `json:"age" form:"age"`  -- YES
}

// When there is a structure field in the controller，Post request failed, Will not enter the method body.
func (u *controller) PostTest(c iris.Context) string {
    fmt.Println("forms:", c.FormValues())
    return "post test"
}

func main() {
    app := iris.Default()
    mvc.New(app).Handle(new(controller))
    _ = app.Listen(":188")
}
```

mine `type.NullString` :

```go
type NullString sql.NullString

func (v *NullString) Scan(value interface{}) error {
    if v.Valid = value != nil; v.Valid {
        v.String = value.(string)
    }
    return nil
}

func (v NullString) Value() (driver.Value, error) {
    if !v.Valid {
        return nil, nil
    }
    return v.String, nil
}

func (v NullString) MarshalJSON() ([]byte, error) {
    if !v.Valid {
        return []byte(""), nil
    }
    return json.Marshal(v.String)
}

func (v NullString) UnmarshalJSON(data []byte) error {
    var s string
    if err := json.Unmarshal(data, &s); err != nil {
        return err
    }
    v.String = s
    v.Valid = len(s) > 0
    return nil
}
```

At this time, the request to Post: http://localhost:188/test failed (400) ：**schema: invalid path "age"schema: invalid path "age"**

If I define the HandleError method, I can request success：

```go
func (u *controller) HandleError(ctx iris.Context, err error) {
    if iris.IsErrPath(err) {
        fmt.Println(ctx.Request().RequestURI)
            return // continue.
    }
    ctx.StopWithError(iris.StatusBadRequest, err)
}
```

Is this really a mistake? But if I want to get into the body of the `PostTest()` method without having to define `HandleError()` how to achieve it?

**Comment by hjzCy** [comment]
In fact, my controller field has nothing to do with Post Body. I only want the properties in iris.Context. The controller defines the `Age` field for testing purposes. It may contain other struct like `sql.NullString` or other struct field.

**Comment by kataras** [comment]
Hello @hjzCy, as I explained to you in the [previous post](https://github.com/kataras/iris/issues/1699) it does NOT matter if you use the controller as body in your functions: If your controller has stateless(request-scope) fields and there is no available dependency to bind those, then it reads the request body and binds your field automatically. To ignore a field from dependency injection you can use the `ignore:"true"` struct field, e.g. `Age    sql.NullString `ignore:"true" json:"age" form:"age"``. That is your solution :)

**Comment by hjzCy** [comment]
Ow！Thank you。
