### ISSUE TITLE
Delete method  request   ..skipObjectDecoder 

### ISSUE THREAD

**Issue by zhaiyujin** [kataras/iris#1708]
When I ask  method  delete:http ://127.0.0.1:8080/admin/menu/2
response:
skipObjectDecoder: expect object or null, error found in #0 byte of ...||..., bigger context ...||...

![2021-01-20 16-31-49 的屏幕截图](https://user-images.githubusercontent.com/22185888/105158810-5616b100-5b49-11eb-934d-a3ce30b78e0a.png)

![2021-01-20 16-37-56 的屏幕截图](https://user-images.githubusercontent.com/22185888/105159188-c32a4680-5b49-11eb-8500-f96cc9ea444e.png)

**Comment by kataras** [comment]
@zhaiyujin did you find the issue in your app?
