### ISSUE TITLE
[BUG]RemoveHandler doesn't work

### ISSUE THREAD

**Issue by sado0823** [kataras/iris#1713]
**Describe the bug**
RemoveHandler occasional

**To Reproduce**
1 - my middleare
```go
"github.com/kataras/iris/v12"

func ABC(c iris.Context) {
}
```

2 - my router
func R(app *iris.Application) {
	v1 := app.Party("/api/")
	v1.Use(middleware.ABC)

         m1 := v1.Party("/m1")
         m1.get("/xxx",xxFunc).RemoveHandler(middleware.ABC)
}

**Expected behavior**
sometimes i got panic when i build, sometimes i can build successful, but remove didn't work

**Screenshots**
ABC()
![image](https://user-images.githubusercontent.com/51654192/105669041-72379b00-5f19-11eb-8143-6b84c2b5d6ad.png)

![image](https://user-images.githubusercontent.com/51654192/105669376-246f6280-5f1a-11eb-9a35-5179785e2ad2.png)

build panic
![image](https://user-images.githubusercontent.com/51654192/105669101-90050000-5f19-11eb-81dc-046ad1605efe.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5 intel cpu

**iris.Version**
github.com/kataras/iris/v12 v12.2.0-alpha2

if this `ABC()` func is not a type of `context.Handler`, why i can set `router.party.use(ABC())` successful

**Comment by kataras** [comment]
Hello @sado0823, you have right. Working for a solution right now.

**Comment by kataras** [comment]
Hello @sado0823, you have right. I pushed a fix. Thanks a lot!

An example of `RemoveHandler` is added as well.

**Comment by sado0823** [comment]
now it worked  💚

**Comment by sado0823** [comment]
hi @kataras , another question here !

this case can remove handler successful
```golang
func Route(r router.Party) {
                r.Use(middleware.Foo)
		r.Get("/foo", ctrl.Index).RemoveHandler(middleware.Foo)
}
```

but this case failed
```golang
func Route(r *iris.APIContainer) {
                r.Use(middleware.Foo)
		r.Get("/foo", ctrl.Index).RemoveHandler(middleware.Foo)
}
```

the difference is `r router.Party` and `r *iris.APIContainer`


![image](https://user-images.githubusercontent.com/51654192/109252467-917f5c00-7828-11eb-98f6-efc03787ec3b.png)

and i find that `middleware.Foo` do not in  `r.Handlers`

actually the handler that use in `app.UseGlobal(...)` can find in this `r.Handlers` ,

It bothers me a lot, and i think it is a `bug`, all the `handlers` shoud be added to `[]Handler`
