### ISSUE TITLE
RemoveHandler(myMiddleware)

### ISSUE THREAD

**Issue by cmboss** [kataras/iris#1718]
**Describe the bug**
Example: https://github.com/kataras/iris/blob/master/_examples/routing/remove-handler/main.go

---------------------------------
users.Get("/", usersIndex).RemoveHandler(myMiddleware)
Compile error!
Error "panic: remove handler: unexpected type of func(*context.Context)"

----------------------------------
users.Get("/", usersIndex).RemoveHandler("myMiddleware")

After modification, it can be compiled and passed! But you cannot delete the processor;
users.Get("/", usersIndex).RemoveHandler("myMiddleware")

**To Reproduce**
1. [...]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
windows 10
golang 1,15

**iris.Version**
github.com/k0kubun/colorstring v0.0.0-20150214042306-9440f1994b88 

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**

**Comment by tuhao1020** [comment]
@cmboss It would be much better to post your code here

**Comment by kataras** [comment]
@cmboss the example you pointed out works as expected, are you sure you are using the `master` branch? Try `go get -u github.com/kataras/iris/v12@master` that was solved a month ago.
