### ISSUE TITLE
websocket: http://localhost:8080/iris-ws.js is not found in browser

### ISSUE THREAD

**Issue by nkev** [kataras/iris#172]
I'm trying to run the example at https://github.com/iris-contrib/examples/tree/master/websocket with no success. http://localhost:8080/iris-ws.js is not found in browser (404). I tried Chrome and Safari on MacbookPro El Capitan, Go v1.6.2

**Comment by kataras** [comment]
You 've right, after last changes I broke it, fixed now, upgrade iris with ` go get -u github.com/kataras/iris` and this should works now. Thanks for the bug report!!
