### ISSUE TITLE
OnChat event can not fired using iris WebSocket with iris Router as below.

### ISSUE THREAD

**Issue by aaronchen2k** [kataras/iris#1721]
I use iris websocket with iris Router as below.
And event OnNamespaceConnected can be fired from the client, but OnChat event can not.

Vue.js code

      const events = {}
      events._OnNamespaceConnected = function (nsConn, msg) {
        if (nsConn.conn.wasReconnected()) {
          this.addMessage('re-connected after ' + nsConn.conn.reconnectTries.toString() + ' trie(s)')
        }

        this.addMessage('connected to namespace: ' + msg.Namespace)
        this.handleNamespaceConnectedConn(nsConn)
      }

      events._OnNamespaceDisconnect = function (nsConn, msg) {
        this.addMessage('disconnected from namespace: ' + msg.Namespace)
      }

      events.chat = function (nsConn, msg) { // "chat" event.
        this.addMessage(msg.Body)
      }

      const that = this
      neffos.dial(WsApi, {
          default: { // "default" namespace.
              _OnNamespaceConnected: function (ns, msg) {
                that.addMessage('connected to namespace: ' + msg.Namespace)
              },
              _OnNamespaceDisconnect: function (ns, msg) {
                that.addMessage('disconnected from namespace: ' + msg.Namespace)
              },
              chat: function (ns, msg) { // "chat" event.
                that.addMessage(msg.Body)
              }
          }
      }).then(function (conn) {
          conn.connect('default').then(that.handleNamespaceConnectedConn).catch(that.handleError)
      }).catch(that.handleError)

GO router:

    r.api.UseRouter(middlewareUtils.CrsAuth())

    app := r.api.Party("/api").AllowMethods(iris.MethodOptions)

    v1 := app.Party("/v1")

    mvcApp := mvc.New(v1.Party("/ws"))
    mvcApp.HandleWebsocket(handler.NewWsController())
    websocketServer := neffos.New(
	   gorilla.Upgrader(gorillaWs.Upgrader{CheckOrigin: func(*http.Request) bool{return true}}),
	   mvcApp)
    mvcApp.Router.Get("", websocket.Handler(websocketServer))

Go controller:

    type WsController struct {
	    BaseController
	    *neffos.NSConn `stateless:"true"`
	    Namespace string
     }

    func NewWsController() *WsController {
    	return &WsController{Namespace: "default"}
    }

    func (c *WsController) OnNamespaceConnected(msg neffos.Message) error {
	    _logUtils.Infof("%s connected", c.Conn.ID())
	    return nil
    }

    func (c *WsController) OnNamespaceDisconnect(msg neffos.Message) error {
    	_logUtils.Infof("%s disconnected", c.Conn.ID())
    	return nil
    }

    func (c *WsController) OnChat(msg websocket.Message) error {
    	_logUtils.Infof("%s", msg)
    	return nil
    }

**Comment by kataras** [comment]
Hello @aaronchen2k, you register the `OnChat` on server-side but on client-side you accept the `chat` event. There is an example already for mvc + websocket.

https://github.com/kataras/iris/blob/5fe233278a28b6b658b2cd95c8338cc1ff0aef6a/_examples/mvc/websocket/main.go#L97

https://github.com/kataras/iris/blob/5fe233278a28b6b658b2cd95c8338cc1ff0aef6a/_examples/mvc/websocket/browser/index.html#L77
