### ISSUE TITLE
[FEATURE REQUEST] httptest strict/require setting

### ISSUE THREAD

**Issue by kalmant** [kataras/iris#1722]
**Is your feature request related to a problem? Please describe.**
During testing I expected `github.com/kataras/iris/v12/httptest.Response.Status` to fail the test immediately if a different status is received. Therefore on subsequent lines I performed some operations that could result in a panic if let's say the response code was not as expected. It turns that it does not fail fast, it simply fails the test. This is because `New` configures `Expect` with `Reporter: httpexpect.NewAssertReporter(t)`.

**Describe the solution you'd like**
I would like to be able to set `Reporter` to `httpexpect.NewRequireReporter(t)`. I think this could be done by extending `Configuration` with a new field (e.g. `Require bool` or `Strict bool`) and then configuring `httpexpect.Config` using that value. I'd be happy to contribute this solution.

**Describe alternatives you've considered**
I have considered copy pasting `github.com/kataras/iris/v12/httptest.New` and manually setting `Reporter` to `httpexpect.NewRequireReporter(t)` (where `httpexpect` is actually `github.com/iris-contrib/httpexpect/v2`) by copying `httptest.New` but I think that's not the right way to go about things.

**Additional context**
None

**Comment by kataras** [comment]
Hello @kalmant, sorry for the delay. It's added, upgrade to the `@master` and you're ready to use it. The otpion name is `Strict`. Please check the [commit](https://github.com/kataras/iris/commit/d26b9bfbedfdee009c5037f8250a42f8d2322b85) to see how I did that so you can open PRs with more confident in the future. Good in-point feature request with clear "wants" and details, good job!

**Comment by kalmant** [comment]
Thanks a lot!
