### ISSUE TITLE
[QUESTION] http request input json data, exec: ctx.getStringDefault("name")  value is NULL

### ISSUE THREAD

**Issue by dafa168** [kataras/iris#1724]
**Describe the bug**

Why can't I get the value passed by http json using a series of Getxxx methods under context ？
Did I do something wrong without using the ReadJSON method?

**To Reproduce**

main.go 
```
package main

import (
	"fmt"
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/context"
)

func main() {

	app := iris.New()

	app.Get("/", func(c context.Context) {
		c.WriteString("index ...")
	})

	app.Post("/api/user", func(c context.Context) {

		fmt.Printf("path: %v", c.Path())
		fmt.Println()
		fmt.Printf("C-Values:%#+v", c.Values())
		fmt.Println()

		uid := c.Values().GetIntDefault("uid", 0)  // 获取不到值
		name := c.Values().GetStringDefault("name", "") // 获取不到值 

		c.JSON(iris.Map{"code": iris.StatusOK, "data": iris.Map{"uid": uid, "name": name}})
	})

	app.Run(iris.Addr(":3000"))
}

```

goland http test
```
POST http://localhost:3000/api/user
Content-Type: application/x-www-form-urlencoded

uid=99&name=zxc

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
  "uid": 10010,
  "name": "zxc"
}

###
```

http response  :
```
POST http://localhost:3000/api/user

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Tue, 09 Feb 2021 09:12:59 GMT
Content-Length: 39

{
  "code": 200,
  "data": {
    "name": "",
    "uid": 0
  }
}

Response code: 200 (OK); Time: 63ms; Content length: 39 bytes
```

console output : 
```
E:\gocode\src\irisdemo>go run main.go
Now listening on: http://localhost:3000
Application started. Press CTRL+C to shut down.
path: /api/user
C-Values:&memstore.Store(nil)
path: /api/user
C-Values:&memstore.Store(nil)

```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows

**iris.Version**
- e.g. github.com/kataras/iris/v12 v12.1.8 // indirect

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Comment by kataras** [comment]
Hello @dafa168,

I think you already found your issue by reading the [routing examples](https://github.com/kataras/iris/tree/master/_examples/routing). The `Values().XXX` are for **dynamic route path parameters, e.g. ` /profile/{name}` -> request: `/profile/kataras` -> `ctx.Params().Get("name")` == `kataras`.

https://github.com/kataras/iris/blob/5fe233278a28b6b658b2cd95c8338cc1ff0aef6a/_examples/routing/dynamic-path/main.go#L155-L160

To **read the URL query parameters** you have to use `ctx.URLParam/URLParamXXX` **or** `ctx.ReadQuery`. Example of ReadQuery: https://github.com/kataras/iris/blob/master/_examples/request-body/read-query.

```go
uid := ctx.URLParamIntDefault("uid",0 )
name := ctx.URLParam("name")
```
**or**

```go
type query struct {
   Uid int `url:"uid"
   Name string `url:"name"`
}

// ... inside your handler:
var data query
err := ctx.ReadQuery(&query)
```

To read the json request body you must use the `ctx.ReadJSON` method. Example can be found at: https://github.com/kataras/iris/blob/master/_examples/request-body/read-json.

**Comment by dafa168** [comment]
Okay thank you. I understand.
