### ISSUE TITLE
Allow Anchor URLs in Redirect

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#173]
Redirecting to a URL with an HTML Anchor in the URL doesn't persist the anchor.

```go
	if c.IsPost() {
		url := iris.RouteByName("myurl").GetURI(user.Username, publicID)
		fmt.Println(url) // Prints correctly.
		url = url + "#myUrlID"
		c.Redirect(url, iris.StatusFound)
	}
```

**Comment by kataras** [comment]
@ryanbyyc 
When you upgrade: 

-  GetURI renamed to ` ParseURI`  it's the right name ( the issue comments, examples, history were also updated) 

- {{ url }} support added for  pongo, jade, amber template engines also

- ` {{ url }}`  and `ParseURI` now supports custom dynamic subdomains also

As for your request:

Servers doesn't care about the hash(#), that's the reason this doesn't works for now but I will try to find a proper solution to this, stay tuned!

**Comment by kataras** [comment]
@ryanbyyc 
When you upgrade: 

-  GetURI renamed to ` ParseURI`  it's the right name ( the issue comments, examples, history were also updated) 

- {{ url }} support added for  pongo, jade, amber template engines also

- ` {{ url }}`  and `ParseURI` now supports custom dynamic subdomains also

As for your request:

Server should not care about the hash(#), that's the reason this doesn't works for now but I will try to find a proper solution to this, stay tuned!

**Comment by ryanbyyc** [comment]
Closing as not a bug, further testing shows its working properly.

**Comment by kataras** [comment]
Is it redirect correctly to ` #myurlID` ? , first time I checked it didn't redirect, maybe valyala 'fixed/changed' this behavior from inside fasthttp

**Comment by egorsmkv** [comment]
@valyala

**Comment by kataras** [comment]
@egorsmkv  Why you mention valyala? we don't have any bugs related to fasthttp, all working well, maybe my english are so bad and you understood that we have bug?

**Comment by kataras** [comment]
Let him code!! :P

**Comment by egorsmkv** [comment]
@kataras No, I think you forgot the dog near the nickname

**Comment by valyala** [comment]
I'm working on the bugfix at the moment :)

**Comment by valyala** [comment]
Fixed - see https://github.com/valyala/fasthttp/commit/efbb037c40c52079e7ba605abb055ad7470a12de and https://github.com/valyala/fasthttp/commit/033bb40f06c5c88ffa4f12c26b4eb3d8a15403b0 .

**Comment by ryanbyyc** [comment]
Thanks for the help @valyala - I had assumed the issue wasn't an issue given that redirects to /my/url/:param#312312B worked fine, but I'm glad we could satisfy more tests as a result. :D

**Comment by kataras** [comment]
@valyala Thanks you also, this will help me to simplify the domain's router also (before when I updated the uri it only accepted relative paths, now as I can see this is fixed*)
