### ISSUE TITLE
Router name in MVC

### ISSUE THREAD

**Issue by yale8848** [kataras/iris#1737]
**Is your feature request related to a problem? Please describe.**

Under code in MVC:

```
func (c *Controller) GetSomeGood() string {
	return "ok"
}

```

It mean this router:

```
http://xxxx.com/xxx/some/good
```

but i want the router like this:

```
http://xxxx.com/xxx/someGood
```

So ,can you add some custom callback function to convert custom router in `methodParser`  ?

**Comment by brookxs** [comment]
using the `BeforeActivation` to custom handle.
```go
func (c *Controller) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle(http.MethodGet, "/xxx/someGood", "GetSomeGood")
        b.Handle(http.MethodGet, "/xxx/AddSomeGood", "AddSomeGood")
}

func (c *Controller) GetSomeGood() string {
	return "ok"
}

func (c *Controller) AddSomeGood() string {
	return "ok"
}
```

**Comment by yale8848** [comment]
@brookxs Thank you very much .  `BeforeActivation` can solve this problem , but if  `methodParser `  can deal this problem by default  maybe is a better way.
