### ISSUE TITLE
[BUG] Context.Application RWMutex Lock 

### ISSUE THREAD

**Issue by o8x** [kataras/iris#1752]
**Describe the bug**
The mutex should be closed, but it doesn't

**Screenshots**
![image](https://user-images.githubusercontent.com/20666153/114482917-fa386180-9c39-11eb-97f3-88e00b5aaa91.png)

**Desktop (please complete the following information):**
 - OS: all

**iris.Version**
-  master

**Comment by o8x** [comment]
Pull Request : https://github.com/kataras/iris/pull/1753

**Comment by kataras** [comment]
PR accepted, thanks @o8x, good one.
