### ISSUE TITLE
[BUG] When Gzip is on and ctx.StatusCode(iris.StatusBadRequest), JSON value can not be returned. Only "Bad Request" is returned.

### ISSUE THREAD

**Issue by glennWang** [kataras/iris#1755]
**Describe the bug**
  When Gzip is on and ctx.StatusCode(iris.StatusBadRequest), JSON value can not be returned. Only "Bad Request" is returned.

**To Reproduce**
```
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	v1 := app.Party("/api")
	v1.Use(iris.Gzip)
	v1.Get("/hello", func(ctx iris.Context) {
		ctx.StatusCode(iris.StatusBadRequest)
		ctx.JSON(iris.Map{
			"errCode": 1001,
			"msg":     "hi I am 400",
		})
		return
	})

	app.Run(iris.Addr(":9090"))
}

```

**Expected behavior**
```
http status code: 
400

Body: 
{
    "errCode": 1001,
    "msg": "hi I am 400"
}
```

**Real behavior**
```
http status code:
400

Body:
Bad Request
```
**Note**
`curl -v http://172.17.6.4:9090/api/hello` is ok.
But when using browser, the problem will occur.

**Comment by tuhao1020** [comment]
@glennWang  what version do you use?
I don't have a `iris.Gzip` middleware, you can use `v1.Use(iris.Compression)` instead, and your issue can't be reproduced.

**Comment by glennWang** [comment]
> @glennWang what version do you use?
> I don't have a `iris.Gzip` middleware, you can use `v1.Use(iris.Compression)` instead, and your issue can't be reproduced.

`github.com/kataras/iris/v12 v12.1.8`

**Comment by tuhao1020** [comment]
you should add a configuration like below:
```
app.Run(iris.Addr(":9090"), iris.WithConfiguration(iris.Configuration{
		DisableAutoFireStatusCode:         true,
}))
```

**Comment by glennWang** [comment]
> you should add a configuration like below:
> 
> ```
> app.Run(iris.Addr(":9090"), iris.WithConfiguration(iris.Configuration{
> 		DisableAutoFireStatusCode:         true,
> }))
> ```

It works ! Thanks a lot for your patience answer.
