### ISSUE TITLE
FormValue function can not receive HTML array parameters

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#176]
@kataras `FormValue()` function is unable to receive the HTML form in the array parameter value, need to use `PostArgs().PeekMulti("test[]")` to get the value of the `[][]byte` type.
But this is not convenient, hoping to increase the `FormArrayValue()` and `FormArrayValueString()` function in the iris.
``` html
<form action="/handler" method="post">
    <input name="test[]" value="test1">
    <input name="test[]" value="test2">
    <button type="submit">submit</button>
</form>
```
``` go
	iris.Post("/handler", func(ctx *iris.Context) {
		test := ctx.PostArgs().PeekMulti("test[]")
		for k,v := range test {
			println(k, string(v))
		}
	})
```

**Comment by raitucarp** [comment]
maybe this is related issue:
https://github.com/kataras/iris/issues/104

**Comment by dxvgef** [comment]
@raitucarp Thank you for help, but I don't like to use the parameter binding structure.

**Comment by kataras** [comment]
@dxvgef  what's the problem with `ctx.PostArgs().PeekMulti("test[]") ` ?

**Comment by dxvgef** [comment]
Yes, I think this is a common operation, should be added to the iris, do you think?

**Comment by kataras** [comment]
Ok as you want my friend, but you will have to wait some days, I'm doing serious refactoring before final v3

**Comment by dxvgef** [comment]
Thank you friend, look forward to the stable version of iris v3

**Comment by kataras** [comment]
@dxvgef 

Done, remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

Read also the [HISTORY](https://github.com/kataras/iris/tree/master/HISTORY.md)

```go
context.PostFormMulti(string) // returns []string
```

**Comment by dxvgef** [comment]
Thank you :+1:

**Comment by kataras** [comment]
No problem, tell me if that suits you or you need something else, also it was an old request of yours, to get all routes , now you can with ` iris.Lookups() []Route` and to get a named-route ` iris.Lookup(routeName string) Route`

**Comment by dxvgef** [comment]
What is `iris.Lookups()` ? I think I do not need this,

**Comment by kataras** [comment]
Gives you all the route information, I think you wanted that and I told you to do it with Plugins and you didn't want so

**Comment by dxvgef** [comment]
Well, I don't need this, but I've made a note of it. Thank you for your work.

**Comment by kataras** [comment]
Yes, 1 week without internet was enough time to redesign and clean the code base :P thanks you for using iris and helps me!

**Comment by dxvgef** [comment]
I also see you have 6 days did not update the code, why is there no network it?
