### ISSUE TITLE
Swagger Plugin

### ISSUE THREAD

**Issue by Talento90** [kataras/iris#177]
First of all your framework looks awesome! 

There is any plans to create a plugin to generate swagger documentation?

:+1: :+1: :+1:

**Comment by qskousen** [comment]
I don't think there are any plans for this right now... But you can make your own plugin and share it with us! :smile:

**Comment by kataras** [comment]
Sorry @Talento90 but this is not something I will do in the near future, but as @qskousen told if you know their API you can easly create a plugin or a middleware and I will share your plugin/or/middleware  on README, examples and e-book !

Thanks for your interest
