### ISSUE TITLE
[FEATURE REQUEST]multipart/related content-type

### ISSUE THREAD

**Issue by herugen** [kataras/iris#1787]
**Is your feature request related to a problem? Please describe.**
iris cannot parse http request with content-type as multipart/related

**Describe the solution you'd like**
can handle multipart/related request and response multipart/related successfully

**Describe alternatives you've considered**
5G Service Based Interface needs multipart/related content-type

**Additional context**
none

**Comment by kataras** [comment]
Hello @TheWayYouMakeMeFeel, sorry for this kind of delay. I've just pushed a commit for a new `Context.ReadMultipartRelated` method wihch may help you.

**Comment by herugen** [comment]
Sorry for my late, really appreciate your updates

**Comment by kataras** [comment]
No worries, you are welcome @herugen!
