### ISSUE TITLE
Something tampered router map

### ISSUE THREAD

**Issue by lanser-z** [kataras/iris#1796]
We build project on "iris@v11.1.1+incompatible". Registered most HTTP handlers (>400) with MVC and less than 10 handlers with `app.Handle`.
After the system run some time, we found some handler return 404. By debuging in `func (h *routerHandler) HandleRequest(ctx context.Context) ` and tracing `h.trees`, I found some keys and fields of the value in router map is tampered. Following is the structure of h.trees:
```
type routerHandler struct {
	trees []*trie
	hosts bool // true if at least one route contains a Subdomain.
}
```
and structure of trie and trieNode:

```
type trie struct {
	root *trieNode

	// if true then it will handle any path if not other parent wildcard exists,
	// so even 404 (on http services) is up to it, see trie#insert.
	hasRootWildcard bool
	hasRootSlash    bool

	method string
	// subdomain is empty for default-hostname routes,
	// ex: mysubdomain.
	subdomain string
}

type trieNode struct {
	parent *trieNode

	children               map[string]*trieNode
	hasDynamicChild        bool     // does one of the children contains a parameter or wildcard?
	childNamedParameter    bool     // is the child a named parameter (single segmnet)
	childWildcardParameter bool     // or it is a wildcard (can be more than one path segments) ?
	paramKeys              []string // the param keys without : or *.
	end                    bool     // it is a complete node, here we stop and we can say that the node is valid.
	key                    string   // if end == true then key is filled with the original value of the insertion's key.
	// if key != "" && its parent has childWildcardParameter == true,
	// we need it to track the static part for the closest-wildcard's parameter storage.
	staticKey string

	// insert data.
	Handlers  context.Handlers
	RouteName string
}
```

Some one tampered `trieNode.children` and 2 of 10 keys became "", while some field e.g. `trieNode.RouterName` became "".
I don't know how to trace the bug, any suggestion is appreciated.

**Comment by kataras** [comment]
@lanser-z try to reproduce the same with the `master` [version](https://github.com/kataras/iris#-learning-iris) or v12+ of Iris and write down if you still having issues with that one. The `iris@v11.1.1+incompatible` is not supported (years old).
