### ISSUE TITLE
Layout specific to party

### ISSUE THREAD

**Issue by qskousen** [kataras/iris#180]
Feature Request: I think it would be useful to be able to set a layout per party, to override the default layout, the way you can in render calls. This way, say you have a party for an admin back end, you would want it to all have the same layout but different from the front end.

On a call to render, it will check: 
1. Does the Render call have a layout specified? If so, use that.
2. Is it in a party? If so, does the party have a layout specified? If so, use that.
3. If none of the above, use the default layout.

I hunted around to check if this already exists but couldn't find anything. If I missed it, let me know!

**Comment by kataras** [comment]
@qskousen Thanks for the request, it seems nice although you can already do this with one per-party custom middleware.

So you suggest a second optional parameter in the ` .Party("/myparty","theLayout.html")...` how you imagine it ? we will do this

**Comment by qskousen** [comment]
Thanks for the work!

For the party layout, the second optional parameter would be fine, or an option you can set on the party. Either one.

**Comment by kataras** [comment]
> Thanks for the work!

Thanks you, I didn't had internet connection for almost a week it was time to clean the code base a little :P 

> or an option you can set on the party 

What do you mean ?

**Comment by kataras** [comment]
Done, take a look at [this example](https://github.com/iris-contrib/examples/blob/master/templates_2/main.go) , thanks you!!
