### ISSUE TITLE
[BUG]支持黑命贵傻逼，送命去吧

### ISSUE THREAD

**Issue by niaiwomattt** [kataras/iris#1806]
傻逼，竟然支持黑命贵；
黑人到你家操了你妈，杀了你爸，你还说黑人命贵，请支持黑人？请释放黑人？请黑人继续杀人？
傻逼玩意，老子支持黑命贵的都是傻逼，都该被黑人干死！

**Comment by lxjcxj** [comment]
Yes.We all discriminate against blacks.

**Comment by niaiwomattt** [comment]
> Yes.We all discriminate against blacks.

**Comment by niaiwomattt** [comment]
我不支持黑命贵，我支持人人平等。

**Comment by niaiwomattt** [comment]
激动了，想想还是关了吧！我要在中国反对，国外还是算了，没我啥事！

**Comment by lxjcxj** [comment]
Blacks are monkeys.

**Comment by absurdm** [comment]
> 我不支持黑命贵，我支持人人平等。

![image](https://user-images.githubusercontent.com/18637223/130171267-e8e51174-7319-4c31-b7fe-13689b0e76d9.png)
还有后半句, 支持人人司法平等
