### ISSUE TITLE
[BUG] Wrong routing for different methods

### ISSUE THREAD

**Issue by mahyari** [kataras/iris#1815]
**Describe the bug**
I defined same route with different http method to serve and modify the entity. It was ok about a month ago but now, for example it route GET request to wrong method.

**To Reproduce**
1. Definition of routes
```
root := app.Party("/root")
	{
		root.Get("/xx/yy", func(ctx *context.Context) {
			logger.Debugln("GET route is called")
		})
		root.Post("/xx/yy", func(ctx *context.Context) {
			logger.Debugln("POST route is called")
		})
	}
```
2. Call `http://localhost/root/xx/yy` as GET Request
3. "POST route is called" log wrote

**Expected behavior**
Write correct log based on request.

**Desktop (please complete the following information):**
 - OS: Its occurred on both Linux as production environment and windows as development environment.

**iris.Version**
v12.2.0-alpha

**Comment by mahyari** [comment]
I found the line cause the problem. I configure AllowMethods to support CORS
```
    app.AllowMethods(iris.MethodOptions, iris.MethodGet, iris.MethodPost, iris.MethodPut, iris.MethodDelete, iris.MethodHead)
```
when I comment above code everything work correctly but uncomment it cause the error

**Comment by kataras** [comment]
If you use `AllowMethods` this enables routing access through all given http verbs to all routes under this Party/Group of routes.
