### ISSUE TITLE
Switch from Jsoniter to Goccy to improve performance and comply with standard json

### ISSUE THREAD

**Issue by TechMaster** [kataras/iris#1818]
I know Iris frameworks is using [https://github.com/json-iterator/go](https://github.com/json-iterator/go). In my recent benchmark, I found that [https://github.com/goccy/go-json](https://github.com/goccy/go-json) has better performance at all test cases. goccy/go-json is fully compatible with standard library encoding/json.

Do you have plan to switch to [https://github.com/goccy/go-json](https://github.com/goccy/go-json)?

```
Benchmark_Goccy_JSON2Struct-8            1442637               826.7 ns/op
Benchmark_Goccy_JSON2Map-8                488211              2304 ns/op

Benchmark_Default_JSON2Struct-8           361782              3146 ns/op
Benchmark_Default_JSON2Map-8              222560              5188 ns/op

Benchmark_Jsoniter_JSON2Struct-8          812524              1355 ns/op
Benchmark_Jsoniter_JSON2Map-8             387609              2794 ns/op
```

**Comment by kataras** [comment]
Hey @TechMaster,

I don't see huge differences in my tests between jsoniter and goccy-json but still goccy-json is a bit faster, we can replace jsoniter with goccy when `app.Listen(..., iris.WithOptimizations)`.

**Comment by TechMaster** [comment]
Great jobs Kataras,

Highly appricate your prompt action !

**Comment by kataras** [comment]
No problem @TechMaster. I found a serious bug on that library though... on big objects it duplicates some of the fields of the entities of a slice. When I remove the go-json and replace it with jsoniter(=undo the change we've made on alpha3) or standard library the json body displays as it should be. Based on that, I have to revert this change this weekend...
