### ISSUE TITLE
compilation to run on android ?

### ISSUE THREAD

**Issue by joeblew99** [kataras/iris#182]
Congrats on this project. It looks really great. i think i can help write plugind that work with react and alm. I did not know about alm until now and its really interesting.

SO, the question:
I am wondering i can cross compile using gomobile, and it will run the "server" on an android phone ?

**Comment by kataras** [comment]
@joeblew99  It should runs because at the first days I tried with an emulator and worked, I have a samsung which costs $20 so I can't tell you with percision if this really works now. If you could test this for me it will be nice, thanks you!!

**Comment by kataras** [comment]
@joeblew99  It should runs because at the first days I tried with an emulator and worked, I have a samsung which costs $20 so I can't tell you with percision if this really works now. If you could test this for me and verify if running/or/not running here, it will be nice, thanks you!!

**Comment by joeblew99** [comment]
@kataras thanks

I have a nexus 6, and will test it now. Should be a good test since its stock android.

Could you write up i the readme or maybe "deployment-mobile.md" about the way you compiled and tested it for android ?
I am going to try to wrap this with a react front end, and a bolt DB backend on mobiles.
I have boltDB working on ios and android already.

In the end it measn we have a stack that can run 100% offline on mobiles, which is my aim.

**Comment by joeblew99** [comment]
did you mean to clsoe this ?

**Comment by kataras** [comment]
I added this as feature request, because I am not sure if running anymore on mobile I made a lot of changes the last 3 months.  When I will have time I will try to give a nice tutorial about mobile deployment, if you wanna test it before me, do it!

**Comment by joeblew99** [comment]
Fair enough. I will give it a go and or any tests and readme I write on it.
Best to leave this open for now

**Comment by kataras** [comment]
@joeblew99 After a year,  but never too late. I did buy a good android phone and I did the experimental, no need of gomobile. **It just works** follow the link to learn how: https://twitter.com/MakisMaropoulos/status/885835216358703104
