### ISSUE TITLE
[QUESTION] websockt in v12

### ISSUE THREAD

**Issue by culion-bear** [kataras/iris#1825]
我发现针对v12版本的websocket文档有些过于简陋了
I found the article about websockt  on the wiki to be rather sketchy.

并且它是针对neffos所撰写的而不是封装后的v12/websocket
And this article is mainly about neffos (go get github.com/kataras/neffos) rather than v12/websocket(github.com/kataras/iris/v12/websocket)

请问一下您有没有关于v12版本封装下websocket聊天室的例子
Do you have any examples of websocket chat rooms demo in V12

**Comment by kataras** [comment]
Hello @culion-bear ,

You can follow these example: https://github.com/kataras/iris/tree/master/_examples/websocket/basic, https://github.com/kataras/iris/tree/master/_examples/websocket/online-visitors and https://github.com/neffos-contrib/bootstrap-chat

**Comment by culion-bear** [comment]
@kataras thank you for your answer!I found a good solution! thank you!
