### ISSUE TITLE
[BUG] c.ServeFile() returns Content-Type header as file name, not MIME type.

### ISSUE THREAD

**Issue by kaibox-git** [kataras/iris#1829]
**Describe the bug**
Function c.ServeFile() returns Content-Type header as file name, not MIME type.

**To Reproduce**
func handler(ctx iris.Context) {
    ctx.ServeFile("./public/main.js")
}
It will return header "Content-Type" = "main.js; charset=utf-8"
So a browser blocks handling the file and writes in console:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "main.js". Strict MIME type checking is enforced for module scripts per HTML spec."

**Expected behavior**
In this case Gin's function c.File() returns "Content-Type" = "text/javascript; charset=utf-8"
and for css files: "text/css; charset=utf-8"

**Desktop (please complete the following information):**
 - OS: ubuntu

**iris.Version**
v12.2.0-alpha4

**Comment by kataras** [comment]
Thanks @kaibox-git, this is fixed now.
