### ISSUE TITLE
Iris logger causing panic?

### ISSUE THREAD

**Issue by ryanlath** [kataras/iris#183]
I was benchmarking Iris with "ab" and noticed I was getting some failed requests (anywhere from 5-70% with this command: 

> ab -c 20 -n 1000 http://nas:5006/

).  I then noticed Iris throwing an error.  I traced it back to this line:  

> iris.Use(logger.New(iris.Logger()))

.   I'm new to the Go language and the stack trace is foreign to me. 

Simple example that produces it...
```
package main

import (
        "github.com/kataras/iris"
        "github.com/kataras/iris/middleware/logger"
)

func main() {
        // this line seems to be the issue...
        iris.Use(logger.New(iris.Logger()))

        iris.Get("/", home)
        iris.Listen(":5006")
}

func home(ctx *iris.Context){
    ctx.Write("HOME: From %s", ctx.PathString())
}
```
Console error message:
`2016/06/11`` 20:37:23 panic: runtime error: index out of range
Stack trace:
goroutine 60 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc820214700, 0xc820289ee0)
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/workerpool.go:207 +0x53
panic(0xa96be0, 0xc82000a070)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/fatih/color.(*Color).sequence(0xc820201000, 0x0, 0x0)
        /var/www/cms/go-test/src/github.com/fatih/color/color.go:239 +0x1a8
github.com/fatih/color.(*Color).format(0xc820201000, 0x0, 0x0)
        /var/www/cms/go-test/src/github.com/fatih/color/color.go:256 +0x57
github.com/fatih/color.(*Color).Set(0xc820201000, 0x2)
        /var/www/cms/go-test/src/github.com/fatih/color/color.go:123 +0x49
github.com/fatih/color.(*Color).Printf(0xc820201000, 0xbdacb0, 0x14, 0xc8202898d0, 0x6, 0x6, 0x0, 0x0, 0x0)
        /var/www/cms/go-test/src/github.com/fatih/color/color.go:168 +0x61
github.com/kataras/iris/logger.(*Logger).Printf(0xc820079050, 0xbdacb0, 0x14, 0xc8202898d0, 0x6, 0x6)
        /var/www/cms/go-test/src/github.com/kataras/iris/logger/logger.go:78 +0xb9
github.com/kataras/iris/logger.(*Logger).Otherf(0xc820079050, 0xbdacb0, 0x14, 0xc8202898d0, 0x6, 0x6)
        /var/www/cms/go-test/src/github.com/kataras/iris/logger/logger.go:167 +0xdb
github.com/kataras/iris/middleware/logger.(*loggerMiddleware).Serve(0xc8201ff570, 0xc82024c060)
        /var/www/cms/go-test/src/github.com/kataras/iris/middleware/logger/logger.go:78 +0x780
github.com/kataras/iris/middleware/logger.(*loggerMiddleware).Serve-fm(0xc82024c060)
        /var/www/cms/go-test/src/github.com/kataras/iris/middleware/logger/logger.go:99 +0x2a
github.com/kataras/iris.HandlerFunc.Serve(0xc8201ff580, 0xc82024c060)
        /var/www/cms/go-test/src/github.com/kataras/iris/handler.go:61 +0x26
github.com/kataras/iris.(*Context).Do(0xc82024c060)
        /var/www/cms/go-test/src/github.com/kataras/iris/context.go:100 +0x5d
github.com/kataras/iris.(*tree).serve(0xc8200177a0, 0xc8201f3680, 0xc8205a4078, 0x1, 0xc82024c101)
        /var/www/cms/go-test/src/github.com/kataras/iris/tree.go:110 +0x1c8
github.com/kataras/iris.(*router).serveFunc(0xc820214400, 0xc8201f3680)
        /var/www/cms/go-test/src/github.com/kataras/iris/router.go:260 +0x25a
github.com/kataras/iris.(*router).(github.com/kataras/iris.serveFunc)-fm(0xc8201f3680)
        /var/www/cms/go-test/src/github.com/kataras/iris/router.go:103 +0x2a
github.com/valyala/fasthttp.(*Server).serveConn(0xc820236000, 0x7f137ddc8000, 0xc82021c028, 0x0, 0x0)
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/server.go:1494 +0x963
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x7f137ddc8000, 0xc82021c028, 0x0, 0x0)
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/server.go:1223 +0x42
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc820214700, 0xc820201b80)
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/workerpool.go:224 +0x11c
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc820214700, 0xc820201b80, 0x94bea0, 0xc820201b80)
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/workerpool.go:183 +0x2b
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /var/www/cms/go-test/src/github.com/valyala/fasthttp/workerpool.go:185 +0x1e9

**Comment by qskousen** [comment]
Can you try this: iris.Use(logger.Logger())

**Comment by ryanlath** [comment]
Get this error:
```
# command-line-arguments
./test.go:11: undefined: "github.com/kataras/iris/middleware/logger".Logger
```

**Comment by qskousen** [comment]
Sorry, this one: `iris.UseFunc(logger.Default())`

**Comment by ryanlath** [comment]
Similar error:
```
# command-line-arguments
./test.go:12: undefined: "github.com/kataras/iris/middleware/logger".Default
```

**Comment by qskousen** [comment]
Sorry, I guess I have an older version! That is working on mine.

**Comment by kataras** [comment]
@ryanlath Did you run benchmarks with logger enabled?... anyway if you could wait some days more I will commit the next version and this should be fixed (although is third-party library bug not Iris but I think I found a temp fix)  Thanks for your issue, I will notice you here, when time comes

**Comment by ryanlath** [comment]
Yes, logger enabled seemed to cause it.  Look forward to your fix.

**Comment by kataras** [comment]
@ryanlath 
@es-lab  Upgrade iris 
remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

and verify if this problem is fixed, please, thanks you!

**Comment by ryanlath** [comment]
No panic, but now I'm, getting this:
```
# command-line-arguments
./test.go:10: cannot call non-function iris.Logger (type *"github.com/kataras/iris                    /logger".Logger)
```

**Comment by qskousen** [comment]
Correct, the format for logging has changed from
```go
iris.Logger().Println("Notice")
```
to
```go
iris.Logger.Println("Notice")
```
You just need to remove the parenthesis.

**Comment by kataras** [comment]
@ryanlath Read the [HISTORY](https://github.com/kataras/iris/tree/master/HISTORY.md) my friend and verify if this problem is not worry us anymore

**Comment by milchinskiy** [comment]
I have the same issue:

```
2016/07/06 19:46:04 panic: No tokens found
Stack trace:
goroutine 7623 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/debug/stack.go:24 +0x80
esp-server/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc820241380, 0xc8204a3ee0)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/workerpool.go:207 +0x53
panic(0x681e40, 0xc8204a1a40)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
esp-server/vendor/github.com/kataras/iris/logger.(*Logger).Panic(0xc82027be10, 0x681e40, 0xc8204a1a40)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/kataras/iris/logger/logger.go:129 +0xb7
esp-server/middlewares.(*AuthDevice).Serve(0xd50fa8, 0xc820298780)
	/Volumes/Development/projects/golang/src/esp-server/middlewares/auth-device.go:24 +0x1eb
esp-server/vendor/github.com/kataras/iris.(*Context).Do(0xc820298780)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/kataras/iris/context.go:134 +0x5d
esp-server/vendor/github.com/kataras/iris.(*serveMux).ServeRequest.func3(0xc820510000)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/kataras/iris/http.go:1365 +0x462
esp-server/vendor/github.com/valyala/fasthttp.(*Server).serveConn(0xc82029f400, 0x1a40000, 0xc82044a020, 0x0, 0x0)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/server.go:1504 +0x973
esp-server/vendor/github.com/valyala/fasthttp.(*Server).(esp-server/vendor/github.com/valyala/fasthttp.serveConn)-fm(0x1a40000, 0xc82044a020, 0x0, 0x0)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/server.go:1223 +0x42
esp-server/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc820241380, 0xc8202e29c0)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/workerpool.go:224 +0x11c
esp-server/vendor/github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc820241380, 0xc8202e29c0, 0x64f1a0, 0xc8202e29c0)
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/workerpool.go:183 +0x2b
created by esp-server/vendor/github.com/valyala/fasthttp.(*workerPool).getCh
	/Volumes/Development/projects/golang/src/esp-server/vendor/github.com/valyala/fasthttp/workerpool.go:185 +0x1e9
```

In /Volumes/Development/projects/golang/src/esp-server/middlewares/auth-device.go:24 is the next:

`iris.Logger.Panic("XXX")`

I'm confused, because seems like only Println method working correctly. Do you have some ETA when this issue will be fixed? Maybe using another logging pkg will be enough?

**Comment by kataras** [comment]
Man, why is that a bug? you propably call ` iris.Logger.Panic`  from your custom middleware: `/Volumes/Development/projects/golang/src/esp-server/middlewares/auth-device.go`  what did you expected to do ?

**Comment by milchinskiy** [comment]
Oh, my fault, sorry. But I have tried with Warningf() and I've got the sane result...
