### ISSUE TITLE
[BUG] - RegisterDependency MVC

### ISSUE THREAD

**Issue by VDVT** [kataras/iris#1839]
**Describe the bug**
I try to register two interface repositories and both inherit from the base repository
![image](https://user-images.githubusercontent.com/18101217/150834785-bae5f11e-becb-468b-af1b-491cfcd20fb7.png)

![image](https://user-images.githubusercontent.com/18101217/150834942-bd432fc9-9498-4ee6-8829-86275ca1cc71.png)

But when I use the ICampaignRepository interface in the controller, all the methods were implemented by TestCampaign Repository instead of CampaignRepository
![image](https://user-images.githubusercontent.com/18101217/150835538-8adf1d08-67a7-4965-89ce-25fe9928c9fe.png)
![image](https://user-images.githubusercontent.com/18101217/150835566-e13bdcc9-898c-4adc-b6a3-5229dcdd99d6.png)

**Comment by kataras** [comment]
Hello @VDVT this is not a bug, if two dependencies are implement the same exact interface and the method accepts that interface, then which should be picked up? It can't be figured, so the latest instance which implements the interface will be used. Solution: remove the `testRepository` dependency and inject it only based on a filter (if statement) of your configuration (e.g. test env or debug env).

**Comment by kataras** [comment]
Hello @VDVT this is not a bug, if two dependencies are implement the same exact interface and the method accepts that interface, then which one should be picked up? It can't be figured, so the latest instance which implements the interface will be used. Solution: remove the `testRepository` dependency and inject it only based on a filter (if statement) of your configuration (e.g. test env or debug env). Another solution, which I can implement on the next minor version, would be to, optionally, give names to dependencies and controller's fields to match.

**Comment by kataras** [comment]
Hello @VDVT,

There is an update that I think can provide you a solid solution for the above issue, please read more at :https://github.com/kataras/iris/issues/1842
