### ISSUE TITLE
Subdomains problem

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#184]
I have a problem using my subdomains while having a get request to the "/" (root) of my website.
It seems like it resets all my subdomains "/"(root) routes and every request to a route of a subdomain is using the main "/" (root) method (so I get the same response of the first page).

Removing the "/" route is making all my "/"(root) subdomains routes work perfectly. What could be the problem?

2 weeks ago everything worked perfectly with my setup, and now after an update of the library, my setup is no longer working.
Please help.

**Comment by es-lab** [comment]
This is a portion of code taken from the Iris Book examples. My website should have a structure like this. This code is working as expected but, the fact is that my project is huge and I tried to separate the initialization of routes in separate places.

	app := iris.New()
	
	system := app.Party("system.domain.local")
	{
		system.Get("/", func(c *iris.Context) {
			c.Write("HEY FROM system")
		})
	}
	admin := app.Party("admin.domain.local")
	{
		admin.Get("/", func(c *iris.Context) {
			c.Write("HEY FROM admin")
		})
	}
	dashboard := app.Party("dashboard.domain.local")
	{
		dashboard.Get("/", func(c *iris.Context) {
			c.Write("HEY FROM dashboard")
		})
	}
	

	app.Get("/", func(c *iris.Context) {
		c.Write("HEY FROM frontend /")
	})

	app.Listen(":80")
<br/>

This is my initialization. In my main.go file I have this 4 methods:

	app := iris.New()
	
	_system.Setup(app)
	_admin.Setup(app)
	_dashboard.Setup(app)
	_frontend.Setup(app)
	
	app.Listen(":80")


This is the setup method in my System module:

	func Setup(this *iris.Iris) {
		system := this.Party("system.domain.local")
		{
			ctrl.NewSY_IndexController(system)
		}
	}

And this is the System controller's routes initialization:

	func NewSY_IndexController(this iris.IParty) {
		ctrl := &SY_IndexController{NewSY_BaseController()}
		
		this.Get("/", ctrl.getIndex)
		/* other routes */
	}

	func (this *SY_IndexController)getIndex(c *iris.Context) {
		c.Write("From %s system", c.PathString())
	}

Here is my Frontend module setup:

	func Setup(this *iris.Iris) {
		frontend := this.Party("/")/* I'm using a party here because I want to group some routes and set some middlewares */
		{
			ctrl.NewIndexController(frontend)
		}
	}

And here is my Fronend controller's routes initialization:

	func NewIndexController(this iris.IParty) {
		ctrl := &IndexController{NewBaseController()}
		this.Get("/", ctrl.getIndex)
		/* other routes */
	}

	func (this *indexController)getIndex(c *iris.Context) {
		c.Write("From %s frontend", c.Request.URI())
	}


The problem is that my subdomains are not bound correctly, and accessing system.domain.local is getting back the response from the domain.local.

All my subdomains can coexists together till adding the main domain, it overrides everything.

**Comment by kataras** [comment]
@es-lab  Upgrade iris 
remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

and verify if this problem is fixed, please, thanks you!

**Comment by es-lab** [comment]
Hi, 
I've upgraded Iris, but the problem wasn't in this, I found out that declaring Static files is broking all my  subdomain routes. Commenting them out solved the problem. Maybe this is a bug, idk. 
This is my main func:

	func main() {
		app := iris.New()

		app.Config.Render.Template.Engine = iris.PongoEngine;

		/*
		 * Setup static files
		 */
		//app.Static("/assets", "./public/assets", 1)
		//app.Static("/upload_resources", "./public/upload_resources", 1)
	
		/*
		 * Setup middleware
		 */
		app.Use(&middleware.Secure{}) // xss and others
		app.Use(&middleware.CSRF{})

		/*
		 * Setup routes
		 */
		_system.Setup(app)
		_admin.Setup(app)
		_dashboard.Setup(app)
		_frontend.Setup(app)

		/*
		 * Run
		 */
		println("Listening...")
		app.Listen("domain.local:80")
	}

How should I use my static files now, javascripts, css, etc.

**Comment by kataras** [comment]
The static is on domain not at subdomain level, right? each subdomain has it's own statics and methods, it shouldn't be a problem, can you show me a snippet of the rest of the code? ( how you initialize subdomains, before static? after static , before global middleware?)

**Comment by es-lab** [comment]
Here is my system setup:

	func Setup(app *iris.Framework) {
		/*
		 * Init Routes
		 */
		system := app.Party("system.")
		{
			ctrl.NewSY_UsersController(app, system)
		}
	}

Here is the controller/routes initialization:

	 type SY_UsersController struct {
	}

	 func NewSY_UsersController(app *iris.Framework, p iris.MuxAPI) {
		ctrl := &SY_UsersController{}

		p.Get("/", ctrl.getIndex)
		p.Post("/", ctrl.postIndex)
	}

	 func (this *SY_UsersController)getIndex(c *iris.Context) {
	
		c.Write("From %s system", c.PathString())
	}

	 func (this *SY_UsersController)postIndex(c *iris.Context) {

		c.Write("From %s post system", c.PathString())
	}

Same is for Admin setup and Dashboard setup.
And my frontend setup looks like this:

	func Setup(app *iris.Framework) {
		/*
		 * Init Routes
		 */
		 // Idk if this is 100% correct, but I'd like to use some middlewares 
		 // here to group some of the routes. The only way I could make it work 
		 // is with an empty string  as parameter of party.
		frontend := app.Party("")
		{
			ctrl.NewIndexController(app, frontend)
		}
	}

Frontend controller/routes initialization:

	type IndexController struct {
	}

	func NewIndexController(app *iris.Framework, p iris.MuxAPI) {
		ctrl := &IndexController{}
	
		p.Get("/", ctrl.getIndex)
		p.Get("/test", ctrl.getTest)
	}

	func (this *IndexController)getIndex(c *iris.Context) {
		c.Write("From %s frontend", c.PathString())
	}

	func (this *IndexController)getTest(c *iris.Context) {
		c.Write("From %s frontend test", c.PathString())
	}

I'm deploying it on my virtualbox machine, I've setup the hosts of my macbook to the next one:
192.168.1.107 domain.local
192.168.1.107 dashboard.domain.local
192.168.1.107 admin.domain.local
192.168.1.107 system.domain.local

In my VB machine hosts file I've put only this (without this I can not start the app, it says port 80 is already taken):
192.168.1.107 domain.local
#192.168.1.107 dashboard.domain.local
#192.168.1.107 admin.domain.local
#192.168.1.107 system.domain.local

Setting the others too didn't change anything, so the problem may be another.

**Comment by kataras** [comment]
@es-lab Hello, first I wanted to know:
-  why you reference this issue to the 'Hot Reload' feature request ?

Secondly, `  frontend := app.Party("")` This is invalid.
Look, your default 'app' is already a `Party` which has "/", so use `app.Get/Post` , you don't need to create a new party with invalid path.

Except that I don't see any invalid code in the code snippet, parties are working and well tested.

the ` Static` is not the problem if you declare them before middlewares and other routes. Try remove the Party("") and test again, the root group you are looking for is the ` app.`

**Comment by es-lab** [comment]
Sorry for the reference, I copied the IPs from my hosts file and they were commented with hashtags, this caused the reference to the issue. I replaced them after.

Removing the party("") didn't solve the problem.

I tried this example, taken from you examples repo. Setting the static files here is causing the same problem. My root routes are breaking my subdomain routes.

	func main() {
		app := iris.New()

		/*
		 * Setup static files
		 */
		//app.Static("/assets", "./public/assets", 1)
		//app.Static("/upload_resources", "./public/upload_resources", 1)

		dashboard := app.Party("dashboard.")
		{
			dashboard.Get("/", func(c *iris.Context) {
				c.Write("HEY FROM dashboard")
			})
		}
		system := app.Party("system.")
		{
			system.Get("/", func(c *iris.Context) {
				c.Write("HEY FROM system")
			})
		}

		app.Get("/", func(c *iris.Context) {
			c.Write("HEY FROM frontend /")
		})

		app.Listen("orarmd.local:80")
	}

**Comment by kataras** [comment]
@es-lab ` app.Listen("domain.local:80")` breaks your code

**Comment by es-lab** [comment]
@kataras `app.Listen("domain.local:80")` is already listening on my domain. I don't understand what do you mean saying to use a domain instead of subdomain.

**Comment by kataras** [comment]
@es-lab You don't have anything that I haven't test already, this was the only one, let me test it now I can

**Comment by kataras** [comment]
@es-lab Sorry these days, I didn't listen you I though you had something wrong in your rest of your configuration. This is really a bug, static with subdomains it shouldn't be a problem but it is I will fix it stay tunned! this is first priority for me

**Comment by kataras** [comment]
@es-lab  Done, is working now, example of your case is here: https://github.com/iris-contrib/examples/tree/master/subdomains_1_1 . Thanks you!! (verify if that is working on you also)

**Comment by kataras** [comment]
@es-lab  Done, is working now, just upgrade ` go get -u github.com/kataras/iris` . Example of your case lives here: https://github.com/iris-contrib/examples/tree/master/subdomains_1_1 . Thanks you!! (verify if that is working on you also)

**Comment by es-lab** [comment]
@kataras Yes, now it is working. Thanks for help and support!!

**Comment by kataras** [comment]
It's my pleasure, thanks for trusting Iris!
