### ISSUE TITLE
[BUG]go-redis session.Clear() not work

### ISSUE THREAD

**Issue by johntostring** [kataras/iris#1841]
**Describe the bug**
https://github.com/kataras/iris/blob/4899fe95f47dfb8ce1f309c5ba267a7ecd0e08ba/sessions/sessiondb/redis/database.go#L275

Seems like `sid` needs to be prefixed(`makeSID(sid)`)?

**Comment by johntostring** [comment]
or just `db.Delete(sid, key)`

**Comment by kataras** [comment]
@johntostring sorry for so late answer, fixed on `/v12@master` version.

**Comment by kataras** [comment]
@johntostring sorry for so delayed response, fixed on `/v12@master` version.
