### ISSUE TITLE
[BUG]go-redis driver does not set the Redis password correctly

### ISSUE THREAD

**Issue by johntostring** [kataras/iris#1844]
**Describe the bug**

https://github.com/kataras/iris/blob/4899fe95f47dfb8ce1f309c5ba267a7ecd0e08ba/sessions/sessiondb/redis/driver_goredis.go#L87-L89

**Comment by kataras** [comment]
Oh @johntostring  this was on the`mergeClusterOptions` function. It's fixed now. Thank you a lot and sorry for the delayed response!
