### ISSUE TITLE
[FEATURE REQUEST]support golang 1.18 generics

### ISSUE THREAD

**Issue by Nyx2022** [kataras/iris#1846]
i wish iris new version can support golang 1.18 generics feature ,such as *iris.Application | router.Party ,thank you

**Comment by kataras** [comment]
Hello @Nyx2022,

Years ago, when I designed Iris I was thinking with generics-way (I was coming from C# world) but then I adapted myself to write in Go/interfaces-way. Now that generics are in beta state and I've already working with them in a personal project, I am thinking where we can use generics to Iris code base but that doesn't mean that we must replace everything with generics. I am expecting you and the rest of the community to recommend exact methods that you want Iris to support generics, e.g. ctx.JSON

Thanks for opening that one!

**Comment by kataras** [comment]
Hello @Nyx2022,

Years ago, when I designed Iris I was thinking with generics-way (I was coming from C# world) but then I adapted myself to write in Go/interfaces-way. Now that generics are in beta state and I've already work with those in a personal project, I am thinking where we can use generics to Iris code base but that doesn't mean that we must replace everything with generics. I am expecting you and the rest of the community to recommend exact methods that you want Iris to support generics, e.g. ctx.JSON

Thanks for opening that one!

**Comment by kataras** [comment]
Idea that you can implement now @Nyx2022:

```go
package your_package

import (
	"github.com/kataras/iris/v12/context"
	"github.com/kataras/iris/v12/x/errors"
)

var ErrorHandler context.ErrorHandler = context.ErrorHandlerFunc(errors.InvalidArgument.Err)

type (
	Handler[Request any | *context.Context, Response any] func(Request) (Response, error)
	HandlerWithCtx[Request any, Response any]             func(*context.Context, Request) (Response, error)
)

func HandleContext[Request any, Response any](handler HandlerWithCtx[Request, Response]) context.Handler {
	return func(ctx *context.Context) {
		var req Request
		if err := ctx.ReadJSON(&req); err != nil {
			errors.InvalidArgument.Details(ctx, "unable to parse body", err.Error())
			return
		}

		resp, err := handler(ctx, req)
		if err != nil {
			ErrorHandler.HandleContextError(ctx, err)
			return
		}

		if _, err = ctx.JSON(resp); err != nil {
			errors.Internal.Details(ctx, "unable to parse response", err.Error())
			return
		}
	}
}

func Handle[Request any, Response any](handler Handler[Request, Response]) context.Handler {
	return HandleContext(func(_ *context.Context, req Request) (Response, error) { return handler(req) })
}

```

Usage Code:

```go
import (
	"your_package"
	"github.com/kataras/iris/v12"
)

type (
	Req struct {
		Email string `json:"email"`
	}

	Res struct {
		Verified bool `json:"verified"`
	}
)

func main() {
	app := iris.New()
	app.Post("/", your_package.Handle(handler))
	app.Listen(":8080")
}

func handler(req Req) (Res, error){
	verified := req.Email == "iris-go@outlook.com"
	return Res{Verified: verified}, nil
}
```

Example response:

```json
{
    "verified": true
}
```
