### ISSUE TITLE
has validation removed from  ReadJSON ?

### ISSUE THREAD

**Issue by dmwin72015** [kataras/iris#1849]
**Describe the bug**
demo in https://github.com/kataras/iris/blob/master/_examples/request-body/read-json-struct-validation/main.go 

validation not work, if use ReadQuery it will be ok

**To Reproduce**
1. go mod init demo
2. go get -u github.com/kataras/iris/v12@master
3. go get github.com/go-playground/validator/v10
4. copy the code to main.go
5. go run main.go
6. send post request http://localhost:8080/user

**Expected behavior**
validation will be work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**iris.Version**
- v12.2.0-alpha6.0.20220219122634-980c889f8d9e

Please make sure the bug is reproducible over the `master` branch:

**Additional context**

**Comment by dmwin72015** [comment]
check the old code , i found the problem, 
in version v12.2.0-alpha5 ReadJSON   `return ctx.UnmarshalBody(outPtr, UnmarshalerFunc(unmarshaler))`. 
in version v12.2.0-alpha6 ReadJSON   `return decodeFunc(ctx.request.Context(), outPtr)`

validation method `ctx.app.Validate` only in ctx.UnmarshalBody

**Comment by kataras** [comment]
Hello @dmwin72015, I am sorry, that was my fault. Re-added the validation on ReadJSON, which should perform a bit faster on most cases too.
