### ISSUE TITLE
paths priority

### ISSUE THREAD

**Issue by monopollly** [kataras/iris#185]
Hi,

I need to get urls like this

**site.com/:userid**
**site.com/help**
**site.com/about**

I mean reserved words...
how to make it with iris?

with fasthttp I can make it like this:

```
switch path {		
		case "/help": helpHandler
		case "/about": aboutHandler 
		case "/:userid":   userHandler
}
```

**Comment by kataras** [comment]
@monopollly Please read: [book](https://www.gitbook.com/book/kataras/iris/details)

in **fasthttp** you do that:

requestHandler := func(ctx *fasthttp.RequestCtx) {
  if string(ctx.Method()) == "GET" {
  switch string(ctx.Path()) {
  case "/foo":
      fooHandler(ctx)
  case "/bar":
      barHandler(ctx)
  default:
      ctx.Error("Unsupported path", fasthttp.StatusNotFound)
  }
 } //else if POST,PUT,DELETE....
}

in **iris** you simple do this: 
```go
iris.Get("/foo,fooHandler)
iris.Get("/bar,barHandler)

// errors are served automatically no need to ctx.Error..
```

**Comment by kataras** [comment]
@monopollly Please read: [book](https://www.gitbook.com/book/kataras/iris/details)

in **fasthttp** you do that:
```go
requestHandler := func(ctx *fasthttp.RequestCtx) {
  if string(ctx.Method()) == "GET" {
  switch string(ctx.Path()) {
  case "/foo":
      fooHandler(ctx)
  case "/bar":
      barHandler(ctx)
  default:
      ctx.Error("Unsupported path", fasthttp.StatusNotFound)
  }
 } //else if POST,PUT,DELETE....
}
```

in **iris** you simple do this: 
```go
iris.Get("/foo",fooHandler)
iris.Get("/bar",barHandler)

// errors are served automatically no need to ctx.Error..
```

**Comment by monopollly** [comment]
no, you don't understand me;)

ok, how I can catch path route before iris?

I need to make static routes and dynamic routes on same path, 
and static routes must be priority something like this

**/about
/contacts
/blog
/news
/:userlogin** //this must catch after all

how to do this?

in fasthttp i can make:

```
switch path[0] {
  case "/about":
      about(ctx)
  case "/contacts":
      contacts(ctx)
  default:
      users(ctx) //all other requests as users pages
  }
```

**Comment by monopollly** [comment]
ok)

**Comment by kataras** [comment]
@monopollly Upgrade your Iris and you should see error logs in your console if you have done something wrong with the router :)
