### ISSUE TITLE
[BUG] WithOptimizations panics

### ISSUE THREAD

**Issue by ozguncagri** [kataras/iris#1853]
I don't know how I can give example to reproduce this error (because it's a huge codebase) but I just recently updated my iris from alpha 5 to alpha 9 and some of my endpoints just crashed. And if I remove `iris.WithOptimizations` config from run function everything works just fine. There was no problem in alpha 5.

Edit : In addition it mostly happens on JSON outputs using `ctx.JSON()`

Here is some dumps from logs

```log
runtime error: invalid memory address or nil pointer dereference
C:/Program Files/Go/src/runtime/panic.go:1038
C:/Program Files/Go/src/runtime/panic.go:221
C:/Program Files/Go/src/runtime/signal_windows.go:254
C:/Users/ozgun/go/pkg/mod/github.com/goccy/go-json@v0.9.5/internal/encoder/vm/vm.go:25
C:/Users/ozgun/go/pkg/mod/github.com/goccy/go-json@v0.9.5/encode.go:308
C:/Users/ozgun/go/pkg/mod/github.com/goccy/go-json@v0.9.5/encode.go:233
C:/Users/ozgun/go/pkg/mod/github.com/goccy/go-json@v0.9.5/encode.go:121
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/context/context.go:662
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/middleware/logger/logger.go:73
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/context/context.go:662
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/middleware/recover/recover.go:77
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/context/context.go:662
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/cache/browser.go:41
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/context/context.go:662
C:/Users/ozgun/go/pkg/mod/github.com/iris-contrib/middleware/cors@v0.0.0-20220301201128-27fa0f6a7d7e/cors.go:194
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/context/context.go:512
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/core/router/handler.go:440
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/core/router/router.go:220
C:/Users/ozgun/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha9/core/router/router.go:339
C:/Program Files/Go/src/net/http/server.go:2879C:/Program Files/Go/src/net/http/server.go:1930
C:/Program Files/Go/src/runtime/asm_amd64.s:1581
```

**Comment by kataras** [comment]
Hello @ozguncagri, without a re-producable example, even the smallest one, I can't guess what's wrong with ease but I'll try to find it soon and fix it. Until then, you can rollback to the previous version.

**Comment by ozguncagri** [comment]
I am really trying hard to reproduce it in smaller example but I can't. I was suspected other libraries that I used, so I tried to collect data and output it to file just before `ctx.JSON()` everything just works normal. But when I output, it goes crazy. I set some breakpoints and tried to follow debugger but it takes too long to follow.

Then I just noticed when debugging around you used [goccy/go-json](https://github.com/goccy/go-json) on your optimized outputs and wanted to check package's repo. On package's repo I saw this issue: [https://github.com/goccy/go-json/issues/339](https://github.com/goccy/go-json/issues/339).

I think the root of the problem is this package but I'm not sure yet. Hope it helps to figure things out...

**Comment by ozguncagri** [comment]
To be sure about json encoding I tried marshaling data with go's built-in `json.Marshal` and sending marshaled data with  `ctx.WriteString` everything is fine. If I dump the data to file, read it using `ioutil.Readfile` and unmarshal it to the variable and return it using `ctx.JSON` it crashes again.

I updated all my direct and transitive packages on my project but nothing changed. My `goccy/go-json`' version is also `v0.9.5` but nothing changed.

I think it's not related with iris, it looks like it's bug of goccy/go-json. If you want you can close this issue. I am sorry that I can't share the source publicly because it is the part of the commercial product but if you still want to see it I can show it to you over screenshare or something you want.

**Comment by kataras** [comment]
@ozguncagri No worries, can you send me a direct message at https://chat.iris-go.com so we can look it together and probably fix it as well?

**Comment by ozguncagri** [comment]
Hey, @kataras I send DM's on chat room around 2 weeks ago. Have you had time to inspect it?

**Comment by kataras** [comment]
Hello @ozguncagri, please upgrade to the latest version. Iris now uses the standard json package (which is faster on go 1.18x versions) but you can still use any package by customizing the `context.WriteJSON` package-level function which is used on `ctx.JSON` method.

**Comment by ozguncagri** [comment]
Hello @kataras 

Thank you for inform. You mean v12.2.0-beta3 right?
