### ISSUE TITLE
Basic Auth's ctx.Logout() is not logging out the user [BUG]

### ISSUE THREAD

**Issue by kukaki** [kataras/iris#1854]
**Describe the bug**
ctx.Logout() to invalidate Basic Auth is not actually logging out the User.

In [this Iris example](https://github.com/kataras/iris/blob/master/_examples/auth/basicauth/basic/main.go#L76), when we enter `/admin/logout`, the `ctx.Logout()` is getting called, and the route is redirected to `/admin`. Now the browser, instead of asking for Username and Password, is displaying `/admin <username>:<password>`.

**To Reproduce**
1. Run --> [the above example](https://github.com/kataras/iris/blob/master/_examples/auth/basicauth/basic/main.go)
2. Open `localhost:8080/admin` in firefox browser.
3. Browser asks for Username and Password. Fill them and press SignIn.
4. Browser displays `/admin <Username>:<Password>
5. Change location to `localhost:8080/admin/logout` manually in the url box of firefox.
6. The route is redirected to `localhost:8080/admin` displaying `/admin <Username>:<Password>`

**Expected behavior**
At the 6th step, the route should be redirected to `localhost:8080/admin` and browser should ask for Username and Password.

**Desktop (please complete the following information):**
 - OS: Windows11

**iris.Version**
- v12.2.0-alpha9

**Comment by kataras** [comment]
Hello @kukaki, you just need to send a status code of `unauthorized 401`. This will invalidate the credentials, for example:

```go
func logout(ctx iris.Context) {
	err := ctx.Logout()
	if err != nil {
		// handle error
		return
	}

	ctx.StatusCode(iris.StatusUnauthorized)
}
```

However it's better to do it through frontend/javascript-side.
