### ISSUE TITLE
[FEATURE REQUEST]websocket.GetContext(conn.Conn) got a wrong ctx

### ISSUE THREAD

**Issue by qiuhongshuai** [kataras/iris#1856]
when try to get context by function websocket.GetContext(conn.Conn)，I got wrong context。
code like this：

```
websocket.OnNamespaceConnect: func(conn *websocket.NSConn, message websocket.Message) error {
		//fmt.Println("connect is legal")
		ctx:=websocket.GetContext(conn.Conn)
		ctx.Application().Logger().Infof("websocket recognized link:%s",ctx.Request().URL.Path)
		_,err:=auth.Verifier.VerifyToken([]byte(ctx.URLParam("X-Websocket-Header-token")))
		//fmt.Println(err)
		if err!=nil{
			ctx.Application().Logger().Errorf("cannot connected to ws,because %s",err.Error())
			return err
		}
		return nil
	},
```
and websocket listen on app.Get("/ws",websocket.Handler(common.WebsocketServer))
but when I use neffos.js to connect it，I got the wrong ctx，because the url I got is “websocket recognized link: /img/admin.d0247083.jpg” which is a static resource on my web

**Comment by kataras** [comment]
Hello @qiuhongshuai, I can't re-produce it, I am getting `websocket recognized link:/echo` which is the correct for my example. If there is a problem, it's an easy fix of cloning the context before the websocket.Handler -> websocket.Upgrade method but can you please post a simple example which I can re-produce the issue you are describing? Thanks!

**Comment by qiuhongshuai** [comment]
It's hard for me to re-produce it with a simple example。when I use a simple example，I can always get right context。In addition I found it only appeared  when I run the project on linux，It performed well in windows。by the way，could you tell me how to clone the context before the websocket.Handler -> websocket.Upgrade method to aviod it，I am a beginner in go。Thanks

**Comment by qiuhongshuai** [comment]
Finally，I found it can be resolved by using websocket.OnConnect。
code like this：
`common.WebsocketServer.OnConnect= func(c *neffos.Conn) error {
		ctx:=websocket.GetContext(c)
		ctx.Application().Logger().Infof("websocket recognized link: %s",ctx.Request().URL.Path)
		token:=ctx.URLParam("X-Websocket-Header-token")
		if _,err:=auth.Verifier.VerifyToken([]byte(token));err!=nil{
			ctx.Application().Logger().Error(err.Error())
			return err
		}
		return nil
	}` 
I wonder to know what difference between   the OnConnect and OnNamespaceConnect

**Comment by kataras** [comment]
Hello @qiuhongshuai, OnNamespaceConnect comes after the OnConnect. Any validation should be done on the "OnConnect" level, so you can forbid a client from connecting to your websocket server. About the previous question, you can do it manually but I was speaking about the Iris' websocket package itself. I'll take a closer look and I'll replace context with its clone if necessary. You should be able to get the correct context even on NamespaceConnect event.

**Comment by kataras** [comment]
@qiuhongshuai please check using the latest Iris version: `go get github.com/kataras/iris/v12@master` i pushed a commit which should fix that one (I got a 2nd report of this issue through my personal social networks).
