### ISSUE TITLE
Debugging templates

### ISSUE THREAD

**Issue by gf3** [kataras/iris#1857]
just wondering how others have managed to debug templates when there's an issue at run time?

for example, if one has a simple template and layout, and the template is attempting to call a function that doesn't exist on a struct the template simply does not render. e.g.

**layout.html**
```html
<!DOCTYPE html>
<html>

{{ yield }}

</html>
```

**view.html**
```html
<h1>{{ .SomeStruct.FuncThatDoesntExist }}</h1>
```

in the scenario above only the layout renders and there are no errors emitted.

in other cases where templates fail to render an internal server error is thrown but there is no error associated with it. e.g.:

**main.go**
```go
func main() {
	app := iris.New()
	app.OnErrorCode(iris.StatusInternalServerError, internalServerError)
	// ...
}

func internalServerError(ctx iris.Context) {
	log := ctx.Application().Logger()

	if err := ctx.GetErr(); err != nil {
		log.Error(err)
		if _, err := ctx.WriteString(err.Error()); err != nil {
			log.Error(err)
		}
	} else {
		log.Error("internal server error")
		if _, err := ctx.WriteString(iris.StatusText(ctx.GetStatusCode())); err != nil {
			log.Error(err)
		}
	}
}
```

in the above scenario the `internalServerError` handler is called, but `ctx.GetErr()` returns `nil`

how do people build and debug templates?

**Comment by kataras** [comment]
Hello @gf3,

By-default the server sends internal error to the client when rendering fails but that's not what we call "error handled".
The `ctx.View`, which is the method you use to render the template, returns an `error` output, take that error output argument and handle it.

**Comment by kataras** [comment]
Yes @gf3 you can also use the mvc's specific error handler to work per-controller if you want so. Wait for a fix, I will respond here soon.

**Comment by kataras** [comment]
OK @gf3, I've pushed a commit which stores the view's error to the context so you can grab it through ctx.GetErr. However, if you try to call an undefined function you will receive a "compile" error (before server starts):

```
[ERRO] 2022/03/10 20:41 View Builder: /example.html: template: example.html:24: function "notfoundpage" not defined
[ERRO] 2022/03/10 20:41 /example.html: template: example.html:24: function "notfoundpage" not defined
```

For any "runtime" errors you may want to look the https://pkg.go.dev/html/template documentation.

**Comment by gf3** [comment]
@kataras thank you! i'll test this out shortly

also for reference, i am using `.Reload(true)` as well as go-bindata but i never receive compile-time errors for missing methods, etc...

**Comment by kataras** [comment]
You cannot use go-bindata with .Reload(true). The go-bindata means that the view file is embedded using raw []byte in your source code and it has no idea when the source files are.

**Comment by kataras** [comment]
Of course @gf3 you are welcome, 

You cannot use go-bindata with .Reload(true). Use go-bindata only when you are ready to go production or make a check of your log level and depend on that use the correct method (load from files with .Reload(true) or go-bindata). The go-bindata means that the view file is embedded using raw []byte in your source code and it has no idea when the source files are.
