### ISSUE TITLE
[BUG]Context.RequestParams.Get() get invalid value when we only use the url param as a validator

### ISSUE THREAD

**Issue by lrita** [kataras/iris#1859]
**Describe the bug**
Context.RequestParams.Get() get invalid value when we only use the url param as a validator.

**To Reproduce**
```go
# register the router, we only use the url param as a validator.
app.Delete("/xxx/{id:int64}", h.apiXXXDel)

func (h *HTTP) apiXXXDel(c iris.Context) {
  id := c.Params().Get("id") // using as string type in logic
  // Bug here, id == "%!s(int64=3)" by fmt issue
}
```

**Expected behavior**
Return it's literals as it in the text protocol.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**iris.Version**
- v12.2.0-alpha9.0

**Comment by kataras** [comment]
You are right @lrita, this should be `%v`, as `%v` will correctly render any custom struct/type which completes the fmt.Stringer (String() string) interface. I approved your PR, thanks a lot!
