### ISSUE TITLE
github.com/aymerick/raymond is apparently abandoned

### ISSUE THREAD

**Issue by tylerd-canva** [kataras/iris#1861]
https://github.com/kataras/iris/blob/af2d017e1b407dfd6177b07b765720480a3736df/go.mod#L12

See https://github.com/aymerick/raymond/issues/40

Would it be feasible to switch to https://github.com/mailgun/raymond ?

**Comment by kataras** [comment]
Hello @tylerd-canva, mailgun's repository has still the v3 support of handlebars, but the latest one is version 4.7.7. However, you are right. I'll do the switch to mailgun's repository as it seems to have a couple of new features and fixes compared to the aymerick's.
