### ISSUE TITLE
Is there anyway to hook request for mvc controller

### ISSUE THREAD

**Issue by yindex** [kataras/iris#1864]
I want to assign value to mvc controller instance before  get(or post put delete) method.
eg.

```golang
type IndexController struct {
	user User
}
func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

can we do like this 

```golang
type IndexController struct {
	user User
}
func (i *IndexController) BeforeAction(ctx iris.Context) {
	i.user = readFromCtx(ctx)
}
func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```
so we need not to fetch user info from ctx in every method

**Comment by kataras** [comment]
Hello @yindex, you have `BeginRequest & EndRequest` methods that you can implement. Example Code:

```go
type IndexController struct {
	user User `stateless:"true"`
}

func (i *IndexController) BeginRequest(ctx iris.Context) {
	i.user = readFromCtx(ctx)
}

func (_ *IndexController) EndRequest(_ iris.Context) {}

func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

**Comment by kataras** [comment]
Hello @yindex, you have `BeginRequest & EndRequest` methods that you can implement. Example Code:

```go
type IndexController struct {
	user User `stateless:"true"`
}

func (i *IndexController) BeginRequest(ctx iris.Context) {
	i.user = readFromCtx(ctx)
}

func (_ *IndexController) EndRequest(_ iris.Context) {}

func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

However, it's recommended to use dependency injection for that kind of actions. The `user` is an unexported field, make it exported (capitalized) `User User` and bind your `readFromCtx` function, which is a valid request dependency, it accepts an iris.Context and returns a `User`. Example Code:

```go
	app.PartyFunc("/your_path", func(r iris.Party) {
		mvc.New(r).
			Register(readFromCtx). // <--- HERE, register readFromCtx as dependency. 
			Handle(new(IndexController))
	})
```

```go
type IndexController struct {
	User User
}

func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

**Comment by kataras** [comment]
Hello @yindex, you have `BeginRequest & EndRequest` methods that you can implement. Example Code:

```go
type IndexController struct {
	user User `stateless:"true"`
}

func (i *IndexController) BeginRequest(ctx iris.Context) {
	i.user = readFromCtx(ctx)
}

func (_ *IndexController) EndRequest(_ iris.Context) {}

func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

Tip: Because you have a single struct field declared in your controller struct and that's not exported: rename `user` to `User` (exported field) otherwise your controller is defined as `singleton` which means that all requests uses the same controller instance, so you can't set different values to the `user` struct field for each request.

However, it's recommended to use dependency injection for that kind of actions. The `user` is an unexported field, make it exported (capitalized) `User User` and bind your `readFromCtx` function, which is a valid request dependency, it accepts an iris.Context and returns a `User`. Example Code:

```go
	app.PartyFunc("/your_path", func(r iris.Party) {
		mvc.New(r).
			Register(readFromCtx). // <--- HERE, register readFromCtx as dependency. 
			Handle(new(IndexController))
	})
```

```go
type IndexController struct {
	User User
}

func (i *IndexController) GetData(ctx iris.Context) {
	model.GetUserData(i.user)
}
```

**Comment by yindex** [comment]
@kataras thks

**Comment by yindex** [comment]
@kataras Thanks you for guide and help me understand `request dependency`,It's so gracefully
