### ISSUE TITLE
[BUG]In the case of an empty streaming response result, can not get a correct statue code

### ISSUE THREAD

**Issue by zjclyz** [kataras/iris#1868]
**Describe the bug**
In the case of an empty streaming response result, can not get a correct statue code.

**To Reproduce**
The following code can reproduce the problem：
```go
app := iris.New()
app.Any("/demo", func(ctx context.Context){
		writer := ctx.ResponseWriter()
		writer.Header().Set("Content-Type", "text/html; charset=UTF-8")
		writer.Header().Set("Transfer-Encoding", "chunked")
		writer.WriteHeader(http.StatusFound)
		writer.(http.Flusher).Flush()
	})
app.Run(iris.Addr(":8001"), iris.WithoutServerError(iris.ErrServerClosed))
```

**Expected behavior**
Access to the services provided by the above code should get a 302 status code, which actually does 200.

**Screenshots**
The result like that:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/22068835/160283159-e978d352-3299-4e71-8756-4232d75f278b.png">
Actually, I was hoping to get 302 because that's what I set up.

**iris.Version**
- v12.1.8

**Comment by kataras** [comment]
Hello @zjclyz,

I did run the example and it works as expected, I see status code 302.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/22900943/160294132-a152443b-f3f5-45b8-acf7-d58f6efa29e8.png">

Could you please try to upgrade to [v12.2.0-alpha9](https://github.com/kataras/iris/releases/tag/v12.2.0-alpha9) and try again? This is similar code:

```go
package main

import "github.com/kataras/iris/v12"


func main() {
	app := iris.New()
	app.Any("/demo", func(ctx iris.Context) {
		writer := ctx.ResponseWriter()
		writer.Header().Set("Content-Type", "text/html; charset=UTF-8")
		writer.Header().Set("Transfer-Encoding", "chunked")
		writer.WriteHeader(iris.StatusFound)
		writer.Flush()
	})
	app.Run(iris.Addr(":8001"), iris.WithoutServerError(iris.ErrServerClosed))
}

```

**Comment by zjclyz** [comment]
> Hello @zjclyz,
> 
> I did run the example and it works as expected, I see status code 302.
> 
> <img alt="image" width="1048" src="https://user-images.githubusercontent.com/22900943/160294132-a152443b-f3f5-45b8-acf7-d58f6efa29e8.png">
> 
> Could you please try to upgrade to [v12.2.0-alpha9](https://github.com/kataras/iris/releases/tag/v12.2.0-alpha9) and try again? This is similar code:
> 
> ```go
> package main
> 
> import "github.com/kataras/iris/v12"
> 
> 
> func main() {
> 	app := iris.New()
> 	app.Any("/demo", func(ctx iris.Context) {
> 		writer := ctx.ResponseWriter()
> 		writer.Header().Set("Content-Type", "text/html; charset=UTF-8")
> 		writer.Header().Set("Transfer-Encoding", "chunked")
> 		writer.WriteHeader(iris.StatusFound)
> 		writer.Flush()
> 	})
> 	app.Run(iris.Addr(":8001"), iris.WithoutServerError(iris.ErrServerClosed))
> }
> ```

Yes, I noticed that changelog of this version:
```
Fix Response Recorder Flush when transfer-encoding is chunked.
```
I tried it and it works. thx!
