### ISSUE TITLE
[FEATURE REQUEST] Urlparam is case insensitive

### ISSUE THREAD

**Issue by aadog** [kataras/iris#1869]
**Is your feature request related to a problem? Please describe.**

It's frustrating when urlparam gets the case. Most web frameworks are not case sensitive

**Describe the solution you'd like**

[FEATURE REQUEST] Urlparam is case insensitive

**Describe alternatives you've considered**

ctx.URLParam("A")=ctx.URLParam("b")

It's better to iris.New can be used as only one option

**Additional context**

**Comment by kataras** [comment]
Hello @aadog,

The parameters should always be in lowercase, because that's how they are passed from clients. So `ctx.URLParam("a")` reads both `?a=test` and `?A=test`.

```go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Get("/", handler)

	// http://localhost:8080?a=test
	// http://localhost:8080?A=test
	app.Listen(":8080")
}

func handler(ctx iris.Context) {
	a := ctx.URLParam("a")
	ctx.Writef("parameter A = %s", a)
}

```

**Comment by kataras** [comment]
Hello @aadog,

The parameters should always be in lowercase, because that's how they are passed from clients. So `ctx.URLParam("a")` reads both `?a=test` and `?A=test`. That's the default behavior of the standard `net/http` package and other http language frameworks from C# to python.

```go
package main

import "github.com/kataras/iris/v12"

func main() {
	app := iris.New()
	app.Get("/", handler)

	// http://localhost:8080?a=test
	// http://localhost:8080?A=test
	app.Listen(":8080")
}

func handler(ctx iris.Context) {
	a := ctx.URLParam("a")
	ctx.Writef("parameter A = %s", a)
}

```
