### ISSUE TITLE
Javascript web tokens

### ISSUE THREAD

**Issue by scorpnode** [kataras/iris#187]
Could this be something that could be in-built within iris? Its a good alternative to sessions and good for interaction with mobile devices.
https://github.com/dgrijalva/jwt-go
https://github.com/auth0/go-jwt-middleware

**Comment by kataras** [comment]
@scorpnode This is a good idea but, as you linked on your comment, there is a middleware for that already, should I just convert it to work with Iris?

Note: I want to see some middlewares for other developers also, it's very easy to convert one from net/http to iris*

**Comment by tonylinyy** [comment]
+1
we recently learn iris,like it

**Comment by transtone** [comment]
+1
https://github.com/labstack/echo/blob/master/middleware/jwt.go

**Comment by kataras** [comment]
@scorpnode A vulnerability in JWT was recently published here: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ . If that tnot bothers you I can make this middleware today, but I need an answer, thanks.

**Comment by kataras** [comment]
@scorpnode @egorsmkv @miko-code @burflip @hrwebasst @stephendolan @jashk @kamilchm @xpbliss @arijoon @jscharnitzke Done, [JWT Middleware book section](https://kataras.gitbooks.io/iris/content/jwt.html)

You already know this, propably, but I must notice that: ` A vulnerability in JWT was recently published here: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/` .

**Comment by kataras** [comment]
@scorpnode @egorsmkv @miko-code @burflip @hrwebasst @stephendolan @jashk @kamilchm @xpbliss @arijoon @jscharnitzke @tonylinyy  Done, by the way this request has one of the biggest number of `thumbs up`, nice!

 [JWT Middleware book section](https://kataras.gitbooks.io/iris/content/jwt.html)

You already know this, propably, but I must notice that: ` A vulnerability in JWT was recently published here: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/` .

**Comment by xpbliss** [comment]
good work!

**Comment by kataras** [comment]
Thanks!! it is just a fork but it works quite good

**Comment by tonylinyy** [comment]
nice work!
we will test it later

**Comment by xpbliss** [comment]
I use the exampl```e https://kataras.gitbooks.io/iris/content/jwt.html```
It always show  the following
''''Required authorization token not found```

**Comment by kataras** [comment]
Do you know how JWT works?

**Comment by xpbliss** [comment]
Should give a compplete example?

**Comment by kataras** [comment]
Why should I? the library itself doesn't have one...

**Comment by kataras** [comment]
Sorry @xpbliss , take a look [here](https://github.com/auth0/go-jwt-middleware/blob/master/jwtmiddleware_test.go#L103) it will help you to understand what's going on with jwt

**Comment by tonylinyy** [comment]
@kataras should we get the token from cookie,I view the source code,it seems can not do this,am i right?
