### ISSUE TITLE
Are there restful api samples for all methods?

### ISSUE THREAD

**Issue by aaronchen2k** [kataras/iris#1872]
Need restful api samples for below methods, I am not sure what response should be returned to the client, thanks.

    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "CONNECT",
    "OPTIONS",
    "TRACE",
    "CUSTOM",

**Comment by kataras** [comment]
Hello @aaronchen2k,


```go
app := iris.New()

app.Get("/", func(ctx iris.Context){
  ctx.JSON(iris.Map{"key": "value"})
})

/*
app.Post(path, handler)
app.Put(path, handler)
app.Patch(path, handler)
app.Delete(path, handler)
app.Head(path, handler)
app.Connect(path, handler)
app.Options(path, handler)
app.Trace(path, handler)
*/

app.Listen(":8080")
```

If you need to know what is an HTTP Method/Verb or/and when you should use each of the HTTP Verbs, please navigate through [there](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods).

**Comment by aaronchen2k** [comment]
> Hello @aaronchen2k,
> 
> 
> ```go
> app := iris.New()
> 
> app.Get("/", func(ctx iris.Context){
>   ctx.JSON(iris.Map{"key": "value"})
> })
> 
> /*
> app.Post(path, handler)
> app.Put(path, handler)
> app.Patch(path, handler)
> app.Delete(path, handler)
> app.Head(path, handler)
> app.Connect(path, handler)
> app.Options(path, handler)
> app.Trace(path, handler)
> */
> 
> app.Listen(":8080")
> ```
> 
> If you need to know what is an HTTP Method/Verb or/and when you should use each of the HTTP Verbs, please navigate through [there](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods).

Thank you, so which kind of message shall we return to the client for each method?

**Comment by kataras** [comment]
It depends @aaronchen2k, you can send whatever status code you want your client to catch, the default is 200 (iris.StatusOK). For example, I usually send 201 (iris.StatusCreated) on `Post/Put/Patch` succeed insert/update/partial update of an object in the database, or 204 (iris.NoContent) on deletion or marked for deletion on `Delete`. You can search online for different kind of articles depending on the server and how much control you have over the http client it talks to.

**Comment by kataras** [comment]
You are welcome @aaronchen2k,

The answer is: it depends, you are not limited by the framework, only your imagination. You can send whatever status code you want your client to catch, the default is 200 (iris.StatusOK). For example, I usually send 201 (iris.StatusCreated) on `Post` insert, and 200 on `Put/Patch` for partial/full update of an object in the database, or 204 (iris.NoContent) on deletion or marked for deletion on `Delete`. You can search online for different kind of articles depending on the server and how much control you have over the http client it talks to.
