### ISSUE TITLE
threre has any idea about iris websocket conn to emit other user?

### ISSUE THREAD

**Issue by Iteravse** [kataras/iris#1874]
we little team need develop a solution about mutiplayer matching, if last one matched in room,then the server must notification others users [game's stared!],but in basic example ,server only can by ask mothed to response  request user, any idea?
btw,i can't found any document about iris websocklet library uasge, it too simple, any recommed?

**Comment by kataras** [comment]
Hello @Iteravse, you can find documentation for our websocket framework at: https://github.com/kataras/neffos. That repository includes example for "notify all users on room joined" and e.t.c. Please do not hesitate to ask for further assistance if the documentation does not fill your needs.

Thanks,
