### ISSUE TITLE
[BUG] ViewData not working anymore with jet

### ISSUE THREAD

**Issue by mblaschke** [kataras/iris#1876]
**Describe the bug**
Data passed with ctx.ViewData is not passed anymore to jet
still works with `jet.AddRuntimeVars`

**To Reproduce**
1. try [template_jet_0](https://github.com/kataras/iris/tree/master/_examples/view/template_jet_0), html title is not set
2. remove the isset from /layouts/application.jet
3. log the error from the route `/all-done`:

```
Jet Runtime Error ("/layouts/application.jet":5): identifier "title" not available in current (map[]) or parent scope, global, or default variables
```

**Expected behavior**
title is set and passed to jet variable map

**Desktop (please complete the following information):**
 - OS: osx

**iris.Version**
- v12.2.0-beta1
- master

**Comment by kataras** [comment]
Hello @mblaschke, thanks for the report. It's fixed on the latest `/v12@master` version.
