### ISSUE TITLE
ReadJSON EOF

### ISSUE THREAD

**Issue by MarybethGasman** [kataras/iris#1878]
Everything else is fine
But  ReadJSON returns an EOF
go 1.17.8
iris v12.2.0-beta1
```go
func main() {
	app := iris.New()
	mvc.Configure(app.Party("/"), func(app *mvc.Application) {
		app.Handle(new(domain.BookController))
		app.Handle(new(domain.CommodityController))
	})
	app.Listen(":8081")
}

type CommodityController struct {

}
type commodity struct {
	Name string `json:"name"`
	Stock int `json:"stock"`
	Price    decimal.Decimal `json:"price"`
	ImageUrl string          `json:"imageUrl"`
}

func (c *CommodityController) SaveCommodity(ctx iris.Context, commodity2 commodity) commodity {
	var comm commodity
	err := ctx.ReadJSON(&comm)
        //here here here here here (●'◡'●)
	if err != nil {	//got a EOF
		ctx.StatusCode(iris.StatusBadRequest)
		ctx.WriteString(err.Error())
	}
	db := mysql.GetConnection()
	_, _ = db.Exec(
		"insert into sku(stock,price,img_url) values (?,?,?)",
		commodity2.Stock, commodity2.Price, commodity2.ImageUrl,
	)
	return commodity2
}

func (m *CommodityController) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle("POST", "/commodities", "SaveCommodity")
}
```
request
![image](https://user-images.githubusercontent.com/90539473/164680112-8749b7d5-97cf-497d-b3e2-945b45f39de9.png)
response
![image](https://user-images.githubusercontent.com/90539473/164680285-ffd5216c-a122-4d3e-a072-b7acfea21e54.png)

**Comment by kataras** [comment]
Hello @MarybethGasman, this is expected, it already reads the request JSON body inside `commodity2 from SaveCommodity(ctx iris.Context, commodity2 commodity)` so you can't read it twice (body consumed on Read functions in Go). If you need to change that behavior please follow the `read-many` example at: https://github.com/kataras/iris/blob/master/_examples/request-body/read-many/main.go#L32

**Comment by kataras** [comment]
Hello @MarybethGasman, this is expected, it already reads the request JSON body inside `commodity2 from SaveCommodity(ctx iris.Context, commodity2 commodity)` so you can't read it twice (body consumed on Read functions in Go). If you need to change that behavior please follow the `read-many` example at: https://github.com/kataras/iris/blob/master/_examples/request-body/read-many/main.go#L32. In-short:

```go
app.Listen(":8081", iris.WithoutBodyConsumptionOnUnmarshal)
```

**Comment by kataras** [comment]
Hello @MarybethGasman, this is expected, it already reads the request JSON body inside `commodity2` from `SaveCommodity(ctx iris.Context, commodity2 commodity)` Controller Method so you can't read it twice (body consumed on Read functions in Go). If you need to change that behavior please follow the `read-many` example at: https://github.com/kataras/iris/blob/master/_examples/request-body/read-many/main.go#L32. In-short:

```go
app.Listen(":8081", iris.WithoutBodyConsumptionOnUnmarshal)
```

**Comment by MarybethGasman** [comment]
@kataras Problem solved.Thanks for your explaination!

**Comment by jiulu313** [comment]
That's what happened to mine

go version: 1.18.5
iris version : v12.2.0-beta4.0



`
app.Listen(":8081",iris.WithoutBodyConsumptionOnUnmarshal, iris.WithOptimizations)

func (c *WxPayController) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle("POST", "/payNotifyUrl", "PayNotifyUrl")                
}

func (c *WxPayController) PayNotifyUrl() string {
	var person bean.Person
	err := c.Ctx.ReadJSON(&person)
	if err != nil {
		fmt.Println("parse json error：", err)
	} else {
		fmt.Println("json data is：", person)
	}

	return `{"code":23,"message":"success","data":"this is a test"}`
}
`

postman visit and log is : 
![image](https://user-images.githubusercontent.com/4046526/182885373-68be7e93-a915-4d40-b224-59d1a2652cf8.png)

but in _example/request-body/read-many  is fine 



What's the difference between **app.Post("/xx", func )**  and    **b.Handle("POST", "/payNotifyUrl", "PayNotifyUrl")    have different **  ?
