### ISSUE TITLE
can i use this framework with MVC arquitecture, how?

### ISSUE THREAD

**Issue by neo2005th** [kataras/iris#188]
like in beego?

**Comment by kataras** [comment]
@neo2005th  Welcome to Iris,

You can use Iris as you like, Iris doesn't limits you as other frameworks many times do, contrary, it gives you complete tools & all that functionality you need to build gold-star web application.

Read the [e-book](https://kataras.gitbooks.io/iris/content/) and you will find the answer you're looking for, you can also download or view some micro-practical [examples](https://github.com/iris-contrib/examples). If you ever need real-time help just talk with the community on the [chat](https://gitter.im/kataras/iris)
