### ISSUE TITLE
[BUG](value of type http.FileSystem) as type string in argument to iris.HTML

### ISSUE THREAD

**Issue by guanzi008** [kataras/iris#1880]
cannot use AssetFile() (value of type http.FileSystem) as type string in argument to iris.HTML
https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app

**Comment by kataras** [comment]
Hello @guanzi008, what's your Iris installed version (see your go.mod file)?

**Comment by guanzi008** [comment]
版本问题。解决了，谢谢。

**Comment by kataras** [comment]
No worries @guanzi008, you are welcome!
