### ISSUE TITLE
[BUG]Http File Server DirListRich

### ISSUE THREAD

**Issue by baichachaa** [kataras/iris#1882]
**Describe the bug**
My http file server configuration looks like this
```go
app.HandleDir("/", iris.Dir("./dir"), iris.DirOptions{
    ShowList: true,
    DirList: iris.DirListRich(),
}
```
I read the source code of `iris.DirListRich` and found that it is possible to use custom sorting
```go
sortBy := ctx.URLParam("sort")
switch sortBy {
case "name":
    sort.Slice(dirs, func(i, j int) bool { return dirs[i].Name() < dirs[j].Name() })
case "size":
    sort.Slice(dirs, func(i, j int) bool { return dirs[i].Size() < dirs[j].Size() })
default:
    sort.Slice(dirs, func(i, j int) bool { return dirs[i].ModTime().After(dirs[j].ModTime()) })
}
```
When I use name as sort, for example like this
```
http://localhost:8080/ccc?sort=name
```
This will cause the file to fail to download, the download link is as follows
```
http://localhost:8080/ccc%3Fsort=name/Pandas_Cheat_Sheet_zh_CN.pdf
```

**Expected behavior**
The download link should look like this no matter if I use sorting on the url or not
```
http://localhost:8080/ccc/Pandas_Cheat_Sheet_zh_CN.pdf
```
**Desktop (please complete the following information):**
 - OS: Windows
 - GoVersion:1.18.1

**iris.Version**
- v12.2.0-beta1 

**My own hope**
Sort folders first, files later. And default sort is name asc.
Or
Provides custom sorting options.

Thanks

**Comment by kataras** [comment]
Hello @baichachaa,

This should be fixed now, please upgrade on `@master` version and try it on a "cognito" browser window.
