### ISSUE TITLE
ctx.Recorder().Reset() with iris.Compression

### ISSUE THREAD

**Issue by qRoC** [kataras/iris#1884]
How use `ctx.Recorder().Reset()` with `iris.Compression`?

Example:

```go
app.UseRouter(iris.Compression)
app.UseRouter(error_handler.New())
```

And error handler:

```go
recorder := ctx.Recorder()

ctx.Next()

if err := ctx.GetErr(); err != nil {
	recorder.Reset()
	statusCode := iris.StatusInternalServerError
	ctx.StopWithJSON(statusCode, contracts.NewErrorResponse(iris.StatusText(statusCode)))
}
```

Compress work, but final response without `Content-Encoding` and `Vary` headers.

With `recorder.ResetBody()` all ok, but I need a full reset of the response

**Comment by kataras** [comment]
Hello @qRoC, please read the godoc of the ResponseRecorder.Reset method:

```go
// Reset clears the headers, sets the status code to 200
// and clears the cached body.
```

So reset will clear the "Content-Encoding" and "Vary" Headers. If you want to keep compression then do not call `Reset`, the `ResetBody` is fine, why do you want to "full reset the response" and in the same time keep the Content-Encoding and Vary headers? In your example there is no reason to use `ctx.Recorder()`, could you please provide more background/information?

**Comment by qRoC** [comment]
> "full reset the response"

Yes, but I think if `iris.Compression` first, then it should set headers anyway.

> In your example there is no reason to use ctx.Recorder(), could you please provide more background/information?

The Handler can start writing a response and panic somewhere. In this case, I want to be sure that I will return the correct error, and not add it to the body

```go
ctx.WriteString("foo")
ctx.Header("foo", "bar")
panic(nil)
```

**Comment by kataras** [comment]
If you want to catch the `panic`, see the [recover](https://github.com/kataras/iris/blob/d98904405476dfa391459ca6bfbb01d59ba9a6cd/middleware/recover/recover.go#L27-L29) middleware code too (it uses defer, recover and sets the error to a special [ ErrPanicRecovery](https://github.com/kataras/iris/blob/d98904405476dfa391459ca6bfbb01d59ba9a6cd/context/context.go#L6020)). You can use `ResetBody` and clear all headers except Vary & Content-Encoding so the error message is written with the selected compression:

```go
package main

import (
	"fmt"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()
	app.UseRouter(iris.Compression)
	app.UseRouter(myErrorHandler)

	app.Get("/", handler)
	app.Listen(":8080")
}

func myErrorHandler(ctx iris.Context) {
	recorder := ctx.Recorder()

	ctx.Application().Logger().Infof("Recording...")

	ctx.Next()
	ctx.Application().Logger().Infof("Handler finished...")

	if err := ctx.GetErr(); err != nil {
		ctx.Application().Logger().Infof("Handler error was: %s", err.Error())

		// clear body.
		recorder.ResetBody()
		// clear all headers except Content-Encoding & Vary
		if h := recorder.Header(); len(h) > 2 {
			for k := range h {
				if k != "Content-Encoding" && k != "Vary" {
					delete(h, k)
				}
			}
		}

		statusCode := iris.StatusInternalServerError
		ctx.StopWithJSON(statusCode, iris.Map{
			"message": err.Error(),
		})
	}
}

func handler(ctx iris.Context) {
	ctx.WriteString("Content may fall")
	ctx.Header("X-Test", "value")

	ctx.SetErr(fmt.Errorf("custom error message"))
	ctx.Application().Logger().Infof("Handler executed...")
}
```

For a common way to handle errors, see the new [x/errors](https://github.com/kataras/iris/tree/master/x/errors) package too ([example](https://github.com/kataras/iris/tree/master/_examples/routing/http-wire-errors)).

**Comment by qRoC** [comment]
Yes thanks, I did that :)

**Comment by kataras** [comment]
@qRoc There is also the `ResetHeaders` method that you can use to roll-back the headers back to the previous handler's ones (compression in your case):
```go
	recorder := ctx.Recorder()
	ctx.Next()

	if err := ctx.GetErr(); err != nil {
		// clear body.
		recorder.ResetBody()
		// set the headers to the previous handler's (compression in our case)
		recorder.ResetHeaders()

		statusCode := iris.StatusInternalServerError
		ctx.StopWithJSON(statusCode, iris.Map{
			"message": err.Error(),
		})
	}
```

**Comment by kataras** [comment]
@qRoC And here it is, a more complete version of the above:

```go
package main

import (
	"errors"
	"fmt"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()
	app.UseRouter(iris.Compression)
	app.UseRouter(myErrorHandler)

	app.Get("/", handler)
	app.Listen(":8080")
}

func myErrorHandler(ctx iris.Context) {
	recorder := ctx.Recorder()

	defer func() {
		var err error

		if v := recover(); v != nil { // panic
			if panicErr, ok := v.(error); ok {
				err = panicErr
			} else {
				err = errors.New(fmt.Sprint(v))
			}
		} else { // custom error.
			err = ctx.GetErr()
		}

		if err != nil {
			// clear body and ant headers created between recorder and handler.
			recorder.ResetBody()
			recorder.ResetHeaders()

			statusCode := iris.StatusInternalServerError
			ctx.StopWithJSON(statusCode, iris.Map{
				"message": err.Error(),
			})
		}
	}()

	ctx.Next()
}

func handler(ctx iris.Context) {
	ctx.WriteString("Content may fall")
	ctx.Header("X-Test", "value")

	// ctx.SetErr(fmt.Errorf("custom error message"))
	panic("errr!")
}

```

**Comment by kataras** [comment]
@qRoC And here it is, a more complete version of the above:

```go
package main

import (
	"errors"
	"fmt"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.New()
	app.UseRouter(iris.Compression)
	app.UseRouter(myErrorHandler)

	app.Get("/", handler)

	app.Listen(":8080", iris.WithoutAutoFireStatusCode)
}

func myErrorHandler(ctx iris.Context) {
	recorder := ctx.Recorder()

	defer func() {
		var err error

		if v := recover(); v != nil { // panic
			if panicErr, ok := v.(error); ok {
				err = panicErr
			} else {
				err = errors.New(fmt.Sprint(v))
			}
		} else { // custom error.
			err = ctx.GetErr()
		}

		if err != nil {
			// clear body and any headers created between recorder and handler.
			recorder.ResetBody()
			recorder.ResetHeaders()

			statusCode := iris.StatusInternalServerError
			ctx.StopWithJSON(statusCode, iris.Map{
				"message": err.Error(),
			})
		}
	}()

	ctx.Next()
}

func handler(ctx iris.Context) {
	ctx.WriteString("Content may fall")
	ctx.Header("X-Test", "value")

	// ctx.SetErr(fmt.Errorf("custom error message"))
	panic("errr!")
}

```

**Comment by kataras** [comment]
@qRoC  Keep note that a good http client checks if the server sent a response with compression applied and only then can de-compress the data. If you want the best performance, do not use compression on small-length bodies. So it's better to keep the default behavior which, wisely, let the errors to be transferred without compression from server to client when a handler does not handle the error by itself (when no data are written). So, to mimic the default behavior and disable compression (e.g. gzip) and send a custom error body you can use the below instead of `recorder.ResetBody & recorder.ResetHeaders`:

```go
import "github.com/kataras/iris/v12/context"
// ...

recorder.Reset()
recorder.ResponseWriter.(*context.CompressResponseWriter).Disabled = true
```
