### ISSUE TITLE
[BUG] 使用127.0.0.1在本机调试时session每次都刷新sessionId

### ISSUE THREAD

**Issue by langzishen** [kataras/iris#1886]
**Describe the bug**
使用Edge和Chrome调试代码时，由于本地使用127.0.0.1测试，浏览器的cookie的Domain为localhost，set-cookie失败

**To Reproduce**
1. 使用Edge或Chrome，在同一个域名下的相同路径或不同路径做session设置和读取

**Expected behavior**
在不同的请求中能够设置和读取session
![d](https://user-images.githubusercontent.com/19563488/168505886-a6ae25ef-232b-4be3-a5a2-d2ba6d090cb3.jpg)
![a](https://user-images.githubusercontent.com/19563488/168505942-6b23a2a1-1edd-4910-b4c5-2509758f05ab.jpg)

修改后：
![c](https://user-images.githubusercontent.com/19563488/168506005-09f90575-3881-4827-8e55-761956009df9.jpg)
![b](https://user-images.githubusercontent.com/19563488/168506034-c74ac48a-c031-48b8-bf3c-994ee075d676.jpg)

**Comment by langzishen** [comment]
修改后，cookie中的sessionId的值就不会刷新

**Comment by kataras** [comment]
您好，请告诉我您的解决方案是否解决了问题，如果是，请不要犹豫，打开 [PR](https://github.com/kataras/iris/pulls]。

> 请注意，我正在使用翻译。

**Comment by kataras** [comment]
您好, @langzishen 请告诉我您的解决方案是否解决了问题，如果是，请不要犹豫，打开 [PR](https://github.com/kataras/iris/pulls)。

> 请注意，我正在使用翻译。

**Comment by kataras** [comment]
However, I've just pushed a commit which enables customizations over the `context.GetDomain` package-level function. Just grab the latest `@master` Iris version and:

```go
package main

import (
  "github.com/kataras/iris/v12/context"
  // ...
)

func init() {
   context.GetDomain = func(host string) string {
      /* your own code */
      
      return ""
   }
}

```
