### ISSUE TITLE
[BUG] HandleDir Not Found

### ISSUE THREAD

**Issue by Teeoo** [kataras/iris#1887]
**Describe the bug**

**To Reproduce**
1. [...]

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25023667/168720230-2c1955b6-0a44-4f4c-86a9-3d33e97d9d0f.png)
![image](https://user-images.githubusercontent.com/25023667/168720251-ae61713c-78b1-4b41-a4ac-39225df69999.png)
![image](https://user-images.githubusercontent.com/25023667/168720315-215a99c2-9dc6-4a1d-a29b-3f53cee7bf20.png)
![image](https://user-images.githubusercontent.com/25023667/168720354-b39fd4f3-db0d-42b9-b3d0-b78660962336.png)
![image](https://user-images.githubusercontent.com/25023667/168720614-a24b1fcc-5455-474b-a1ed-f873944fcf50.png)

**Desktop (please complete the following information):**
 - OS: wsl【ubuntu】

**iris.Version**
- v12.2.0-alpha5.0.20220122232131-4899fe95f47d

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**

**Comment by Teeoo** [comment]
I seem to know the reason, when the file suffix is ​​uppercase, it will trigger 404 lowercase and it is normal

**Comment by Teeoo** [comment]
Could this be a bug?

**Comment by kataras** [comment]
Hello @Teeoo,

Could you please try running with `app.Listen(":8080", iris.WithLowercaseRouting)` or set to true the configuration's `ForceLowercaseRouting` field?

**Comment by Teeoo** [comment]
After I ForceSetLowercaseRouting it is normal, thank you

**Comment by kataras** [comment]
You are welcome @Teeoo!
