### ISSUE TITLE
How to emmbed static resources into iris powered app?

### ISSUE THREAD

**Issue by netroby** [kataras/iris#189]
I want package css,js, png,jpeg static files into the build binary executable file.
So the result binary file can be easily deploy to anywhere.

**Comment by kataras** [comment]
You can use  the [https://github.com/jteeuwen/go-bindata](go-binddata) to generate  and use the Assets configuration field which you can find [here](https://github.com/kataras/iris/blob/master/config/render.go#L100)  to register your templates, thanks for the question!

**Comment by kataras** [comment]
You can use  the [https://github.com/jteeuwen/go-bindata](go-binddata) to generate  and make use of the Asset and AssetName configuration field which you can find [here](https://github.com/kataras/iris/blob/master/config/render.go#L100)  to register your templates ( it's just a func which you will return the binary data of your template) , thanks for the question!

**Comment by hrwebasst** [comment]
I understand how this is simply done with templates.
`iris.UseTemplate(django.New()).Directory("./templates", ".html").Binary(Asset, AssetNames)`

What is the best way to do this with iris.Static?

**Comment by kataras** [comment]
@hrwebasst I suppose with `iris.StaticContent` which receives raw []byte, test it and tell me the results if something more needed I'll do it

**Comment by hrwebasst** [comment]
@kataras thank you, I'll try it out. I was hoping it would be possible if we could do something simple like:
`iris.StaticServe("/static", "/assets/static").Binary(Asset, AssetNames)`

I understand .Binary is called after a Loader but the concept is very simple. That way we could generate all of our assets with `go-bindata -pkg main -o assets.go assets/...`
```
assets/
    javascript/
    css/
    templates/
```

**Comment by hrwebasst** [comment]
I don't feel like you need to put a lot of work into it of course. For people that have this question in future it's simple enough to do:

```
iris.UseTemplate(django.New()).Directory("./assets/templates", ".html").Binary(Asset, AssetNames)

	iris.Get("/static/*path", func(ctx *iris.Context) {

		filepath := fmt.Sprintf("assets/static%s", ctx.Param("path"))
		fmt.Printf("looking for: %s", filepath)

		data, err := Asset(filepath)
		if err != nil {
			ctx.Write("asset not found")
		}

		ctx.Data(iris.StatusOK, data)

	})
```

**Comment by speedwheel** [comment]
Your code makes sense. 

That would be awesome, and other users will benefit from it. Thanks.

**Comment by kataras** [comment]
I already provided a manually solution here: https://github.com/kataras/iris/issues/485#issuecomment-254068254


But @hrwebasst I will implement your feature request at the next hour, you are not the only one who didn't know how to do it at the first place, thanks!

**Comment by kataras** [comment]
Done, 

**outline**
```go

// StaticEmbedded  used when files are distrubuted inside the app executable, using go-bindata mostly
// First parameter is the request path, the path which the files in the vdir(second parameter) will be served to, for example "/static"
// Second parameter is the (virtual) directory path, for example "./assets"
// Third parameter is the Asset function
// Forth parameter is the AssetNames function
//
// For more take a look at the
// example: https://github.com/iris-contrib/examples/tree/master/static_files_embedded
StaticEmbedded(requestPath string, vdir string, assetFn func(name string) ([]byte, error), namesFn func() []string) RouteNameFunc

```

**example**

You can view and run it from [here](https://github.com/iris-contrib/examples/tree/master/static_files_embedded) *

```go
package main

// First of all, execute: $ go get https://github.com/jteeuwen/go-bindata
// Secondly, execute the command: cd $GOPATH/src/github.com/iris-contrib/examples/static_files_embedded && go-bindata ./assets/...

import (
	"github.com/kataras/iris"
)

func main() {

	// executing this go-bindata command creates a source file named 'bindata.go' which
	// gives you the Asset and AssetNames funcs which we will pass into .StaticAssets
	// for more viist: https://github.com/jteeuwen/go-bindata
	// Iris gives you a way to integrade these functions to your web app

	// For the reason that you may use go-bindata to embed more than your assets, you should pass the 'virtual directory path', for example here is the : "./assets"
	// and the request path, which these files will be served to, you can set as "/assets" or "/static" which resulting on http://localhost:8080/static/*anyfile.*extension
	iris.StaticEmbedded("/static", "./assets", Asset, AssetNames)


	// that's all
	// this will serve the ./assets (embedded) files to the /static request path for example the favicon.ico will be served as :
	// http://localhost:8080/static/favicon.ico
	// Methods: GET and HEAD



	iris.Get("/", func(ctx *iris.Context) {
		ctx.HTML(iris.StatusOK, "<b> Hi from index</b>")
	})

	iris.Listen(":8080")
}

// Navigate to:
// http://localhost:8080/static/favicon.ico
// http://localhost:8080/static/js/jquery-2.1.1.js
// http://localhost:8080/static/css/bootstrap.min.css

// Now, these files are stored inside into your executable program, no need to keep it in the same location with your assets folder.


```
