### ISSUE TITLE
Pull the latest package and report an error

### ISSUE THREAD

**Issue by kaishibianchengqiji12** [kataras/iris#1891]
go get github.com/kataras/iris/v12@master

Error in Windows OS

![image](https://user-images.githubusercontent.com/50549812/169731520-82775aab-10d3-403e-ad5b-974b31ece493.png)

**Comment by kataras** [comment]
Hello @kaishibianchengqiji12, provide go version please with the `go version` command as the issue template says. If you have installed <1.17 please upgrade your [Go](https://golang.org/dl) language and retry to get the `github.com/kataras/iris@master`.

**Comment by kaishibianchengqiji12** [comment]
thanck You！ ready to download

**Comment by kataras** [comment]
You are welcome @kaishibianchengqiji12 !
