### ISSUE TITLE
Is there a way to set ignoreUnknownKeys When calling ctx.ReadQuery

### ISSUE THREAD

**Issue by Xujkstra** [kataras/iris#1895]
There is a method to set queryDecode ignoreUnknownKeys true, but there is no way to set it when using ctx.ReadQuery to parse query?

**Comment by kataras** [comment]
Hello @Xujkstra,

Yes, correct. There is the `DisallowUnknownFields` on

```go
err := ctx.ReadJSON(&value, iris.JSONReader{
  DisallowUnknownFields: true,
  Optimize: true,
}
```

About `ctx.ReadQuery`, by default we don't fire error on unknown parameter and we don't have a way to customize it per-call, BUT there is a way - it's a bit tricky but there is, you need to access the iris-contrib/schema and on initialization of your program, change the default query decoder (which affects all ctx.ReadQuery calls):

```go
import "github.com/iris-contrib/schema"

func init() {
  // fire an error on unknown url query parameter, but valid parameters stil binded.
  schema.Query.IgnoreUnknownKeys(false) 
}

// ...more code
// example inside an Iris Handler:
err := ctx.ReadQuery(&value)
```

**Comment by kataras** [comment]
Hello @Xujkstra,

Yes, correct. There is the `DisallowUnknownFields` on

```go
err := ctx.ReadJSON(&value, iris.JSONReader{
  DisallowUnknownFields: true,
  Optimize: true,
}
```

About `ctx.ReadQuery`, by default we don't fire error on unknown parameter and we don't have a way to customize it per-call, BUT there is a way - it's a bit tricky but there is, you need to access the iris-contrib/schema and on initialization of your program, change the default query decoder (which affects all ctx.ReadQuery calls):

```go
import "github.com/iris-contrib/schema"

func init() {
  // fire an error on unknown url query parameter, but valid parameters stil binded.
  schema.Query.IgnoreUnknownKeys(false) 
}

// ...more code
// example inside an Iris Handler:
err := ctx.ReadQuery(&value)

```

To check for unknown url query parameter, you need to check if the err != nil and if the error is an `schema. MultiError` and contains an `schema.UnknownKeyError`, that error value holds the `.Key` field which reports the unknown parameter's name.
