### ISSUE TITLE
Cannot use (type func(ctx iris.Context)) as the type context.Handler

### ISSUE THREAD

**Issue by Heylosky** [kataras/iris#1896]
Why i got this error on my GoLand ? But in fact, the code can run with no error.

![image](https://user-images.githubusercontent.com/96582832/170426227-c96ffb67-ddde-4a53-8384-309a74528927.png)

**Comment by kataras** [comment]
Hello @Heylosky,

1. Download latest Go programming language: https://golang.org/dl.

2. Go to your project's folden, open a temrinal and install latest Iris:

```sh
go get github.com/kataras/iris/v12@master
go mod tidy -compat=1.18
# if windows: go mod tidy -compat="1.18" 
```

3. Report if you have issues.

**Comment by Heylosky** [comment]
Hello, I follow the steps but the error still shows.
![image](https://user-images.githubusercontent.com/96582832/170457712-0c2aa090-bdbb-4c1b-8752-dab9f528b9a9.png)
![image](https://user-images.githubusercontent.com/96582832/170457763-968099ef-f5bf-4c59-bc60-f2feb78b263f.png)
![image](https://user-images.githubusercontent.com/96582832/170457845-16ec498d-c8d8-4f8b-a2d7-7d3c89b5df8c.png)

Is this a problem with my the Goland configuration only? as it does not affect the code running.

**Comment by kataras** [comment]
@Heylosky this is wrong that's why it fails. Why you changed the improt path to `import "github.com/kataras/iris"` now? You should import "github.com/kataras/iris/v12" as your first comment.

**Comment by Heylosky** [comment]
After i change it still wrong.
![image](https://user-images.githubusercontent.com/96582832/170870263-8d38576f-8998-477e-89e8-1fc6de0ee921.png)

**Comment by kataras** [comment]
@Heylosky can you print us the `go.mod` file contents of yours? I am sure you are not using the latest version there.
