### ISSUE TITLE
Setting a header with a multi-line string affects the response body

### ISSUE THREAD

**Issue by heynemann** [kataras/iris#190]
If you use a multi-line string as a header as in:

    header := `some
    multi-line
    string`
    c.SetHeader("Some-Header", header)
    c.Write("Hello World")

Iris gets confused and you do not get Hello World in the body of the response. If you do trim all the spaces around the multi-line header it works, though.

I don't think setting headers should affect the response body, no matter what value you set as header.

**Comment by kataras** [comment]
This is not Iris bug, I think you should transfer this bug report to [fasthttp](https://github.com/valyala/fasthttp), if valyala doesn't fix it then I will try to fix it through Iris, ok my friend?

**Comment by kataras** [comment]
This is not Iris bug, I think you should transfer this bug report to [fasthttp](https://github.com/valyala/fasthttp), if @valyala doesn't fix it soon then (and only then) I will try to fix it through Iris, ok my friend? 


` c.SetHeader(k,v) -> fasthttp: RequestCtx.Response.Header.Set(k, v)` 

` c.Write -> fasthttp: RequestCtx.WriteString(fmt.Sprintf(format, a...))`

**Comment by kataras** [comment]
This is not Iris bug, I think you should transfer this bug report to [fasthttp](https://github.com/valyala/fasthttp), if @valyala doesn't fix it soon then (and only then) I will try to fix it through Iris, ok my friend? 


` c.SetHeader(k,v) -> fasthttp: RequestCtx.Response.Header.Set(k, v)` 

` c.Write(format,...a) -> fasthttp: RequestCtx.WriteString(fmt.Sprintf(format, a...))`

**Comment by kataras** [comment]
@heynemann  Hello, I though your request, we could add ` strings.TrimSpace`  on `context.SetHeader` but there is no need to do something like this, if you want to add a multi line string then do TrimSpace by yourself. For the 'body' and 'header' confusion on multi line please refer to the [fasthtt](https://github.com/valyala/fasthttp) although it is not problem for me, who will use multi line string for header value lol, thanks for your issue!

**Comment by kataras** [comment]
@heynemann  Hello, I though your request, we could add ` strings.TrimSpace`  on `context.SetHeader` but there is no need to do something like this, if you want to add a multi line string then do TrimSpace by yourself. For the 'body' and 'header' confusion on multi line please refer to the [fasthttp](https://github.com/valyala/fasthttp) although it is not problem for me, who will use multi line string for header value lol, thanks for your issue!

**Comment by kataras** [comment]
@heynemann  Hello, I though your request, we could add ` strings.TrimSpace`  on `context.SetHeader` but there is no need to do something like this, if you want to add a multi line string then do TrimSpace by yourself. For the 'body' and 'header' confusion on multi line please refer to the [fasthttp](https://github.com/valyala/fasthttp) although, in my opinion, it is not problem, at the end, who will use multi line string for header value lol, thanks for your issue!

**Comment by kataras** [comment]
@heynemann  Hello, I though your request, we could add ` strings.TrimSpace`  on `context.SetHeader` but there is no need to do something like this, if you want to add a multi line string then do TrimSpace by yourself. For the 'body' and 'header' confusion on multi line please refer to the [fasthttp](https://github.com/valyala/fasthttp).

` c.SetHeader(k,v) -> fasthttp: RequestCtx.Response.Header.Set(k, v)` 

` c.Write(format,...a) -> fasthttp: RequestCtx.WriteString(fmt.Sprintf(format, a...))` 

Although, in my opinion, it is not problem, at the end, who will use multi line string for header value lol, thanks for your issue!

**Comment by valyala** [comment]
Created the corresponding `fasthttp` issue - https://github.com/valyala/fasthttp/issues/123
