### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by whoisfisher** [kataras/iris#1904]
**Describe the bug**
After a period of time, the IRIS service suddenly fails to be accessed. After restarting the service, the service returns to normal. What should I do?
**To Reproduce**
1. [...]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**iris.Version**
- e.g. v12.2.0-alpha8 or master

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**

**Comment by kataras** [comment]
We are running Iris on production with thousand of users and activity and we didn't notice any failure to the executable. Please provide more information so I can help you @whoisfisher
