### ISSUE TITLE
How to make iriscontrol or editor listen on something other than 127.0.0.1?

### ISSUE THREAD

**Issue by DSpeichert** [kataras/iris#191]
it seems like we can define the port that iriscontrol or editor would listen on but they default to 127.0.0.1 to listen on. I can't seem to find a way to change that. Any help will be appreciated.

**Comment by kataras** [comment]
Hello @DSpeichert 

You have right about iriscontrol, but this is fixed now` go get -u github.com/kataras/iris` , is listening on the main server's hostname, but the editor plugin has  ` config.Editor.Host ` and ` config.Editor.Port`   field, you should fill these.

**Comment by kataras** [comment]
Just added a realtime browser logger to the iris control plugin also, remove the $USER/.iris folder (if any, in order to re-download the clientside assets for the iris control)

**Comment by kataras** [comment]
Just added a realtime browser logger to the iris control plugin also, remove the %HOME%/.iris folder (if any, in order to re-download the clientside assets for the iris control)

**Comment by DSpeichert** [comment]
@kataras Thank you, that works. Is there any way to use TLS with the IrisControl?

**Comment by kataras** [comment]
@DSpeichert TLS is used automatically by the iris control when your main server has TLS, you want to add an option for TLS only on iris control?

**Comment by DSpeichert** [comment]
I think I have a few problems that are related:
* I run iris.ListenWithTLS and yet the iriscontrol does not work over TLS, only plain-HTTP (it shows errors on iris server console when trying https)
* Iris control stopped workin (MustRender panics for client with IP: x On template: index.html) - this worked before, now it seems to be missing assets.

**Comment by kataras** [comment]
Can you open a new post for this new issue please? 

I'm working on [this](https://github.com/kataras/rizla) right now, I will look that a little bit later ok?
