### ISSUE TITLE
Whether each connection will start a separate coroutine to process, use websocket native message

### ISSUE THREAD

**Issue by nathonNot** [kataras/iris#1928]
我现在正在用v12/websocket库构建游戏服务器
I am now building a game server with v12/websocket library

我的预期设计是，在项目中，每个玩家都应该有自己的消息处理协程，来保证一些io操作不会影响到其他玩家的消息处理
My expected design is that in the project, each player should have its own message processing coroutine to ensure that some io operations will not affect the message processing of other players

我目前的代码是这样的
My current code is like this

```
func InitEvent() neffos.Events {
	SocketEvent := neffos.Events{
		websocket.OnNativeMessage: func(nsConn *websocket.NSConn, msg websocket.Message) error {

			data := encryption.Decoding(string(msg.Body))
			clientInfo := &message.MsgBase{}
			err := json.Unmarshal(data, clientInfo)
			if err != nil {
				return nil
			}
			if clientInfo.MsgType == GameInterface.Heartbeat {
				return nil
			}
			msgInfo := &message.MsgHandlerInfo{
				MsgBase: clientInfo,
				Conn:    nsConn,
			}
			DispatchEvent(msgInfo)
			//player := gamer.GetPlayerByConnId(nsConn.Conn.ID())
			//if player != nil {
			//	player.MessageChannel <- msgInfo
			//	return nil
			//}
			//room := gamer.GetRoomByConnId(nsConn.Conn.ID())
			//if room != nil {
			//	room.MessageChannel <- msgInfo
			//	return nil
			//}
			//MsgHandle <- msgInfo
			//log.ConnectLog(nsConn.Conn).Printf("Server got: %s", clientInfo.MsgInfo)

			return nil
		},
	}
	return SocketEvent
}
```
我想知道，如果我在DispatchEvent方法中进行一些sql的操作，是否会阻塞到其他连接的消息处理？我是否需要单独为每个玩家单独做chan来运行协程
I would like to know, if I do some sql operations in the DispatchEvent method, will it block the message processing to other connections? Do I need to do chan for each player individually to run the coroutine

**Comment by kataras** [comment]
Hello @nathonNot,

Each webscoket communication message lives on its own goroutine, so if you add some sql login inside there it shouldn't block the rest.

**Comment by nathonNot** [comment]
Thank you for your reply.

**Comment by kataras** [comment]
Of course, you are welcomed @nathonNot
