### ISSUE TITLE
Add Layout support for Jade Engine

### ISSUE THREAD

**Issue by p4tin** [kataras/iris#193]
In jade you can create a template file and they use "block content" in the template and then in the partials you simply say:

extends layout
block content

and everything in the block content is added to the template to produce the html page.  This does not appear to be supported in iris and may not be supported in Joker/Jade either.

**Comment by kataras** [comment]
Reference: https://github.com/Joker/jade/issues/7

If the Joker doesn't solve it I will do, but no with partial ` extends and block` but with the layout system iris has

**Comment by bang88** [comment]
Jade was rename to Pug https://github.com/pugjs/pug
Its best to keep the same syntax and extend way,so someone can use an jade template on both client and server,what do you think ?

**Comment by kataras** [comment]
Done, https://github.com/iris-contrib/examples/tree/master/template_engines/template_pug_2
