### ISSUE TITLE
[FEATURE REQUEST] Redirect with flash messages

### ISSUE THREAD

**Issue by mostafa-binesh** [kataras/iris#1937]
Hi. I was working on a login form today with template and flash messages, and I created two functions:
```
func Render(ctx iris.Context, address string, data iris.Map) {
		s := sessions.Get(ctx)
		s.SetFlash("flashmessage", data)
		ctx.Redirect(address)
}
```
```
func GetFlashData(ctx iris.Context) interface{} {
	        s := sessions.Get(ctx)
		data := s.GetFlash("flashmessage")
		return data
}
```
The first one sets some flash data and redirects the user to the address, and we have to use GetFlashData like this:
```
app.Get("/", func(ctx iris.Context) {
		returnedFlashData := GetFlashData(ctx)
		ctx.ViewLayout("main")
		ctx.View("index",returnedFlashData)
	})
```
Please add these two functions and then make the ctx.View somehow that I should not add returnedFlashData and the framework do it automaticly
Thanks

**Comment by kataras** [comment]
Hello @mostafa-binesh,

We can't bind flash messages to an "index" view or any view automatically. This will confuse users and may occur to unexpected behavior and reported issues by Iris developers. Your code is specifically for your own use case (sessions + an index template + redirect), somebody else may use browser's local storage. Iris is a modular web framework, so you did it using the existing API - nothing stopped you.
