### ISSUE TITLE
[NOT WORKING] CSRF

### ISSUE THREAD

**Issue by mostafa-binesh** [kataras/iris#1938]
Hey. CSRF examples and library has been outdated
Please update it
https://github.com/kataras/iris/tree/3b572eb23b43cf6ce560b4b2bb525b6f8f350e4a/_examples/miscellaneous/csrf
error: C:\Users\...\go\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20220722121102-69215b87ab0b\csrf.go:177:48: cannot call pointer method String on "github.com/kataras/iris/v12/context".Referrer

**Comment by kataras** [comment]
Good catch @mostafa-binesh, fixed!

**Comment by mostafa-binesh** [comment]
The latest update was 4 days ago by @Thelvaen. Maybe those changes broke it
