### ISSUE TITLE
[BUG] DisableBodyConsumptionOnUnmarshal  not effective

### ISSUE THREAD

**Issue by CyJaySong** [kataras/iris#1939]
**Describe the bug**
DisableBodyConsumptionOnUnmarshal  not effective

**To Reproduce**
_ = irisApp.Run(iris.Addr("0.0.0.0:8080"), iris.WithPathEscape,
		iris.WithOptimizations, iris.WithoutInterruptHandler, iris.WithoutBodyConsumptionOnUnmarshal)

**Expected behavior**
fix it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 

**iris.Version**
- v12.2.0-beta4

**Comment by kataras** [comment]
Hello @CyJaySong,

So, the [example](https://github.com/kataras/iris/tree/master/_examples/request-body/read-many) doesn't work on your side?

**Comment by CyJaySong** [comment]
@kataras yes, get a error with 'EOF' content when second unmarshal

**Comment by kataras** [comment]
Let me check @CyJaySong

**Comment by kataras** [comment]
@CyJaySong I don't see the error. The example is working. Could you please post a code snippet which reproduces the issue, based on the feature?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/22900943/181376280-b1eb58f2-7f97-4f49-9894-d6351eb13ad9.png">

**Comment by CyJaySong** [comment]
@kataras 

![lQLPJxaJZ58OssnNAc7NBJSwDrjwlyheHwkC4jC20ACJAA_1172_462 png_720x720g](https://user-images.githubusercontent.com/29367599/181397166-576ff7fa-0500-44e4-82a9-4bf208e05447.jpg)

**Comment by CyJaySong** [comment]
@kataras No exceptions when i use v12.2.0-beta3

**Comment by hwzp99** [comment]
> @CyJaySong I don't see the error. The example is working. Could you please post a code snippet which reproduces the issue, based on the feature?
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/22900943/181376280-b1eb58f2-7f97-4f49-9894-d6351eb13ad9.png">

@kataras readjson same problem

**Comment by yjz2222** [comment]
Please refer to the solution of #1949
