### ISSUE TITLE
Stormpath Intergration

### ISSUE THREAD

**Issue by Mudpuppy12** [kataras/iris#194]
This is more or less a feature request to support Stormpath authentication. I used it before for Flask and it was really nice middleware authentication.

**Comment by kataras** [comment]
Hello @Mudpuppy12 , thanks for the request but I dont think this will be implemented in the near future, at least by me, you can always create that as middleware for Iris and share with us. I don't think that Iris should have build'n support for all types of authentication apis, thanks you!

**Comment by kataras** [comment]
Hello @Mudpuppy12 , thanks for the request but I dont think this will be implemented in the near future, at least by me, you can always create that as middleware for Iris and share with us.

I will let this open, for any people interesting implement a third-party middleware for that

> If you like Iris star it please, this is the only way I know that people use this framework

**Comment by Mudpuppy12** [comment]
Sounds Good. I'll prob be playing around with it and see what I can implement. Your framework seems documented and easy enough to understand. Thank you.

**Comment by kataras** [comment]
Thanks you and welcome!! It's very easy to start creating middleware or plugin for iris, if you need anything more go to the chat I'll be there :)

**Comment by kataras** [comment]
With Iris version 4.0.0-alpha.4

Look the [middleware repo](https://github.com/iris-contrib/middleware) or [plugin repo](https://github.com/iris-contrib/plugin) for examples on how to do it by your own or any community member who wants to help here!
