### ISSUE TITLE
[BUG] GetDomain parsing error

### ISSUE THREAD

**Issue by uninstall-h** [kataras/iris#1945]
**Describe the bug**
Iris runs on 172.28.4.51, access from other machines will prompt “net/http: invalid Cookie.Domain "4.51"; dropping domain
 attribute”. The GetDomain parsing error can be located by debugging, and 172.28.4.51 is parsed into 4.151.

**iris.Version**
-  master

![debug](https://user-images.githubusercontent.com/23739868/183047425-ec4b3cb7-0fb8-4295-b938-0d4f724bf31f.png)

**Comment by kataras** [comment]
Hello @uninstall-h, this is an IP. You have several options to retrieve the host, here are some:

1. Run Iris under this specifically IP instead of localhost and retrieve with  `app` or `ctx.Application().ConfigurationReadOnly.GetVHost()`:

```go
app.Listen("172.28.4.51:80", ...)
```

2. Get through request:

```go
ctx.request.Host // OR
ctx.request.URL.Host
```

**Comment by uninstall-h** [comment]
Thanks for your reply. I may not have described the bug clearly, I am not trying to retrieve the host. I just don't want to see this warning, although it doesn't affect my business.
![warnning](https://user-images.githubusercontent.com/23739868/184474482-922a4e00-5f55-4298-ae99-a72f2ac5f5c0.png)
The device for the screenshot is 172.16.3.151.

**Comment by kataras** [comment]
@uninstall-h this is a std net/http error, could you please post an example code and steps to reproduce the issue?

**Comment by uninstall-h** [comment]
```Go
package main

import (
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/context"
	"github.com/kataras/iris/v12/sessions"
	"time"
)

const sessionCookieName = "session_"

func main() {
	app := iris.New()

	sess := sessions.New(sessions.Config{Cookie: sessionCookieName, AllowReclaim: true, Expires: time.Hour * 24})

	router := app.Party("/")
	router.Use(sess.Handler())

	router.Post("/", func(ctx context.Context) {
		_, _ = ctx.JSON(iris.Map{
			"code": 0,
		})

		return
	})

	app.Run(iris.Addr("0.0.0.0:80"))
}

```

Running on 172.16.3.151, it can be reproduced with the `curl 172.28.4.51/ -X POST --header "Content-Type: application/json"`  command.

But running the command  `curl localhost/ -X POST --header "Content-Type: application/json"` does not have this problem.

![console](https://user-images.githubusercontent.com/23739868/184563800-26fd50da-3ec2-478c-81bc-c74c0371bc1e.png)
![curl](https://user-images.githubusercontent.com/23739868/184563950-0693c342-68f6-4a3e-8731-0c7461f96691.png)

**Comment by ssongliu** [comment]
![image](https://user-images.githubusercontent.com/73214554/186107378-356ffc02-b45a-440e-812b-90431aa29cf9.png)
I have the same problem. Is there a solution ?

**Comment by uninstall-h** [comment]
@ssongliu I took a temporary solution to this problem by adding the following code after [HERE ](https://github.com/kataras/iris/blob/master/context/context.go#L1014)
```golang
		if net.ParseIP(host) != nil {
			return host
		}
```
![add](https://user-images.githubusercontent.com/23739868/186555978-ffc0f7fa-8905-4d32-9945-a13e2fa61dda.png)

**Comment by kataras** [comment]
Thanks @uninstall-h, that seems right. I've just pushed a commit.
