### ISSUE TITLE
Example Sessions + Template + Basic Auth

### ISSUE THREAD

**Issue by Mudpuppy12** [kataras/iris#195]
Was playing around with Iris. Thought someone might like this as an example

https://gist.github.com/Mudpuppy12/db9f2a2b4ab62babd72a1edddd4b5273

**Comment by xpbliss** [comment]
wrong link?

**Comment by xpbliss** [comment]
@Mudpuppy12 ,  when /logout，  it is still login status.

**Comment by kataras** [comment]
I dont understand why you use the 'low-level' sessions when you have access to sessions by ` context.Session()` :P 

@Mudpuppy12 You're free to make a pull request on [iris-contrib/examples](https://github.com/iris-contrib/examples) or the [gitbook](https://github.com/iris-contrib/gitbook)  I will approve any good pr there! thanks you!!
