### ISSUE TITLE
[QUESTION] MVC Routing Url

### ISSUE THREAD

**Issue by trungdlp-wolffun** [kataras/iris#1955]
**Is your feature request related to a problem? Please describe.**
Hi there, currently I'm working with Iris MVC, I use dynamic routing via the naming function. Ex:

`func(*Controller) GetLogin() - GET:/user/login`

**Describe the solution you'd like**
How can I name function plural with dynamic routing? Ex:

`func(*Controller) GetDo_Work() - GET:/user/do-work`

Or another naming like this.

**Describe alternatives you've considered**

**Additional context**
MVC Docs: https://docs.iris-go.com/iris/mvc/mvc
<img width="871" alt="image" src="https://user-images.githubusercontent.com/93299415/186564265-6c2aec37-edbe-49ba-b56d-7d9b005be70d.png">

**Comment by kataras** [comment]
Hello @trungdlp-wolffun, this feature already exists in the framework. take look at the example at: https://github.com/kataras/iris/blob/master/_examples/mvc/basic/main.go#L92.

```go
func (c *Controller) BeforeActivation(b mvc.BeforeActivation) {
	b.HandleMany("GET POST", "/user/do-work", "GetDo_Work()")
}

func (c *Controller) AfterActivation(a mvc.AfterActivation) { }
```

**Comment by trungdlp-wolffun** [comment]
Thanks!
