### ISSUE TITLE
[BUG] Ctx.SendFile file name will appear at the beginning of fixed UTF-8

### ISSUE THREAD

**Issue by Eminlin** [kataras/iris#1957]
**Describe the bug**
1.With `context.SendFile(str1, "")` method, a fixed UTF-8 header will appear 

![image](https://user-images.githubusercontent.com/20252561/187580377-27ae5c32-2f6b-4851-97ad-c7e744bf4583.png)

**iris.Version**
- v12.2.0-beta4

**Screenshots**
![image](https://user-images.githubusercontent.com/20252561/187579983-59c7094c-2827-4527-9c2b-fdc039515fdc.png)

**Comment by kataras** [comment]
@Eminlin What's the operating system you are testing it? I don't see the fixed filename in my [test](https://github.com/kataras/iris/blob/master/_examples/file-server/send-files/main.go) (macOS).

**Comment by Eminlin** [comment]
Thanks for your reply.

I try to use Windows 7 / Windows 10  / Windows Server 2019

Chrome Version: 103.0.5060.134

This does not seem to be caused by the operating system, I make the following modifications to remove this fixed UTF-8 filename beginning: 

```go
func MakeDisposition(filename string) string{
  return `attachment;filename:` +url.QueryEscape(filename)+`filename*'UTF-8''` + url.QueryEscape(filename)
}
```

But it change to like `_filename_.zip`, an underscore appears.

I don't have a clue :(

Have a nice day

**Comment by fanglina** [comment]
https://github.com/kataras/iris/blob/master/_examples/file-server/send-files/main.go

It works (Windows7),  I don't see the fixed filename

**Comment by optimistic9527** [comment]
@Eminlin  same issues，can you help me？how to fix it

**Comment by Eminlin** [comment]
@optimistic9527 按照 https://github.com/kataras/iris/blob/master/_examples/file-server/send-files/main.go 里面的例子，就没发现问题了
