### ISSUE TITLE
[FEATURE REQUEST] Compilation speed improved

### ISSUE THREAD

**Issue by aadog** [kataras/iris#1964]
Compilation speed of iris is getting slower and slower now, use grouping and reflection to speed up compilation

**Comment by aadog** [comment]
Speed ​​is not that important, speeding up and speeding up the developer experience

**Comment by kataras** [comment]
Hello @aadog, what is your machine's hardware details? Compilation of our company's iris services (a lot of code) is done within a range of 2 to 5 seconds (mac).

**Comment by aadog** [comment]
At present, there are too many built-in components in iris, resulting in slow compilation speed

The compilation speed of gin is several times faster than iris

**Comment by kataras** [comment]
@aadog gin is just a router + some useful functions and middlewares. Iris is a web framework. Iris builtin code is not as large as other alternatives of the same software. Compilation in Go and Iris is fast enough compared to the rest languages and frameworks of the identical type of features.

> use grouping and reflection to speed up compilation`

How reflection and grouping can make compilation faster?

Also, check [gin vs iris #1396](https://github.com/kataras/iris/issues/1396).
