### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#197]
Feature request: I know that everyone can implement himself this security layer but, wouldn't be good to have it inside the secure middleware?

**Comment by kataras** [comment]
Hello @es-lab we have two middleware(s) for this scope

https://github.com/kataras/iris/tree/master/middleware/secure
https://github.com/kataras/iris/tree/master/middleware/cors

Of course these are the start, the rest of your security SHOULD be your responsibility

**Comment by ptman** [comment]
Those don't seem to protect form CSRF/XSRF, or am I mistaken?

See e.g. https://github.com/justinas/nosurf

**Comment by kataras** [comment]
Nice, you just need to port it to Iris, let's do some third party libraries guys, this is open source!
