### ISSUE TITLE
How to use Godash OmitByKeys with ReadJSON

### ISSUE THREAD

**Issue by tienanh088** [kataras/iris#1972]
Here is my code to use

```
var payload orm.Users
  
if err := ctx.ReadJSON(&payload); err != nil {
  ctx.StopExecution()
  panic("Error to read JSON")
}
```

How do I use the `OmitByKeys` for `payload` like:
`lo.OmitByKeys(payload, []string{"password"})`

This is the library which I used https://github.com/samber/lo

**Comment by kataras** [comment]
Hello @tienanh088 ,

I have no idea, never used that library. Why you didn't post that question there instead?

**Comment by kataras** [comment]
Hello @tienanh088 ,

I have no idea, never used that library. ReadJSON fills the orm.Users by reading the request body. After that you can use the structure as any go value. Why you didn't post this question to their repository instead?
