### ISSUE TITLE
How to add  template funcs to views

### ISSUE THREAD

**Issue by Ianmuhia** [kataras/iris#1976]
Any way examples on how to add template funcs to view, for example [masterminds sprig](http://masterminds.github.io/sprig/).

**Comment by kataras** [comment]
@Ianmuhia it depends on the template engine, e.g. for HTML (standard go html template package):

https://github.com/kataras/iris/blob/76d69a25dd40109f590b5a8a4b22fd0b47ed5e46/_examples/view/template_html_0/main.go#L10-L22
