### ISSUE TITLE
Graceful middleware causes routing registration error

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#198]
The RunWithErr function of the graceful middleware causes all of the routes errors, but it is normal to use iris.Listen.
Output message:
```
panic: 
[IRIS]  Error: Router: Middleware were already registered for the path: '/static/*filepath' !
panic: 
[IRIS]  Error: Router: Middleware were already registered for the path: '/' !
```

**Comment by kataras** [comment]
@dxvgef  Can you saw is the code snippet?

**Comment by kataras** [comment]
@dxvgef  Can you post the code snippet you're using to produce this error?

**Comment by kataras** [comment]
Propably you did something wrong, I just tested it... post your code here in order to help you

**Comment by dxvgef** [comment]
@kataras Use this sample code did not work
https://kataras.gitbooks.io/iris/content/package-graceful.html
I have tried the 3.0.0-rc1 and 3.0.0-rc2, output an error message:
```
panic:
[IRIS] Error: Router: Middleware were already registered for the path: '/'!
```

**Comment by kataras** [comment]
@dxvgef Fixed :)
