### ISSUE TITLE
Cannot Use Middlewares in Iris

### ISSUE THREAD

**Issue by JohnKinyanjui** [kataras/iris#1982]
go: module github.com/kataras/iris/v12@latest found (v12.1.8), but does not contain package github.com/kataras/iris/v12/middleware/jwt

**Comment by kataras** [comment]
Hello @JohnKinyanjui, please try `go get github.com/kataras/iris/v12@master` instead of `latest`. The version contains the builtin jwt middleware is the v12.2.0+ (current v12.2.0-beta5+).
