### ISSUE TITLE
Tarantool provider

### ISSUE THREAD

**Issue by kirillDanshin** [kataras/iris#199]
Hi!
First of all, thanks for cool framework!

I want to request a [tarantool](http://tarantool.org/) ([github](https://github.com/tarantool/tarantool)) session provider. Is it possible?

Thanks!

**Comment by kataras** [comment]
With Iris version 4.0.0-alpha.4 you can create & use your own session db, look [this repo](https://github.com/iris-contrib/sessiondb) for examples on how to do it!!
