### ISSUE TITLE
Can I get the http message

### ISSUE THREAD

**Issue by CyJaySong** [kataras/iris#1990]
Is there any Api that can obtain the standard format http message text?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview#http_messages

**Comment by kataras** [comment]
Hello @CyJaySong, 

You can use the standard `net/http/httputil` package to get the full request:

```go
dump, err := httputil.DumpRequest(ctx.Request(), false)
```

And for response (at your http clients):

```go
dump, err := httputil.DumpResponse(resp, true)
```

This is mostly useful for debugging and error reporting.

Am I missing something?

**Comment by CyJaySong** [comment]
Wow, that's cool
