### ISSUE TITLE
Support unit testing using Ginkgo with iris httptest

### ISSUE THREAD

**Issue by MuhmdHsn313** [kataras/iris#1991]
**Is your feature request related to a problem? Please describe.**
I always use **Ginkgo** for TTD, so I didn't find official support for **Ginkgo** on **Iris httptest**. **Ginkgo** doesn't provide an instance for `testing.T` for integrating 3rd party packages, but it provides `GinkgoT` that provides the same `testing.T` methods.

In `testing.T` case (Work correctly):
```golang
func TestNewApp(t *testing.T) {
    app := newApp()
    e := httptest.New(t, app)
}
```

In `GinkgoT()` case (does not work):
```golang
Describe("Suite Name", func() {
	var app *iris.Application
	var exp *httptest.Server

	BeforeAll(func() {
		app = iris.New()
		exp = httptest.New(GinkgoT(), app)
	})
})
```

**Describe the solution you'd like**
Most libraries accept the `testing.T` object via an interface and you can usually simply pass in `GinkgoT()` and expect the library to work. For example, if you're using [Gomock](https://code.google.com/p/gomock/) you can simply pass GinkgoT() to your controller : 
```golang
import (
  "code.google.com/p/gomock/gomock"

  . "github.com/onsi/ginkgo/v2"
  . "github.com/onsi/gomega"
)

var _ = Describe("Consumer", func() {
  var (
    mockCtrl *gomock.Controller
    mockThing *mockthing.MockThing
    consumer *Consumer
  )

  BeforeEach(func() {
    mockCtrl = gomock.NewController(GinkgoT())
    mockThing = mockthing.NewMockThing(mockCtrl)
    consumer = NewConsumer(mockThing)
  })


  It("should consume things", func() {
    mockThing.EXPECT().OmNom()
    consumer.Consume()
  })
})
```

**Comment by 1saifj** [comment]
I think it's very crucial for the Iris web framework to have an integration with Ginkgo or any BDD frameworks.

**Comment by MuhmdHsn313** [comment]
The feature supported with PR #1992
