### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by hardcoar** [kataras/iris#200]
WARNING: DATA RACE
Write by goroutine 15:
  github.com/kataras/iris.(*Server).serve()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/http.go:354 +0x7d

Previous read by main goroutine:
  github.com/kataras/iris.(*Server).IsListening()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/http.go:261 +0x37
  github.com/kataras/iris.(*Server).Host()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/http.go:276 +0x40
  github.com/kataras/iris.(*Framework).openServer()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/initiatory.go:178 +0x25f
  github.com/kataras/iris.(*Framework).ListenWithErr()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:200 +0x95
  github.com/kataras/iris.(*Framework).Listen()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:210 +0x42
  github.com/kataras/iris.Listen()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:188 +0x54
  main.main()
      /home/hanscem/Desktop/xx01/005/web/main.go:33 +0x2f7

Goroutine 15 (running) created at:
  github.com/kataras/iris.(*Server).listen()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/http.go:322 +0x16e
  github.com/kataras/iris.(*Server).Open()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/http.go:389 +0x307
  github.com/kataras/iris.(*Framework).openServer()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/initiatory.go:173 +0x136
  github.com/kataras/iris.(*Framework).ListenWithErr()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:200 +0x95
  github.com/kataras/iris.(*Framework).Listen()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:210 +0x42
  github.com/kataras/iris.Listen()
      /home/hanscem/GOLANG/src/github.com/kataras/iris/iris.go:188 +0x54
  main.main()
      /home/hanscem/Desktop/xx01/005/web/main.go:33 +0x2f7

main.go:33 here:
```
iris.Listen(":20000")
```

**Comment by kataras** [comment]
@hardcoar  did you upgrade iris? please give me more information

**Comment by kataras** [comment]
@hardcoar  No race conditions, you have a very old version. **Please upgrade your iris** with ` go get -u github.com/kataras/iris/iris` 

Relative: https://github.com/kataras/iris/issues/196

**Comment by kataras** [comment]
@hardcoar 
Before posting anything:
1. Check other issues first, if an issue didn't fixed already then post a new bug report.
2.  **upgrade your iris** with ` go get -u github.com/kataras/iris/iris` 

Thanks you!!

> Please star Iris if you liked it

**Comment by kataras** [comment]
Hello @hardcoar  I'm sorry I did that to you I just got upset when I read this issue which was already fixed on the previous issue of yours.

Thanks for the feedback, this will not happen again, just [upgrade iris](https://github.com/kataras/iris/blob/master/HISTORY.md) and this problem should dissapears!
