### ISSUE TITLE
[FEATURE REQUEST] Allow to replace golog dependency

### ISSUE THREAD

**Issue by lightglitch** [kataras/iris#2006]
**Is your feature request related to a problem? Please describe.**
I would like to have only on logger in  my project, and I'm unable to replace golog in iris. 
I know I can integrate external loggers in golog but I only get a string message already processed, no message arguments or stacktrace to report in the external logger as I want.

**Describe the solution you'd like**
Iris should use an interface that anyone can implement with all loggers.

**Comment by kataras** [comment]
You are correct but how this interface differs the ExternalLogger you mentioned? Could  you please provide an example which neither Externa Logger or `Handle` can help on using a 3rd-party logger?

```go
app.logger.Handle(func(value *golog.Log) bool {

    return true
})
```

**Comment by kataras** [comment]
You are correct but how this interface differs the ExternalLogger you mentioned? Could  you please provide an example which neither Externa Logger or `Handle` can help on using a 3rd-party logger?

```go
app.Logger().Handle(func(value *golog.Log) bool {

    return true
})
```

**Comment by lightglitch** [comment]
As a interface I should have access to:

1. the context where is called in iris because I may have extra information that I want to put in logs (request id for tracing, etc)
2. the error object, with information if it was panic error that was not handle by code but iris was able to catch
3. the message and the args raw values, not the formatted message

`golog.Log` doesn't provide this at the moment.

**Comment by kataras** [comment]
I am not getting it, all of the features you mention already exist in `golog` (fatal and information of the app in general) or middleware/[accesslog](https://github.com/kataras/iris/blob/master/_examples/logging/request-logger/accesslog-simple/main.go) (http). With `golog` you can put message and arguments (= [golog.Fields](https://github.com/kataras/golog/blob/cab8303b290e6111eaf9669d59c31768e747cbed/_examples/customize-output/main.go#L52)). For request id you can use the `middleware/requestid` and get the id through `ctx.GetID()`.

Could you please provide an example of all the features you mentioned ?

**Comment by lightglitch** [comment]
I'm not saying that `golog` doesn't have those features. I'm saying the ExternalLogger  integration doesn't pass that information to other loggers.
And I would like to avoid having multiple loggers in my project.

**Comment by kataras** [comment]
You don't need to pass an `ExternalLogger` to have that information. Use the `Handle` method, as I mentioned in my first comment. It provides that kind of flexibility through the [golog.Log](https://github.com/kataras/golog/blob/cab8303b290e6111eaf9669d59c31768e747cbed/log.go#L12-L36) instance:

```go
app.Logger().Handle(func(value *golog.Log) bool {
	// value.Timestamp int64
	// value.Level Level
	// value.Message string
	// value.Fields Fields
	// value.Stacktrace []Frame
	// value.NewLine bool
    return true
})
```

**Comment by kataras** [comment]
You don't need to pass an `ExternalLogger` to have that information. Use the `Handle` method, as I mentioned in my first comment. It provides that kind of flexibility through the [golog.Log](https://github.com/kataras/golog/blob/cab8303b290e6111eaf9669d59c31768e747cbed/log.go#L12-L36) instance:

```go
app.Logger().Handle(func(value *golog.Log) bool {
    // value.Timestamp int64
    // value.Level Level
    // value.Message string
    // value.Fields Fields
    // value.Stacktrace []Frame
    // value.NewLine bool
    yourLogger.Log(...)
    return true
})
```

**Comment by kataras** [comment]
You don't need to pass an `ExternalLogger` to have that information. Use the `Handle` method, as I mentioned in my first comment. It provides that kind of flexibility through the [golog.Log](https://github.com/kataras/golog/blob/cab8303b290e6111eaf9669d59c31768e747cbed/log.go#L12-L36) instance:

```go
app.Logger().Handle(func(value *golog.Log) bool {
    // value.Timestamp int64
    // value.Level Level
    // value.Message string
    // value.Fields golog.Fields
    // value.Stacktrace []golog.Frame
    // value.NewLine bool
    yourLogger.Log(...)
    return true
})
```

**Comment by lightglitch** [comment]
Sorry I misread the handle comment and thought you were talking about something else.
That would work, thx.

**Comment by kataras** [comment]
No worries @lightglitch, happy coding!
