### ISSUE TITLE
[BUG] route override with path parameters return 404

### ISSUE THREAD

**Issue by genfanh** [kataras/iris#2008]
**Describe the bug**
When I override route with path parameters, it reports not found. Does it a bug?

**To Reproduce**
1. the code look like below:
```
package main

import (
	"fmt"
	"github.com/kataras/iris/v12"
	"github.com/sirupsen/logrus"
)

func main() {
	irisApp := iris.Default()
	irisApp.Logger().SetLevel(logrus.DebugLevel.String())

	irisApp.Get("/api/v1/test/{echo:uint64}", func(context iris.Context) {
		_, _ = context.WriteString(fmt.Sprintf("echo is %d", context.Params().GetUint64Default("echo", 0)))
	})

	irisApp.Get("/api/v1/test/{echo:uint64}", func(context iris.Context) {
		_, _ = context.WriteString(fmt.Sprintf("echo 123 is %d", context.Params().GetUint64Default("echo", 0)))
	})

	if err := irisApp.Run(iris.Addr(":8080"), iris.WithCharset("UTF-8")); err != nil {
		logrus.Errorf("error with :%+v", err)
	}
}
```
2. when I use postman to visit 'http://localhost:8080/api/v1/test/123' , it returns 404.

**Expected behavior**
when I visit http://localhost:8080/api/v1/test/123, it should be returns `echo 123 is 123`

**Screenshots**
![image](https://user-images.githubusercontent.com/22853384/203600244-0793c48e-0575-4c70-b4b9-417e35f49bf9.png)
![image](https://user-images.githubusercontent.com/22853384/203600158-51b9dea9-643b-4044-aac5-8d93cc6dc83c.png)

**Desktop (please complete the following information):**
 - OS: windows or ubuntu

**iris.Version**
- e.g. v12.2.0-beta6

**Comment by kataras** [comment]
Thanks @genfanh for the report, it should be fixed now.
