### ISSUE TITLE
file upload confused

### ISSUE THREAD

**Issue by gkdgo** [kataras/iris#2011]
**Describe the bug**
https://www.iris-go.com/docs/#/?id=single-file
follow the example ,but error
**To Reproduce**
<img width="818" alt="Xnip2022-12-04_11-54-27" src="https://user-images.githubusercontent.com/55651847/205473594-1be57d20-b02a-4e3b-bd7d-b23f80b84368.png">

**iris.Version**
- e.g. v12.2.0-beta5

**Comment by kataras** [comment]
Hello @gkdgo, you are right, the documentation says "file" but the correct is to pass the "fileHeader". I am going to fix it rn, thanks!
