### ISSUE TITLE
Cookies not set

### ISSUE THREAD

**Issue by Elistratov** [kataras/iris#2027]
```
       outh := app.Party("/v1", func(ctx iris.Context) {
		tmpl := iris.HTML("./templates", ".html")
		tmpl.Reload(true)
		app.RegisterView(tmpl)
		ctx.View("/outh/outh.html")
	})

	outh.Get("/test", func(ctx iris.Context) {
		ctx.SetCookieKV("test", "testvalue")
	})
```
Why doesn't it set cookies?

If you do this: https://github.com/iris-contrib/examples/blob/master/cookies/basic/main.go, then cookies are set

how to make it work in my example?

**Comment by kataras** [comment]
Hello @Elistratov, I have tested it and cookies are set correctly. Can you provide a full example and steps to reproduce the issue? Thanks
