### ISSUE TITLE
layout.html placeholder {{ yield . }} rendered nothing after update version beta 7

### ISSUE THREAD

**Issue by schooltech** [kataras/iris#2033]
hi, as title above descipted, after I update iris v12.2.0-beta7,  the origial html layout html placholder {{ yield }} rendered nothing, 
also after I change to {{ yeild . }} as beta7 the document file HISTORY.md, and still displayed nothing.
when I downgrade back to version beta 6 and everything is ok.

`Breaking-change: HTML template functions yield, part, partial, partial_r and render now accept (and require for some cases) a second argument of the binding data context too. Convert: {{ yield }} to {{ yield . }}, {{ render "templates/mytemplate.html" }} to {{ render "templates/mytemplate.html" . }}, {{ partial "partials/mypartial.html" }} to {{ partial "partials/mypartial.html" . }} and so on.`

thank you very much

**Comment by kataras** [comment]
Hello @schooltech, please try to update by: `go get github.com/kataras/iris/v12@master` and try again, it should be fixed now.
