### ISSUE TITLE
Appears to be a dependency issue 

### ISSUE THREAD

**Issue by JuJu227** [kataras/iris#204]
### $ go get github.com/kataras/iris
   github.com/kataras/iris/logger
../github.com/kataras/iris/logger/logger.go:31: undefined: colorable.NewColorable

**Comment by kataras** [comment]
The Installation sections says: ` go get -u github.com/kataras/iris/iris` 

- -uu to upgrade all dependencies
- /iris/iris to install the iris command line tool in the same time

so please do ` go get -u github.com/kataras/iris/iris` and you should be fine :)
