### ISSUE TITLE
GRPC bindings not working correctly

### ISSUE THREAD

**Issue by AgentNemo00** [kataras/iris#2040]
**Describe the bug**
I get a panic on startup

```
panic: expected [3] bindings (input parameters) but got [2]
Function:
  - sca-chat/api.(*Server).GetMessages
Expected:
  - [1] *api.Server
  - [2] *grpc.RangeConfiguration
  - [3] grpc.Chat_GetMessagesServer
Missing:
  - [3] grpc.Chat_GetMessagesServer
```

**To Reproduce**
Create a grpc server

**Expected behavior**
No panic

**Screenshots**

```
func Start() {
	grpcServer := grpc.NewServer()

	myService := &Server{}
	grpc2.RegisterChatServer(grpcServer, myService)
	app := iris.New()

	rootApp := mvc.New(app)
	rootApp.Handle(myService, mvc.GRPC{
		Server:      grpcServer,  // Required.
		ServiceName: "grpc.Chat", // Required.
		Strict:      false,
	})
}
```

**Desktop (please complete the following information):**
 - OS: windows

**iris.Version**
- v12.2.0-beta7

Please make sure the bug is reproducible over the `master` branch:

Same problem on master

**Comment by kataras** [comment]
Hello @AgentNemo00, can you provide a full working code example so I can re-produce it by myself? I don't an issue so far.
