### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by hrwebasst** [kataras/iris#205]
A great REST alternative, the Facebook suggested standard standard for React apps

* [graphql](https://github.com/graphql-go/graphql) - An implementation of GraphQL for Go follows graphql-js
* [graphql-relay-go](https://github.com/graphql-go/relay) - A Go/Golang library to help construct a server supporting react-relay.
* [graphql](https://github.com/tmc/graphql) - GraphQL parser and server for Go.
* [c-graphqlparser](https://github.com/tecbot/c-graphqlparser) - Go-gettable version of the libgraphqlparser C library for parsing GraphQL.
* [tallstreet-graphql](https://github.com/tallstreet/graphql) - GraphQL parser and server for Go that leverages libgraphqlparser

**Comment by ryanbyyc** [comment]
👍 Seconded.

**Comment by Asoseil** [comment]
What is the best way to integrate graphql?

**Comment by kataras** [comment]
Hello @Asoseil , 

> What is the best way to integrate graphql?

as you used before Iris I suppose, did you stuck anywhere in the code?

**Comment by Asoseil** [comment]
there is no problem with iris and graph but I was curious to understand how graphql can be an integration of the v4 milestone

**Comment by kataras** [comment]
@Asoseil Community wantsintegration for some reason, so I will look it when fnal v3 released and start for v4. I really  don't know yet,  we will discuss it when the time comes.

**Comment by armandodev** [comment]
I agree with beast. This would be very ideal and a win for the Iris community.

**Comment by kataras** [comment]
Hello folks, The last month, I saw many of usages with Graphql for Golang with some libraries and I also implement integration with my local Iris, but the results were not good, happens to make things harder and not easier. Graphql for Golang, with standalone libraries, is enough good, I released that it's not needed to add something like this into Iris, we will complicate things without a good reason. I don't like to disagree with community but, **Graphql will not be added into Iris as built'n feature, like ORM, you can select your favourite library and work with that**. Thanks for your suggestions!
