### ISSUE TITLE
how to translate a msg by iris.Context

### ISSUE THREAD

**Issue by gkdgo** [kataras/iris#2051]
after set 
```go 
app.I18n.SetDefault("en-US")

````
how to translate a msg to other language while app running 
I guess it could be like this 
```go 
res:=ctx.TransLang(key,"zh-CN")

```

**Comment by gkdgo** [comment]
oh I find the method ctx.SetLanguage, I've been focusing on the app and ignore the context

**Comment by kataras** [comment]
No worries @gkdgo! Have fun
