### ISSUE TITLE
What makes Iris so much faster than the others?

### ISSUE THREAD

**Issue by treeder** [kataras/iris#206]
What are you guys doing differently?

**Comment by qskousen** [comment]
The main components to make it fast are: 

1. Using FastHTTP and making everything by default use `[]byte` type as much as possible
2. Custom router that works as fast as possible, again using `[]byte` and built to work directly with FastHTTP

That is my understanding, however @kataras can probably answer this better when he wakes up.

**Comment by kataras** [comment]
3. Other frameworks uses slices(which underhood locks by golang runtime when concurrency) or maps to the router, we use different approach which produce 0 locks on runtime.
4. Custom gzip library instead the golang's standard to serve content from the server
5. General code

**Comment by kataras** [comment]
As @qskousen  told, uses fasthttp and follows its path, working with []byte on runtime when this is possible, 

3. Other frameworks uses slices(which underhood locks by golang runtime when concurrency) or maps to the router, we use different approach which produce 0 locks on runtime.
4. Custom gzip library instead the golang's standard to serve content from the server
5. BSD-kernel's like mux algorithm
5. General code abstraction and other small things 

Welcome @treeder !

**Comment by kataras** [comment]
As @qskousen  told, uses fasthttp and follows its path, working with []byte on runtime when this is possible, 

3. Other frameworks uses slices(which underhood locks by golang runtime when concurrency) or maps to the router, we use different approach which produce 0 locks on runtime.
4. Custom gzip library instead the golang's standard to serve content from the server
5. BSD-kernel's like mux algorithm
6. self-optimized router which depends on what routes you registered to
7. General code abstraction and other small things 

Welcome @treeder !

**Comment by kataras** [comment]
As @qskousen  told, uses fasthttp and follows its path, working with []byte on runtime when this is possible, 

3. Other frameworks uses slices(which underhood locks by golang runtime when concurrency) or maps to the router, we use different approach which produce 0 locks on runtime.
4. Custom gzip library instead the golang's standard to serve content from the server
5. BSD-kernel's like mux algorithm
6. self-optimized router which depends on what routes you registered to
7. General code abstraction and other small things 
8. and last, 24/24 coding only for iris, drop normal life for 3 months

Welcome @treeder !

**Comment by alaska** [comment]
> slices(which underhood locks by golang runtime when concurrency)
Care to explain this a bit further? I was unaware of any extra runtime-locking on slices.

**Comment by kataras** [comment]
It's better to search on google, my english will confuse you even more, the meaning is that you said already ` they are still unsafe for concurrent writing.`

**Comment by ScottMansfield** [comment]
@alaska there is no locking for slices. Anything not synchronized is unsafe for concurrent writing in general.

**Comment by dxvgef** [comment]
Iris performance is good, but the updated changes too frequently, such as variable name and function name, hope this is temporary and stable as soon as possible.
