### ISSUE TITLE
http: multiple response.WriteHeader calls with first example

### ISSUE THREAD

**Issue by tuxlinuxien** [kataras/iris#208]
when i run *siege* i got this message, then the more i have simultaneous clients, the more i have this message.

```
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
2016/06/22 12:43:14 http: multiple response.WriteHeader calls
[...]
```

is that normal?

**Comment by kataras** [comment]
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol

**Comment by kataras** [comment]
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris **IS NOT NET/HTTP at all**

**Comment by kataras** [comment]
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris **IS NOT NET/HTTP at all** ,you even don't star Iris it aah..

**Comment by kataras** [comment]
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris **IS NOT NET/HTTP at all** ,you even don't star Iris it aah..

You message has been removed: propaganda.

**Comment by kataras** [comment]
- You don't using Iris man, **This is not Iris**,maybe **this error occurs to other frameworks** like this you are contribute to.
- Iris **DOES NOT HAVE response.WriteHeader** because
- Iris **IS NOT NET/HTTP at all** 
- Your name is known to me,

You message has been removed: propaganda.

**Comment by kataras** [comment]
- You don't using Iris man.
-  **This is not Iris**,maybe **this error occurs to other frameworks** like this you are contribute to.
- Iris **DOES NOT HAVE response.WriteHeader** because
- Iris **IS NOT NET/HTTP at all** 
- Your name is known to me,

You message has been removed: propaganda.

**Comment by tuxlinuxien** [comment]
@kataras please remove the sand that you have into your vagina.

and please put all your message next time.

```
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris IS NOT NET/HTTP at all ,you even don't star Iris it aah..
```

because not staring your project doesn't make me a legit user?

**Comment by tuxlinuxien** [comment]
@kataras 

```
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris IS NOT NET/HTTP at all ,you even don't star Iris it aah..
```

please keep track of all your messages. you need to assume what you say.

since when do i need to star a project to use it?

**Comment by tuxlinuxien** [comment]
@kataras 

```
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris IS NOT NET/HTTP at all ,you even don't star Iris it aah..
```

please keep track of all your messages. you need to assume what you say.

since when do i need to star a project to use it?

**Comment by tuxlinuxien** [comment]
@kataras 

```
@tuxlinuxien You don't using Iris man, Iris DOES NOT HAVE response.WriteHeader, lol, Iris IS NOT NET/HTTP at all ,you even don't star Iris it aah..
```

please keep track of all your messages. you need to assume what you say.

since when do i need to star a project to use it?

**Comment by kataras** [comment]
@tuxlinuxien I'm sorry to act angry, I just upset so much that you didn't know the difference between net/http and iris.

Your comments, 
really hurt me, I felt they were rude. I act so fast, I even didn't view all of your message's content after some words, so I locked the conversation and remove all of your messages very fast

**Comment by tuxlinuxien** [comment]
@kataras when I have opened the issue I haven't said anything bad about you or your project. I had just copy the first example that you give on your homepage and then run *siege* on it, no more no less.

I really don't even know why you edit comments that I have written.  It's simply not fair. I could have put a screenshot of our conversation but you don't even worth that i spend time working with you. not even star your project.

However, I am glad to see that you have so many star but at least, don't fuck up your reputation with a bad, immature and irresponsible attitude.

Feel free to delete my comment.

BTW, what's the deal with the issue #148?

**Comment by tuxlinuxien** [comment]
So now I just ask you one single thing:

take this code:

```go
# $GOPATH/src/test/main.go
package main

import (
    "github.com/kataras/iris"
)

func main() {

    // render JSON
    iris.Get("/", func(c *iris.Context) {
        c.Text("ok")
    })
    iris.Listen(":8080")
}
```

then run:

```
$> siege -v http://localhost:8080/
```

personally, siege give me this output:

```
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       0 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       4 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /
^C
Lifting the server siege...      done.

Transactions:		         296 hits
Availability:		      100.00 %
Elapsed time:		       11.60 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	       25.52 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.03
Successful transactions:         296
Failed transactions:	           0
Longest transaction:	        0.01
Shortest transaction:	        0.00
 
FILE: /var/log/siege.log
You can disable this annoying message by editing
the .siegerc file in your home directory; change
the directive 'show-logfile' to false.
```

but my go program gives me this:

```
yoann:/go/src/datapro(masterv2.25 ✗)% go run main.go 
2016/06/26 01:38:47 http: multiple response.WriteHeader calls
2016/06/26 01:38:51 http: multiple response.WriteHeader calls
2016/06/26 01:38:54 http: multiple response.WriteHeader calls
2016/06/26 01:38:57 http: multiple response.WriteHeader calls
```

there is no propaganda in it. I was just asking if it's normal?

**Comment by kataras** [comment]
Can you try re-produce that using ` c.Write("ok")`  instead of ` c.Text("ok")` and tell me the results?

**Comment by tuxlinuxien** [comment]
no problems now. Seem that your Text method is the problem.

**Comment by kataras** [comment]
` Text(status int, v string)` 

you wrote: ` .Text("ok")`  . What is your Iris version? ( type ` iris -v` on your command -line)

**Comment by kataras** [comment]
@tuxlinuxien   I think that the problem is that you are using a version which doesn't exists now ( the version 1 net/http iris), please confirm that

**Comment by tuxlinuxien** [comment]
@kataras 

```
yoann:/save/work/go/src/datapro(masterv2.25 ✗)% iris -v
zsh: command not found: iris
```

I have followed the instruction in your README.md

```
$ go get -u github.com/kataras/iris/iris
```

Maybe your doc is not up-to-date.

**Comment by kataras** [comment]
Docs, books and examples are always updated, before the iris commit. You just didnt read the [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md). 

How to upgrade: remove your $GOPATH/src/github.com/kataras folder, open your command-line and run go get -u github.com/kataras/iris/iris.

**Comment by kataras** [comment]
@tuxlinuxien Could you confirm that?

**Comment by kataras** [comment]
@tuxlinuxien You're welcome, and sorry again !
