### ISSUE TITLE
some question about iris.Context

### ISSUE THREAD

**Issue by gkdgo** [kataras/iris#2088]
1. dose ever request use different iris.Context are they isolate from each other?

Actually , I want to keep a global userInfo in one request lifecycle, and I do't want one request access any other request's iris.Context , is it safe to store userInfo in iris.Context ?

**Comment by kataras** [comment]
Hello @gkdgo,

Yes, it is safe to store it on the `iris.Context`, its store is new on each request. That's why we have the `ctx.Values().Set(key, value)` and `ctx.Values().Get(key)` methods.
