### ISSUE TITLE
OnErrorCode seems to not be working on master

### ISSUE THREAD

**Issue by zaibon** [kataras/iris#2091]
**Describe the bug**
I'm trying to define a a error handler using the `OnErrorCode` method but the handler is never used.

**To Reproduce**
Test code:
```go
package main

import (
	"fmt"
	"net/http"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.Default()

	errHandler := func(ctx iris.Context) {
		err := ctx.GetErr()
		if err != nil {
			ctx.JSON(iris.Map{
				"error": err.Error(),
			})
		}
	}
	app.OnErrorCode(http.StatusInternalServerError, errHandler)

	app.Get("/error", func(ctx iris.Context) {
		ctx.StopWithError(iris.StatusInternalServerError, fmt.Errorf("An error occurred"))
	})

	app.Run(iris.Addr(":8080"))
}
```
Do a request to `localhost:8080/error` and observe the response.

**Expected behavior**
The response should a be JSON formatted error looking like
```json
{"error": "An error occurred"}
```
Instead we have just a simple string: `An error occurred`

**Desktop (please complete the following information):**
 - OS: Archlinux (Linux tesla 5.15.94-1-lts)

**iris.Version**
Tested with both 
- v12.2.0-beta7
- master

**Comment by kataras** [comment]
Hello @zaibon,

If you want to directly write a JSON response on error code use the `StopWithJSON`. If you want to send the error and handle it on the error code handler, you should use the `StopWithPlainError` instead, because the `StopWithError` writes the error's message into plain text format. Example Code:

```go
package main

import (
	"errors"
	"net/http"

	"github.com/kataras/iris/v12"
)

func main() {
	app := iris.Default()

	errHandler := func(ctx iris.Context) {
		err := ctx.GetErr()
		if err != nil {
			ctx.JSON(iris.Map{
				"error": err.Error(),
			})
		}
	}
	app.OnErrorCode(http.StatusInternalServerError, errHandler)

	app.Get("/error", func(ctx iris.Context) {
		ctx.StopWithPlainError(iris.StatusInternalServerError, errors.New("an error occurred"))
	})

	app.Run(iris.Addr(":8080"))
}

```
