### ISSUE TITLE
[BUG] Markdown doesn't support single dash table define

### ISSUE THREAD

**Issue by zyxkad** [kataras/iris#2098]
**Describe the bug**
When I render user inputs that used single dash table, it didn't render correctly.

**To Reproduce**
```go
data := `
| a | b | c |
| - | - | - |
| 1 | 2 | 3 |
`
app := iris.Default()
app.Get("/", func(ctx iris.Context){
    ctx.Markdown(([]byte)(data))
})
// serve app
```
Access the entrypoint, it will return
```html
<p>| a | b | c |
| - | - | - |
| 1 | 2 | 3 |</p>
```

**Expected behavior**

when I access the point, it should returned a table

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A

**iris.Version**
- v12@master

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**
I opened an issue at <https://github.com/russross/blackfriday/issues/707>, but I think this project was died, can you use another markdown library that support markdown table?

Don't ask me use three dashes input, the input is users, not mine

**Comment by kataras** [comment]
Hello @zyxkad, I've just pushed a commit on `master` branch (`go get github.com/kataras/iris/v12@master` && `go mod tidy --compat=1.20`) which replaced the markdown library. I've tested your example, it parsed correctly.

**Comment by zyxkad** [comment]
Thank you :)
