### ISSUE TITLE
[FEATURE REQUEST] Circuit Breaker (Handling overload)

### ISSUE THREAD

**Issue by trungdlp-wolffun** [kataras/iris#2106]
**Is your feature request related to a problem? Please describe.**
Handling system overload like call failure call third-party API, DB overload, stop domino effect system fail.

**Describe the solution you'd like**
Some patterns can handle, I prefer Circuit Breaker
<img width="824" alt="image" src="https://user-images.githubusercontent.com/93299415/226235992-bd2ffa72-c332-4ef7-8f8f-5a26807df42d.png">
See some impl at: https://github.com/zeromicro/go-zero/tree/master/core/breaker

**Comment by trungdlp-wolffun** [comment]
@kataras https://sre.google/sre-book/handling-overload/

**Comment by kataras** [comment]
Hello @trungdlp-wolffun this is a job for a proxy/load balancer. I don't think smart to put such implementations and features inside Iris itself. On production Iris runs behind load balancers (AWS, nginx, caddy, ...).

**Comment by kataras** [comment]
Hello @trungdlp-wolffun this is a job for a proxy/load balancer. I don't think it's a good idea to start such implementations and features inside Iris itself. On production Iris runs behind load balancers (AWS, nginx, caddy, ...).

**Comment by trungdlp-wolffun** [comment]
Excuse me, @kataras, but if I were to call a third-party service and it were to fail, why should I wait for another request that would likely return the same failed result?

**Comment by kataras** [comment]
Hello @trungdlp-wolffun, so you are speaking about client-side. Can you give us an example that you can't handle with the current implementations (e.g. `https://github.com/sony/gobreaker`, `https://github.com/cep21/circuit` and e.t.c.)  so we can provide a better solution?

**Comment by trungdlp-wolffun** [comment]
Nice, thanks for your information
