### ISSUE TITLE
[QUESTION] Suggest database library for MongDB

### ISSUE THREAD

**Issue by trungdlp-wolffun** [kataras/iris#2108]
@kataras Do you known any library for MongoDB ??

Easy way to use, syntax like ORM

Some library I know:

- https://github.com/mongodb/mongo-go-driver
- https://github.com/Kamva/mgm
- https://github.com/zeromicro/go-zero/tree/master/core/stores/monc

**Comment by trungdlp-wolffun** [comment]
Another library I found: https://github.com/qiniu/qmgo

**Comment by kataras** [comment]
If someone searching for a postgres library instead, I've just publish my new project: https://github.com/kataras/pg.
