### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by dlsniper** [kataras/iris#211]
Hi, 

I would like to use this in a high workload scenario but the lack of tests is frightening. 
Any ETA when industry established best practices would be followed and tests will be added? 

Thank you.

**Comment by kataras** [comment]
Hi @dlsniper , 

> I would like to use this in a high workload scenario but the lack of tests is frightening

Don't be frighten, fasthttp ( which iris is built on top of ) has covered 100% by tests. Many users using Iris every day (certain for big apps, this is the reason this framework built for) by many users, their bug reports and feature requests are helping Iris to be a stable version, when a stable version releases.
Also don't forget that we are one of the most active go project exists in github today, we answer fast, we fix fast, we talk every day.

If you think that you need unit tests for each case, you're free to write some tests and pr them into the [tests](https://github.com/kataras/iris/tree/master/tests) folder, this is a community-driven project.

Thanks for your interest, don't hesitate to ask any question or talk with us via [gitter](https://gitter.im/kataras/iris)

**Comment by kataras** [comment]
Hi @dlsniper , 

Don't be frighten, fasthttp ( which iris is built on top of ) has been covered 100% by tests. Many users using Iris every day (certain for big apps, this is the reason this framework built for) by many users, their bug reports and feature requests are helping to Iris' stability, every time a stable version published.

Also don't forget that Iris is one of the most active go project exists in github today, we answer fast, we fix fast, we talk every day.

If you think that you need unit tests for each case, you're free to write some tests and pr them into the [tests](https://github.com/kataras/iris/tree/master/tests) folder, this is a community-driven project.

Thanks for your interest, don't hesitate to ask any more questions or talk with us via [gitter](https://gitter.im/kataras/iris)

**Comment by kataras** [comment]
Hi @dlsniper , 

Don't be frighten, fasthttp ( which iris is built on top of ) has been covered 100% by tests. Many users using Iris every day (certain for big apps, this is the reason this framework built for) by many users, their bug reports and feature requests are helping to Iris' stability, every time a stable version published.

Also don't forget that Iris is one of the most active go project exists in github today, we answer fast, we fix fast, we talk every day.

If you think that you need unit tests for each case, you're free to write some tests and pr them into the [tests](https://github.com/kataras/iris/tree/master/tests) folder, this is a community-driven project.

Thanks for your interest, don't hesitate to ask if you have any more questions or talk with us via [gitter](https://gitter.im/kataras/iris)

**Comment by kataras** [comment]
:Closing this, answered.

**Comment by dlsniper** [comment]
I'm sorry, the fact that it's based on fasthttp means nothing. After all, everything that's running in a server is based on the OS, should we stop testing?

> Also don't forget that Iris is one of the most active go project exists in github today

Based on your saying.

> , we answer fast, we fix fast, we talk every day.

You clearly haven't fixed but did talked

>  Many users using Iris every day (certain for big apps, this is the reason this framework built for) by many users, their bug reports and feature requests are helping to Iris' stability, every time a stable version published.

Yet you are listed as the sole contributor to this project.

The fact that you labeled this as a question and then quickly closed it just proves that I can't trust this project with no workload.

I'm sorry but I'll seek another project that I can use.

**Comment by kataras** [comment]
There is no ETA for tests yet, but I'll start writing some soon

**Comment by dlsniper** [comment]
I'm sorry, I'm not interested in this project anymore after the clear violations of copyrights, editing / removing my comments and locking the thread. I don't believe this to be a mature leadership for the project. The simple fact that you don't have the guts to leave your previous comment here proves it. Thank you for your efforts but I will recommend everyone to stay away from this as well. Have a nice day.

**Comment by avsej** [comment]
![57848d08c69b3122c52682887558c0f1](https://cloud.githubusercontent.com/assets/7280/16358508/1721eea2-3b1d-11e6-85db-de08de8c35d2.jpg)

**Comment by kataras** [comment]
@dlsniper  

> The simple fact that you don't have the guts to leave your previous comment here proves it

Hoewever I had 'the guts' to apologize.

> I will recommend everyone to stay away from this as well.  

It's your decision, I 'm sure you will think it again, anyway good luck
