### ISSUE TITLE
[QUESTION] Handling path parameters with MVC

### ISSUE THREAD

**Issue by pcfreak30** [kataras/iris#2129]
This question seems simple, but I cannot find docs or an example.

I have an API of `/api/v1/files/download`

I want to know in an MVC controller method, `func (f *FilesService) GetDownload(cidString string) {` how I can trigger the creation of a route `/api/v1/files/download/{cid:string}`

You can see the project code at https://git.lumeweb.com/LumeWeb/portal, though not everything may be pushed.

Thanks!

**Comment by kataras** [comment]
Hello @pcfreak30, you have two ways:

1. Rename the method to `GetDownloadBy(cidString string)` as shown in [this example](https://github.com/kataras/iris/blob/master/_examples/mvc/login/web/controllers/users_controller.go#L51) - the `By` keyword says the framework that the input arguments may be path parameters (in your case, the `cidString`).
2. Customize the Controller's routes using `BeforeActivation & AfterActivation`, as shown in the [example](https://github.com/kataras/iris/blob/master/_examples/mvc/basic/main.go#L91):

```go
func (_ *FilesService) AfterActivation(_ mvc.AfterActivation) {}

func (f *FilesService) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle(iris.MethodGet, "/api/v1/files/download{cid:string}", "GetDownload")
}
```

**Comment by pcfreak30** [comment]
Kudos!
