### ISSUE TITLE
How could I get iris context from grpc context

### ISSUE THREAD

**Issue by windysl06** [kataras/iris#2131]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/blob/master/_examples/mvc/grpc-compatible/main.go>.

I have a question, how do I get the iris context inside the grpc service?

type myController struct {
	Ctx iris.Context
	SingletonDependency service
}

When I use the http client, ctx is working, while using the grpc client it fails.

grpc client: Ctx is nil

@kataras Looking forward to your reply. Thanks a lot

**Comment by kataras** [comment]
Hello @windysl06,

This is normal. When you are using a gRPC client, it wraps a `net.Listener` with gRPC protocol <- this is NOT HTTP, so you don't have access to the http `iris.Context`. If you want to have access on http protocol features then use HTTP Client instead, we can't do anything more here :/

**Comment by windysl06** [comment]
@kataras got it, thanks.
But I have a doubt, I use the logging middleware, with grpc client request can still get http corresponding data, I have no way to get the corresponding request structure data content too?

app.Use(xmiddleware.LoggerMid("log/request.log"))

// SayHello implements helloworld.GreeterServer.
func (c *OpServer) SayHello(ctx context.Context, in *api.HelloRequest) (*api.HelloReply, error) {
	fmt.Println(in.GetName())
	return &api.HelloReply{Message: "Hello " + in.GetName()}, nil
}
func LoggerMid(path string) icontext.Handler {
    return func(c iris.Context) {
            //how could I get the data: "in *api.HelloRequest", is there  any suggestion? or is there any way to trans any data from SayHello to here? such as "c.Values().Get("DATA")"
            c.Request().URL.Path  //is working
           c.Request().Method //is working
    }
}

**Comment by kataras** [comment]
You are welcome @windysl06,

No, because your gRPC client does not communicate with the Iris HTTP Server at all, so how can it knows to log the request?

**Comment by windysl06** [comment]
ok, thanks, I got it. I used a different way to record logs. 
`grpc.UnaryInterceptor(interceptor.UnaryServerInterceptor(logger))`
