### ISSUE TITLE
[Feat] Support for streaming media files in Iris

### ISSUE THREAD

**Issue by sayem314** [kataras/iris#2139]
#### Issue Description:

I would like to request support for streaming media files in Iris. Currently, I'm working on a project where I need to stream video and audio files to clients. However, I couldn't find a straightforward way to achieve this using the existing features of Iris.

#### Expected Behavior:

I expect that Iris should provide a built-in mechanism or guidelines for streaming media files, allowing developers to efficiently handle media streaming scenarios. This would greatly benefit applications that involve media playback, video streaming platforms, or file-sharing platforms.

#### Additional Information:

Streaming media files is a common requirement in web applications. It would be helpful if the Iris framework could provide a clear and efficient way to achieve media streaming, including support for range requests and handling of partial content.

**Comment by kataras** [comment]
Hello @sayem314,

What way do you prefer with the standard library `net/http` or any other framework? I can easily show you the "Iris way" of your preferred implementation because Iris is based on the standard library.

**Comment by sayem314** [comment]
This works with `net/http`. Note that I have generated code with ChatGPT and slightly modified it so I haven't fully verified if range parsing works properly but on opening stream on the browser it works fine.

```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
)

func main() {
	http.HandleFunc("/stream", streamHandler)
	http.ListenAndServe(":8080", nil)
}

func streamHandler(w http.ResponseWriter, r *http.Request) {
	// Open the MP4 file
	filePath := "path/to/your/file.mp4"
	file, err := os.Open(filePath)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer file.Close()

	// Retrieve the file's size
	fileStat, err := file.Stat()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	fileSize := fileStat.Size()

	// Parse the range header
	rangeHeader := r.Header.Get("Range")
	var start, end int64
	if rangeHeader != "" {
		rangeParts := strings.Split(rangeHeader, "=")
		if len(rangeParts) != 2 || rangeParts[0] != "bytes" {
			http.Error(w, "Invalid range header", http.StatusRequestedRangeNotSatisfiable)
			return
		}

		rangeValues := strings.Split(rangeParts[1], "-")
		if len(rangeValues) != 2 {
			http.Error(w, "Invalid range header", http.StatusRequestedRangeNotSatisfiable)
			return
		}

		start, err = strconv.ParseInt(rangeValues[0], 10, 64)
		if err != nil {
			http.Error(w, "Invalid range header", http.StatusRequestedRangeNotSatisfiable)
			return
		}

		if rangeValues[1] == "" {
			end = fileSize - 1
		} else {
			end, err = strconv.ParseInt(rangeValues[1], 10, 64)
			if err != nil {
				http.Error(w, "Invalid range header", http.StatusRequestedRangeNotSatisfiable)
				return
			}
		}

		if start >= fileSize || end >= fileSize || start > end {
			http.Error(w, "Invalid range header", http.StatusRequestedRangeNotSatisfiable)
			return
		}

		w.Header().Set("Content-Type", "video/mp4")
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, fileSize))
		w.Header().Set("Content-Length", fmt.Sprintf("%d", end-start+1))
		w.WriteHeader(http.StatusPartialContent)

		// Seek to the start position in the file
		_, err = file.Seek(start, 0)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	} else {
		// No range requested, serve the entire file
		w.Header().Set("Content-Type", "video/mp4")
		w.Header().Set("Content-Length", fmt.Sprintf("%d", fileSize))
		w.WriteHeader(http.StatusOK)
	}

	// Stream the file contents to the response writer
	_, err = io.Copy(w, file)
	if err != nil {
		// Handle any error that occurs during streaming
		// For example, if the client cancels the request
		fmt.Println("Error streaming:", err)
		return
	}
}
```

**Comment by sayem314** [comment]
After conducting extensive research on the Iris documentation, I discovered the `ServeContent` method, which appears to be suitable for streaming in this code. Please provide feedback on whether this implementation is correct or if any further improvements should be made to enhance the streaming functionality.

```go
package movies

import (
	"net/http"
	"os"

	"github.com/kataras/iris/v12"
	"github.com/lunarr-app/lunarr-go/internal/util"
)

func MovieStreamHandlerTest(ctx iris.Context) {
	filePath := "/path/to/file"

	file, err := os.Open(filePath)
	if err != nil {
		util.Logger.Error().Err(err).Msg("Failed to open file")
		ctx.StopWithJSON(http.StatusInternalServerError, iris.Map{
			"status":  http.StatusText(http.StatusInternalServerError),
			"message": "Failed to open file",
		})
		return
	}
	defer file.Close()

	fileStat, err := file.Stat()
	if err != nil {
		util.Logger.Error().Err(err).Msg("Failed to get file stats")
		ctx.StopWithJSON(http.StatusInternalServerError, iris.Map{
			"status":  http.StatusText(http.StatusInternalServerError),
			"message": "Failed to get file stats",
		})
		return
	}

	ctx.Header("transferMode.dlna.org", "Streaming")
	ctx.Header("contentFeatures.dlna.org", "DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000")
	ctx.ServeContent(file, fileStat.Name(), fileStat.ModTime())
}
```

**Comment by sayem314** [comment]
After conducting extensive research on the Iris documentation, I discovered the ServeContent method, which appears to be suitable for streaming in this code. Please provide feedback on whether this implementation is correct or if any further improvements should be made to enhance the streaming functionality.

https://github.com/lunarr-app/lunarr-go/blob/8d94c983170c3c35eb55f2d137dcdbbc00d411b7/internal/handlers/movies/stream.go#L32-L58

**Comment by kataras** [comment]
Nice @sayem314, yes `ctx.ServeContent/ServeContentWithRate` is a richer implementation of the standard `http.ServeContent` which uses some of the code you posted above for the standard library example. So yes, `ctx.ServeContent` is that you need. Don't hesitate to ask more questions If it doesn't work as you expected.

**Comment by sayem314** [comment]
Thanks for the clarification! I appreciate your help! Closing the issue now.
