### ISSUE TITLE
[FEATURE REQUEST] We Need Template Engine Like EJS

### ISSUE THREAD

**Issue by segun-flexible** [kataras/iris#2140]
Am coming from a background of JavaScript/Node where we use ejs, for use to be able to write js code inside our rendering file

Please we need something similar for iris, we want to be able to use syntax similar to ejs iris

**Comment by kataras** [comment]
Hello @segun-flexible,

Did that not help?: https://github.com/lmmfy/goejs

**Comment by kataras** [comment]
I don't know why you just down-voted without a comment @segun-flexible but if you want ejs-like template engines inside Iris, beside the link I gave you above, you have already the Jet engine, example at: https://github.com/kataras/iris/tree/master/_examples/view/template_jet_0
