### ISSUE TITLE
{{ yield }} in template reports an error

### ISSUE THREAD

**Issue by Transmigration-zhou** [kataras/iris#2141]
In v12.2.0, the error is reported in the part of layout.html containing {{ yield }}.
`wrong number of args for yield: want 1 got 0`

But In v12.1.8, no error is reported.

if I code in  v12.2.0, what should I do？

I‘m a  newbie and this is my first time using iris. Can you help me? 

This is part of my code.
```golang
template := iris.HTML("./backend/web/views", ".html").Layout("shared/layout.html").Reload(true)
app.RegisterView(template)
```

```golang
func (p *ProductController) GetAll() mvc.View {
	....
	return mvc.View{
		Name: ...,
		Data: iris.Map{
			...
		},
	}
}
```

```html
<div class="be-content">
    {{ yield }}
</div>
````

**Comment by kataras** [comment]
Hello @Transmigration-zhou,

The `yield` template function requires the template data as its argument as described at: https://github.com/kataras/iris/blob/master/HISTORY.md#fixes-and-improvements. If you want to contain all data into the `yield` you can just replace all your `{{ yield }}` with `{{ yield . }}`.

**Comment by Transmigration-zhou** [comment]
> Hello @Transmigration-zhou,
> 
> The `yield` template function requires the template data as its argument as described at: https://github.com/kataras/iris/blob/master/HISTORY.md#fixes-and-improvements. If you want to contain all data into the `yield` you can just replace all your `{{ yield }}` with `{{ yield . }}`.

thx!!
