### ISSUE TITLE
Iris run fails when not running from ./

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#215]
```
$ iris run app/web/main.go

[IRIS]  Error:
Failed to run the app/web/main iris program. Trace: fork/exec ./app/web/main: no such file or directory
```

**Comment by kataras** [comment]
Will fix it on the next commit, I must complete some other changes to, some things will change again ( middleware and plugins move outside of this repo, in order to be easy to mantain and users contribute )

**Comment by kataras** [comment]
Thanks, Will fix it on the next commit, I must complete some other changes too, some things will change again ( middleware and plugins move outside of this repo, in order to be easy to mantain and users contribute )

**Comment by ryanbyyc** [comment]
STOP BREAKING THE API! 

-.-

;)

**Comment by kataras** [comment]
No the API will no change, just some imports path only from /kataras/iris to iris-contrib, I duscuss this change with the community in the chat, the morning and they all agree don't worry it will be painless :P

**Comment by kataras** [comment]
@ryanbyyc  iris run main.go works, why the something/other/doesntworks ? this is relative path also, hmm

**Comment by kataras** [comment]
@ryanbyyc  Fixed, will commit the changes when I finish other changes also

**Comment by kataras** [comment]
@ryanbyyc  Fixed on rc.3 read the [HISTORY.md](https://github.com/kataras/iris/tree/master/HISTORY.md) for changes, book and examples are also updated
