### ISSUE TITLE
[BUG] jwt/refresh-token examples not work

### ISSUE THREAD

**Issue by warjiang** [kataras/iris#2160]
**Describe the bug**
When use refresh-token example, i found that the IDE report mismatch type error like following 
![image](https://github.com/kataras/iris/assets/6478745/297a6f7e-6360-4cb6-8bee-d90693693e0e)
It's seem that the conflicts between `github.com/kataras/iris/v12/middleware/jwt` and `github.com/kataras/jwt`.

**To Reproduce**
1. just copy jwt/refresh-token examples 
2. go run it

**Desktop (please complete the following information):**
 - OS: MacOS

**iris.Version**
- Iris:  12.2.0

**Comment by kataras** [comment]
@warjiang, this is not a fix. The `Expected` type is declared as an alias in the `middleware/jwt` package. You don't have to import the `github.com/kataras/jwt` package here.

**Comment by kataras** [comment]
What version of `Go` do you have installed? Iris plays at 1.19+

**Comment by warjiang** [comment]
> What version of `Go` do you have installed? Iris plays at 1.19+

golang 1.20, #2161 closed, same problem
