### ISSUE TITLE
Fix or disable colors in iris run

### ISSUE THREAD

**Issue by peterbe** [kataras/iris#217]
The screenshots shows how it's a mess. I get this when I run `iris run main.go` (which, by the way, is amazing!)
<img width="1118" alt="screen shot 2016-06-23 at 3 56 23 pm" src="https://cloud.githubusercontent.com/assets/26739/16318042/3770db50-395b-11e6-8e03-bf55d7c867e8.png">

I suspect the simplest thing would be to disable all the background colors and just use green, red and standard text.

**Comment by kataras** [comment]
I done that already but I have to complete some other changes and I will commit, thanks you by the way!!

**Comment by kataras** [comment]
@peterbe , fixed on rc.3 thanks you for the report!!

**Comment by kataras** [comment]
@peterbe Fixed on rc.3 read the [HISTORY.md](https://github.com/kataras/iris/tree/master/HISTORY.md) for changes, book and examples are also updated.

Thanks for the report!!
