### ISSUE TITLE
Match Routing Not Found

### ISSUE THREAD

**Issue by xgpc** [kataras/iris#2174]
**Describe the bug**
The route app.Any("/*", func) returns "Not Found".

**To Reproduce**
go.mod: github.com/kataras/iris/v12 v12.2.0 main.go:
```golang
func Demo() {
    app := iris.Default()

    app.Any("/", func(context iris.Context) {
        context.WriteString(context.Path())
    })

    app.Any("/*", func(context iris.Context) {
        context.WriteString(context.Path())
    })

    app.Run(iris.Addr(":8080"))
}

```
**Expected behavior**
- e.g curl http://localhost:8080/123/123 => /123/123
- e.g curl http://localhost:8080/aaa => /aaa

**Screenshots**
Incorrect
![image](https://github.com/kataras/iris/assets/24631625/a2d5d15b-6e7f-4373-9b3e-f0ac33069c0d)

Correct
![image](https://github.com/kataras/iris/assets/24631625/53dd39d3-aa70-48ae-b850-7cc4259744eb)

**iris.Version**
- e.g. v12.2.0 or master

**Comment by kataras** [comment]
Hello @xgpc, there is no `/*` pattern matching.  Try reading the [_examples/routing](_examples/routing):

```go
func Demo() {
	app := iris.Default() // or iris.New()

	app.Any("/", func(context iris.Context) {
		context.WriteString(context.Path())
	})

	app.Any("/{p:path}", func(context iris.Context) {
		context.WriteString(context.Path())
	})

	app.Run(iris.Addr(":8080")) // or just app.Listen(":8080")
}
```

**Comment by xgpc** [comment]
@kataras  Sorry, I didn't read it carefully. Thank you

**Comment by kataras** [comment]
You are welcome @xgpc, have fun!
