### ISSUE TITLE
why irisv12 need to download iris v0.0.2

### ISSUE THREAD

**Issue by FocusHuang** [kataras/iris#2189]
D:\Workspace\GO\src\gitee.com\oncity051\sailor> go get github.com/kataras/iris/v12@latest
go: downloading github.com/kataras/iris v0.0.2                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
go: downloading github.com/kataras/iris/v12 v12.2.1
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading github.com/kataras/golog v0.1.9
go: downloading github.com/tdewolff/minify/v2 v2.12.7
go: downloading github.com/gomarkdown/markdown v0.0.0-20230716120725-531d2d74bc12
go: downloading github.com/microcosm-cc/bluemonday v1.0.24
go: downloading golang.org/x/crypto v0.12.0
go: downloading github.com/kataras/pio v0.0.12
go: downloading github.com/tdewolff/parse/v2 v2.6.6
go: warning: github.com/microcosm-cc/bluemonday@v1.0.24: retracted by module author: Retract older versions as only latest is to be depended upon
go: to switch to the latest unretracted version, run:   
        go get github.com/microcosm-cc/bluemonday@latest
go: added github.com/BurntSushi/toml v1.3.2
go: added github.com/CloudyKit/fastprinter v0.0.0-20200109182630-33d98a066a53
go: added github.com/CloudyKit/jet/v6 v6.2.0
go: added github.com/Joker/jade v1.1.3
go: added github.com/Shopify/goreferrer v0.0.0-20220729165902-8cddb4f5de06   
go: added github.com/andybalholm/brotli v1.0.5
go: added github.com/aymerick/douceur v0.2.0
go: added github.com/fatih/structs v1.1.0
go: added github.com/flosch/pongo2/v4 v4.0.2
go: added github.com/golang/snappy v0.0.4
go: added github.com/gomarkdown/markdown v0.0.0-20230716120725-531d2d74bc12
go: added github.com/gorilla/css v1.0.0
go: added github.com/iris-contrib/schema v0.0.6
go: added github.com/josharian/intern v1.0.0
go: added github.com/kataras/blocks v0.0.7
go: added github.com/kataras/golog v0.1.9
go: added github.com/kataras/iris/v12 v12.2.1
go: added github.com/kataras/pio v0.0.12
go: added github.com/kataras/sitemap v0.0.6
go: added github.com/kataras/tunnel v0.0.4
go: added github.com/klauspost/compress v1.16.7
go: added github.com/mailgun/raymond/v2 v2.0.48
go: added github.com/mailru/easyjson v0.7.7
go: added github.com/microcosm-cc/bluemonday v1.0.24
go: added github.com/russross/blackfriday/v2 v2.1.0
go: added github.com/schollz/closestmatch v2.1.0+incompatible
go: added github.com/sirupsen/logrus v1.8.1
go: added github.com/tdewolff/minify/v2 v2.12.7
go: added github.com/tdewolff/parse/v2 v2.6.6
go: added github.com/valyala/bytebufferpool v1.0.0
go: added github.com/vmihailenco/msgpack/v5 v5.3.5
go: added github.com/vmihailenco/tagparser/v2 v2.0.0
go: added github.com/yosssi/ace v0.0.5
go: added golang.org/x/time v0.3.0
go: added gopkg.in/ini.v1 v1.67.0
go: added gopkg.in/yaml.v3 v3.0.1

**Comment by kataras** [comment]
Hello @FocusHuang, I don't see it downloads `0.0.2` from my machine, maybe you need `go mod clean` or change the `GOPROXY` env variable to "direct" or try `go get github.com/kataras/iris/v12@master` ? Here is the full output:

```sh
PS C:\Users\kataras\Desktop\issue_2189> go mod init testapp
go: creating new go.mod: module testapp
PS C:\Users\kataras\Desktop\issue_2189> go get -v github.com/kataras/iris/v12@latest
get "golang.org/x/net": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net?go-get=1
get "golang.org/x/crypto": found meta tag vcs.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto?go-get=1
get "golang.org/x/sys": found meta tag vcs.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys?go-get=1
get "golang.org/x/text": found meta tag vcs.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text?go-get=1
get "golang.org/x/time": found meta tag vcs.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at //golang.org/x/time?go-get=1
get "google.golang.org/protobuf": found meta tag vcs.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at //google.golang.org/protobuf?go-get=1
get "gopkg.in/ini.v1": found meta tag vcs.metaImport{Prefix:"gopkg.in/ini.v1", VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at //gopkg.in/ini.v1?go-get=1
get "gopkg.in/yaml.v3": found meta tag vcs.metaImport{Prefix:"gopkg.in/yaml.v3", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v3"} at //gopkg.in/yaml.v3?go-get=1
go: warning: github.com/microcosm-cc/bluemonday@v1.0.24: retracted by module author: Retract older versions as only latest is to be depended upon
go: to switch to the latest unretracted version, run:
        go get github.com/microcosm-cc/bluemonday@latest
go: added github.com/BurntSushi/toml v1.3.2
go: added github.com/CloudyKit/fastprinter v0.0.0-20200109182630-33d98a066a53
go: added github.com/CloudyKit/jet/v6 v6.2.0
go: added github.com/Joker/jade v1.1.3
go: added github.com/Shopify/goreferrer v0.0.0-20220729165902-8cddb4f5de06
go: added github.com/andybalholm/brotli v1.0.5
go: added github.com/aymerick/douceur v0.2.0
go: added github.com/fatih/structs v1.1.0
go: added github.com/flosch/pongo2/v4 v4.0.2
go: added github.com/golang/snappy v0.0.4
go: added github.com/gomarkdown/markdown v0.0.0-20230716120725-531d2d74bc12
go: added github.com/google/uuid v1.3.0
go: added github.com/gorilla/css v1.0.0
go: added github.com/iris-contrib/schema v0.0.6
go: added github.com/josharian/intern v1.0.0
go: added github.com/kataras/blocks v0.0.7
go: added github.com/kataras/golog v0.1.9
go: added github.com/kataras/iris/v12 v12.2.1
go: added github.com/kataras/pio v0.0.12
go: added github.com/kataras/sitemap v0.0.6
go: added github.com/kataras/tunnel v0.0.4
go: added github.com/klauspost/compress v1.16.7
go: added github.com/mailgun/raymond/v2 v2.0.48
go: added github.com/mailru/easyjson v0.7.7
go: added github.com/microcosm-cc/bluemonday v1.0.24
go: added github.com/russross/blackfriday/v2 v2.1.0
go: added github.com/schollz/closestmatch v2.1.0+incompatible
go: added github.com/sirupsen/logrus v1.8.1
go: added github.com/tdewolff/minify/v2 v2.12.7
go: added github.com/tdewolff/parse/v2 v2.6.6
go: added github.com/valyala/bytebufferpool v1.0.0
go: added github.com/vmihailenco/msgpack/v5 v5.3.5
go: added github.com/vmihailenco/tagparser/v2 v2.0.0
go: added github.com/yosssi/ace v0.0.5
go: added golang.org/x/crypto v0.11.0
go: added golang.org/x/net v0.12.0
go: added golang.org/x/sys v0.10.0
go: added golang.org/x/text v0.11.0
go: added golang.org/x/time v0.3.0
go: added google.golang.org/protobuf v1.31.0
go: added gopkg.in/ini.v1 v1.67.0
go: added gopkg.in/yaml.v3 v3.0.1
PS C:\Users\kataras\Desktop\issue_2189>
```
