### ISSUE TITLE
Let’s Encrypt integration 

### ISSUE THREAD

**Issue by kataras** [kataras/iris#220]
Add automated  SSL/TLS when `.ListenTLS` using https://letsencrypt.org/docs/client-options/ .
##

**Comment by kataras** [comment]
Implemented, example [here](https://github.com/iris-contrib/examples/blob/master/letsencrypt/main.go).

This is tested by me, but if any of you has any issues with this please post it here.

**Comment by azastrael** [comment]
You wrote in `iris.go` that for production we should use `$app.Serve(iris.LETSENCRYPTPROD("mydomain.com"))` instead of `$app.ListenLETSENCRYPT("127.0.0.1:443")` but `iris.LETENCRYPTPROD` is undefined.

Also does iris support listening for two domains name using the same port ?

**Comment by kataras** [comment]
Hello @azastrael ,

> $app.Serve(iris.LETSENCRYPTPROD("mydomain.com")) instead of $app.ListenLETSENCRYPT("127.0.0.1:443") but iris.LETSENCRYPTPROD is undefined.

Yes, `iris.LETSENCRYPTPROD` is using the `golang/x/` repository's acme implementation which is the recommended, it's on the `master` repository .

> Also does iris support listening for two domains name using the same port ?

Iris supports unlimited domains and subdomains with different ports by-default but if you're hosting your app behind a `unix` I think you can take look at the [reuseport](https://github.com/valyala/fasthttp/tree/master/reuseport)

Thanks,
kataras
