### ISSUE TITLE
Passing variables to the layout template

### ISSUE THREAD

**Issue by olek-p** [kataras/iris#221]
Hi, I'm fairly new to Go, so please forgive me if this is a dummy question.

I've defined a custom `iris.Config.Render.Template.Layout`, and within it I would like to use variables - e.g. an indicator whether there is a user logged in (and display their username) or not (and display the login form), based on information stored in `Session()`. How can I do that?

I thought of using a custom function and passing it inside a `template.FuncMap` to `iris.Config.Render.Template.HTMLTemplate.Funcs`, but then hit a wall: how do I access the `*iris.Context` from it?

Is the `FuncMap` the way to go, or is there a better way to achieve my goal?

**Comment by kataras** [comment]
@olek-p Hello & Welcome then!

> how do I access the *iris.Context from it?

You cannot pass `*iris.Context`  to these functions.

> Is the FuncMap the way to go, or is there a better way to achieve my goal?

You could just pass a struct or a map via ` context.Render("thetemplate.html",myStruct{Logged:false})`  this struct will be available from your layout and from your template.

**Comment by olek-p** [comment]
@kataras thanks for the quick reply!

I know I could pass that to `context.Render()`, but that means I would have to pass the same information to ALL the calls to `context.Render()`, right? That sounds like a lot of duplicated code. That's why I was wondering if there is a better way, i.e. to pass the session information in one place.

**Comment by kataras** [comment]
I don't know what you meant with dublicated code, this is up to you, I suggest you to make a struct which can have child structs and use that, you can come to [chat](https://gitter.im/kataras/iris) to discuss that with community, maybe they can give you a better solution to this

**Comment by olek-p** [comment]
OK, I get it now, thank you! :)

**Comment by kataras** [comment]
You're welcome, we are here if you have any questions or issues!! You will love go!
