### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by billizzard** [kataras/iris#2214]
I have main layout

```

func initApp() *iris.Application {
	app := iris.New()
	tmpl := iris.HTML("./src/public/html", ".html")
	tmpl.Layout("layout/main.html")
	app.RegisterView(tmpl)

	return app
}

```

stucture public/html folder

```

-layout
--main.html
-files
--list.html
-menu
--menu.html

```

layout/main.html has this code (this is main layout)

```

<html>
<head>
    {{ block "title" .}}<title>Default</title>{{end}}
</head>
<body>
</body>
</html>

```

There are also pages that are rendered like this (routes different)
`ctx.View("files/list.html");`
`ctx.View("menu/menu.html");`

files/list.html content
```

{{ define "title"}}
    <title>222</title>
{{ end }}

```

menu/menu.html content
```

{{ define "title"}}
    <title>111</title>
{{ end }}

```

no matter which page of these two you go to, it’s always 111 in title, but expect 222 in list.html page

**Comment by kataras** [comment]
Hi @billizzard, actually this is not a bug, this is how Go HTML templates work. If you parse more than one template with the same {{ define }}, the one overrides the other, you can read it at: https://stackoverflow.com/questions/66613213/rendering-golang-template-defining-the-same-block-multiple-times. For that reason we have the custom `{{ yield . }}`, however if I modify the code of the HTML view engine to use a set of templates and register a new template set for each of the layouts for each one of the template files it can work.

**Comment by kataras** [comment]
Hi @billizzard, actually this is not a bug, this is how Go HTML templates work. If you parse more than one template with the same {{ define }}, the one overrides the other, you can read it at: https://stackoverflow.com/questions/66613213/rendering-golang-template-defining-the-same-block-multiple-times. For that reason we have two features: the custom `{{ yield . }}`, however in your case that's not what you need, the 2nd one is the `Blocks` template engine which uses similar solution (map/set of templates) and supports multiple {{define}} tags.

**Comment by billizzard** [comment]
Thank you, sorry for bothering you

**Comment by kataras** [comment]
Hello @billizzard, it's ok, indeed to made me to make `blocks` even more modular. I uploaded an example for you at: https://github.com/kataras/iris/tree/main/_examples/view/template_blocks_2. Hope that you enjoy the framework!

**Comment by kataras** [comment]
Hello @billizzard, it's ok, indeed you "forced" me to make `blocks` even more modular. I uploaded an example for you at: https://github.com/kataras/iris/tree/main/_examples/view/template_blocks_2. Hope that you enjoy the framework!
