### ISSUE TITLE
[BUG] Process hang

### ISSUE THREAD

**Issue by secsys-go** [kataras/iris#2216]
**Describe the bug**
We used the Fuzz engine to modify some Test(TestUseRouterParentDisallow) data, and then we encountered process hang. We hope to get the help of the developer to confirm whether it is a real bug.

**To Reproduce**
```go
app := iris.New()
app.PartyFunc("{0h0", func(p iris.Party) {
	p.UseRouter(func(ctx iris.Context) {
		ctx.WriteString("0")
		ctx.Next()
	})

	p.Get("(o}\x10\x00}", func(ctx iris.Context) {
		ctx.WriteString("0")
	})
})
```

**Expected behavior**
Process hang should not happen.

**Desktop (please complete the following information):**
 - OS: Windows 10

**iris.Version**
- commit [28f49cd](https://github.com/kataras/iris/commit/28f49cd50d5d9f1364745d9fe8873e3b22c9e177)

**Comment by fubuki8087** [comment]
I try to fix this bug. I debugged it and found the root cause of this bug was derived from `readIdentifierFuncArgument` function in `macro/interpreter/lexer/lexer.go` where reading input will not end because of lacking end check of string. I will submit PR later.
