### ISSUE TITLE
Liquid Template Engine

### ISSUE THREAD

**Issue by necrogami** [kataras/iris#222]
Is it possible to add support to iris for Liquid Templates 

https://github.com/karlseguin/liquid

**Comment by kataras** [comment]
It is possible, if you use this engine, no problem, expect that on V4

**Comment by kataras** [comment]
With Iris version 4.0.0-alpha.4 you can create & use your template engine with ease, look [this repo](https://github.com/iris-contrib/template) for examples on how to do it!!

I'm marking this as third-party job, it's your time  folks, community !
