### ISSUE TITLE
Cannot contact via twitter

### ISSUE THREAD

**Issue by suisfa** [kataras/iris#223]
Hi,

I cannot contact you via twitter which is opened to the public on [http://iris-go.com/](http://iris-go.com/).
Why are you a protected account?

**Comment by kataras** [comment]
Hello @suisfa my account is opened again, I was sleeping ( yes I disable tweets sharing when I'm sleeping). Now my turn

Your account has created today and star only Iris, thanks you, are you new github user or dublicated account?
