### ISSUE TITLE
readJSON - decode time string with desired layout

### ISSUE THREAD

**Issue by jesusgalvan** [kataras/iris#228]
I am passing a string in the format `"Thu, 13 Jun 1996 19:00:00 GMT"` to my struct.  And currently I am passing it in a different format than it is expecting.

```go
type Post struct {
        TheDate time.Time
}
//...
//...
func (c Post) Post() {
        p := Post{}
        // payload
        // { TheDate: "Thu, 13 Jun 1996 19:00:00 GMT" }
        err := c.ReadJSON(&p)
}



```
Error:
`Error: While trying to read JSON from the request body. Trace parsing time ""Thu, 13 Jun 1996 19:00:00 GMT"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "Thu, 13 Jun 1996 19:00:00 GMT"" as "2006"`

Am I able to set the time format for the date parse'ing?

**Comment by yakleg** [comment]
Hi! m.b. it be helpful for you:
https://godoc.org/time#Time.UnmarshalJSON

or it:
http://stackoverflow.com/questions/20475321/override-the-layout-used-by-json-marshal-to-format-time-time
