### ISSUE TITLE
flag.Parse()

### ISSUE THREAD

**Issue by Dal-Papa** [kataras/iris#229]
Hey,

You added a `flag.Parse()` which makes any flag not working in your binary as long as you include Iris. 

**Version of Iris** : tag: v3.0.0-rc.3
**Reproducible steps** : Include Iris and use flag.Parse() with a flag of yours
**Code that shows the issue** : 
```
var configPath = flag.String("config", "config.json", "path to your config file")
...
flag.Parse()
```
**Errors in the terminal** : 
```
Usage of <binary-name>:
  -s	Disable banner via command line tool, overrides the logger's config field
```

**Comment by kataras** [comment]
@Dal-Papa  

>  You added a flag.Parse() which makes any flag not working in your binary as long as you include Iris
Is used inside /kataras/iris/iris/run.go and is working, what do you mean?

Although I agree with you about breaking changes ( no more from final v3 and after) I have to tell you that you should read the [https://github.com/kataras/iris/blob/master/CONTRIBUTING.md](https://github.com/kataras/iris/blob/master/CONTRIBUTING.md) before posting an issue.

**Comment by Dal-Papa** [comment]
Sorry about the Guidelines, modified it.

**Comment by kataras** [comment]
I understand you about changes, this will stop after v3 stable released, you have absolute right.

**Comment by kataras** [comment]
@Dal-Papa Fixed.

**Comment by kataras** [comment]
@Dal-Papa Fixed, thanks you very much about your pattience!

**Comment by kataras** [comment]
@Dal-Papa Fixed and thanks you very much about your pattience!

**Comment by kataras** [comment]
@Dal-Papa Fixed and thanks you very much for your pattience!
