### ISSUE TITLE
What makes iris significantly faster?

### ISSUE THREAD

**Issue by juan-orca** [kataras/iris#23]
I am looking at this image

http://kataras.github.io/iris/assets/benchmarks_all.png

What is it that makes Iris so fast as opposed to these other libraries?

**Comment by kataras** [comment]
Iris is the only go web framework as far as I know which uses thread-safe cache for routing, and group of subdomains for faster serving, and it's light mini framework no heavy like other huge web frameworks. I hope I solve your puzzle. Don't believe don't trust anyone just run your own benchmarks and compare all frameworks with Iris, iris is x3 faster and on some of them x50 faster (on my hardware), I will upload detailed results sometime when I have more time for this type of things. Thanks for the issue!

**Comment by Atsman** [comment]
Hello,

Why you didn't contribute to some other library like gin to make it faster, instead of creating new one?

**Comment by kataras** [comment]
@Atsman I want to use a mini web framework for myself, I couldn't find any other web frameworks that fills my needs and I am not sure if other teams ( like gin ) wanted to re-write the whole of their code to my needs, this was the first 
motivation to write the Iris. Iris first of all is written for my clients and client's servers. When I saw/understood how much faster is than other web frameworks I realized that I MUST open source it
