### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by kron4eg** [kataras/iris#230]
Please read the [CONTRIBUTION](https://github.com/kataras/iris/glob/master/CONTRIBUTION.md) before posting any issue, in Iris the post issues are only for bugs, feature requests, you can chat for other things, please set things organised.

**Comment by kataras** [comment]
Please read the [CONTRIBUTION](https://github.com/kataras/iris/glob/master/CONTRIBUTION.md) before posting any issue, in Iris the post issues are only for bugs, feature requests, you can chat for other things, please set things organised.

**Comment by kataras** [comment]
@kron4eg we are working to add licenses for all third-party libraries, I though  [THIRDPARTY.md](https://github.com/kataras/iris/blob/master/THIRDPARTY.md) was enough but it is not.

**Comment by rileytg** [comment]
why in THIRTPARTY.md do these links:
```
goo used inside iris command line tool
cli used inside iris command line tool
```
go to kataras/goo and kataras/cli instead of https://github.com/gernest/goo and https://github.com/urfave/cli ?

**Comment by kataras** [comment]
Hello @rileytg there are no broken links in THIRDPARTY.md

cli used inside iris command line tool is the https://github.com/kataras/cli

the goo is one of my new projects for run and watch a go program, it will be ready on a few minutes, link: https://github.com/kataras/goo

Note: gernest/goo ? and I though I found a unique name... 

However thanks for your effort!

[Dublicated: https://github.com/kataras/iris/issues/233]

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, hope now I can continue developer the code I 'm boring of these things  I have no idea how it works, hopefuly now we are ok!! thanks for all!!

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, hope now I can continue develop the code I 'm boring of these things  I have no idea how it works, hopefuly now we are ok!! thanks for all!!

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, https://github.com/kataras/iris/commit/57ba8e89b5c48537683f66bf24fdf820dc99919f  hope now I can continue develop the code I 'm boring of these things  I have no idea how it works, hopefuly now we are ok!! thanks for all!!

**Comment by kataras** [comment]
Done https://github.com/kataras/iris/commit/cd71b945b733be6638b963cb81344b56bdfc14c9, https://github.com/kataras/iris/commit/57ba8e89b5c48537683f66bf24fdf820dc99919f. Hopefuly now we are ok in order continue develop the project as I used to. Thanks for all!!
