### ISSUE TITLE
Session not persisting on subdomains

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#231]
The session set in the 'domain.local' is not available in the 'sub.domain.local'. 
It should be setup to '.domain.local' to persist even on all subdomains.

Can you make this fix please or, introduce a new optional parameter so there will be the possibility for everyone to setup as they want.

**Comment by es-lab** [comment]
@kataras can you please take a look at this issue, I know you are working hard on a lot of features, but I'm actually stuck with my project, and I'd like to complete the sessions setup and go forward.
Thanks.

**Comment by kataras** [comment]
@es-lab I'm trying but fasthttp doesn't supports wildcard cookie domain to be added, I could make cookies foreach subdomaind and pass them to the client but this is not the best solution, we are waiting for [that](https://github.com/valyala/fasthttp/issues/125) now.

**Comment by kataras** [comment]
@es-lab I'm trying but fasthttp doesn't supports wildcard cookie domain to be added yet, I could make cookies foreach subdomain and pass them to the client but this is not the best solution, we are waiting for [that](https://github.com/valyala/fasthttp/issues/125) now.

**Comment by kataras** [comment]
@es-lab I'm trying but fasthttp doesn't supports wildcard cookie domain to be added yet, I could make cookies foreach subdomain and pass them to the client but this is not the best solution, we are waiting for [that](https://github.com/valyala/fasthttp/issues/125) now.

Reference: https://github.com/valyala/fasthttp/issues/125

**Comment by kataras** [comment]
You have absolute right, as [RFC2109](https://www.ietf.org/rfc/rfc2109.txt) says.

Fixed, upgrade Iris with ` go get -u github.com/kataras/iris/iris` .

Just to know: If you ever want to disable this behavior pass: ` iris.Config.Sessions.DisableSubdomainPersistance = true ` 

By default (1-level) subdomain persistance is enabled, as RFC2109 commands: 
```

* A Set-Cookie from request-host y.x.foo.com for Domain=.foo.com
     would be rejected, because H is y.x and contains a dot.

* A Set-Cookie from request-host x.foo.com for Domain=.foo.com would
     be accepted.

```

Thanks for the bug report!!
