### ISSUE TITLE
broken links in THIRDPARTY.md

### ISSUE THREAD

**Issue by rileytg** [kataras/iris#233]
why in THIRTPARTY.md do these links:
```
goo used inside iris command line tool
cli used inside iris command line tool
```
go to kataras/goo and kataras/cli instead of https://github.com/gernest/goo and https://github.com/urfave/cli ?

**Comment by kataras** [comment]
cli used inside iris command line tool is the https://github.com/kataras/cli

the goo is one of my new projects for run and watch a go program, it will be ready on a few minutes, link: https://github.com/kataras/goo

Note: gernest/goo ? and I though I found a unique name...
