### ISSUE TITLE
Listen on two ports

### ISSUE THREAD

**Issue by DSpeichert** [kataras/iris#235]
I want my application to work on HTTPs on port 443.
Sometimes, I'd also want it to be available on HTTP (80). However, it's not possible to run `iris.Listen...` twice for the same iris instance.

A common use would be to redirect all HTTP->HTTPS. I think that the `secure` middleware has such a switch but it cannot work unless there is a listener on port 80 as well.

**Comment by kataras** [comment]
so you want two servers with the same station ( routes and configuration) the one `http` port 80 and the other `https` port 443 or you want to have one empty station with server `http` port 80 which will redirect to https://samelocation ?

**Comment by DSpeichert** [comment]
The first one (same "station" on ports 80 and 443). I tried that but running `iris.Listen()` and then again `iris.ListenTLS()` (in goroutines) makes the second one hang. It would be great if documentation could cover how to do that.

The second one (a dumb HTTP listener that redirects to HTTPS) is, as you say, simple to do by creating another instance of iris.

I'd be more interested in the third variant - having one iris instance redirect all HTTP to HTTPS with a simple switch or anything that would save the need for creating a new instance of iris just for that purpose.

**Comment by kataras** [comment]
I made something different, the ability to start servers in the same iris station, I will commit on a little and tell me if that suits you

**Comment by DSpeichert** [comment]
Okay, that seems to cover part 1 of the use case.
How about a shortcut for HTTP (80) -> HTTPS (443) redirect?

**Comment by kataras** [comment]
Done, example [here](https://github.com/iris-contrib/examples/tree/master/multiserver_listening2).

```go

package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.SecondaryListen(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}
```

I hope we are ok with this feature request, it is useful, thanks you very much!!

**Comment by DSpeichert** [comment]
Perfect, that was quick!
I appreciate it!

**Comment by kataras** [comment]
I'm too!!  however can you tell me if you have any reason don't star iris yet? :P

**Comment by DSpeichert** [comment]
Oops, you caught me. Fixed now ;)
