### ISSUE TITLE
Handlebars templating engine

### ISSUE THREAD

**Issue by DJviolin** [kataras/iris#239]
Is it possible to add this engine? It is really useful in Node/express apps:

https://github.com/aymerick/raymond

**Comment by kataras** [comment]
@DJviolin With pleasure!

**Comment by kataras** [comment]
@DJviolin  Done :) 

Book and Examples updated also,
basic handlebars example can be found here: https://github.com/iris-contrib/examples/tree/master/templates_handlebars

Upgrade with `go get -u github.com/kataras/iris/iris` and have fan :)

**Comment by kataras** [comment]
@DJviolin  Done :) 

Book and Examples updated also,
basic handlebars example can be found here: https://github.com/iris-contrib/examples/tree/master/templates_handlebars

Upgrade with `go get -u github.com/kataras/iris/iris` and have fun :)

**Comment by DJviolin** [comment]
JESUS!!!! It was so fast! :o Thank You very much!!!

**Comment by DJviolin** [comment]
I've getting the following error message when I try to run my app:

```shell
Lanti@LANTI-PC C:\www\node\lantosistvan\go\app
$ main.exe
Server is running at: 8080
panic: Parse error on line 5:
Expecting ID, got: 'Sep{"."}'

goroutine 1 [running]:
panic(0x8ee380, 0xc042259eb0)
        C:/go/src/runtime/panic.go:500 +0x1af
github.com/kataras/iris/render/template.New(0x5, 0x984188, 0x5, 0xc042259a80, 0x1, 0x1, 0x98813e, 0x9, 0x9838be, 0x5, ...)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/render/template/template.go:110 +0x46a
github.com/kataras/iris.(*Framework).prepareTemplates(0xc04200d320)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/initiatory.go:149 +0x242
github.com/kataras/iris.(*Framework).initialize(0xc04200d320)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/initiatory.go:118 +0x199
github.com/kataras/iris.(*Framework).openServer(0xc04200d320, 0x982098, 0x1)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/initiatory.go:156 +0x54
github.com/kataras/iris.(*Framework).ListenWithErr(0xc04200d320, 0x9834fe, 0x5, 0x0, 0x992801)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/iris.go:198 +0x63
github.com/kataras/iris.(*Framework).Listen(0xc04200d320, 0x9834fe, 0x5)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/iris.go:208 +0x46
github.com/kataras/iris.Listen(0x9834fe, 0x5)
        C:/www/node/lantosistvan/go/vendor/src/github.com/kataras/iris/iris.go:186 +0x48
main.main()
        C:/www/node/lantosistvan/go/src/github.com/DJviolin/lantosistvan/main.go:69 +0x6f
```

The actual go app can be found here: https://github.com/DJviolin/lantosistvan/blob/6f6ba05d27cee4e68ab70154153270031733c72b/go/src/github.com/DJviolin/lantosistvan/main.go

**Comment by kataras** [comment]
@DJviolin You use HandleBars not html/template why you use `.` here: https://github.com/DJviolin/lantosistvan/blob/6f6ba05d27cee4e68ab70154153270031733c72b/go/app/views/page1.html#L5 ?

**Comment by DJviolin** [comment]
Sorry, it's just left in from the last example implementation ofhtmlTemplate. Now I uncommented and works without problem. Thank You! :)

**Comment by kataras** [comment]
You're welcome!!

**Comment by DJviolin** [comment]
One more question: Is there a way to use partials in the template files like `{{< partials/page1_partial1.hbs}}`? Partials worked with htmlTemplate but not with this Handlebars package:

```shell
panic: Parse error on line 7:
Lexer error
Token: Error{"Unexpected character in expression: '<'"}
```

Defining the main layout works without problem though.

**Comment by kataras** [comment]
@DJviolin You mean https://github.com/aymerick/raymond#dynamic-partials, I already asnwered you that currently this is not supported automatically by Iris but you can still use that and make partials manually, however I can implement a Layout system for handlebars like other template engimes, but a bit latter, I will notify you :)

**Comment by kataras** [comment]
@DJviolin Done, for a complete example click [here](https://github.com/iris-contrib/examples/tree/master/templates_handlebars/templates). The [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md)  also updated. Thanks !!

**Comment by kataras** [comment]
``@DJviolin Done, for a complete example click [here](https://github.com/iris-contrib/examples/tree/master/templates_handlebars). The [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md)  also updated. Thanks !!

**Comment by kataras** [comment]
@DJviolin Done, for a complete example click [here](https://github.com/iris-contrib/examples/tree/master/templates_handlebars). The [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md)  also updated. Thanks !!

**Comment by DJviolin** [comment]
OMG, Thank You!!!! :)

**Comment by DJviolin** [comment]
One little correction for: https://github.com/iris-contrib/examples/blob/master/templates_handlebars/main.go

`my` routes should be:

```go
// set a layout for a party, .Layout should be BEFORE any Get or other Handle party's method
my := iris.Party("/my").Layout("layouts/mylayout.hbs") //{
my.Get("/", func(ctx *iris.Context) {
  ctx.MustRender("home.hbs", map[string]interface{}{
    "Name": "Iris",
    "Type": "Web",
    "Path": "/my/",
  })
})
my.Get("/other", func(ctx *iris.Context) {
  ctx.MustRender("home.hbs", map[string]interface{}{
    "Name": "Iris",
    "Type": "Web",
    "Path": "/my/other",
  })
})
```

Instead of:

```go
// set a layout for a party, .Layout should be BEFORE any Get or other Handle party's method
my := iris.Party("/my").Layout("layouts/mylayout.html")
{
  my.Get("/", func(ctx *iris.Context) {
    ctx.MustRender("home.html", map[string]interface{}{"Name": "Iris", "Type": "Web", "Path": "/my/"})
  })
  my.Get("/other", func(ctx *iris.Context) {
    ctx.MustRender("home.html", map[string]interface{}{"Name": "Iris", "Type": "Web", "Path": "/my/other"})
  })
}
```

**Comment by kataras** [comment]
@DJviolin Man I loveed your feature request but you have to READ the book, you can change the extension with ` iris.Config.Render.Template.Extensions = []string{".hbs"}` after you define the template engine, and you are ready to go :)

**Comment by DJviolin** [comment]
No, the error is at `{}`. You shouldn't use this double quote. The two `my.Get` child element should be at the same level like `my :=`.

I already modified `iris.Config.Render.Template.Extensions = []string{".hbs"}`, this one works without problem. That's why is in my code.

**Comment by kataras** [comment]
@DJviolin Why I shouldn't use this double quote?
this: 
```go
// set a layout for a party, .Layout should be BEFORE any Get or other Handle party's method
my := iris.Party("/my").Layout("layouts/mylayout.html")
{
  my.Get("/", func(ctx *iris.Context) {
    ctx.MustRender("home.html", map[string]interface{}{"Name": "Iris", "Type": "Web", "Path": "/my/"})
  })
  my.Get("/other", func(ctx *iris.Context) {
    ctx.MustRender("home.html", map[string]interface{}{"Name": "Iris", "Type": "Web", "Path": "/my/other"})
  })
}

```
and this:
```go
// set a layout for a party, .Layout should be BEFORE
// any Get or other Handle party's method
my := iris.Party("/my").Layout("layouts/mylayout.hbs")
my.Get("/", func(ctx *iris.Context) {
  ctx.MustRender("home.hbs", map[string]interface{}{
    "Name": "Iris",
    "Type": "Web",
    "Path": "/my/",
  })
})
my.Get("/other", func(ctx *iris.Context) {
  ctx.MustRender("home.hbs", map[string]interface{}{
    "Name": "Iris",
    "Type": "Web",
    "Path": "/my/other",
  })
})
```
are the same, what's the issue I didn't understand, please explain to me

**Comment by DJviolin** [comment]
Go 1.7 Beta 2 compiler complained about this at building.

**Comment by kataras** [comment]
Really? I use 1.6.1, what's the error trace it shows?

**Comment by DJviolin** [comment]
Sorry, I written like `my := iris.Party("/my").Layout("layouts/mylayout.hbs") {`, so the `{` at the same line with `my :=`, than throwing this compiler error:

```shell
$ wgo build -o app/main.exe github.com/DJviolin/lantosistvan
# github.com/DJviolin/lantosistvan
src\github.com\DJviolin\lantosistvan\main.go:130: syntax error: unexpected { at end of statement
src\github.com\DJviolin\lantosistvan\main.go:137: syntax error: unexpected ), expecting }
src\github.com\DJviolin\lantosistvan\main.go:138: syntax error: non-declaration statement outside function body
src\github.com\DJviolin\lantosistvan\main.go:139: syntax error: unexpected ctx, expecting (
src\github.com\DJviolin\lantosistvan\main.go:144: syntax error: non-declaration statement outside function body
```

**Comment by kataras** [comment]
Yes the same error will be at 1.6.1, you should move the `{` at the next line not at the same, so no issue ouf... :P
