### ISSUE TITLE
[question] go binary not running without iris/go installed?

### ISSUE THREAD

**Issue by hrwebasst** [kataras/iris#240]
I'm a newbie to go but `iris run` builds a binary and I expected that to run on my laptop without go or iris. I used an alpine linux to do both a `go build` and `iris run` (I expect both to build a binary) then copy that binary to a linux box (same architecture as alpine) and get:

![screenshot from 2016-06-28 21-15-47](https://cloud.githubusercontent.com/assets/9060082/16440306/84561bd8-3d75-11e6-8532-46e790dba3c8.png)

Am I crazy or just missing something?

**Comment by tuxlinuxien** [comment]
they explain it there https://github.com/gliderlabs/docker-alpine/issues/78

**Comment by kataras** [comment]
@hrwebasst This is not an Iris problem, please read the blogs that @tuxlinuxien  sent to you, I'm label this as question and close, thanks you !
