### ISSUE TITLE
body size exceeds the given limit

### ISSUE THREAD

**Issue by hbfs** [kataras/iris#241]
Hi, I'm testing large file uploads, in this case images and running into the following error:

```
MaxRequestBodySize:  -1

(no such table: users)
[2016-06-29 04:01:05]
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 3.0.0-rc.4

Wed, 29 Jun 2016 04:01:05 GMT: Running at 127.0.0.1:8000

2016/06/29 04:01:35 error when serving connection "127.0.0.1:8000"<->"127.0.0.1:64506": body size exceeds the given limit
2016/06/29 04:01:35 error when serving connection "127.0.0.1:8000"<->"127.0.0.1:64509": body size exceeds the given limit
```

In "net/http" I call `r.ParseMultipartForm(<memory limit in bytes>)` to handle large uploads. While fasthttp has `MultipartForm()`, it doesn't have the `ParseMultipartForm` where you can specify the memory to use for the upload.

**Comment by hbfs** [comment]
It seems this was just changed ~14 hours ago due to mitigate DDoS with large body size, https://github.com/valyala/fasthttp/commit/e4db3cb5600317e91d93e07036e4d20903c8fa17

Specifying the MaxRequestBodySize in the config fixes this issue.

``
import "github.com/kataras/iris/config"

irisConfig := config.Iris{MaxRequestBodySize: <size in bytes>}
www := iris.New(irisConfig)

**Comment by kataras** [comment]
Yes, we had already that setted by the Iris :)

**Comment by hbfs** [comment]
Hey cool framework but based on the documentation and the code https://github.com/kataras/iris/blob/master/config/iris.go#L59 is no longer applicable. I think fasthttp overrides the -1 to 4MB from the commit above

**Comment by kataras** [comment]
hmm yes you have right I didn't see the length I assumed it was -1 again, I will update that right now
