### ISSUE TITLE
please add reference to *fasthttp.Cookie in iris for ease of use

### ISSUE THREAD

**Issue by SaulDoesCode** [kataras/iris#242]
It would be very nice if iris could contain the ``*fasthttp.Cookie`` type the same way it makes ``map[string]interface{}`` easy to use with ``iris.Map``.
Perhaps add it as ``iris.Cookie``.
thanks

**Comment by kataras** [comment]
Hello @SaulDoesCode , you have an option to add a cookie (key,value) very easy and an option to add cookie with ` *fastttp.Cookie`. I think it is unnecessary to add an ` iris.Cookie ` as ` *fasthttp.Cookie`, thanks for the idea but it won't happen, you can easly create your variable type if you want 

```go
// SetCookieKV adds a cookie, receives just a key(string) and a value(string)
SetCookieKV(key, value string) 
// SetCookie adds a cookie
SetCookie(cookie *fasthttp.Cookie)
```

**Comment by kataras** [comment]
Hello @SaulDoesCode , you have an option to add a cookie (key,value) very easy and an option to add cookie with ` *fastttp.Cookie`. I think it is unnecessary to add an ` iris.Cookie ` as ` *fasthttp.Cookie`, thanks for the idea but it won't happen, you can easly create your variable type if you want 

**Context**
```go
// SetCookieKV adds a cookie, receives just a key(string) and a value(string)
SetCookieKV(key, value string) 
// SetCookie adds a cookie
SetCookie(cookie *fasthttp.Cookie)
```

**Comment by SaulDoesCode** [comment]
How does one add an Expires value to the cookie using ``context.SetCookieKV(key, val)``?
