### ISSUE TITLE
Problems with ctx.SessionDestroy()

### ISSUE THREAD

**Issue by DSpeichert** [kataras/iris#244]
I suspect there is a glitch somewhere with killing a session.
I use the redis session manage but the same seems to happen with "memory" session backend.

I have some data in the session and then a visitor goes to a URL with the following HandlerFunc:
```go
func signout(ctx *iris.Context) {
	ctx.SessionDestroy()
	ctx.Redirect("/", 303)
	fmt.Println("Deleting session...")
}
```

Yet, on subsequent requests, all the session data is still there - therefore, noone can log out.

Any tips how I can debug this?

Note: I just updated everything (`go get -u all`) before reporting this, so I'm using the latest version.

**Comment by kataras** [comment]
**Fixed**, it was a small problem with the name of the session ( at the last version I decided to encode/decode the key of the session id also), just upgrade with ` go get -u github.com/kataras/iris/iris` 

> Any tips how I can debug this?

I think the small examples is exactly this, just tests for you and for me, you can go there and test it: 
https://github.com/iris-contrib/examples/blob/master/sessions/main.go

**Comment by DSpeichert** [comment]
I am not sure this is fixed yet. I've upgraded iris but still see the same issue.

**Comment by kataras** [comment]
I tested it several times on many browsers, try to clear your browser's history and tell me again, what domain do you use for your ` iris.Listen`?

**Comment by DSpeichert** [comment]
I invoke listen like this:
```go
go iris.ListenTLS("0.0.0.0:443", c.String("ssl-cert"), c.String("ssl-key"))
```

i've tested again clearing redis (FLUSHALL) and browser cookie and it's still like that.

**Comment by kataras** [comment]
@DSpeichert Man the whole sessions are not working with TLS not only destroy, I will fix it right now, please wait

**Comment by kataras** [comment]
Fixed, upgrade again with ` go get -u github.com/kataras/iris/iris` please and verify it

**Comment by DSpeichert** [comment]
It still doesn't work.. can't delete sessions.

**Comment by kataras** [comment]
What do you mean, I tested it ListenTLS `0.0.0.0:443` like you  , can you share your code with me?

**Comment by DSpeichert** [comment]
I've shared the private repo with the code with you. It doesn't have the ClientID/Secret for OAuth2 so you can't test that part out yourself but feel free to check out the live version (you'll find the link in the repo) and feel free to commit any changes you'd like me to test.

**Comment by kataras** [comment]
@DSpeichert Ok, I did some internal tests seems. that for some reason I didnt make the Provider's Destroy to remove all values on Destroy, so the Clear -> Destroy worked but the ->Destory didn't clear the values but deletes the session from client and server, now is **fixed(hopefuly)**, please verify it and tell me if that works!

**Comment by DSpeichert** [comment]
Yup, most likely working fully now :)

**Comment by kataras** [comment]
Finally ! :)
