### ISSUE TITLE
No LICENSE in github.com/iris-contrib/schema

### ISSUE THREAD

**Issue by deadline527** [kataras/iris#2472]
Unable to use github.com/iris-contrib/schema due to missing LICENSE within the repository.

Since iris/v12 depends on this import, I can no longer use iris due to sonarqube scanning for valid licenses.

Was hoping a license could be added as a file even though its included in the README.md since tools scanning for this will flag it as a potential problem and not allow the package.

**Comment by kataras** [comment]
Hello, you don't need to use this. A new faster library is coming which takes advantage of the generics feature. However, if you need this package as standalone, please refer to tbe README and use the original project instead.
