### ISSUE TITLE
Go get problems with submodule mustache

### ISSUE THREAD

**Issue by mehlert** [kataras/iris#249]
Hello,

Seeing this when I run `go get -u github.com/kataras/iris/iris`

This only happening with this github.com project. Using `go get` with other projects is working fine.

```
# cd /Users/ehlertm/wt/go/src/github.com/aymerick/raymond; git submodule update --init --recursive
Cloning into '/Users/ehlertm/wt/go/src/github.com/aymerick/raymond/mustache'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out

fatal: clone of 'git://github.com/mustache/spec.git' into submodule path '/Users/ehlertm/wt/go/src/github.com/aymerick/raymond/mustache' failed
package github.com/aymerick/raymond: exit status 128
```

**Comment by kataras** [comment]
I install Iris today on a fresh installed machine, please follow these steps if you have any problems:

**method 1**
- Remove the folder $GOPATH/src/github.com/kataras
- Open command line(Shell)
- Write `go get -u github.com/kataras/iris/iris`
- Hit Enter 
- You're ready

**method 2**

- If you still have issue try to manual download the go-colarable package, run: `go get -u -v github.com/mattn/go-colorable` 
- That should give you an error message if your Operating System has errors installing this library, if so write the error trace here, at this post.


Write below which method worked for you, so I can label it as question for other people having the same issue, thanks

**Comment by mehlert** [comment]
Hasn't worked on my laptop.

I have a fresh Ubuntu installed on my desktop. I will try there and report back.

**Comment by kataras** [comment]
The solution I gave you didn't worked? I tested both on windows 7 and ubuntu 16.04

**Comment by mehlert** [comment]
Ahoy!

Reporting back. Install worked on fresh Ubuntu 16.04.

The issue on Mac OSX laptop remains. If I get it fixed, I will report back.

**Comment by bjwschaap** [comment]
Just wanted to let you know that using:
```
git config --global url.https://github.com/.insteadOf git://github.com/ && \
go get -u github.com/kataras/iris/iris
```
solved the issue for me on OSX. Problem actually is my client company firewall not allowing SSH to the outside, so need to let git know to use https i/o git://

**Comment by mehlert** [comment]
Oh nice! Came back to basically say the same thing. 

I realized I had only tried this on corp net. Tried it tethered to my phone and it worked fine.

**Comment by kataras** [comment]
Oh ok thanks! , I have one thing less to worry :P
