### ISSUE TITLE
ctx.GetFlash() documentation

### ISSUE THREAD

**Issue by DSpeichert** [kataras/iris#250]
I think it should be noted that ctx.GetFlash("something") can only be called once.

I used to have the following code, which didn't work properly:
```go
if ctx.GetFlash("Redirect") != "" {
    fmt.Printf("Redirecting to %s\n", ctx.GetFlash("Redirect"))
    ctx.Redirect(ctx.GetFlash("Redirect"), 303)
} else {
	ctx.Redirect("/profile", 303)
}
```

This code works instead:
```go
r := ctx.GetFlash("Redirect")
if r != "" {
	fmt.Printf("Redirecting to %s\n", r)
	ctx.Redirect(r, 303)
} else {
	ctx.Redirect("/profile", 303)
}
```

**Comment by kataras** [comment]
Yes, if you search on google for flash messages, it tells that the information is deleted after the first getter, I though that web developers already know that things, like sessions, websocket and so on, but I will add a more detailed docs on this, the book is located [here](https://github.com/iris-contrib/gitbook) if you feel that you can explain it with better english, than mine, please do it :P

**Comment by DSpeichert** [comment]
My expectation was that the flash message is available throughout the whole "next request". In other words, while serving the subsequent request to setting the flash message, I'd be able to access it freely.

**Comment by kataras** [comment]
Hmm so you recommend, set when request finish and remove when request finish, so `GetFlash` can be called many times into the same request and `SetFlash`'s work will execute after the request finish ?

**Comment by kataras** [comment]
Hmm so you recommend, set when request finish and remove when request finish, so `GetFlash` can be called many times into the same request and `SetFlash`'s work will execute after the request finish ? (I'm also fan of this method, although the community didn't wanted it when I designed the flash messages)

**Comment by DSpeichert** [comment]
Yes, precisely. That's how I believe it works in other web frameworks - flash is for the lifetime of the request.
In iris, it seems like flash message can live for subsequent requests if it hasn't been "read". That's great, but it could be deleted at the end of the request when it is used.

**Comment by kataras** [comment]
Yes I totally Agree with you, so I will change this behavior, update book and examples and after do some tests for iris and we are ready for the final v3

**Comment by kataras** [comment]
@DSpeichert Done :)
