### ISSUE TITLE
Can Iris serve partial of large file?

### ISSUE THREAD

**Issue by TechMaster** [kataras/iris#251]
Hi,

I want to serve a big file by sequentially read part of this file and serve to client. Can you advise me how to do?

Thanks

**Comment by kataras** [comment]
Same way you did before Iris, the only difference is now you will use ` context.Write, context.StreamWriter`. Although for big files I suggest using the ` iris.StaticFS` function which will pre-compress your files and serve them zipped

**Comment by TechMaster** [comment]
Thank Kataras,
I will try your suggestion
