### ISSUE TITLE
HTML engine error?

### ISSUE THREAD

**Issue by BChip** [kataras/iris#253]
```
<!-- ./templates/hi.html -->
<html><head> <title> Hi Iris [THE TITLE] </title> </head>
  <body>
    <h1> Hi {{.Name}}
  </body>
</html>
```
```

// ./main.go
import "github.com/kataras/iris"

func main() {
    iris.Get("/hi", hi)
    iris.Listen(":8080")
}

func hi(ctx *iris.Context){
   ctx.Render("hi.html", struct { Name string }{ Name: "iris" })
}
```

Source: https://kataras.gitbooks.io/iris/content/hi.html

This does not seem to work for me. However, the Django/Pongo based code does work.

Not sure what the issue could be.

**Comment by kataras** [comment]
I just tested it and it works:

` ./main.go` 
` ./templates/hi.html` 

Run with LiteIDE.

Provide me more information in order to help you, please

**Comment by BChip** [comment]
kataras, I got it to work with LiteIDE. For some reason, LiteIDE will put the executable in the same directory as my main.go file. The command line tools do not do this. I always ran the executable through the bin folder. Anyways, thanks for the response and thanks for introducing LiteIDE.

**Comment by kataras** [comment]
You're welcome, yes it does with the correct way :)
