### ISSUE TITLE
How to: Iris inside a Docker container ?

### ISSUE THREAD

**Issue by danielfbm** [kataras/iris#254]
Hi, I am facing an issue while trying to run Iris inside a docker container.

Here is a [repo that reproduces the error](https://github.com/danielfbm/test-iris)

1. Build the docker image locally. e.g. ``docker build -t test-iris .``
2. Run the container exposing 8080: ``docker run -d --name test -p 8080:8080 test-iris``
3. Test on the browser or using ``curl``

I tried to use other solutions like the one [here](https://blog.golang.org/docker) and it works very well. I tried to use CORS and debug to check for CORS related problem but the fact is that the request never gets printed.

Additionally Iris is working inside the container. When I enter the container with ``exec`` I can get the data using ``curl``

I looked for specific instructions regarding docker deployment in book and in the repo but couldn't find anything relevant. 

Am I missing something?

Thanks

BTW: I tried in these two environments:
- Mac OSX 10.11.5 using Docker for Mac (beta)
- Ubuntu 14.04 (EC2) using Docker

**Comment by kataras** [comment]
Hello @danielfbm, 

I know that Iris is running inside docker, and runs very smoothly, I know that because of the community (which send me some benchmarks inside docker), but I never needed/used docker myself. 

The answer is yes, is working very good and fast but I can't help you more, you have to join to our [community chat](https://kataras.rocket.chat/channel/iris), there you will find other people using Iris with docker.

**Comment by danielfbm** [comment]
Hi @kataras, thanks for the reply. I will post a message in the chat with a back link here. Thanks for the fast reply

**Comment by danielfbm** [comment]
Figured out how to solve the issue

By default Iris will bind to ``127.0.0.1`` as I can see in the configuration file [here](https://github.com/kataras/iris/blob/master/config/server.go#L12)

This can be setup using ``iris.Listen`` or derivates. by giving a full IP address:

```go
iris.Listen("0.0.0.0:80")
```

Also [I updated the repo](https://github.com/danielfbm/test-iris/blob/master/test.go#L18) linked for other people that might be interested.

**Comment by danielfbm** [comment]
There is a limitation actually. Binding to 0.0.0.0 will make it impossible to run in development. I generally run all my development inside a docker container so this is not a problem for me, but for other, you might consider to use a **Environment variable** to switch between the IPs

Here is a snippet to make this fast

```go
import (
	"os"
)

func getHostValueOrDefault(key string, defaultVal string) string {
	value := os.Getenv(key)
	if value == "" {
		value = defaultVal
	}
	return value
}
// In your main() function

iris.Listen(getHostValueOrDefault("IP_ADDRESS","")+":80")

```

**Comment by kataras** [comment]
Yes we had like this ( with `PORT` as environment variable)  on before-v3 versions but I didn't find so useful so I removed it. But you can't manually start iris on  `iris.Listen("yourip:PORT") ` via docker ?

**Comment by danielfbm** [comment]
It is a IP binding thing. I am not completely sure why this happens, but it happens like this if you bind to "127.0.0.1". Can't access from the outside of the container. In this case just bind it to ``0.0.0.0``:``$PORT``

**Comment by danielfbm** [comment]
Next I will see If I can setup a [Caddy](https://github.com/mholt/caddy) for a robust deployment with docker and add the link here

**Comment by kataras** [comment]
Ok but I'm telling you again, someone did iris+docker without all these (we wait for answer on the chat), but it's a good idea to search about it, until he/she answers back
