### ISSUE TITLE
Save somewhere the connection to the database

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#257]
The idea is simple.

I have to access 2 databases and to store the connection to them during the request.

Any idea how I would handle that ?

**Comment by cristian-sima** [comment]
With `beego` I would have done like that:

1. create a new controller which exntends the default (in this case it would be `appContext` extends `iris.Context`
2. Create a `map[*gorm.DB]
3. Store each connection

**Comment by cristian-sima** [comment]
I can do this inside each handler, but the idea is that lets say that when you navigate to `users` you need yo be connect as well as when you go to `profiles`

A middleware which can save the connection it would be a perfect option

**Comment by cristian-sima** [comment]
I saw [this solution ](https://github.com/kataras/iris/issues/72) and I can use `c.Set("db1", connection)`, but the downfall of this is that I have to cast every time

**Comment by kataras** [comment]
@cristian-sima Hello and welcome,

 Did you read the Custom Handler on examples and gitbook?

**Comment by cristian-sima** [comment]
Yes. Did I miss something. Let me read it again

**Comment by cristian-sima** [comment]
Yep. I can create a custom handler and add the connection there. That's good, but how about creating 2 handles and share the db connection

**Comment by danielfbm** [comment]
@cristian-sima create a struct to keep the connection and add a pointer to each handler. If they are cascaded you could use a middleware function to work this out for you.

In another point-of-view I would keep connections as short as possible, and avoid to *pass it around* as it could generate some hard-to-track bugs. Instead, I would use a connection-pool and let it handle the connecting. There are lots of options, including some open-source software that can be installed directly in the server/docker to handle it for you. Where I work we use [Pgbouncer](https://pgbouncer.github.io/) for that and it works very well.

**Comment by cristian-sima** [comment]
@kataras I've been working for a 8 months with beego. I've started today playing with *iris* and I am very pleased of what I've found. Good job :)

**Comment by kataras** [comment]
@cristian-sima That really means a lot to me, thanks you very much, hopes you the best experience with Iris, if you have any ideas post an issue as feature request, I couldn't made all that without the community with its suggestions!!
