### ISSUE TITLE
Template files generated URL output IP:PORT

### ISSUE THREAD

**Issue by rayxiaoo** [kataras/iris#258]
Template file `{{url "url-profile" $ user.Username}}` generated URL `ip:port/profile/username`
Are there options control does not generate ip: port

**Comment by kataras** [comment]
Yes, use the {{ path "url-profile" ...}}

**Comment by jonywtf** [comment]
if i replace 'url' to 'path', then i get error
```
MustRender panics for client with IP: 127.0.0.1 On template: index.html.Trace: html/template: "index.html" is an incomplete template
```

newline in the example https://github.com/iris-contrib/examples/blob/f9ba556ffdcf685e6388fa896cdf6ed9d6c3d5d3/plugin_oauth_oauth2/templates/index.html after '{{index' breaks template engine

**Comment by jonywtf** [comment]
oh, need replace to 'urlpath'

**Comment by kataras** [comment]
I gave you the wrong template func it was `urlpath` you have right, I do so many things in the same time and sometimes I'm confused, sorry.
