### ISSUE TITLE
windows iris create project error

### ISSUE THREAD

**Issue by rayxiaoo** [kataras/iris#259]
D:\codes\go\src>iris create project 

|||
Problem while copying the basic package to the D:\codes\go\src. Trace: GetFileAttributesEx C:\Users\username\.iris\iris-command-assets\\basic: The system cannot find the file specified.

**Comment by kataras** [comment]
The ` iris create ...` command downloads the package and after copy the contents to the $GOPATH directory you specify, check your firewall or your internet connection
