### ISSUE TITLE
Using StaticWeb and Party simultaneously

### ISSUE THREAD

**Issue by joeyism** [kataras/iris#260]
I have a problem, where I'm trying to use StaticWeb with the folder "./public" to map to /, such that "./public/index.html" is the default site. However, there is also an API component to this webapp that I'm building, and I'm trying to write that by using Party with "/api". However, I run into the problem where

Error: Router: Path's part: '/api/team/:team' conflicts with wildcard '/*filepath' in the route path: '/api/team/:team' 

I'm guessing this happens because the path /* is already registered by StaticWeb, so Party's "/api" conflicts with that. I'm not quite sure how to solve this to have the same client side code and API on the same port. Can anyone help?

**Comment by kataras** [comment]
You cannot have a `StaticWeb` in the same location with other routes, `StaticWeb` is used only to serve `Static` web site by its `index.html`, this is the meaning of the Static functions.

**Comment by joeyism** [comment]
So if I want to serve up all content in a folder that maps to "/*", and additionally want the api to be mapped at "/api", what should I use?

**Comment by kataras** [comment]
You use other route path for your static content, it is not recommended to have static content in root path (via the Static methods) and at the same time use the same path for dynamic routing
