### ISSUE TITLE
iris create project error 

### ISSUE THREAD

**Issue by sachinbhutani** [kataras/iris#261]
I get the following error when trying to create a basis project using
" iris create -d myproject"

basic package was installed successfully [/Users/s/sites/go/myproject]main.go:4:2: cannot find package "myproject/backend/api" in any of:
	/usr/local/go/src/myproject/backend/api (from $GOROOT)
	/Users/s/sites/go/src/myproject/backend/api (from $GOPATH)
main.go:5:2: cannot find package "myproject/backend/routes" in any of:
	/usr/local/go/src/myproject/backend/routes (from $GOROOT)
	/Users/s/sites/go/src/myproject/backend/routes (from $GOPATH)
 Failed to run the basic package. Trace: fork/exec ./backend: no such file or directory

Iris version :3.0.0-rc.4
OSX 10.11 (El Capitan)
Golang version  1.6

**Comment by kataras** [comment]
@sachinbhutani You have run ` iris create` from a $GOPATH, please read the docs and search about relative post issues carefully before posting a new one
