### ISSUE TITLE
React/VueJS integration example

### ISSUE THREAD

**Issue by sachinbhutani** [kataras/iris#262]
Something I really likes about Iris is the detailed explanation in the book and examples, which I could not find in most of the other go-frameworks. 
being a novice to go, iris seems to be easy for me to learn. 

Is it possible to add an example to integrate with reactjs/vuejs on the frontend using websockets with iris ? 
also, is it possible to use webpack for frontend with iris ?

**Comment by kataras** [comment]
First of all thanks for using Iris,

I don't have time to do different all-in-one examples alone, I am preparing for final v3, you can contribute to the [examples](https://github.com/iris-contrib/examples) or [book](https://github.com/iris-contrib/gitbook) if you have time
