### ISSUE TITLE
iris command line tool `iris run main.go`

### ISSUE THREAD

**Issue by rayxiaoo** [kataras/iris#263]
When I modify the template html file, it will not be reloaded, which would require me to re-start the tool.
Can monitor modify the html template file? and reload them, so save some annoying repetitive operation.

-----
sorry, i do not use english, english is very very bad, i don't know if you can understand.

**Comment by kataras** [comment]
Please read the docs before posting an issue, I answer to this many many times, to reload templates add this line to your configuration: ` iris.Config.Render.Template.IsDevelopment = true` , the `iris run main.go` will reload only when source code changes (`.go` )

NO problem about english, I'm the same !!
