### ISSUE TITLE
Getting the values from a simple POST form

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#265]
How do I do this?

**Comment by kataras** [comment]
Read the docs please, I can't answer one-by-one everytime... you do that by ` context.FormValue("thekey")` or ` context.ReadForm(&yourStruct{})`

**Comment by cristian-sima** [comment]
Hi and thanks @kataras Is it a simple way to get the string for a particular form value ?

I have tried using `context.GetString()` and `context.Get()` but it does not work

**Comment by kataras** [comment]
No,  `Context.Get/Set` are for request-lifetime temporary store, that you can use to transfer information between middleware.

>  Is it a simple way to get the string for a particular form value ?

Yes, use the ` context.PostFormValue`  (Note that this will be renamed to FormValueString on the final version*)

**Comment by cristian-sima** [comment]
Thanks @kataras :dango:

**Comment by cristian-sima** [comment]
I suggest to add a section for this is the book, because nothing is there for the forms (I searched :+1: )

**Comment by kataras** [comment]
Examples are there I can't add a section foreach case, yet, when I finish the final v3 I will add more :)

**Comment by cristian-sima** [comment]
Right :D Thank. I did not know there are examples
