### ISSUE TITLE
StreamWriter: connection closed

### ISSUE THREAD

**Issue by paduvi** [kataras/iris#266]
Hi,
I'm not sure is it an issue or not? But I'm in trouble with streaming a file. It seems that the function StreamWriter has run async, and connection closed before it finish.

It's possible I'm doing something wrong in my code.
Please have a look it. I'll be grateful for any kind of advice.

Thanks.

`func check(e error) {
	if e != nil {
		panic(e)
	}
}`

Here is code of that route:
			
			var total int64
			if stat, err := os.Stat(requestPath); os.IsNotExist(err) {
				ctx.NotFound()
				return
			} else {
				total = stat.Size()
			}

			var start int64 = 0
			var end int64 = total - 1

			if string(ctx.QueryArgs().Peek("bytes")) != "" {
				bytes := string(ctx.QueryArgs().Peek("bytes"))
				start = parseInt64(strings.Split(bytes, "-")[0])
				end = parseInt64(strings.Split(bytes, "-")[1])
			}

			f, err := os.Open(requestPath)
			check(err)

			ctx.SetStatusCode(206)
			ctx.SetHeader("Accept-Ranges", "bytes")
			ctx.SetContentType("application/dash+xml")

			ctx.StreamWriter(func(writer *bufio.Writer) {
				defer f.Close()

				_, err = f.Seek(start, 0)
				check(err)

				limit := int(end - start + 1)

				for {

					var buffer []byte
					if limit > 2048 {
						buffer = make([]byte, 2048) // 2KB
					} else {
						buffer = make([]byte, limit)
					}
					n, err := f.Read(buffer)
					if err != nil && err == io.EOF {
						break
					}
					if n == 0 {
						break
					}
					limit = limit - n
					check(err)
					writer.Write(buffer)
					err := writer.Flush()
					check(err)
				}

			})

And this is stack trace:

> 2016/07/06 17:44:54 panic in StreamWriter: connection closed
Stack trace:
goroutine 20 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/chotoxautinh/.gvm/gos/go1.6/src/runtime/debug/stack.go:24 +0x80
github.com/valyala/fasthttp.NewStreamReader.func1.1()
	/Users/chotoxautinh/.gvm/pkgsets/go1.6/global/src/github.com/valyala/fasthttp/stream.go:47 +0x4e
panic(0x682280, 0xc82000b1c0)
	/Users/chotoxautinh/.gvm/gos/go1.6/src/runtime/panic.go:426 +0x4e9
main.check(0xcaa028, 0xc82000b1c0)
	/Users/chotoxautinh/WorkProject/iris-test/server.go:21 +0x4b
main.main.func1.1(0xc82012e480)
	/Users/chotoxautinh/WorkProject/iris-test/server.go:142 +0x294
github.com/valyala/fasthttp.NewStreamReader.func1(0xc82025c4e0, 0xc82012e480, 0x1a001f0, 0xc82026a200)
	/Users/chotoxautinh/.gvm/pkgsets/go1.6/global/src/github.com/valyala/fasthttp/stream.go:51 +0x47
created by github.com/valyala/fasthttp.NewStreamReader
	/Users/chotoxautinh/.gvm/pkgsets/go1.6/global/src/github.com/valyala/fasthttp/stream.go:56 +0x39d

**Comment by kataras** [comment]
Hello this is not an iris question as you see in your logs, please refer this post issue to the [fasthttp](https://github.com/valyala/fasthttp/issues)
