### ISSUE TITLE
How I can read binary body

### ISSUE THREAD

**Issue by milchinskiy** [kataras/iris#267]
Currently this is not an issue, I just not found answer for this question in the doc. So, how i can read binary body, protobuf message for example? As I see, I just can read form, json and xml.

**Comment by kataras** [comment]
`ctx.Request.Body` if you just want to read bytes from the request body, if you want to do streaming you can refer to the book

**Comment by milchinskiy** [comment]
Great, thanks, context.Request.Body() is ok

**Comment by kataras** [comment]
You're welcome

**Comment by labkode** [comment]
How can I use Body as a io.Reader for reading date from it.
My use case is that I have an endpoint where people would upload files (`curl -X PUT ...` --binary-data @/etc/passwd`) but it is a pure binary upload, not multipart.

StreamWriter and StreamReader just work for populating response body, but I need to consume request body as a io.Reader

**Comment by kataras** [comment]
@labkode You answered correctly, here: https://github.com/kataras/iris/issues/377 :)
