### ISSUE TITLE
Possible typo problem

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#268]
From [this page](https://github.com/kataras/iris/blob/master/config/sessions.go#L37)

![image](https://cloud.githubusercontent.com/assets/12199042/16627389/bad02438-43b5-11e6-8926-6158f66896bd.png)

**Comment by pawatzaza** [comment]
100.117.231.253

**Comment by cristian-sima** [comment]
Maybe it was 127.0.0.1:6379

**Comment by pawatzaza** [comment]
ผมไม่สามารถ

**Comment by pawatzaza** [comment]
ช่วยบอกที่ละขั้นตอนได้โปรดผมไม่ถนัดอังกฤษ ผมคนไทย

**Comment by cristian-sima** [comment]
I have no idea what you are saying :))

**Comment by kataras** [comment]
@cristian-sima Thanks it was comment typo, it's `127.0.0.1:6379` 
like some lines up: 

```go
	// DefaultRedisAddr the redis address option, "127.0.0.1:6379"
	DefaultRedisAddr = "127.0.0.1:6379"
```
