### ISSUE TITLE
How to get all the names and actions urls ?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#27]
How to get the action name or  action Url?
How to get all the names and actions.
I want to intercept some routes for authority. Such as for forbidden "/admin"

**Comment by keuller** [comment]
@xpbliss If I understand your question, maybe you can do a middleware for that. For example:

```
func (g *authoriteMiddleware) Serve(ctx *iris.Context) {
   url := ctx.Request.URL
   // here you do any validation based on "URL"
   method := ctx.Request.Method
   // here you do any validation based on "method" or "action"
}
```
Remember that Iris uses standard structs from "net/http" package.

**Comment by kataras** [comment]
@xpbliss  you don't have to pass a global middleware for that, you can just do 
```go

admin := iris.Party("admin")
{
    admin.UseFunc(func(c *iris.Context){ 
       //your logic here
       isAdmin := true
       if isAdmin {
            c.Next()
       }
    }),
    admin.Get("/",func....),
    admin.Get("/dashboard",func..)
}

```

Did we answer your question ?

**Comment by xpbliss** [comment]
Yes,thanks!

**Comment by xpbliss** [comment]
But how to get all the actions to assign to the different user?
Only want to get all the actions!

**Comment by kataras** [comment]
@xpbliss  No problem, with iris you can do a lot of things, for example to get every route registed you can make a plugin, from the [iriscontrol still devellopment plugin](https://github.com/kataras/iris/blob/development/plugins/iriscontrol/iriscontrol.go)
```go


// implement the base IPlugin

func (i *irisControlPlugin) Activate(container iris.IPluginContainer) error {
	i.pluginContainer = container
	return nil
}

func (i irisControlPlugin) GetName() string {
	return Name
}

func (i irisControlPlugin) GetDescription() string {
	return Name + " is just a web interface which gives you control of your Iris.\n"
}

//

// implement the rest of the plugin

// PostHandle collect the registed routes information,append the whole route instance
func (i *irisControlPlugin) PostHandle(route iris.IRoute) {
	if i.routes == nil {
		i.routes = make([]RouteInfo, 0)
	}
	i.routes = append(i.routes, RouteInfo{route.GetMethod(), route.GetDomain(), route.GetPath()})
}

```

check it's code and you will understand, in order to regsted it to the iris you write this:
```go
iris.Plugin(yourPluginStruct{})
iris.Get("/"....)
and so on
```
Tell me if this helped you

**Comment by xpbliss** [comment]
If it is not a plugin?

**Comment by kataras** [comment]
what you mean? you create one plugin for this reason you want, you cannot get them otherwise, if I saved the routes in the plain form your server would use more memory that it is now, this is the best way to do it, using a plugin. do it it's 11 lines of code lol why u boring :P

**Comment by xpbliss** [comment]
```
func main() {
    iris.Get("/home", iris.ToHandlerFunc(testGet))
    iris.Post("/login",testPost)
    iris.Put("/add",testPut)
    iris.Delete("/remove",testDelete)
    iris.Head("/testHead",testHead)
    iris.Patch("/testPatch",testPatch)
    iris.Options("/testOptions",testOptions)
    iris.Listen(":8080")
}
```
How to get the ```/home,/login,/add/remove,/testHead...`` ,and their fun name?

**Comment by kataras** [comment]
@xpbliss  I told you how to get `/home,/login,/add/remove,/testHead..., but why you want to get their func names?

**Comment by xpbliss** [comment]
Just for RBAC.

**Comment by kataras** [comment]
Ok you know better, thanks for the issues

**Comment by xpbliss** [comment]
It may be ugly to get the routes by using plugin.

And,How to get all routes registered at runtime?

**Comment by kataras** [comment]
Plugins are working runtime, look Iris is light for some reasons, one of these are that we don't store all routes to a slice or something like that but instead you can use a plugin to make it, when you learn how plugins works( I add plugins to the documentation, you can read for them) then you will understand what things you can do with that... if you want I can make a plugin for you to get all routes, and call it my routesplugin.GetAllRoutes() for example if you want tell me to do it, but I really thing it's better to code it by yourself you will learn the power of plugins easier

**Comment by kataras** [comment]
@xpbliss  Just created for you, take a look and tell me if that you was looking for: https://github.com/kataras/iris/tree/development/plugins/routesinfo

**Comment by xpbliss** [comment]
Hi, it is worthless. 
because can't  get the   ```Method``` or ```Domain```or ```Path``` from a func or a method at the runtime.
and only give them to a var, and get them from the var at the runtime.

**Comment by kataras** [comment]
Yes man but I don't understand what is the relationship of the 'get all routes' to all these ? the Domain,Name and that's are working I tested myself but logicaly I dont understand what are you asking, you think iris is like revel or something like that, for now it's not I'm alone and I am trying to make it nice ,simple and keep the performance as it is, create a new issue and write your last post, this is a feature.

**Comment by xpbliss** [comment]
```
iris.Get("/getRoutes", func(c *iris.Context) {
        //How to get them?  In the func to get all the route paths, not for a plugin
, but in the func 
    }) 
```

**Comment by kataras** [comment]
You have to explain, what do you mean route paths? the registed paths? you can't do it with the plugin.GetAll() ?

**Comment by xpbliss** [comment]
Use it for rbac .
i can't get them with the plugin.GetAll()  In the func.

**Comment by kataras** [comment]
Why you can't? it shows you an error ? or you don't want to have it as a variable?

**Comment by xpbliss** [comment]
In the func , it get nothing

**Comment by kataras** [comment]
Hmm let me test it wait 5 minutes

**Comment by kataras** [comment]
```go
	iris.Get("/yourpath", func(c *iris.Context) {
		all := info.All()
		for i:=0; i<len(all); i ++ {
			println(all[i].String())
			//outputs->
		
		}
		
		c.Write("yourpath")
	})


```

this is working for me, not for you?

**Comment by xpbliss** [comment]
Yes

**Comment by kataras** [comment]
Share your code snippet with me, because on me this I saw it's working...

**Comment by xpbliss** [comment]
sorry!  it's ok!

**Comment by kataras** [comment]
Okay so I understood well and created this plugin, it's not worthless :P no problem thanks for your issue, if you want something different that the framework doesn't have please create a new issue

**Comment by xpbliss** [comment]
Maybe no necessary to use plugin to ```get all the names and actions urls```,because it only is usef just once.  Indeed , i only use it just once.

Should use a simple function to solve it.

**Comment by kataras** [comment]
Plugin is run before server's listen, it doesn't cost you anything, I can do a function if you want but this will cost you more because  store them as a slice and this will increase the memory usage

**Comment by xpbliss** [comment]
No necessary to store , but  can get them when necessary or runtime.

**Comment by kataras** [comment]
This is the plugin, it doesn't runs after server's listen you're safe no memory or performance cost. 

>No necessary to store , but can get them when necessary or runtime. 
 How am I going to do that? I must  store them inside the tree with their full paths and this is  ++ memory also

**Comment by kataras** [comment]
Look, if some else need it too I will do it . But I can't cost memory usage to all other users because one person wants it... I hope you understand...

**Comment by xpbliss** [comment]
Visit all the tree?

**Comment by kataras** [comment]
they stored as parts, not as complete paths :/

**Comment by kataras** [comment]
@xpbliss  I will do it but the slice of the routes will be NIL AFTER server's listen. So you can get them and store them somewhere at the last line before iris.Listen, is that suits you?

**Comment by xpbliss** [comment]
It does not suit me , because get them  after the server listen anywhete

If can not,  please don't do it, maybe waste your times.

**Comment by kataras** [comment]
You want to be a able to get them in runtime before server's listen? just like an event?

**Comment by xpbliss** [comment]
Yes

**Comment by kataras** [comment]
Ok, you have to use plugin to catch the routes are register in the runtime before server's listen

```go

type routePl struct {}

// This is the event you wanted, plugins works this way
func (r routePl) PreHandle(route iris.IRoute) {
    println(route.GetPath())
}

func main() {

iris.Plugins().Add({}routePl)

iris.Get("/aroute", func(ctx *iris.Context){

})

iris.Listen(":8080")

}


```

**Comment by xpbliss** [comment]
indeed, i didn't like the plugin, it is simple.  so   it is more better if it is a func.

**Comment by kataras** [comment]
Tomorrow I will add a function for this
