### ISSUE TITLE
Getting session outside of handlers

### ISSUE THREAD

**Issue by e4stw00d** [kataras/iris#271]
Easiest example - using iris with html/templates and trying to add custom helper, which one should be able to get session variable (checking for admin rights or other), but can't.

How i can handle it?

**Comment by kataras** [comment]
You can use the 'low-level' sessions API but again you will need the Context, which is unavailable via html functions, you will have to find other way, the most easier is to check for authentication via handler before rendering, and pass the bindings(a custom context for the template) with the ` context.Render("yourfile.html",mapOrStructObjecthere{})`
