### ISSUE TITLE
PongoEngine: 2016/07/08 11:43:18 panic: interface conversion: interface {} is iris.Map, not map[string]interface {} Stack trace:

### ISSUE THREAD

**Issue by jinfei** [kataras/iris#272]
hello ，I use this engine when you encounter this problem, to use the default is not the problem.Is this PongoEngine's problem?

**Comment by jinfei** [comment]
this is my code  
func AppInit(c *iris.Context) {
   	c.MustRender("index.html", nil)
}


func main() {

	// set the configs
	iris.Config.Render.Template.Engine = iris.PongoEngine
	iris.Config.Render.Template.Directory = "./views"
	iris.Config.Render.Template.IsDevelopment = true


	// set the global middlewares
	iris.Use(logger.New(iris.Logger))

	// set the custom errors
	iris.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
		ctx.Render("errors/404.html", iris.Map{"Title": iris.StatusText(iris.StatusNotFound)})
	})

	iris.OnError(iris.StatusInternalServerError, func(ctx *iris.Context) {
		ctx.Render("errors/500.html", nil, iris.NoLayout)
	})

	// register the routes & the public API
	registerRoutes()

	// start the server
	iris.Listen("127.0.0.1:8080")

}

**Comment by kataras** [comment]
@jinfei Are you sure? if the binding is nil it just returns nil, not an iris.Map, what version of Iris did you have? (type `iris -version` )

**Comment by kataras** [comment]
@jinfei Yes, ` iris.Map`  is not correct for Pongo Engine, the example uses html/template because of this you can use iris.Map

**Comment by jinfei** [comment]
Thank you .  I will use  html/template  in the future.
