### ISSUE TITLE
Can i render from string?

### ISSUE THREAD

**Issue by averrin** [kataras/iris#273]
I need single file app, and i want embed template as const string. How i can render it directly?

**Comment by kataras** [comment]
If it's raw html you can use the ` context.HTML` if it is ` html/template` you can use the ` context.ExecuteTemplate` before that you have to load the template from your string as you did before Iris

**Comment by averrin** [comment]
I saw this method, but if i use pongo renderer, can i access RenderString method?

**Comment by kataras** [comment]
`iris.RenderString` takes a template **filename**, converts the template to **html** and **output it's contents**. You can use this if you use the built'n Iris view engine, which supports Pongo also

**Comment by averrin** [comment]
Its very strange for me. Imho ability to render strings is useful for builtin renderers.
But thanks for answer.

**Comment by kataras** [comment]
You can do it, I already answered, with Iris you can do everything but we provide built'n view engines also, it is your decision
