### ISSUE TITLE
Issue with URI Encoded routes

### ISSUE THREAD

**Issue by heynemann** [kataras/iris#275]
I'm testing with Mac OS X, using Iris with commit dcded4e4004a1b5ff7602e8733bc71360a6e14b5 and fasthttp with commit 83a24c301bb683e450cd0304a3eb69556c48678c.

The issue happens when I setup a Route that takes URI encoded fragments. I've tried the following routes:

* `a.Get("/encoding/:url", HealthCheckHandler(app))`
* `a.Get("/encoding/http%3A%2F%2Fsome-url.com", HealthCheckHandler(app))`

Both fail if I request them with `http://localhost:8888/encoding/http%3A%2F%2Fsome-url.com`, but the first one works with `http://localhost:8888/encoding/qwe`.

The error I get is 404. The weird thing here is the URI that was not found is `http://localhost:8888/encoding/http:/some-url.com`. If you look closely you'll notice that it's missing one slash. Not sure if iris or fasthttp is trimming this slash, but it sounds like a bug to me.

I've tried requesting this URL using both Chrome and curl, either way I'm getting 404.

The HealthcheckHandler is a simple handler:

    func(c *iris.Context) {
        c.SetStatusCode(iris.StatusOK)
        c.Write("WORKING")
    }

Hope this helps pinpointing the issue. If you need any further info, let me know.

**Comment by kataras** [comment]
Did you try ` a.Config.DisablePathEscape = true ` ?

**Comment by heynemann** [comment]
I didn't, but it seems to me that when using it as a `:url` argument it should not give 404, should it?

I can see the DisablePathEscape as a workaround for the second scenario (where I have the full URL), but I still can't understand why I should get a 404 in the second one, where I'm using a parameter.

**Comment by kataras** [comment]
I will investigate it later tonight, will be fixed, yes the ` :url`  is acceptable path parameter, it shouldn't be a problem

**Comment by kataras** [comment]
Hello @heynemann ,
Upgrade iris and ** use the iris.URLEncode **.

It was more simplier than we think, not an iris problem, it was a invalid (http:/ instead of http:// of the fasthttp url encoding system) I replace that with the `net/url` parser and now is working, at least for me this worked:

```go

	iris.Get("/encoding/:url", func(ctx *iris.Context) {
		url := iris.URLEncode(ctx.Param("url"))
		ctx.SetStatusCode(StatusOK)
		ctx.Write(url) // gives http://some-url.com
	})

	e := iris.Tester(t)

	e.GET("/encoding/http%3A%2F%2Fsome-url.com").Expect().Status(iris.StatusOK).Body().Equal("http://some-url.com")

```

Please verify it

**Comment by heynemann** [comment]
Shouldn't it be `iris.URLDecode`?

**Comment by kataras** [comment]
The name is not the problem I will fix it, but verify if its worked please
