### ISSUE TITLE
iriscontrol compile error

### ISSUE THREAD

**Issue by darin-lao** [kataras/iris#276]
func main() {
	iris.Plugins.Add(iriscontrol.New(9090, map[string]string{
		"1":             "1",
		"irisusername2": "irispassowrd2",
	}))
	restConfig := config.Rest{
		Gzip:true,
	}
	iris.Servers.Main()
	irisConfig := iris.Default.Config
	irisConfig.Render.Rest = restConfig
	irisConfig.DisablePathCorrection=false
	apiSystem := iris.Party("/api")
	apiV1 := apiSystem.Party("/v1")
	apiV1.API("/user", api.UserAPI, middlewares.CheckUserToken)
	apiV1.Get("/user/:mobile", api.UserAPI.GetByMobile, middlewares.CheckUserToken)
	//apiV1.Get("/user/:mobile", api.UserAPI.GetBy(), middlewares.CheckUserToken)
	//apiV1.Get("/user/:id/:mobile", api.UserAPI.GetByIdMobile(), middlewares.CheckUserToken)
	iris.OnError(iris.StatusNonAuthoritativeInfo, middlewares.ErrorTokenInvalidity)
	iris.Listen("http://127.0.0.1:8080")
}

error  on compile

 github.com/iris-contrib/plugin/iriscontrol
..\github.com\iris-contrib\plugin\iriscontrol\iriscontrol.go:171: i.parent.Servers.Main().VirtualHostname undefined (type *iris.Server has no field or method VirtualHostname)

**Comment by kataras** [comment]
Please post plugins issue on this [repository](https://github.com/iris-contrib/plugin) , the issue has solved, upgrade iris please, thanks you!!
