### ISSUE TITLE
Allow configuring ReadBufferSize

### ISSUE THREAD

**Issue by lcosmin** [kataras/iris#277]
I'm experiencing some errors like:

    2016/07/12 12:12:37 error when serving connection "127.0.0.1:8000"<->"127.0.0.1:45031": error 
    when reading request headers: headers exceed 4096 bytes. Increase ReadBufferSize. buf="GET 
    /api/update HTTP/1.0\r\nHost: localhost:8000\r\nConnection: close\r\nAccept: */*\r\nAccept-
    Encoding: gzip, deflate, sdch, br\r\nAccept-Language: r"..."blablablablablabla"

when handling some GET request with very large headers. However, I'm not able to find a method of adjusting this `ReadBufferSize` to avoid this error. Any idea how I could do this?

**Comment by kataras** [comment]
Yes, you can with the `MaxRequestBodySize` configuration field of the server, which located here: https://github.com/kataras/iris/blob/master/config/server.go#L43 .

To do this, you should use the ` iris.ListenTo(config.Server{ListeningAddr:":8080", MaxRequestBodySize: yourMaxSizeAsint64Here}` instead of ` iris.Listen(":8080")`

**Comment by kataras** [comment]
Hello @lcosmin, you can do that with:

`iris.ListenTo(config.Server{ListeningAddr:":8080", ReadBufferSize : yourSizeHere})` instead of `iris.Listen(":8080")` , don't forget to import the ` github.com/kataras/iris/config`

**Comment by lcosmin** [comment]
Thanks for adding `ReadBufferSize` ! However, I think the commit broke something, because this isn't working anymore (nothing is listening on the port):

package main

    import (
            "github.com/kataras/iris"
	    "github.com/kataras/iris/config"
    )
    
    func main() {
            api := iris.New()
	    api.Must(api.ListenTo(config.Server{ListeningAddr: "0.0.0.0:8080", ReadBufferSize: 16384}))
    }

Commenting this line: https://github.com/kataras/iris/commit/e61d1f8c3cdb4498e9e678cec23080f408324372#diff-fe6b69ef4717d5933c0042b80f5f3246R374   seems to fix it, but not sure if it's the right thing to do.

**Comment by kataras** [comment]
Yes I imagine that... will fix it
