### ISSUE TITLE
Incorrect HTTP method with iris.API

### ISSUE THREAD

**Issue by cgyy** [kataras/iris#284]
Hello @kataras 
I see the example code
```go
// PUT /users
func (u UserAPI) Put() {
	name := u.FormValue("name")
	// myDb.InsertUser(...)
	println(string(name))
	println("Put from /users")
}

// POST /users/:param1
func (u UserAPI) PostBy(id string) {
	name := u.FormValue("name") // you can still use the whole Context's features!
	// myDb.UpdateUser(...)
	println(string(name))
	println("Post from /users/" + id)
}
```
I think this it not correct, Use PUT when you can update a resource completely through a specific resource. For instance, if you know that an article resides at http://example.org/article/1234, you can PUT a new resource representation of this article directly through a PUT on this URL.

If you do not know the actual resource location, for instance, when you add a new article, but do not have any idea where to store it, you can POST it to an URL, and let the server decide the actual URL.

so, I think it should be
```go
// Post /users
func (u UserAPI) Post() {
	name := u.FormValue("name")
	// myDb.InsertUser(...)
	println(string(name))
	println("Put from /users")
}

// PUT /users/:param1
func (u UserAPI) PutBy(id string) {
	name := u.FormValue("name") // you can still use the whole Context's features!
	// myDb.UpdateUser(...)
	println(string(name))
	println("Post from /users/" + id)
}

```

http://stackoverflow.com/questions/630453/put-vs-post-in-rest
http://restcookbook.com/HTTP%20Methods/put-vs-post/

**Comment by kataras** [comment]
Post is dublicated with: https://github.com/iris-contrib/examples/issues/3  please post issues in the correct repo. I already know these for a decade or so, the guy opened this issue made a pr , made your own if you think something should change,thanks!
