### ISSUE TITLE
graceful middleware error

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#285]
I updated to Iris v3, graceful middleware error:
`github.com\iris-contrib\graceful\graceful.go:13:2: cannot find package "github.com/kataras/iris/logger"`

Do not do the test after each update? Most people think that the function of Iris has been very rich, we want to be stable, do not change too frequently.

**Comment by kataras** [comment]
Change the import path to the ` gopkg.in/kataras/iris` , when I finish with the work I'm doing I will make a new branch for middlweare and plugins for v3 ( it is not so hard for developers to think or pr on that but ok..)

**Comment by dxvgef** [comment]
I replace `"github.com/kataras/iris"` into `"gopkg.in/kataras/iris"`, now there's a new error :
`gopkg.in\kataras\iris.v3\http.go:17:2: cannot find package "github.com/kataras/iris/logger"`

**Comment by kataras** [comment]
You have to fix all of them, alone for now, I will do that when I finish the new sessions I'm doing from yesterday

**Comment by dxvgef** [comment]
I have fixed the Iris import path to all files in the project, and now I still need to modify the Iirs of all the source files?

**Comment by kataras** [comment]
Just download the alpha and stick withit until the its final release, the only change is how to register template engine, the examples has been updated you can see there the changes, it will be easier to you, I will fix the v3 but later

**Comment by kataras** [comment]
You're correct about the issue but I never used gopkg my own, I though it can do that automatically, but go dep manager is not the best..
