### ISSUE TITLE
How can  I use the templates Funs by myself ?

### ISSUE THREAD

**Issue by jinfei** [kataras/iris#288]
Hello , I  find  the framework  provide some template Function  ,for example render ,partial  .  But   I will use  some custom function .
How can  I use the templates Funs by myself ?

**Comment by kataras** [comment]
```go
myFuncs := map[string]interface{}{
 "myFunc": func....
}

iris.UseTemplate(html.New(html.Config{Funcs:myFuncs })).Directory("./mytemplates",".html")

```

**Comment by jinfei** [comment]
Thank you for your great help.

**Comment by kataras** [comment]
No problem mate, you're welcome! It's my fault that you didn't know it,  I'm sorry for not updating the book yet ( examples are updated), I just finished with the new sessions also

**Comment by jinfei** [comment]
Hello .These are my templates functions  hope useful to you。

const (
	DateFormat     = "2006-01-02"
	DateTimeFormat = "2006-01-02 15:04"
)

	myFuncs := map[string]interface{}{
		"raw": func(text string) template.HTML {
			return template.HTML(text)
		}, // Format a date according to the application's default date(time) format.
		"date": func(date time.Time) string {
			return date.Format(DateFormat)
		},
		"datetime": func(date time.Time) string {
			return date.Format(DateTimeFormat)
		},
		"even": func(a int) bool { return (a % 2) == 0 },
	}
