### ISSUE TITLE
template charset runtime

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#292]
@kataras I've update the iris framework to the v4.a-2.
I'm using the django template engine. Before the update all my views texts with special characters were displayed normally, but after the update the special characters are no more displayed correctly. 

Is there a new option to set the encoding manually?? Or may this be a bug?

**Comment by kataras** [comment]
It's the `config.Charset` but this will be ` iris.Config.Charset` on the next revision, I am writing an engine to inject the ` context.JSON,XML,Text,Data `  and add custom types also :)

**Comment by kataras** [comment]
Alpha.3 is ready, set your default charset with ` iris.Config.Charset = "your-charset"`

also you can ovveride it with `context.Render("mytemplate.html", bindingStruct{},iris.RenderOptions{"charset":"runtime-charset-for-that-user"})`
