### ISSUE TITLE
No template engine in Iris 4.0

### ISSUE THREAD

**Issue by ivancduran** [kataras/iris#294]
I run this example on iris 3 and works fine, but in the new version send me this error

Error: No template engine found to manage '.html' extensions 

```` go

func indexPage(ctx *iris.Context) {
	fmt.Println("home")
	ctx.Render("page1.html", mypage{"Message"})
	// works on iris 3
	// ctx.MustRender("page1.html", mypage{"Message"})
	// I try this with this too
	// if err := ctx.Render("page1.html", nil, iris.RenderOptions{"layout": iris.NoLayout}); err != nil {
	// 	println(err.Error())
	// }
}

````
Thanks

**Comment by jinfei** [comment]
You can try it .
iris.UseTemplate(html.New()).Directory("./mytemplates",".html")

**Comment by ivancduran** [comment]
Thanks for your help, works fine.

I don't know why in iris 3 works without the library and use template declaration.

But this is the code to solve it


```` go 

import (
	"github.com/kataras/iris"
	"github.com/iris-contrib/template/html"
	...
)

func main() {
    iris.UseTemplate(html.New()).Directory("./templates",".html")
...
}

````

**Comment by kataras** [comment]
@ivancduran  @jinfei The template engine works without  manually the `UseTemplate(html.New())` because it's the default engine if no engines were registered, your code should work, I will look on this

**Comment by kataras** [comment]
Fixed
