### ISSUE TITLE
the manual sample code has been unable to work

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#297]
Iris structure of the project when it can be stable? I will lose patience, I need to spend a lot of time to modify the code compatible with the latest version of the iris, now do not know how to modify, completely unable to start my project :(

**Comment by kataras** [comment]
What do you mean? I made no frontend api changes on the last release, if you used the version 2 or something like that, just read the [HISTORY.d](https://github.com/kataras/iris/blob/master/HISTORY.md). If you're boring to evolve just don't upgrade iris, upgrade of iris gives you new things every time, stability is up to you, iris doesn't have something like auto-updater

**Comment by kataras** [comment]
What do you mean? I made no frontend api changes on the last release, if you used the version 2 or something like that, just read the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) I'm always updating this file before any changes. If you're boring to evolve just don't upgrade iris, upgrade of iris gives you new things every time, stability is up to you, iris doesn't have something like auto-updater.

This is not an issue, you don't give me any code to help you, move these type of conversations on the [chat](https://kataras.rocket.chat/channel/iris) please, thanks you @dxvgef !
