### ISSUE TITLE
Using Unix Socket

### ISSUE THREAD

**Issue by tom-adsfund** [kataras/iris#299]
This is just a question.

Please could you give an example of how to use the Unix Socket listen function? I'm confused by the file mode argument.

Thanks

**Comment by kataras** [comment]
You use the: ` iris.ListenUNIX` if you're confused about file mode on linux you should check some general tutorials first

**Comment by tom-adsfund** [comment]
I really was more wondering how it was used in this context. But from more thinking/searching I see I can simply provide a code like iris.ListenUNIX("filename",0660) and it applies to the socket file itself.

**Comment by kataras** [comment]
Exactly, context is used to communicate with requests/clients, to startup the server you use one of the ` iris.Listen` methods
