### ISSUE TITLE
Would you please help me with this problem?

### ISSUE THREAD

**Issue by taggedboy** [kataras/iris#300]
Would you please help me with this problem? 
[http://stackoverflow.com/questions/38445818/iris-go-web-framework-iris-pongoengine-error-from-iris-official-book](http://stackoverflow.com/questions/38445818/iris-go-web-framework-iris-pongoengine-error-from-iris-official-book)

And from where should we install the framework, gopkg.in or github?

I'm following the book and the last example at [Hi.html](https://kataras.gitbooks.io/iris/content/hi.html) doesn't work.

**Comment by kataras** [comment]
Please follow the examples, https://github.com/iris-contrib/examples/tree/master/template_engines here and this repo: https://github.com/iris-contrib/template you will find the answer :)

**Comment by taggedboy** [comment]
The installation of iris from gopkg.in is not getting successful showing some missing dependencies.

**Comment by kataras** [comment]
I already know this, but this is just an import path issue, you can copy the folder from ` $GOPATH/src/gopkg.in/kataras/iris` to `$GOPATH/src/github.com/kataras/iris` just download the last version and follow the examples, nothing big changed

**Comment by taggedboy** [comment]
So after this issue is fixed, we'd be installing IRIS from github or gopkg.in?

**Comment by kataras** [comment]
I updated the answer please refresh :)

**Comment by taggedboy** [comment]
What if I install master branch from github.com? and set the imports as shown in your above comment? Would it fix everything?

**Comment by kataras** [comment]
Yes, this I'm telling you :)

**Comment by taggedboy** [comment]
So it means I should follow the README at Master(github) for installation and add `"github.com/iris-contrib/template/django"` to the imports in the example I'm stuck in? 

Thank You :+1:

**Comment by kataras** [comment]
Yes and remove the ` iris.Config.Render...` as the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) says, I recommend you always view the history.md file I always update this file on code changes :) You're welcome

**Comment by taggedboy** [comment]
Its asking for too much :) , but I think [the book ](https://kataras.gitbooks.io/iris/content/) is the only resource to learn iris, so when would you update the book to work with the latest version of the framework?

**Comment by kataras** [comment]
I'm writing the book right now :)

**Comment by taggedboy** [comment]
Wow, that would be really awesome! I'm just starting to learn iris and if I get the updated book by tomorrow, it will be more than awesome. 
Thank You once again. :)
If you tell me what needs to be changed, I may help to update it.

**Comment by kataras** [comment]
Ah no problem, there are not big changes but new features added, you can help with english when the commit pushed, if you want :P

**Comment by taggedboy** [comment]
Hi @kataras, I hope you're alright. Did you already start updating the book?

**Comment by kataras** [comment]
Yes I have some issues because of gitbook editor bugs (wordspace and lines are no rendering as they were before the new version, and I work now with two other markdown editors)... I made some fixes also I will write them also

**Comment by kataras** [comment]
@taggedboy  Just finished !!!

[HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md)

**Comment by taggedboy** [comment]
@kataras You mean the book is already updated and we can start using it?

Thank You for the good work!

**Comment by kataras** [comment]
Yes!!, You're welcome !

**Comment by taggedboy** [comment]
@kataras please also let me know which version of the framework do you recommend to be used with the (updated) book? I wanna resume learning iris as soon as I get time. Thank You again!

**Comment by taggedboy** [comment]
@kataras , Let me tell you something. I saw your dedication, which says that someday you'll be very successful.

**Comment by kataras** [comment]
I try for that, but for now maybe I'm the poorest developer in github ahah
