### ISSUE TITLE
Is sessions.expires working?

### ISSUE THREAD

**Issue by antlaw** [kataras/iris#301]
Thanks very much for developing iris. It is fast and easy to use!  
I test the configuration of session expires and try to figure if the session expires really work. The following is the piece of codes to configure the session expires. While I am not sure if Sessions.Exipires or GcDuration works, I try both. 

The following codes should make a new session to be expired almost instantly. However, it does'nt work. It seems that the session is still there, until I restart the server. Is it a bug or there is something wrong with the following codes?

func main() {
	iris.Config.Sessions.Cookie = "_server_session"
	iris.Config.Sessions.Expires = time.Now()
	iris.Config.Sessions.GcDuration = time.Duration(2) * time.Second

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

Yes the `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session.

Sessions has no meaning if you deleting the contents them immediatly, you should try `context.SetFlash/GetFlash/GetFlashes` instead, but I will look into this issue about `GcDuration` and I will response again, please try `context.SetFlash` and tell me if that suits you

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

Yes the `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session (from the server, if the client re-connects then the session is re-new without any needed action from you).

Sessions has no meaning if you deleting the contents them immediatly, you should try `context.SetFlash/GetFlash/GetFlashes` instead, but I will look into this issue about `GcDuration` and I will response again, please try `context.SetFlash` and tell me if that suits you, please

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

Yes the `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session (from the server, if the client re-connects then the session is re-new without any needed action from you).

Sessions has no meaning if you deleting the contents immediately, you should try `context.SetFlash/GetFlash/GetFlashes` instead, but I will look into this issue about `GcDuration` and I will response again, please try `context.SetFlash` and tell me if that suits you, please

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

Yes the `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session (from the server, if the client re-connects then the session is re-new without any needed action from you).

A session has no meaning if you deleting the contents immediately, you should try `context.SetFlash/GetFlash/GetFlashes` instead, but I will look into this issue about `GcDuration` and I will response again, please try `context.SetFlash` and tell me if that suits you, please

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

First of all, try to make an upgrade with ` go get -u github.com/kataras/iris/iris` and try your code again, it should works now.

Some explaination, good to know:

The `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session (from the server, if the client re-connects then the session is re-new without any needed action from you).

A session has no meaning if you deleting the contents immediately, you should try `context.SetFlash/GetFlash/GetFlashes` instead :)

**Comment by kataras** [comment]
Thanks for your nice words, I'm doing my bests.

First of all, try to make an upgrade with ` go get -u github.com/kataras/iris/iris` and try your code again, it should works now.

Some explaination, good to know:

The `iris.Config.Sessions.Expires` sets the expires date on the `Cookie` no the server-side expiration,
the `GcDuration` is checking every `x` , on your case 2 seconds, if a session is used(get or set) lately, and if not it deletes the session (from the server, if the client re-connects then the session is re-new without any needed action from you).

A session has no meaning if you deleting the contents immediately, you should try `context.SetFlash/GetFlash/GetFlashes` instead.

Thanks for bug report!

**Comment by antlaw** [comment]
Hi Gerasimos,

Thanks very much for your prompt response!

Actually I want to expire a session in an hour or two so as to force client
to login again, as a way of minimize the problem of session hijacking. I
set it to 2 seconds just for testing. Thus, GetFlashes doesn't suit my
purpose. If that doesn't work at the moment, I will have another security
measure to serve the same purpose. Cheers!

Best,

Anthony LAW

**Comment by kataras** [comment]
No need to hard-thinking of this, you can simple do this with the `iris.Config.Sessions.Expire` option, which will set the client's session cookie expiration date. The GcDuration is working now I tested it, same with the Expire.

**Comment by antlaw** [comment]
Please correct me if I am wrong: in case a session is hijacked, the hacker
can make use of the session cookie even if it is expired. Then the
option iris.Config.Sessions.Expire
cannot reduce session hijack.  Is that correct?

Best,

Anthony LAW

**Comment by kataras** [comment]
Why don't write something like user- managment with a firstLogged time.Time and logged time.Time compare the firstLogged with the logged every time  and when you should remove the session just call the ` context.Session().Destroy()`  ?

**Comment by antlaw** [comment]
You are rite! That serves the purpose. Great thx!

Best,

Anthony LAW

**Comment by kataras** [comment]
You're welcome!!

**Comment by kataras** [comment]
@antlaw  Ok I did it as you really wanted, I think about it and this is the correct way, you, as developer, shouldn't do that alone, I am responsible for sessions, so you will be updated on the next commit this session change will happens: 

- `iris.Config.Sessions.Expires` it was time.Time, changed to time.Duration, which defaults to 0, means unlimited session life duration, if you change it then the correct date is setted on client's cookie but also server destroys the session automatically when the duration passed, this is better approach, see [here](https://github.com/kataras/iris/issues/301)

**Comment by antlaw** [comment]
Hi Gerasimos,

Thanks very much for the solution! By the way, I am thinking of anything I
can contribute to Iris. For example, I am using Couchbase and wrote a
module that wrap github.com/couchbase/gocb.  Is that useful? Or if you
think of something I can help, please do let me know.

Best,

Anthony LAW

**Comment by kataras** [comment]
Just done, book is updated also, look the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) 

Everybody can help,  you can build a template engine, a response engine, a middleware , or a plugin, [here](https://github.com/iris-contrib).

> I am using Couchbase and wrote a module that wrap github.com/couchbase/gocb. Is that useful? 

Very nice!!
gocb is a prototype lib as I can understand, you can create a [response engine](https://github.com/iris-contrib/response/) for that, make a pull request and I will approve it!!

**Comment by kataras** [comment]
Just done, book is updated also, look the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) 

Everybody can help,  you can build a template engine, a response engine, a middleware , or a plugin, [here](https://github.com/iris-contrib). Or try to find something you can implement for the community, explore the 'third-party job' issue labels: https://github.com/kataras/iris/issues?q=is%3Aissue+label%3A%22third-party+job%22

> I am using Couchbase and wrote a module that wrap github.com/couchbase/gocb. Is that useful? 

Very nice!!
gocb is a prototype lib as I can understand, you can create a [response engine](https://github.com/iris-contrib/response/) for that, make a pull request and I will approve it!!

**Comment by antlaw** [comment]
Just tested it with memory session. It works fine! Thx once again!

Best,

Anthony LAW

**Comment by kataras** [comment]
You're welcome, I thanks you!!
