### ISSUE TITLE
how to set gzip global ?

### ISSUE THREAD

**Issue by darin-lao** [kataras/iris#302]

**Comment by kataras** [comment]
Upgrade with ` go get -u github.com/kataras/iris/iris` 

Before v4.alpha-x you did that with iris.Config.Render.Template.Gzip = true &  iris.Config.Render.Rest.Gzip = true , now you can set it with `iris.Config.Gzip = true` and if you want to change this at runtime for a specific render action use the `iris.RenderOptions` inside `context.Render("myfileOrResponse", struct{}, iris.RenderOptions{"gzip":true})` 

Thanks!
