### ISSUE TITLE
iris.Config.IsDevelopment not work

### ISSUE THREAD

**Issue by zyanho** [kataras/iris#303]
my env 
mac os 10.11.5
go 1.6.2
iris 4.0.0-alpha.3 lastest.

```
irisMyConfig := config.Iris{
	DisableBanner: true,
	IsDevelopment: true,
}

server := iris.New(irisMyConfig)
server.UseTemplate(django.New()).Directory("./templates", ".html")
```

andthen change template and refresh brower. and nothing changed. util recompile and run server.

**Comment by kataras** [comment]
Thanks for the bug report!! It has been fixed now, upgrade with ` go get -u github.com/kataras/iris/iris`
