### ISSUE TITLE
Running child process has exited and the iris's reloading does not work

### ISSUE THREAD

**Issue by whrool** [kataras/iris#304]
When I modified a go file, the iris detected it changed. But the file I modify has some syntax errors, the iris will give some build error. For example:

![image](https://cloud.githubusercontent.com/assets/7413974/16940163/7ede9af4-4dba-11e6-9f0b-9fc8ada30346.png)

After I finished the go file, in other words it has no syntax errors, the iris detected the changes, and then  it will rebuild and reload. But it gave me an error. As follows:

![image](https://cloud.githubusercontent.com/assets/7413974/16940375/10608126-4dbc-11e6-9b20-df0b4e4b492e.png)

And I have looked up the error code, it stands for "No Waiting Child Process".
The problem is caused when killing a non-existent process.
I have checked the rizla code, maybe we can take this exception as a friendly one.

![image](https://cloud.githubusercontent.com/assets/7413974/16940681/03584a34-4dbe-11e6-8407-a01405bc5a7a.png)

**Comment by kataras** [comment]
It's better to transfer this issue on the [rizla](https://github.com/kataras/iris/rizla/issue) 's repo in order to have the needed space to solve it, can you re-write it?

**Comment by whrool** [comment]
I have submitted it on the rizla's repo. Does this need to be closed ?

**Comment by kataras** [comment]
Yes, I will reference the rizla's issue's link here, thanks you very much!

**Comment by kataras** [comment]
Fixed ` go get -u github.com/kataras/rizla`
