### ISSUE TITLE
Provide methods to change/disable exposure of Iris naming

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#305]
Examples:
https://github.com/kataras/iris/blob/077984bd60d12bad27de639c5c7b7b13ef1c3b86/config/sessions.go#L17

https://github.com/kataras/iris/blob/b99afb2875c1cb1876c22995b6a45ead038ffdb7/config/server.go#L42

**Comment by kataras** [comment]
for your first example you can change it already, you should know you're one of the older user:P 

https://github.com/kataras/iris/blob/077984bd60d12bad27de639c5c7b7b13ef1c3b86/config/sessions.go#L33


for the second, I will think about it

**Comment by kataras** [comment]
Just done, book is updated also, look the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) 

`iris.ListenTo(config.Server{ListeningAddr: ":8080", Name: "Myserver built with Iris"}) `
