### ISSUE TITLE
Question: json bindings validation

### ISSUE THREAD

**Issue by SlavaBobik** [kataras/iris#306]
Hi. I didn't find any information about: how to validate model after binding?
For e.g I have a code like:
```go
type postUserViewModel struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func postUser(ctx *iris.Context) {
	var userVM postUserViewModel
	ctx.ReadJSON(&userVM)
}
```
Of course I can check my properties by hand(`if userVM.Email != nil .....`) , but is there a way to do it by framework?

**Comment by ryanbyyc** [comment]
https://github.com/kataras/iris/issues/84

I personally use https://gopkg.in/bluesuncorp/validator.v8

**Comment by kataras** [comment]
This post is dublicated, please search older post issues before posting new,

json validation or any type of validation can be done by custom methods or using a third-party package, as @ryanbyyc  suggested
