### ISSUE TITLE
Can not pass emty address to iris.Listen

### ISSUE THREAD

**Issue by positiveviking** [kataras/iris#307]
When using `iris.Listen(addr)` I can not force to listen on all host interfaces because iris change empy hostname to `config.DefaultServerAddr` (i.e. "127.0.0.1").

But `net.Listen` which used inside server can serve empty hostname for listenini on all interfaces.

There is workaround - set servers manualy, but I want to use `iris.Listen` in simple cases.

Iris version: v4.0.0-alpha.1

Steps to reproduce:
1. create instance of iris server by `iris.Listen(":8080")`
2. try to connect to port 8080 on net interface different from localhost by any client. Now got connection refused

**Comment by ljyf5593** [comment]
please try iris.Listen("0.0.0.0:8080")
in my code, it's work.

**Comment by kataras** [comment]
@positiveviking  ` iris.Listen(":8080")` on iris will gives you the `127.0.0.1:8080` , if you want to do that you telling, just use the `iris.Listen("0.0.0.0:8080")` as very correctly @ljyf5593 says!

**Comment by positiveviking** [comment]
This situation makes Iris servers different in configuration from other golang network apps.
I think in this case it should be explicitly documented or value of `config.DefaultServerAddr` changed to "0.0.0.0".

PS my question was not "how to get listeners on all interfaces".

**Comment by kataras** [comment]
you can pass empty addr on iris, ` iris.Listen(":8080")` but not empty port

**Comment by positiveviking** [comment]
If I use net.Listen("tcp", ":8080") then I will listen on all interfaces. But in Iris I will listen on localhost only.
It's bit confusing and for common config for all applications I should write workarounds for Iris.

From [oficial documentation](https://golang.org/pkg/net/#Listen) on net.Listen function:
> If host is omitted, as in ":8080", Listen listens on all available interfaces instead of just the interface with the given host address

**Comment by kataras** [comment]
I already know this but some hosting websites are not allowed `0.0.0.0` this is the reason which Iris is listening on 127.0.0.1 by default if you do not specify an addr, this is not problem you can just use `iris.Listen("0.0.0.0:8080")`

**Comment by kataras** [comment]
You know that I can't approve it, if you read the contribution file... anyway I did something different, set the default to '0.0.0.0' as it's by golang's default listener, and if someone has problems with their hosting machines they can just open an issue
