### ISSUE TITLE
router_memory panic

### ISSUE THREAD

**Issue by oskca** [kataras/iris#31]
when rolling back to revision: 445cf20, this error vanished 

2016/03/23 19:08:04 http: panic serving [::1]:47968: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc82036c000)
	$GOROOT/src/net/http/server.go:1389 +0xc1
panic(0xb13c00, 0xc82000e110)
	$GOROOT/src/runtime/panic.go:426 +0x4e9
github.com/kataras/iris.(*MemoryRouter).ServeHTTP(0xc8200101e0, 0x7f0b9147b3d8, 0xc82033b380, 0xc8203562a0)
	$GOPATH/src/github.com/kataras/iris/router_memory.go:76 +0xb3
github.com/kataras/iris.ServeHTTP(0x7f0b9147b3d8, 0xc82033b380, 0xc8203562a0)
	$GOPATH/src/github.com/kataras/iris/iris.go:191 +0x5c
net/http.HandlerFunc.ServeHTTP(0xd18830, 0x7f0b9147b3d8, 0xc82033b380, 0xc8203562a0)
	$GOROOT/src/net/http/server.go:1618 +0x3a

**Comment by kataras** [comment]
Yes because Iris were used two routers, memory and the normal, now it uses normal,normal-domain,memory and memory-domain, we didn't have support for subdomains now we have. So I think you forget to call the iris.Listen or if you use other server, you have to return the handler wih that: 
```go
iris.Listen(":80")  
////OR //////
yourIrisvariable := iris.New()
http.ListenAndServe(":80",yourIrisvariable.Serve())

```go

**Comment by oskca** [comment]
Yes. Problem Solved.  The problem did relate to function `Serve()`. Thank you :+1:

**Comment by kataras** [comment]
@oskca  now this is optionally but it's good to have it :) no problem I thanks for your issue comment!
