### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by cocotyty** [kataras/iris#311]
```html
<main>
    <div>
        <line each="{item in lines}" data="{item}"></line>
    </div>
    <script>
        this.lines = [{
            "Name": "James",
            "Address": "xxxxxx"
        }, {
            "Name": "James",
            "Address": "oooo"
        },];
    </script>
</main>
```

```html
<line>
    <div>
        <h5>{data.Name}</h5>
        <p>{data.Address}</p>
        <p show="{text}">text:{text}</p>
        <button type="button" onclick="{click}">ADD</button>
    </div>

    <script>
        var self = this;
        this.data = opts.data;
        this.click = function () {
            self.update({text: "show texts"});
        }
    </script>
</line>
```
update not works.

but ,
```html
<line>
    <div>
        <h5>{data.Name}</h5>
        <p>{data.Address}</p>
        <p show="{data.text}">text:{data.text}</p>
        <button type="button" onclick="{click}">ADD</button>
    </div>

    <script>
        var self = this;
        this.data = opts.data;
        this.click = function () {
            self.data.text="show texts"
            self.update();
        }
    </script>
</line>
```

update can work.

??

**Comment by kataras** [comment]
@cocotyty This is a backend web framework.  Template engines has nothing to do with the underline template parsing, so you should ask this question to the link of each template engine you're using, for example https://github.com/iris-contrib/examples/blob/master/template_engines/template_django_5/main.go#L46

**Comment by kataras** [comment]
@cocotyty This is a backend web framework.  Template engines have nothing to do with the underline **template parsing**, so **you should ask this question to the link** of each template engine's parser you're using, for example https://github.com/iris-contrib/examples/blob/master/template_engines/template_django_5/main.go#L46

Sorry, I can't answer you here, but thanks for posting!

> next time write a specific title please

**Comment by cocotyty** [comment]
sorry  ,wrong place! 
very sorry!

**Comment by kataras** [comment]
Don't worry man, you're welcome, if you have any question or iris-releated issue  don't hesitate to ask again!
