### ISSUE TITLE
auto-gzip doesn't really compress data in latest code

### ISSUE THREAD

**Issue by snksoft** [kataras/iris#312]
The issue is that gzipWriterPool creates gzipWriters as follows: &gzip.Writer{}
Which means all gzip.Writer fields are initialized with 0 values for corresponding type. Particularly level member of the struct is initialized to 0, which means NoCompression.  Which renders auto-gzip useless. Compression level should be either DefaultCompression (which is my preference) or BestSpeed.  Or better still, configurable through iris.Config options.

I, honestly, see what you are trying to achieve by using &gzip.Writer{} instead of calling NewWriterLevel, but that sets compression level to NoCompression and I don't see any option in the library to change it later. Though, you can probably ask library author to add ResetWithLevel method.

On a related note though, are you sure you want to have a gzip pool there? I'd say synchronized acquire and and synchronized release will probably outweigh cost of allocation of gzip.Writer struct.

Another potential issue is with this code in response.go (and similar code in other places):

        if gzipEnabled {
                gzipWriter := ctx.framework.AcquireGzip(ctx.Response.BodyWriter())
                defer ctx.framework.ReleaseGzip(gzipWriter)
                _, err := gzipWriter.Write(finalResult)
                if err != nil {
                        return err
                }
                ctx.Response.Header.Add("Content-Encoding", "gzip")
        } else {
                ctx.Response.SetBody(finalResult)
        }

The trouble is -  gzipWriter must be closed explicitly once writing is done (i.e after gzipWriter.Write), not waiting till function exit with defer. Otherwise there is no guarantee that data will be flushed. In fact, it's almost guaranteed that it won't as gzip format appends 8 byte metadata at the end of file, which just can't be done until file is closed. The code above does work properly at the moment, but only because it is the last block in the function and also ctx.Response.BodyWriter() still exists after the function exits. I'd say it spells "asking for trouble". E.g. similar code in template.go calls another function in return statement. If that functions accesses and modifies response body then data will become corrupted (once original function exits, closing gzip stream and appending gzip metadata to whatever is now in response body).

**Comment by kataras** [comment]
Hello @snksoft, you have to try this on bigger examples to see the difference, otherwise an 8bytes of text, it will go 25 with gzip, but 5k bytes will go ~2.2k. However the true is that we had an issue, I tested with examples and gzip is working again now, can you verify it, please?

 Thank you very much!

**Comment by kataras** [comment]
Hello @snksoft, could you please, upgrade iris and verify that is fixed? 

Try to test it with 1k bytes+ size,  you can download and run [this response engine example](https://github.com/iris-contrib/examples/blob/master/response_engines/markdown_2/main.go#L82) and [this template engine example](https://github.com/iris-contrib/examples/blob/master/template_engines/template_markdown_1/main.go)

 Thank you very much!

**Comment by snksoft** [comment]
Yes, it works now. 

On a related note though, StaticWeb does not appear to compress files by default. I sure can workaround this by using StaticHandler directly and it works. But documentation appears to suggest that StaticWeb already does it by default. Or am I missing something?
