### ISSUE TITLE
context.FormValue should return string, not []byte

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#314]
I am always getting the value of the forms as strings, but because `context.FormValue` is returning an `array of bytes`, I am forced to end up with something complex, which **minimize the readability of code**:

`clientID    = string(context.FormValue("client"))`

It would be easier to have this way:

`clientID    = context.FormValue("client")`

Also, in **all examples** you convert it to string as [shown here ](https://github.com/iris-contrib/examples/search?utf8=%E2%9C%93&q=string%28context.FormValue)

Returning a string instand of a byte array, does not affect the previous code, because it will be something like:

 `string(string(byteArray))`

**Comment by kataras** [comment]
`context.FormValue(string) []byte`  is useful on some certain scenarios I'm not changing this. We have already a function which will return string, without need to convert it. `context.FormValueString`  will return string

**Comment by kataras** [comment]
We have already a function which returns string, without need to convert it. `context.FormValueString`  will return string.

`context.FormValue(string) []byte`  is useful on some certain scenarios I'm not changing this, sorry.

**Comment by kataras** [comment]
We have already a function which returns string, without need to convert it. **`context.FormValueString`** .

`context.FormValue(string) []byte`  is useful on some certain scenarios I'm not changing this, sorry.

**Comment by cristian-sima** [comment]
That's good :) Did you think about something more simpler ? (it is usually very used) - like `context.GetString("")`

**Comment by kataras** [comment]
`context.GetString` is already there, used to get the string value of the context's request-life-timetime-store

**Comment by kataras** [comment]
Do you have read about `context.ReadForm` ? , it can help you if you use many times the `context.FormValue/FormValueString` on the same handler. Book section [here](https://kataras.gitbooks.io/iris/content/request-body-bind.html)

**Comment by cristian-sima** [comment]
Thank you :D I will have a look

**Comment by kataras** [comment]
You're welcome my friend!
