### ISSUE TITLE
Go-Bindata + ctx.Render

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#315]
I'm having issues with using go-bindata

```
t := iris.UseTemplate(html.New(html.Config{})).Directory("./templates", ".html")
t.Binary(views.Asset, views.AssetNames)
```

Response: `html/template: "public/home.html" is undefined`

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/iris-contrib/template/...` and iris for any case `go get -u github.com/kataras/iris` it was a mistake for path prefix with `./templates` and `templates`. Thank you!!

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/iris-contrib/template/...` and iris for any case `go get -u github.com/kataras/iris` it was a mistake for path prefix with `./templates` and `templates`. 

How you can also use `iris.UseTemplate(html.New(html.Config{})).Directory("./templates", ".html").Binary(views.Asset, views.AssetNames)` 

Thank you!!

- Example [here](https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary)

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/iris-contrib/template/...` and iris for any case `go get -u github.com/kataras/iris` it was a mistake for path prefix with `./templates` and `templates`. 

How you can also use `iris.UseTemplate(html.New()).Directory("./templates", ".html").Binary(views.Asset, views.AssetNames)` 

Thank you!!

- Example [here](https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary)

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/iris-contrib/template/...` and iris for any case `go get -u github.com/kataras/iris` it was a mistake for path prefix with `./templates` and `templates`. 

How you can also use `iris.UseTemplate(html.New()).Directory("./templates", ".html").Binary(views.Asset, views.AssetNames)` 

Thank you, verify it and close the issue please

- Example [here](https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary)

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/iris-contrib/template/...` and iris for any case `go get -u github.com/kataras/iris` it was a mistake for path prefix with `./templates` and `templates`. 

Now you can also use `iris.UseTemplate(html.New()).Directory("./templates", ".html").Binary(views.Asset, views.AssetNames)` 

Thank you, verify it and close the issue please

- Example [here](https://github.com/iris-contrib/examples/tree/master/template_engines/template_binary)

**Comment by ryanbyyc** [comment]
See the changes, in the process of verifying now.

**Comment by ryanbyyc** [comment]
Verified as working! Thanks a bunch.

**Comment by kataras** [comment]
You're welcome, as always, I thank you!
