### ISSUE TITLE
https://github.com/kataras/iris/issues?utf8=%E2%9C%93&q=author%3Aetemelkuran%20

### ISSUE THREAD

**Issue by etemelkuran** [kataras/iris#317]
There should be a special gerasimos page. 

Routeraki (ρωυτεράκι) (Chinese Alphabet)

gerasimos := iris.Kataras()

prints ->
"γεράσιμος μαροπουλος" (Chinese meaning -> Birds fly, man die.)

**Comment by kataras** [comment]
Ok, sorry man I can't continue this, I know you have respect on me but you can't post these things on github issue page, you did it more than one time: https://github.com/kataras/iris/issues?utf8=%E2%9C%93&q=author%3Aetemelkuran%20 , I told you stop doing that man... 

You're blocked from the repository, sorry I can't do something else.
