### ISSUE TITLE
Feature: data binding for iris

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#32]
Like  data binding[https://github.com/mholt/binding](url)

**Comment by kataras** [comment]
This is very nice, welldone, 99% a future feature, we can build our own bindings for the request, it's not too hard. If you want to pull request an implementation of bindings do it, thanks!

**Comment by xpbliss** [comment]
Should do something for binding form.

Request data binding and validation for iris.
such as ```https://github.com/echo-contrib/binding```

**Comment by kataras** [comment]
https://github.com/mholt/binding is not suited you, so you want Bind function inside Context.
I just (almost) finished the Typescript plugin, the next step is bindings I promise you :)

**Comment by kataras** [comment]
@xpbliss  JSON and XML, is already here in iris via the ```c.ReadJSON(&yourstruct)``` and ```c.ReadXML(&yourstruct)``` the Form is missing, the next commit will be that, and a custom binder. 

Also I didn't liked the echo's bindings because are slow, I prefer your first suggestion /mholt/binding, I will try to integrade that with Iris

**Comment by kataras** [comment]
@xpbliss Can you upgrade Iris and test if c.ReadForm(&yourObject{}) works?

**Comment by xpbliss** [comment]
Tomorrow, i can test it.

**Comment by xpbliss** [comment]
Why not give a example for test?

**Comment by xpbliss** [comment]
c.ReadForm(&yourObject{}) does not work.

```
  iris.Post("/form", func(ctx *iris.Context) {
	aa:=Company{}
	err:=ctx.ReadForm(&aa) 
	fmt.Println(aa)
    })
```
```curl -X POST http://localhost:8080/form -d 'name=123'```, the ```aa``` is nil.
when as the following:
```
  iris.Get("/form", func(ctx *iris.Context) {
	aa:=Company{}
	err:=ctx.ReadForm(&aa) 
	fmt.Println(err)
	fmt.Println(aa)
    })
```
```http://localhost:8080/form?name=123```
```Error on ReadForm: request doesn't contains form data```

another way :https://github.com/gorilla/schema

**Comment by kataras** [comment]
Do you have a form with valid fields ? if not you have somehow to tell the binder how to read your object

```go
type Person struct {
    Name  string `schema:"name"`  // custom name
    Phone string `schema:"phone"` // custom name
    Admin bool   `schema:"-"`     // this field is never set
}

```

**Comment by kataras** [comment]
Wait I will add an example on iris-contrib repository

**Comment by kataras** [comment]
This is working for me:

```go
package main

import (
	"fmt"
	"html/template"

	"github.com/kataras/iris"
)

type Visitor struct {
	Username string
	Mail     string
}

func main() {

	iris.Get("/", func(ctx *iris.Context) {
		ctx.ExecuteTemplate(formTemplate, "")
	})

	iris.Post("/form_action", func(ctx *iris.Context) {
		visitor := &Visitor{}
		err := ctx.ReadForm(visitor)
		if err != nil {
			fmt.Println("Error when reading from form: " + err.Error())
		}
		fmt.Printf("\n Visitor: %v", visitor)
	})

	fmt.Println("Server is running at :8080")
	iris.Listen()
}

var formTemplate = template.Must(template.New("").Parse(`
<!DOCTYPE html>
<head>
<meta charset="utf-8">
</head>
<body>
<form action="/form_action" method="post">
<input type="text" name="Username" />
<br/>
<input type="text" name="Mail" />
<hr/>
<input type="submit" value="Send data" />

</form>
</body>
</html>
`))



```

**Comment by xpbliss** [comment]
Thanks!

**Comment by kataras** [comment]
My pleasure, you see Iris finds easier way to do bindings, no external libraries or so much code for simple binds is necessary, your  feature has implemented with the best way I think :P

**Comment by xpbliss** [comment]
How about Datetime? Embedded struct?

**Comment by kataras** [comment]
It can map Embedded  structs, what do you mean datetime? you can just get string and parse it to date

**Comment by xpbliss** [comment]
Ok!

**Comment by kataras** [comment]
I cant provide datetime because you maybe want to format your datetime other way that I want? you understand;

**Comment by xpbliss** [comment]
```ctx.ExecuteTemplate(formTemplate, "")```
ctx has not the function!

**Comment by kataras** [comment]
the golang works with libraries/packages, the ExecuteTemplate is new function inside the context, so the .ReadForm(), so please run ``` go get -u github.com/kataras/iris ``` to update the package

**Comment by xpbliss** [comment]
it doesn't support Embedded struct?

```
package main

import (
	"fmt"
	"html/template"
	"github.com/kataras/iris"
)

type Visitor struct {
	Username string
	Mail     string
	Usr      []struct {
		Username string
		Mail     string
	}
	Location struct {
		Country string
		City    string
	}
}

func main() {

	iris.Get("/", func(ctx *iris.Context) {
		//template.Template.ExecuteTemplate(ctx.GetResponseWriter(), "name", formTemplate)
		ctx.ExecuteTemplate(formTemplate, "")
	})

	iris.Post("/form_action", func(ctx *iris.Context) {
		visitor := &Visitor{}
		err := ctx.ReadForm(visitor)
		if err != nil {
			fmt.Println("Error when reading from form: " + err.Error())
		}
		fmt.Printf("\n Visitor: %v", visitor)
		fmt.Println(visitor)
	})

	fmt.Println("Server is running at :8080")
	iris.Listen()
}

var formTemplate = template.Must(template.New("").Parse(`
<!DOCTYPE html>
<head>
<meta charset="utf-8">
</head>
<body>
<form action="/form_action" method="post">
<input type="text" name="Username" />
<br/>
<input type="text" name="Mail" />
<br/>
<input type="text" name="Usr[0].Username" />
<br/>
<input type="text" name="Location.City" />
<br/>
<input type="submit" value="Send data" />
</form>
</body>
</html>
`))

```

**Comment by xpbliss** [comment]
another form dealer.  suport datetime and embedded struct? 
[https://github.com/monoculum/forma](https://github.com/monoculum/formam)

**Comment by kataras** [comment]
Yes, this is actually better from mine implementation, it'is the only which I can approve for this job

**Comment by xpbliss** [comment]
Make it in iris?

**Comment by kataras** [comment]
I just do that, check it and tell me the results !

**Comment by xpbliss** [comment]
it work well!  thanks!
