### ISSUE TITLE
How to set template.delimiters?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#320]
I want to set  template's delimiters such as "[[ ]]",
How to set it  in Iris?

**Comment by kataras** [comment]
https://github.com/iris-contrib/template/blob/master/html/config.go#L5

Please read the [docs](https://kataras.gitbooks.io/iris/content/template-engines.html) and [examples](https://github.com/iris-contrib/examples/tree/master/template_engines).

Code snippet:

```go
import (
   "github.com/iris-contrib/template/html"
   //...
)
//...
iris.UseTemplate(html.New(html.Config{Left: "[[", Right: "]]"}))

```

**Comment by xpbliss** [comment]
thanks!

**Comment by kataras** [comment]
You're welcome my friend!
