### ISSUE TITLE
Automated Documentation for REST APIs

### ISSUE THREAD

**Issue by douglarek** [kataras/iris#322]
This will  make api documentation an easier task.

A sample: http://restframework.herokuapp.com/.

**Comment by kataras** [comment]
Anyone who wants to help to build that, 
take a look at
- the [plugin.go](https://github.com/kataras/iris/blob/master/plugin.go)
- [book section](https://kataras.gitbooks.io/iris/content/plugins.html)
- simple plugin [example](https://github.com/iris-contrib/examples/blob/master/plugin_simple/main.go)

With plugins you can register another running server instance inside iris, or add routes, or inject user-defined routes or add middleware and everything else you can do with iris.

**Comment by jjhesk** [comment]
is this possible to have a page to show all the api endpoints and the workbrench to test them?
