### ISSUE TITLE
Blocking TLS

### ISSUE THREAD

**Issue by matthmsl** [kataras/iris#323]
Hi @kataras 
I noticed that creating a server with ListenTLS is a blocking function due to the Go() function in iris.go. This function tries to read from a system pipe but blocks while the pipe is empty. The problem is 

1. It doesn't seems that this function is unblocked when a SIGKILL or a SIGTERM is triggered
2. I can't start a second server, listening on another port in a single function just after listening the TLS one.

Suggestion : what if this (on iris.go starting line 316)

s.Plugins.DoPostListen(s)
	go func() { s.Available <- true }()
	ch := make(chan os.Signal)
	<-ch
	s.Close() // btw, don't panic here
	return nil
}

became this
	s.Plugins.DoPostListen(s)
	go func() { s.Available <- true }()
	go waitDeath(s)
	return nil
}

func waitDeath(s *Framework){
	ch := make(chan os.Signal)
	<-ch
	s.Close() // btw, don't panic here
}

Tried it on my project. Seems it's working.

Fun fact : starting a HTTP server seems non blocking
--
using iris ver 4.0.0-alpha.4

**Comment by kataras** [comment]
ListenTLS works just fine, please read the docs and the examples first, the .Listen/To/TLS always goes to the end.

about your suggestion, if we do that then it is non-blocking

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.AddServer(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}

```

- examples [here](https://github.com/iris-contrib/examples/),  	multiserver_listening &  	multiserver_listening_2

**Comment by kataras** [comment]
ListenTLS works just fine, please read the docs and the examples first, the .Listen/To/TLS always goes to the end.


```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.AddServer(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}

```

- examples [here](https://github.com/iris-contrib/examples/),  	multiserver_listening &  	multiserver_listening_2

About your suggestion, if we do that you say then we will break the Listen functions, they will be non-blocking functions. 
If the signals doesn't works for you, you can try the [graceful](https://github.com/iris-contrib/graceful).

> Please star Iris in order to be notified for updates, you're welcome to our community!

**Comment by kataras** [comment]
Hello, first of all thanks for using Iris.

Secondly, provide a more specific issue title the next time.

ListenTLS works just fine, please read the docs and the examples first, the .Listen/To/TLS always goes to the end.


```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.AddServer(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}

```

- examples [here](https://github.com/iris-contrib/examples/),  	multiserver_listening &  	multiserver_listening_2

About your suggestion, if we do that you say then we will break the Listen functions, they will be non-blocking functions. 
If the signals doesn't works for you, you can try the [graceful](https://github.com/iris-contrib/graceful).

> Please star Iris in order to be notified for updates, you're welcome to our community!

**Comment by kataras** [comment]
Hello, first of all thanks for using Iris.

Secondly, provide a more specific issue title the next time.

ListenTLS works just fine, please read the docs and the examples first, the .Listen/To/TLS/UNIX always goes to the end.


```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.AddServer(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}

```

- examples [here](https://github.com/iris-contrib/examples/),  	multiserver_listening &  	multiserver_listening_2

About your suggestion, if we do that you say then we will break the Listen functions, they will be non-blocking functions. 
If the signals doesn't works for you, you can try the [graceful](https://github.com/iris-contrib/graceful).

> Please star Iris in order to be notified for updates, you're welcome to our community!

**Comment by kataras** [comment]
Hello, first of all thanks for using Iris.

Secondly, provide a more specific issue title the next time.

ListenTLS works just fine, please read the docs and the examples first, the .Listen/To/TLS/UNIX always goes to the end.


```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/config"
)

/*
	Previous example: multiserver_listening
*/
func main() {
	host := "127.0.0.1:443"
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server")
	})

	iris.Get("/mypath", func(ctx *iris.Context) {
		ctx.Write("Hello from the SECURE server on path /mypath")
	})

	// start a secondary server (HTTP) on port 80, this is a non-blocking func
	// redirects all http to the main server which is tls/ssl on port :443

	iris.AddServer(config.Server{ListeningAddr: ":80", RedirectTo: "https://" + host})

	// start the MAIN server (HTTPS) on port 443, this is a blocking func
	iris.ListenTLS(host, "mycert.cert", "mykey.key")

	// now if you navigate to http://127.0.0.1/mypath it will send you back to https://127.0.0.1:443/mypath (https://127.0.0.1/mypath)
}

```

- examples [here](https://github.com/iris-contrib/examples/),  	multiserver_listening &  	multiserver_listening_2

About your suggestion, if we do that you say then we will break the Listen functions, they will be non-blocking functions. 

try this and tell me if that works for you : 
change the `ch := make(chan os.Signal)`  to: 
` ch := make(chan os.Signal, 1)` 

If the signals doesn't works for you, you can try the [graceful](https://github.com/iris-contrib/graceful).

> Please star Iris in order to be notified for updates, you're welcome to our community!

**Comment by matthmsl** [comment]
OK ! see I have to use the AddServer function. Thanks for helping ;)

The signal still doesn't work with `ch := make(chan os.Signal, 1)`

**Comment by kataras** [comment]
You're welcome mate!

> I think it would be very helpful to have a non-blocking listen function

no need for a non-blocking when you can just `go iris.Listen/To/TLS/UNIX, iris.Go()`, I want to keep this framework as much simple as possible with many features at the same time.

> The signal still doesn't work with ch := make(chan os.Signal, 1)

Then if you really want graceful shutdown, use the graceful package posted on the previous comment
