### ISSUE TITLE
iris ListenTLSAuto wrong redirection ?

### ISSUE THREAD

**Issue by gzliudan** [kataras/iris#325]
When I test below code, if I type http://192.168.0.55 or http://127.0.0.1 in Chrome, it becomes https://0.0.0.0 

package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from SECURE SERVER!")
	})

	iris.Get("/test2", func(ctx *iris.Context) {
		ctx.Write("Welcome to secure server from /test2!")
	})

	iris.ListenTLSAuto(":443")
}

**Comment by kataras** [comment]
@gzliudan Sorry man this is not an iris problem, more likely chrome's behavior on localhost/127.0.0.1/0.0.0.0, try it on firefox and you will understand, ` iris.ListenTLSAuto` should have real domain to work for real, otherwise you're just testing it
