### ISSUE TITLE
CORS issue on alpha 4.0 

### ISSUE THREAD

**Issue by intoxicated** [kataras/iris#326]
I initially started the project with iris v3 and it worked out well. But after I updated iris to current version, it started to stop functioning, specifically, Options method won't passed CORS validation.
I used cors from iris-contrib package. 

    	s.Use(cors.New(cors.Options{
		  AllowedOrigins:   []string{"*"},
		  AllowedMethods:   []string{"GET", "PATCH", "PUT", "POST", "DELETE", "OPTIONS"},
		  AllowedHeaders:   []string{"Authorization", "Content-Type", "Accept"},
		  AllowCredentials: true,
	    }))

Any idea how to fix this?

**Comment by kataras** [comment]
Please look other issues its [repository](https://github.com/iris-contrib/middleware/issues) look my answer there, thanks you!
