### ISSUE TITLE
Need suggestion.

### ISSUE THREAD

**Issue by kujtimiihoxha** [kataras/iris#327]
@kataras What would you suggest to use as ORM with iris? do you have any preferences or any other solution for database connection with iris.

Thank you in advance.

**Comment by kataras** [comment]
Iris doesn't have preferences, you can use whatever you like, you used to use and you used before iris.

For example we have an example with `Mongo` [here](https://github.com/iris-contrib/examples/tree/master/AIO_examples_mgo). But iris can work with all ORM, I don't want to affect you  with my personal flavour on this subject...

**Comment by kataras** [comment]
Iris doesn't have preferences, you can use whatever you like, you used to use and you used before iris.

For example we have an example with `Mongo` [here](https://github.com/iris-contrib/examples/tree/master/AIO_examples_mgo). But iris can work with all ORM, I don't want to affect you, on public, with my personal flavour on this subject...

These type of questions are good for [chat](https://kataras.rocket.chat/channel/iris), we already do a lot of these conversations, for ORM and other stuff, I will be glad if you joined with us!

**Comment by kataras** [comment]
Hello @kujtimiihoxha, I understand your concerns, some frameworks limits your will on certain things, but iris is not one of them.

Iris doesn't have preferences, you can use whatever you like, you used to use and you used before iris.

For example we have an example with `Mongo` [here](https://github.com/iris-contrib/examples/tree/master/AIO_examples_mgo). But iris can work with all ORM, I don't want to affect you, on public, with my personal flavour on this subject...

These type of questions are good for [chat](https://kataras.rocket.chat/channel/iris), we already do a lot of these conversations, for ORM and other stuff, I will be glad if you joined with us!
