### ISSUE TITLE
Form format?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#330]
When i use '''post''" method to submit form data to the server.
It is such as the following 

      ```name1=value1&name2=value2```,

why ? It should be the ```get```  method data form.

**Comment by DevSpouk** [comment]
Nothing he has not read the http protocol specification.
Form secretly sent to the server when using the POST / PATH, using the GET method, the form data is transmitted in the clear, with have a limit on the length.

The author correctly there is a processing such requests.

**Comment by xpbliss** [comment]
but I use the post method

**Comment by kataras** [comment]
Hello @xpbliss , can you give me a code snippet, if you pass them using `POST` it should be getable with ` context.PostValue ` or `context.ReadForm` . Does the url seems like `name1=value1&name2=value2` ?, if yes then you should take a better look at your client code, it is not iris problem :/
