### ISSUE TITLE
Replace/disable default session?

### ISSUE THREAD

**Issue by DevSpouk** [kataras/iris#332]
There are specific mechanisms disable or replace an existing session, the implementation of its own?
Tnx.

**Comment by kataras** [comment]
Iris' sessions is one of the best implementations in the Golang world, 'why the hell' will you ever need to replace it? Btw, if you want to use your own stuff, it is possible with iris, pass an empty cookie name:  `iris.Config.Sessions.Cookie = " "` and sessions will be disabled,  or just don't call `context.Session()`.

**Comment by kataras** [comment]
Iris' sessions is one of the best implementations in the Golang world, 'why the hell' will you ever need to replace it? Btw, if you want to use your own stuff, it is possible with iris, pass an empty cookie name:  `iris.Config.Sessions.Cookie = " "` and sessions will be disabled,  or just don't call `context.Session()`.
You're welcome!

**Comment by kataras** [comment]
Iris' sessions is one of the best implementations in the Golang world, 'why the hell' will you ever need to replace it? Btw, if you want to use your own stuff, it is possible with iris, pass an empty cookie name:  `iris.Config.Sessions.Cookie = ""` and sessions will be disabled,  or just don't call `context.Session()`.
You're welcome!

**Comment by kataras** [comment]
Iris' sessions is one of the best implementations in the Golang world, 'why the hell' will you ever need to replace it? Btw, if you want to use your own stuff, it is possible with iris, pass an empty cookie name:  `iris.Config.Sessions.Cookie = ""` and sessions will be disabled,  or just don't call `context.Session()`.
You're welcome!

> Star Iris if you liked to be notified for updates, and close this issue if  the questions is answered, thanks!

**Comment by kataras** [comment]
Iris' sessions is one of the best implementations in the Golang world, 'why the hell' will you ever need to replace it? Btw, if you want to use your own stuff, it is possible with iris, pass an empty cookie name:  `iris.Config.Sessions.Cookie = ""` and sessions will be disabled,  or just don't call `context.Session()`.
You're welcome!

> Star Iris if you like to be notified for updates, and close this issue if  the questions is answered, thanks!
