### ISSUE TITLE
Acl middleware

### ISSUE THREAD

**Issue by ekoome** [kataras/iris#333]
Is it possible to add acl middleware akin https://github.com/OptimalBits/node_acl

**Comment by kataras** [comment]
Yes, you can create a custom middleware and pass it using ` iris.Use` or `iris.UseFunc`, you're welcome to create it and pull a request to the [middleware repository](https://github.com/iris-contrib/middleware) or host it at your own repository and give me the link to share it!

**Comment by ekoome** [comment]
Just started learning Golang, so may not be any good. Looking to rewrite my nodeJS app which uses the nodeacl middleware in GO.
