### ISSUE TITLE
bad file descriptor

### ISSUE THREAD

**Issue by zulmaster** [kataras/iris#336]
Some times get in logs:
2016/08/02 18:13:03 error when serving connection "xxxx:80"<->"xxxx:57118": write tcp4 xxxx:80->xxxxx:57118: write: bad file descriptor
And request does not complete. Why its happen?

**Comment by kataras** [comment]
I never got this message, please provide more information

**Comment by zulmaster** [comment]
what's kind information do u need?

**Comment by kataras** [comment]
I can't help if I don't know the version of iris, the code snippet, the operating system, the version of your valyala/fasthttp, btw forget these, just open an issue on [fasthtt](https://github.com/valyala/fasthttp/issues) this is not an iris issue as I can see from the logs, but thanks for reporting that!
