### ISSUE TITLE
Can we provide chinese document?

### ISSUE THREAD

**Issue by wednesdaysunny** [kataras/iris#338]
Excuse me, can we provide chinese document? If so, it is more conducive to the spread of Iris.

**Comment by kataras** [comment]
I don't know any chinese  and google translate will not do the job, we need people who know chinese to do the [book](https://github.com/iris-contrib/gitbook) translation, already a translation for `FR` is coming from a community member, if you want to translate the book to chinese, create a folder with the `CH` and make a [pull request](https://github.com/iris-contrib/gitbook/pulls) the chinese `*.md`
