### ISSUE TITLE
suggestion: replace fasthttp with net/http?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#339]
the following is only my opinion.

1. You should not awlays seek for the fastest webframek.  this is all so unnecessary.

2. sometime the net/http is more ```Stable```  and ```maintainable``` than fasthttp.

3.some features are more easy achieved than fasthttp,  such as http2.

why not do a try?

**Comment by kataras** [comment]
Iris v1 was the fastest net/http, fasthttp is faster, I wanted to create a framework which will be faster, not only for Go, and I did it, we did it, if you want net/http web framework, I am preparing a new framework(with different and unique structure) it will be an experimental I will send you the link on the private chat when I publish it

**Comment by kataras** [comment]
@xpbliss Check [Q web framework](https://github.com/kataras/q) Iris' features for net/http fans :)

**Comment by kataras** [comment]
@xpbliss Iris supports http/2 now :) Take a look here: https://github.com/kataras/iris/issues/565
