### ISSUE TITLE
support for built-in JSON schema validation

### ISSUE THREAD

**Issue by typekpb** [kataras/iris#341]
I'd love to validate the incoming JSON with JSON schema.
There seem to be golang implementation available (https://github.com/xeipuuv/gojsonschema). However I'd love to have iris built-in option for that 
Currently I'm using for unmarshalling method:
```
func (ctx *Context) ReadJSON(jsonObject interface{}) error {
```
Any chance for providing the new method with additional argument referring the JSON schema, or do you suggest some other way to achieve that?

**Comment by kataras** [comment]
This discussion has already be done by the community, and we decided  that is not needed to be added to iris. becaise it's very easy to use third-party libraries with Iris, keep things as simple as possible. But thanks for your interest, keep going!
