### ISSUE TITLE
Add default route

### ISSUE THREAD

**Issue by malstoun** [kataras/iris#345]
Hi

I reserve `/f/` folder for my static files and I want to handle other routes by one handler.

It would be great if I could write something like this:

```go
server.Static("/f/", "./static/", 0)
server.Handle("GET", "/*path", &get.GetHandler{})
```

or this:
```go
server.Handle("GET", "/f/", &get.FilesHandler{})
server.Handle("GET", "/*path", &get.GetHandler{})
```

The first route is more specific, so the router should use it instead of wildcard.

Also you forgot error handling [here](https://github.com/kataras/iris/blob/master/http.go#L926) and [here](https://github.com/kataras/iris/blob/master/http.go#L938).

Thanks.

**Comment by kataras** [comment]
Hi, this you asking has been discussing many times at the past, and I'm not willing to change these, you cannot have wildcard or :param with a static path at the same path, this is by design, it really force you to build better routes for your web app, but thanks for your recommendations, keep going!

> Also don't forget to star Iris and iris-contrib/examples to be notified for any future updates!

**Comment by malstoun** [comment]
The problem is I don't choose routes and I don't know (in code) what routes exist, so it's not force me at all. It's not an app, it's a site. Managers can create any route that they think would be nice and change it three times a day. So, routes are dynamic. I can select 5k routes from db and bind handlers to them or make some workarounds, but it looks bad at least when wildcards exist. And what would be with a speed if I do that?..

But I heard you, thanks for the answer.

**Comment by kataras** [comment]
We will have router-performance cost if we do that you're asking for, you can still bind your database routes with a wildrcard `/*site` . You can still do whatever you want with routes, just add an `if statement` inside your `wildcard handler`.

**Comment by kataras** [comment]
We will have router-performance cost if we do that you're asking for, you can still bind your database routes with a wildrcard `/*site` . You can still do whatever you want with routes, just add an `if statement` inside your `wildcard handler`. 

>  I don't choose routes and I don't know (in code) what routes exist

Yes you know, name your routes ( [docs section here] (https://kataras.gitbooks.io/iris/content/routing.html)) and try `iris.Lookups() which returns []Route `&& `iris.Lookup(routeName string)`
