### ISSUE TITLE
How to refresh the template html files?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#346]
1. when iris started, the html files was loaded?
but when i  modified  some  template-html files in the web ui,  and how to the refresh them,  and let them make  effect?

2. ```iris.TemplateString("form.html", data)```, 
 how to make the ```form.html``` to be an absolute path ```d:/examples/form.html``` and not to set the ```template Directory```?

**Comment by kataras** [comment]
> when iris started, the html files was loaded?
but when i modified some template-html files in the web ui, and how to the refresh them, and let them make effect?


Yes templates are loaded when the iris is listening to the server, you can set the `iris.Config.IsDevelopment = true` to load templates on each request (if you edit them they will be refreshed too), as the [book section](https://kataras.gitbooks.io/iris/content/template-engines.html) and examples shown, you already made this question on another thread, please remember the answers I give to you or just read the book..

> iris.TemplateString("form.html", data),
how to make the form.html to be an absolute path d:/examples/form.html and not to set the template Directory?

You cannot

**Comment by kataras** [comment]
> when iris started, the html files was loaded?
but when i modified some template-html files in the web ui, and how to the refresh them, and let them make effect?


Yes templates are loaded when the iris is listening to the server, you can set the `iris.Config.IsDevelopment = true` to load templates on each request (if you edit them they will be refreshed too), as the [book section](https://kataras.gitbooks.io/iris/content/template-engines.html) and examples shown, you already made this question on another thread, please remember the answers I give to you or just read the book..

> iris.TemplateString("form.html", data),
how to make the form.html to be an absolute path d:/examples/form.html and not to set the template Directory?

You cannot do that with one template engine, but you can specify a new template engine (with different extension than the first) with the `d:/examples/` as the directory and use that template engine to parse this file

**Comment by xpbliss** [comment]
1.which is latest? Iris.com or  https://kataras.gitbooks.io/iris?
2. and for log, Which is more latest? ctx.Log, ? ris.Logger ?  https://github.com/iris-contrib/logger?

Thanks!

**Comment by kataras** [comment]
> 1.which is latest? Iris.com or https://kataras.gitbooks.io/iris?

Both are the latest, but I recommending you reading from gitbook at the future, if you are ok with graphics there.

> 2. and for log, Which is more latest? ctx.Log, ? ris.Logger ? https://github.com/iris-contrib/logger?

what do you mean letest? Both `ctx.Log` and `iris.Logger` does the same job, `ctx.Log(string,...interface)` calls the `iris.Logger.Printf(string,...interface)`

**Comment by kataras** [comment]
> 1.which is latest? Iris.com or https://kataras.gitbooks.io/iris?

Both are the latest, but I recommending you reading from gitbook at the future, if you are ok with graphics there.

> 2. and for log, Which is more latest? ctx.Log, ? ris.Logger ? https://github.com/iris-contrib/logger?

what do you mean letest? Both `ctx.Log` and `iris.Logger` does the same job, `ctx.Log(string,...interface)` calls the `iris.Logger.Printf(string,...interface)` **Source code is open :P **
