### ISSUE TITLE
Forcefully closing a web socket connection

### ISSUE THREAD

**Issue by GeorgeLyon** [kataras/iris#348]
As far as I can tell, there is no way to close a web socket connection server-side. Is there something I'm missing? Is this left out of the API on purpose?

**Comment by kataras** [comment]
Ok upgrade your iris `go get -u github.com/kataras/iris` , the **connection**'s method is: `Disconnect()` which returns an error if something 'bad' happened.  Could you please verify that is working?

**Comment by GeorgeLyon** [comment]
LGTM
