### ISSUE TITLE
iris didn't crash when starting web server on occupied port

### ISSUE THREAD

**Issue by linuxerwang** [kataras/iris#349]
Hi, I am using iris v3. I found that when a port has been occupied by other services, iris will not crash. Instead, it seemed started normal, although it did not really work. The document says it will panic but didn't.

> // **It panics on error** if you need a func to return an error, use the ListenTo
> // ex: err := iris.ListenTo(":8080","yourfile.cert","yourfile.key")
> ListenTLS(addr string, certFile string, keyFile string)

This happens for both http and https. As a comparison, net/http returns error correctly.

Thanks.

**Comment by kataras** [comment]
Hello @linuxerwang, I get a panic correctly, try to upgrade your iris to v4, at the next days it will be the stable version. [HISTORY](https://github.com/kataras/iris/blob/master/HISTORY.md), [new docs](http://iris-go.com) and new [examples](https://github.com/iris-contrib/examples) will help you to fill the gaps from the conversion
```go
panic: listen tcp4 0.0.0.0:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally
 permitted.

goroutine 1 [running]:
```

**Comment by linuxerwang** [comment]
Thanks, kataras

I'd rather wait for v4 to be in stable. Also, I feel that the incompatible versions are released too fast, v3 is released less than a month ago. Hope the APIs can be a little more stable from change.

**Comment by kataras** [comment]
Yes , 4 versions released on 4 months, each month new release, but v4 will stay for a much longer time, have fun!

**Comment by linuxerwang** [comment]
Cool! Looking forward to v4.

**Comment by kataras** [comment]
Don't except big changes, the framework will not change, I just still waiting for new bug reports to fix, if any
