### ISSUE TITLE
support for http 2

### ISSUE THREAD

**Issue by hydroflame** [kataras/iris#352]
I love the project but I'd love to see http/2 support for it. Thank you for your time.

**Comment by kataras** [comment]
Dublicated post but I will answer. Support for http2 depends on fasthttp. Its a TODO. If you want http2 support, today, then take a look on [this framework](https://github.com/kataras/q). Thank you for your comment

**Comment by hello-code** [comment]
Why

>  "Support for http2 depends on fasthttp"

?
I love iris! But she do not support http/2! Too sad... When are you support http/2?
Thanks for your great job!

**Comment by kataras** [comment]
@hydroflame Iris supports http/2 now :) Take a look here: https://github.com/kataras/iris/issues/565
