### ISSUE TITLE
While set MaxBodySize, upload file bigger than the limit, the connection will be reset.

### ISSUE THREAD

**Issue by netroby** [kataras/iris#353]
While set MaxBodySize, upload file bigger than the limit, the connection will be reset.
How to catch this error, then display a message to user, tell them do not post file larger than the limit. not just reset connections. thanks.

```

2016/08/10 16:32:36 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34904": body size exceeds the given limit
2016/08/10 16:32:36 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34906": body size exceeds the given limit
2016/08/10 16:32:51 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34910": body size exceeds the given limit

```

**Comment by kataras** [comment]
Could you please open an issue to the [fasthttp](https://github.com/valyala/fasthttp) in order to discuss it there?  We have to make a pr there, this is an fasthttp internal error

**Comment by netroby** [comment]
I am not quite understand how it works. so i can not post the right question. can you help explain it for me ?

**Comment by kataras** [comment]
How you post it there? Do the same in fasthttp repo, I will help you after your post
