### ISSUE TITLE
Wrong redirect with relative path for https 

### ISSUE THREAD

**Issue by linuxerwang** [kataras/iris#355]
On Iris 3/4, the iris.Redirect("/home") redirects to http:// instead of https:// when the webserver is using https.  This behavior is different from net/http. I think it's better to be the same as net/http, and it's very convenient for developers. That is, when scheme is not specified in the path, take the scheme of the current webserver automatically. 

Thanks.

**Comment by kataras** [comment]
This is a bug, it should redirect to https:// if you listen with ListenTLS/ListenTLSAuto

**Comment by kataras** [comment]
No, you did something wrong, could you please give us a snippet of your code?, I tested it with:

```go
// Package main provide one-line integration with letsencrypt.org
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Write("Hello from SECURE SERVER!")
	})

	iris.Get("/test2", func(ctx *iris.Context) {
		ctx.Write("Welcome to secure server from /test2!")
	})

	iris.Get("/redirect", func(ctx *iris.Context) {
		ctx.Redirect("/home")
	})

	iris.Get("/home", func(ctx *iris.Context) {
		ctx.Write("Hello from %s", ctx.PathString())
	})

	// This will provide you automatic certification & key from letsencrypt.org's servers
	// it also starts a second 'http://' server which will redirect all 'http://$PATH' requests to 'https://$PATH'
	iris.ListenTLSAuto("127.0.0.1:443")
}

```

**Comment by linuxerwang** [comment]
Thank you. I am going to create an issue for fasthttp.

**Comment by kataras** [comment]
@linuxerwang Fixed internally, you can just update iris and it should be OK now.

fasthttp is not fixed yet, but I understood where was the issue ( on FullURI it was returned with `http://...` instead of `https://` even if `IsTLS` was true), I'll add a PR and tests there when I find some time.

**Comment by linuxerwang** [comment]
Thank you, kataras! I verified that your latest commit fixed the problem!
