### ISSUE TITLE
use custom session(s) in websocket

### ISSUE THREAD

**Issue by TsumiNa** [kataras/iris#358]
Hi, I'm planning to using iris for my recently project and did some test follow the example. I want to use session in websocket connection to trace user info but iris session relay on the `iris.Context` so i can't got a session instance outside a route.

Are there some way to get the session anywhere and create a session with custom key like iris did with `irissessionid`. 😄

**Comment by kataras** [comment]
`iris.Config.Sessions.Cookie = "mysessionid"` , Session manager is only available by context, you cannot get current session without the client's session's cookie's value, so practically you cannot use sessions outside of Context. You should find other way to deal with it, websocket is not like http, so you shouldn't be confused with it

**Comment by TsumiNa** [comment]
thank your for answer! I will think about it

**Comment by kataras** [comment]
`*http.Request` access from Websockets

Example:

- https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34

Relative commits to kataras/go-websocket:

- kataras/go-websocket@550fc8b

- kataras/go-websocket@62c2d98

> use the `c.Request()` only when you really need it, websockets have everything you need already.
