### ISSUE TITLE
Resumable SendFile

### ISSUE THREAD

**Issue by pyrostrex** [kataras/iris#359]
First off, Iris is super cool!

Looking at `context.go`, currently `SendFile`, `ServeFile` and `ServeContent` does not seem to parse the `Range` Header resulting in a non-resumable file download. This is bad for users who are downloading a huge file with a slow internet speed. I really do hope to see this feature in Iris. Thank you so much!

**Comment by kataras** [comment]
This is already implemented by` ctx.RequestCtx.SendFile/ServeFile` read more https://github.com/valyala/fasthttp/issues/51

**Comment by kataras** [comment]
First of all thanks you for using it!!

This is already implemented by` ctx.RequestCtx.SendFile/ServeFile` read more https://github.com/valyala/fasthttp/issues/51

**Comment by pyrostrex** [comment]
Wow, I missed that! thanks!

**Comment by kataras** [comment]
No problem, I will try to compine my implementation with fasthttp's to make it more compatible with the common usage, as you suggested

**Comment by kataras** [comment]
No problem, I will try to combine my implementation with fasthttp's to make it more compatible with the common usage, as you suggested

**Comment by netroby** [comment]
The commmit befa43b break SendFile api.

**Comment by kataras** [comment]
What do you mean 'break' ? What's the issue, the docs or the SendFile itself? Please be more specific in order to help

**Comment by kataras** [comment]
What do you mean 'break' ? What's the issue, the docs (which they fixed this morning) or the SendFile itself? Please be more specific in order to help

**Comment by netroby** [comment]
SendFile API it self break.


so our old project can not compiled


获取 Outlook for Android






On Wed, Aug 31, 2016 at 1:21 AM +0800, "Gerasimos Maropoulos" <notifications@github.com> wrote:












What do you mean 'break' ? What's the issue, the docs (which they fixed this morning) or the SendFile itself? Please be more specific in order to help
