### ISSUE TITLE
No hints for the occupied port?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#36]
When a port  is occupied by another application,  and you run the iris on the port, then iris exit directly and no hints for the occupied port.

**Comment by xpbliss** [comment]
You are frequent  to update the iris.
When i go get -u.....,        the server did not work.
Something is wrong.

**Comment by kataras** [comment]
@xpbliss what you mean server didnt work?? you can't run iris ?

**Comment by xpbliss** [comment]
it is ok.  thanks!

**Comment by rohanthewiz** [comment]
I created a pull request to update the basic example in the README to use log.Fatal.
PR #37
