### ISSUE TITLE
automatic gzip compression must check accept-encoding header

### ISSUE THREAD

**Issue by snksoft** [kataras/iris#361]
I'm trying to use automatic compression enabled by iris.Config.Gzip = false

Found two issues with it:

1. It must check that "Accept-Encoding" is present and does contain "gzip" before compressing anything. The trouble is that despite all modern browsers support gzip encoding, that's not guaranteed and many libraries don't (e.g. http builder I use in automated tests written in groovy). And the rule is - server cannot use a Content-Encoding, unless it is allowed by the client in Accept-Encoding header.

2. Response should set ctx.SetHeader("Vary", "Accept-Encoding") if it does compression (really, if it uses any Content-Encoding). This is required for it to play nicely with caches and accelerators. Just google for "header vary content-encoding", you'll find plenty of good explanations why.

**Comment by kataras** [comment]
Done, check the code and tell me if that's ok now, I already know these but thanks for trying to be so good person!

Notes: enabled by iris.Config.Gzip = false, you propably mean = `true`.

**Comment by snksoft** [comment]
Sorry for the delay. I'm on a branch. Had to finish and commit my stuff before I can play.

Yes, it all appears to be working properly now. Thanks.

**Comment by kataras** [comment]
Nice, you're welcome!
