### ISSUE TITLE
permission denied - ListenTLSAuto

### ISSUE THREAD

**Issue by dem-waffles** [kataras/iris#362]
Since ports below 1024 are priveleged, I'm unable to start an iris webserver using ListenTLSAuto because it fails to create the secondary webserver around line 485 in iris.go. The error message looks like this:
`➜  chat git:(master) ✗ go run server/server/server.go`
`listen tcp4 0.0.0.0:80: bind: permission denied`
`panic: listen tcp4 0.0.0.0:80: bind: permission denied`

Removing the line to start the secondary server on port 80 allows my server to start. Obviously, the same error occurs when you try to pass in a port lower than 1024 to the ListenTLSAuto function.
How should this be dealt with? I've tried changing the port of the secondary server to 8080, which causes it to not fail, but it doesn't redirect traffic from 8080 to (in my case) 8443.

**Comment by kataras** [comment]
If your machine doesn't allows port 443, then you can use the `iris.ListenTLS` to pass the certfile and keyfile manually, this is not an iris problem, you have to configure your machine like you do with other web servers & web frameworks

**Comment by kataras** [comment]
If your machine doesn't allows port 443, then you can use the `iris.ListenTLS` to pass the certfile, keyfile and binding port manually, this is not an iris problem, you have to configure your machine like you do with other web servers & web frameworks

**Comment by kataras** [comment]
If your machine doesn't allows port 443, then you can use the `iris.ListenTLS` to pass the certfile, keyfile and binding port manually, this is not an iris problem, you have to configure your machine like you do with other web servers & web frameworks. Look the multi_server examples on [this](https://github.com/iris-contrib/examples) repository to see how you can configure your secondary server which will redirect to your secure server
