### ISSUE TITLE
CSRF any plans?

### ISSUE THREAD

**Issue by akme** [kataras/iris#363]
Any plans to add CSRF checks?
Like:
https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/09.1.html
https://github.com/gorilla/csrf

**Comment by kataras** [comment]
Check [this iris-contrib middleware repository](https:://github.com/iris-contrib/middleware). If one of these doesn't suits your needs you can create and use a middleware, read more on the iris book. Thank you.
