### ISSUE TITLE
Is it possible to define a Party to handle all subpath requests?

### ISSUE THREAD

**Issue by linuxerwang** [kataras/iris#364]
Hi,

I am trying to map a URL pattern to a local folder which contains all markdown files. I tried this but not working:

iris.Party("docs", func(ctx *iris.Context) {
    ctx.MustRender(path, nil)
})

It doesn't work for this path: /docs/path/to/index.md.

Do I have to create parties specifically like this:

iris.Party("docs").Party("path").Parth("to").Get("/index.md")

Is there a better way to handle all subpaths?

Thanks.

**Comment by kataras** [comment]
Yes, first [read the docs](http://iris-go.com) before posting a new issue to the github repository, you can always [chat](https://kataras.rocket.chat/channel/iris) with the community if for some reason you are not able to read the book, community will guide you!

Quick answer: 
- You don't need Party, parties are for route grouping, but I think you just need a segment to know what is the path after the `/docs` , so you will need a wildcard path, **answer**: 
```go
iris.Get("/docs/*path", func(ctx *iris.Context){
    path:= ctx.Param("path") 
    ctx.MustRender(path, nil) // or path+".md" if you don't want suffix on your route.
})
```

-  `func(ctx...` on .`Party` is the middleare for the party's routes, no the handler, it will never work if you just use `iris.Party` you have to use something like: `myparty := iris.Party("/users",...) ` ` myparty.Get("/signin"...)`, read the docs please.

Thank you, keep going!

**Comment by linuxerwang** [comment]
Great, didn't realize there is a chatting channel. Thanks.

I did skim the documents but didn't find examples for wildcard path. Maybe I missed it.

**Comment by kataras** [comment]
Great, there's a section (one of the firsts) talking a little about wildcards, did your problem solved, is that the correct answer for you my friend?

**Comment by linuxerwang** [comment]
In this documentation I didn't find the wildcard section: http://iris-go.com/.

For my problem, the *path trick worked well. But I wonder what if I need a partial match like "*.html", "abc*.html", or "test.*"? Also, "*path" is confusing, I thought it matches "apath", "bpath", but turned out it matches any string. It might be better to use a normal wildcard "*", isn't it? Or alternatively iris can add support for regex?

I also have questions about the markdown renderer, I'll ask in the chat channel later.

Thanks for the help!

**Comment by kataras** [comment]
> In this documentation I didn't find the wildcard section: http://iris-go.com/.

http://iris-go.com/named_parameters/

> Or alternatively iris can add support for regex?

No, regex are very slow, someday I will add an option to override the default iris' router and set your own, optionally, so then you will be able to make something like this, but for your particular 'problem' the regex is not the only solution, you can add the regex inside the wildcard route's handler and send 404 if the *path is not passed the regex compilation, think and you will find the answer, it's not a big deal it's easy.

> I also have questions about the markdown renderer

About markdown search for answer [here](https://github.com/russross/blackfriday) , thank you!!

**Comment by kataras** [comment]
> In this documentation I didn't find the wildcard section: http://iris-go.com/.

http://iris-go.com/named_parameters/

> Or alternatively iris can add support for regex?

No, regex are very slow, someday I will add an option to override the default iris' router and set your own, optionally, so then you will be able to make something like this, but for your particular 'problem' the regex is not the only solution, however you can add the regex inside the wildcard route's handler and send 404 if the *path is not passed the regex compilation, think and you will find the answer, it's not a big deal it's easy.

> I also have questions about the markdown renderer

About markdown search for answer [here](https://github.com/russross/blackfriday) , thank you!!

**Comment by linuxerwang** [comment]
I see, so "*" is the wildcard and "path" give it a name. Now I understand. Thanks for the link.
Agree with the slowness of regex. I can accept the way iris takes.
Thanks, man!

**Comment by kataras** [comment]
You're welcome,  thanks for using Iris!
