### ISSUE TITLE
Multiple websockets error (Middleware were already registered)

### ISSUE THREAD

**Issue by bluedaniel** [kataras/iris#365]
I'm currently getting the following error when trying to setup 2 websockets, although it might be how I'm setting them up.

`Error: Router: Middleware were already registered for the path: '/iris-ws.js'`

Is this is the simplest example of multiple websockets?

````go
api := iris.New()

w := iris.NewWebsocketServer(&config.Websocket{Endpoint: "/my_endpoint"})
iris.RegisterWebsocketServer(api, w, api.Logger)

w2 := iris.NewWebsocketServer(&config.Websocket{Endpoint: "/another_endpoint"})
iris.RegisterWebsocketServer(api, w2, api.Logger)

api.Listen("0.0.0.0:8000")
````

**Comment by kataras** [comment]
You can still create new Iris instance and bind that to the new webocket server, but wait I will fix this issue

**Comment by kataras** [comment]
@bluedaniel Ok, fixed, could you, please, verify that is working now ?

**Comment by macnibblet** [comment]
Is this still possible, I cannot find the RegisterWebsocketServer method ?
