### ISSUE TITLE
StaticServe doesn't work in root directory

### ISSUE THREAD

**Issue by peterbe** [kataras/iris#366]
I have this:
```go
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		log.Fatal("$PORT must be set")
	}
	debug := os.Getenv("DEBUG")
	irisConfig := config.Iris{
		IsDevelopment: debug == "true",
	}
	api := iris.New(irisConfig)
	api.Get("/tree", TreeInfo)
	api.Post("/tree", Tree)
	api.Static("/static", "./dist/static/", 1)
	// api.StaticWeb("/", "./dist", 0)
	api.StaticServe("./dist")
	api.Listen("0.0.0.0:" + port)
}
```

And in the same directory there's a `./dist/` that contains `index.html` and `google-analytics.html` amongst other things. There's also a `static/foo.jpg`.

So these URLs work:
```
curl http://localhost:5000/static/foo.jpg
curl http://localhost:5000/tree
```
But these do not:
```
curl http://localhost:5000/
curl http://localhost:5000/google-analytics.html
```

(the file `./dist/index.html` contains AngularJS code so it's trouble trying to render)

When I load `http://localhost:5000/` it returns a `404 Not Found` with a body that just says "Not found". 

There's nothing in the console to indicate if I have a typo or something.

**Comment by peterbe** [comment]
When I mess with it and change it to 
```go
api.StaticWeb("/foo", "./dist", 0)
```
I at least get some errors in the console stdout. For example...:
```
2016/08/16 14:44:08 0.000 #0000000300000001 - 127.0.0.1:5000<->127.0.0.1:50704 - GET http://localhost:5000/foo/ - cannot open file "./dist/foo": open ./dist/foo: no such file or directory
```

**Comment by kataras** [comment]
StaticServe serves files from `./dist` directory, for the request path `127.0.0.1:5000/dist/anyfilehere` no from root directory,  you have setspecify the second,  optional, parameter to change the request path

**Comment by peterbe** [comment]
Oh right. That explains it. I wrote a [custom view function](https://github.com/peterbe/go-htmltree/blob/a5679cc4a9c2886f168c6bb92ef738f7cb233408/main.go#L177-L183) for `/`  and that worked.
