### ISSUE TITLE
Websocket panic on non-websocket connection

### ISSUE THREAD

**Issue by brentnk** [kataras/iris#367]
If you attempt to connect to a websocket endpoint eg. `localhost:8080/my_endpoint` with a web browser or curl iris panics bringing down the whole application.  
Is this intended?  If so, what is the preferred way of catching this. 

Thanks for the great library,
Brent

**Comment by kataras** [comment]
This is not by design, for sure, I didn't noticed so far no one told me before, I'll fix it and will response back , thanks you

**Comment by kataras** [comment]
This is not by design, for sure, I didn't noticed so far no one told me before, I'll fix it and will response back , thanks

**Comment by kataras** [comment]
It was totally my false, fixed, thank you!!

**Comment by brentnk** [comment]
Thank you sir for the good work!

**Comment by kataras** [comment]
Thank you, I have to note something, Iris is an active-development project so if you want to receive updates please star/or/and watch the [iris](https://github.com/kataras/iris/stargazers) repository, the [book](https://kataras.gitbooks.io/iris/) and the [examples](https://github.com/iris-contrib/examples) repository
