### ISSUE TITLE
iris binary file

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#369]
Hi, @kataras  I'm glad you develop the project!

My problem:

I use [gom](https://github.com/mattn/gom) and after I install the framework, create the file **vendor/bin/iris**. You can disable this feature by default, because they do not want this file to add to your git.

**Comment by kataras** [comment]
Hello @egorsmkv , thank you,

Can you explain me what you want from me to do? I didn't understand the question or the suggestion

**Comment by egorsmkv** [comment]
1) For project management I use Git.
2) The Gom project creates a folder vendor/ which contains the connection library projects, including the Iris.
3) As Iris creates a binary file, it creates unnecessary for me the folders: vendor/bin and vendor/pkg (it contains the compiled library files)
4) Created utility I don't use, so you can somehow disable its creation and I should just add these two folders to .gitignore?

**Comment by kataras** [comment]
Iris is a web framework not a cmd library, it contains a cmd library to integrade with Iris but it's optionally.

Try to pass the `github.com/kataras/iris`  instead of `github.com/kataras/iris/iris`, tell me if that works on you.

**Comment by kataras** [comment]
Iris is a web framework not a cmd library, the repository's folder `/iris` contains a cmd library to integrate with Iris but it's optionally.

Try to pass the `github.com/kataras/iris`  instead of `github.com/kataras/iris/iris`, tell me if that works on you.

**Comment by egorsmkv** [comment]
See asciicast https://asciinema.org/a/978ysordl2fv8ecjco04935b3

**Comment by kataras** [comment]
I cannot help on this, this is not an Iris issue, propably gom is searching for subdirectories, but why is that a problem, just remove the `/iris` subfolder and make a `gom install` again, if it makes a `./bin/iris` again then it's a gom's bug and you should post an issue there, not here, thank you!!
