### ISSUE TITLE
Compress and resize logotype in documentation

### ISSUE THREAD

**Issue by egorsmkv** [kataras/iris#370]
```
<div class="banner">
      
        <div class="logo">
          <img src="http://iris-go.com/images/logo.png">
        </div>
      
      <div class="name">
        <strong>Iris - Documentation <span class="version">4.0.0-alpha.5</span></strong>
        
          <br>
          kataras/iris
        
      </div>
    </div>
```

http://iris-go.com/images/logo.png very big file, please add small version for documentation pages.

**Comment by kataras** [comment]
Hello @egorsmkv Is that a propert issue post for github? you know that we have chat, also you know that logo has its own [repository](https://github.com/iris-contrib/logo) and the [website](https://github.com/iris-contrib/website) also, please make a pr there and I will approve it. This page is for github issues specific to bug/suggestion for iris web framework itself, thank you!
