### ISSUE TITLE
g-zip compression applied inconsistently

### ISSUE THREAD

**Issue by bekite** [kataras/iris#371]
I have several scenarios where gzip compression is applied differently.

1. ctx.WriteString() does not compress the data. Is this intended?
```go
// enable gzip compression
iris.Config.Gzip = true
// in a handler function
ctx.WriteString("some random string")
```
2. ctx.JSON() does always compress the data regarding its size. Small data is getting bigger when compressed.
```go
// enable gzip compression
iris.Config.Gzip = true
// in a handler function
ctx.JSON(iris.StatusOK, someStruct)
```

3. Static file server with compression
```go
iris.Get("/static/*file", iris.StaticHandler("./static", 1, true, false, nil))
```
This is working like intended. Only "larger" files are compressed.
You should mention this in the docs maybe and add an example on how to use StaticHandler.
I was confused at first, because I expected the file server to compress all files regarding its size.
``` ctx.ServeFile("./static/index.html", true) ``` is compressing the file ignoring its size, but the file server did not compress it.

It would be best if only "larger" files were compressed.

**Comment by kataras** [comment]
Yes, you have right it would be better, but slower also, this is the reason iris doesn't provides this, however it's very easy to do that by yourself. If you want to use gzip on very small, sized, files then you should manually check the size before using gzip, you can disable gzip on all `JSON/JSONP/XML/Text/Data/Markdown` and all templates passing an `iris.Map{"gzip": false}` as third parameter on `ctx.Render` or `ctx.JSON/JSONP/XML/Text/Data/Markdown` funcs. Thank you!!

**Comment by bekite** [comment]
Thank you for the fast answer. But I have still some issues left.

So if it's faster to not check the file size before gzipping it, why is StaticHandler checking it?
Would it not be better to disable the file size checking and gzip small files too to boost performance?

Sorry, but I couldn't find the answer to why ctx.WriteString() is not gzipping the data.

Thank you for your suggestion with passing iris.Map{"gzip": false} as the third parameter. But somehow I get the "too many arguments in call to ctx.JSON" error.
```ctx.JSON(iris.StatusOK, someStruct, iris.Map{"gzip": false})```

**Comment by kataras** [comment]
Because StaticHandler compress the files BEFORE serve them as zip. This is the best way to serve big files. As for your second question , try to use 'ctx.Render("application/json", yourstruct,iris.RenderOptions{"gzip":false})'
