### ISSUE TITLE
gzip for dynamic content

### ISSUE THREAD

**Issue by typekpb** [kataras/iris#373]
It might be obvious to others, however I'm still a bit lost here. How should I serve my dynamic content in a gzipped way?

Currently I have something similar to:
```
func IrisAPI() *iris.Framework {
	api := iris.New()
	api.Post("/api/schemas/:id", func(ctx *iris.Context) {
             ctx.Text(iris.StatusOK, "foo")
	})
	return api
}

func main() {
	IrisAPI().Listen(":9292")
}
```

what should I use instead of `ctx.Text` to get gzip compression in play? I've seen somewhere in a code hint to use:
```
ctx.ResponseWriter.WriteString
```
but didn't figure it out.

In the best case I'd expect also headers to be set (automagically) and gzip to happen only if it is acceptable by client.

**Comment by kataras** [comment]
It happens only if it's acceptable already, you don't have to do anything for that, you can enable globla gzip with `iris.Config.Gzip = true` and disable for specific render actions using `context.Render("text/plain", "my text", iris.RenderOptions{"gzip": false"})` . Please read the book all these is written [there](https://www.gitbook.com/book/kataras/iris/details)

**Comment by kataras** [comment]
First of all gzip is disabled by default, you can enable global gzip with `iris.Config.Gzip = true`.

> In the best case I'd expect also headers to be set (automagically) and gzip to happen only if it is acceptable by client.

It happens only if it's acceptable by client, already, you don't have to do anything for that, you can also disable for specific render actions using `context.Render("text/plain", "my text", iris.RenderOptions{"gzip": false"})` . Please read the book all these is written [there](https://www.gitbook.com/book/kataras/iris/details)

**Comment by kataras** [comment]
First of all gzip is disabled by default, you can enable global gzip with `iris.Config.Gzip = true`.

> In the best case I'd expect also headers to be set (automagically) and gzip to happen only if it is acceptable by client.

It happens only if it's acceptable by client, already, you don't have to do anything for that, you can also disable for specific render actions using `context.Render("text/plain", "my text", iris.RenderOptions{"gzip": false"})` . Please read the book all these is written [there](https://www.gitbook.com/book/kataras/iris/details)

If you want to serve static file with gzip use the `iris.Static...` functions, see the book for details. If you want to make a custom gzip writer, just go to the source code, look how I'm doing this and do the same. Thanks!!
