### ISSUE TITLE
When I create a local copy of the sample apps I receive: panic: template: help_message:10: illegal number syntax: "-"

### ISSUE THREAD

**Issue by mikepc** [kataras/iris#374]
Here's the full stack:

panic: template: help_message:10: illegal number syntax: "-"

goroutine 1 [running]:
github.com/kataras/iris.init.2()
       	/Users/michael/code/go/src/github.com/kataras/iris/ssh.go:249 +0x394
github.com/kataras/iris.init()
       	/Users/michael/code/go/src/github.com/kataras/iris/websocket.go:957 +0xa5e
main.init()
       	/Users/michael/code/go/src/bitbucket.org/frobl/overmind/main.go:13 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
       	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [sleep]:
time.Sleep(0x3b9aca00)
       	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/time.go:59 +0xf9
github.com/valyala/fasthttp.init.1.func1()
       	/Users/michael/code/go/src/github.com/valyala/fasthttp/header.go:1372 +0x20
created by github.com/valyala/fasthttp.init.1
       	/Users/michael/code/go/src/github.com/valyala/fasthttp/header.go:1375 +0x30

goroutine 34 [syscall]:
os/signal.loop()
       	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
       	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 36 [select]:
github.com/kataras/iris.(*websocketServer).serve(0xc820207130)
       	/Users/michael/code/go/src/github.com/kataras/iris/websocket.go:190 +0xe27
created by github.com/kataras/iris.newWebsocketServer
       	/Users/michael/code/go/src/github.com/kataras/iris/websocket.go:138 +0x3e8

Source:
`package main

import "github.com/kataras/iris"

func main() {
       	api := iris.New()
       	api.Get("/hi", hi)
       	api.Listen(":4321")
}

func hi(ctx *iris.Context) {
       	ctx.Write("Hi %s", "iris")
}`

**Comment by mikepc** [comment]
I upgraded to version 1.7 of Golang and it solve the problem. Ouch. I hope the rest of my stuff runs under 1.7 :\

**Comment by kataras** [comment]
Hmm, that's weird I have 1.6 it's running without panics, the ssh.go's template help message is produce the error to you, I will remove dashes to be 100% sure that will not produce any panics to other people, thank you
