### ISSUE TITLE
OPTIONS preflight 404

### ISSUE THREAD

**Issue by bluedaniel** [kataras/iris#375]
Getting the error for `Access-Control-Allow-Origin` when using the CORS middleware for `api.Party`. 

Seems to be an OPTIONS preflight only issue as GET requests work just fine.

The sample code I'm using is:

````go
apiRoot := api.Party("/api")
    {
    apiRoot.Use(cors.New(cors.Options{
        AllowedOrigins:   []string{"*"},
        AllowedMethods:   []string{"GET", "PATCH", "PUT", "POST", "DELETE", "OPTIONS"},
        AllowedHeaders:   []string{"Origin", "Authorization", "Content-Type", "Accept"},
        AllowCredentials: true,
        Debug:            true,
    }))
    // Define api routes
    apiRoot.API("/signup", endpoints.xxx{})
    ...
````

**Comment by kataras** [comment]
You have to use iris.Any, only .Get supports OPTIONS by default. Please search the 
already post issues and you will find the answer. This post is duplicated.

**Comment by intoxicated** [comment]
Ok, i get that you implement options for get method and any, but what about other methods like post and put?

**Comment by kataras** [comment]
`.Any` means `.Post,.Get,.Options,.Put,.Head,.Connect,.Delete...` you do the same for .Post preflight also or just `iris.Post("/path", handler)` `iris.Options("/path", handler)`
