### ISSUE TITLE
Could you add Captcha middleware for Iris?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#376]
I have not found a better Captcha middleware for Iris.

**Comment by kataras** [comment]
My job is not create every single feature you want for a web app, I'm sorry, you have to create for your own or search on the internet, an Iris middleware is just a `func(ctx *iris.Context){ /*implementation*/ ctx.Next()}`

**Comment by dxvgef** [comment]
Ok, thanks for your reply

**Comment by kataras** [comment]
It's better to let the community do something, I don't want to do all things alone, I hope you understand

**Comment by dxvgef** [comment]
Yes, I understand
