### ISSUE TITLE
Debate: x/net/websocket or gorilla/websocket

### ISSUE THREAD

**Issue by kataras** [kataras/iris#38]
Before Iris continue the work for the build'n websocket support via a middleware or a simple handler. Want to know which one do you use more, which one are you used to, which one you prefer to use [http://golang.org/x/net/websocket](http://golang.org/x/net/websocket) or the  [Gorilla's implementation: http://www.gorillatoolkit.org/pkg/websocket](http://www.gorillatoolkit.org/pkg/websocket) ?

**Comment by insionng** [comment]
The Gorilla's implementation maybe best!

**Comment by kataras** [comment]
Yeah I think it too, The gorilla maybe has awful router but their sessions and websockets are the best:)

**Comment by insionng** [comment]
IRIS may need a middleware like this: https://github.com/go-Macaron/Sockets

**Comment by kataras** [comment]
Yes, ofcourse via middleware , gorilla is a third party I can't add it to the build'n Iris. Build'n we will have the x/net/websocket and as middleware the gorilla's implemenatation or even better the 'socket.io' (maybe this is the final decision, we will see if anyone will comment here) and if anyone wants to use this must install the third party library too

**Comment by insionng** [comment]
I'm going to migrate my project(YOUGAM http://www.yougam.com/)  from the Macaron to IRIS. But Iris is currently missing some of the required components, such as websocket, internationalization, and the captcha.

**Comment by insionng** [comment]
captcha: https://github.com/go-macaron/captcha

**Comment by kataras** [comment]
Yeah I just saw your project I don't understand the language but I saw a lot of posts, very good!
Ok then today I will port the captcha and make the socket.io middleware, but for internationalization I must make the Iris to use static config files and this is not our priority right now but if you can help me on this issue it will be nice!

**Comment by insionng** [comment]
Recommended only the websocket as middleware.
Perhaps this more flexible instead of IRIS should be introduced in the core code.

**Comment by kataras** [comment]
What are you mean? no socket.io just raw websockets? this is already done ,what about capcha u dont want a middleware for this? ( take a look at the Plugins chapter at the documentation, I added this yesterday this will be help you what you can do to inject the Iris' flow)

**Comment by insionng** [comment]
I'm sorry that my native language is not English. so maybe I didn't clearly express what I mean.

**Comment by kataras** [comment]
Yeah me too, I'm from Greece :P so my eng is a little shit. I understand that you want middleware only for websocket no for capcha or for socket.io, and at your second sentence I understand that you mean you want iris to be flixble, which it's this is the reason we only have raw websocket without any third party

**Comment by insionng** [comment]
Now I hope the IRIS support internationalization, websocket, and captcha middleware.So I can migrate projects to the IRIS.

**Comment by kataras** [comment]
Yes this I understand at the first place but after I though you changed your mind, ok then I will do the weboscket and captcha today and if  I catch I'll do the internationalization also, but if you want and can help to make internationalization it will be nice

**Comment by insionng** [comment]
I currently use this middleware is the international https://github.com/go-Macaron/i18n

**Comment by insionng** [comment]
I will do all I can to assist you.

**Comment by kataras** [comment]
xmm I don't want to copy from other project But I could do this if you need this

**Comment by insionng** [comment]
Okay,Maybe you have a better way. Grateful!

**Comment by kataras** [comment]
Yes I just want examples on how you imagine these middlewares, code examples no how they are now but how you want to be

**Comment by insionng** [comment]
I wish they would just try to clear, simple, and easy to use.

**Comment by kataras** [comment]
I'll do my bests thanks you!

**Comment by kataras** [comment]
April 28 2016

Iris is using it's own custom sessions now
