### ISSUE TITLE
Disable caching of static files / wrong Content-Length header

### ISSUE THREAD

**Issue by luca-moser** [kataras/iris#382]
Hi Kataras.

I am facing a problem in my workflow, as I migrated from gin-gonic to iris. I've a Livereload setup, which automatically refreshes stylesheets/js files in the browser when I change them. My problem is, that iris seems to cache those files, so that it randomly sometimes still returns the old version of a file or returns the wrong `Content-Length` for the changed file.

workflow:
1. change in style.scss
2. compile style.scss to style.css through gulp
3. the Livereload servers calls the extension in the browser
4. browser tries to redownload/replace style.css from the go/iris webserver

Sometimes I get a `net::ERR_CONTENT_LENGTH_MISMATCH`  and sometimes I just get the old file.

In development mode, I use `engine.Static("/assets", "./frontend", 1)` and `engine.Config.Gzip = false` (just being explicit) to serve those static files. The `style.css` file in the example has file content in the file system. The `Content-Length` header has the same size as the previous http-request for the file, although the length has changed (hess the error).

Thanks for any help.

**Comment by luca-moser** [comment]
Using `"github.com/kataras/iris/config" StaticCacheDuration = time.Duration(0)` also does not fix the issue.

**Comment by luca-moser** [comment]
Ok, I fixed it. `fasthttp` automatically uses 10 second caching, if the set duration is 0. Now I am using `StaticCacheDuration = time.Duration(0)` and the problem doesn't occur anymore.

I think this should be noted somewhere.

**Comment by kataras** [comment]
>I think this should be noted somewhere.

Make a PR to the gitbook static files section, the repo is : https://github.com/iris-contrib/gitbook . thank you!

**Comment by luca-moser** [comment]
PR: https://github.com/iris-contrib/gitbook/pull/22
