### ISSUE TITLE
JWT middleware settings

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#384]
@kataras I try to implement the JWT middleware, but I encountered some problems. As when you generate the token you can set some params:
```go
jwt.StandardClaims{
	ExpiresAt: time.Now().Unix() + 60 * 60 * 24, // 1 day
	Issuer:    "test",
        ...
}
```

The middleware is doing checking for the ExpiresAt, but what about Issuer?
How does the middleware check for the Issuer and the other params (aud, jti, iat, iss, sub, etc.).
Is there a way to set these options in the middleware configs? Or I should somehow manually check for all these in another middleware?

**Comment by kataras** [comment]
This repository's issue is not the correct place, iris has nothing to do with JWT it's just a middleware for Iris, please ask it there: https://github.com/iris-contrib/middleware and someone will answer you, jwt middleware has a test file also, read it :)  thanks!!
