### ISSUE TITLE
Secure Websockets + HTTP TLS

### ISSUE THREAD

**Issue by Allendar** [kataras/iris#386]
καλησπέρα,

It looks like secure web sockets doesn't work based on the examples in the user guide.

I've cloned the [JS code](https://github.com/kataras/iris/blob/8f1bf8dcc766f2f21361635a89aa04e3695665dd/websocket.go#L742) in a custom file and changed the `ws://` check to `wss://`.

I'm running localhost over TLS on port 9443 with cert/key.

The result I'm now giving to the script is `wss://localhost:9443/sock_ep` (`m.Config.Websocket.Endpoint = "/sock_ep"`), but I'm not sure if that's OK?

Also I can't find any other things to set in `iris.config.Websocket` about possible certificates referencing.

Also I'm getting straight warnings/errors on the file itself:

```
jQuery.Deferred exception: ws.OnConnection is not a function. (In 'ws.OnConnection(function () {
		console.log('Websocket connection estabilshed');
	})', 'ws.OnConnection' is undefined) (2)
"https://localhost:9443/assets/js/chat.js:13:17
j@https://localhost:9443/assets/js/vendor/jquery.js:1189:27
https://localhost:9443/assets/js/vendor/jquery.js:1195:13"
undefined

TypeError: ws.OnConnection is not a function. (In 'ws.OnConnection(function () {
		console.log('Websocket connection estabilshed');
	})', 'ws.OnConnection' is undefined)
```

I'm using jQuery 3. Maybe that might be the cause; I'll try to figure that in the meanwhile.

**Comment by kataras** [comment]
Hello @Allendar, thanks for the greek word  which means good evening :)

Please search(look top) and read older post issues, this is already answered, you don' have to do anything special,  works with ssl automatically

**Comment by kataras** [comment]
Hello @Allendar, thanks for the greek word  which means good evening :)

Please search(look top) and read older post issues before posting a new issue, this is already answered, you don' have to do anything special,  works with ssl automatically

**Comment by Allendar** [comment]
I lived in Greece for a few months last year so I came by some Greek back then :)

I'll do some research on that tomorrow. Thanks for the tip!
