### ISSUE TITLE
Serving several domains with single instance

### ISSUE THREAD

**Issue by stunpix** [kataras/iris#388]
Iris has example of serving subdomains with single instance, but there no example for serving different domains in same way. I've tried `iris.Party`  (as in subdomains example), but without luck.

```go
func main() {
	serv := iris.New()

	host1 := serv.Party("localhost")
	host1.Get("/", func(c *iris.Context) {
		c.Write("Hi from localhost")
	})

	host2 := serv.Party("127.0.0.0")
	host2.Get("/", func(c *iris.Context) {
		c.Write("Hi from 127.0.0.1")
	})

	serv.Listen(":8080")
}
```

Can be this somehow achieved with current version of Iris?

**Comment by kataras** [comment]
`.Party` is for group routing and **subdomains**.

Iris supports unlimitted servers and domains with in single Iris instance. 
Go to multiserver examples [here](https://github.com/iris-contrib/examples/blob/master/multiserver_listening/main.go) you put each of the domains to the `ListeningAddr`  server's configuration field

**Comment by stunpix** [comment]
Thank you. Definitely what I need.
IMHO, multiserver example should be also tagged as multidomain solution, because this is not so obvious. My first thought was: it explains how to serve with different ports.

**Comment by kataras** [comment]
You're welcome!

If you think that something can be added or updated you're always free to do it, just go to the [iris-contrib/gitbook](https://github.com/iris-contrib/gitbook)  repo and make a PR I will approve it :)
