### ISSUE TITLE
SendFile api changed cause document and old project broken

### ISSUE THREAD

**Issue by netroby** [kataras/iris#390]
```
	SendFile(string, string)
```
The old project still using 

```
	SendFile(string, string) error

```

While compile project. golang will show error 

```
c.SendFile(file, "saveAsName.zip") used as value
```

http://iris-go.com/send_files/

so the code at the document should change to 

```
package main

import "github.com/kataras/iris"

func main() {

    iris.Get("/servezip", func(c *iris.Context) {
        file := "./files/first.zip"
        c.SendFile(file, "saveAsName.zip")
    })

    iris.Listen(":8080")
}

```

**Comment by kataras** [comment]
If you want to make changes on the book you ** are free to do  a PR**,  gitbook repo is: https://github.com/iris-contrib/gitbook , the website repo is: https://github.com/iris-contrib/website . Thanks for your notice but this is not a place to post these type of issues, we have other repository for the website and we've have a [chat](https://kataras.rocket.chat/channel/iris) too. I will fix it but next time please post the issue in the correct repository, thank you!!

**Comment by kataras** [comment]
Thanks, docs are fixed.

If you want to make changes on the book you ** are free to do  a PR**,  gitbook repo is: https://github.com/iris-contrib/gitbook , the website repo is: https://github.com/iris-contrib/website . Thanks for your notice but this is not a place to post these type of issues, we have other repository for the website and we've have a [chat](https://kataras.rocket.chat/channel/iris) too. Next time please post the issue in the correct repository, thank you!!
