### ISSUE TITLE
Plugin Error?

### ISSUE THREAD

**Issue by MaJie86** [kataras/iris#391]
It tell me a error about Plugin when i use the code in example.

"..\github.com\iris-contrib\plugin\iriscontrol\iriscontrol.go:149: not enough arguments in call to i.parent.Servers.OpenAll"。

My code is "	
iriscontrol.iris.Plugins.Add(iriscontrol.New(9090, map[string]string{
		"1":             "1",
		"irisusername2": "irispassowrd2",
	}))".

**Comment by kataras** [comment]
The issue has been solved

Please, next time post plugin issues here: https://github.com/iris-contrib/plugin
