### ISSUE TITLE
Websocket Join

### ISSUE THREAD

**Issue by omarseda** [kataras/iris#392]
Hello, noob here. Before continuing, I want to say sorry for my bad grammar, I cant speak English.
Actually this question is not about Iris, but rather than about websocket itself, since this is _my first touch with websocket_ world. I am asking it here because --practically-- i am going to do this by using Iris.

There is a method named `foo.Join("...")` as I saw in websocket example.

My questions are:

1. Can we call this method _more than once,_ with new room name? I mean this is something like `foo.Join(oldRoom) /*and then*/ foo.Join(newRoom)`

2. If we can, what is the condition of `foo` after that second call? Is `foo` now _subscribed_ both to `oldRoom` and `newRoom` (_aggregating_), or the condition of `foo` is now _subscribed_ only to the `newRoom` (_switching_), and leaving (unsubscribing) the old one?

    - If the case of Join is _aggregating_ , how can `foo` _unsubscribe_ from the old one? Is there any method, something like `foo.UnJoin(oldRoom)`?

    - If the case of Join is _switching_ , how can `foo` subscribe to more than one room? Something like `foo.JoinMore("...")`?

3. Is there any method to disconnect `foo` or any other connection from the server-side? This means
that in the client-side, client will receive `"OnDisconnect"` event, but of course this is not becaues we emit it, but we _force_ that particular connection to be closed? ... or ... do I have _no need_ to do this ...?

Im sorry, if this question is in the wrong place.
Thank You, and great work Mr. Kataras ...

**Comment by kataras** [comment]
1. Yes one client can join to more than one rooms

2.  Yes you can leave from a  room using the `connection.Leave("myroom")` 
'Join switching' I dont understand it, but see `1` and one room can have more than one client so you can just use the `connection.Join` and `connection.Leave` 


3. Yes use the `connection.Disconnect` 

All these are inside the [book](https://www.gitbook.com/book/kataras/iris/details) and the [website](http://iris-go.com), you better go read them we have [examples](https://github.com/iris-contrib/examples)...I didn't do all these for myself, I hope you understand 


Don't worry about 'bad grammar' I'm from Greece, English is not my primary language.

You're welcome, keep going!

**Comment by omarseda** [comment]
Very clear answer, Sir. That is all i need. Thank You.
