### ISSUE TITLE
Standard golang html template engine?

### ISSUE THREAD

**Issue by everyonce** [kataras/iris#394]
Is there a way to use the standard golang template engine within iris?  I'm porting an existing application over that uses that engine.  I've considered using the iris html engine, but there's no examples on how to do things like blocks, etc, like the golang engine does.

Thanks!

**Comment by kataras** [comment]
Of course, you will only need the `io.Writer` to execute the standard html templates, which is the `contextResponse.BodyWriter())` . However Iris also supports standard html templates by default, if you want take a look at the [book section](https://kataras.gitbooks.io/iris/content/template-engines.html)
