### ISSUE TITLE
Routes behaving unexpectedly

### ISSUE THREAD

**Issue by yadvendar** [kataras/iris#396]
Consider this code:

```
    api := iris.New(irisConfig.Iris{
		Gzip:          true,
		DisableBanner: !AppConfig.Debug,
		IsDevelopment: AppConfig.Debug,
	})	
    api.Get("/hello/world", func(ctx *iris.Context) {
		ctx.WriteString("This is the hello world. Harcoded route.")
	})
	api.Get("/hello/:w", func(ctx *iris.Context) {
		ctx.WriteString("This is just hello. Variable route.")
	})
```

If I send a request `GET "localhost/hello/world"` - this works fine but `GET "localhost/hello/random"` throws 404.

**Comment by kataras** [comment]
`:w` and `word` are conflicts, please read the book and discover older post issues for this theme, the router should panic before server' listen if you put the `/hello/:w` before `/hello/world`

**Comment by yadvendar** [comment]
1. Went through that section where it says its a conflict for performance reasons but then shouldnt it panic in this case as well?

2. Also, consider this case: 

```
	api.Get("/hello/world/here", func(ctx *iris.Context) {
		ctx.WriteString("This is the hello.")
	})
	api.Get("/hello/:w", func(ctx *iris.Context) {
		ctx.WriteString("This is the world.")
	})

```
`GET localhost/hello/world/here ` works but `GET localhost/hello/x ` throws 404

Please let me know how to handle such cases as the complexity of the application increases, is there any other way apart from hard coding them in if else conditions inside the handler (as mentioned in one of the example)? 
Looks like whenever prefix of two routes match then this will be an issue.

**Comment by kataras** [comment]
Yes, you can just use a wildcard or search older github issues , you will find many solutions. 

Wildcard: `/hello/*path/
```go
path := ctx.Param("path")

if path = "/world/here" {
   worldHandler(ctx)
}else {
  wHandler(ctx) // where the :w is the 'path' -> ctx.Param("path")
}
```

**Comment by kataras** [comment]
Yes, you can just use a wildcard or search older github issues , you will find many solutions. 

Wildcard: `/hello/*path/`
```go
path := ctx.Param("path")

if path = "/world/here" {
   worldHandler(ctx)
}else {
  wHandler(ctx) // where the :w is the 'path' -> ctx.Param("path")
}
```

**Comment by kataras** [comment]
Yes, you can just use a wildcard or search older github issues , you will find many solutions. 

Wildcard: `/hello/*path` 
```go
path := ctx.Param("path")

if path = "/world/here" {
   worldHandler(ctx)
}else {
   wHandler(ctx) // where the :w is the 'path' -> ctx.Param("path")
}
```
