### ISSUE TITLE
How to pass struct to ctx.JSON

### ISSUE THREAD

**Issue by megabait1212** [kataras/iris#397]
Hi, how to pass struct to ctx.JSON? I tried different ways but always it returns empty response
My code:
```
        Db := db.MgoDb{}
	Db.Init()
	defer Db.Close()

	result := []models.Product{}
	err := Db.C("products").Find(nil).All(&result);
	if err != nil {
		//this.JSON(iris.StatusOK, models.Err("1"))
		panic(err)
	}
	type Response struct {
		draw            int `json:"draw"`
		recordsTotal    int `json:"records_total"`
		recordsFiltered int `json:"records_filtered"`
		data            []models.Product `json:"data"`
	}
	response := Response{
		draw: 1,
		recordsTotal: 3,
		recordsFiltered: 3,
		data: result,
	}
fmt.Printf("%+v\n", response)
ctx.JSON(iris.StatusOK, &response)
```
If I pass only result to ctx.JSON it working as expected, but if I pass struct response it's not working. In console I can see struct with data. Could you help me? Thank you

**Comment by megabait1212** [comment]
Also, 1 more question is it possible pass struct to HTML template? Thank you

**Comment by kataras** [comment]
Yes, examples and book covers both of your questions. Pass a struct with 'ctx.JSON(iris.StatusOK,response)' . To pass struct to template, use the 'ctx.Render("my file.html, myStruct{MyField:"myvalue"})'

**Comment by megabait1212** [comment]
I read manual many times I tried different ways how to pass struct and it always returns empty result and I don't know why

**Comment by kataras** [comment]
You're the first who report something like this, please upgrade your iris and try again I just tested the JSON ad it seems to work

**Comment by megabait1212** [comment]
Today I updated to latest version and same result. It's working if I pass to json only variable result (result := []models.Product{}), but if I pass struct it's I get nothing.

**Comment by megabait1212** [comment]
Struct data from console {
draw:1 
recordsTotal:3 
recordsFiltered:3 
data:[
{Id:W�_,K�Bsb¶↑
 Name:Test 
Status:true 
Slug:test 
CreatedAt:{sec:0 nsec:0 loc:<nil>}
 UpdatedAt:{s
ec:0 nsec:0 loc:<nil>} 
Attributes:[] 
Price:[] 
Marketplace:[] 
Formula:[]
} 
{
Id:W�_
,K�Bsb¶↑♂ 
Name:Test 2 
Status:true 
Slug:test2 
CreatedAt:{sec:0 nsec:0 loc:<nil>}
UpdatedAt:{sec:0 nsec:0 loc:<nil>} 
Attributes:[] 
Price:[] 
Marketplace:[] 
Formula:[]
} {
Id:W�_,K�Bsb¶↑♀ 
Name:Test 3 
Status:true 
Slug:test3 
CreatedAt:{sec:0 nsec:0 loc:<nil>} 
UpdatedAt:{sec:0 nsec:0 loc:<nil>} 
Attributes:[] 
Price:[] 
Marketplace:[] 
Formula:[]
}]
}

**Comment by megabait1212** [comment]
Also it's not working if I pass 	struct without array 
```
type Response struct {
		draw            int `json:"draw"`
		recordsTotal    int `json:"records_total"`
		recordsFiltered int `json:"records_filtered"`
		//data            []models.Product `json:"data"`
	}
	response := Response{
		draw: 1,
		recordsTotal: 3,
		recordsFiltered: 3,
		//data: result,
	}
ctx.JSON(iris.StatusOK, response)
```

**Comment by kataras** [comment]
Run this example: https://github.com/iris-contrib/examples/tree/master/response_engines/json_1

Go to `localhost:8080` and `localhost:8080/alternative_1` and tell me the results,

After go to your local project and  try to capialize your `Response` fields like:

```go
type Response struct {
        Draw            int `json:"draw"`
        RecordsTotal    int `json:"records_total"`
        RecordsFiltered int `json:"records_filtered"`
        //data            []models.Product `json:"data"`
    }

```

render the page and response back with the results please

**Comment by megabait1212** [comment]
Oh, thank you very much. It's working now. Golang it so strict. I spent a few days trying to fix this problem.

**Comment by kataras** [comment]
Could you share your solution in order to help golang newcomers?

**Comment by megabait1212** [comment]
Solution is simple all properties of struct should start from Capital letter

**Comment by kataras** [comment]
Correct, nice job, keep going, you will love Golang + Iris :)
