### ISSUE TITLE
Modifying url scheme

### ISSUE THREAD

**Issue by tkshnwesper** [kataras/iris#398]
If iris was the only webserver running on my system, my current configuration would have worked perfectly fine. But, there is already a Nginx server which listens on port 80. Which means that iris cannot bind to port 80. Okay, understandable. In that case, I can start listening on port 8080 which is free.

But the problem is this, everywhere in my templates I have used url schemes such that have been described in the guide:
`<a href='{{ url "something0" }}'>Something 0</a>`
And that translates to:
`<a href='http://0.0.0.0:8080/something0'>Something 0</a>`

Like I said before, if iris was the standalone server there wouldn't be any problem. I could just listen on
host: _my_domain_name_ and
port: 80
So I would see something like:
`<a href='http://my_domain_name/something0'>Something 0</a>`

_But_, not in my case. I cannot do the above unless I want everyone to see a port number in their url. I usually setup a `proxy_pass` in Nginx whenever some application is listening on a certain port, which enables the app to be seen on a different subdomain instead of people seeing its port number in the url.

I have tried to modify the server config, but I was not able to tweak it to my requirements from that. I mean to remove the `url` part from the template so that it will work with any url (`/something0`) and I can safely use it with Nginx. There were 2 options in the server config that I spent lots of time tweaking, `VScheme` and `VListeningAddr` but I wasn't able to completely remove the scheme and listening address from the url. That was because I could not pass empty strings to those two parameters, as they revert to their default values if I do so. Is this a missing feature or did I miss something or is there a way around this (other than hard-coding links)? 

Thanks.

**Comment by kataras** [comment]
Dear @tkshnwesper 

You're not the only one, we discussed this on the chat and we found a solution, you have to use the `iris.AddServer(config.Server{})` and `iris.Go()` As you correctly, say you have to fill these fields: https://github.com/kataras/iris/blob/master/config/server.go#L107 . **IF** you want only the Path why you use the `{{url }}` ? Iris has `{{urlpath}}` for these reasons, try this and tell me the results,please

**Comment by tkshnwesper** [comment]
Thank you! `{{ urlpath }}` did the trick! This is exactly what I wanted.

**Comment by kataras** [comment]
You're welcome !
