### ISSUE TITLE
How to integrate with http.ServeMux?

### ISSUE THREAD

**Issue by SmarkSeven** [kataras/iris#400]
I want the Iris to  integrate with github.com/qor/admin,What should I do ?

**Comment by kataras** [comment]
Iris is build on top of fasthttp, if you want Iris features (almost) but with net/http http.ServeMux you have to use [this framework](https://github.com/kataras/q). Or convert this middleware you want to an Iris middleware, read how we do that in the [middleware repository](https://github.com/iris-contrib/middleware)
