### ISSUE TITLE
indipendent benchmark

### ISSUE THREAD

**Issue by drakkan** [kataras/iris#403]
Hi,

I'm just searching for a golang framework to build rest api, I think would be useful to compare iris performance in an indipendent benchmark such as this:

https://github.com/TechEmpower/FrameworkBenchmarks/

there are already several go frameworks:

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go

and if iris is really the fastest go framework this could be a good way to grow your user base too,

feel free to close this issue as invalid, it is only a suggestion,

thanks!

**Comment by kataras** [comment]
First of all, The README benchmark images are indipendent , the benchmark suite is not created by me and no from person I knew before I create this framework. The community already knows that, welcome to Iris!

About TechEmpower, it's not my fault they don't include Iris into,
But you can go and make an issue there to include Iris in their benchmarks, I will be glad if you do that for Iris!

**Comment by kataras** [comment]
First of all, The README benchmark images are indipendent(if you click on the image you will see the link, which are came from)  , the benchmark suite is not created by me and no from person I knew before I created this framework. The community already knows that, welcome to Iris!

About TechEmpower, it's not my fault they don't include Iris into,
But you can go and make an issue there to include Iris in their benchmarks, I will be glad if you do that for Iris!

**Comment by kataras** [comment]
First of all, The README benchmark images are **already indipendent**(if you click on the image **you will see the link, which are came from**)  , the benchmark suite is not created by me and no from person I knew before I created this framework. The community already knows that, welcome to Iris!

About **TechEmpower**, it's **not my fault** they don't include Iris into,
But you can go and **make an issue there to include Iris** in their benchmarks, **I will be glad** if you do that for Iris!

**Comment by drakkan** [comment]
Hi, thanks for your answer, about TechEmpower bechmark they don't add frameworks on their own but rely on PR, in my spare time I'll give a try to iris and if I like it I eventually try to implement TechEmpower bechmarks and submit a PR

**Comment by kataras** [comment]
Yes, that I meant, godd, keep me noticed if/when you do that, thank you
