### ISSUE TITLE
Cannot install iris' depedencies when using glide

### ISSUE THREAD

**Issue by opam22** [kataras/iris#404]
Hi mate,

I try to get the iris package with glide but I cannot get its depedencies like go-websocket, go-template, go-sessions, go-fs, go-errors, cli and rizla. The only thing I got is the 'iris' package.
My machine: MacBook Pro with OS X Yosemite 10.10.5

Any suggestion?

Thanks!

**Comment by opam22** [comment]
Solved this by run
> cd /vendor/github.com/kataras/iris
> glide update

**Comment by hero0926** [comment]
It also happens in Sierra and I'm not sure how to install specific version of Iris by Glide!!
