### ISSUE TITLE
iris can't use sqlite3

### ISSUE THREAD

**Issue by ShookGao** [kataras/iris#406]
```
package main

import (
	"database/sql"
	"fmt"

	"github.com/kataras/iris"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	db, err := sql.Open("sqlite3", "./data.db")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	db.Ping()
	fmt.Println("connect is success!")
	iris.Get("/", func(c *iris.Context) {
		c.Write("this is a test!")
	})
	iris.Listen(":80")
}
```
errors:
```
C:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f30c0): multiple definition of `r2r1kp'
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f30b0): first defined here
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f30f0): multiple definition of `r4r3kp'
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f30e0): first defined here
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f1ad8): multiple definition of `r5kp'
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f1ad0): first defined here
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f31a0): multiple definition of `rupolykp'
C:\Users\iamgb\AppData\Local\Temp\go-link-028001747\go.o:(.text+0x7f31b0): first defined here
collect2.exe: error: ld returned 1 exit status
```

only use sqlite3 is no problem ! iris+progres is ok.

**Comment by kataras** [comment]
I can't help you my friend, you have to post that issue at the mattn/go-sqllite3 repository and we will see what mattn will say for this

**Comment by kataras** [comment]
Why is that an Iris issue and no sqllite3 ?
I can't help you my friend, you have to post that issue at the mattn/go-sqlite3 repository and we will see what mattn will say for this

**Comment by kataras** [comment]
Iris has nothing to do with sqlite or other sql packages,  so I don't think this is an iris-specific post issue.
Recommendations:
- Could you explain me why you think that is an Iris issue and no sqllite3 ?
- Post this issue to the mattn/go-sqlite3 repository in order to take an answer, I can't help you more on this, I'm sorry

**Comment by ShookGao** [comment]
ok, I try to contact mattn.

**Comment by kataras** [comment]
@ShookGao Fixed, as https://github.com/mattn/go-sqlite3/issues/329 , go-fs doesn't contains klauspost/compress in /vendor folder, solution for you:

remove your `$GOPATH/src/github.com/kataras` and `$GOPATH/src/github.com/klauspost` and exec `go get -u github.com/kataras/iris` tell me if that is working please

**Comment by kataras** [comment]
@ShookGao Fixed, as https://github.com/mattn/go-sqlite3/issues/329 , go-fs,now, doesn't contains klauspost/compress in /vendor folder, solution for you:

remove your `$GOPATH/src/github.com/kataras` and `$GOPATH/src/github.com/klauspost` and exec `go get -u github.com/kataras/iris` tell me if that is working please

**Comment by ShookGao** [comment]
Yes, this question has been solved! Thanks @kataras

**Comment by kataras** [comment]
You're welcome, thanks for the report!
