### ISSUE TITLE
reverse routing after proxy

### ISSUE THREAD

**Issue by daanpape** [kataras/iris#408]
Hello,

I'm starting to use iris for a project which will run after a proxy. I want to use the reverse routing function with the template/html engine. 

The problem is this generates static URLs with the fully qualified domain name in it. Off course this domain name is not correct. Also it's the proxy who adds the TLS layer so the scheme also isn't correct. 

Is their a way to exclude the domain name from the URLS?
So for example instead of generating http://127.0.0.1/hello, just /hello

Kind regards,
Daan

**Comment by kataras** [comment]
Yes, instead of `{{url }}` use the `{{urlpath }}` 

Note: already answered before couple of days, please search older issue before posting new,  we need to keep an order

**Comment by kataras** [comment]
Hello Daan, The answer is yes, instead of `{{url }}` use the `{{urlpath }}` , welcome to Iris!

Note: already answered before couple of days, please search older issue before posting new,  we need to keep an order

**Comment by kataras** [comment]
Hello Daan, The answer is yes, instead of `{{url }}` use the `{{urlpath }}` , welcome to Iris!

Note: already answered before couple of days, please search older issue posts before posting new,  we need to keep an order
