### ISSUE TITLE
render template from string

### ISSUE THREAD

**Issue by goldalworming** [kataras/iris#409]
Hi, I'm very new with Iris

how to render template from string? is it possible?
like rendering templates but without load from template file. I need to render from string template

e.g : 
{% if current_user %} {{current_user}} {%end%}

**Comment by kataras** [comment]
Hello and welcome to Iris!

Currently Iris (via [go-template](https://github.com/kataras/go-template) ) supports parse, execute and render template files to the client or return it's string, no the opossite.

So it's not supported yet, but it's a good idea I'm coding this feature right now, you will be noticed when I finish

**Comment by kataras** [comment]
Hello and welcome to Iris!

Currently Iris (via [go-template](https://github.com/kataras/go-template) ) supports parse, execute and render template files to the client or return it's string, no the opposite (except HTML and Markdown which you can do that with (`context.HTML` and `context.Markdown`.)

So it's not supported yet, but it's a good idea I'll start coding this feature today, you will be noticed when I finish

**Comment by goldalworming** [comment]
Hi, thank you for the response..

currently I need to render html string to string. I plan to migrate my python tornado apps to go iris but didn't find suitable function to do this.

fyi in tornado I generate tempate by (STRTPL is string template) self.finish(STRTPL.generate(current_user=current_user,objpd=objpd))

currently I try to implement this tutorial https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/07.4.html

**Comment by kataras** [comment]
Ok, I implement this on Iris also, but I can't commit them because yesterday I made some changes on configuration which I need to work a little deeper before push the new version, so you will have to wait some hours, the function(s) which you will work wil be: 
```go
context.RenderTemplateSource(status int, src string, binding interface{}, options ...map[string]interface{}) error
// this will parse the src raw contents to the template engine and render the result to the client
```

and if you want to take only the raw html back from a template, to send a rich e-mail for example, 
then: 
```go
iris.TemplateSourceString(src string, binding interface{}) string
// this will parse the src raw contents to the template engine and return the string result
```

**Comment by kataras** [comment]
Ok, I just implemented this on Iris also, but I can't commit them because yesterday I made some changes on configuration which I need to work a little deeper before push the new version, so you will have to wait some hours, the function(s) which you will work wil be: 
```go
context.RenderTemplateSource(status int, src string, binding interface{}, options ...map[string]interface{}) error
// this will parse the src raw contents to the template engine and render the result to the client
```

and if you want to take only the raw html back from a template, to send a rich e-mail for example, 
then: 
```go
iris.TemplateSourceString(src string, binding interface{}) string
// this will parse the src raw contents to the template engine and return the string result
```

**Comment by goldalworming** [comment]
please tell me if I can update iris library to implement this

**Comment by goldalworming** [comment]
It's still undefined now..

**Comment by kataras** [comment]
Yes, I'm working on other options I left unfinished from yesterday, I can't commit incomplete things, please be pattient, I am working 13 hours without stop

**Comment by goldalworming** [comment]
ok..I'll wait. thank you

**Comment by kataras** [comment]
Finally, I done for today, you can upgrade iris with `go get -u github.com/kataras/iris` and the functions will be definied :)

Also take a look at the [configuration book section](https://kataras.gitbooks.io/iris/content/configuration.html) and the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) for the **v4.2.0** configuration changes

 Thank you for your patience and your feature request, keep going!

**Comment by kataras** [comment]
Finally, I done for today, you can upgrade iris with `go get -u github.com/kataras/iris` and the functions will be defined :)

Also take a look at the [configuration book section](https://kataras.gitbooks.io/iris/content/configuration.html) and the [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md) for the **v4.2.0** configuration changes

 Thank you for your patience and your feature request, keep going!

**Comment by goldalworming** [comment]
how to return page as html. ctx.Text and ctx.Write not work.
![image](https://cloud.githubusercontent.com/assets/440256/18385006/1b1487a0-76b8-11e6-8f18-7ed14c0dd02e.png)

**Comment by goldalworming** [comment]
found it use ctx.HTML

thank you
