### ISSUE TITLE
Custom Http Errors

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#41]
Hello,

Receiving the following error on using your prescribed snippet:
 
```Go
iris.OnError(404,func (c *iris.Context){
        c.HTML("<h1> The page you looking doesn't exists </h1>")
        c.Status(404)
    })
```

Error being:
`undefined: iris.OnError`

Thank you for the wonderful micro framework you're working on, simple and beast fast.:wink:

**Comment by kataras** [comment]
@kryptodev  Fixed, thanks for the issue! thanks for your nice words, I hope you like it!
