### ISSUE TITLE
After update logger compile error

### ISSUE THREAD

**Issue by megabait1212** [kataras/iris#410]
Hi, if I create logger as wrote iris.Use(logger.New()), then I have compile error
C:\GoProjects\src\repr\backend>iris run main.go
# command-line-arguments
.\main.go:23: not enough arguments in call to "github.com/iris-contrib/middleware/logger".New

But if I pass nil, it's compiled iris.Use(logger.New(nil))

**Comment by kataras** [comment]
Logger is no longer takes an argument, it uses the station's one automatically... please read docs, examples or HISTORY.md before posting a new issue, thank you

Reference: https://kataras.gitbooks.io/iris/content/logger.html
