### ISSUE TITLE
`iris run *.go` problem

### ISSUE THREAD

**Issue by shkim** [kataras/iris#411]
I have two .go files: main.go, sub.go

It's ok to use wildcard with `go run`
```
$ go run *.go
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 4.2.0

Fri, 09 Sep 2016 18:48:58 GMT: Running at 0.0.0.0:50001

``` 

But I can't run with iris command
```
$ iris run *.go
# command-line-arguments
./main.go:23: undefined: xxxxyyyzzz    <-- method in sub.go

Error: Failed to build the program.

```

How can I use iris CLI tool for multiple .go file project?

**Comment by kataras** [comment]
When you do `iris run main.go` it will compile the whole folder, we don't need iris run *.go, this has no purpose when the file is builded(Which it's with iris run)
