### ISSUE TITLE
Pull request & feature request debate: add context processors

### ISSUE THREAD

**Issue by skyflyer** [kataras/iris#412]
I would very much appreciate if we could add context processors to Iris. One of the (canonical) applications for context processors is to include authentication/user information and flash messages in rendering contexts.

I've explained and presented the rationale here: https://github.com/skyflyer/iris/issues/1

Let me know your thoughts about this.

**Comment by ryanbyyc** [comment]
I think this is bad smell, and unnecessary overhead which could be easily solved with something like:

```
	c.Render("my-page.html", &Page{
		ErrorMsg:   c.GetFlash("error"),
		Data: map[string]interface{}{
			"foo": "bar",
		}})
```

Moreover, this seems like a series of convenience functions which are not globally useful to all users. I'm disinclined to advocate for the inclusion of this feature, and prefer existing TemplateFuncs to do these kinds of tasks.

All in all, seems a bit too Kitchen Sink for Iris.

**Comment by skyflyer** [comment]
@ryanbyyc, you present a solution, but the point of the "context processor" is to reduce this boilerplate code (`ErrorMsg: c.GetFlash("error")`) in practically every method (in my case).

The TemplateFuncs were my go-to choice in the beginning, but they don't have access to `*iris.Context` and hence can't read flash messages. I've seen some people asking about how to get to flash messages and the answer has consistently been "just read them in http handlers and pass them as data to templates". Context processors (in Django), Action filters (ASP.NET MVC, Ruby on Rails) etc are very useful in this regard as they enable developers to roll their own utility functions.

Mind you: I'm not advocating adding the context processor to add "flash messages" to data for every template. I'm simply advocating adding a possibility for developers to write their own functions/helpers when needed.

I see frameworks (in general) as helpers to reduce common and boilerplate code. And as iris's registration helpers and template engine registrations and numerous other features enable us to reduce and streamline our code, I see this this way to.

Now, I must say, that I am not super satisfied with the interface, but this is a proposal and I hope we can perhaps clean it up a little and perhaps even alias the argument function.

**Comment by skyflyer** [comment]
@kataras what are your though about that? Do you see that functionality like context processor could be integrated into Iris?

**Comment by kataras** [comment]
Dear @skyflyer 

I think that this is not necessary, you can always wrap the iris' context with your own context( I will write an article on medium.com to show you how to do it if you don't know already*)

But maybe I didn't understand the feature request yet, I'm waiting for more community's questions and replies in order to understand its usage 

Cheers,
kataras

**Comment by skyflyer** [comment]
@kataras, I would appreciate an example of how to achieve desired functionality. Let me just emphasise, that it is not context that I need wrapping, but providing "man in the middle" functionality between a "handler function" and "template rendering". I don't see how this could be achieved by wrapping Iris's context into something else. The gist of the example is [that we're modifying the binding](https://github.com/skyflyer/iris/issues/1#issuecomment-245916429) passed into the template engine rather than doing anything with context itself.

Perhaps "context processors" is an inappropriate name (taken from other frameworks).

Let me know what you think.

Kind regards,
 Miha.

**Comment by kataras** [comment]
I got it now, so I can think it simplier, without adding a new feature(keep things as simple as possible) I think we can do that with the existing functionality called 'Middleware', as you already know, and a context key for the `binding` object, which will be passed/or/merge to the `ctx.RenderWithStatus/Render` if it's not nil,  as I did already to archieve the `iris.NoLayout` and `iris.Party(...).Layout("mylayout.html")` , do I understand well or you want something more than a bridge between a middleware and template's bindings?

**Comment by skyflyer** [comment]
It would be great if this could be simplified. Unfortunately, I don't (currently) see how I can achieve this with a middleware? If my render function is:

```go
    iris.Get("/", func(ctx *iris.Context) {
        ctx.MustRender("t.html", map[string]interface{}{"name": "iris"})
    })("test")
```

How can a middleware before this handler function get a `binding` reference and add/merge contents to it?

**Comment by kataras** [comment]
The middleware is one part which already exists, the `binding` merge feature is missing, which can be added with 3-4 lines of code(this was the 'contextKey' I commented previous). I don't want to misunderstand my opinion and the way I see things, I love user's feature requests and suggestions, we can wait if other users vote for this feature too (all feature requests are implemented, except 2*)

**Comment by skyflyer** [comment]
Gerasimos, it would be great if we could use middleware for that. I'm not sure where to put those 3-4 lines though (I'm not that much experienced in go). Could you point me in the right direction, so I can try it out and perhaps prepare a different PR for that?

The way I see it, `ctx.MustRender` is "directly tied" all the way down to `response.go`'s 'render` method and I see no way to modify the binding in the between (using middleware).

**Comment by skyflyer** [comment]
@kataras, did you get a chance to think about it?

**Comment by kataras** [comment]
@skyflyer I'm coding this right now :)

**Comment by kataras** [comment]
Done,

```go
// ...
	iris.UsePreRender(func(ctx *iris.Context, filename string, binding interface{}, options ...map[string]interface{}) bool {
		// put the 'Error' binding here, for the shake of the test
		if b, isMap := binding.(map[string]interface{}); isMap {
			b["Error"] = "error!"
		}
		// true= continue to the next PreRender
    // false= do not continue to the next PreRender
    // * but the actual Render will be called at any case *
		return true
	})

  iris.Get("/", func(ctx *Context) {
  		ctx.Render("hi.html", map[string]interface{}{"Username": "anybody"})
      // hi.html: <h1>HI {{.Username}}. Error: {{.Error}}</h1>
  })

// ...
```

Additionaly you have access to filename and you're able to stop the next PreRender. Share your thoughtsabout this

**Comment by kataras** [comment]
Done,

```go
// ...
	iris.UsePreRender(func(ctx *iris.Context, filename string, binding interface{}, options ...map[string]interface{}) bool {
		// put the 'Error' binding here, for the shake of the test
		if b, isMap := binding.(map[string]interface{}); isMap {
			b["Error"] = "error!"
		}
		// true= continue to the next PreRender
    // false= do not continue to the next PreRender
    // * but the actual Render will be called at any case *
		return true
	})

  iris.Get("/", func(ctx *iris.Context) {
  		ctx.Render("hi.html", map[string]interface{}{"Username": "anybody"})
      // hi.html: <h1>HI {{.Username}}. Error: {{.Error}}</h1>
  })

// ...
```

Additionaly you have access to filename and you're able to stop the next PreRender. Share your thoughtsabout this

**Comment by skyflyer** [comment]
Gerasimos, works like a charm! :) Thank you!

BTW, I recently learned that we don't need to check for nil when operating on slices, for instance:
```go
if t.prerenders == nil {
	t.prerenders = make([]PreRender, 0)
}
t.prerenders = append(t.prerenders, argument)
```
can be transformed to just
```go
t.prerenders = append(t.prerenders, argument)

It makes no functional difference, however :)

**Comment by kataras** [comment]
Yeap, I also know that but you know... I want to be described in the code that I didn't initialize it before , it's just the way I code in order to keep a logical flow , nothing else, I will re-open it because it's new feature and other users should be notified also :)

**Comment by kataras** [comment]
Yeap, I know that... I want to be described in the code, I didn't initialize it before. It's just the way I code in order to keep a logical flow , nothing else.

I made a feature for you, please at least star Iris to be updated for any other new updates :) 

 I will re-open the issue, because it's new feature and other users should be notified also
