### ISSUE TITLE
MustRender on django triggers error, while Render doesn't

### ISSUE THREAD

**Issue by Allendar** [kataras/iris#413]
I'm getting this error: MustRender panics for client with IP: 127.0.0.1 On template: login.html.Trace: Error: No response engine found.

I'm running Django template engine and the connection over HTTPS and call from a browser (not Postman, cURL, wget, e.a.).

This works and renders the page fine:

```
c.Render(
    "login.html",
    map[string]interface{}{},
)
```

This causes the error:

```
c.MustRender(
    "login.html",
    map[string]interface{}{},
)
```

Engine registered as in the guide:

```
m = iris.New(iris.Configuration{
    IsDevelopment: true,
     DisableBanner: true,
     Gzip:                  true,
     ProfilePath:        "/debug",
})
m.UseTemplate(django.New()).Directory("./Views", ".html")
```

**Comment by kataras** [comment]
Render returns an error, you have to manage this error, MustRender panics on error. If your template login.HTML is in your /views folder then you should see the HTML response on your browser. Please make sure that you are read and run the template_engines examples before post an issue about them

**Comment by Allendar** [comment]
You keep referring to documentation in questions. Yet I'm doing my best to constantly read back to the documentation (which I read thoroughly when I started testing with this repo) and even spit through the source code itself when trying to debug.

I know what the functions do and should do; the problem is that it Renders fine on normal Render, but MustRender throws an explicit error, which makes no sense.

**Comment by kataras** [comment]
Man I refer to them(examples and book) because I **just test the examples with a 'Views' directory and django worked perfect, with Render and MustRender**  please give me more information about your problem, show me the codeview you try to render and so on

**Comment by kataras** [comment]
So you closed? Could you write your solution in order to be easy for other members to find what was the issue ?
