### ISSUE TITLE
Django template syntax error causes a "template doesn't exist" log message

### ISSUE THREAD

**Issue by Liamraystanley** [kataras/iris#415]
It seems as though if there is a syntax error in a Django template, it states that the template file isn't found.

```go
package main

import (
	"github.com/kataras/go-template/django"
	"github.com/kataras/iris"
)

func main() {
	iris.StaticWeb("/static", "./static", 1)
	iris.UseTemplate(django.New()).Directory("./static", ".html")

	iris.Get("/", func(ctx *iris.Context) {
		fmt.Println(ctx.Render("index.html", make(map[string]interface{})))
	})

	iris.Listen(":8080")
}
```

And file structure:
```
app/
    main.go
    static/
        index.html
```

Specifically, if there is invalid syntax within `static/index.html` (in my case, just giving an example):
```
{{ block "test" }}
{{ end }}

this is a test!
```

Iris will throw the below error:
```
[IRIS TEMPLATES] Template with name index.html doesn't exists in the dir
```

The error states index.html doesn't exist -- however this is not the case. The returned HTML is completely blank (whereas if I enable development mode, it will throw a **Internal Server Error**)

**Comment by kataras** [comment]
Could you please run this django example: https://github.com/iris-contrib/examples/tree/master/template_engines/template_django_1 and write down if it works on you, if yes try to keep align with the example, first `UseDatabase`, after `StaticWeb` .  I have to tell you that this is not safe workspace, you have static files and templates in the same dir

**Comment by Liamraystanley** [comment]
Yes, that example works. However, if I change [templates/mypage.html](https://github.com/iris-contrib/examples/blob/master/template_engines/template_django_1/templates/mypage.html) in that example to:
```html
<html>
<head>
<title>Hello Django from Iris</title>

</head>
<body>
	{% ifis_admin %}
	<p>{{username}} is an admin!</p>
	{% endif %}
</body>
</html>
```
(notice how the syntax for `{% ifis_admin %}` is incorrect), and wrap `ctx.Render()` with a `fmt.Println()`, like so:
```go
package main

import (
	"fmt"
	"github.com/kataras/go-template/django"
	"github.com/kataras/iris"
)

func main() {

	iris.UseTemplate(django.New()).Directory("./templates", ".html")

	iris.Get("/", func(ctx *iris.Context) {
		fmt.Println(ctx.Render("mypage.html", map[string]interface{}{"username": "iris", "is_admin": true}, iris.RenderOptions{"gzip": true}))
	})

	iris.Listen(":8080")
}
```

I still get:
```
[IRIS TEMPLATES] Template with name mypage.html doesn't exists in the dir
```

This is without the use of `iris.StaticWeb()` at all (it doesn't seem to have any affect if it is present, if it isn't, where it's placed, etc).

The issue is fairly straightforward. It seems to be throwing an invalid error -- it should still be throwing an error, but it should not be stating that the file isn't found. If the syntax is fixed, it does not throw any error.

**Comment by Liamraystanley** [comment]
On these same lines, it looks as though the django templates extend functionality (sort of like iris/html's block/define functionality) is unable to find templates when `iris.UseTemplate(django.New()).Directory("./templates", ".html").Binary()` is being used (with **go-bindata** for example). I will likely post another issue in regards to this once I have time to setup the testing/examples.

**Comment by kataras** [comment]
Dear @Liamraystanley 

I read your comments over and over and I cannot find what's the issue about, so please help me to understand, as far as I understand the issue is only the wrong log message on pongo2 templates when executing?

Cheers,
kataras

**Comment by kataras** [comment]
Dear @Liamraystanley 

I read your comments over and over and I cannot find what's the issue about, so please help me to understand, as far as I understand the issue is only the wrong log message on pongo2 templates when executing? (please post the next templates issue here: https://github.com/kataras/go-template)

Cheers,
kataras

**Comment by kataras** [comment]
Dear @Liamraystanley 

I read your comments over and over and I cannot find what's the issue about, so please help me to understand, as far as I understand the issue is only the wrong log message on django templates when executing? (please post the next templates issue here: https://github.com/kataras/go-template)

Cheers,
kataras

**Comment by Liamraystanley** [comment]
The issue does not look to be specifically with pongo/django templates directly, after looking further. Rather, it actually looks like there are multiple error catching implementations within [kataras/go-template](https://github.com/kataras/go-template/blob/a597fba8ae0a4a71cb31a632ddcbc0be3d5f0d05/django/django.go#L191) (for example) that are throwing template files not found when there is any syntax error. (this seems to be across more than just Django, I believe). Unfortunately I don't have much time as of yet to test further. I will move this issue over to the go-template repository.

**Comment by kataras** [comment]
So this is an error handling issue only, I can fix it very fast then. No need to open other issue for that today :)

**Comment by kataras** [comment]
Before that, I have to ask you, I see the code and it should panic on error when loading the templates, before server startup (if syntax error) , but you get the error on runtime, when you navigate to the route, right?

**Comment by Liamraystanley** [comment]
Correct, it is throwing the error at runtime, as I navigate to the route.

**Comment by kataras** [comment]
This is the bug then, I have to see what's going on, I just verified it, thank you, wait for fix soon :)

**Comment by kataras** [comment]
Fixed, upgrade `go get -u github.com/kataras/iris` or just `go get github.com/kataras/go-template` , please verify that is working now, thanks!

**Comment by Liamraystanley** [comment]
Confirmed, panics on initialization. Thanks much!

**Comment by kataras** [comment]
I thank you, have fun!
