### ISSUE TITLE
redis session bug

### ISSUE THREAD

**Issue by zyanho** [kataras/iris#416]
my env:
iris: 4.2.1
go: 1.7.1
os: mac osx 10.11.6

go run main.go from
"""
https://github.com/iris-contrib/examples/blob/master/sessions/redis/main.go
"""

and i got 

"""
panic: runtime error: invalid memory address or nil pointer dereference 
"""

at 
"""
github.com/kataras/iris.(*Framework).UseSessionDB(0xc42026e5a0, 0xa7e560, 0xc420122028)
"""

**Comment by kataras** [comment]
Did you have a redis server running and listening at `127.0.0.1:6379` as default configuration writes: https://github.com/kataras/go-sessions/blob/master/sessiondb/redis/service/config.go ?

**Comment by zyanho** [comment]
yes, it running
"""
ps aux | grep redis
/usr/local/opt/redis/bin/redis-server 0.0.0.0:6379
"""

**Comment by kataras** [comment]
Hi @zyanho , I just came home, I will run the same example in my machine(windows) and will answer you back here

**Comment by kataras** [comment]
OK @zyanho I just came home, I fixed it please do a full iris upgrade: remove folder `$GOPATH/src/github.com/kataras`  and re-execute in shell `go get -u github.com/kataras/iris/iris` and you should be fine now, thanks for the bug report!
