### ISSUE TITLE
RiakKV & RiakTS support

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#417]
@kataras I've found this library https://github.com/basho/riak-go-client, wouldn't it be great to implement this in iris?

**Comment by es-lab** [comment]
@kataras I'm waiting for your response to this.

**Comment by kataras** [comment]
Dear @es-lab 

Labeled as: `third-party job`. 
Means that this is not a priority for me, and probably will never be, you're understand that I cannot do all middleware for all type of scenarios in the world, you have to work on your web project too, this is an open-source project and a community-driven project

Cheers,
kataras

**Comment by kataras** [comment]
Dear @es-lab 

Labeled as: `third-party job`. 
Means that this is not a priority for me, and probably will never be, you're understand that I cannot do all middleware for all type of scenarios in the world, you have to work on your web project too, this is an open-source project and a community-driven project. 

The book has a section which helps you how to build an iris middleware or plugin(it's very easy), you can also see some examples on real middleware and plugins, here: https://github.com/iris-contrib/middleware and here: https://github.com/iris-contrib/plugin

Cheers,
kataras

**Comment by es-lab** [comment]
Ok. Thanks for the references.
