### ISSUE TITLE
panic:  template: help_message:10: illegal number syntax: "-"

### ISSUE THREAD

**Issue by lewislyou** [kataras/iris#419]
panic: template: help_message:10: illegal number syntax: "-"

goroutine 1 [running]:
github.com/kataras/iris.init.2()
        /home/vagrant/golang/3rdpkg/src/github.com/kataras/iris/ssh.go:250 +0x394
github.com/kataras/iris.init()
        /home/vagrant/golang/3rdpkg/src/github.com/kataras/iris/websocket.go:107 +0xebe
main.init()
        /home/vagrant/golang/3rdpkg/src/github.com/tedcy/gnl2go/cmd/main.go:40 +0x3b

ssh.go
` helpMessage = SSHBanner + `

COMMANDS:
          {{ range $index, $cmd := .Commands }}
                  {{- $cmd.Name }} | {{ $cmd.Description }}
          {{ end }}
USAGE:
          ssh myusername@{{ .Hostname}} {{ .PortDeclaration }} {{ first .Commands}}
          or just write the command below
VERSION:
          {{ .Version }}`

"-" cause panic

**Comment by kataras** [comment]
Could you tell me please what version of Iris do you have installed (you see that on the console window when you run your main.go) and the go version, I think you have v1.5 or v1.6 while the README says go v1.7+

**Comment by kataras** [comment]
Could you tell me please what version of Iris do you have installed (you see that on the console window when you run your main.go) and the go version? I think you have v1.5 or v1.6 while the [README.md](https://github.com/kataras/iris) says **at least v1.7**.

 Solution: 
- Remove your `$GOPATH/src/github.com/kataras `
- Unistall your Go
-  Go to: https://golang.org/dl/ and download the correct golang for your machine
- Install the downloaded file
- Open a shell, and execute: `go get -u github.com/kataras/iris/iris` 
- Re-run your application and you should be fine.

**Comment by lewislyou** [comment]
go v1.7 and work fine

**Comment by kataras** [comment]
Yes, README also notes that, you're welcome :) Have fun with Iris
