### ISSUE TITLE
Hot reload with multiple files

### ISSUE THREAD

**Issue by wolfgangmeyers** [kataras/iris#421]
I have two files, `service.go` and `service_windows.go`, one of which is imported by my main.go file depending on if it is running on windows or not. With `go run` I have to specify both main.go and the platform-specific `service.go` file. With `iris run` only the first file is recognized, the second is ignored, and all of the imports from `service.go` are undefined. Can Iris accept multiple files when launching?

http://stackoverflow.com/questions/26920969/why-does-the-go-run-command-fail-to-find-a-second-file-in-the-main-package

**Comment by wolfgangmeyers** [comment]
Looks like rizla supports multiple source files. So this file could be changed to look at the length of command line args and pass them all in:
https://github.com/kataras/iris/blob/12cae9be3e90bed092bad660ca32a4b946cdb2c2/iris/run.go#L17

**Comment by wolfgangmeyers** [comment]
Tested this out, looks like the files are run separately. The imports from each are reported as undefined.

**Comment by wolfgangmeyers** [comment]
I think the rizla Project would need to allow multiple main source files - https://github.com/kataras/rizla/blob/master/rizla/project.go

**Comment by kataras** [comment]
Why you don't open an issue there and you opened here?
