### ISSUE TITLE
Handle multipart/form-data post

### ISSUE THREAD

**Issue by adred** [kataras/iris#424]
Is there an example with handling multipart/form-data post?

**Comment by xpbliss** [comment]
https://github.com/iris-contrib/examples/blob/master/bind_form/main.go

**Comment by adred** [comment]
@xpbliss It's not a multipart/form-data form.

**Comment by kataras** [comment]
`context.MultipartForm()`

**Comment by adred** [comment]
Can someone show an actual example please. My problem is I don't know how to retrieve it from the request and save into the disk. Also I don't which type I should use for the image in the `Visitor` `struct` in the example.
