### ISSUE TITLE
Unable to get go

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#426]
...\github.com\kataras\iris\websocket.go:99: cannot use s.Server.HandleConnection (type func("github.com/kataras/go-websocket".UnderlineConnection)) as type func(*"github.com/iris-contrib/websocket".Conn) inargument to "github.com/iris-contrib/websocket".Custom

**Comment by kataras** [comment]
Why is that? The websocket examples are working, with the latest `iris-contrib/websocket` ,`kataras/go-websocket` and `kataras/iris` . Please do an upgrade: 

- Remove your `$GOPATH/src/github.com/kataras `
- Unistall your Go
-  Go to: https://golang.org/dl/ and download the correct golang for your machine
- Install the downloaded file
- Open a shell, and execute: `go get -u github.com/kataras/iris/iris` 
- Re-run your application and you should be fine.

**Comment by kataras** [comment]
Dear dxvgef,

The `"github.com/iris-contrib/websocket".Custom` does not receive a websocket.Conn as you wrote, but an UnderlineConnection, seems that **you have an old version of iris-contrib/websocket** . Please upgrade with the latest `iris-contrib/websocket` ,`kataras/go-websocket` and `kataras/iris`. Do a `go get -u github.com/kataras/iris` or for the best solution, follow these steps: 

- Remove your `$GOPATH/src/github.com/kataras `
- Unistall your Go
-  Go to: https://golang.org/dl/ and download the correct golang for your machine
- Install the downloaded file
- Open a shell, and execute: `go get -u github.com/kataras/iris/iris` 
- Re-run your application and you should be fine.

Cheers,
kataras

**Comment by kataras** [comment]
Dear dxvgef,

The `"github.com/iris-contrib/websocket".Custom` does not receive a websocket.Conn as you wrote, but an UnderlineConnection, seems that **you have an old version of iris-contrib/websocket** . Please upgrade with the latest `iris-contrib/websocket` ,`kataras/go-websocket` and `kataras/iris`. Do a `go get -u github.com/kataras/iris` or for the best solution, follow these steps: 

- Remove your `$GOPATH/src/github.com/kataras ` & `$GOPATH/src/github.com/iris-contrib`
- Open a shell, and execute: `go get -u github.com/kataras/iris/iris` 
- Re-run your application and you should be fine.

Cheers,
kataras

**Comment by dxvgef** [comment]
Thanks, I updated iris-contrib solved.

**Comment by kataras** [comment]
You're welcome, I also noticed that you starred the fasthttp-contrib/render, which I wrote but this library is a little 'old', I split some sections and improve the 'old' render package by `github.com/kataras/go-serializer` and `github.com/kataras/go-template` * just to know *

**Comment by dxvgef** [comment]
Ok
