### ISSUE TITLE
Restart server when change template or view

### ISSUE THREAD

**Issue by hifisultonauliya** [kataras/iris#427]
Sorry im beginner for this. i learn this today, i make webapp then i dont know if i change view (.html) file, why i must restart the server, if i didnt restart the render didt make a change on chrome.

sorry if i mistake, im just beginner...

**Comment by kataras** [comment]
Hello, you can do that by setting `iris.Config.IsDevelopment = true` , this will reload your templates on any changes (on each request). Please read the [book](https://www.gitbook.com/book/kataras/iris/details) and take a look at the [examples](https://github.com/iris-contrib/examples). You're welcome, you can be a good iris developer if you read older issues and the examples, dont worry!

**Comment by hifisultonauliya** [comment]
Thanks a lot guys. This what i means. Why default of iris using lock view. And why i must setting to is develop if i want to do small chang on view.

**Comment by kataras** [comment]
Because Iris (and all other go web frameworks) loads the templates BEFORE you run the server, so it doesn't re-builds the template on each request, for performance reasons. When you learn a little bit more of Go and you search on google for articles and tutorials you will understand better

**Comment by hifisultonauliya** [comment]
ow like that, thanks a lot this framework look like awesome to me :)

**Comment by kataras** [comment]
You're welcome, I do my bests. I left from the colleague to work on this project without paid, full time 'job', so I hope you like it and you will like it after many years also!

**Comment by hifisultonauliya** [comment]
Seriousely?

Thanks so many for youre time. ill make product using this framework. maybe
after im success this project ill donate you.

Thanks bro,
