### ISSUE TITLE
Some suggestions？

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#43]
Some suggestions:
1.Config file
       such as the [iniflag](https://github.com/goaltools/iniflag),it can set some initial default configs for iris. 
2.Add a RBAC
       such as the [goRBAC](https://github.com/mikespook/gorbac)
3.Add a login example
      every web frameork always need  this func.  
4.need a good doc for your iris-contollers usage.

**Comment by jcmartins** [comment]
Maybe support to this 
 [Alice](https://github.com/justinas/alice) 
Support to [Flatbuffer](https://google.github.io/flatbuffers/)
Or support to [Protobuffer](http://gogo.github.io/)

**Comment by kataras** [comment]
@jcmartins Alice is not useful here, Iris is implementing a faster and more light solution for middlewares and chain handlers, the Flatbuffer or Protobuffer doesn't have much relation with a web framework (I think) but we will see, thanks for your suggestions!

**Comment by xpbliss** [comment]
5. Could you give a flow diagram for iris?
6.

**Comment by kataras** [comment]
I have to do it when I have some time, because as you see I'm only one, other frameworks has 83 + members

**Comment by xpbliss** [comment]
How to use the ```https://github.com/kataras/iris/tree/development/plugins/iriscontrol```?

**Comment by kataras** [comment]
@xpbliss  This is not ready yet, it should be ready but I had some serious issues with iris' runtime, so it can wait, when it's ready I will add  the how to use  to the /plugins/iriscontrol/readme.md file

**Comment by xpbliss** [comment]
Why  not make a benchmark with no cache?

**Comment by kataras** [comment]
@xpbliss  it's already there, without cache iris is faster than httprouter/gin about 3-4.000 milesseconds

**Comment by xpbliss** [comment]
Why not do something for https://github.com/mholt/binding
Every web framework will do deal with the post form.

**Comment by kataras** [comment]
@xpbliss What do you mean? you can use https://github.com/mholt/binding, you can take the Request object and pass into this binding library, ```context.Request``` .

If you mean build'n iris support for this, post it as a feature and when I finish the new server and router which I'm trying to design these days we will consider your request! thanks you

**Comment by xpbliss** [comment]
Ok. 
I will be glad to see new server and routet. The soon the better.

**Comment by kataras** [comment]
@xpbliss  Yeah it will be a prototype I hope it will be faster than it's or at least faster response at server's heavy work. Thanks you for the feedback again my friend!

**Comment by xpbliss** [comment]
The [Echo v2](https://github.com/labstack/echo) is now more faster?

**Comment by kataras** [comment]
as I see their code it couldn't be faster, but I didn't benchmark the version 2 of Echo yet, if you can do that [here](https://github.com/iris-contrib/go-http-routing-benchmark) it will be nice

**Comment by xpbliss** [comment]
Add errors dealer [https://github.com/pkg/errors](https://github.com/pkg/errors) ?
Add [Vote]( https://github.com/cryptoballot/cryptoballot) for web framework  ?

**Comment by kataras** [comment]
@xpbliss  pkg/errors are on go trending as iris, it's good package but I already implement my own stuff for handling errors, but thanks as always for your links I hope that you are using Iris and no just spamm links here :P 

Github has vote system, for example, here https://github.com/kataras/iris/issues/67 we have 3 images, you can voteup with emoji ( the +face ) :P

**Comment by hsluoyz** [comment]
Hi @xpbliss ,

Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the go RBAC. Let me know if there's any question:) Thanks.
