### ISSUE TITLE
websocket config not work

### ISSUE THREAD

**Issue by chenshaobo** [kataras/iris#430]
as is said at [#428]( https://github.com/kataras/iris/issues/428)

**Comment by kataras** [comment]
As I said you have to upgrade your Iris, because configuration is setted again before iris' Listen, look here: https://github.com/kataras/iris/blob/master/iris.go#L279 but I will test it again and if it's invalid issue then I'll close it and mark as invalid, ok?

**Comment by kataras** [comment]
Websocket config is working, verified, as this example: https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L22

**Comment by kataras** [comment]
Fixed: https://github.com/kataras/go-websocket/commit/bfb19718e7dca519a9eb48e277c33f45a24b63b8

**Comment by chenshaobo** [comment]
**Yet,It is ok now!!! Thanks**

**Comment by kataras** [comment]
I thank you!! and sorry for my brutal comments before, I'm asleep
