### ISSUE TITLE
Can't believe you didn't find an obvious bug on this project's frontpage

### ISSUE THREAD

**Issue by beef9999** [kataras/iris#432]
```
// handle "/" - HTTP METHOD: "GET"
  iris.Get("/", func(ctx *iris.Context) {
    ctx.Render("index.html")
  })
```

Render missing the second parameter?

**Comment by kataras** [comment]
Correct, thank you, next time better titles please I'm doing my bests, full time job on Iris no paid, no $$ to eat some days, have a little more respect

**Comment by kataras** [comment]
Thanks for the observation
