### ISSUE TITLE
Iris Sessions Not Persistent

### ISSUE THREAD

**Issue by chacken** [kataras/iris#434]
I'm stuck with getting any sort of persistent sessions to work in Iris.

Calling a route with "Login" will print out a token; then when I call a route with Restricted, the token is empty. Am I doing something wrong or do I misunderstand the concept behind sessions in GoLang?

```
func Login(c *iris.Context) {
    username := c.FormValueString("email")
    password := c.FormValueString("password")
    test := "unauthorized"
    if username == "jon@snow.com" && password == "123abc!@#" {
        token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
            "name": "Jon Snow",
            "exp": time.Now().Add(time.Hour * 72).Unix(),
        })

        t, err := token.SignedString([]byte("SecretKey"))
        if err != nil {
            panic(err)
        }

        c.Session().Set("token", t)
        test = c.Session().GetString("token")
    }

    c.Text(200, test)
}



func Restricted(c *iris.Context) {  
    tokenString := c.Session().GetString("token")
    if tokenString != "" {
        c.Text(iris.StatusOK, tokenString)
    } else {
        c.Text(iris.StatusOK, "no Token")
    }
}
```

**Comment by kataras** [comment]
Dear @chacken 

I tested your code snippet (without the token.Signed...) and it seems to be working just fine, can you give me the configuration code snippet and please upgrade iris for any case? remove `$GOPATH/src/github.com/kataras` and exec `go get -u github.com/kataras/iris` 

Cheers,
kataras

**Comment by kataras** [comment]
Dear @chacken 

I tested your code snippet (without the token.Signed...) and it seems to be working just fine, can you give me the configuration code snippet and please upgrade iris for any case? remove `$GOPATH/src/github.com/kataras` and exec `go get -u github.com/kataras/iris` 

Look at this example: https://github.com/iris-contrib/examples/blob/master/sessions/main.go , you do a `set` and `get` action, which this example does too.

Cheers,
kataras
