### ISSUE TITLE
iris.NoLayout err

### ISSUE THREAD

**Issue by zjb0807** [kataras/iris#435]
my versions is 4.2.9, i have tried the two ways to return nolayout, but failed
ctx.Render("login.html", nil, iris.RenderOptions{"layout": iris.NoLayout})
ctx.MustRender("login.html", nil, iris.RenderOptions{"layout": iris.NoLayout}) 

errors:
[IRIS] 2016/09/15 18:33:02 MustRender panics for client with IP: 192.168.20.1 On template: login.html.Trace: html/template: "@.|.@no_layout@.|.@" is undefine

**Comment by kataras** [comment]
Let me check it first, thanks for the report I will respond back

**Comment by kataras** [comment]
Dear @zjb0807 

I have tried to re-produce the issue, but I couldn't, could you please give us more details or the full source code snippet of your handler?

This is the code I ran and worked: 
```go
package main

import (
	"github.com/kataras/go-template/html"
	"github.com/kataras/iris"
)

func main() {
	// directory and extensions defaults to ./templates, .html for all template engines
	iris.UseTemplate(html.New(html.Config{Layout: "layouts/layout.html"}))
	//iris.Config.Render.Template.Gzip = true
	iris.Get("/", func(ctx *iris.Context) {
		if err := ctx.Render("page1.html", nil); err != nil {
			println(err.Error())
		}
	})

	// remove the layout for a specific route
	iris.Get("/nolayout", func(ctx *iris.Context) {
		if err := ctx.Render("page1.html", nil, iris.RenderOptions{"layout": iris.NoLayout}); err != nil {
			println(err.Error())
		}
	})

	// set a layout for a party, .Layout should be BEFORE any Get or other Handle party's method
	my := iris.Party("/my").Layout("layouts/mylayout.html")
	{
		my.Get("/", func(ctx *iris.Context) {
			ctx.MustRender("page1.html", nil)
		})
		my.Get("/other", func(ctx *iris.Context) {
			ctx.MustRender("page1.html", nil)
		})
	}

	iris.Listen(":8080")
}


```
Thanks,
kataras

**Comment by kataras** [comment]
Dear @zjb0807 

I have tried to re-produce the issue, but I couldn't, could you please give us more details or the full source code snippet of your handler?

This is the code I ran and worked: 
```go
package main

import (
	"github.com/kataras/go-template/html"
	"github.com/kataras/iris"
)

func main() {
	// directory and extensions defaults to ./templates, .html for all template engines
	iris.UseTemplate(html.New(html.Config{Layout: "layouts/layout.html"}))
	//iris.Config.Render.Template.Gzip = true
	iris.Get("/", func(ctx *iris.Context) {
		if err := ctx.Render("page1.html", nil); err != nil {
			println(err.Error())
		}
	})

	// remove the layout for a specific route
	iris.Get("/nolayout", func(ctx *iris.Context) {
		if err := ctx.Render("page1.html", nil, iris.RenderOptions{"layout": iris.NoLayout}); err != nil {
			println(err.Error())
		}
	})

	// set a layout for a party, .Layout should be BEFORE any Get or other Handle party's method
	my := iris.Party("/my").Layout("layouts/mylayout.html")
	{
		my.Get("/", func(ctx *iris.Context) {
			ctx.MustRender("page1.html", nil)
		})
		my.Get("/other", func(ctx *iris.Context) {
			ctx.MustRender("page1.html", nil)
		})
	}

	iris.Listen(":8080")
}


```

Maybe you have an old version of the `kataras/go-template` package, try this:

- remove `$GOPATH/src/github.com/kataras` and `$GOPATH/src/github.com/iris-contrib` 
- open your shell and execute: `go get -u github.com/kataras/iris` 
- try again and write the results to this thread

Thanks,
kataras

**Comment by zjb0807** [comment]
i have tried:
rm -rf $GOPATH/src/github.com/kataras
go get -u github.com/kataras/iris

but it also failed, what's your e-mail addr ?

**Comment by zjb0807** [comment]
It's my fault .
modify "github.com/iris-contrib/template/html" to "github.com/kataras/go-template/html", it is ok!
thank you !

**Comment by kataras** [comment]
`iris-contrib/template` has the same source code as `kataras/go-template` for these type of things, seems that you had an old version of `iris-contrib/template`, you're welcome!
