### ISSUE TITLE
Go vet complains about Log

### ISSUE THREAD

**Issue by Andersbiha** [kataras/iris#436]
Upon updating a project to the latest Iris version and running `gometalinter` i started receiving the error below.

`possible formatting directive in Log call (vet)`

It appears that `go vet` expects the method to be named `Logf` instead of `Log` due to formatting being detected.

Is this considered a bug or the expected behavior?

**Comment by kataras** [comment]
It's expected, go vet just suggest a different name for this function, nothing more, don't worry :)

**Comment by kataras** [comment]
It's expected, go vet just suggests a different name for this function, nothing more, don't worry :)
