### ISSUE TITLE
Odd behavior on router with paths ending in "/"

### ISSUE THREAD

**Issue by gpaixao** [kataras/iris#437]
Registered routes:
`GET /segment`
`POST /segment`

**Weird**
Request `GET /segment/` gets redirected (301) to `/segment`
Should't the router just match the route ignoring the final `/`?

**Weirdest**
Request `POST /segment/` calls `func` registered to `GET /segment`. Ignores the `HTTP Verb`, ignores the final `/`.

Is this the desired behavior?

**Comment by kataras** [comment]
Dear @gpaixao 

This is a desired behavior, to disable this set `iris.Config.PathCorrection = false `, I think documentation covers that part also

Cheers,
kataras

**Comment by gpaixao** [comment]
Tks :smile:

**Comment by kataras** [comment]
You're welcome, have fun!
