### ISSUE TITLE
Writing tests with httptests?

### ISSUE THREAD

**Issue by macnibblet** [kataras/iris#440]
I'm trying to figure out how to write tests, but documentation is a tiny bit lacking on integration with httptest ?

**Comment by kataras** [comment]
Dear @macnibblet 

Integration with https://github.com/gavv/httpexpect  ,  as the README says, you can find iris test examples on httpexpect's repository

Cheers,
kataras

**Comment by macnibblet** [comment]
Ahh cool, thanks, I only checked the gitbook documentation, perhaps that should be updated with a testing section ?

**Comment by kataras** [comment]
I think people who don't read the README probably will never read the 'testing' section on a gitbook but if you desired, you can write an article, just make a PR [here](https://github.com/iris-contrib/gitbook) , book is open too :)
