### ISSUE TITLE
cache gzipped static file in Contxt.ServeContent

### ISSUE THREAD

**Issue by reedom** [kataras/iris#441]
Hi,

`Contxt.ServeContent` looks like it gzip every time for each of "new face" browser session.
I think the gzipped files can be cached, which makes iris faster than now in this case, doesn't it?

Thanks.

**Comment by kataras** [comment]
Dear @reedom ,

`StaticFS` is the function you need, which will cache the zipped files and serve them faster than other static functions.

Iris has more than one functions for static files, `StaticContent` is for 'dynamic' content, for example to serve bytes as file, anyway. if you had read the gitbook you should know these...

Cheers,
kataras

**Comment by kataras** [comment]
Dear @reedom ,

`StaticFS` is the function you need, which will cache the zipped files and serve them faster than other static functions.

Iris has more than one functions for static files, `Context.ServeContent` is for 'dynamic' content, for example to serve bytes as file, anyway. if you had read the gitbook you should know these...

Cheers,
kataras

**Comment by reedom** [comment]
> StaticFS is the function you need, which will cache the zipped files and serve them faster than other static functions.

Kataras, I cannot use `StaticFS` due to your design decision.

In detail:

My app serves under `/api/*` for REST API.
`/` and `/static/*` serves static files.

To serve `/`, index file(index.html), `iris.Context.ServeFile` is the one to call instead of `StaticFS`, isn't it?

**Comment by kataras** [comment]
You can call whatever you want to servea single file. You can read the file, save its bytes to the memory and serve them with `ServeContent` , you can also use browser's cache and use the `ServeFile` or other static functions, if you read the gitbook you will find a better answer :)

**Comment by reedom** [comment]
Would you let me know the URL of the page where I can find a better answer?

Sadly I failed to found one among:
https://kataras.gitbooks.io/iris/content/handlers.html and sub pages
https://kataras.gitbooks.io/iris/content/static-files.html
https://kataras.gitbooks.io/iris/content/gzip.html
https://kataras.gitbooks.io/iris/content/serialize-engines.html

Thank you!
