### ISSUE TITLE
error go get

### ISSUE THREAD

**Issue by Daedfr** [kataras/iris#443]
Windows 10

go get -u github.com/kataras/iris/iris

# golang.org/x/sys/windows
..\..\..\golang.org\x\sys\windows\syscall.go:61: undefined: Timeval
..\..\..\golang.org\x\sys\windows\syscall.go:69: undefined: Timeval
..\..\..\golang.org\x\sys\windows\syscall_windows.go:191: undefined: SecurityAttributes
..\..\..\golang.org\x\sys\windows\syscall_windows.go:402: undefined: Timeval
..\..\..\golang.org\x\sys\windows\syscall_windows.go:423: undefined: Timeval
..\..\..\golang.org\x\sys\windows\syscall_windows.go:702: undefined: WSABuf
..\..\..\golang.org\x\sys\windows\syscall_windows.go:702: undefined: Overlapped
..\..\..\golang.org\x\sys\windows\syscall_windows.go:740: undefined: Overlapped
..\..\..\golang.org\x\sys\windows\syscall_windows.go:752: undefined: Overlapped
..\..\..\golang.org\x\sys\windows\syscall_windows.go:766: undefined: Filetime
..\..\..\golang.org\x\sys\windows\syscall_windows.go:766: too many errors

Try to download manually package , same erros when i try to build a test.

I try remove iris-contrib & kataras folder and go get again , same errors and now i have this error when i try to build a project .

main.go:8:2: cannot find package "github.com/iris-contrib/plugin/oauth" in any of:
	C:\Go\src\github.com\iris-contrib\plugin\oauth (from $GOROOT)
	C:\Gowork\src\github.com\iris-contrib\plugin\oauth (from $GOPATH)

**Comment by kataras** [comment]
Dear @Daedfr 
I installed a fresh win10 in my virtual machine and `go get -u github.com/kataras/iris/iris` installed successfully and ran just fine, I think you have to unistall your entirely Go and $GOPATH and install the latest golang 1.7: https://golang.org/dl open your shell and execute `go get -u github.com/kataras/iris/iris` 

Thanks,
kataras

**Comment by kataras** [comment]
Dear @Daedfr 

This  should be a general issue, not iris-specific.

I installed a fresh win10 in my virtual machine and `go get -u github.com/kataras/iris/iris` installed successfully and ran just fine, I think you have to unistall your entirely Go and $GOPATH and install the latest golang 1.7: https://golang.org/dl open your shell and execute `go get -u github.com/kataras/iris/iris` 

Thanks,
kataras

**Comment by Daedfr** [comment]
reinstalled, same error . i have installed many libraries since few months , never get an error .

**Comment by kataras** [comment]
Did that fixed your issue ?

**Comment by amorroxic** [comment]
Same thing, Ubuntu 14.04 - anyone managed to figure this one out?

```
GOPATH=/root/gopath go get github.com/kataras/iris
# github.com/kataras/iris
/root/gopath/src/github.com/kataras/iris/response_writer.go:65: undefined: http.Pusher

GOPATH=/root/gopath go get github.com/kataras/iris/iris
# gopkg.in/kataras/iris.v6
/root/gopath/src/gopkg.in/kataras/iris.v6/response_writer.go:65: undefined: http.Pusher

GOPATH=/root/gopath go get -u github.com/kataras/iris/iris
# gopkg.in/kataras/iris.v6
/root/gopath/src/gopkg.in/kataras/iris.v6/response_writer.go:65: undefined: http.Pusher
```

Cheers!

**Comment by kataras** [comment]
@amorroxic 
- README.md says: **at least go version 1.8**
- README.md says: the import path is `gopkg.in/kataras/iris.v6`  not `github.com/kataras/iris`

**Comment by amorroxic** [comment]
My bad @kataras - didn't mean to sound ignorant, advance apols. I was trying to provision a new VM building a codebase (running on iris 6.0.6, go 1.7.4) and that's the first thing i did, gopkg../iris.v6 - broken sources (iris.API / iris.Listen undefined now), hence lots of trial and error with various other packages.  

Much admiration for how fast you guys evolve - however would love a bit of API stability to be honest, it's quite a pain to adapt servers provisioning / sources with each new iteration of Iris and not being able to spin a new instance in one month from now on. I'm not a very prolific golang programmer - more like dev-ops so I definitely realize how many points I may have missed in my amateurish comment. Thanks for a great project you built!
