### ISSUE TITLE
logger and logger middleware confusion

### ISSUE THREAD

**Issue by luca-moser** [kataras/iris#448]
Hi.

I have a problem getting Iris to log http requests to a file.

`github.com/iris-contrib/middleware/logger`.New() creates a HandlerFunc to use with `engine.Use()`.
`github.com/iris-contrib/logger` contains a logger, which in its config I can specify a file. However, I can't mix them because they don't use the same config type.

How can I tell Iris to log its processed http requests to a log file?

```
// imports
"github.com/iris-contrib/logger"
loggerMiddleware "github.com/iris-contrib/middleware/logger"

loggerCnf := logger.DefaultConfig().MergeSingle(logger.Config{Out: logFileWriter.(*os.File)})
// compiler error
r.Use(loggerMiddleware.New(logger.New(loggerCnf)))
```

**Comment by kataras** [comment]
The logger middleware takes the `iris-contrib/logger` , from when? Logger middleware does not takes an iris-contrib/logger as parameter, https://github.com/iris-contrib/middleware/blob/master/logger/logger.go#L54.

Please read the docs before post a issue, do not make guesses, thank you!

**Comment by kataras** [comment]
The logger middleware takes the `iris-contrib/logger` , from when? Logger middleware does not takes an iris-contrib/logger as parameter, https://github.com/iris-contrib/middleware/blob/master/logger/logger.go#L54.

Please read the docs before post a issue, do not make guesses, thank you!

About your question,

> How can I tell Iris to log its processed http requests to a log file?

logger middleware takes the `iris.Logger` as its logger, so if you setted the framework's logger to a file, the middleware automatically will write to this file

**Comment by xpbliss** [comment]
How to save the log to the different fies according to the date?  such as  20160922.log, 20160923.log,20160924.log,20160925......?

**Comment by kataras** [comment]
@xpbliss This is not relative to Iris, you can search on google for these type of questions but I can give you a start idea,

- create a new writer of `io.Writer`
- in this writer you will take the current timestamp and create a new file in the directory if this file is not already exists
- set this `io.Writer` to the iris'Logger, which is just a `*log.Logger`, ex: `iris.Set(iris.OptionLoggerOut(myWriter))` 
- now, each time iris or you logs something by using `iris.Logger` these contents will go to your custom `io.Writer` and this writer will be responsible how and where will write the contents

**Comment by xpbliss** [comment]
thanks!

**Comment by kataras** [comment]
You're welcome!

**Comment by luca-moser** [comment]
@kataras 
I had an older version of the loggerMiddleware which still took the `iris-contrib/logger.Logger` (https://github.com/iris-contrib/middleware/commit/c690f8a44a767f524f5119c814cf2b12a85b769a). I've updated those packages and obviously now I get compilation errors, so that's ok.

However:
Setting `engine.Logger.SetOutput(logFile)` prints nothing to the log file (I am doing multiple requests and nothing shows up). I can't use the loggerMiddleware, because its config doesn't support an output to be set, so it's useless in my case.

I've created this repository https://github.com/luca-moser/iris-logtest which reproduces the issue. I expect data to be written to the logfile but nothing shows up. There's also a branch (https://github.com/luca-moser/iris-logtest/tree/with-option-set ) which uses `engine.Set(iris.OptionLoggerOut(logfile))` which doesn't work either.

**Comment by luca-moser** [comment]
Ok I've resolved the issue. The problem was, that you must set the io.Writer as you specified (`engine.Set(iris.OptionLoggerOut(logfile)`) **AND** use the logger middleware so that Iris actually logs http requests.

**Comment by kataras** [comment]
Exactly, If you want to log to a file you have to set the logger's out, which you do with the option I shown before, and you correctly, put. To log http requests, you  have to use the middleware, which will write its logs to the iris' logger, which will output to the logFile you setted as the logger's writer, it's simple :)

**Comment by kataras** [comment]
Exactly, If you want to log to a file you have to set the logger's out, which you do with the option I shown before, and you correctly, put. To log http requests, you  have to use the middleware, which will write its logs to the iris' logger, which will output to the logFile you setted as the logger's writer, it's simple but this wasn't your issue's question :)

**Comment by kataras** [comment]
Exactly, If you want to log to a file you have to set the logger's out, which you do with the option I shown before, and you correctly, put. To log http requests, you  have to use the middleware, which will write its logs to the iris' logger, which will output to the logFile you setted as the logger's writer, it's simple but this wasn't your issue's question :) happy to helped

**Comment by fengxsong** [comment]
```
iris.Set(iris.OptionLoggerPreffix("testprefix"))
iris.Logger.Println(iris.Config.LoggerPreffix)
iris.Use(logger.New())
iris.Get("/", func(ctx *iris.Context) {
	ctx.WriteString(strconv.FormatInt(time.Now().Unix(), 10))
})
```
I have not idea why did i still get the log format `[IRIS] 2016/09/30 17:54:06 127.0.0.1 GET /`

**Comment by kataras** [comment]
Let me fix that

**Comment by kataras** [comment]
@fengxsong fixed, thank you!
