### ISSUE TITLE
Need Help on Cors

### ISSUE THREAD

**Issue by sameersanatkpatro** [kataras/iris#449]
Hi @kataras ,
I know this Question have been asked multiple times.But I am not able to understand how to implement the Iris.Any.
I have implemented my frontend in react and backend in iris.
When I am trying a PUT its throws CORS issue.
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access

I have configured CORS:

app := iris.New()
app.Use(cors.DefaultCors())

The API are as follows:
app.Post("/user/create",func(c *iris.Context){//db.insert...}
app.Put("/user/edit/:email",func(c *iris.Context){//db.update...}
.....
I have read on the previous answers that we need to user Iris.Any.
Can you please tell me  how the Iris.Any will be implemented for the Api's above?Thanks in advance for your help.

**Comment by kataras** [comment]
Let's fix this too, but please, first, transfer this issue to the correct [repository](https://github.com/iris-contrib/middleware). We should maintain order.

**Comment by sameersanatkpatro** [comment]
Thanks @kataras for your reply.So should I close the issue here and create a new one in the repository you mentioned?

**Comment by kataras** [comment]
Yes, I'm waiting

**Comment by sameersanatkpatro** [comment]
Thanks .Done.

**Comment by kataras** [comment]
FIXED

Reference: https://github.com/iris-contrib/middleware/issues/13
