### ISSUE TITLE
Framework.URL and Framework.Path methods should add query parameters

### ISSUE THREAD

**Issue by skyflyer** [kataras/iris#450]
When route is defined like:

```go
iris.Get("/", func(c *iris.Context) {})("name")
```

it should be possible to call `iris.Path` or `iris.URL` methods with `name` parameter and extra paramateres to be added as query string values. For instance:

```go
iris.Path("name", []string{"q", "search me"})
```
should produce URL `/q=search+me`

Is this supported / planned or is there another way of achieving this? I can prepare a PR for this, if desired. Probably #138 is related.

**Comment by kataras** [comment]
This is already discussed by the Community, the parameters are for `path parameters ` .
```go
iris.Get("/profile/:username", func(c *iris.Context) {})("profile")
iris.Path("profile", "usernamehere") // = /profile/usernamehere
```

Please read the contribution file before posting a new issue, you cannot tell 'should produce URL' in the same time you even didn't star the repo or read the docs  or view the examples...
