### ISSUE TITLE
How can I implement SSL with this framework?

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#451]
I am new to GO world and decided to start with this framework. 

Only concern at this point is: how can I implement SSL with this framework without NGINX?

**Comment by kataras** [comment]
It's your first question, so this time I can answer you, but the next time please read the [guide](https://kataras.gitbooks.io/iris/content/) before post a new issue.

Book section: https://kataras.gitbooks.io/iris/content/tls.html

Examples:

- Manual key and cert files:  https://github.com/iris-contrib/examples/tree/master/listentls
- Automatic TLS: https://github.com/iris-contrib/examples/tree/master/letsencrypt

```go
// with files
iris.ListenTLS(host, "mycert.cert", "mykey.key")

```

```go
// auto tls
iris.ListenLETSENCRYPT("127.0.0.1:443")
```

**Comment by kataras** [comment]
Dear @speedwheel, you're welcome

It's your first question, so this time I can answer you, but the next time please read the [guide](https://kataras.gitbooks.io/iris/content/) before post a new issue.

Book section: https://kataras.gitbooks.io/iris/content/tls.html

Examples:

- Manual key and cert files:  https://github.com/iris-contrib/examples/tree/master/listentls
- Automatic TLS: https://github.com/iris-contrib/examples/tree/master/letsencrypt

```go
// with files
iris.ListenTLS(host, "mycert.cert", "mykey.key")

```

```go
// auto tls
iris.ListenLETSENCRYPT("127.0.0.1:443")
```

> Don't forget to star the repository in order to always be up-to date and notified about any new changes.

Thanks,
kataras

**Comment by speedwheel** [comment]
Thank you, I will look more carefully into the documentation next time.

**Comment by kataras** [comment]
You're welcome to our community!! Happy coding!
