### ISSUE TITLE
The example of the chapter "Recovery" in the Documentation is broken.

### ISSUE THREAD

**Issue by YamiOdymel** [kataras/iris#452]
![2016-10-01 8 35 49](https://cloud.githubusercontent.com/assets/7308718/19014112/cabbc050-8816-11e6-8b2f-880328101f7c.png)

https://kataras.gitbooks.io/iris/content/middleware-recovery.html

**Comment by kataras** [comment]
Fixed, but no need to post an issue for these things, you can just fix it via PR on the [gitbook](https://github.com/iris-contrib/gitbook) or post it in the [correct](https://github.com/iris-contrib/gitbook) repository. BTW thank you!
