### ISSUE TITLE
Config.DisablePathEscape does not take effect

### ISSUE THREAD

**Issue by Kisesy** [kataras/iris#455]
Hi, kataras
iris version: 4.4.3

https://github.com/iris-contrib/examples/blob/master/named_parameters_pathescape/main.go
In this example the test does not pass

>Request: http://localhost:8080/details/Project%2FDelta
>Output : `Not Found`

**Comment by kataras** [comment]
Hi Kisesy, todo it with `iris.Set(iris.OptionDisablePathEscape(true))` or `app := iris.New(iris.Configuration{DisablePathEscape: true}`  instead, I will update the example. Thank you

**Comment by kataras** [comment]
Hi Kisesy, do it with `iris.Set(iris.OptionDisablePathEscape(true))` or `app := iris.New(iris.Configuration{DisablePathEscape: true}`  instead, I will update the example. Thank you

**Comment by kataras** [comment]
Hi Kisesy, do it with `iris.Set(iris.OptionDisablePathEscape(true))` or `app := iris.New(iris.Configuration{DisablePathEscape: true}); app.Get(...)`  instead, I will update the example. Thank you

**Comment by kataras** [comment]
Hi Kisesy, do it with `iris.Set(iris.OptionDisablePathEscape(true))` or `app := iris.New(iris.Configuration{DisablePathEscape: true}); app.Get(...)`  instead, I will update the example. Thank you, please the next time try to post examples issues on the examples repository.

**Comment by kataras** [comment]
Hi Kisesy, thank you for the report, it was a small issue after the last changes, fixed
