### ISSUE TITLE
Build error, some parameters in iris.go & websocket.go undefined

### ISSUE THREAD

**Issue by ctc316** [kataras/iris#456]
iris version: 4.4.5
go: 1.7.1

Errors show up when build as follows: 
```
vendor/github.com/kataras/iris/iris.go:714: undefined: fs.DefaultUpdaterAlreadyInstalledMessage
vendor/github.com/kataras/iris/iris.go:715: undefined: fs.GetUpdater
vendor/github.com/kataras/iris/iris.go:721: undefined: fs.Stdout
vendor/github.com/kataras/iris/iris.go:721: undefined: fs.Stderr
vendor/github.com/kataras/iris/iris.go:721: undefined: fs.Silent
vendor/github.com/kataras/iris/websocket.go:75: s.Server.Set undefined 
```

**Comment by ctc316** [comment]
I am using glide for package management. And I think for the 
`vendor/github.com/kataras/iris/websocket.go:75: s.Server.Set undefined`

It's because glide cannot get the latest github.com/kataras/go-websocket package.
Due to the the go-websocket not yet has a release version

**Comment by ctc316** [comment]
The same thing happens to `github.com/kataras/go-fs` for the other 5 err lines.

**Comment by kataras** [comment]
Hello @ctc316 I am not responsible for everyone's glide workspace, I'm sorry. Try to remove `$GOPATH/src/github.com/kataras` and `$GOPATH/src/github.com/iris-contrib` and execute `go get -u githb.com/kataras/iris`

**Comment by ctc316** [comment]
Hi kataras,
      The release tags of these two repository. The problem is solved. Thank you for everything you’ve done. Iris is Cool.

**Comment by kataras** [comment]
Of course, in your service, thank you very much for your nice words! I want to enjoy Iris as much as possible!
