### ISSUE TITLE
Websocket API similar to socket.io, Why not direct support socket.io?

### ISSUE THREAD

**Issue by arden** [kataras/iris#459]
Websocket API similar to socket.io, Why not direct support socket.io?

Because ios/android client have no any lib support "Websocket API similar to socket.io".

**Comment by kataras** [comment]
Hi @arden 

Iris supports everything, we don't provide ORM but you're free to use anything you like, if you like socket.io package convert it to go and fasthttp and you will be able to use  it with Iris, we don't have limits. I designed a library to work with websockets only, saying 'webocket api like socket.io' means its simple function's names and all that you're usually work with. Iris websocket is unique coded from scratch, if you want to use other library you're free to do it.

Thanks,
kataras

**Comment by fromiuan** [comment]
hi @kataras ,i'm sorry ，my english is to poor,i have a very simple question to you，I find a package socket.io in github `https://github.com/googollee/go-socket.io`,but i don't know use the function `http.Handle("/socket.io/", server)` in the iris ..think you

**Comment by NItaMII** [comment]
so is there a protocol like stomp which can base on websocket, or just you rule it...

**Comment by kataras** [comment]
@NItaMII  and @fromiuan Look this example I wrote on other issue here: https://github.com/kataras/go-websocket/issues/25#issuecomment-276942582 It's a `socket-io` example (untested) .

**Comment by fromiuan** [comment]
@kataras Thinks to you.I try try
