### ISSUE TITLE
Excessive recursive dependencies

### ISSUE THREAD

**Issue by berlincount** [kataras/iris#467]
Hi,

I'm worried about getting into something like the npm mess (http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) ...

Currently, I'm counting 28 github vendors, providing 52 external packages, only seven of which are orgs, i.e. have a Github setup in place that would allow any kind of succession should something untoward happen.

What's the future plan for this? :)

Cheers,

   count

**Comment by kataras** [comment]
Hi @berlincount I, as all other golang library authors we have backup for any case, if at least one external library is removed by its author, I'm prepared to upload all dependecies to one github repo and update the imports within an hour, so don't worry and trust go community :)
