### ISSUE TITLE
change StaticCacheDuration default value

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#472]
How can I change StaticCacheDuration value directly from my application, without editing the configuartion.go from the iris package? 

I wish my static files to be cached for more than 20 seconds.

Thanks.

**Comment by kataras** [comment]
`iris.StaticCacheDuration = myseconds* time.Second`  that's the only option, fasthttp has it as global variable too so I can't do anything more... you have to open an issue on [its](https://github.com/valyala/fasthttp) repository if you want per-action or per server cache duration configuration field
