### ISSUE TITLE
very hard to write action test

### ISSUE THREAD

**Issue by cocotyty** [kataras/iris#473]
can context be a interface?

**Comment by kataras** [comment]
Hello cocotyty, explain your title, yes context can be interface, you can make that interface and use it to your projects, please search on google for Go Programming Language tutorials :) , thanks for posting

**Comment by cocotyty** [comment]
type Context interface{}
func Action(ctx Context){}
iris.Get("/x",Action)

It cannot work

**Comment by cocotyty** [comment]
I want a mock context to test my code. I don't want to start server.
@.@

**Comment by kataras** [comment]
You don't have to start a server to run the tests, did you look up at the `http_test.go` ? it doesn't runs the server at the 99% of the cases, you only need the handler, if you are boring to read the 'How to write tests with Iris' (is an article posted at the very top of the README page of this repository), look below:

you want the handler to make your tests, and a virtual scheme and host if you want to test advanced things,  normally to get the handler you have to execute manually the `iris.Build`, but as you know Iris is both for experts and newcomers, so I am providing you a function which you can prepare your tester in one line: ` e:= iris.Tester(t)`  so, a trivial example of this: 

```go
// do iris.Config.VHost = "myhost.com" and iris.Config.VScheme = "https://" if you want to
iris.Get("/mypath", func(ctx *iris.Context){
  //...
  ctx.Write("%s", "my body")
})

e := iris.Tester(t) // t = *testing.T
e.GET("/mypath").Expect().Status(iris.StatusOK).Body().Equal("my body")
```

Hope that I helped you enough, but you should read the README at least ,ok my friend? :) thanks for using Iris happy coding!

**Comment by cocotyty** [comment]
httpexpect is a very useful and very good package to test handler which  output json/text/xml content.
If handler output html content with template engine,httpexpect may be not suitable.

In tranditional web framework, we have MVC( Model - View - Controller) architecture.
The test code written for the controller may be just input data, check the output data, do not need to care about rendering.

Thank you for your great project,your help,and your patience!
Iris is really greact web framework!

**Comment by kataras** [comment]
@cocotyty , you're welcome but I have to notify you that 

Upgrade your iris with `go get -u github.com/kataras/iris` 

`iris.Tester` is removed, because it produces some httptest flags errors according to [this](https://github.com/kataras/iris/issues/337#issuecomment-253429976)



**old**
```go
import (
	"github.com/kataras/iris"
	"testing"
)

func MyTest(t *testing.T) {
	iris.Get("/mypath", func(ctx *iris.Context){
		ctx.Write("my body")
	})
	// with configs: iris.Config.Tester.ExplicitURL/Debug = true
	e:= iris.Tester(t)
	e.GET("/mypath").Expect().Status(iris.StatusOK).Body().Equal("my body")
}
```
**used that instead/new**
```go
import (
	"github.com/kataras/iris/httptest"
	"github.com/kataras/iris"
	"testing"
)

func MyTest(t *testing.T) {
	// make sure that you reset your default station if you don't use the form of app := iris.New()
	iris.ResetDefault()

	iris.Get("/mypath", func(ctx *iris.Context){
		ctx.Write("my body")
	})

	e:= httptest.New(iris.Default, t)
	// with configs: e:= httptest.New(iris.Default, t, httptest.ExplicitURL(true), httptest.Debug(true))
	e.GET("/mypath").Expect().Status(iris.StatusOK).Body().Equal("my body")
}
```
