### ISSUE TITLE
Iris at Techempower benchmarks.

### ISSUE THREAD

**Issue by taggedboy** [kataras/iris#475]
I would love to have Iris for the performance benchmarks at Techempower against other web technologies.
The [round 13 or Techempower benchmarks](https://www.techempower.com/benchmarks/previews/round13/) is in preview stage, so its a nice time to include Iris and have Iris' included easily in round # 13.

**Comment by kataras** [comment]
I would like that too as I already said on previous post I am expecting from you, as users, to make the benchmarks, none of iris benchmarks done by me for transparency reasons, so I will be gladeful if someone of you add iris on every benchmark suite is possible
