### ISSUE TITLE
Support for static serving of binary assets

### ISSUE THREAD

**Issue by hrwebasst** [kataras/iris#477]
I think it would be valuable for users trying to do something similar to me with something like this:
`iris.StaticServe("/static", "/assets/static").Binary(Asset, AssetNames)`

I understand .Binary is called after a Loader but the concept is very simple, maybe have a StaticLoader? That way we could generate all of our assets with `go-bindata -pkg main -o assets.go assets/...`

with a structure like this:
```
assets/
    templates/
    static/
        javascript/
        css/
```

and we could serve all assets simply with two lines:

```
iris.UseTemplate(django.New()).Directory("./assets/templates", ".html").Binary(Asset, AssetNames)
iris.StaticServe("./static", "/assets/static").Binary(Asset, AssetNames)
```

Part of this request is for serving proper mimetype. "application/javascript", "text/css", etc.

**Comment by kataras** [comment]
Hello,

Look, I think you confuse things,

`Loader, Templates ,.Binary` areonly for the 6 template engines that Iris built'n supports, and they have **nothing** to do with `StaticServe` , Static functions are used to serve all other static files  from directory, from bytes, from filepath and from zipped files.

So, thing like `StaticServe(...).Binary` is not needed. There is a function which let you **serve bytes** from your go-bindata result: it's the `StaticContent` and `context.StaticContent`.

I have already answered to you before. 

Thanks,
kataras
