### ISSUE TITLE
utilize docs.iris-go.com or doc.iris-go.com for documentation

### ISSUE THREAD

**Issue by Liamraystanley** [kataras/iris#480]
Gitbook supports using custom domains (and subdomains) for documentation. I would recommend setting up Iris to use docs.iris-go.com [using this guide](https://help.gitbook.com/books/can-i-use-custom-domain.html)

This is not only more professional, but:

- Gives users a link they can remember
- No more need to go back to the github page, click docs, then click read (using custom domains brings you right to the content under https://kataras.gitbooks.io/iris/content/, not https://www.gitbook.com/book/kataras/iris/details -- which is nice.

**Comment by kataras** [comment]
**Done**,  it's already shown up at https://docs.iris-go.com at my machine, it may take a while to refresh on yours, I will wait 2 days to refresh the README links in order to make sure that all of the user's dns are refreshed.

**Comment by Liamraystanley** [comment]
Awesome, thanks. Looks good on my end. Feel free to close or when you update the links.

**Comment by kataras** [comment]
Yeah, I thanks! the only 'bad' is that users now can't star the book on the gitbook so we will let 2 links to the /details in order to be notable that they can discuss, star and **watch** the gitbook (on the <learn> link and on the image) all other book's links will be updated to the new , I think we are ok

**Comment by Liamraystanley** [comment]
You could add a link (right next to `Don't forget to <star>`, for example) that says "Subscribe to the docs" and links to: https://www.gitbook.com/book/kataras/iris/subscriptions maybe?

**Comment by kataras** [comment]
I care more about **watch** because gitbook is changed on every iris feature add or change happens, I have already a `Don't forget to star` link, it's ok.
