### ISSUE TITLE
Iris on App Engine?

### ISSUE THREAD

**Issue by ctaggart** [kataras/iris#481]
- Version : **4.6.0**

- Operating System: 

- [x] I have read the [book](https://www.gitbook.com/book/kataras/iris/details), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

- [ ] I am an iris [donator](https://github.com/kataras/iris/blob/master/DONATIONS.md).

--------------

Hi, reviewing the [install documentation](https://docs.iris-go.com/install.html), it says `Compatible with go1.7+`. I looked though the [release notes](https://github.com/kataras/iris/releases), but didn't see any mention of Iris ever being compatible with 1.6. From the [App Engine Release Notes](https://cloud.google.com/appengine/docs/go/release-notes), it looks like it has been on Go 1.6.2 since 2016-05-25. It does not appear that Go 1.7 is [not available yet even for testing](https://groups.google.com/forum/#!searchin/google-appengine-go/1.7%7Csort:relevance/google-appengine-go/3K0gJh8qZUE/3pjXrla5AgAJ). Is there a version of Iris that is compatible with App Engine? When Go 1.7 is supported, will it be possible to use Iris? I'm a little confused how you would integrate the two.

**Comment by kataras** [comment]
Dear @ctaggart 

Iris, always, uses the latest Go features, v3 was on go 1.6,  now v4 depends on the go 1.7 changes and improvements, you have to ask App Engine when and how they will support go1.7. You you'll need to check the [fasthttp](https://github.com/valyala/fasthttp) repository and its release notes/post issues about App Engine.  

 My job is to improve and make Iris a better framework day by day for users, I can't wait for App Engine to support go 1.7.  I'm sorry but I think you have to make this question to the App Engine's staff.

Thanks,
kataras

**Comment by ctaggart** [comment]
Thanks @kataras! Iris looks great. I may look into using Iris v3 if support for go 1.7 isn't around the corner.

**Comment by kataras** [comment]
You're welcome, but I have to tell you that if you go with v3 you will be caused by import paths problems, most of the middleware & plugins are moved to `v3` branches instead of the `master`. I think it's better if you can build your web app in a web server supports go1.7 and when you will be ready for publish, then I suppose App Engine will be ready for go1.7 too, I don't know
