### ISSUE TITLE
problem in routing with CORS

### ISSUE THREAD

**Issue by masiqi** [kataras/iris#486]
- Version : **4.6.0**

- Operating System: MacOS

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,kataras
I found a problem in routing with CORS, simple code :
```golang
package main

import (
	"github.com/iris-contrib/middleware/cors"
	"github.com/kataras/iris"
)

func main() {
	r := iris.New(iris.Configuration{FireMethodNotAllowed: true, IsDevelopment: true})
	r.Use(cors.Default())
	r.Put("/a", h)
	r.Post("/b", h)
	r.Post("/ab/cd", h)
	r.Put("/c", h)

	r.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}
```
it will return correctly when I call 
```
curl -X OPTIONS  "http://127.0.0.1:8080/a"
curl -X OPTIONS  "http://127.0.0.1:8080/c"
```
but when i go with "/b", or "/ab/cd" ,it will return "Method Not Allowed"

when i remove "r.Put("/a", h)"
```
    //r.Put("/a", h)
	r.Post("/b", h)
	r.Post("/ab/cd", h)
	r.Put("/c", h)
```
"/b" and "/ab/cd" will ok,but "/c" return "Method Not Allowed"

when i remove "r.Put("/c", h)"
```
    r.Put("/a", h)
	r.Post("/b", h)
	r.Post("/ab/cd", h)
	//r.Put("/c", h)
```
"/a" will ok,but "/b", or "/ab/cd" return "Method Not Allowed"

I think there are some problems in http.go,thank you

**Comment by kataras** [comment]
Hi, @masiqi

There is no problem with http.go you just didnt read  the cors' options and other post issues about your question from [its repository](https://github.com/iris-contrib/middlware) .

None of your routes executes the handler if you call them with `OPTIONS`, you have to put this option:
```go
r.Use(cors.New(cors.Options{OptionsPassthrough: true}))
```
Cors is working fine, pure `OPTIONS` without other header is not allowed normally, you have to specifiy the `OptionsPassthrough` option if you need your routes to respond on pure `OPTIONS` requests also. 
Your routes are working, I just tested it. 

Thanks,
kataras

**Comment by masiqi** [comment]
thank you, kataras
but it doesn't work, in my project ,iris provide api for frontend requests,i don't need response pure OPTIONS ,but the frontend and backend are not in the same domain, and frontend always call api with a JWT token named Authorization in its header, so the browser will make a Preflight request [with OPTIONS method] ,and the backend will give it a "Method Not Allowed" as response, then the browser will not call the api [with POST method]. what i need is browser make a  request with OPTIONS method, iris response 200 ok with CORS response headers, then browser make real api call.i can solve this problem with change routing from "r.Post" to "r.Any",but i think there must have better way, and i don't know how to do that.


```
package main

import (
	"github.com/iris-contrib/middleware/cors"
	"github.com/kataras/iris"
)

func main() {
	r := iris.New(iris.Configuration{FireMethodNotAllowed: true, IsDevelopment: true})
	r.Use(cors.New(cors.Options{OptionsPassthrough: false, Debug: true, AllowedHeaders: []string{"*"}}))
	r.Put("/a", h)
	r.Post("/b", h)
	r.Post("/ab/cd", h)
	r.Any("/d/ef", h)
	r.Put("/c", h)

	r.Listen(":8080")
}

func h(ctx *iris.Context) {
	ctx.Write("Hello from %s", ctx.PathString())
}
```  

in this code snippet, i can get right response with "/d/ef/", "/a" "/c" [curl -X OPTIONS  "http://127.0.0.1:8080/d/ef" -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost'] but will get "Method Not Allowed" with "/b" or "/ab/cd"

```
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 4.6.0 
```

thank you

**Comment by masiqi** [comment]
i don't need OptionsPassthrough = true ,i do not need it go with ctx.Next() ,return ctx.SetStatusCode(iris.StatusOK) is good enough for me

**Comment by masiqi** [comment]
and i tried remove the last break in BuildHandler for i := range mux.garden in http.go then it works

**Comment by kataras** [comment]
Or just remove your setted option `FireMethodNotAllowed` :) 

```go
  r := iris.New(iris.Configuration{FireMethodNotAllowed: true, IsDevelopment: true})
 // to:
  r:= iris.New(iris.OptionIsDevelopment(true))
```

**Comment by masiqi** [comment]
remove FireMethodNotAllowed it responses "not found", doesn't work too

**Comment by kataras** [comment]
It's the same as removing the last for i:= range mux.garden as you said, it should fire 404 not found also, it doesn't ?

**Comment by masiqi** [comment]
@kataras i'm here, if i remove last break in for i := range mux.garden it will work, if i change routing from .Post to .Any it will work ,but i don't think that is the best way
is there any solution i don't need change my routing or modify iris source code and can get Preflight work ?
i have the right mux.garden in http.go line 1143.but it not the first one in the loop,and it will break the loop at line 1215
no matter how i config in cors settings, it will never go with the middleware
