### ISSUE TITLE
Historical commits all gone??

### ISSUE THREAD

**Issue by jamietsao** [kataras/iris#489]
- Version : **4.6.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

I noticed that a commit was made 2 hours ago, and that's the only commit for the entire repo: https://github.com/kataras/iris/commits/master

Was this an accident?  This broke our CI build because a previous version/commit no longer exists.

- J

**Comment by kataras** [comment]
Yes, each new version has clean history because my local git goes up to 800MB and I can't transfer it easly to my other home, this has zero affects to you as users

**Comment by kataras** [comment]
Yes, each new version has clean history because my local git goes up to 800MB and I can't transfer it easly to my other home, this has zero affects to you as users. 

Please use the golang vendor instead of glide and you should no have any issues , or use the release zipped file
