### ISSUE TITLE
Reverse Proxy Related

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#49]
This is a Reverse Proxy related feature request:

***

I notice that on _Echo_ webserver when it is run behind _nginx_ reverse proxy eg:
```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:1234;
  }
```

Echo somehow makes it such that <ins>c.Request.RemoteAddr</ins> is the correct IP address which is supplied by _nginx_. Maybe it thinks since **X-Forwarded-For** or **X-Real-IP** has been supplied then it must be the real IP, and it replaces the value in <ins>c.Request.RemoteAddr</ins> with that for user convenience.

If that was available on _Iris_ it would be nice. Hopefully this won't slow down _Iris_ at all.

**Comment by kataras** [comment]
@kryptodev  No it's not,I know how to do that I did before with jboss repo wait 5 minutes

**Comment by kryptodev** [comment]
Edit: The requested feature works with the following middleware:
`https://github.com/sebest/xff`

How it looks:
`log.Fatal(http.ListenAndServe(":8080", xff.Handler(iris.Serve())))`

But that middleware repo is a little old and it's best we keep one for Iris use, maybe a middleware.

Thanks. :)

**Comment by kataras** [comment]
@kryptodev  Ok I think I did it , can you test it? the method is the context. RequestIP()

**Comment by kryptodev** [comment]
Maybe if you put that feature in context.RemoteAddr it would be better.

For example my code already has many calls for context.RemoteAddr, now will have to replace them all with RequestIP. Also for future logger, how will the logger know which function to use to find out real IP because the server can be running behind Nginx.

Not sure if I made myself clear.

In simple word, if context.RemoteAddr can automatically decide which the real IP is then that is better. Just like that middleware.

**Comment by kataras** [comment]
https://github.com/kataras/iris/issues/49

**Comment by kataras** [comment]
@kryptodev  Look, the RequestIP returns the RemoteAddr if no proxy is used, so I think it's working. But you mean I must rename the RequestIP to RemoteAddr and RemoteAddr to RequestIP ?

**Comment by kryptodev** [comment]
Just keep one function, RemoteAddr, it returns normal IP if no proxy is used or X-Forwarded-For/X-Real-IP(etc.) if behind proxy.:relaxed:

**Comment by kataras** [comment]
@kryptodev RemoteAddr makes your work now ( reverse the func names) I want to keep both of them, because the RequestIP is faster than RemoteAddr, so if I'm not using proxy and I want to get the Ip fast i will use the just the RequestIP, don't forget we must continue be the fastest

**Comment by kataras** [comment]
Also can I ask you to help me with the readme on one place? I want to add a section which will tell to the users that they can recommend features and discuss about he future of Iris, and what the community decides is improtant to me I want really to make real the moto ' by the community, for the community'.

**Comment by kryptodev** [comment]
@kataras True :) Thank you!

If my idea makes performance cost then it's best we reverse what you did. I don't want other people to suffer for it.

I can just use the middleware https://github.com/sebest/xff

Upto you for final decision. Thanks! :) 
Maybe keep this open for other people to put their suggestions.

**Comment by kataras** [comment]
@kryptodev  No no the performance is untouchable now we just create a function nothing more we don't call it inside anywhere don't worry :P , no need of middlewares, just call context.RemoteAddr(), I thanks you hope you like Iris, I just finished with the  Internationalization and Localization middleware which you can find [here](https://github.com/kataras/iris/tree/examples/middleware_internationalization_i18n) tell me your opinion

**Comment by kryptodev** [comment]
@kataras Yup I actually switched from Echo to this. Loving it. All we need is a smart logger middleware and we go big :P

**Comment by kataras** [comment]
@kryptodev Thanks you for nice words!! Hmm logger is the easier  I think, can I ask you ; you need a logger than can log to any io.Writer no just terminal output or file, right?

**Comment by kryptodev** [comment]
@kataras Terminal output, maybe you can make it optional, terminal or filebase.

**Comment by kataras** [comment]
@kryptodev Please go to issue #50 and write it again so I can answer you there :P

**Comment by kryptodev** [comment]
I just noticed that you created a separate function for it lol.
I think there was some confusion, you implemented c.RemoteAddr(), when my real request was to make that feature available on c.Request.RemoteAddr so I can use it in the handler functions for every route. My setup is behind nginx.

**Comment by kataras** [comment]
Then I don't understand what you asked me to do, and you say it now..?  again I don't understand what's the difference of using the c.RemoteAddr() of the c.Request.RemoteAddr ? if you want to modify the c.Request.RemoteAddr then it will have a performance issue for every request even if you don't use a proxy... so tommorow we can just create a middleware which will call the c.RemoteAddr() and put it's contents to the c.Request.RemoteAddr , this is you asking for ?

**Comment by kryptodev** [comment]
Yep, in all confusion, I think that is the best idea :)

**Comment by kataras** [comment]
Yeah just use that.I dont think we must create a new middleware folder for this, is that ok?

**Comment by kryptodev** [comment]
@kataras Sounds good buddy.

**Comment by kataras** [comment]
@kryptodev Good, tomorrow i'll will create and the logger, I am not doing this today because I want to wait until tomorrow for any suggestions to the issue #50 ... if nothing comes i'll do it with my own experience and if anyone wants to change something just  post to the #50
