### ISSUE TITLE
Error : Not possible to fast-forward, aborting.

### ISSUE THREAD

**Issue by SulthonZH** [kataras/iris#493]
- Version : **V4 LTS**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi, I got error whe go get 

like this 
\# cd /home/habib/Documents/project/go/src/github.com/kataras/iris; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/kataras/iris/iris: exit status 128

**Comment by kataras** [comment]
Hello, 
You have to **upgrade** iris as we always do when a new version comes up, follow these steps:

1. Remove your `$GOPATH/src/github.com/kataras` 
2. Open your terminal/shell
3. Execute `go get -u github.com/kataras/iris/iris` 

You're ready :)

Reference: [HISTORY.md -how to upgrade](https://github.com/kataras/iris/blob/master/HISTORY.md)

**Comment by peterbourgon** [comment]
Squashing the entire contribution history in the repo to a single commit whenever you produce a release is not an acceptable way to maintain an open-source project. It prevents users from tracking stable (for them) versions of your code as a library, breaks third-party tools and integrations that assume mainline commit SHAs are immutable, and subverts contributors to your project, whose contributions are erased from history, and whose work you duplicitiously claim as your own.

**Comment by SulthonZH** [comment]
OK, I'm ready. 👍  Thank you very much

**Comment by kataras** [comment]
You're welcome, happy coding!
