### ISSUE TITLE
Question: How to manage preflighted CORS

### ISSUE THREAD

**Issue by afboteros** [kataras/iris#498]
- Version : **V4 LTS**

- Operating System: Arch Linux

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi, i'm getting the following error when making a request to Iris with angularjs resource:
`
XMLHttpRequest cannot load http://externalurl.com:3001/action. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
`

I have CORS configured this way on main.go file:
`
//Cors
iris.Use(cors.New(cors.Options{
	AllowedMethods:     []string{"GET", "POST", "OPTIONS", "HEAD"},
	AllowedOrigins:     []string{"*"},
	AllowedHeaders:     []string{"*"},
	ExposedHeaders:     []string{"*"},
	OptionsPassthrough: true,
	MaxAge:             3600,
}))
`

Any idea what i'm missing here?, thanks for your help.

**Comment by kataras** [comment]
Hello abroteros,

Could you please read the contribution file and post it to the [correct repository](https://github.com/iris-contrib/middleware)?

You may fine your answer and the solution to your problem through older cors-releated [post issues](https://github.com/iris-contrib/middleware/issues).

Thanks,
kataras

**Comment by kataras** [comment]
Hello abroteros,

You may fine your answer and the solution to your problem through older cors-releated [post issues](https://github.com/iris-contrib/middleware/issues).

But if you don't, could you please read the contribution file and post it to the [correct repository](https://github.com/iris-contrib/middleware)?



Thanks,
kataras

**Comment by afboteros** [comment]
Hello kataras,

Ok, thanks.

**Comment by kataras** [comment]
Reference: https://github.com/iris-contrib/middleware/issues/17
