### ISSUE TITLE
Feature: Logger

### ISSUE THREAD

**Issue by kataras** [kataras/iris#50]
First of all is a logger needed here? golang has already the 'log' package. Secondly if  you think yes it's good to have a logger inside Iris , using the log package, write below how you want a logger to work, and how you imagine/want to write the code [write down some code snippets/examples] in order to enable and configure the logger? as  a middleware function or something different  ?  Logs what? requests (as middleware) something else like debuging? I am not taking these decisions alone so please come, we are a community write down your ideas!

**Comment by kryptodev** [comment]
By default webservers choose their own verbosity level, for example Gin's logger middleware shows you the IP, and how long it took to respond to the request,
But echo's logger also shows parameters and some additional stuff.

So for Iris, maybe it's best to make the logger configurable. People can choose how verbose they want, maybe very verbose with all parameter logging, IP address, etc. or very minimal, with just IP address and route.

I think this would be a good feature to have, so people can choose to up the verbosity if they want, or make it very low to their needs without much impact to performance.

**Comment by kataras** [comment]
@kryptodev  first version/ look of the logger middleware is finished,  check [here](https://github.com/kataras/iris/tree/examples/middleware_logger) and tell us your thoughs! thanks!

**Comment by kryptodev** [comment]
Great work Kataras!

**Comment by kataras** [comment]
@kryptodev Thanks!! you can define your own writer with .Custom(writer io.Writer, prefix string, flag int, options ...Options) also, if you have more ideas write here!!

**Comment by peterbe** [comment]
> @kryptodev first version/ look of the logger middleware is finished, check here and tell us your thoughs! thanks!

That link now 404s.

**Comment by raitucarp** [comment]
@peterbe he move all the examples to iris-contrib

**Comment by raitucarp** [comment]
https://github.com/iris-contrib/examples/tree/master/middleware_logger

**Comment by kataras** [comment]
@peterbe  The book contains always the correct but some older comments not, Fixed now thanks!
