### ISSUE TITLE
Cross domain settings？

### ISSUE THREAD

**Issue by xinjiayu** [kataras/iris#501]
How to set? 

old    ==>	iris.Config.Websocket.Headers["Access-Control-Allow-Origin"] = "*"

now ==>   ????   How to set?

**Comment by kataras** [comment]
Hello @xinjiayu 

You have nothing to do now, **All Origins Are Accepted on Websockets by default**

But if you want to change this behavior:
It's not so hard, it's a function `CheckOrigin` which takes context and returns boolean.
 
Now, https://github.com/kataras/iris/blob/master/configuration.go#L686 
```go
iris.Config.Websocket.CheckOrigin = func(ctx *iris.Context){
        // if you had * on headers before then here, just return true, that's defaults.
       return true
}

```

Thanks,
kataras

**Comment by xinjiayu** [comment]
Thanks
