### ISSUE TITLE
Adding a "raw write" option to iris.Context

### ISSUE THREAD

**Issue by skyflyer** [kataras/iris#507]
- Version : 4.4.4

- Operating System: OS X and Linux

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

I hope I'm just missing something, but I've stumbled upon a challenge today, where I tried to render a custom response to the output stream. By custom, I mean dynamic, where I don't know in advance what kind of content type the request will be (it is a "reverse proxy" scenario).

I know there are custom serializers and there are many ways to render different objects to output. What I needed in this case, was a way to render some bytes with some `Content-Type` header, which was not known before hand (retrieved dynamically).

I was surprised that I could not simply use a `RenderWithStatus(iris.StatusOk, "custom/mime", []byte(`some data here`)) approach, because it requires the serializer. In the end, I implemented a rather ugly workaround by wrapping the net.http handlerfunc like so:

```go
			ctype := "image/jpeg"
			content := []byte(`image here`)

			innerHandlerWorkaround := iris.ToHandlerFunc(
			func(writer http.ResponseWriter, request *http.Request) {
				writer.Header().Add("Content-Type", ctype)
				writer.Write(content)

			})
		innerHandlerWorkaround.Serve(ctx)
```

Did I miss the function to write RAW data with a custom mime type somewhere or... is it really missing?

**Comment by kataras** [comment]
Hello @skyflyer 


No need to use net/http handler, this will slow your web, iris is built on top of fasthttp. If you want to just write raw data. use this:

`context.SetBody(bytes)`

Also you can make use of the `context.Render` , see how `context.JSON/XML` are written, iris supports customize serializers with custom content type for your need case also!
 
> And thank you very much

**Comment by skyflyer** [comment]
Excellent, this is exactly what I was looking for. I will create a PR for documentation in case somebody else needs this in the future. Will close this now, thanks!

**Comment by kataras** [comment]
You're welcome!

The book's repository is there: https://github.com/iris-contrib/gitbook
