### ISSUE TITLE
How to make... websockets

### ISSUE THREAD

**Issue by monopollly** [kataras/iris#508]
- Version : **V4-LTS**

- Operating System: mac os 

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

could you explain me please...

I want to make websocket server but I don't know the right way for clients auth
could you please write a right pattern for it?

for example I check a cookie with token in middleware and how to send a result to websocket connection?

```go
//auth middleware
iris.UseFunc(func(c *iris.Context){
//...check token here from cookie
// ok, go next...
c.Next()
})

iris.Config.Websocket.Endpoint = "/"
iris.Websocket.OnConnection(func(c iris.WebsocketConnection){
//token is ok and now client is connected  
//but how to get result from middleware here?
})
```

thank you!

**Comment by kataras** [comment]
Hi @monopollly 

Look, you don't have direct access to http whole context via `websockets` , and you shouldn't, they are different 'protocols'.

This has been asked before, and **users find a solution which is better than sharing a context**  between websocket clients, **read** the whole **issue post** here, it will helps you to think it right: https://github.com/kataras/iris/issues/372#issuecomment-242985720 

Thanks,
kataras

**Comment by kataras** [comment]
Reference: https://github.com/kataras/iris/issues/372

**Comment by monopollly** [comment]
hm its interesting but i try to find a better solution

could I control a handshake and get a access token as part of it, and then decide open connection or denied?

**Comment by kataras** [comment]
Yes, the authentication should be before websocket connection, and the OnConnection should check if that user is verified/authenticated or not if not it can `Close()` the connection , if you look at the post issue you will understand, I gave an idea to a user which I used but he/she posted an alternative (and probably) better solution

**Comment by monopollly** [comment]
Maybe was I explained not so good, sorry)
But thats the simple way to do it, this is the solution...
```go
func main() {
 //use a middleware for upgrade connection
 iris.UseFunc(auth)

 //websocket setup
 iris.Config.Websocket.Endpoint = "/"
 iris.Websocket.OnConnection(router)
 iris.Listen(port)	
}

func auth(ctx *iris.Context){
 //get cookies
 token:=c.GetCookie("token")
 // do some with token
 // and if token is ok do upgrade the connection
 // or reject... 
 iris.Websocket.Upgrade(ctx)
 iris.Websocket.OnConnection(func(c iris.WebsocketConnection){
       //now connect only if token is good
       c.OnMessage(func(message []byte){
             //messages
       }
})
}
```
so, now I have a full control of websocket connections
yeah, maybe its not ideal but now I don't need any additional things thats I talking about...)

Thank you for Iris man;)

**Comment by monopollly** [comment]
Maybe we could post this example to the book, cause its helpfull what do you think?

**Comment by kataras** [comment]
No this is not the correct solution, you thinking it wrong, you didn't read the link I sent you :/

-  **kataras, why is wrong?**

The `auth->OnConnection` will be register on connections events on each http request! this will be overhead you will have thousand of events with the same job without reason

**Comment by monopollly** [comment]
yep I am stupied, sorry for annoy)
but... maybe you can write a small "right" real example for auth?
you know... when you will have a time? I will be really grateful for you.

**Comment by kataras** [comment]
Okay, I can do that, keep note that developers can do this with more than one solution, however I cannot write all of them so I'll put a small example when I find some time

**Comment by monopollly** [comment]
It will be nice really, I just try to understand a websockets,
and I really confuse that no simple way to share some data between http and websockets, considering that websockets comes from http upgrade...

**Comment by kataras** [comment]
I could add context access but , as software designer I'm telling you that this is not the correct solution, it seems easier but many things may gone wrong, One probably solution (flow) can be: Client connects to websocket, server accepts connection and waits for ws authentication(`.On`), client sends an event(`.emit`) with data for authentication, websocket server accepts this and checks (the database) for authentication, if failed the client connection is `Close()`

**Comment by kataras** [comment]
If we add context access then websocket will be much more slower on connection and `Response` will be closed, so all context methods for writing to the client will not work as expected and then users will ask for questions and I have to explain this from the beggining... because websocket upgrades with hijack

**Comment by kataras** [comment]
I will look further on this to make it easier for newcomers, like you, give me some time because I'm working on something else the last hours,ok?

**Comment by kataras** [comment]
`*http.Request` access from Websockets

Example:

- https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34

Relative commits to kataras/go-websocket:

- kataras/go-websocket@550fc8b

- kataras/go-websocket@62c2d98

> use the `c.Request()` only when you really need it, websockets have everything you need already.
