### ISSUE TITLE
commits gone away ?

### ISSUE THREAD

**Issue by plouc** [kataras/iris#512]
- Version : *doesn't matter for the scope of this issue*
- Operating System: *doesn't matter for the scope of this issue*

--------------

Hi,

Thank you for Iris.

I'm using [glide](https://github.com/Masterminds/glide) to manage my go dependencies, I've got  a sha1 in my `glide.lock`file which si no more valid **2336c01ccfa5367a1dcf2c16ebb54ef64e17c5d3**, are you rewriting git history or am I missing something ?

Regards
Raphaël

**Comment by plouc** [comment]
We're few people working on the project using iris, so it's quite an issue as none of my teammates were not able to install the project.

**Comment by kataras** [comment]
Commits are there, please make sure that you manage your glide correctly, I am not responsible for any `glide things` and I am not recommending using glide, there is no reason when you have vendoring, but that's another history..

**Comment by porty** [comment]
@plouc Itis' git history is continually rewritten to avoid extra contributors being attributed - I'd recommend not vendoring Iris, or ditching it entirely
