### ISSUE TITLE
Request sprig template engine integration

### ISSUE THREAD

**Issue by themotu** [kataras/iris#514]
- Version : **V4-LTS**
- Operating System:
- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

---

Hi,

I think this would be a great addition as a template engine. 

https://github.com/Masterminds/sprig/

**Comment by kataras** [comment]
Hi, 

This sounds good, I'll try to find sometime for this template engine too, thanks!


> As contributing file says, please the next time post issues or feature requests, to the correct [repository](https://github.com/kataras/go-template).

**Comment by dxvgef** [comment]
Perhaps Fast Template is the better choice 😏

**Comment by kataras** [comment]
@dxvgef  You can already use Fast Template with iris and quicktemplate also :)

**Comment by dxvgef** [comment]
@kataras Where has its middleware ❓

**Comment by kataras** [comment]
@dxvgef I didn't get it, why you need a middleware for this? middleware will not help you on fast template and quicktemplate, middleware are something we use between handlers

**Comment by dxvgef** [comment]
@kataras How do I integrate it with Iris?

**Comment by kataras** [comment]
They are waiting for an `io.Writer`, you can pass the `context.Response.BodyWriter` , as with all other template engines that expecting an `io.Writer` (any serious template engine expects a parameter like this to execute a template)

**Comment by kataras** [comment]
They are waiting for an `io.Writer`, you can pass the `context.Response.BodyWriter` , as with all other template engines that expecting an `io.Writer` (any serious template parser should expects a parameter like this to execute a template)
