### ISSUE TITLE
From address while sending email

### ISSUE THREAD

**Issue by tkshnwesper** [kataras/iris#515]
- Version : **V4-LTS**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

I am facing an issue while sending email. When I send mail, Iris sets my *from address* as the **Username** without the '@' + Host name appended to it. It is causing a problem because whenever I send to Gmail, it marks it as spam :cry:

The functionality that would help me will be either of these:
1. To allow setting a from address, or
2. To set from address as `Username@Host`

For the time being I can use [Golang API](https://golang.org/pkg/net/smtp/) for sending emails, but I felt it would be good to let you know :smile:

**Comment by kataras** [comment]
Hello @tkshnwesper , Maybe you post on the wrong repository, iris doesn't provides e-mail sender.

What do you mean `Iris sets my from address as the Username without the '@' + Host name appended to it` ? Iris doesn't provides e-mail sender built'n, we have an external package , named [go-mailer](https://github.com/kataras/go-mailer).

If you mean `http url path` then you should make sure that you read the docs and set this configuration field:

```go
iris.Config.DisablePathEscape  = true 
```

Did that helped you?

Thanks,
kataras

**Comment by kataras** [comment]
Hello @tkshnwesper , Maybe you post on the wrong repository, iris doesn't provides e-mail sender.

What do you mean `Iris sets my from address as the Username without the '@' + Host name appended to it` ? Iris doesn't provides e-mail sender built'n, we have an external package , named [go-mailer](https://github.com/kataras/go-mailer) which can send e-mail without any `http` action.

**BUT** If you mean `http url path` then you should make sure that you read the docs and set this configuration field:

```go
iris.Config.DisablePathEscape  = true 
```

Did that helped you?

Thanks,
kataras

**Comment by tkshnwesper** [comment]
> Maybe you post on the wrong repository, iris doesn't provides e-mail sender.

Sorry I didn't realize at the time of posting, I should have posted this in [go-mailer](https://github.com/kataras/go-mailer) as you said.


> What do you mean Iris sets my from address as the Username without the '@' + Host name appended to it ?

Okay, to answer this question, this is what the details of the email look like when I send it with go-mailer (goes into spam):

```
from:	saurabh <saurabh> via mail.example.com
to:	xyz@gmail.com
date: 	Thu, Oct 27, 2016 at 11:06 PM
subject:	Some subject
mailed-by:	mail.example.com
encryption:	Standard (TLS) Learn more
```

And this is what it looks like when I send it using Squirrelmail (goes into inbox):

```
from:	saurabh@mail.example.com
to:	xyz@gmail.com
date: 	Thu, Oct 27, 2016 at 10:26 PM
subject:	Some subject
mailed-by:	mail.example.com
encryption:	Standard (TLS) Learn more
```

(Only the **from** field is relevant)

So, in the first example the from address is just `saurabh` (between the pair of chevrons, because the first `saurabh` is set by the `FromAlias` parameter) which I am using as my `Username`. On the other hand, in the second example, the from address is *valid*, so Gmail allows it to go into my inbox. I could not find any way to set my from address using the [API](https://docs.iris-go.com/mail.html) provided by Iris or go-mailer as you say.

**Comment by kataras** [comment]
@tkshnwesper Could you please upgrade the `go-mailer` : `go get github.com/kataras/go-mailer` and test again with the new configuration `FromAddr` ?

**Comment by kataras** [comment]
@tkshnwesper Could you please upgrade the `go-mailer` : `go get -u github.com/kataras/go-mailer` and test again with the new configuration `FromAddr` ?

**Comment by kataras** [comment]
@tkshnwesper Could you please upgrade the `go-mailer` : `go get -u github.com/kataras/go-mailer` and test again with the new configuration field `FromAddr`? Thanks

**Comment by tkshnwesper** [comment]
@kataras Thank you! That did the trick.

Just a reminder that you forgot to add the `FromAddr` field in the `README.md`.
