### ISSUE TITLE
Why is DefaultServerName is always prefixed with "iris_"

### ISSUE THREAD

**Issue by pieterclaerhout** [kataras/iris#516]
Hi,

we wanted to customize the DefaultServerName as follows:

```golang
iris.DefaultServerName = "My Server Name"
```

However, when testing what is returned in the HTTP Headers, it seems that it's always prefixed with "iris_":

```
HTTP/1.1 200 OK
Server: iris_My Server Name
Date: Fri, 28 Oct 2016 07:27:26 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 9
```

Is this on purpose or is there a way to remove this prefix?

**Comment by kataras** [comment]
Hello @pieterclaerhout ,

Ofcourse you can change it, it's just a header  `context.Response.Header.Add("Server", "myserver")`  :)

Cheers,
kataras

**Comment by pieterclaerhout** [comment]
I just figured out you can do this easily using middleware.

However, you need to use `c.Response.Header.Set` instead of `c.Response.Header.Add`, or you will get duplicate headers (which seems a bit weird).

```go
func ServerHeaderMiddleware(c *iris.Context) {
	c.Response.Header.Set("Server", "My Server Name")
	c.Next()
}
```

**Comment by kataras** [comment]
Exactly, with Iris it's easy, you can customize anything :)
