### ISSUE TITLE
After refreshed , it show nothing?!

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#52]
when visit  ```http://localhost:8080/aa```, the browser first shows  is  ok.  but after  refresh the webbrowser, it shows nothing?  as  following:
```
package main

import (
	"github.com/kataras/iris"
)

func f1(c *iris.Context) {
	println("i am f1!")
	c.Next()
}
func f2(c *iris.Context) {
	println("i am f2!")
	c.Next()
}
func main() {
	iris.Get("/aa", f1, f2, func(c *iris.Context) {
		println("it is test func!")
		c.Write("the string to browser")
	})
	iris.Listen(":8080")
}

```

**Comment by kataras** [comment]
@xpbliss  man are you sure? this code you gave me it's working on me... can you try to update your Iris ?

**Comment by xpbliss** [comment]
after  ```go get -u github.com/kataras/iris```, it's ok.
thanks!

**Comment by kataras** [comment]
@xpbliss  Yeah, I do a lot of updates and changes and some versions are full of bugs but every night the Iris is working so update it every night ahah <3
