### ISSUE TITLE
about file upload 

### ISSUE THREAD

**Issue by hugcoday** [kataras/iris#522]
there have two way to  uplaod file  , one way is form-data ,the other is binary

like postman client  upload  like this:

![qq 20161103093839](https://cloud.githubusercontent.com/assets/324961/19953493/58b25422-a1a9-11e6-9918-1c04bea1bef6.png)

but I can't find the iris how to support the binary way , How to do ?

**Comment by kataras** [comment]
You will not find examples for each case, examples just gives you an idea and the basic structs that you can use with Iris, we will need more than 1million examples to show what Iris can do...

You have access to the full request  via `context.Request` and to the Response via `context.Response` there, you will find all functions that you need to read from client's request `context.Request.Body() and stream readers` and to write to the client(`context.Response.Write` and other stream writers)

**Comment by hugcoday** [comment]
Ok I know how to work.  thanks.

by way,this function supported by nodejs php java ,it's good to use then form-data file upload,  because upload file may be failed, when form-data has other data ,the server can't get the other data. so this function only  file upload, it's good choice

**Comment by kataras** [comment]
Yes, I agree with you, but if you implement a binary uploader why you don't make a PR to the [examples repository](https://github.com/iris-contrib/examples) in order to help other people, like I'm doing everyday?

**Comment by kataras** [comment]
Yes, I agree with you, we must help new developers to learn. Like you wanted help from me, other people may need help on this too, so if you found the solution, I'm asking you to make a PR to the [examples repository](https://github.com/iris-contrib/examples). Get involved, don't expect no one to help you if you don't help others :) 

Thanks!
