### ISSUE TITLE
Session function problem

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#524]
- Version : **V4-LTS**
--------------
Hi,
I get no data in the session, use the GetInt() function

``` Go
package main

import (
	"log"
	"github.com/kataras/iris"
)

func main() {
	var test int64 = 11111
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Session().Set("test", test)
	})
	iris.Get("/get", func(ctx *iris.Context) {
		log.Println(ctx.Session().Get("test"))
		log.Println(ctx.Session().GetInt("test"))
		log.Println(ctx.Session().GetString("test"))
		log.Println(ctx.Session().GetAll())
	})
	iris.Listen(":8080")
}
```

Output:
```
2016/11/06 04:35:35 11111
2016/11/06 04:35:35 -1
2016/11/06 04:35:35 
2016/11/06 04:35:35 map[test:11111]
```

Very urgent! Hope to repair the bug as soon as possible, thank you!

**Comment by dxvgef** [comment]
I looked at the source code, the `GetInt()` function will judge this value is a int type, If it is not, return `-1`, so this is not a bug, but it will make me misunderstand that it has no value, can you join `GetFloat() GetFloat64() GetBool() GetInt64()` these functions into the Iris?

**Comment by kataras** [comment]
Yes, if you can change the title :)

**Comment by kataras** [comment]
I'll add an error value to the GetInt then no problem

**Comment by kataras** [comment]
```go
type Session interface {
  ID() string
  Get(string) interface{}
  GetString(key string) string
  GetInt(key string) (int, error)
  GetInt64(key string) (int64, error)
  GetFloat32(key string) (float32, error)
  GetFloat64(key string) (float64, error)
  GetBoolean(key string) (bool, error)
  GetAll() map[string]interface{}
  VisitAll(cb func(k string, v interface{}))
  Set(string, interface{})
  Delete(string)
  Clear()
}

```

Done, please the next time post session feature requests at [the go-sessions repository](https://github.com/kataras/go-sessions)

**Comment by dxvgef** [comment]
Good job! Thank you!
