### ISSUE TITLE
How to get HTTP Referer URL?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#525]
- Version : **V4-LTS**

--------------

Hi, how can I get http referer url in iris?

**Comment by kataras** [comment]
Hi,
`Referer` is just a header, you don't know how to get a header in Iris then,

```go

func(ctx *iris.Context){
   referer := ctx.RequestHeader("Referer")
}

```

Hope that helps you

**Comment by kataras** [comment]
Hi,

`Referer` is just a header, you can get header's values from request using the `context.RequestHeader` 
 or response headers using `context.Response.Header` , example:
``` go

func(ctx *iris.Context){
   referer := ctx.RequestHeader("Referer")
}

```

But do not rely on http referer header, it can be alted, read more here: http://stackoverflow.com/questions/6023941/how-reliable-is-http-referer

Hope that helps you

**Comment by dxvgef** [comment]
OK, thank you!

**Comment by kataras** [comment]
In your services, as always :)
