### ISSUE TITLE
Context's functional recommendations

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#526]
- Version : **V4-LTS**

--------------

Hi, @kataras !
First of all thank you for developing such a great project, I will donate it after I used it to develop my project.
But I hope to be able to add the following values type conversion function, so that we can reduce the amount of the underlying processing, focusing on the development of the business logic of the project:

- ctx.FormValueToInt()
- ctx.FormValueToInt64()
- ctx.FormValueToFloat32()
- ctx.FormValueToFloat64()
- ctx.FormValueToBool()
- ctx.ParamToInt()
- ctx.ParamToInt64()
- ctx.ParamToFloat32()
- ctx.ParamToFloat64()
- ctx.ParamToBool()

Now I see that there have been `ctx.FormValueString()` and `ctx.ParamInt()`, and so on a number of related functions, since it has been done why not more perfect?
If you accept my PR, I can submit my code to complete these functions.

**Comment by kataras** [comment]
Too much functions without reason @dxvgef , sorry I can't accept these things, it's a web framework not an number library ...

**Comment by dxvgef** [comment]
I have developed a package for the type conversion work, then I will continue to use it, thank you!

**Comment by kataras** [comment]
You're welcome, I thanks!
