### ISSUE TITLE
HTTP OPTIONS request header (preflight) return 404

### ISSUE THREAD

**Issue by thesyncim** [kataras/iris#53]
```go
func (r *RouterDomain) processRequest(ctx *Context) bool {
	reqPath := ctx.Request.URL.Path
	gLen := len(r.garden)
	for i := 0; i < gLen; i++ {
		if r.garden[i].hosts {
			//it's expecting host
			if r.garden[i].domain != ctx.Request.Host {
				//but this is not the host we were expecting, so just continue to the next
				continue
			}
			reqPath = ctx.Request.Host + reqPath
		}
		if r.garden[i].method == ctx.Request.Method {   //<--"i think this is the cause "

			return r.find(r.garden[i], reqPath, ctx)
		}

	}
	ctx.NotFound()
	return false
}

```

**Comment by thesyncim** [comment]
this fixes the isue

```go
func (r *RouterDomain) processRequest(ctx *Context) bool {
    reqPath := ctx.Request.URL.Path
    gLen := len(r.garden)
    for i := 0; i < gLen; i++ {
        if r.garden[i].hosts {
            //it's expecting host
            if r.garden[i].domain != ctx.Request.Host {
                //but this is not the host we were expecting, so just continue to the next
                continue
            }
            reqPath = ctx.Request.Host + reqPath
        }
        if r.garden[i].method == ctx.Request.Method  || ctx.Request.Method == "OPTIONS"{  

            return r.find(r.garden[i], reqPath, ctx)
        }

    }
    ctx.NotFound()
    return false
}

//and here
func (r *Router) processRequest(ctx *Context) bool {
	reqPath := ctx.Request.URL.Path
	method := ctx.Request.Method
	gLen := len(r.garden)
	for i := 0; i < gLen; i++ {
		if r.garden[i].method == method || ctx.Request.Method == "OPTIONS" {
			return r.find(r.garden[i], reqPath, ctx)
		}
	}
	ctx.NotFound()
	return false
}

```

**Comment by kataras** [comment]
@thesyncim  if you register an Options route it will be handle well no 404, you want the 'OPTIONS' to be avaiable to ANY http methods (get,put and post and delete?)

**Comment by thesyncim** [comment]
Its required by CORS 


so if i have something like 

```go
iris.Post("/corsurl", func(c *iris.Context) {
        c.Write("hi")
})
```

browsers will "preflight" the request with an HTTP OPTIONS (check bold text)


from https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the set of origins that are permitted to read that information using a web browser. Additionally, for HTTP request methods that can cause side-effects on user data (in particular, for HTTP methods other than GET, or for POST usage with certain MIME types), the specification mandates that browsers "preflight" the request, **soliciting supported methods from the server with an HTTP OPTIONS request header, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method**. Servers can also notify clients whether "credentials" (including Cookies and HTTP Authentication data) should be sent with requests.

**Comment by thesyncim** [comment]
this can also be fixed inside cors middleware

**Comment by kataras** [comment]
I know the specification but I though that the CORS middleware ( I didn't write that middleware) do that work, so you have right but if I do that you suggest inside the Router so we will have performance cost ( because of the second OR if check ) and doesn't seems right to me because this can be procude other routing missunderstaning and wrongs...

Hmm we could make it differently, If I add build'n support for CORS without the middleware I can create a new router which will be used only if you use the CORS option inside the StationOptions but this is wrong too because it will make all routes as domain shared and that's not good, so I am thinking of making something like that: 
```go
//...
iris.PostCORS("/corssomething", func(ctx *iris.Context){})
//...

```
instead of 
```go
//...
import "github.com/kataras/iris/middleware/cors"
///...
iris.Post("/corssomething",cors.Cors(), func(ctx *iris.Context){})
```

is that ok or .. no ?

**Comment by thesyncim** [comment]
yeah that would work too. 
that's fine for me.

but maybe we also need :
iris.DeleteCORS
iris.PatchCORS  
iris.PutCORS    
iris.HeadCORS     

thank you

**Comment by kataras** [comment]
Yes with //... I meant an of that :P so it will be no problem to use them? the problem is that the conversation will be to rename the functions if you even choose to disallow other domains... I am thinking of this but sure today I'll find a sollution and write here when this is ready, ok ? for now`,temporary just do that: 
```go
//...
import "github.com/kataras/iris/middleware/cors"
//...
myCors:= iris.Party("/corssomething")
{
    myCors.Use(cors.Cors())
    myCors.Post("/", func (c *iris.Context){})
    myCors.Options("/", func (c *iris.Context){})
}

iris.Listen()

```

**Comment by thesyncim** [comment]
ok!
Take your time, no worries.

greetings from Portugal

**Comment by kataras** [comment]
@thesyncim Hello I think I found a solution with no performance cost, can you please check if that works? update the iris using 
``` 
go get -u github.com/kataras/iris

``` 
and just pass the kataras/iris/middleware/cors as you did before and check it with .Post for example ( no need of PostCors )
Write here if that works or not thanks !!
Cheers from Greece brother!!!

**Comment by thesyncim** [comment]
you need to export isMethodAllowed .
Maybe move coors middleware inside iris to be less awkward  .what do you think?

**Comment by kataras** [comment]
@thesyncim  I approve your pull request, thanks can you try it again? ( I though to move this inside iris but we will see at the future, I have to finish some things first)

**Comment by thesyncim** [comment]
yep, working as intended
