### ISSUE TITLE
i need your email

### ISSUE THREAD

**Issue by airinfection** [kataras/iris#530]
put somewhere your email i will send something regularly.

**Gerasimos Fan**

**Comment by kataras** [comment]
My friend, this is not the place for asking me for personal things, this is a repository of the oneof the greatest web frameworks ever created for a system programming language, it's too poor to ask something like this in the issues pages. 

- We have a [chat](https://kataras.rocket.chat/channel/iris) which you can click on my name and ask me private things if you'd like so.

- Go to my github profile and you'll see my personal website at the description, there you will find my twitter,facebook and everything you like if you want to contact with me. 

Thanks.
