### ISSUE TITLE
URL typo in godocs

### ISSUE THREAD

**Issue by joohoi** [kataras/iris#531]
- Version : **5.0.1**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi,

I noticed the links provided in docs for two functions have a typo in them:

https://github.com/kataras/iris/blob/master/iris.go#L540
and
https://github.com/kataras/iris/blob/master/iris.go#L555

**Comment by kataras** [comment]
Yes, the link is https://github.com/iris-contrib/examples/blob/master/letsencrypt/main.go it's not a big deal you can easy understand what example to look, but I'll fix it on the next revision, thank you very much!
