### ISSUE TITLE
How to send a broadcast to all clients using websocket

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#533]
- Version : **5.0.1**

``` Go
package main

import (
	"github.com/kataras/iris"
	"strconv"
	"time"
)

func main() {
	iris.Static("/js", "./static/js", 1)
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("client.html", map[string]interface{}{"Host": ctx.HostString()})
	})

	iris.Config.Websocket.Endpoint = "/ws"

	var channel = "room1"

	iris.Websocket.OnConnection(func(c iris.WebsocketConnection) {
		c.Join(channel)

		c.On("chat", func(msg string) {
			c.To(channel).Emit("chat", "["+strconv.FormatInt(time.Now().Unix(), 10)+"] ID: "+c.ID()+":"+ msg)
		})

	})

	iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
@dxvgef This is not so hard to think of...

- Just collect all clients into a slice of `iris.WebsocketConnection` 
- make sure you collect them using channels or mutex, for safety
- make a function which will iterate to all of these websocket connections and call the
`client.To(iris.Broadcast).Emit("chat", "my message")`

**Comment by kataras** [comment]
@dxvgef This is not so hard to think of...

 **`OnConnection` gives you the client connected**, so: 
- Just collect all clients into a slice of `iris.WebsocketConnection`, 
- make sure you collect them using channels or mutex, for safety
- make a function which will iterate to all of these websocket connections and call the
`client.To(iris.Broadcast).Emit("chat", "my message")`

**Comment by dxvgef** [comment]
Do I need to declare a variable (like this `var clients []websocket.Connection`), and then in `iris.Websocket.OnConnection(iris.WebsocketConnection C)` in the implementation of `append(clients, c)`?

**Comment by kataras** [comment]
Yes, this but in sync way, I recommend you to use channels for these cases, you got the point nice!

**Comment by dxvgef** [comment]
I did it, thank you!

**Comment by kataras** [comment]
Nice! iris websockets has `OnDisconnect` also, use that to **remove** a websocket connection from the connections slice too
