### ISSUE TITLE
done

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#534]
Have done

**Comment by kataras** [comment]
What have done, could you please explain us what was the issue and how you solve it? New users in the future may have the same issue like you, thanks!!

**Comment by dxvgef** [comment]
This is a very funny issue, no one is as stupid as me, please delete it 😅

**Comment by kataras** [comment]
ahah Ok then, you're not stupid, you just posting issues without investigate them first but that's ok, I'll be always here for all of you,  github doesn't allows delete action for issues, so this issue will stay here...
