### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by araneta** [kataras/iris#537]
- Version : **4**

- Operating System: linux mint
i got this error when accessing rest url
XMLHttpRequest cannot load http://localhost:8080/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 
here is my code
`import (
	"gopkg.in/kataras/iris.v4"
	"gopkg.in/iris-contrib/middleware.v4/cors"
	
	"github.com/heroku/go-getting-started/routes"
)

func main(){
	iris.Use(cors.Default()) 
	

    iris.Get("/home", func(c *iris.Context) {
        c.Write("Hello from /home")
    })
	iris.Get("/", func(c *iris.Context){
		c.HTML(iris.StatusOK, "<h1> Hello World! </h1>")
	})
	
	iris.Get("/install", routes.Install)
    iris.Post("/login", routes.Login)
    
`

**Comment by jiangyoucai** [comment]
i get the same error
[https://github.com/kataras/iris/issues/538](https://github.com/kataras/iris/issues/538)
it looks like the get method in route

**Comment by kataras** [comment]
Dublicate & Invalid repository,

- https://github.com/iris-contrib/middleware/issues/18
