### ISSUE TITLE
about graceful

### ISSUE THREAD

**Issue by chengshihard** [kataras/iris#539]
- Version : **5.0.1**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I used the documentation example to run graceful,but not achieved
can you explain it , thank you

**Comment by kataras** [comment]
Sorry, you are in the wrong repository, I can't answer you for one small midleware, here at the iris' core issues. Go and ask this [there](https://github.com/iris-contrib/middleware) better, you may get an answer who helps you.
