### ISSUE TITLE
40MB of github.com/aws/aws-sdk-go

### ISSUE THREAD

**Issue by roytan883** [kataras/iris#540]
Can you remove the asw dependence ? It's about 40MB. 
Downloading is slow, also I don't need it. 
Is there anyway not install it when "go get" ?

**Comment by roytan883** [comment]
sorry, seems gopm has bug , download all will get aws, but get only will work.

**Comment by kataras** [comment]
We don't have github.com/aws/aws-sdk-go dependency either our imports has this as dependency (as far as I know), I think you have to change your vendor mechanism and just use the Go's standard...

**Comment by kataras** [comment]
We don't have github.com/aws/aws-sdk-go dependency either our imports have this as dependency, as you correctly noted, I think you have to change your vendor mechanism and just use the Go's standard...
