### ISSUE TITLE
tx.requestctx

### ISSUE THREAD

**Issue by prajnak** [kataras/iris#542]
- Version : **5.0.1**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

**Comment by kataras** [comment]
Dear Prajna

Do not post empty issues please, if you have any questions do not hesitate to ask on the [chat](https://kataras.rocket.chat/channel/iris) and if you have prepared a bug report open a new issue with full title.


Thanks,
kataras
