### ISSUE TITLE
Please remove vulcan from the front page

### ISSUE THREAD

**Issue by iamthemuffinman** [kataras/iris#546]
On the site for [iris](http://iris-go.com/) and in the benchmarks section here on Github, vulcan is listed there as part of the comparison. As far as I know, there is no web framework named vulcan so I must assume you're comparing it to [vulcand](https://github.com/vulcand/vulcand) which is a load balancer backed by etcd and doesn't make any sense to compare it with a bunch of web frameworks. If I'm wrong and there is a web framework called vulcan, feel free to close this issue. If not, please remove it from the graphic.

**Comment by kataras** [comment]
I didn't made them, in the iris and the README there are two benchmarks made by third-party persons please do not speak me about them I didn't touch them and I will not.

**Comment by kataras** [comment]
Hi,

I didn't made them, in the iris and the README there are two benchmarks made by third-party persons please do not speak me about them I didn't touch them and I will not.


Github issues is for bug reports and feature requests, please, respect that do not make your own things here... respect the others.

Thanks,
kataras
