### ISSUE TITLE
a flexible exceptions handling expected

### ISSUE THREAD

**Issue by minhlucvan** [kataras/iris#549]
- Version : **5.0.1**

- Operating System: ubuntu 16.04

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Hello, 
First of all I want to thank you for creating an amazing Iris +1.

I'm building my first application with Iris, you can see my source code [here](https://github.com/minhlucvan/gotodo). Some frameworks I used before like Laravel or Play have really good exception handling mechanisms, I read the iris the custom HTTP errors  the ``OnError`` and `` ctx.EmitError`` seem useless in my case. 

- How do I implement custom error handling method for all http error codes?
- How do i emit error along with some data such as error message?
- How do i implement two error types, one for JSON api amd the other for HTML api?

I'm pretty new at Go and Iris as well, so Can anyone show me how do I get my functions work well and easy to maintain and extend in future? 
Thank you in advance.

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**, #### so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 to catch ALL errors.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have thee options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too) 

3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so if you make something like this: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR
htmlAPI := iris.Party("html.")
htmlAPI.OnError(500, func(ctx *iris.Context){ /* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR
jsonAPI := iris.Party("html.")
jsonAPI .OnError(500, func(ctx *iris.Context){ /* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Post here if you have any further questions about this, my english are not the easier to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have thee options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too) 

3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so if you make something like this: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR
htmlAPI := iris.Party("html.")
htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR
jsonAPI := iris.Party("html.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Post here if you have any further questions about this, my english are not the easier to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have thee options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too) 

3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so if you make something like this: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for html.mydomain.com ( mydomain.com comes from iris.Listen)
htmlAPI := iris.Party("html.") 

htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for json.mydomain.com ( mydomain.com comes from iris.Listen)
jsonAPI := iris.Party("json.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Post here if you have any further questions about this, my english are not the easier to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have three options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too). You can do that:

```go
myHTMLAPI := iris.Party("/api/html")
myHTMLAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myHTMLAPI*/ }) 

myJSONAPI:= iris.Party("/api/json")
myJSONAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myJSONAPI*/ }) 
```
3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so if you make something like this: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for html.mydomain.com ( mydomain.com comes from iris.Listen)
htmlAPI := iris.Party("html.") 

htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for json.mydomain.com ( mydomain.com comes from iris.Listen)
jsonAPI := iris.Party("json.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Let me know if you have any further questions about this, my english are not the easier to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have three options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too). You can do that:

```go
myHTMLAPI := iris.Party("/api/html")
myHTMLAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myHTMLAPI*/ }) 

myJSONAPI:= iris.Party("/api/json")
myJSONAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myJSONAPI*/ }) 
```
3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for html.mydomain.com ( mydomain.com comes from iris.Listen)
htmlAPI := iris.Party("html.") 

htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for json.mydomain.com ( mydomain.com comes from iris.Listen)
jsonAPI := iris.Party("json.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Let me know if you have any further questions about this, my english are not the easier to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have three options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too). You can do that:

```go
myHTMLAPI := iris.Party("/api/html")
myHTMLAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myHTMLAPI*/ }) 

myJSONAPI:= iris.Party("/api/json")
myJSONAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myJSONAPI*/ }) 
```
3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for html.mydomain.com ( mydomain.com comes from iris.Listen)
htmlAPI := iris.Party("html.") 

htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR

//stands for json.mydomain.com ( mydomain.com comes from iris.Listen)
jsonAPI := iris.Party("json.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are easy, just put a subdomain for your REST APIs it will make your life easier, trust me, and it will be easier to horizontally scale it when you will need to make a decision like that.

Let me know if you have any further questions about this, my english are not the easiest to read but I think you will got the point!!

**Comment by kataras** [comment]
Hello @minhlucvan ,

First of all thanks for trying out Iris and I'm welcome you to the Go community!

Let's deep, the first two questions are easy to answer with a general thinking,

- The HTTP subprotocol has http status codes which you can send to the client, if you read the HTTP specification you will see what are the error status codes and what are not, but, it's easier to just read from wikipedia [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), if you scroll a little down you will see this: **4xx Client Error** and **5xx Server Error**,  _so you can make a for loop, starting from 400 and end with 499 to handle the CLIENT errors, from 500 to 599 to handle SERVER errors, or loop between 400 and 599 and put an `iris.OnError(i, myErrorHandler)` to catch ALL errors_.

- The iris' custom **errors are just handlers**, the `iris.OnError`  takes an integer (the http status code) and a handler, look [here](https://github.com/kataras/iris/blob/master/iris.go#L2145). So you have access to the **iris.Context** like a normal handler, you can send any data(template, json, html, text or whatever) you want like you do with your route handlers. On the Example [here](https://github.com/iris-contrib/examples/blob/master/httperrors/main.go#L9) we are just sending raw text.

- At your last question , you have three options: 
1. Define one error handler with `iris.OnError` and inside it open an if branch and check for the route's handler's try to send a ContentType with `string(context.Response.ContentType())` if it's application/json do that else do something else

2. After v4, iris supports `Party(group of routes) error handling`  for example if you have all your JSON Rest API on the `/api/json/$PATH_API` and a second HTML Rest API on `/ api/html/$PATH_API` ( I don't know why you want an html rest api and why you compare it with json but that's your decision, Note: if you meant about rendering pages just comment to answer to that too). You can do that:

```go
myHTMLAPI := iris.Party("/api/html")
myHTMLAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myHTMLAPI*/ }) 

myJSONAPI:= iris.Party("/api/json")
myJSONAPI.OnError(404, func(ctx *iris.Context){ /* error handler for myJSONAPI*/ }) 
```
3. The third solution is similar to the second, I made iris to handle subdomains very simple like parties, so: 

```go
// HTML API ON SUBDOMAIN WITH CUSTOM ERROR

// stands for html.mydomain.com ( mydomain.com comes from iris.Listen)
htmlAPI := iris.Party("html.") 

htmlAPI.OnError(500, func(ctx *iris.Context){ 
/* do the html.mydomain.com error handling here */ })
htmlAPI.Get("/api/users", getAllUsers)

// JSON API ON SUBDOMAIN WITH CUSTOM ERROR

// stands for json.mydomain.com ( mydomain.com comes from iris.Listen)
jsonAPI := iris.Party("json.")
jsonAPI .OnError(500, func(ctx *iris.Context){ 
/* do the json.mydomain.com error handling here */ })
jsonAPI .Get("/api/users", getAllUsers)

iris.OnError(500, func(ctx *iris.Context){
   ctx.HTML("<h1> This is a general Server error by mydomain.com, NOT shown on html.mydomain.com/**/* or json.mydomain.com/**/* </h1>")
})
iris.Listen("mydomain.com")
```` 

I prefer the third way, subdomains with iris are really easy, just make use of subdomains(anyname and dot. or *. for wildcard subdomain) for your REST APIs, it will make your life easier, trust me,  it will be easier to scale your web app horizontally later on.

Let me know if you have any further questions about this, my english are not the easiest to read but I think you got the point!!

**Comment by minhlucvan** [comment]
thank you @kataras ,

I'm really appreciate your help, It's was save my days, I'll try the third way.

There is no doubt that Iris is the best frame work for Go for now.

Minh.
