### ISSUE TITLE
throughputs is very low if business logics take a little time

### ISSUE THREAD

**Issue by smallnest** [kataras/iris#55]
I create a application to mock the real product and handlers takes some time to process business logics such as accessing databases and invoke other services:
``` go
package main

import (
	"os"
	"strconv"
	"time"

	"github.com/kataras/iris"
)

func main() {
	api := iris.New()
	api.Get("/rest/hello", func(c *iris.Context) {
		sleepTime, _ := strconv.Atoi(os.Args[1])
		if sleepTime > 0 {
			time.Sleep(time.Duration(sleepTime) * time.Millisecond)
		}

		c.Text("Hello world")
	})
	api.Listen(":8080")
}
```

compile it as "iris" and run "iris 10".  I mock 10 ms processing time.
The throughput only reach 97 requests/second, Instead, go default mux can reach "9294 requests/second"

If i run "iris 1000",  The throughput only reach 1 requests/second, Instead, go default mux can reach "95 requests/second" .

You can reproduce it easily in multiple cores environment by "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello".

Inestigate it in depth I found the below method maybe cause low performance:
```go
func (r *MemoryRouterDomain) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	method := req.Method
	path := req.URL.Path + req.Host
	if ctx := r.cache.GetItem(method, path); ctx != nil {
		ctx.Redo(res, req)
		return
	}

	ctx := r.getStation().pool.Get().(*Context)
	ctx.Reset(res, req)

	if r.processRequest(ctx) {
		//if something found and served then add it's context's clone to the cache
		r.cache.AddItem(method, path, ctx.Clone())
	}

	r.getStation().pool.Put(ctx)
}
```

for example, maybe requests of visited the same uri from  a lot of clients enter this method, then the below will be run in loops until one request has been handled.
```go
	if ctx := r.cache.GetItem(method, path); ctx != nil {
		ctx.Redo(res, req)
		return
	}
```

**Comment by kataras** [comment]
@smallnest  Hmmm I already do these kind of tests with ab -c 10000 -n 500000 http://localhost:8080/hello/makis for example, is it differenet from the 'wrk' ? ( I'm working on Windows atm). Can you share your code which you do these tests ? thanks!!

**Comment by smallnest** [comment]
because of holidays I can't do this test without cache until three days later. but I believe you are right and hope you find a solution with cache, for example, clone temp contexts in case of high press

**Comment by smallnest** [comment]
because of holidays I can't do this test without cache until three days later. but I believe you are right and hope you find a solution with cache, for example, clone temp contexts in case of high press

**Comment by kataras** [comment]
@smallnest  Yes, the Context is already cloned before passed to the Context, the problem are the locks on multiple workers, I have to convert all the cache to work with channels/pipes and use pool-workers design pattern, I will do it and finally if the performance is better  good, otherwise the cache will be disabled when multiple workers and cores are used...one way or another iris is faster than other frameworks either without cache at all, thanks you for your feedback and happy holidays!!

**Comment by thesyncim** [comment]
maybe use a [shard hash table](http://openmymind.net/Shard-Your-Hash-table-to-reduce-write-locks/) will improve the contention

**Comment by kataras** [comment]
@thesyncim  I already seen this and tried before, is slower than it's now , maps with small keys(get,post,delete... http methods) are faster than this in this post, I must do what i say before it will take a long to do and I am not sure if the performance will be faster than just simple no use cache at all (at many workers with many cpu cores)

**Comment by smallnest** [comment]
Thanks for the fix. Test result for 10ms processing time and 1s processing time :

1. without cache
```
	api := iris.New()
	api = iris.Custom(iris.StationOptions{Cache: false, PathCorrection: true})
```

`iris 10` can reach 9281 request/s
`iris 1000` can reach 95 request/s

2. GOMAXPROCS = 1
```
	runtime.GOMAXPROCS(1)
	api := iris.New()
```
`iris 10` can reach 8098 request/s
`iris 1000` can reach 95 request/s

**Comment by kataras** [comment]
Yes this happens to other routers too, I'm designing a new server from start which will work out of the box with concurrency and more parallel, hopefuly I will finish it in time, thanks for your help man I really appriciate

**Comment by kataras** [comment]
@smallnest I did it finally, if you want to test it go [here](https://github.com/kataras/golang_iris_experiments/tree/master/channels4) I tried with channels, I tried a lot but I changed this small router to use the fasthttp and works really fast. I assume that I have to convert the whole iris project to use the fasthttp and a channel-cached version of a mux/router, the only bad is that fasthttp doesn't provide http2 support yet, but browsers can downgrade to http/1.1 if server doesn't support http2 as I remember

**Comment by xpbliss** [comment]
Good!

**Comment by smallnest** [comment]
Great, @kataras!

**Comment by kataras** [comment]
@xpbliss  @smallnest  Thanks you, take a look with cached version ( local project )
httprouter-benchmarks 

  200000	      6830 ns/op	       0 B/op	       0 allocs/op 

and ab: ab -c 100 -k -t 30 http://127.0.0.1:8080/rest/hello 
135861.81 Requests per second

and the net/http: 94334.28 Requests per second

I'm so happy!!!

**Comment by xpbliss** [comment]
using the fasthttp instead of the old ?

**Comment by kataras** [comment]
With fasthttp and new way of handling the Context, you will see the code here soon !!

**Comment by kataras** [comment]
@smallnest  @xpbliss  Fixed with https://github.com/kataras/iris/commit/9ad833c32962f251404d78331e2bd3544020ebfb

**Comment by smallnest** [comment]
@kataras cool.
I updated my https://github.com/smallnest/go-web-framework-benchmark

**Comment by kataras** [comment]
@smallnest  Nice, I see in the graph that echo2is faster, but I already tested echo2 with it's fasthttp server and it was much slower.. but ok it's your repo thanks for adding Iris to this!! I really appriciate it!

**Comment by kataras** [comment]
@smallnest  Notify me when you run the tests again in order to replace readme benchmarks with yours repo link!

**Comment by smallnest** [comment]
@kataras  Run Round 2 test and updated test result

**Comment by kataras** [comment]
Ok, do I see well, Iris is the fastest framework (after fasthttp-raw which it isnt' a framework )  on 'real' benchmarks? Very nice my friend, it's time for an article too aahah I'm too happy that you helped me to figure what was wrong on previous version

**Comment by kataras** [comment]
Ok I can't hold myself I pull the new benchmarks, [here](https://github.com/kataras/iris/#benchmarks) I give your link twice and your name in the benchmark section if it's ok, if you don't for any reason want tell me to remove it

**Comment by smallnest** [comment]
It is great. Thank you for developing such a high performance web framework, Iris.

**Comment by kataras** [comment]
@smallnest My pleasure I need this framework too :) Because I really appriciate your interest and your work I mention [your](https://twitter.com/MakisMaropoulos/status/716961765087641600) [articles](https://twitter.com/MakisMaropoulos/status/720153709657919488) [here](https://twitter.com/MakisMaropoulos/status/720154119009345536) , hope that you continue this :rose:
