### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by araneta** [kataras/iris#551]
- Version : **5.0.1**

- Operating System: Linux Mint 14

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
Please give me example how to handle file upload from REST. I can't find it anywhere. Thanks

**Comment by xpbliss** [comment]
https://github.com/iris-contrib/examples/tree/master/file_upload_simple
