### ISSUE TITLE
Party example in the git book is missing ctx.Next()

### ISSUE THREAD

**Issue by claudehohl** [kataras/iris#552]
- Version : **5.0.1**

- Operating System: Debian 8.6

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

In this example: https://docs.iris-go.com/party.html

The middleware is stuck, because the ctx.Next() is missing in the example. After adding it, everything works as expected.

Tried to make a PR, but it seems the GitBook is not like GitHub, no repo. So here is the diff:

```diff
@@ -3,7 +3,7 @@ package main
 import "github.com/kataras/iris"
 
 func main() {
-       admin := iris.Party("/admin", func(ctx *iris.Context) { ctx.Write("Middleware for all party's routes!") })
+       admin := iris.Party("/admin", func(ctx *iris.Context) { ctx.Write("Middleware for all party's routes!"); ctx.Next() })
        {
                // add a silly middleware
                admin.UseFunc(func(c *iris.Context) {
```

--------------

**Comment by kataras** [comment]
@claudehohl Thanks but it's not needed to create an issue for the examples or the book, you can just fix it via PR, for the gitbook go here: github.com/iris-contrib/gitbook/pulls. If you need any help on how to create pull a commit write down in order to navigate you!

**Comment by kataras** [comment]
@claudehohl Thanks but it's not needed to create an issue for the examples or the book, you can just fix it via PR, for the gitbook go here: https://github.com/iris-contrib/gitbook/pulls. If you need any help on how to create pull a commit write down in order to navigate you!

**Comment by kataras** [comment]
@claudehohl Thanks but it's not needed to create an issue for the examples or the book, you can just fix it via PR, for the gitbook go here: https://github.com/iris-contrib/gitbook/pulls. If you need any help on how to pull a commit write down in order to navigate you!

**Comment by claudehohl** [comment]
iris-contrib/gitbook - ah, I didn't know about that! Thanks for clearing up & for the fix.

**Comment by kataras** [comment]
Yeah I'm writing that on the contribution file but that's ok most of the users never notice these github files :)

I thanks you for your contribution, you can make any PR to the gitbook or examples, I'll approve them. I'm not a native english speaker so any help is welcomed there!!

**Comment by claudehohl** [comment]
My apologies. I have read the book, the examples - but not the contributing file, which points to the book-repo.

Neither am I a native english speaker (I'm swiss, grüezi :) ), but yea, I'll make PRs if I discover more things to improve.

Last but not least: Thank you for inventing Iris. I'm coming from a webdev-background (node/express.js, CodeIgniter, ...) and I discovered the Go wonderland earlier this year. I'm so glad that there exists a framework that actually *works*, feels natural to me with all batteries included and still outperforms all others.

So - thank you, and keep up the good work! :+1:

**Comment by kataras** [comment]
Thank you very much!! Words like these makes me to continue contribute to the Go community and Iris, even if that comes with big personal lifestyle cost.

If you find any bugs or you have any framework-relative suggestion just post an issue, most of the times you will get an answer or/and fix at the same day!
