### ISSUE TITLE
How to set and get from the header?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#554]
- Version : **5.0.4**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I can't get the authorization string, how to get it ?   why?  what's wrong with the following?

```
iris.Get("/setAuth", func(ctx *iris.Context) {
    ctx.Response.Header.Set("Authorization", "my authorization string")
    ctx.Render("set.html", nil)
})

//set.html
<form action="getAuth" method="post">
 <input type="submit" value="submit">
</form>

iris.Post("/getAuth", func(ctx *iris.Context) {
    str:= ctx.RequestHeader("Authorization")   
    fmt.Println(str)                                          //Why not the str get nothing?
    ctx.Text(200, str)
})

```

**Comment by kataras** [comment]
Hello, the `RequestHeader` and `Response.Header.Set` works just fine, I think you do something else which isn't clear in the code snippet you saw us. Look the [basicauth iris middleware](https://github.com/iris-contrib/middleware/blob/master/basicauth/basicauth.go#L97) on how to make your own authentication, if you wanna so.

**Comment by kataras** [comment]
Hello, the `RequestHeader` and `Response.Header.Set` works just fine, I think you do something else which isn't clear in the code snippet you show us. Look the [basicauth iris middleware](https://github.com/iris-contrib/middleware/blob/master/basicauth/basicauth.go#L97) on how to make your own authentication, if you wanna so.

**Comment by xpbliss** [comment]
```
package main

import (
	"fmt"
	"github.com/kataras/iris"
)

func main() {
	iris.Get("/setString", func(ctx *iris.Context) {
		tokens := "This is a test for header!"
		ctx.SetHeader("Authorization", string(tokens))
		ctx.Response.Header.Add("Server", "myserver")
		fmt.Println("This is the tokens111:", string(tokens))
		ctx.Render("set.html", nil)

	})

	iris.Post("/getString", func(ctx *iris.Context) {
		accessToken := ctx.RequestHeader("Authorization") + ctx.RequestHeader("Server") + ctx.RequestHeader("Host")
		fmt.Println("This is the tokens:", accessToken)
		ctx.Text(200, string(accessToken))
	})
	
	iris.Listen(":80")
}
```
```
//set.html
<form action="getAuth" method="post">
 <input type="submit" value="submit">
</form>
```

always can't get the string ```tokens := "This is a test for header!"```  from the post  action ```getString```, why?
what's wrong with it?

**Comment by kataras** [comment]
@xpbliss Really I don't know your flow, on my code is working as it worked before, nothing changed for headers the last 5 months! **If you want to set custom headers try to put an X- before the name/key** , for example: `X-Authorization` and try again, tell me the results here

**Comment by kataras** [comment]
@xpbliss Really I don't know your flow, on my code is working as it worked before, nothing changed for headers the last 5 months! **If you want to set custom headers try to put an X- before the name/key** , for example: `X-Authorization` and try again, tell me the results here.

Also you asked the same thing on `3 Oct` here: https://github.com/kataras/iris/issues/457 Please do NOT duplicate yourself this is not a chat room...

**Comment by yeweishuai** [comment]
try:

`ctx.Header("Authorization", tokens)`
