### ISSUE TITLE
Allow RFC-3339 times in context.ReadForm

### ISSUE THREAD

**Issue by dan-0** [kataras/iris#556]
- Version : **5.0.4**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Can formBinder be modified to accommodate RFC-3339 compliant date-time formats?

iris.Context.ReadForm parses times in the following manner:

`t, err := time.Parse("2006-01-02", dec.values[0])`
`if err != nil {`
        `return newError(fmt.Errorf("the value of field \"%v\" in path \"%v\" is not a valid datetime", dec.field, dec.path))`
`}`
`dec.curr.Set(reflect.ValueOf(t))`

This is fine parsing standard form datetime types, but date, datetime, and datetime-local are not supported across all browsers, specifically Firefox. This leads to a need for some workarounds on client side and/or server side.

I haven't been able to find a way to resolve the issue of parsing an RFC-3339 compliant date-time without modifying the data in the form body prior to invoking `ReadForm`. This works find for me, but I imagine I'm not the only one having to work around this.

Thanks for all your work, I really enjoy Iris!

**Comment by kataras** [comment]
Hello @dan-0 , thanks for your nice words I thanks you for using it.

You are able to edit the form binder (which the `ReadForm` depends), just add make your changes to this [file](https://github.com/iris-contrib/formBinder/blob/master/formBinder.go) and make a PR, I can do that too but I don't have time to test its behavior ( while keeping the old behavior with some option or whatever) .

**Comment by kataras** [comment]
Hello @dan-0 , thanks for your nice words I thanks you for using it.

You are able to edit the form binder (which the `ReadForm` depends), just make your changes to this [file](https://github.com/iris-contrib/formBinder/blob/master/formBinder.go) and make a PR, I can do that too but I don't have time to test its behavior ( while keeping the old behavior with some option or whatever) .

**Comment by kataras** [comment]
Thanks for the fix @dan-0. Relative PR: https://github.com/iris-contrib/formBinder/pull/2
