### ISSUE TITLE
How do i can integrate ReverseProxy with Iris

### ISSUE THREAD

**Issue by ysaakpr** [kataras/iris#557]
- Version : **5.0.4**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
How do i wire golang ReverseProxy with Iris.

**Comment by kataras** [comment]
Iris is the low-level access framework which means that you can do everything, if you know how to do it. The issue lists are not a tutorial for general web development or programming courses, this is not a forum, a website which can help you is the [stackoverflow](http://stackoverflow.com/) like the README says... anyway  if you search [here](https://github.com/valyala/fasthttp/issues) you will find some answers and for a very PURE example very very pure and awf look [here](https://github.com/kataras/iris/blob/master/http.go#L1412) and [here](https://github.com/kataras/iris/blob/master/http.go#L1446) , these are not reverse proxies but you can get the syntax on what methods to use.

Good luck and stay strong,  learn - learn learn never stop!
