### ISSUE TITLE
Can't get post values with javascript formdata API 

### ISSUE THREAD

**Issue by jackey** [kataras/iris#559]
- Version : **5.0.4**

- OS: Mac OS

here's javascript code
```
var data = new FormData();
data.append("comment", "test");
fetch("/api/comment", {method:"POST", body: data, headers: {"Content-Type": "application/application/x-www-form-urlencoded"}});
```

the request payload is

```
------WebKitFormBoundaryZAUExpMo0olgBBRA
Content-Disposition: form-data; name="comment"

test
------WebKitFormBoundaryZAUExpMo0olgBBRA--
```

golang & iris

```
func handler(ctx *iris.Context) {
  args := ctx.PostArgs()
  fmt.Println(args) // empty 
}
iris.Post("/api/comment", handler)
```

I followed the REAMD tutorial , probably missed important step.

**Comment by kataras** [comment]
Try these: 
- `ctx.PostValuesAll() map[string][]string` which is the *Iris function** which may do the job for you, https://github.com/kataras/iris/blob/master/context.go#L281 
- `ctx.FormValues(name string) []string` https://github.com/kataras/iris/blob/master/context.go#L268 

Iris has several functions to get post parameters and form data, look the links I sent you and generally look the context.go file you will find many methods.

The `ctx.PostArgs` is a fasthttp function, if you have any issue with that you should post to [this](https://github.com/valyala/fasthttp) repo.
