### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by araneta** [kataras/iris#562]
- Version : **5.0.4**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I got this error: XMLHttpRequest cannot load http://localhost:8080/employee-educations/?token=eyJhbGciOiJIUzI1NiIsInR5cC…bGRvYXBwLmNvbSJ9.G-gZxD2HgVubGAprl_CqY7u99wWFcjmZIDHNfxFR5C8&employeeId=31. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
Here is the main function: 
//CORS	
	crs := cors.New(cors.Options{
		AllowedOrigins:[]string{"*"},
		AllowedMethods:[]string{"HEAD","GET","POST","PUT","DELETE","OPTIONS"},
		
	})
	iris.Use(crs) // crs
//employee education
	iris.Get("/employee-educations", myJwtMiddleware.Serve, routes.GetAllEmployeeEducations)
	iris.Post("/employee-educations", myJwtMiddleware.Serve, routes.AddEmployeeEducation)
	iris.Get("/employee-educations/:id", myJwtMiddleware.Serve, routes.GetEmployeeEducation)
	iris.Put("/employee-educations/:id", myJwtMiddleware.Serve, routes.UpdateEmployeeEducation)
	iris.Delete("/employee-educations/:id", myJwtMiddleware.Serve, routes.DeleteEmployeeEducation)
I dont know why it throws an error if i add employeeId=31 on this url http://localhost:8080/employee-educations like in the example

**Comment by kataras** [comment]
@araneta This is dublicated, you can find a solution to its repository's issue list, it is no need to post everything about web development in the iris' issues list... [this is the correct repository](https://github.com/iris-contrib/middleware). Please read the [contribution file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) before posting a new issue. Thanks!!
