### ISSUE TITLE
http2 support?

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#563]
- Version : **5.1.3**

- Operating System: Ubunutu 16.04

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Hello is there any plan to support http2? Or is it already supported and only not documented?

**Comment by kataras** [comment]
Hello Dexus, this is a question many people asked before too, if you searched older issues (as your comment says) you could see a more complete answer, http/2 is not implemented by all clients, yet. Short answer: http/2 is a TODO, read more [here](https://github.com/valyala/fasthttp/issues/144).

**Comment by Dexus** [comment]
@kataras sorry did not search for `http/2`

**Comment by kataras** [comment]
@Dexus Iris supports http/2 now :) Take a look here: https://github.com/kataras/iris/issues/565
