### ISSUE TITLE
DefaultServerName no more supported?

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#564]
- Version : **5.1.3**

Why i can't change the ServerName? This feature looks removed...

For some reasons, I think it should be possible to change...

**Comment by kataras** [comment]
Dear Dexus, you didn't read previous posts, again, no problem I have patience to explain the same thing 40 times more :P

Server name is just a simply HTTP header, nothing special to do to set it... 

Make a middleware and pass it to `iris.Use(ServerHeaderMiddleware)` , middleware code: 
```go
func ServerHeaderMiddleware(ctx *iris.Context) {
    ctx.Response.Header.Set("Server", "My Server Name")
    ctx.Next()
}

```

Hope that helped you!

**Comment by kataras** [comment]
Dear Dexus, you didn't read previous posts, again, no problem I have patience to explain the same thing 40 times more :P

Server name is just a simply HTTP header, nothing special to do to set it... 

Make a middleware and pass it to `iris.UseFunc(ServerHeaderMiddleware)` before all other route registration , middleware code: 
```go
func ServerHeaderMiddleware(ctx *iris.Context) {
    ctx.Response.Header.Set("Server", "My Server Name")
    ctx.Next()
}

```

Hope that helped you!

**Comment by kataras** [comment]
Dear Dexus, you didn't read previous posts, again, no problem I have patience to explain the same thing 42 times more :P

Server name is just a simply HTTP header, nothing special to do to set it... 

Make a middleware and pass it to `iris.UseFunc(ServerHeaderMiddleware)` before all other route registration , middleware code: 
```go
func ServerHeaderMiddleware(ctx *iris.Context) {
    ctx.Response.Header.Set("Server", "My Server Name")
    ctx.Next()
}

```

Hope that helped you!

**Comment by Dexus** [comment]
Shame on my head.
