### ISSUE TITLE
Debate: HTTP/2 Support

### ISSUE THREAD

**Issue by ghost** [kataras/iris#565]
I'm always open for discussion and community knows that, nowadays many people take leverage of my opinion-sharing and experience. They find me and asking me different things, some of them are Iris-relative. 

Don't misunderstood me, but I don't want to post private conversations without the agreement of the person, in the other hand I am willing to share some of the public comments about Iris and I will try to combine them(private+public) into one in the next paragraph

![](https://docs.iris-go.com/comment36.png)

![](https://docs.iris-go.com/comment35.png)

![](https://docs.iris-go.com/comment34.png)

![](https://docs.iris-go.com/comment2.png)

![](https://docs.iris-go.com/comment30.png)

![](https://docs.iris-go.com/comment31.png)

![](https://docs.iris-go.com/comment32.png)

![](https://docs.iris-go.com/comment33.png)

![](https://docs.iris-go.com/comment26.png)

![](https://docs.iris-go.com/comment1.png)

![](https://docs.iris-go.com/comment3.png)

![](https://docs.iris-go.com/comment8.png)

![](https://docs.iris-go.com/comment12.png)

![](https://docs.iris-go.com/comment13.png)

![](https://docs.iris-go.com/comment14.png)

![](https://docs.iris-go.com/comment17.png)

![](https://docs.iris-go.com/comment21.png)

![](https://docs.iris-go.com/comment22.png)

![](https://docs.iris-go.com/comment24.png)

![](https://docs.iris-go.com/comment27.png)

I will try to combine into one:

> Iris is the best framework I have ever worked in my whole career (not only golang), it makes my life so easy, feels like I coded with Iris before, it has an easy API and I can understand what a function does without navigating to the source code, it supports different template engines out-of-the-box, has fast session support and websocket support with extremely easy API as well, it can combine my files to one binary and serve them very fast, I can now public my app without nginx. Ideally If you compare with its (golang) alternatives it's a Goddess  **BUT** why no http/2 support as well? 

At first I thanks them/you for the nice words about Iris but also I try to answer with my own way (and my bad english) to their 'Why' (it is a complaint): http/2 is not fully established in the real-world scenarios. **Τhe majority** of the http clients are not fully upgraded to http/2, yet (I am NOT talking about web browsers only, in the real industry and most business apps you will need a custom http client), so if you have a http/2 server it will act like http/1 for those clients. 

In most cases I did continue with an explanation of what is http/2 and how differs from http/1 versions. You should really read [here](https://http2.github.io/faq/), if you didn't so far.

I am in the industry for a decade++, I believe that, I know when is the best season to really change something  in order to make it better.

**I am guessing that things will change and the majority of clients will be ready for http/2 in the mid of 2017**, so my answer to you will change. 

I want to be prepared and start  coding the changes as soon as possible. **2017 is near so I am asking you ( the community) about your opinion of Iris to be aligned with the net/http/ go's standard subprotocol library** which supports both http/1 versions and http/2. Go v1.8 introduces the `Server Push` support, this is fantastic and can help you make your apps even faster. **Iris is well-designed so don't worry about big API changes**.

- **Vote up** if you're waiting for this and you're willing to make some internal changes to your apps.
- **Vote down** if you do not approve the http/2 support announcement and want things to stay as they are.
- or comment below your opinion

> The future commits for http/2 support will target this thread, I'll try to complete this until the end of this year, no Christmas for me this year :)

**Comment by egiathamaershada** [comment]
so iris is using net/http instead of valyala/fasthttp now? is net/http getting better than fasthttp or there is something have to do with net/http? i'm not following go packages and still getting myself in go.

**Comment by kataras** [comment]
report so far:

Most of the core plus plus upgrade has been finished. 
I lost the holidays but I hope to win the community!

All features are in on the new version too!! Some cool things were implemented too :) 

- [Book/readme](https://docs.iris-go.com) **is not updated yet**. 
- [Examples](https://github.com/iris-contrib/examples) , updated & refactored with small but many changes (mostly ctx.Write to ctx.Writef) [master branch], 'old' [v5 branch](https://github.com/iris-contrib/examples/tree/5.0.0).
- [Middleware](https://github.com/iris-contrib/examples)(you can use any third-party middleware you want now), updated & refactored with small changes [master branch], 'old' [v5 branch](https://github.com/iris-contrib/middleware/tree/5.0.0).
- [Plugins](https://github.com/iris-contrib/plugin) , updated & refactored with small changes [master branch], 'old' [v5 branch](https://github.com/iris-contrib/plugin/tree/5.0.0).

All other iris-relative packages (20+)  didn't need refactoring at all.

`5.0.0` branch is still there for those who want to use them with [iris v5 (no http/2 support)](https://github.com/kataras/iris/tree/5.0.0).

**Comment by kataras** [comment]
report so far:

Most of the v6-http/2 support code has been finished. 
I lost the holidays but I hope to win the community!

All features are in on the new version too!! Some cool things were implemented too :) 

- [Book/readme](https://docs.iris-go.com) **is not updated yet** but don't expect for huge changes to the public API, keep the things you knew, nothing crazy changed(except the HTTP/2 support :) )

- [Examples](https://github.com/iris-contrib/examples) , updated & refactored with small but many changes (mostly ctx.Write to ctx.Writef) [master branch], 'old' [v5 branch](https://github.com/iris-contrib/examples/tree/5.0.0).
- [Middleware](https://github.com/iris-contrib/examples)(you can use any third-party middleware you want now), updated & refactored with small changes [master branch], 'old' [v5 branch](https://github.com/iris-contrib/middleware/tree/5.0.0).
- [Plugins](https://github.com/iris-contrib/plugin) , updated & refactored with small changes [master branch], 'old' [v5 branch](https://github.com/iris-contrib/plugin/tree/5.0.0).

All other iris-relative packages (20+)  didn't need refactoring at all.

`5.0.0` branch is still there for those who want to use them with [iris v5 (no http/2 support)](https://github.com/kataras/iris/tree/5.0.0).

**Comment by kataras** [comment]
Iris HTTP/2 based on net/http just released.  Thanks for your 12-days pattience!
