### ISSUE TITLE
Routing: is there a way to use a route like /api/:date.json ?

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#568]
- Version : **5.0.4**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Hi, I have a need to match my old api how can I use a route like `/api/:date.json`?

Is there a way to say :date needs to be format "YYYY-MM-DD"? Or ignoring the `.json` extension?

**Comment by kataras** [comment]
Yes,

1. register your handler with a named parameter:  `/api/:date`.
2. inside the handler make use of the `regexp` go package and do your validation, **iris doesn't provides validators like these**, but this never stopped developers to make or use third-party validators.
3. If validation fails then just `context.EmitError(iris.StatusNotFound)`

You can also make middleware(or search for third-parties, many of them exists already)  for custom validations and use these whenever you need, a middleware can run inside handler with an if statement also.

**Comment by kataras** [comment]
Yes,

1. register your handler with a named parameter:  `/api/:date`.
2. inside the handler make use of the `regexp` go package and do your validation or `context.Param("date")`, **iris doesn't provides validators like these**, but this never stopped developers to make or use third-party validators.
3. If validation fails then just `context.EmitError(iris.StatusNotFound)`

You can also make middleware(or search for third-parties, many of them exists already)  for custom validations and use these whenever you need, a middleware can run inside handler with an if statement also.

**Comment by kataras** [comment]
Yes,

1. register your handler with a named parameter:  `/api/:date`.
2. inside the handler make use of the `regexp` go package and do your validation on `context.Param("date")`, **iris doesn't provides validators like these**, but this never stopped developers to make or use third-party validators.
3. If validation fails then just `context.EmitError(iris.StatusNotFound)`

You can also make middleware(or search for third-parties, many of them exists already)  for custom validations and use these whenever you need, a middleware can run inside handler with an if statement also.

**Comment by kataras** [comment]
Dear @Dexus,
Now you can add regexp to your route's path, if you enable the Gorilla Mux  iris plugin.

Check here to see how: https://github.com/kataras/iris/issues/588 

Thanks,
kataras.

**Comment by Dexus** [comment]
Thank you @kataras
