### ISSUE TITLE
How to set custom Delims?

### ISSUE THREAD

**Issue by Domoryonok** [kataras/iris#569]
Hi, I found same #71 , but, cant repeat it, because cant find `iris.TemplateDelims` func.

**Comment by kataras** [comment]
Hello, there are some examples on how to set custom configuration on each template engine, look these two links:

- https://github.com/iris-contrib/examples/blob/master/template_engines/template_html_2/main.go#L10
- https://github.com/kataras/go-template/blob/master/html/config.go#L5
