### ISSUE TITLE
replace cases for i := 0; i < xxx; i++ by for i:=range xxx

### ISSUE THREAD

**Issue by thesyncim** [kataras/iris#57]
is shorter, the new SSA compiler completely eliminate bound checks for the later

update: for i:=range xxx // doesn’t work (remove BC) for strings

**Comment by kataras** [comment]
Can you give me an example ?

**Comment by thesyncim** [comment]
you use this pattern (for i := 0; i < xxx; i++) in those files:

branch.go
	for i := 0; i < len(params); i++ {
	for i := 0; i < len(_paramsstr); i++ {
	for i := 0; i < len(path); i++ {
	for i := 0; i < len(b.tokens); i++ {
	for i := 0; i < len(b.tokens); i++ {
	for i := 0; i < len(b.tokens); i++ {
plugin.go
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
	for i := 0; i < len(p.activatedPlugins); i++ {
ticker.go
	for i := 0; i < len(c.tickHandlers); i++ {

**Comment by thesyncim** [comment]
according to [Bounds Checking Elimination](https://docs.google.com/document/d/1vdAEAjYdzjnPA9WDOQ1e4e05cYVMpqSxJYZT33Cqw2g/edit#heading=h.30zzl2nt14h ) the compiler now can completely eliminate bound checks since [25017](https://go-review.googlesource.com/#/c/20517/) for this pattern:

```go
for i:=range slice{
_=slice[i] //no bound checks
}

```

**Comment by kataras** [comment]
for i:=0;i<...i++ I though it was the faster, at all programming languages I worked the last 10 years, but as I can see they make improvements with go, this is faster than C for loop ( as I'm reading).

Thanks for the info, I will convert them if needed!!
