### ISSUE TITLE
Check iris version make a panic

### ISSUE THREAD

**Issue by monoflash** [kataras/iris#570]
- Version :
INFO: Running with the latest version(5.0.0)

- Operating System:
macOS 10.12.3 (16D17a)

Use firewall or problem with internet connection to check iris version make a panic.
This is not the correct behavior of the program. It would be correct to get an error in the log.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x441350f]

goroutine 29 [running]:
panic(0x4a2b660, 0xc4200100e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
vendor/github.com/kataras/go-fs.(*Updater).HasUpdate(0x0, 0xc420c4c500, 0x0, 0x0)
	/Users/kallisto/Projects/tubecj/tower/src/vendor/github.com/kataras/go-fs/updater.go:94 +0x3f
vendor/github.com/kataras/go-fs.(*Updater).Run(0x0, 0xc420c71e60, 0x3, 0x3, 0x0)
	/Users/kallisto/Projects/tubecj/tower/src/vendor/github.com/kataras/go-fs/updater.go:116 +0x261
vendor/github.com/kataras/iris.(*Framework).CheckForUpdates.func1()
	/Users/kallisto/Projects/tubecj/tower/src/vendor/github.com/kataras/iris/iris.go:729 +0x330
sync.(*Once).Do(0x505e290, 0xc420c71f68)
	/usr/local/go/src/sync/once.go:44 +0xdb
vendor/github.com/kataras/iris.(*Framework).CheckForUpdates(0xc420824460, 0x4b03c00)
	/Users/kallisto/Projects/tubecj/tower/src/vendor/github.com/kataras/iris/iris.go:735 +0x209
created by vendor/github.com/kataras/iris.(*Framework).Build.func1
	/Users/kallisto/Projects/tubecj/tower/src/vendor/github.com/kataras/iris/iris.go:400 +0x888
```

**Comment by kataras** [comment]
Try the `iris.Config.CheckForUpdates = false` as defaulted or make a clean install of iris (remove its dependencies too)

**Comment by monoflash** [comment]
You did not understand. Application fall should not at fault in the secondary function!
Imagine an operating system that falls, and will not boot if do not find the WiFi adapter.
You did the same thing in the iris.

The application should fall only when further work applications are not possible!
Error in CheskForUpdates is not critical, but you have made it critical. What for?

**Comment by kataras** [comment]
It shouldn't fail there, are you sure you didn't touch the source code? If not let me test and fix that too, give me your iris configuration please

**Comment by kataras** [comment]
You have right, you have no internet connection or a proxy blocked the github version access but you had `Config.CheckForUpdates = true` and it fails, this is one-line fix

Can you upgrade iris and try again?
