### ISSUE TITLE
Globally share variables

### ISSUE THREAD

**Issue by msaron** [kataras/iris#572]
- Version : **6.0.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I would like to attach a database connection to the context during startup so that it is globally available to all the handlers.  How can I do that? Thank you.

**Comment by kataras** [comment]
```go
func dbMiddleware(ctx *iris.Context){
   ctx.Set("db", myDatabase)
})

// global shared
iris.UseFunc(dbMiddleware)

// or register this per -route
iris.Get("/hi", dbMiddleware, myHiHandler)

func myHiHandler(ctx *iris.Context){
 db := ctx.Get("db").(*yourORMType)
})
```

**Comment by msaron** [comment]
Thank you. I am just starting out with Go after programming in Node. After reviewing all the frameworks out there, I selected this one as it felt the most natural.

**Comment by kataras** [comment]
Thank you for your decision, you will love Iris more and more, as you going deep you will understand its value and how much better it is from other go web frameworks. You can request for new features too! 

If you have any question please let me know!

**Comment by msaron** [comment]
I believe this framework will reach the fame of Vue.js. I have one feature request (or maybe it is already implemented). Is it possible to set the RSS size like so in hapijs? Hapijs describes it as the maximum process RSS size, in bytes, over which incoming requests are rejected with an HTTP Server Timeout (503) response? Thanks.
