### ISSUE TITLE
Could you add support for go-bootstrap?

### ISSUE THREAD

**Issue by Igorek536** [kataras/iris#573]
Can you add a native support for go-bootstrap? It's great tools for fast create a base web project. I think that support for this component will make this framework better. Sorry for my bad english.

http://go-bootstrap.io/

**Comment by kataras** [comment]
Hello @Igorek536, 

Could you, please, explain me what exactly Iris you want/imagine to do with that library?  Give me some examples, even a code snippet and I can make it happen if it's fancy :)

**Comment by msowka-ninja** [comment]
Hi I would love to see a bootstrap project for iris too.
There is of course the question what should be included.
I would see a React + Redux + Iris stack witch some aditionally candy like e.g.:
https://github.com/Sirupsen/logrus .
Expressjs has a nice generator  for the basics like selecting the template-engine etc.

**Comment by Igorek536** [comment]
How can i use bootstrap on my project with iris framework? Can someone give me example please?

**Comment by kataras** [comment]
@Igorek536 bootstrap is just a stylesheet you can serve it by `iris.StaticWeb`, example: `iris.StaticWeb("/css", "./public/css")` method.

Iris Web Framework has examples which you can see some of its features and run them with [LiteIDE](https://github.com/visualfc/liteide), click [here](https://github.com/iris-contrib/examples) to view all small and practical examples.

Some full(~big) examples: 

- Semantic UI: look [here](https://github.com/iris-contrib/examples/blob/master/AIO_examples/mongo/backend/main.go#L20) and [herehttps://github.com/iris-contrib/examples/tree/master/AIO_examples/mongo/frontend/public/css

- Bootstrap: look [here](https://github.com/iris-contrib/examples/blob/master/static_files/main.go#L18) and [here](https://github.com/iris-contrib/examples/tree/master/static_files/resources/css)

**Comment by kataras** [comment]
@Igorek536 bootstrap is just a stylesheet you can serve it by `iris.StaticWeb`, example: `iris.StaticWeb("/css", "./public/css")` method.

Iris Web Framework has examples which you can see some of its features and run them with [LiteIDE](https://github.com/visualfc/liteide), click [here](https://github.com/iris-contrib/examples) to view all small and practical examples.

Some full(~big) examples: 

- Semantic UI: look [here](https://github.com/iris-contrib/examples/blob/master/AIO_examples/mongo/backend/main.go#L20) and [here]https://github.com/iris-contrib/examples/tree/master/AIO_examples/mongo/frontend/public/css)

- Bootstrap: look [here](https://github.com/iris-contrib/examples/blob/master/static_files/main.go#L18) and [here](https://github.com/iris-contrib/examples/tree/master/static_files/resources/css)

**Comment by kataras** [comment]
@msowka-ninja Iris has the get command to download and run some examples, click [here](https://github.com/kataras/iris/tree/master/iris#get) for more. If you need something inside code please provide a code snippet how you imagine it and what exactly you want to do, I don't find any usage to bundle the bootstrap with iris but maybe I'll change my mind if I see something fancy and worth to deal with

**Comment by msowka-ninja** [comment]
@kataras This is exactly what I had in mind. I think it would make sense to describe it on http://iris-go.com/ . Maybe as an "Getting started" like meteor does in: https://www.meteor.com/tutorials/blaze/creating-an-app Or "boilerplate" as in: http://mean.io/.

**Comment by kataras** [comment]
Yes, we have many features not documented because I don't have time to do all ( iris depends on more than 20 packages that I maintain myself, with their examples, their docs...) if you're willing and have time to write a section about this to the book (just make a PR) here: https://github.com/iris-contrib/gitbook it will be nice!

**Comment by kataras** [comment]
@msowka-ninja I just finished the review of Logrus' source code and it's seems a very good project, I'm thinking of using that with log levels inside Iris (no at runtime, for performance reasons) but we can make a middleware or/and a plugin which will be optional and it will logs depending on the log level. To be absolutely honesty I didn't need a logger and I think that we should avoid them in production, BUT if that helps you and other Iris users to understand what's going on especially when debugging, it can be integrated, how is that sounds to you?

**Comment by msowka-ninja** [comment]
Actually the idea is to use logrus to send some (error) logs directly to some of the log-blackholes. I hadn't time to review it myself, I hope it sends the logs async. The approach with the middleware sounds good, this keeps the framework fast. I'll look if it's easy to integrate logrus.
I'm also checking if it's easy to integrate graphql (also as middleware).

Concerning the Documentation I'll keep it in mind if I have some spare time, should i create an issue in the gitbook repository?

**Comment by kataras** [comment]
@msowka-ninja 

Yes, we have already a middleware for logging `http requests only` (take a look [here](https://github.com/iris-contrib/middleware) ) but it makes use of the standard `log.Logger`. Take your time and think about making a [plugin](https://github.com/iris-contrib/middleware) or a [middleware](https://github.com/iris-contrib/middleware) for logrus and graphql too (graphql was a feature request but I though that users can make use of it without any middleware, so I let that as 'community job' and I think these things are not need to exists inside the iris core project) 

>  I hope it sends the logs async.

As far as I saw it uses locks for writers and it is not spawning a goroutine, but, I'm sure we can make it work as async too ( don't expect huge difference, spawning a goroutine takes some time, it's lightweight but spawning a new goroutine for each log it is not a good idea, my opinion*)

About docs, no need to create an issue first, just add or fix things( my english for example xD) and make a PR.

Waiting for your results
