### ISSUE TITLE
Subdomains do not work after update to 6.0.0

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#574]
- Version : **6.0.0**

- Operating System: ubuntu 14.04

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

**Comment by kataras** [comment]
Hello @es-lab ,
Subdomains tests are passed, so I ran some subdomain examples and all worked, nothing changed for domains and subdomains after 6.0.0 .

Could you please provide us the code snippet you're using in order to find out what is happening on you?

**Comment by kataras** [comment]
Thanks for the report, it was an easy fix and I took the opportunity to add a more realistic subdomain test then we had before  :)

**Comment by kataras** [comment]
Thanks for the report, it was an easy fix and I took the opportunity to add a more realistic subdomain test than we had before  :)
