### ISSUE TITLE
Does "iris.ToHandlerFunc()" function still exist?

### ISSUE THREAD

**Issue by celsosz** [kataras/iris#578]
Hi Everyone. Happy new year!

Something has changed with "iris.ToHandlerFunc()" function? Does it still exist?

I am having the following error message: "undefined: iris.ToHandlerFunc".

I migrated my environment to a new notebook. The codebase is the same. I just tried to rebuild (go build).

Sorry for my English.

Best regards,
Celso.

**Comment by kataras** [comment]
Simply 'iris.ToHandler' handles your case now
