### ISSUE TITLE
Where is a PostBody?

### ISSUE THREAD

**Issue by monopollly** [kataras/iris#580]
- Version : **6.0.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Hi are you delete a c.PostBody()?
Why?
How to get a raw body now?
Thanks!

**Comment by FanFani4** [comment]
c.Request.Body is an io.Reader interface

**Comment by kataras** [comment]
@monopollly It's like net/http raw, you can view all request's fields and methods by `context.Request.` or all post methods with `context.Post...` we have many Post methods  as before, nothing is missing from before v6 :) If the requested METHOD is POST then you can just read all body by `ioutil.ReadAll(context.Request.Body)` as @FanFani4  noticed, you will get the raw body in slice of byte.
