### ISSUE TITLE
local Remote Address seems changed when updated to latest iris

### ISSUE THREAD

**Issue by Tanete** [kataras/iris#583]
- Version : **6.0.8**

- Operating System: Linux Mint 18.1 Cinnamon 64-bit

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I just updated from iris.v4 to latest iris.

I noticed that `RequestIP` was removed from `iris *Context`, but I could not find any **description/warn** in **changelog/commits message/histroy**.

Is it recommended that use only `ctx.RemoteAddr` to get client's request IP now?

In addition, I run my project on local machine, the `Remote Address` of http request header changed from `127.0.0.1:8088` to `[::1]:8088` after updating latest iris. This caused some failure in my code. What is the reason of this change? Is there something wrong?

Thanks kataras!

**Comment by kataras** [comment]
You updated from v4 to v6 and you have only two questions? That's nice, thanks!

> RequestIP/RemoteAddr

I removed the `RequestIP` because net/http has its own function for that: `ctx.Request.RemoteAddr`

but we keep the `ctx.RemoteAddr()` because it covers more details on how to find the client's IP, I use that everytime and I recommend you to do the same.

>  In addition, I run my project on local machine, the Remote Address of http request header changed from 127.0.0.1:8088 to [::1]:8088

I didn't understand the question, you mean the `Listen` func? the `RemoteAddr` func or the `Request.RemoteAddr` field ?

**Comment by Tanete** [comment]
Not the `Listen` func.
Yeah, It's the `ctx.Request.RemoteAddr` func/field.
Bellow code in func (ctx *Context) RemoteAddr()
```go
addr := strings.TrimSpace(ctx.Request.RemoteAddr)
```
`addr` is `[::1]:8088` in latest iris. When opening Chrome Dev Tool, I saw the Remote Address of request turned into `[::1]:8088` too.

![image](https://cloud.githubusercontent.com/assets/5023202/21811441/a9c95222-d78a-11e6-92ea-d4604ed6450a.png)

**Comment by kataras** [comment]
::1is the IPv6 equivalent of localhost
Maybe you are behind a proxy?

**Comment by kataras** [comment]
::1is the IPv6 equivalent of localhost (net/http , fasthttp worked other way for your case, but this can be solved with one line of code, just replace the [::1] with 127.0.0.1 )
Maybe you are behind a proxy? Try `ctx.RemoteAddr()`

**Comment by kataras** [comment]
::1is the IPv6 equivalent of localhost (net/http works this way, fasthttp didn't) 
Maybe you are behind a proxy? 

Solutions: 

-  Try `ctx.RemoteAddr()` 
- `ctx.RequestHeader("Origin")` 
- External (easy) solution which I think you will not need, but here you go: https://husobee.github.io/golang/ip-address/2015/12/17/remote-ip-go.html

One of these should do the job for you, write below if you need more help.

**Comment by Tanete** [comment]
Thanks!

I located the problem about `::1`. It seems to be my own problem. Hosts file on my PC (`/etc/hosts`) added these lines by [this hosts tool](https://github.com/racaljk/hosts/blob/master/hosts) to get access to Google in China.

```hosts
# Localhost (DO NOT REMOVE)
127.0.0.1       localhost
::1    localhost ip6-localhost ip6-loopback
```
After I commented the line starting with `::1`, `Remote Address` turns back into `127.0.0.1` and everything works now.

But it is strange to find that only latest iris (v6) get `localhost` as `::1` in same dev env.

**Comment by kataras** [comment]
the ::1 is the correct, it's an alias for ipv6 localhost. If you have any questions don't hesitate to post!
