### ISSUE TITLE
MultipartForm.File feature in Context menu

### ISSUE THREAD

**Issue by sapnaSpaceo** [kataras/iris#586]
- Version : **6.1.2**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
Hello,
I am not able to find proper implementation for Multiple files feature in Iris template can you suggest me how I can do that?

Asking for feature which we do in golang 
r.MultipartForm.File["files"] 

Can we do like this ctx.MultipartForm.File["files"]  ?

**Comment by kataras** [comment]
`context` has both `*http.Request` and a customized `http.Response`, so you can use the standard functions you already know. So: 

> Asking for feature which we do in golang
r.MultipartForm.File["files"]

You can, simply, do `ctx.Request.MultipartForm.File["files"]`  :)

**Comment by kataras** [comment]
@`context` has both `*http.Request` and a customized `http.ResponseWriter`, so you can use the standard functions you already know. So: 

> Asking for feature which we do in golang
r.MultipartForm.File["files"]

You can, simply, do `ctx.Request.MultipartForm.File["files"]`  :)

**Comment by sapnaSpaceo** [comment]
Hello,
thanks for clarifying the concept. I have tried the solution which you suggested.I am attaching screen shot of the error message I got while running below code.Please let me know where I am wrong in this.

package main

import (
	"fmt"
	"github.com/kataras/iris"
)

func main() {
	iris.Post("/api", func(ctx *iris.Context) {
		iris.Config.IsDevelopment = true
		image_files := ctx.Request.MultipartForm.File["files"]
		fmt.Println("Images")
		fmt.Println(image_files)
	})
	iris.Listen(":8080")
}
![panicerror](https://cloud.githubusercontent.com/assets/19609185/21972229/12133d50-dbde-11e6-96da-6949761627de.png)
