### ISSUE TITLE
iris.API call doesn't works for me

### ISSUE THREAD

**Issue by modi-swati** [kataras/iris#587]
- Version : **6.1.2**

- Operating System:

- [x] I have updated iris version from 5 to 6.1.2. After updating api request call are not working. Please let me know what i have to do to.

--------------

**Comment by kataras** [comment]
What do you mean by "api request call". All functions are tested, if you mean the `iris.API`, as I describe to the book and on examples it is not supposed to use for production, it's like a controller-ready but it's slower than standard iris' methods for building a fast API. Let me see what I can do for you.
