### ISSUE TITLE
caching issue with Parameters

### ISSUE THREAD

**Issue by apetitbois** [kataras/iris#59]
Hi,

I have a party handler using two methods :

status := api.Party("/status")
{
	status.Get("/", GetStatus)
	status.Get("/:slug", GetStatus)
}

My function GetStatus will check if you have a c.Param("slug") and return a different value based on that slug.

When I call /status/slug1, it returns slug1
when I call /status/slug2, it returns slug2

when I call slug1, slug2, slug1, it returns slug1, slug2, slug2

If I disable cache entirely, I don't have the same issue.

**Comment by kataras** [comment]
@apetitbois This should not be a problem I just tested and no problem with cache on or cache off, cache does nothing with parameters, can you please share the whole code here in order to see what's wrong?

**Comment by kataras** [comment]
@apetitbois  You've right, the cache does nothing with parameters but if we run the slug1,slug2 and after slug1 again it returns slug1,slug2,slug2 ( because it keeps the previous slug2) but cache doesn't do that, the problem must be inside the .Clone function of the Context, let me look it

**Comment by kataras** [comment]
@apetitbois  Thanks for feedback, fixed :)

**Comment by apetitbois** [comment]
Thanks for the quick fix !

**Comment by kataras** [comment]
@apetitbois Always my friend
