### ISSUE TITLE
SendFile does not work correctly, cannot customize fileName.

### ISSUE THREAD

**Issue by Tanete** [kataras/iris#590]
- Version : **6.1.2**

- Operating System: Linux Mint 18.1 Cinnamon 64-bit

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

`SendFile` in `Context` does not work correctly in latest iris. As shown in sample code below, only the 4th /last router could render the filename as the code wanted.

```go
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/servezip1", func(c *iris.Context) {
		file := "./files/first.zip"
		c.SendFile(file, "1.zip")
	})

	iris.Get("/servezip2", func(c *iris.Context) {
		file := "./files/first.zip"
		c.SendFile(file, "2.zip")
	})

	iris.Get("/servezip3/file", func(c *iris.Context) {
		file := "./files/first.zip"
		c.SendFile(file, "3.zip")
	})

	iris.Get("/servezip4/:fileName/:pkgName", func(c *iris.Context) {
		fileName := c.Param("fileName")
		pkgName := c.Param("pkgName")
		c.SendFile(fileName, pkgName)
	})
	iris.Listen(":8080")
}
```

**Comment by Tanete** [comment]
I found this when I changed sample code below in iris-contrib/examples into my code above.

```go
package main

import "github.com/kataras/iris"

func main() {

	iris.Get("/servezip", func(c *iris.Context) {
		file := "./files/first.zip"
		c.SendFile(file, "first.zip")
	})

	iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
I'll look into this soon, I'm designing a new API for custom routers. Expect a fix for your issue until tomorrow. Thanks for the report!

**Comment by kataras** [comment]
Hello @Tanete ,

I just fixed that, it was a header-write order issue. Please upgrade iris with `go get -u github.com/kataras/iris` and you should be fine.

Thanks for the report!

**Comment by Tanete** [comment]
Yes, fixed already. Thanks!
