### ISSUE TITLE
Autocompletion for iris package isn't working with gocode

### ISSUE THREAD

**Issue by njuettner** [kataras/iris#591]
- Version : **6.1.2**

- Operating System: MacOS 10.12.2

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

There seems to be an issue with gocode and atom. When I'm trying to autocomplete the iris package it doesn't work because there's an parsing problem, see below:

2017/01/18 11:33:52 Found "github.com/kataras/iris" at "/Users/nick/go/pkg/darwin_amd64/github.com/kataras/iris.a"
2017/01/18 11:33:52 Error parsing input file (inner block):
2017/01/18 11:33:52  13:1: expected selector or type assertion, found '}'
2017/01/18 11:33:52  13:2: expected ';', found 'EOF'
2017/01/18 11:33:52  13:2: expected '}', found 'EOF'
2017/01/18 11:33:52 extracted expression tokens: iris

I tried to get other packages from different web frameworks, since I was doubting that it's an issue with iris. But there everything seems to work, I can immediately autocomplete the whole package.

I've also removed the package and built it again. No luck.

**Comment by njuettner** [comment]
I've also removed the package and built it again. No luck.

**Comment by kataras** [comment]
Hello @njuettner,

This was the first time a user report something like this.

I'm using atom+go-plus plugin for atom and iris auto completion working just fine (on windows 10, win 7 vb and ubuntu 16.04 vb). Try to remove the whole $GOPATH/src/github.com/kataras and $GOPATH/bin/iris and $GOPATH/pkg/iris.a and exec: `go get github.com/kataras/iris/iris`
