### ISSUE TITLE
Getting Cannot read property 'length' of undefined erro

### ISSUE THREAD

**Issue by avinlakhera** [kataras/iris#593]
Hi I am using iris websocket. from client side when every I am Emitting some think I am getting below error in console 

Uncaught TypeError: Cannot read property 'length' of undefined
    at Ws.fireMessage (iris-ws.js:202)
    at Ws.messageReceivedFromConn (iris-ws.js:143)
    at WebSocket.Ws.conn.onmessage (iris-ws.js:44)

**Comment by kataras** [comment]
Dear @avinlakhera 

That's strange I am working with websockets on a chat application with the current iris version and all seems to be working just fine. 

So I'll ask you to test some things: 

- First, check if the websocket example shows the same errors, go here: https://github.com/iris-contrib/examples/tree/master/websocket , download and run it, write below the results of your web browser's console output.

- Could you please give us more information? Like your web browser name, the iris version and a code snippet of your client side(.js) and your server-side(.go). 



Thanks,
kataras

> It seems that you didn't read the CONTRIBUTION file on how to write post issues into Iris project, but this is OK for your first post issue.
