### ISSUE TITLE
Angular2 routing conflicts

### ISSUE THREAD

**Issue by es-lab** [kataras/iris#594]
- Version : **6.1.1**

- Operating System: mac os sierra

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I have conflicts using iris routing and angular routing together. 
I need my angular app to be served on the root domain, and I do it like this:
`app.Get("/*file", app.StaticHandler("/", "./public/ng/", false, true))`  

After my app is served, angular will continue to manage all the routing, but the problem comes in when I refresh the browser, if I'm on another route than '/' (eg: '/auth/login') then iris will try to find a folder named auth instead of returning the same index.html with the other resources, and here the server returns a not found.

I saw there is an spa example, but that's not my use case, I already moved all my api on a subdomain.

A solution to this may be to apply the same behavior as for the spa. It may look like this:
The code below is invented, but I hope you get the concept
```
res := app.None("/res/*file", app.StaticHandler("/res", "./public/ng/", false, true))("res")
app.Get("/*_", func(context *iris.Context) {
	context.ServeFile("public/ng/index.html", true)
}, res)
```

I know I could just move all my app to another route (eg: '/home'), and use a redirect from the / to the /home and serve all my resources from a route called /res but It's kind of weird.

If you understand my problem, please help me solving it.
Thanks

**Comment by kataras** [comment]
I understand your problem, it conflicts because of wildcards (static handlers uses wildcards too) but iris has a solution for that too: 

```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	usersAPI := iris.None("/api/users/:userid", func(ctx *iris.Context) {
		ctx.Writef("user with id: %s", ctx.Param("userid"))
	})("api.users.id")

	authLogin:= iris.None("/auth/login", func(ctx *iris.Context) {
		ctx.Writef("auth login here"))
	})("auth.login")

      // third parameter is optional, if not empty then these routes 
      // will have priority over the static handler when the request path is one of their route's path
      iris.StaticWeb("/", "./www", usersAPI, authLogin)

      iris.Listen("localhost:8080")
}

```

Does this helped you?

**Comment by es-lab** [comment]
Hi @kataras,
Thanks for the second solution. It works great!

**Comment by kataras** [comment]
You're welcome @es-lab , happy to helped out!
