### ISSUE TITLE
Websocket hangs when calling iris.WebsocketConnection.Leave() on Disconnect

### ISSUE THREAD

**Issue by antlaw** [kataras/iris#595]
- Version : **5.0.4**

- Operating System: Windows 10

- In an simple IRIS websocket server, if the server try to leave a room when it detects a websocket is disconnected, the websocket server will hang. The following is a code piece to illustrate the problem (It is not the exact code piece that  reproduces the problem, but it is a simplified version to demonstrate what I am talking about).

- In the following code piece, if the line "c.Join("server")" and "c.Leave("server")" are there, once the program comes to c.Leave("server"), the program will hang there and will not continue.

- To me, a simple fix is, of course to avoid the line "c.Leave("server")", but I think fixing WebsocketConnection.Leave() would make iris more robust.

--------------

// OnConnect handles incoming websocket connection
func OnConnect(c iris.WebsocketConnection) {
	c.Join("server")
	c.OnDisconnect(func() { OnDisconnect(c) })

}

// OnDisconnect clean up things when a client is disconnected
func OnDisconnect(c iris.WebsocketConnection) {
	c.Leave("server")
}

**Comment by kataras** [comment]
You're referring to [this](https://github.com/kataras/go-websocket).

If I understood your post,
The client `leaves automatically` from all connected rooms `when disconnected` , you should not call `c.Leave` after Disconnect, the `OnDisconnect` is to make cleanup of your other source code that depends on this client, not to call functions from this client.

So you are telling that the `c.Leave` on already left-room is the referring bug? Did you get any message from console? What you expected to do on the `c.Leave` inside `OnDisconnect` ?

**Comment by kataras** [comment]
You're referring to [this](https://github.com/kataras/go-websocket) repository.

If I understood your post,
The client `leaves automatically` from all connected rooms `when disconnected` , you should not call `c.Leave` after Disconnect, the `OnDisconnect` is to make cleanup of your other source code that depends on this client, not to call functions from this client.

So you are telling that the `c.Leave` on already left-room is the referring bug? Did you get any message from console? What you expected to do on the `c.Leave` inside `OnDisconnect` ?

**Comment by kataras** [comment]
You're referring to [this](https://github.com/kataras/go-websocket) repository.


The client `leaves automatically` from all connected rooms `when disconnected` , you should not call `c.Leave` after Disconnect, the `OnDisconnect` is to make cleanup of your other source code that depends on this client, not to call functions from this client.

If I understood your post,
So you are telling that the `c.Leave` on already left-room is the referring bug? Did you get any message from console? What you expected to do on the `c.Leave` inside `OnDisconnect` ?

**Comment by kataras** [comment]
You're referring to [this](https://github.com/kataras/go-websocket) repository.


The client `leaves automatically` from all connected rooms `when disconnected` , you should not call `c.Leave` after Disconnect, the `OnDisconnect` is to make cleanup of your other source code that depends on this client (for example a list of all connected websocket clients), not to call functions from this client.

If I understood your post,
You are telling that the `c.Leave` on already left-room is the referring bug? Did you get any message from console? What you expected to do on the `c.Leave` inside `OnDisconnect` ?

**Comment by kataras** [comment]
You're referring to [this](https://github.com/kataras/go-websocket) repository.


The client `leaves automatically` from all connected rooms `when disconnected` , you should not call `c.Leave` after Disconnect, the `OnDisconnect` is to make cleanup of your other source code that depends on this client (for example a list of all connected websocket clients), not to call functions from this client.

If I understood your post,
You are telling that the `c.Leave` on disconnected client is the referring bug. Let me fix it and I'll respond in a few

**Comment by antlaw** [comment]
Yes, you understand the problem. Actually I cannot find comment on when to call c.Leave and when not to do so, therefore I put it in OnDisconnect().

**Comment by kataras** [comment]
Fixed

**Comment by kataras** [comment]
Fixed, please verify it

> on v.0.0.3 branch (which is the gopkg path for iris.v5) too

@antlaw  Thanks for the report! Please next time post issues about websockets on [this repo](https://github.com/kataras/go-websocket)
