### ISSUE TITLE
I have update iris to 6.1.2 but can not read the Request Body

### ISSUE THREAD

**Issue by yinhui87** [kataras/iris#596]
- Version : **6.1.2**

- Operating System:MacOS Sierra

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I have update iris to 6.1.2 and update some function to new version, but I can not get request body now. I can use context.Body() to get http body, how can I get the request body with iris 6.1.2?

**Comment by kataras** [comment]
`context.Request.Body` is an io.Reader interface. 

So you can read from it, one way to do it is: `ioutil.ReadAll(context.Request.Body)`. This is a basic net/http question
