### ISSUE TITLE
how to do authenticate Go lang rest api with iris framework

### ISSUE THREAD

**Issue by vvd12345** [kataras/iris#599]
how to do authenticate Go lang rest api with iris framework

**Comment by kataras** [comment]
Navigate through the [examples](https://github.com/iris-contrib/examples) before post something, please. 

In general" you can 'do authenticate Go lang rest api like you do with net/http or other web framework, these things are not 'special-to-a-framework'' , Iris provides you some plugins and middleware to work with, (see the examples) but you can use any method you want and may used before Iris.
