### ISSUE TITLE
Websocket lost the connection.

### ISSUE THREAD

**Issue by tspn** [kataras/iris#602]
- Version : **6.1.2**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------
I ran my old project that use iris and I found that websocket close the connection automatically.
I tried to run example file (/iris-contrib/examples) and it go the same way.

**Comment by kataras** [comment]
Dear @tspn ,
First time that someone reports something like this, what exactly do you mean by this? 

Write down the version of your `iris` and `kataras/go-websocket` library and a code snippet of your program, because the examples are running well here.

Thanks,
kataras

**Comment by kataras** [comment]
Dear @tspn ,
First time that someone reports something like this, what exactly do you mean by this? 

Write down the version of your `iris`, I am sure that you're not using the latest iris (you wrote 'old project that use iris') so please:

- Upgrade your iris with `go get -u github.com/kataras/iris`, re-run your program
- If step 1 produces the same behavior then, write a code snippet of your program, because the examples are running well here.

Thanks,
kataras

**Comment by kataras** [comment]
Dear @tspn ,
First time that someone reports something like this, what exactly do you mean by 'close the connection automatically', when, how, where? 

Write down the version of your `iris`, I am sure that you're not using the latest iris (you wrote 'old project that use iris') so please:

- Upgrade your iris with `go get -u github.com/kataras/iris`, re-run your program
- If step 1 produces the same behavior then, write a code snippet of your program, because the examples are running well here.

Thanks,
kataras

**Comment by tspn** [comment]
Iris version is 6.1.2 and lastest commit aa8f6649e880f64e5579f87330bd503ec9747414.
go-websocket lastest commit is c688b53fa37da2a8bcca1976a68b8e649e76d8a7.

- I ran my project tspn/wrk-load-testing-module and found that websocket work incorrectly.
- I clone this project https://github.com/iris-contrib/examples/tree/master/websocket to test a simple websocket work.
- I ran the the project and open browser to http://127.0.0.1:8080
- Waiting about 10 second and "Disconnected" appear in the page

It's seem like the websocket close connection by themself.
Is that correctly work ?

**Comment by kataras** [comment]
Iris' default websocket library (aka [go-websocket](https://github.com/kataras/go-websocket)) is based on the [gorilla/websocket](https://github.com/gorilla/websocket), at the [last issue we fixed](https://github.com/kataras/go-websocket/issues/24) we had to test thousands of clients running for hours and we didn't got any issue like you describe here, I can assume only that your code has some flues that you have to manage.

If the current implementation doesn't suits you can use any other external websocket alternatives with Iris (all golang websocket libraries are compatible with Iris). I can see from your code that you have included the client side of socket.io, so why you don't use the socket.io server-side golang library(aka [/googollee/go-socket.io](https://github.com/googollee/go-socket.io)) and test if you can reproduce the same?

**Comment by kataras** [comment]
Iris' default websocket library (aka [go-websocket](https://github.com/kataras/go-websocket)) is based on the [gorilla/websocket](https://github.com/gorilla/websocket), at the [last issue we fixed](https://github.com/kataras/go-websocket/issues/24) we had to test thousands of clients running for hours and we didn't got any issue like you describe here, I can only assume that your code has some flues that you have to manage and it is not library's issue.

If the current implementation doesn't suits you can use any other external websocket alternatives with Iris (all golang websocket libraries are compatible with Iris). I can see from your code that you have included the client side of socket.io, so why you don't use the socket.io server-side golang library(aka [/googollee/go-socket.io](https://github.com/googollee/go-socket.io)) and test if you can reproduce the same?

**Comment by kataras** [comment]
Iris' default websocket library (aka [go-websocket](https://github.com/kataras/go-websocket)) is based on the [gorilla/websocket](https://github.com/gorilla/websocket), at the [last issue we fixed](https://github.com/kataras/go-websocket/issues/24), before ~2 days, we had to test thousands of clients running for hours and we didn't got any issue like you describe here, I can only assume that your code has some flues that you have to manage and it is not library's issue.

If the current implementation doesn't suits you can use any other external websocket alternatives with Iris (all golang websocket libraries are compatible with Iris). I can see from your code that you have included the client side of socket.io, so why you don't use the socket.io server-side golang library(aka [/googollee/go-socket.io](https://github.com/googollee/go-socket.io)) and test if you can reproduce the same?
