### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by rikvdh** [kataras/iris#603]
- Version : **6.1.2**

- Operating System: Any

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Since google/brotli is making its way into servers (Nginx/Apache) and also in Browsers (http://caniuse.com/#feat=brotli) perhaps it is a good idea to embed this into iris?

The performance gain w.r.t. Gzip can be huge.

**Comment by kataras** [comment]
Dear @rikvdh This is not even a Go library.
Do you really expect to spend a month(++) to to port the whole library to Go?

If you have any idea I can make it happen, if you want to support any Go library I can do that, but to convert a whole software to Go in order to be used in Iris, this never happens I work alone I don't have a team behind me, sorry.

**Comment by kataras** [comment]
Dear @rikvdh This is not even a Go library.
Do you really expect to spend a month(++) to to port the whole library to Go?

If you have any idea I can make it happen, if you want to support any Go library I can do that, but to convert a whole software to Go in order to be used in Iris? this never happens I work alone I don't have a team behind me, sorry.

**Comment by kataras** [comment]
Dear @rikvdh This is not even a Go library.


If you have any idea I can make it happen, if you want to integrate any Go library into Iris, I can do that also.

First, ask a Go port from [google/brotli](https://github.com/google/brotli), after ask from me to integrate that to Iris. I'm not willing and I don't want to spend a month only to port a whole C program to Go.

Thanks,
kataras

**Comment by skhameneh** [comment]
I wish this hadn't been closed, it would be nice to see it done through the same caching mechanism as gzip.  Brotli level 1 is faster than zlib gzip level 1, with better compression than zlib gzip level 3.

At some point, I'll work on middleware for this.  @kataras Any chance you'd reconsider this as a base feature for Iris?  It's supported in Firefox & Chrome and will be supported in the next Edge release as well.

**Comment by kataras** [comment]
Hello @skhameneh thanks for posting!

I totally understand you and  I already watching this subject even before posted. I accept almost every community feature request but not all of them, I want to but I know that this is not a good idea. Implement a feature that is not critical-necessary inside iris' main repository while it and can be work the same as a middleware is a bad idea, believe me. Features like this can be created as middleware, as you mentioned too, or as an adaptor(if more control needed). As you mentioned, this is not even supported by all web browsers, we are looking the future but we should have built'n features that can work for the whole developers and their users.

Sorry but I hope that you understand that we cannot implement everything in the main repository, it may sound strange at the first but you'll thank me later :) This is the main idea of Iris, you can now do almost anything without even touch the framework base. 

Iris is very extensible framework, we don't need to keep all things in the main repository, believe me. We should keep this framework lightweight as much as we can. 

I'll be glad if you implement this as a middleware on your own custom repository or push a PR to the[iris-specific community middleware repository](https://github.com/iris-contrib/middleware).

Thanks,
kataras
