### ISSUE TITLE
Go1.8 is released

### ISSUE THREAD

**Issue by ghost** [kataras/iris#606]
_Last update: 17 Feb 2017_

As I promised to the Community, I have completed the Iris' core for the new Go' 1.8 features.

[GoDocs](https://godoc.org/gopkg.in/kataras/iris.v6) are readable now, so you can read the whole documentation from there, nothing more needed. Each addon(adaptors and middleware) has its own `_example` folder too!  

Iris is only compatible with [Go 1.8](https://golang.org/dl/). Users should download the new version if they can, otherwise they should not upgrade their local Iris.

- 2 Routers to select from (httprouter and gorillamux), same API for both of them

- 5 template engines to select from (html, django, pug, handlebars, amber)

- Websocket and Sessions improvements

- Installation size reduced by 50%

- New Event flow

- New Logger

- `context.Push(...)` for Server Push

- `app.Shutdown(...)` for Gracefully shutdown 

- 9 minor fixes

- cors middleware fixed

- Fix and improve oauth/oauth2

- Fix typescript compiler and hot-reloader

- Fix and improve the cloud-editor alm/alm-tools

- External third-party middleware of form `func(http.ResponseWriter, *http.Request, next http.HandlerFunc)` can now be used without any boilerplate code using `iris.ToHandler`

- Addons([adaptors](https://github.com/kataras/iris/tree/v6/adaptors) and [middleware](https://github.com/kataras/iris/tree/v6/middleware) have their own `_example` folder 

- New community repository for [Community Adaptors](https://github.com/iris-contrib/adaptors)

- [iris-contrib/middleware](https://github.com/iris-contrib/middleware) folders are tested and refactored, those who didn't pass the tests are removed (like the PR for zaplogger, it had compiled errors on its own import path lol...)

Even better performance boost can be achieved using `context.Push`. An example which combines Iris' `TLS`, `Secure Websockets` and `Server Push`, can be found [here](https://github.com/kataras/iris/tree/v6/adaptors/websocket/_examples/websocket_secure).

Newcomers: do not try to search older issues for answers, most of that code is deprecated, Iris has been re-based. Ask anything iris-relative and I personally will answer to you immediately!

Read [HISTORY.md](https://github.com/kataras/iris/blob/v6/HISTORY.md) if you think that you miss something. 

> It's possible that this post will be updated to catch upcoming news about this release. You will be able to understand via `Last Update: xxx-xxx-xxx` text on the top-left corner.

**Comment by adarqui** [comment]
Hey @kataras, I recently updated to go1.8 and i'm getting tons of errors, for example:

```
http.go:26: undefined: "gopkg.in/kataras/iris.v6".Set
http.go:26: undefined: "gopkg.in/kataras/iris.v6".OptionIsDevelopment
http.go:28: undefined: "gopkg.in/kataras/iris.v6".Use
http.go:28: undefined: recovery in recovery.New
http.go:31: undefined: "gopkg.in/kataras/iris.v6".Use
http.go:34: undefined: "gopkg.in/kataras/iris.v6".UseSessionDB
http.go:42: undefined: "gopkg.in/kataras/iris.v6".OnError
http.go:63: undefined: "gopkg.in/kataras/iris.v6".Listen
```

I see that iris.Set for example is in the iris go docs.. any idea?

Thanks alot

**Comment by adarqui** [comment]
Also I have a bunch of "wrapper functions" which used to return a RouteNameFunc. What should I replace that with?

```
func (state *State) ApiPut(path string, handlerFn ...iris.HandlerFunc) iris.RouteNameFunc {
```

Sorry, trying to tackle all of these things to get my code to build again. So asking in advance.

**Comment by adarqui** [comment]
Hi @kataras , i'm currently reading though that history file you made, it's helping me find/fix issues. One thing i'm looking for, is RouteNameFunc. I have a bunch of wrappers which return a RouteNameFunc like this:

```
func (state *State) ApiAuthGet(permissions int64, path string, authHandlerFn AuthHandlerFunc) iris.RouteNameFunc {
...
}
```

What should I replace that with?

Thanks so much.

**Comment by adarqui** [comment]
Hi @kataras,

Is https://godoc.org/gopkg.in/kataras/iris.v6/middleware/logger up to date? I can't use it via iris.Default.Adapt(logger.New(...)) . It's returning a HandlerFunc but, it should be returning Policies?

Sorry, confused. Trying to get everything to build again.

**Comment by adarqui** [comment]
This answers my logger question: https://github.com/kataras/iris/issues/615

**Comment by kataras** [comment]
@adarqui Yes it's up-to-dated of course. 

**Logger itself has an example(https://github.com/kataras/iris/blob/v6/middleware/logger/_example) ** it's a middleware not an adaptor, you should `.Adapt` adaptors, and `.Use` the middleware. 

Adaptors and middleware are not the same thing.

Middleware is like you knew from before, all web frameworks uses them too at all programming languages.
They are being used per-route (preppend/append to the route's handler, order matters) , per-subdomain( `mysubdomain.Use/.UseFunc`), per-party( `myGroupParty.Use/.UseFunc`) or per all routes globally  ( `app.Use/.UseFunc`).

Adaptors is a feature for the entire application, no just per-route or per-party or per-subdomain. Think it like plugins, can be registered before any route are registered using the `app.Adapt(...)`

**Comment by kataras** [comment]
@adarqui Yes it's up-to-dated of course. 

**Logger itself has an example(https://github.com/kataras/iris/blob/v6/middleware/logger/_example)** it's a middleware not an adaptor, you should `.Adapt` adaptors, and `.Use` the middleware. 

Adaptors and middleware are not the same thing.

Middleware is like you knew from before, all web frameworks uses them too at all programming languages.
They are being used per-route (preppend/append to the route's handler, order matters) , per-subdomain( `mysubdomain.Use/.UseFunc`), per-party( `myGroupParty.Use/.UseFunc`) or per all routes globally  ( `app.Use/.UseFunc`).

Adaptors is a feature for the entire application, no just per-route or per-party or per-subdomain. Think it like plugins, can be registered before any route are registered using the `app.Adapt(...)`

**Comment by kataras** [comment]
@adarqui Yes it's up-to-dated of course. 

**Logger itself has an example(https://github.com/kataras/iris/blob/v6/middleware/logger/_example)** it's a middleware not an adaptor, you should `.Adapt` adaptors, and `.Use` the middleware. 

Adaptors and middleware are not the same thing.

Middleware is like you knew from before, all web frameworks uses them too at all programming languages.
They are being used per-route (preppend/append to the route's handler, order matters) , per-subdomain( `mysubdomain.Use/.UseFunc`), per-party( `myGroupParty.Use/.UseFunc`) or per all routes globally  ( `app.Use/.UseFunc`).

Adaptors is a feature for the entire application, no just per-route or per-party or per-subdomain. Think it like plugins, can be registered before any route are registered using the `app.Adapt(...)` 

If that helped you, please let me know in order to remove the duplicate posts*
