### ISSUE TITLE
After add time simulation of the business - Dublicated with https://github.com/kataras/iris/issues/55 - Fix on https://github.com/kataras/iris/issues/58

### ISSUE THREAD

**Issue by dbsn** [kataras/iris#61]
First of all, please forgive me for my bad English, translation of this article is by bing.

I really like your work and would like to use it to develop the Web site.
However, I ran a test and found that it had a problem.

In the case of business processing time, it fared well.

Please see here:
http://colobu.com/2016/04/01/Is-iris-the-fastest-golang-router-library/

Main idea of this article is:

Test and production environments are mismatched, Test framework Handler should also join time, So add time simulation of the business:

package main
import (
    "os"
    "strconv"
    "time"
    "github.com/kataras/iris"
)
func main() {
    api := iris.New()
    api.Get("/rest/hello", func(c *iris.Context) {
        sleepTime, _ := strconv.Atoi(os.Args[1])
        if sleepTime > 0 {
            time.Sleep(time.Duration(sleepTime) * time.Millisecond)
        }
        c.Text("Hello world")
    })
    api.Listen(":8080")
}

Run iris 10, and "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello", Concurrent 100, 30 seconds test.
Throughput rate is 97 requests/second

Use Golang's built-in routing capabilities:

package main
import (
    "log"
    "net/http"
    "os"
    "strconv"
    "time"
)
// There are some golang RESTful libraries and mux libraries but i use the simplest to test.
func main() {
    http.HandleFunc("/rest/hello", func(w http.ResponseWriter, r *http.Request) {
        sleepTime, _ := strconv.Atoi(os.Args[1])
        if sleepTime > 0 {
            time.Sleep(time.Duration(sleepTime) * time.Millisecond)
        }
        w.Write([]byte("Hello world"))
    })
    err := http.ListenAndServe(":8080", nil)
    if err != nil {
        log.Fatal("ListenAndServe: ", err)
    }
}

Run gomux 10, and "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello", Concurrent 100, 30 seconds test.
Throughput rate is 9294 requests/second

And In more extreme cases:

Run iris 1000, and "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello", Concurrent 100, 30 seconds test.
Throughput rate is 1 requests/second

Run gomux 1000, and "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello", Concurrent 100, 30 seconds test.
Throughput rate is 95 requests/second

Because Iris to improve performance, the cache context, requests for the same URL and method, it will use the same context from the cache.

When larger amounts of time, multiple client requests are entered in the above method ServeHTTP, lead to the same request will enter the following logic:

if ctx := r.cache.GetItem(req.Method, req.URL.Path); ctx != nil {
    ctx.Redo(res, req)
    return
}

ctx. Redo (res, req) led to loop continuously until each request has finished processing, putting context back in the pool.

For Iris, large amount of concurrent cases, for the same request (req. URL. Same Path and Method) will enter the queue status, resulting in poor performance.

**Comment by kataras** [comment]
@dbsn  First of all please read other issues(opened) before post new, this is dublicated, I have answered to this question, iris is not poor performance is the fastest tested at all scenarios, Secondly please look how to fix it on the issue #58 .

**Comment by dbsn** [comment]
sorry ， I did not see that  https://github.com/kataras/iris/issues/55

**Comment by kataras** [comment]
@dbsn  Is fixed now, for now, please do the tests again and write the results here (if you have time) and thanks for your feedback again!

**Comment by kataras** [comment]
@dbsn Fixed with https://github.com/kataras/iris/commit/9ad833c32962f251404d78331e2bd3544020ebfb
