### ISSUE TITLE
How to config Session Expires =-1?

### ISSUE THREAD

**Issue by yunhor** [kataras/iris#610]
- Version : **6.2.0**

- Operating System:ubuntu 16.10,chrome,firefox

I try to set Expires : -1 or Expires: time.Duration(-1) ,it didn't work
but set to 0 or >0 can work normally

**Comment by yunhor** [comment]
I try to set Expires : -1 or Expires: 	time.Duration(-1) ,it didn't work
but set to 0 or >0 can work normal

**Comment by kataras** [comment]
Tell me what you want to do, you want to remove the cookie on browser close?

**Comment by yunhor** [comment]
yes,I want to cookie only browser open

**Comment by kataras** [comment]
Fixed, please verify it!

**Comment by yunhor** [comment]
Thank you ,kataras
