### ISSUE TITLE
Is the project really open to contributions? Open source?

### ISSUE THREAD

**Issue by JulienBreux** [kataras/iris#612]
Due to my PR #601 in pending since more than 25 days, I'm asking.

Is the project really open to contributions?
Really open source?

Thanks, have a good day. 😃

**Comment by kataras** [comment]
Did you accepted a PR like this in your life's project?

**Comment by kataras** [comment]
If you was me, would you accepted a PR like this in your life's project? Just asking. Have a nice day :)
