### ISSUE TITLE
website for the iris project

### ISSUE THREAD

**Issue by mamiu** [kataras/iris#613]
Hey @kataras,

yesterday I stumbled upon your project and have to say, that I never saw a project like this, where one developer runs such an incredible one-man show!

What I think is missing, in order to gain more quickly on popularity, is to create a website that is just as awesome as your project. I know your gitbook and it's value. But I think a fancy website with all important information is, what people are used to.

In my opinion there are only a few pages necessary, e.g.:

- Homepage -> to promote iris, it's features and explain why it's the best golang web framework
- Tutorial/Guide -> provide a really simple way to get started and also to learn and understand the conventions
- Samples -> source code of some simple iris applications (maybe with demos)
- Docs -> your gitbook
- About -> few words about you and the background of iris

The easiest way probably would be to adjust a free website template (for example one from [https://startbootstrap.com/](https://startbootstrap.com/)).

What do you think about that?

**Comment by kataras** [comment]
Hello @mamiu 
First of all thanks for contacting and for your nice words!

I am not good  in promoting things but we  have a website for iris  (https://iris-go.com), it's quite old and I want to finish the new gitbook (its examples may not run on new iris stable release) first.
Before an hour or so I have also started a new `examples series` for new golang developers, which I'll try to add a new example every single day (https://github.com/iris-contrib/gowebexamples) it's not published yet I'm thinking its domain name.

I don't have time for design things even for ready-templates.

I'm open for any help because I'm sleeping 3-4 hours per day for the last month in order to complete the vNext release :/

**Comment by mamiu** [comment]
Wow, I've never met a developer like you! :1st_place_medal: 

No problem, I can do it if you provide me some content for the pages mentioned above (no images, only text or headwords).
And please accept the pull request with the new logo, it's much more professional than the current one.

**Comment by santoshanand** [comment]
Hi @kataras ,

I would like to contribute on web site designing.

**Comment by mamiu** [comment]
I have to be honest: After looking at the whole project, I became somewhat suspicious. So I googled and found a lot of unpleasant things about iris and it's author.

**So I take back everything I said above.**

Sry, but editing git history to be the only contributor while closing users' pull requests isn't ok!
This project would be awesome, if you would respect other developers source code, licences, copyrights and so on.

Maybe you'll make a shift and drive this project like any other open source project? Then I'll be open to provide help.

**Comment by kataras** [comment]
@santoshanand  and @mamiu Thank you very much for your support, you can contribute by making a folder with your name to the existing repository for the website( http://iris-go.com ): https://github.com/iris-contrib/website

@mamiu See http://iris-go.com for the content, I am not a native english speaker so I'm sure you will find better words to describe Iris and if you need anything I'm here!!!

**Comment by mamiu** [comment]
I have to be honest: After looking at the whole project, I became somewhat suspicious. So I googled and found a lot of unpleasant things about iris and it's author.

**So I take back everything I said above.**

Sry, but editing git history to be the only contributor while closing users' pull requests isn't fair!
This project would be awesome, if you would respect other developers source code, licences, copyrights and so on.

Maybe you'll make a switch and drive this project like any other open source project? Then I'll be open to provide help. I'm sorry, I'm out.
