### ISSUE TITLE
Tip: Forms

### ISSUE THREAD

**Issue by kataras** [kataras/iris#618]
_Last update: 20 Feb 2017_

This example will show how to simulate a contact form and parse the message into a struct.

```go
// forms.go
package main

import (
	"gopkg.in/kataras/iris.v6"
	"gopkg.in/kataras/iris.v6/adaptors/httprouter"
	"gopkg.in/kataras/iris.v6/adaptors/view"
)

// ContactDetails the information from user
type ContactDetails struct {
	Email   string
	Subject string
	Message string
}

func main() {
	app := iris.New()
	app.Adapt(httprouter.New())

	// Parse all files inside `./mytemplates` directory ending with `.html`
	app.Adapt(view.HTML("./mytemplates", ".html"))

	app.Get("/", func(ctx *iris.Context) {
		ctx.Render("forms.html", nil)
	})

	// Equivalent with app.HandleFunc("POST", ...)
	app.Post("/", func(ctx *iris.Context) {

		// details := ContactDetails{
		// 	Email:   ctx.FormValue("email"),
		// 	Subject: ctx.FormValue("subject"),
		// 	Message: ctx.FormValue("message"),
		// }

		// or simply:
		var details ContactDetails
		ctx.ReadForm(&details)
		
		// do something with details
		_ = details

		ctx.Render("forms.html", struct{ Success bool }{true})
	})

	app.Listen(":8080")
}

```
```html
<!-- mytemplates/forms.html -->
{{if .Success}}
	<h1>Thanks for your message!</h1>
{{else}}
	<h1>Contact</h1>
	<form method="POST">
		<label>Email:</label><br />
		<input type="text" name="email"><br />
		<label>Subject:</label><br />
		<input type="text" name="subject"><br />
		<label>Message:</label><br />
		<textarea name="message"></textarea><br />
		<input type="submit">
	</form>
{{end}}
```
```sh
$ go run forms.go
```

> Is possible that this post will be updated to catch any updates. You will be able to understand via `Last Update: xxx-xxx-xxx` text on the top-left corner.

**Comment by olegsobchuk** [comment]
@kataras I can figure out why, but ReadForm doesn't work. At least for me.

If you add `fmt.Println(details)` after `ctx.ReadForm(&details)` it returns empty map. I added issue to stackoverflow [http://stackoverflow.com/q/42409710/3884750](http://stackoverflow.com/q/42409710/3884750).

**Comment by matthmsl** [comment]
@olegsobchuk can you post your code ?

**Comment by olegsobchuk** [comment]
[github](https://github.com/olegsobchuk/go-iris/blob/contact_details/main.go)

**Comment by matthmsl** [comment]
Got it ! You must use caps to first letters of your name attributes in contact_detail.html

```HTML
<!-- http://gopherbook.iris-go.com/forms/ -->
<h1>Contact details form</h1>

{{ if .Success }}
  Thanks!
{{ else }}
  <h3>Contact</h3>
  <form method="POST">
    <label>Email: </label>
    <input type="text" name="Email"><br>
    <label>Subject: </label>
    <input type="text" name="Subject"><br>
    <label>Message: </label>
    <input type="text" name="Message"><br>
    <input type="submit">
  </form>
{{ end }}
```

**Comment by olegsobchuk** [comment]
@matthmsl  thanks it works as you sad. But it is interesting `ReadForm` case sensitive, but `FormValues` not

**Comment by kataras** [comment]
@olegsobchuk ReadForm using Encode/Decode methods to convert an html form to a golang struct, like json, golang supports only exported fields(Uppercase first letter), this is not iris specific, the FormValues is a different thing, it's not converting your struct, it just returns a form value.

**Comment by olegsobchuk** [comment]
@kataras  I understood, thanks. But I guess this point should be stated in documentation.
