### ISSUE TITLE
For the new Iris v 1.1

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#62]
Great news on deciding to use fasthttp, it's a good decision imo.

This is a feature request for upcoming fasthttp based Iris. Just wanted to make you aware that websockets don't work by default with fasthttp as base.

However the author of the project has said that it can be done if I quote:

> There are plans for adding HTTP/2.0 and WebSockets support in the future. In the mean time, third parties may use RequestCtx.Hijack for implementing these goodies. See the first third-party websocket implementation on the top of fasthttp.

I believe having websockets available via fasthttp in Iris will be very unique because no other frameworks have it. It will get Iris a lot of attention and interest. 

Thank you.

**Comment by kataras** [comment]
@kryptodev  Hello! Yes I know this, because of this we will have both net/http and fast http support, I added an option to StationOptions { FastHTTP: false } if someone wants to use websockets. BUT I made some research and think that we could make websockets work on fasthttp we will see, tomorrow !

Today I wrote small ammount of code  in 16hours on my laptop...  but I understand how fasthttp works, it took me a lot but ok :P stay tuned!

**Comment by kryptodev** [comment]
Maybe in your spare time you can check this one out: https://github.com/buaazp/fasthttprouter

Seemed interesting to me.

**Comment by kataras** [comment]
@kryptodev Hmmm it wasn't difficult to convert the router it was the first thing I did, btw nice project. The difficult was, at the beggining, how to make compatible with net/http and fasthttp within the same package and switchable with just an option, but I managed it. Just now finished with cookies too and procced to make the sessions from begin(almost) when I finish it will be released at the master ( I already converted all existing middlewares).

**Comment by kataras** [comment]
FInally... I just finished I do a lot of changes and clean up.. check it and tell me the results, use pipeline with your benchmark tests and see the difference, it's x5 times faster

**Comment by xpbliss** [comment]
Good!

**Comment by kataras** [comment]
@xpbliss  thanks you man, also it's the only framework which has session support for fasthttp :P
