### ISSUE TITLE
can

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#63]
In iris:
```iris.Static("/public", "./static/",1)```
and under  ```static``` directory , there are ``` index.html``` and  ```test.html```.
When i  visit ```http://localhost/public/index.html```,  it can't find the index.html.  but ```http://localhost/public/```  is ok.
How to visit ```http://localhost/public/test.html```?

**Comment by xpbliss** [comment]
And when ```ab -c 100 -k -n 500000 http://127.0.0.1/public```
the error:
 ``` GET http://127.0.0.1/public - cannot open file "./static/public": open ./s
tatic/public: The system cannot find the file specified.```

**Comment by kataras** [comment]
Yes I am working on this normaly you can do that:
You have to use ```iris.Static``` for static assets like javascript,css, html it's better to be loaded by the ```iris.Templates("./templates/*.html")``` 

But right now I see that we have a bug on match any* after last changes, I will fix it fast wait 5 minutes please

**Comment by kataras** [comment]
@xpbliss  Ok now you can use ```iris.Static("/public", "./static",1)``` , thanks for the issue man it was very important
