### ISSUE TITLE
Add asset pipeline (digesting & compression of static files)

### ISSUE THREAD

**Issue by bigcurl** [kataras/iris#630]
- Version : **6.2.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Please either point me to the docu for or add digestion and compression of static files. 

 The output folder will contain:
    * the original file
    * the file compressed with gzip
    * a file containing the original file name and its digest
    * a compressed file containing the file name and its digest
    * a cache manifest file

Example of generated files:
    * app.js
    * app.js.gz
    * app-eb0a5b9302e8d32828d8a73f137cc8f0.js
    * app-eb0a5b9302e8d32828d8a73f137cc8f0.js.gz
    * cache_manifest.json

Similar feature in [Phoenix (Elixir)](https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.digest.ex
) or in [Rails (Ruby)](http://guides.rubyonrails.org/asset_pipeline.html)

**Comment by kataras** [comment]
Hello @bigcurl , thanks for posting

You suggest something that already exists, similar to `webpack`, `fuse-box`, `gulp` and `babel`?

**Comment by bigcurl** [comment]
Depends on the investment of time you are willing to make. 

Phoenix went with a mix of elixir code for digesting and javascript (npm brunch) for compression.
Rails has a ruby only solution.

Go only code would be nice as it would avoid npm installation etc.
