### ISSUE TITLE
fmt.Println prints 3 times iris issue? go issue? me issue?

### ISSUE THREAD

**Issue by phamdt** [kataras/iris#631]
- Version : **6.2.0**

- Operating System: OSX 10.11.6

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

i'm having this weird issue in which a fmt.Println is printing 3 times despite being used once
as in `fmt.Println(os.Stderr, "should print once but prints 3 times")`

i started off with one main.go file and it printed out once as expected. then i started breaking out the app into different directories with multiple packages which is when it started.

it's such a weird thing i don't even know what other relevant code to paste. likewise, i saw the disclaimer that examples are behind the current version, so thought i'd just post this issue.

thoughts?

**Comment by phamdt** [comment]
nevermind, it was just something that i needed to return/exit.

**Comment by kataras** [comment]
Could you please explain to other users where was the issue ?
