### ISSUE TITLE
Can't serve static files in root url with staticEmbedded

### ISSUE THREAD

**Issue by lexrus** [kataras/iris#633]
- Version : **6.2.0**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

```go
app.StaticEmbedded("/", "./public", Assets.Asset, Assets.AssetNames)
// http://127.0.0.1:8888/index.html Always return Not Found
```

```go
app.StaticEmbedded("/public", "./public", Assets.Asset, Assets.AssetNames)
// http://127.0.0.1:8888/public/index.html Works.
```

**Comment by lexrus** [comment]
```go
app.StaticEmbedded("./", "./public", Assets.Asset, Assets.AssetNames)
// http://127.0.0.1:8888/index.html Works.
// http://127.0.0.1:8888/ This one returns Not Found.
```

**Comment by kataras** [comment]
@lexrus Thanks for the report!! It should be fixed now, could you please verify it?

Some notes: at your second comment you wrote `"./", "./public"` HTTP Resource's Paths cannot begin with dot `.` , you can just put a slash `/` as you did on your first comment. (although I 'fix' that too)

**Comment by lexrus** [comment]
@kataras Thank you for your rapid reply!
I'm a newbie gopher. May I ask how to stick to the latest commit? I integrated your lib with `import "gopkg.in/kataras/iris.v6"`

**Comment by kataras** [comment]
Yes of course, just do a `go get -u gopkg.in/kataras/iris.v6`  and you should be ready to test it

**Comment by lexrus** [comment]
Yeah, fixed. Thanks again.

One more thing. I just found StaticEmbedded won't response the index.htm{,l} while visiting the root, http://127.0.0.1:8080/

**Comment by kataras** [comment]
You're welcome,

Yes `StaticEmbedded` depends on your `go bindata` , so the "/" doesn't maps with "index.html" automatically, you have to specify the exactly path, i.e "http://127.0.0.1:8080/index.html" .

This is not a bug but decision, I can change that to map the "index.html" if you think that it will not produce any unexpected results for other users (although you can wrap the handler and do it manually but I will not ask this from you :P ), I'm waiting your opinion!

**Comment by kataras** [comment]
@lexrus  OK, I did change that, now, "/" maps with "/index.html" if "index.html" file exist in the root embedded directory.

Upgrade again with `go get -u gopkg.in/kataras/iris.v6` and verify it when you'll have time please, thank you very much for your reports and welcome to Go!

**Comment by lexrus** [comment]
Oh. You are so gracious and productive. Love you.

**Comment by kataras** [comment]
Thank you very much, you are great!!
