### ISSUE TITLE
OnError not returning HTML

### ISSUE THREAD

**Issue by clanstyles** [kataras/iris#634]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [GopherBOOk](http://gopherbook.iris-go.com), [Examples](https://github.com/iris-contrib/examples), [Contributing File](https://github.com/kataras/iris/blob/v6/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** before.

### What version of Go are you using (`go version`)?
Go 1.8

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What version of Iris are you using?
v6 (latest)

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

app.OnError(http.StatusNotFound, func(ctx *iris.Context) {
	ctx.Render("errors/404.html", iris.Map{"Title": iris.StatusText(iris.StatusNotFound)})
	return
})

### What did you expect to see?
Header text/html

### What did you see instead?
Header text/plain (which prints the text out)

**Comment by kataras** [comment]
Are you sure? I just tried 

```
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Fri, 24 Feb 2017 11:25:26 GMT
Content-Length: 113
```

```go
	app := iris.New()
	// output startup banner and error logs on os.Stdout
	app.Adapt(iris.DevLogger())
	// set the router, you can choose gorillamux too
	app.Adapt(httprouter.New())
	// load the view templates from ./templates folder and .html extension
	// use the standard html/template syntax
	app.Adapt(view.HTML("./templates", ".html"))

	app.OnError(iris.StatusInternalServerError, func(ctx *iris.Context) {
		ctx.Writef(iris.StatusText(iris.StatusInternalServerError)) // Outputs: Internal Server Error
		ctx.SetStatusCode(iris.StatusInternalServerError)           // 500

		println("http status: 500 happened!")
	})

	app.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
		ctx.Render("errors/404.html", nil)
	})

	app.Listen(":8080")
```
```html
<!-- ./templates/errors/404.html -->
<html><head><title>Not Found </title></head>
<body>
	<h1> My custom 404 not found page! </h1>
</body>
</html>
```
