### ISSUE TITLE
websocket emit problem

### ISSUE THREAD

**Issue by kael777** [kataras/iris#636]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [GopherBOOk](http://gopherbook.iris-go.com), [Examples](https://github.com/iris-contrib/examples), [Contributing File](https://github.com/kataras/iris/blob/v6/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** before.

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
macos 10.12

### What version of Iris are you using?
5.0

### What did you do?
i use websocket's emit function to send bytes which i encode by json and base64,
in my program there maybe need 2 or three times sending in a function,
like
val:=FSUtils.GetRandom(10)
(*ctx).EmitMessage([]byte("{\"method\":\"Echo\",\"msg\":\"aojuju\"})}"))
// do staffs here
(*ctx).EmitMessage([]byte("{\"method\":\"Echo\",\"msg\":\"aojuju2\"})}"))
// other staffs

### What did you expect to see?
in client i suppose to see two seperated json bytes in sequence like
"{aojuju}"
then 
"{aojuju2}"
### What did you see instead?
in client receive the two of message be in one like "{aojuju}{aojuju2}"

in the code of emitter.go i saw the message is put in a channel but not send it directly,and i think this cause the problem.

**Comment by kataras** [comment]
@kael777 Sorry for late but I am trying to reproduce this the last days and I can't, could you please share the complete code snippet you use with us in order to solve that?
