### ISSUE TITLE
Which import should I use? gopkg.in/kataras/iris.v6 vs github.com/kataras/iris

### ISSUE THREAD

**Issue by kitgary** [kataras/iris#637]
I am a bit confused, the iris book use github.com/kataras/iris but the README and examples use gopkg.in/kataras/iris.v6, what is the difference?

**Comment by kataras** [comment]
There is nothing strange. As readme says , gitbook is not updated yet, I'm rewriting it with even more chapters. Use gopkg.in/kataras/iris.v6 as examples, gopherbook.iris-go.com and readme .
