### ISSUE TITLE
`gopkg.in` installation problems

### ISSUE THREAD

**Issue by xingcuntian** [kataras/iris#641]
go get gopkg.in/kataras/iris.v6
# gopkg.in/kataras/iris.v6
/data/golang/src/gopkg.in/kataras/iris.v6/response_writer.go:66: undefined: http.Pusher

**Comment by vasukolli** [comment]
May be issue with go version. 
Try with go1.8.

**Comment by xingcuntian** [comment]
Thanks!!

**Comment by kataras** [comment]
Please write your 'solutions' at README.md it already says at least go 1.8 version....
