### ISSUE TITLE
What's wrong with it? strange?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#643]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [GopherBOOk](http://gopherbook.iris-go.com), [Examples](https://github.com/iris-contrib/examples), [Contributing File](https://github.com/kataras/iris/blob/v6/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** before.

### What version of Go are you using (`go version`)?
 go1.8 windows/386

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=386
set GOBIN=c:\go\bin
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\golang
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\bliss\AppData\Local\Temp\go-build939121659=/tmp/go-build
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```
### What version of Iris are you using?
iris version 6.2
### What did you do?
```
package main

import (
	"gopkg.in/kataras/iris.v6"
	"gopkg.in/kataras/iris.v6/adaptors/httprouter"
	"gopkg.in/kataras/iris.v6/adaptors/view"
)
func main() {
	app := iris.New()
	app.Adapt(iris.DevLogger())
	app.Adapt(httprouter.New())
	app.Adapt(view.HTML("./templates", ".html"))
	app.StaticWeb("/public", "./static", nil)
	app.Get("/map/usgs", func(ctx *iris.Context) {
		ctx.SetHeader("Access-Control-Allow-Origin", "*")
		ctx.Render("USGS.html", nil)
	})
	app.Listen(":80")
}
```
and the usgs.html is:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Access-Control-Allow-Origin" content="*">
  <meta HTTP-EQUIV="refresh" CONTENT="1800">
  <title>the title</title>
  <script src="/public/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<body>
  <div id="data"></div>
</body>
 <script type="text/javascript" > 
$.ajax({   
          type:"get",   
      async: false,
          dataType:"json",   
          url:"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson",   
          success:function(data){ 
      alert(data.features[0].properties.time);     
        },
          error: function (XMLHttpRequest, textStatus, errorThrown) { 
        }   
      }); 
 </script>
</html>
```

when i visit ```http://localhost/map/usgs```, it may be ok,  but ``` when i refresh the browser  a few more```.
the console is  

```
[Iris] 2017/03/02 20:15:33 error from a pre-defined error handler while trying t
o send an http error: http: wrote more than the declared Content-Length
......
```

and sometimes it panic!
and some times in the browser debug mode , it shows

 ``` GET http://localhost/public/js/jquery-1.9.1.min.js                             [HTTP/1.1 404 Not Found 3ms] ```
the ````http://localhost/public/js/jquery-1.9.1.min.js``` file is ok.
what's wrong with it?   please help me, @kataras

**Comment by kataras** [comment]
Xmm first time that somebody report something like this, I'll investigate it when I go home, OK?

**Comment by kataras** [comment]
@xpbliss  I'm back, I have to tell you that nothing is wrong with Iris, 
the specific javascript code snippet inside the html is the issue, if you remove that part of the script and replace it with another it works as expected... but I'll try to help you more on this, I'm still working on this.

**Comment by xpbliss** [comment]
but the v5 is all ok!   the v6 is wrong!

**Comment by kataras** [comment]
This is net/http thing I'm sure of it, look. Now it doesn't shows me the error, try to comment the javascript code snippet, run your program, close your program, uncomment the javascript code, clear your browser's cache and it works (on me) please try this flow and tell me the results!

**Comment by kataras** [comment]
I can't reproduce the issue, this is very strange man

**Comment by kataras** [comment]
The error was coming from this line: https://github.com/kataras/iris/blob/v6/status.go#L199 which means was the http.ResponseWriter.Write's error

**Comment by xpbliss** [comment]
these error still appear
 ```
[Iris] 2017/03/03 07:42:20 error from a pre-defined error handler while trying t
o send an http error: http: wrote more than the declared Content-Length
```

**Comment by kataras** [comment]
On me it doesn't, also we don't have a prefix or '[Iris]' on the current version, please do a fast upgrade with `go get -u gopkg.in/kataras/iris.v6` ...

**Comment by kataras** [comment]
On me it was browser's cache thing, and it never panics as you invalidate said. It just shows a log 'useless' error which can be ignored on `http.ResponseWriter.Write` method it has to do with the new version of go 1.8 and its `net/http` package which Iris using underline, Please try to create a code snippet in pure net/http and open a new issue [here](https://github.com/golang/go/issues/new), I am not part of the go dev team.

**Comment by kataras** [comment]
Hello @xpbliss again,
I can't reproduce it second time, but it has something to do with the javascript code inside the html document. If you comment the inline javascript, it works as expected without any error logs. If you clear the browser's cache and uncomment the custom inline javascript code then it runs without any error logs too.

Also I ran it 1kk times(ab) and it never panics as you invalidate said. The error log can be ignored if you remove the line of app.Adapt(iris.DevLogger()).

Your error log comes from the http.ResponseWriter.Write method.
It's certain an 'issue' but it's not Iris-specific, you should refer to the net/http repository on go 1.8 for solving this issue, you never had this issue before because of the golang version.

I test this with pure net/http and the error was the same: http: wrote more than the declared Content-Length .Please try to create a code snippet in pure net/http and open a new issue here, I am not part of the go dev team. Thanks for your contribution!

P.S: Sorry for re-posting but I'm trying to give you as much information as you need to post a correct issue on the golang repository.

**Comment by xpbliss** [comment]
indeed, remove the line of ```app.Adapt(iris.DevLogger())```, and all seem to be ok. 
love iris.
