### ISSUE TITLE
Can't install any of v4..v6 with golang 1.6

### ISSUE THREAD

**Issue by Zoetermeer** [kataras/iris#644]
Steps to reproduce:

$ go version
go version go1.6 linux/amd64
$ go get gopkg.in/iris.v4
package context: unrecognized import path "context" (import path does not begin with hostname)

I cannot get this to work with the v5 or v6 releases either (nor master).

**Comment by kataras** [comment]
Iris v6 Installation README section says `version 1.8 at least` why you try to install with go 1.6? Iris v4 was with go 1.7, never compatible with 1.6. Please read at least the README page of this repository before posting an issue :)
