### ISSUE TITLE
[Chat] community chat!

### ISSUE THREAD

**Issue by pcariel** [kataras/iris#646]
Hi, @kataras . Do you have a chat at [gitter](https://gitter.im) If not, can you create one? Gitter is very popular. Thank you.

**Comment by h4ckedneko** [comment]
From README: https://kataras.rocket.chat/channel/iris

**Comment by pcariel** [comment]
@h4ckedneko, If I have seen, but does not allow integration with github.

**Comment by kataras** [comment]
@pcariel rocket.chat is more featured chat engine. I used gitter for many users but rocket.chat gives more features to their users ( like big file uploads and more, read its features list). You could ask this on chat too, please keep issues for bugs and examples only ...
