### ISSUE TITLE
graceful

### ISSUE THREAD

**Issue by ego008** [kataras/iris#65]
```
$ cat irisgraceful.go
package main

import (
    "github.com/kataras/iris"
    "gopkg.in/tylerb/graceful.v1"
    "time"
)

func main() {
    api := iris.New()
    api.Get("/home", func(c *iris.Context) {
        c.Write("Hello from the /home")
    })

    graceful.Run(":8080", 10*time.Second, api)
}

$ go run irisgraceful.go 
# command-line-arguments
./irisgraceful.go:15: cannot use api (type *iris.Station) as type http.Handler in argument to graceful.Run:
	*iris.Station does not implement http.Handler (missing ServeHTTP method)

```

**Comment by kataras** [comment]
Iris has small build-in support for graceful shutdowns, also you get error because Iris is build on top of fasthttp. I have to convert the whole graceful package to work with this, I will start right now, please wait some time

**Comment by kataras** [comment]
Update with ``` go get -u github.com/kataras/iris ``` , install the iris graceful  ``` go get github.com/kataras/graceful```, and example:

```go

package main

import (
	"time"

	"github.com/kataras/graceful"
	"github.com/kataras/iris"
)

func main() {
	api := iris.New()
	api.Get("/", func(c *iris.Context) {
		c.Write("Welcome to the home page!")
	})

	graceful.Run(":3001", time.Duration(10)*time.Second, api)
}


```

Thanks for your feedback!

**Comment by ego008** [comment]
I got another error when install the iris graceful `go get github.com/kataras/graceful` in my macbook.

```
$ go get github.com/kataras/graceful
# github.com/kataras/graceful
../Goprojects/src/github.com/kataras/graceful/graceful.go:154: srv.Server.Listener undefined (type *iris.Server has no field or method Listener, but does have iris.listener)
```

**Comment by kataras** [comment]
It's working on me, do you update the iris  as I wrote?

**Comment by ego008** [comment]
It is not work just run `go get -u github.com/kataras/iris` before `go get -u github.com/kataras/graceful`.

```
$ go get -u github.com/kataras/iris
$ go get -u github.com/kataras/graceful
# github.com/kataras/graceful
./kataras/graceful/graceful.go:154: srv.Server.Listener undefined (type *iris.Server has no field or method Listener, but does have iris.listener)
```

It works fine for me after `rm -rf $GOPATH/github.com/kataras/iris`.

Thank you for your response and your work on iris.

**Comment by kataras** [comment]
Thanks for the tip, I though that -u makes an upgrade but unfortunately on some systems may not work. 
No problem my friend, thanks for your feedback, you can post any feature you want iris to has,  I'm always here!

**Comment by albertchan** [comment]
This is issue should not be closed, I've ran `go get -u github.com/kataras/iris` but still getting the following error:

```
cannot find package "github.com/kataras/iris/graceful" in any of:
```

**Comment by kataras** [comment]
My dear friend, it is `github.com/iris-contrib/graceful` no kataras/graceful ,
- Remove/Delete your `$GOPATH/src/github.com/kataras` & `$GOPATH/src/github.com/iris-contrib` folders.
-  Upgrade iris ` go get -u github.com/kataras/iris` and then get the graceful package with: `go get -u github.com/iris-contrib/graceful`

**Comment by kataras** [comment]
My dear friend, it is `github.com/iris-contrib/graceful` no kataras/iris/graceful ,
- Remove/Delete your `$GOPATH/src/github.com/kataras` & `$GOPATH/src/github.com/iris-contrib` folders.
-  Upgrade iris ` go get -u github.com/kataras/iris` and then get the graceful package with: `go get -u github.com/iris-contrib/graceful`

**Comment by albertchan** [comment]
You're right! Silly me, I was looking at the wrong docs then. Thanks!

**Comment by kataras** [comment]
You're welcome my friend!
