### ISSUE TITLE
Iris Communities

### ISSUE THREAD

**Issue by kataras** [kataras/iris#658]
Hello Community,

Sorry for being late to start something like this but I was so busy with my new responsibilities.

Here **you will post your active development** clones of Iris. You can "fork" or not "fork" the repository itself,  improve its code and anything else you think its better.

Example: 

```
[$name]($link)

Changes:
- `AttachView` -> `SetView`
- Websocket moved to another repository, [here]($organisation_link_to_websocket_lib)

Performance and speed of router: unaffected/or affected

Improvements:
- ...
- ....
```

You'll choose what community is best to continue developing the Iris open-source base. React with "+1" if you like the posted repository, you can vote more than one repo.

At the end of this week I'll speak with the community has the most "+1" reactions and I'll transfer **this** repository to that community (if it's ok with them).

Thank you very much!

**Comment by godofdream** [comment]
https://github.com/go-siris/siris is a fork of iris v7
Currently we have three maintainers.
Each of us uses siris in some of our projects, so we will continue serving bugfixes.
We try to keep api-changes minimal and will do our best to improve test-coverage and fix any bugs.
We won't delete siris git-history ever and we update any licenses or copyrights we touch.

If you transfer this repository our our organisation, we will archive iris and keep working on siris to make clear it's a fork.
