### ISSUE TITLE
X-Forwarded-For in websocket

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#66]
Hi,

This is either a feature request or not, I wanted to get the X-Forwarded-For parameter from a websocket connection since Iris is running behind Nginx.

Can you tell me how it can be done?
Previously I hacked the gorilla code to pass X-Forwarded-For parameter from the request context, and passed it into a new created function.

Think of it like:

```
func wsHandler(ws *websocket.Conn) {
fmt.Println(ws.XFF())
}
```
The above should print the x-forwarded-for value.

Thank you.

**Comment by kataras** [comment]
Hello, you want access to the X-Forwarded-For  or to all headers?

**Comment by kataras** [comment]
I did it for all headers:

```go

func wsHandler(ws *websocket.Conn) {
      fmt.Println(ws.Header("X-Forwarded-For"))
}

```

Hope that suits you better :)

**Comment by kryptodev** [comment]
Perfect :+1:

**Comment by kryptodev** [comment]
Edit: Works well now.
