### ISSUE TITLE
if get 500 code, how can i get the error?

### ISSUE THREAD

**Issue by igoper** [kataras/iris#660]
v7 benching having error,but i can not get it;

**Comment by kataras** [comment]
`app.OnErrorCode(500, func(ctx context.Context){/*job */ })` 

or inside a done handler ` if app.GetStatusCode() == 500 {/* job */ }`

**Comment by kataras** [comment]
I don't fully get the question but if you want to catch http errors:

`app.OnErrorCode(500, func(ctx context.Context){/*job */ })` 

or inside a done handler ` if ctx.GetStatusCode() == 500 {/* job */ }`
