### ISSUE TITLE
 Just ask, Can the template  be used like this ?

### ISSUE THREAD

**Issue by dotnet123** [kataras/iris#663]
tmpl := view.HTML("templates/**/*", ".html")

If I have multiple folders, how to do it. thanks.

**Comment by hiveminded** [comment]
@dotnet123 `view.HTML("./templates")` will load all files, including subfolders, therefore you don't have to do it with glob.
```go
[...]
tmpl := view.HTML("./templates", ".html")
[...]
func(ctx context.Context){
   // will render the ./templates/user/profile.html
   ctx.View("user/profile.html")
}
```

**Comment by dotnet123** [comment]
I got it , many thanks .
