### ISSUE TITLE
Is @hiveminded a @kataras alter ego ?

### ISSUE THREAD

**Issue by guilhermef** [kataras/iris#664]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.

**Comment by hiveminded** [comment]
Are you serious right now?

**Comment by guilhermef** [comment]
Yeah, @hiveminded account is 17 days old.

**Comment by kataras** [comment]
I removed both @hiveminded 's and @guilhermef 's comments after their acceptance, it was a misunderstanding between them and it solved now.

**Comment by kataras** [comment]
I removed both @hiveminded 's and @guilhermef 's comments after their acceptance, it was a misunderstanding between them and it solved now.
