### ISSUE TITLE
Can we get the reporter?

### ISSUE THREAD

**Issue by corebreaker** [kataras/iris#678]
Hello,

Even if the reporter has exported methods, we can't get the reported configured neither in in Application nor in APIBuilder structure.

However, if we had an GetReporter method on them for getting the reporter, we could call Add or AddErr methods on a reporter.

**Comment by corebreaker** [comment]
I can make a push request for that, it's easy.

**Comment by hiveminded** [comment]
> we can't get the reported configured neither in in Application nor in APIBuilder structure.

Yes we can, there is an exported function, `app.GetReport()` will return the errors as one, we don't give public access to/export the Reporter object itself because it's not used as one, it's combined with other error reporter inside the `iris.Application#Build` function, which is running on `app.Run`.

**Comment by corebreaker** [comment]
So, how do you add an error from inside a Configurator to the caller of app.Run ?

**Comment by hiveminded** [comment]
Okay, I see your point, I thought that letting iris describes its own errors and your application its own by using a custom `errors.Reporter` and wrap the `app.Build` was a better way of doing these things. It's a small PR function without conflicts but I think users will overuse that and report strange issues, so I think it's "dangerous" to export that function. But as you wish, we've to wait for @kataras to review that and share his opinion with us. I am OK with that if helps you.

**Comment by corebreaker** [comment]
Ok, i understand.

**Comment by kataras** [comment]
Hello @hiveminded , @corebreaker Let's accept that, will help to reduce end-developer's code for reporting errors.
