### ISSUE TITLE
How to dynamically render in elements?

### ISSUE THREAD

**Issue by RyanDelap** [kataras/iris#687]
I know "issues" probably isn't the correct place to ask a question, but seeing as the rocket.chat isn't very used, I'll ask here.

I'm trying to add a unspecified amount of \<li> elements to my \<ul>. How could I achieve this? 

I didn't see anything about this in the examples. If I am wrong, my apologies

**Comment by kataras** [comment]
Hello,

Please search on  websites like https://stackoverflow.com, you'll learn much more from there. This is a back-end web framework, not a front-end (like react, angular...).

@RyanDelap [Rocket chat](http://chat.iris-go.com) is very active but you just ask some hours ago, I just wake up...

**Comment by kataras** [comment]
Hello,

I don't quite understand your question, but if you're talking about the `range` html/template keyword, we have an example of this too: 
html: https://github.com/kataras/iris/blob/master/_examples/authentication/oauth2/templates/index.html#L1
go: 
https://github.com/kataras/iris/blob/master/_examples/authentication/oauth2/main.go#L399

If you're not talking about this but you mean client things, then please search on  websites like https://stackoverflow.com, you'll learn much more from there. This is a back-end web framework, not a front-end (like react, angular...).

@RyanDelap [Rocket chat](http://chat.iris-go.com) is very active but you just ask some hours ago, I just wake up...

**Comment by RyanDelap** [comment]
Thank you for the information. I'm new to golang and iris, my apologies for the ignorance. 
Question answered 👍

**Comment by kataras** [comment]
No need for apologies @RyanDelap, I can feel you!,Welcome to go and iris then! Do not hesitate to post in the future!
