### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on windows

### ISSUE THREAD

**Issue by raitucarp** [kataras/iris#69]
It seems iris doesn't support windows. I run the following code and my browser says ERR_TOO_MANY_REDIRECTS

```go
package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/hello", func(c *iris.Context) {
		c.HTML("<b> Hello </b>")
	})
        // I use several port, and it doesn't work either
	iris.Listen(":2020")
}
```

**Comment by raitucarp** [comment]
Sorry, that's my bad. because Iris doesn't use default 500 error handler. And I access / instead of /hello. It gives me redirects.

**Comment by kataras** [comment]
@raitucarp   your issue report was right! It's fixed now just upgrade your iris, thanks!
```
go get -u github.com/kataras/iris
```
