### ISSUE TITLE
Add a function for large files upload?

### ISSUE THREAD

**Issue by xpbliss** [kataras/iris#690]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.

It    always is a problem to  upload and download the large files for web framework.  
Any good ideas for  uploading and downloading the large files?

**Comment by kataras** [comment]
There is no need for a new function, you have everything you want already, I have no problem to upload big files on my iris server.

You can handle the `limit` of received files using the `context#SetMaxRequestBodySize` , i.e `ctx.SetMaxRequestBodySize(10 << 20) // 20MB`, example can be found there: https://github.com/kataras/iris/blob/master/_examples/http_request/upload-files/main.go#L38

You may also want to take a look at a `stackoverflow` question titled "`golang - which function for uploading large files`": https://stackoverflow.com/questions/36254522/golang-which-function-for-uploading-large-files
