### ISSUE TITLE
How can i use template options?

### ISSUE THREAD

**Issue by vinhjaxt** [kataras/iris#694]
I am try to use option function of html/template
So i try:
`tmpl := iris.HTML("./templates", ".html");
tmpl.Option("missingkey=zero");
tmpl.Reload(true);
`
i got an error:
Option is undefined func
then i try:
`tmpl := iris.HTML("./templates", ".html");
tmpl.Templates.Option("missingkey=zero");
tmpl.Reload(true);
`
i got an error:
tmpl.Templates is nil
So, how can i use html template option?
https://golang.org/pkg/html/template/#Template.Option

**Comment by kataras** [comment]
Hello, upgrade with `go get -u github.com/kataras/iris` and try again, it was missing.

**Comment by vinhjaxt** [comment]
Thank you
