### ISSUE TITLE
can not set cookie when POST

### ISSUE THREAD

**Issue by a7a2** [kataras/iris#695]
app.Post("/why/ajaxReg.html", func(ctx iris.Context) {
		ctx.SetCookieKV("why", "can_not_set_cookie")
	})
	app.Get("/why/cookie.html", func(ctx iris.Context) {//cookie not in here
		ctx.View("index/ok.html")
	})

**Comment by kataras** [comment]
@a7a2 I see that you're using go1.9 , look the implementation of the `context#SetCookieKV`:

```go
	c := &http.Cookie{}
	c.Name = name
	c.Value = value
	c.HttpOnly = true
	c.Expires = time.Now().Add(SetCookieKVExpiration)
	c.MaxAge = int(SetCookieKVExpiration.Seconds())
	http.SetCookie(ctx.writer, cookie)
```

As we can see here, there **is nothing special here, it is just net/http, not iris**. 

Could you please open an issue on the [golang/go](https://github.com/golang/go) targets on go1.9 release repository instead?

**Comment by kataras** [comment]
@a7a2 I see that you're using go1.9 , look the implementation of the `context#SetCookieKV`:

```go
	c := &http.Cookie{}
	c.Name = name
	c.Value = value
	c.HttpOnly = true
	c.Expires = time.Now().Add(SetCookieKVExpiration)
	c.MaxAge = int(SetCookieKVExpiration.Seconds())
	http.SetCookie(ctx.writer, cookie)
```


As we can see here, there **is nothing special here, it is just net/http, not iris**. 

If we don't set (comment the lines of ) `c.Expires` and `c.MaxAge` then it works.
I tested it and it doesn't work on GET too, not only POST. Give me some more time to see if that is a go bug or I did something wrong.

**Comment by kataras** [comment]
@a7a2 It's not iris or golang issue. It was a `postman` issue when reading the cookies (the set was worked for both GET and POST) which is solved some days ago, just **update your POSTMAN to the latest version**. Have a nice day!

**Comment by a7a2** [comment]
I've tested on chrome Mac OS.go1.9

2017年8月1日 18:56，"Gerasimos (Makis) Maropoulos" <notifications@github.com>写道：

@a7a2 <https://github.com/a7a2> It's not iris or golang issue. It was a
postman issue when reading the cookies (the set was worked for both GET and
POST) which is solved some days ago, just *update your POSTMAN to the
latest version*. Have a nice day!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kataras/iris/issues/695#issuecomment-319338154>, or mute
the thread
