### ISSUE TITLE
Session: decoding cookie can return empty string, but it thinks that session is active

### ISSUE THREAD

**Issue by corebreaker** [kataras/iris#698]
I used securecookie from Gorilla like in example.
The problem is that the decode function can return error "securecookie: expired timestamp". Securecookie has a max age in its configuration.

Therefore the method `decodeCookieValue` of type `Session` returns empty string even if its argument is not empty. Then no new session ID is generated, and an empty session ID is sent to load from database. And also, no new cookie is sent to browser.

It's easy to resolve, i've already identified the problem. We have just to regenerate an ID when decoder return empty string (normally this correspond to an error returned by the underlying decoder).

I'm going to post a PR.

**Comment by kataras** [comment]
Fixed with #699 by @corebreaker. Thanks!
