### ISSUE TITLE
File based session storage

### ISSUE THREAD

**Issue by krokite** [kataras/iris#702]
Hi, I see "iris" is back up with v8.x . Congratulation to team and @hiveminded

Does Iris / get-ion supports file based session ? Memory based session and database sessions are not optimal requirement for scaling up.

If it's not already there, is it hard to implement them ? Please share some light so that , i can try implementing them.

Thanks

Reference: https://github.com/get-ion/issues-v1/issues/8

**Comment by corebreaker** [comment]
Hello @krokite.

No it's not hard to implement, you can do it easily if you.
As it's a good idea, i can also do it this saturday.

**Comment by kataras** [comment]
Hello friends, 

@krokite This is actually already implemented on [kataras/go-sessions](https://github.com/kataras/go-sessions), so, we can use that: https://github.com/kataras/go-sessions/tree/master/sessiondb/file . I'll push it here too and @corebreaker @hiveminded  can test and improve it if necessary

**Comment by kataras** [comment]
@krokite Thanks, actually it's **very easy to make a session database for our session manager**. We already had an implementation of this at kataras/go-sessions, I pushed it here with some minor fixes but I didn't test it on different operating systems, I let this to you, upgrade with `go get -u github.com/kataras/iris`.

@corebreaker  and @hiveminded Please test [this](https://github.com/kataras/iris/tree/master/sessions/sessiondb/file) and push any improvements if necessary.

**Comment by kataras** [comment]
Example: https://github.com/kataras/iris/blob/master/_examples/sessions/database/file/main.go (upgrade your local iris again, it should work now, please test it)

**Comment by corebreaker** [comment]
I tested with the example:
- Get: ok
- Set: ok
- Clear: ok in memory cache but not persisted in DB (file)
- Destroy: ok in memory, a new session ID is sent to browser, but the file is nor removed

**Comment by corebreaker** [comment]
Someone could confirm my tests ?

**Comment by kataras** [comment]
Hello @corebreaker , on Destroy it shouldn't send a new session id to the browser, is this an expected behavior?

**Comment by corebreaker** [comment]
Hello @kataras, it's ok for me.

Concerning the session ID, you are right the destroy doesn't send a new session ID, but with my test, i meant that when i refresh the browser (indeed send a new HTTP request), a new session id wasn't sent. But, maybe it was due that the file wasn't removed. I think your changes will make that the session will be invalidated by a destroy and so the browser refresh will order a new session ID.
