### ISSUE TITLE
IsAjax func bug at context/context.go

### ISSUE THREAD

**Issue by vinhjaxt** [kataras/iris#703]
`
// Read more at: http://www.w3schools.com/ajax/
func (ctx *context) IsAjax() bool {
	return ctx.GetHeader("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"

}
`

should be 
`
// Read more at: http://www.w3schools.com/ajax/
func (ctx *context) IsAjax() bool {
	return ctx.GetHeader("X-Requested-With") == "XMLHttpRequest"

}
`
Note that
HTTP_X_REQUESTED_WITH is in $_SERVER variable of PHP

**Comment by a7a2** [comment]
You're right.

**Comment by kataras** [comment]
@vinhjaxt  @a7a2 
You've right on that the "HTTP_" prefix should be removed, that's it. 

Bellow I'll try to explain you some things, generally speaking.

First, lowercase or uppercase doesn't matters on golang, the lower level use the canonical version to receive the headers. 

Secondly, there is no a 100% way of knowing that a request was made via Ajax. **You should never trust data coming from the client, they can be easily overcome by spoofing.** 

"X-" Headers can be modified by any client, so don't rely on `IsAjax` for really serious stuff, try to find another way of detecting the type(personally, I use the content type for these things), there are many blogs that describe these problems and provide different kind of solutions,  **always depending on the application you're building**, this is the reason why context's IsAjax is simple enough for general purpose use.
