### ISSUE TITLE
Gzip doesn't work

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#705]
I am trying to enable gzip for all the website, but getting the following error in the browser's
 console for my static files: `"Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH".`

If I disable Gzip everything works fine.

![bbbb](https://user-images.githubusercontent.com/5404341/28980828-f76f7a78-7957-11e7-83ff-87636a882359.PNG)

This is the code I've used inside Iris:

```go
app = iris.New()
app.Use(func(ctx context.Context) {
    ctx.Gzip(true)
})
```

I am using the latest version of Iris, Ubuntu 16.04 and Chrome.

 Any thoughts?

P.S. I opened by mistake this issue on iris-contrib first.

**Comment by kataras** [comment]
Hello @speedwheel , I'm from the office and I was able to serve using gzip. Did you forgot the 'ctx.Next()' call at the end of the middleware? It seems to be working here.

**Comment by speedwheel** [comment]
@kataras , yes I am using ```ctx.Nex()```go , did you clear your browser image cache while performing the test?

**Comment by kataras** [comment]
Could you please post us a code snippet so I could test it later?

**Comment by speedwheel** [comment]
I fixed it finally. I added ``app.Use(func(){...})`` after the static server. Thanks.

**Comment by kataras** [comment]
No problem, do not hesitate to ask anything else!

**Comment by corebreaker** [comment]
You can reopen this issue cause there is a problem with big files, i tested with jquery non-minified.
The code:
```Go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.New()
	app.UseGlobal(func(ctx context.Context) {
		ctx.Gzip(true)
		ctx.Next()
	})

	app.StaticWeb("/static", "public/common")

	app.Run(iris.Addr(":8080"))
}
```
Here the result:
![image](https://user-images.githubusercontent.com/9797898/28993462-7923d5e8-79bf-11e7-8935-7bea735207ac.png)


The real size of the file:
![image](https://user-images.githubusercontent.com/9797898/28993191-0ddb348a-79b9-11e7-96e9-9dfca75afe43.png)


And the response headers in browser:
![image](https://user-images.githubusercontent.com/9797898/28993445-1384c756-79bf-11e7-9e21-7781e3b49207.png)


We see that the Content-Length header has the uncompressed size (268039), it should have the compressed size (79470) or the response should be chunked.


Here the response header sent by Django with Gzip Encoding Middleware:
![image](https://user-images.githubusercontent.com/9797898/28993426-d69f8c86-79be-11e7-9fc5-ccc60e71307f.png)
