### ISSUE TITLE
sometimes 502

### ISSUE THREAD

**Issue by seven-tan** [kataras/iris#708]
[HTTP Server] http: panic serving 172.18.0.1:55636: runtime error: invalid memory address or nil pointer dereference
goroutine 9555 [running]:
net/http.(*conn).serve.func1(0xc4200fe280)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:1721 +0xd0
panic(0xb62e60, 0x1173dd0)
	/home/tan/.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
main.main.func3(0x119a5c0, 0xc420070380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/goapi/main.go:49 +0x1b4
github.com/kataras/iris/context.Next(0x119a5c0, 0xc420070380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:746 +0x109
github.com/kataras/iris/context.(*context).Next(0xc420070380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:917 +0x37
goapi/middle.RobotMiddleware(0x119a5c0, 0xc420070380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/goapi/middle/robot.go:56 +0xd7
github.com/kataras/iris/context.(*context).Do(0xc420070380, 0xc4203480b0, 0x2, 0x2)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:860 +0x74
github.com/kataras/iris/core/router.(*routerHandler).HandleRequest(0xc420332de0, 0x119a5c0, 0xc420070380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/handler.go:207 +0x4e4
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0x118d7a0, 0xc4202ae1c0, 0xc42000a900)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/router.go:70 +0x8f
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc420301940, 0x118d7a0, 0xc4202ae1c0, 0xc42000a900)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/router.go:147 +0x48
net/http.serverHandler.ServeHTTP(0xc420278370, 0x118d7a0, 0xc4202ae1c0, 0xc42000a900)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200fe280, 0x118dfe0, 0xc4201063c0)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:2668 +0x2ce

**Comment by hiveminded** [comment]
@seven-tan `context/context.go:917` is a comment line, `context/context.go:746` is an interface, the trace is invalid, so I assume that you're using an **older version of Iris** please upgrade with `go get -u github.com/kataras/iris` and open a new issue if that still the case.
