### ISSUE TITLE
I update the iris,then I get the same problem

### ISSUE THREAD

**Issue by seven-tan** [kataras/iris#709]
[HTTP Server] http: panic serving 172.18.0.1:58740: runtime error: invalid memory address or nil pointer dereference
goroutine 46 [running]:
net/http.(*conn).serve.func1(0xc42009a0a0)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:1721 +0xd0
panic(0xb8c6e0, 0x11b4da0)
	/home/tan/.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
main.main.func3(0x11dba40, 0xc4201ec380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/goapi/main.go:49 +0x1b4
github.com/kataras/iris/context.Next(0x11dba40, 0xc4201ec380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:757 +0x109
github.com/kataras/iris/context.(*context).Next(0xc4201ec380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:928 +0x37
goapi/middle.RobotMiddleware(0x11dba40, 0xc4201ec380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/goapi/middle/robot.go:56 +0xd7
github.com/kataras/iris/context.(*context).Do(0xc4201ec380, 0xc420359190, 0x2, 0x2)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/context/context.go:871 +0x74
github.com/kataras/iris/core/router.(*routerHandler).HandleRequest(0xc420369320, 0x11dba40, 0xc4201ec380)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/handler.go:207 +0x4e4
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0x11ce9e0, 0xc42022e0e0, 0xc4200f0000)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/router.go:70 +0x8f
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc42034f080, 0x11ce9e0, 0xc42022e0e0, 0xc4200f0000)
	/home/tan/.gvm/pkgsets/go1.8.3/global/src/github.com/kataras/iris/core/router/router.go:147 +0x48
net/http.serverHandler.ServeHTTP(0xc42020d810, 0x11ce9e0, 0xc42022e0e0, 0xc4200f0000)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42009a0a0, 0x11cf220, 0xc42038a1c0)
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/tan/.gvm/gos/go1.8.3/src/net/http/server.go:2668 +0x2ce

**Comment by krokite** [comment]
The error is at line no. 49 :- /home/tan/.gvm/pkgsets/go1.8.3/global/src/goapi/main.go:49

Your created value is `nil`

**Comment by kataras** [comment]
@seven-tan Are you kidding us? is this a bug report? Please post us your code, did you initialize the iris with `app := iris.New()` ? or you use it as a variable without initialize it?
