### ISSUE TITLE
How to set a custom Delims for templates?

### ISSUE THREAD

**Issue by raitucarp** [kataras/iris#71]
It seems iris should has a capability to set custom Delims for Templates. 

I try to set delims via GetTemplates().Templates.
```go
	iris.Templates("./templates/web/" + templateName + "/*.html")
	iris.GetTemplates().Templates.Delims("${", "}")
	
	iris.Get("/", func(ctx *iris.Context) {
		ctx.RenderFile("layout.html", map[string]string{"test": "test"})
	})
	errorListen := iris.Listen(":8080")
	log.Fatal(errorListen)
```
But it doesn't work. It ignores ```${.}``` but parse ```{{ . }}```

Since, Delims should be defined before ParseGlob. and iris.Templates() use ParseGlob. I try to switch line:
```go
iris.GetTemplates().Templates.Delims("${", "}")
iris.Templates("./templates/web/" + templateName + "/*.html")
```
gives me this:

```panic: runtime error: invalid memory address or nil pointer  #dereference```

note: Honestly, I like the design of https://github.com/unrolled/render which is give me more options to do sort of rendering job. If you can implement it, it would be great. 

Or for another design, Iris need to consider a render system like labstack/echo (https://labstack.com/echo/guide/templates/).

**Comment by kataras** [comment]
Done :) 
```go
iris.TemplateDelims("left delims here","right delims here")
iris.Templates("./templates/*.html")
```

**Comment by raitucarp** [comment]
OK, wait a minutes

**Comment by kataras** [comment]
Also note that you can always use your own code for templates, if you are using html/template standard package and you need more than Iris provides you can create your templates and just execute them with ```context.ExecuteTemplate(the *template.Template object here) ```

**Comment by raitucarp** [comment]
give me a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5badaa]

goroutine 1 [running]:
panic(0x9d10e0, 0xc082002080)
        C:/Go/src/runtime/panic.go:464 +0x3f4
html/template.(*Template).New(0x0, 0x0, 0x0, 0x0)
        C:/Go/src/html/template/template.go:276 +0x3a
github.com/kataras/iris.(*HTMLTemplates).parseGlob(0xc082060380, 0xc082179740, 0x1e, 0x18, 0x0, 0x0)
        F:/Work/Go/src/github.com/kataras/iris/templates.go:99 +0x75
github.com/kataras/iris.(*HTMLTemplates).Load(0xc082060380, 0xc082179740, 0x1e, 0x0, 0x0)
        F:/Work/Go/src/github.com/kataras/iris/templates.go:120 +0x11f
github.com/kataras/iris.(*Station).Templates(0xc08200ea20, 0xc082179740, 0x1e, 0x0, 0x0)
        F:/Work/Go/src/github.com/kataras/iris/station.go:279 +0x4c
github.com/kataras/iris.Templates(0xc082179740, 0x1e, 0x0, 0x0)
        F:/Work/Go/src/github.com/kataras/iris/iris_default.go:207 +0x4a
main.main()
```

**Comment by kataras** [comment]
Ok, wait please

**Comment by kataras** [comment]
Fixed, upgrade and try again please  :)

**Comment by raitucarp** [comment]
``` The server encountered an unexpected condition which prevented it from fulfilling the request.```

**Comment by kataras** [comment]
Are you sure?
This is working https://github.com/iris-contrib/examples/blob/master/static_files/main.go

```go
package main

import (
	"github.com/kataras/iris"
)

type page struct {
	Title string
}

func main() {
	//optionally
	iris.TemplateDelims("${", "}")
	//
	iris.Templates("./templates/*.html")

	iris.Static("/css", "./resources/css", 1)
	iris.Static("/js", "./resources/js", 1)

	iris.Get("/", func(c *iris.Context) {
		err := c.RenderFile("something.html", page{Title: "Home"})
		if err != nil {
			println(err.Error())
		}
	})

	println("Server is running at :8080")
	iris.Listen()
}

````

```html
<html>
	<head>
    	<title>${.Title}</title>
	 	<link rel="stylesheet" href="css/bootstrap.min.css">
	</head>
	<body>
		<h1>Home </h1>
		<button class="btn btn-primary"> Hi, Iris </button>

		<script src="js/jquery-2.1.1.js" > </script>
	</body>
</html>
```

**Comment by raitucarp** [comment]
Wait I will give you a report.

**Comment by raitucarp** [comment]
Ah I know, my templates path is a bit long, and it gives me a panic. 
```
iris.Templates("./templates/web/default/*.html")
```
Could you confirm it?

**Comment by raitucarp** [comment]
@kataras Ah, I know. That's my problem. In my templates there are undefined funcMap. I think ```iris.Templates()``` should use ```template.Must``` and gives panic if it errors when parsing. Actually, this is waste code
```
err := iris.Templates()
if err != nil {
   panic(err)
}
```

**Comment by raitucarp** [comment]
Ok. this is fixed now.
