### ISSUE TITLE
First middleware executed 2 times

### ISSUE THREAD

**Issue by Syam** [kataras/iris#712]
Hello,

I guess i found a bug in middlewares execution :

```
func TestHandler(ctx context.Context) {
	ctx.Application().Logger().Info("TestHandler ", ctx)
	ctx.Next()
}

test := app.Party("/foo")
	test.Get("/bar", security.TestHandler, func(ctx baseContext.Context){
		ctx.Text("test")
	})

```

Using Middleware on `test` Party or appHandlers on `Get()`, the first handler is always executed 2 times :
```
?[36m[INFO]?[0m 2017/08/09 01:05 TestHandler &{0xc0420ea150 0xc0422a0100 {[]} [] 0xc0420eeab0 [0x7af540 0x8ceb60 0x8ceee0] 0}
?[36m[INFO]?[0m 2017/08/09 01:05 TestHandler &{0xc0420ea150 0xc0422a0100 {[]} [] 0xc0420eeab0 [0x7af540 0x8ceb60 0x8ceee0] 1}

```

Expected to execute handler only one time.
I am using current Iris stable version / go1.8 amd64.

**Comment by hiveminded** [comment]
@Syam No it's not, test yourself, the code you show us is:

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.New()
	test := app.Party("/foo")
	test.Get("/bar", TestHandler, func(ctx context.Context) {
		ctx.Text("test")
	})

	app.Run(iris.Addr(":8080"))

}
func TestHandler(ctx context.Context) {
	ctx.Application().Logger().Info("TestHandler ", ctx)
	ctx.Next()
}
```

```sh
go run main.go
```
The logs are: 

![ek1](https://user-images.githubusercontent.com/29665371/29116199-c34182f6-7d02-11e7-85db-e09521359842.PNG)

Run it yourself,  I assume you made a mistake somewhere, please post your entire code-snippet .

**Comment by Syam** [comment]
I pointed out what cause this bug, and found it's related to official cors middleware :

```
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
	"github.com/iris-contrib/middleware/cors"
)

func main() {
	app := iris.New()

	crs := cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"},
	})

	app.Use(crs)

	test := app.Party("/foo", TestHandler)

	test.Get("/bar", func(ctx context.Context) {
		ctx.Text("test")
	})

	app.Run(iris.Addr(":8080"))

}

func TestHandler(ctx context.Context) {
	ctx.Application().Logger().Info("TestHandler ", ctx)
	ctx.Next()
}
```

CORS use from [official documentation](http://iris-go.com/v8/recipe#CORS)

**Comment by Syam** [comment]
Using alternate `app.WrapRouter()` method is working as expected :

```go
app.WrapRouter(cors.WrapNext(cors.Options{
	AllowedOrigins: []string{"*"},
	AllowedMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"},
}))
```

What's wrong with `cors.New()` + `app.Use()` ?

**Comment by hiveminded** [comment]
Therefore the title is not describing the issue

**Comment by kataras** [comment]
Nothing is wrong, as described in docs: use the wrapper for entire app, use the middleware for specific routes only.

**Comment by Syam** [comment]
> as described in docs: use the wrapper for entire app, use the middleware for specific routes only.

No, docs do not mention that it's not possible to use `cors.New()` with `app.Use()` explicitly.

Docs only mention this :
> ... this should work better and with all cors' features. Use that instead, if suits you.

The exemple show cors usage on a party, not a route. How to know there is a cors midware usage difference between app and party ? Docs is not explicit enough on this usage, leading to a weird behavior.


So, **yes**, something is wrong : **documentation**.

And as an open source user, i am contributing to this great project with my 2 cents.

Please, be well mannered, and do not ignore this remark.
