### ISSUE TITLE
Gzip doesn't work for a kind of files

### ISSUE THREAD

**Issue by ZaniaDeveloper** [kataras/iris#717]
There is a problem with big files or average sized files, for example i tested with jquery non-minified (~ 250 ko).

The code:
```Go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.New()

	// Put it before the static server, if i put it after, 
	// the response for static files won't be gzipped .
	// We can put it after the static server
	// but only with `app.UseGlobal()`, not `with app.Use()` .
	app.Use(func(ctx context.Context) {
		ctx.Gzip(true)
		ctx.Next()
	})

	// Static server
	app.StaticWeb("/static", "public/common")

	// Starts th serving task
	app.Run(iris.Addr(":8080"))
}
```
Here the result:
![image](https://user-images.githubusercontent.com/9797898/28993462-7923d5e8-79bf-11e7-8935-7bea735207ac.png)

The real size of the file:
![image](https://user-images.githubusercontent.com/9797898/28993191-0ddb348a-79b9-11e7-96e9-9dfca75afe43.png)

And the response headers in browser:
![image](https://user-images.githubusercontent.com/9797898/28993445-1384c756-79bf-11e7-9e21-7781e3b49207.png)

We see that the Content-Length header has the uncompressed size (268039), it should have the compressed size (79470) or the response should be chunked.

Here the response header sent by Django with Gzip Encoding Middleware:
![image](https://user-images.githubusercontent.com/9797898/28993426-d69f8c86-79be-11e7-9fc5-ccc60e71307f.png)

I have localized the problem, i'll push a PR soon.

**Comment by speedwheel** [comment]
I also experienced this bug and went around it by putting the static server before calling ``ctx.Gzip(true)``go.

**Comment by ZaniaDeveloper** [comment]
putting it before with app.Use() will cause that your static server won't have static files gziped, so it's not resolved by that way, you could see it with response headers (Content-Encoding header).

But, i know how to fix it up. I'll post a pull request tomorrow.

**Comment by kataras** [comment]
Gzip works but file servers such as `StaticWeb` are built from an individual API on the `core/router/fs.go` which accepts a `gzip` option but on `StaticWeb` is set to false:  `rb.StaticHandler(systemPath, false, false)` the only change we have to do is to check if gzip is enabled by this context and use gzip instead...

**Comment by kataras** [comment]
@ZaniaDeveloper  @speedwheel , could you please upgrade using `go get -u github.com/kataras/iris` and test these on your machines(clear the browser's cache first), tell me the results.

**Comment by ZaniaDeveloper** [comment]
The problem is not resolved, for `StaticHandler()` method too (i tested with example single-page-application). That's cause the size sent in Content-Length is still bad. The use case is:
I want activate or not the Gzip in `app.UseGlobal()` as a middleware or an option in `app.Run(runner, iris.WithGzip())`. So even if static files is configured after doesn't matter.

More, using the `app.StaticWeb()` method doesn't have the Gzip activation parameter, so the `ctx.Gzip()` in middleware will be used because the `app.StaticWeb()` method use the common API to register a route.

**Comment by kataras** [comment]
@ZaniaDeveloper You've right, sorry for being late to answer, yes the problem was not solved  when I wrote my comment, but now it should be fixed( and tested), please tell me the results.

About your proposal, `iris.WithGzip`, it's better to use a simple middleware, we have `iris.Gzip` which can be passed on `app.Use(iris.Gzip)`

**Comment by ZaniaDeveloper** [comment]
Yes, that's good as a middleware as `app.Use(iris.Gzip)` but also as `app.UseGlobal(iris.Gzip)`.

**Comment by kataras** [comment]
Exactly, do you have time to test if the fix is actually the solution you and @speedwheel were looking for ?

**Comment by ZaniaDeveloper** [comment]
Yes, it's good now. Good job !
I'm going to close this issue.

**Comment by speedwheel** [comment]
I also confirm that now it's working, thanks a lot!

**Comment by kataras** [comment]
Thank you both, nice job!
