### ISSUE TITLE
go-bindata api changes

### ISSUE THREAD

**Issue by speedwheel** [kataras/iris#718]
The go-bindata package has been updated and now it uses only one function to access the assets when you run ``go-bindata ./templates/...``:

```go
func Asset(name string) ([]byte, error) {
	if f, ok := _bindata[name]; ok {
		return f()
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}
```
Iris it's using also the ``AssetNames`` function which was generated in the past by the old go-bindata API. 

These are the two functions that Iris it's using now, one of them has been changed and the other is not present anymore in the file generated file by go-bindata:

```go
// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}
```

Can we change the embedding functionality in Iris so we can use the generated file by go-bindata by default?

**Comment by kataras** [comment]
Are you sure? [go-bindata](https://github.com/jteeuwen/go-bindata)'s last change was 2 years ago.
` Latest commit on Oct 23, 2015`

I upgraded again but`Aseet` and `AssetNames` are there and working by-default with Iris, as expected. 

![xmm-wrong-issue](https://user-images.githubusercontent.com/22900943/29236600-65016868-7f15-11e7-9909-0049b454c485.PNG)

Who told you that the API changed recently?

**Comment by speedwheel** [comment]
My bad, I had on that server an older version of go-bindata installed from ubuntu package.

How can I use bindata with my default template: 
```go
app.RegisterView(tmpl.Layout("layouts/default.html")) 
```

Because now it's pulling only the View.

**Comment by kataras** [comment]
No problem for me but please be careful the next time or to other open-source projects when posting issues.

About using go-bindata with templates, please check the examples, layouts are just template files like others, they work the same: 

```go
// $ go-bindata ./templates/...
// $ go build
app.RegisterView(iris.HTML("./templates", ".html").Binary(Asset, AssetNames).Layout("layouts/default.html"))
```
https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app

**Comment by kataras** [comment]
No problem for me but please be careful the next time or to other open-source projects when posting issues.

About using go-bindata with templates, please check the examples, layouts are just template files like others, they work the same: 

```go
// $ go-bindata ./templates/...
// $ go build
tmpl := iris.HTML("./templates", ".html").Binary(Asset, AssetNames).Layout("layouts/default.html")
app.RegisterView(tmpl )
```
https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app

**Comment by speedwheel** [comment]
That works, thanks.

**Comment by kataras** [comment]
Yes, you see how easy is with Iris? You just add the `Binary(Asset, AssetNames)` and its ready to serve the embedded template files, everything else is kept as before, your API remains the same
