### ISSUE TITLE
StaticWeb map static path can't include "index.html" ？

### ISSUE THREAD

**Issue by yunhor** [kataras/iris#719]
Documentation for the _iris_ project can be found at
<https://github.com/kataras/iris#-learn>.
iris version 8.2.4
When I use StaticWeb method map a static path, and request "static/index.html" ,it will "Not Found".
But when I change index.html to go.html ,it work .
I am sure the old iris hasn't this error .
![2017-08-13 00-59-50](https://user-images.githubusercontent.com/1693437/29242649-34dd27cc-7fc3-11e7-9e75-e3365269a14c.png)

**Comment by kataras** [comment]
The `StaticWeb` looks for `index.html` not for `go.html`... I tested it yesterday for the previous post issue.
First time I hear about a homepage like `go.html`, so it is not possible that StaticWeb would find that and not index.html...

Could you please provide us a code-snippet that produces this type of error?

> Please follow the project to learn about its new features, I am pushing a history entry on every single change, this way you will not have to post an issue every time.

**Comment by yunhor** [comment]
![2017-08-13 01-28-41](https://user-images.githubusercontent.com/1693437/29242849-cd698032-7fc6-11e7-9f5a-00d4da7a21fa.png)

I map ./go to /go ,when ./go/go.htm change name to "index.html" ,It can't work on v8.2.4

**Comment by yunhor** [comment]
Thank you @kataras  ,I will try SPA method.

**Comment by kataras** [comment]
I found the origin of the issue and I've fixed that but I have no time to test it much more right now, I'm in the office. I want to be 100% sure that we will not face an issue like that on the near future and I'll push the fix to the repository when I go back to my house. Wait for that fix, which solves the issue of StaticWeb you described on this thread.

**Comment by kataras** [comment]
Done, upgrade with `go get -u github.com/kataras/iris` and you're ready to go :) 

@yunhor Thank you very much for your report, it lead me to fix an important issue I had in my mind for a long time.

Please star or watch the repository to receive real-time updates.

**Comment by jolee11** [comment]
I just run iris-master/_examples/file-server/basic/main.go

All the following gives "Not Found"
http://localhost:8080/static
http://localhost:8080/static/
http://localhost:8080/static/index.html


If I rename index.html to i.html, then 
http://localhost:8080/static/i.html gives "Hello index"

![screen shot 2018-11-26 at 10 55 37 am](https://user-images.githubusercontent.com/5764520/48990618-14a53980-f16a-11e8-9343-87163ea30e3b.png)

**Comment by kataras** [comment]
@jolee11 this happens because /static/ redirects to /static and index.html is not part of the /static but /static/index.html, to fix that you could pass `iris.WithoutPathCorrection` option to `iris.Run(iris.Addr(...), iris.WithoutPathCorrection)` however I will refactor the code a bit in order to fix this, stay tuned.

**Comment by jolee11** [comment]
Thank you very much!
