### ISSUE TITLE
Be able to append a Data object on the Context

### ISSUE THREAD

**Issue by dvwallin** [kataras/iris#72]
Maybe im doing it wrong but I have my big struct called HTTPData which contains like 50 different fields. Most of them are never set at the same time - only a few are efualt values. For example I have a function to always set the version of the system or the name of the system but for example the Boats -field (a slice of boat struct) is only set when going to the boat-index-page.

Instead of starting every route handler function with something like 
```
Data := getDefaultDafa()
Data.Boats := getAllBoats()
```
The example below would be nicer.

First you declare the data object struct so you have your structure
```
type MyData struct {
    Systemname string
    Version int
    Boats []Boats
    Ports []Ports
}
```
then in main do something like
```
func myInit(c *iris.Context) {
    c.DataStruct = MyData{
        Systemname: "TEST",
        Version: 1,
    }
}

func main() {
    iris.UseFunc(myInit())
```
and then in a handler you could do
```
c.DataStruct.Boats = mylib.GetAllBoats()
```

**Comment by kataras** [comment]
You can do that with ``` c.Set("DataStructure") = MyData {} ``` and ```c.Get("DataStructure") ``` , it is not the best way, but temporary you can use that.

Also if we make something like a binder inside the Context, then it will be an interface{} right?for example ``` type Context {.... DataStruct interface{}} ``` you lose the type checking again, as before.. 

We need to discuss it more, please anyone who has an idea don't hesitate to post!

**Comment by qskousen** [comment]
I think probably the ideal way to handle something like this would be to have a custom middleware that adds the MyData struct (from @kataras example) to the context, then you would be able to set routes like normal but the MyData would be available to all handlers from the context. The middleware can set the UserAgent each time. Potential performance issue would be creating the struct with every request, would be better, if the data was the same for every request (again from the example, if it didn't have the UserAgent field) if you added a pointer to a global to the context in the middleware instead, then you would only have to create the struct once at program start. Hopefully that makes sense.

(As an aside, thanks for making this framework, fantastic work... I wish I knew about it a few weeks ago then I wouldn't have had to do my own work of implementing gorillla websockets into echov2 with fasthttp!)

**Comment by qskousen** [comment]
I just reread this and realized I said pretty much exactly what @dvwallin said already... However, I am nto sure why that wouldn't work or is not a good idea. I need to do something like this in some of my projects so I am interested in the best way to handle it. @kataras if this is not a good way to handle it can you explain why it is a bad idea? I am confused about your example, how would you be able to handle routes in a normal way, and what makes your example more efficient than what dvwallin suggested?

**Comment by kataras** [comment]
@qskousen  Thanks for your nice words, it is not too late for you to change framework :) .
First of all, maybe you missunderstood but I never told that david's question/feature is a bad idea, contrariwise I let this 'issue' open to for discussion.

Your suggestion to do a middleware and set a custom data on it, it's already there using `ctx.Set & ctx.Get` , can you suggest how we could keep the 'auto-completion on' for the `MyData struct` with middlewares? The only way I know is to inject it into the handler function ex. `func(ctx *iris.Context, mydata MyData)` but this would have issue performance and I am not doing that in this framework.

Thanks for your interest, I'm waiting more from you!!

**Comment by qskousen** [comment]
I am not sure what you mean by "keep auto-completion on", can you clarify?

**Comment by kataras** [comment]
I mean you suggest to have a field with typeof ` interface{} ` inside the Context(?)

**Comment by dvwallin** [comment]
I think that Go (since it does not support generics) really hinders my own feature suggestion here

**Comment by kataras** [comment]
Yeah.. that I said, if go supported generics it will be more exciting to my opinion, but you can extend the example I wrote I think, maybe at the future I will design a bigger example to look. David I missed you, all good ?

**Comment by qskousen** [comment]
@kataris, I meant to attach the structure to the context with
c.Set({struct}). Am I misunderstanding how that works?

**Comment by kataras** [comment]
You can do that already with`c.Set(key string ,value interface{})` , but it's interface{} on the `c.Get("mykey")` , you have to cast it to MyData, and I don't like this way but it's alright if you need to do it

**Comment by qskousen** [comment]
I see now what you are saying. I guess you will just have to keep strict control of what data goes in so your cast can be successful every time. I don't think there is a better way to do that. Possibly you could marshal it in then marshal it out into the struct, but that would involve a lot of marshaling which would certainly impact performance.

**Comment by kataras** [comment]
That's exactly I meant to my previous comments, no reason to un/marshal the only way,at least for now, is the c.Set/C.Get , and the custom handler example I wrote before ( which I'm using for real). You can do whatever with Iris, it doesn't tell you what to do and what to not, you will figure out solutions to this kind of issues based on your experience and the sittuation.
