### ISSUE TITLE
MyContext - Is the documentation wrong or what is?

### ISSUE THREAD

**Issue by ear** [kataras/iris#720]
The current version of [_examples/routing/custom-context/method-overriding/](https://github.com/kataras/iris/blob/6a1742bda51f712ac6273d34b9200fc242aa7cd3/_examples/routing/custom-context/method-overriding/main.go) says:

```go
// should always print "($PATH) Handler is executing from 'MyContext'"
```

But when I run it locally I instead get:

```
Now listening on: http://localhost:5555
Application started. Press CMD+C to shut down.
[INFO] 2017/08/12 21:51 (/) Handler is executing from: 'context'
```

Furthermore this does not work… although I'm not sure it should! (It would be nice if it did, though 🌟)

```go
if c, ok := ctx.(*MyContext); ok {
	fmt.Printf("%+v\n", c)
} else {
	fmt.Printf("type assertion to MyContext failed\n")
}
```

As a general point: am I understanding correctly that I can create my own context type that embeds `context.Context` and carries along other data in it? (E.g. a database connection, or whatever.)

Thank you very much for taking the time to read this through. It is appreciated!

**Comment by kataras** [comment]
It's working but the example is missing from the `Do()` function,( `Next` and `Do` are required for method overloading) I'll update the example on a second
