### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by yarossia** [kataras/iris#729]
What about Facebook's GraphQL support?

**Comment by kataras** [comment]
Hello dear @yarossia ,

Is this really necessary to be supported inside the core of a web framework like Iris?

I think there are smore pecialized developers on GraphQL field than me who already ported GraphQL for Go, search engines will help you to locate and learn about them.

Thank you!

**Comment by kataras** [comment]
Hello dear @yarossia ,

Is this really necessary to be supported inside the core of a web framework like Iris?

I think there are more specialized developers on GraphQL field than me who already ported GraphQL for Go, search engines will help you to locate and learn about them.

Thank you!

**Comment by yarossia** [comment]
Hello @kataras! But as we can see you positioning your framework as the fastest from all other and depending on test  graphics we can see it and we knew that one query request is more faster then for example 3 REST requests to server. As for me if you wrote the fastest framework, for one of the fastest web-languages, it can be awesome if you support query language as GraphQL.

**Comment by kataras** [comment]
What do you mean by adding support for GraphQL? To write another package for graphQL and how this can be related with this web framework? I can't understand... is like telling me to write a package for gui or mysql, they are not related and they should not be included into a web framework's core. Currently I have no time to create and maintain other packages than Iris. I am full into this and I'm not leaving, it gave me a job and a lot of experience

**Comment by krypton97** [comment]
@yarossia 
https://github.com/playlyfe/go-graphql  is the fastest go implementation and they even use it in production, you should use that. Check my profile also, I have a middleware that connects the graphql schema to an endpoint. Following the code you can port it for iris ;). I'll be using them both in production for a powerfull backend

**Comment by kataras** [comment]
I have just uploaded an example, you can take a look at: https://github.com/kataras/iris/tree/master/_examples/graphql/schema-first.
