### ISSUE TITLE
Improve Render

### ISSUE THREAD

**Issue by raitucarp** [kataras/iris#73]
Rendering HTML or other format should be more easier. 

Take a look https://github.com/unrolled/render/. It gives me more options. Especially for HTML. It has a layout. For designer it is important to separate file for specific page (for example: home.html, page.html, single.html). So, it can be used as a theme for a website under specific folder. 

Currently Iris has ```ctx.RenderFile("home.html")``` for example, but if I have 10, 20 page or more with the same structured basic layout. It will difficult to maintains. 

Since, unrolled/render doesn't support fasthttp yet, they barely use ```http.ResponseWriter``` which is standard net/http. I want a feature for Iris that capable of doing the same approach.

If Iris has it as a standard method not a third library. It would be great. At the same time, keep another alternatives such as ctx.HTML(), ctx.RenderFile(), ctx.ExecuteTemplate(), don't remove it. So developer can choose what is the best for them.

**Comment by dvwallin** [comment]
I am not sure it is a great idea to have a lot of options in a framework. It is quickly getting bloated and nobody knows which is the best one to use. The framework itself should probably stick to one way of doing it and then have third-party middleware for options (such as pongo2 for example). I know pongo2 is the template engine and you're taking about rendering-methods but pongo2 supplies that when used in iris.

The failure in bigger frameworks such as Revel or Beego is that they have grown too big and that makes them more complex. Now even with great Docs it is still confusing what you should use when.

Im not arguing against your suggested way of rendering files but I am against having multiple ways of doing one thing.

**Comment by raitucarp** [comment]
@dvwallin OK. I see.. But currently iris have a lot of options to define handlers and middleware too.

What is your suggestion for current features? ctx.HTML(), ctx.Render(), ctx.RenderFile, ctx.ExecuteTemplate()?

I agree, maybe my request feature shouldn't put in the main framework, and separate it as an independent package.

**Comment by kataras** [comment]
Hey,

-  ```go ctx.HTML("<b> Hi </b>")  ```just renders html from a string
- ```go ctx.Render``` it has been removed on version 1.2.0+
- ```go ctx.RenderFile("file.html",pageContext{}) ``` renders a file based on the files exists on the iris.Templates("filepath/*.html") 
- ```go ctx.ExecuteTemplate(mytemplate *template.Template) ``` it is used when you have already your own html/template and you want just to render them

I think that's enough. BUT your suggestion is not too bad, I can implement a middleware (as pongo2) to use unrolled/render ,if you want you can give me some suggestions and some tips which I have to worry about when using this package because I never used this myself, Thanks!!

**Comment by raitucarp** [comment]
Thanks @kataras unrolled/render actually extends the capability of html/template in a structured way and straightforward.

**Comment by kataras** [comment]
@raitucarp yes but unrolled/render it uses explicit the ``` http.ResponseWriter ``` , I have to fork it and convert for Iris... I'm starting now.

**Comment by kataras** [comment]
Done: https://github.com/iris-contrib/render

**Comment by kataras** [comment]
for v2.0.0-beta1 iris-contrib/render is inside the **Context** no need to use the iris-contrib/render anymore, read CHANGELOG.md also.

**Comment by raitucarp** [comment]
do you mean no need to import iris-contrib/render? and use context instead

**Comment by kataras** [comment]
**Exactly**
