### ISSUE TITLE
undefined iris.Context

### ISSUE THREAD

**Issue by lkmadushan** [kataras/iris#730]
I can't run application. it says undefined iris.Context.

```
app.Handle("GET", "/", func(ctx iris.Context) {
        ctx.HTML("<b>Welcome!</b>")
})
```

**Comment by lkmadushan** [comment]
fixed after updating go to V1.9

**Comment by kataras** [comment]
Yes, if you use go 1.8 you have to import and use the 'github.com/kataras/iris/context', readme.md has an example of this as well.

**Comment by lkmadushan** [comment]
@kataras Thanks for your reply. I am new to Golang and started learning it from this month.

There are lot of go frameworks but this is the best one that i found after researching a lot of frameworks 👍 Great work

**Comment by kataras** [comment]
Thank you very much, if you need anything about go or iris you can also join to the community live chat by clicking [here](https://kataras.rocket.chat/channel/iris) !
