### ISSUE TITLE
Global Middleware bugs

### ISSUE THREAD

**Issue by raitucarp** [kataras/iris#74]
If I have two middleware, it seems iris.Get will be broke.
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/logger"
)

type page struct {
	Title string
}

func main() {
	iris.Use(logger.Default())

	iris.UseFunc(func(ctx *iris.Context) {
		println("what?")
		ctx.Next()
	})

	iris.UseFunc(func(ctx *iris.Context) {
		println("hmm?")
		ctx.Next()
	})

	// define all routes here
	iris.Get("/", func(ctx *iris.Context) {
		ctx.HTML("index")
	})
	iris.Get("/login", func(ctx *iris.Context) {
		ctx.HTML("login")
	})
	iris.Get("/hello", func(c *iris.Context) {
		c.HTML("<b> Hello </b>")
	})

	println("Server is running at :8080")
	iris.Listen()
}
```

/, /login, /hello all render Hello message. Can you confirm this?

**Comment by kataras** [comment]
Please, wait I will test it now

**Comment by kataras** [comment]
It is so strange..lol I will fix it fast.. it maybe a bug from my last changes

**Comment by kataras** [comment]
It's a bug when global middleware registed, I will fix it

**Comment by kataras** [comment]
Temporary fix:  if your routes are equal to the global middlewares just declare an extra empty middleware. I will convert the whole party.go i'll try to make it simplier in order to see whats wrong..

**Comment by raitucarp** [comment]
Is this fixed now?

**Comment by kataras** [comment]
Yes, this particular bug is fixed
