### ISSUE TITLE
Add go-i18n core support

### ISSUE THREAD

**Issue by syklevin** [kataras/iris#743]
It is more feature rich and widely used.
other than making our own custom middleware, it would be better if could be provided as an official supported service.
thanks.

**Comment by hiveminded** [comment]
We've never used go-i18n before and we're quite happy with the current i18n implementation so far, however you can prepare and push a PR for that and explain the benefits over the current implementation to us.

**Comment by syklevin** [comment]
All right, I've made a custom middleware of go-i18n.
Could check it out [here](github.com/syklevin/iris-go-i18n) if interested.

**Comment by kataras** [comment]
@syklevin Thank you, we appreciate it, but I've noticed that your example is not working as purposed, fix it when you have time!

**Comment by syklevin** [comment]
Thanks for point it out, it is due to the dependency library pointed to master branch which is unstable. I have pushed an update for it.

**Comment by kataras** [comment]
@syklevin Nice job, push a PR to the https://github.com/iris-contrib/middleware or/and to this repository and add your middleware to the list
