### ISSUE TITLE
Guidelines for Iris structure?

### ISSUE THREAD

**Issue by maplerichie** [kataras/iris#748]
Do Iris have standard structure?
Sorry that I'm still new to GoLang, but i wish to build my mobile app backend API with Iris. The problem i face is I dunno where to start from because I have already used to the framework with generator like Angular2, Ionic, Android. These frameworks come with tools that can generate folder structure and main file needed. I have go through other Go framework like Revel, Beego also but most of the review said Iris is the fastest one and this make me decide to use Iris to build my API.

As from Beego docs, it do have MVC structure like below:
├── conf
│   └── app.conf
├── controllers
│   ├── admin
│   └── default.go
├── main.go
├── models
│   └── models.go
├── static
│   ├── css
│   ├── ico
│   ├── img
│   └── js
└── views
    ├── admin
    └── index.tpl
**We can see the M (models), V (views), C (controllers) folders. main.go is the entry point.

And below is from Revel
![image](https://user-images.githubusercontent.com/10757316/30373251-3dbd6a60-98b3-11e7-93ea-75275bb40f24.png)

Will Iris come out a CLI tools? Or can guide me on this with an example?
I wish to build a AIM stack!
Angular2 (UI) + Iris (API) + MongoDB

**Comment by JermineHu** [comment]
**Iris needs a perfect code generator should be a cli tool or scaffolding, making it easy to create a project, controller, view, model...  Just as Core ,DotNet, Yii (Gii), React Native... Iris also can be used like this command line "iris create -p myapp", "iris create -m UserMoudle". If Iris can generate the corresponding moudle according to the database or PDM model, it will greatly improve the development efficiency.**

**Comment by kataras** [comment]
@maplerichie What stops you from using your favorite structure? Iris is a low level web framework, it has got MVC support but it doesn't limit your folder structure, this is your choice. Now if you ask me I can tell you that the images you posted looks good.  **It always depends on your needs, I can't tell you how to design your own application, I give you the tools, it's your choice**

**Comment by kataras** [comment]
@JermineHu Iris is fully feature web framework but it's easy to learn and start, unlike others. However I'm open to approve any PRs that completes your CLI idea!

**Comment by maplerichie** [comment]
@kataras  I'm understand that Iris are free to build as MVC or whatever structure. But with a guideline, like the issue i stated (folder structure), it can make people adopt this great framework faster. From my point of view, it always being easier when there is a "standard" guideline to follow instead of build from scratch.
Is it @JermineHu  have the same though as me? 
I'm already start to building web backend with Iris, but i wish Iris can go further step and spread to more people trying to adopt Golang
#Salute

**Comment by kataras** [comment]
@maplerichie I've uploaded some "guidelines" about folder structuring and package design after your question, you can find those examples at: https://github.com/kataras/iris/tree/master/_examples#structuring

Iris is unopinionated, you can adapt your experience right away, you are not starting from scratch, just make the folder structure you want (optionally; upload it to a github repository and share with the rest of us) and use that at your web applications as you like, don't compare our decisions of free willing with other web framework authors' decisions to keep you in a certain box, opinionated.

**Comment by kataras** [comment]
I appreciate your feedback, although I don't need an article to tell me the right thing :P Keep strong!

I know performance is not everything, it's one good point but Iris is not all about performance only, anymore, now it's a complete web framework, inneed the most featured framework for the http subprotocol written in Go so far.

**Comment by kataras** [comment]
I appreciate your feedback @mainnika, I totally agree with you but this is not the place neither the correct issue, you could talk with us at the [chat](https://chat.iris-go.com) as well, we don't need an article to tell us the right thing, right? Keep strong!

I know performance is not everything, it's one good point but Iris is not all about performance only, anymore, now it's a complete web framework, inneed the most featured framework for the http subprotocol written in Go so far.

**Comment by mainnika** [comment]
@maplerichie I think the text above is for you.

**Comment by ElhamAfshar** [comment]
hi

**Comment by kataras** [comment]
> hi
> I need different Layouts in my project
> can I use two different layout in web project by iris framework?
> 
> `app.RegisterView(iris.HTML("web/view", ".html").Layout("layout.html"))`

**Rel to:** https://github.com/kataras/iris/issues/1368
