### ISSUE TITLE
https://iris-go.com/ : http://localhost:8080/ vs. http://context:8080/

### ISSUE THREAD

**Issue by liotier** [kataras/iris#750]
In the Hello World example at https://iris-go.com/ the "// Resource:" comments for routes sometimes mention http://localhost:8080/ and sometimes http://context:8080/

In the example at https://iris-go.com/v8/start it is always "// Resource: http://localhost:8080" and I think the Hello World example should follow the same consistency.

**Comment by hiveminded** [comment]
@lioter there is not sometimes, it's only one part, the overview example at https://iris-go.com on the third route, it's a typo and will be fixed thank you very much
