### ISSUE TITLE
MVC: Support for RegEx?

### ISSUE THREAD

**Issue by NextGringo** [kataras/iris#752]
Hi is there a potential to support RegEx for URLParams?
Or what is the best approach to use RegEx on the Params?

**Comment by krokite** [comment]
Iris already support URL Parameters and you can get them by `ctx.Params().Get('name')` against URL like `"user/{name}"`

Is this your actual requirement ?

**Comment by NextGringo** [comment]
No I would like to use my own regex like only small chars and some special chars like "!+.," or special format of a string that is a param. Like: https://github.com/kataras/iris/blob/master/_examples/routing/dynamic-path/main.go#L157

**Comment by NextGringo** [comment]
But that for the MVC if possible.

**Comment by krokite** [comment]
Yes, you can use in MVC too those examples. What is issue ?

**Comment by NextGringo** [comment]
and how can i do it? in the way i can do it with the normal `app.get(...)` ? It's a bit bad documented.

**Comment by kataras** [comment]
@NextGringo  @krokite the `string` macro type has a `regexp` built'n function, like `int` has the `min` and `max`. You can register your own macro functions for any supported type: https://github.com/kataras/iris/blob/master/core/router/macro.go#L50.  You have full access to "macros" from the `app.Macros()` so if you want to register a custom macro func you can do something like this:

The below example can be found at: https://github.com/kataras/iris/blob/master/_examples/routing/dynamic-path/main.go#L114
```go
app := iris.New()
// checks if the param value's int representation is
// bigger or equal than 'min'
app.Macros().Int.RegisterFunc("min", func(min int) func(string) bool {
		return func(paramValue string) bool {
			n, err := strconv.Atoi(paramValue)
			if err != nil {
				return false
			}
			return n >= min
		}
	})

// usage:
app.Get("/user/{id:int min(10)}", myHandler)
```

> app.get(...) ? It's a bit bad documented.

No it's not bad documented, we have full examples for any use case you **just didn't take the time to look at the examples**.

## We have regexp example already into our _examples

**regexp example:** https://github.com/kataras/iris/blob/master/_examples/routing/dynamic-path/main.go#L157

As we already mention, `string` macro type has the `regexp` built'n function, can be used like: 

`app.Get("/path/{paramName:string regexp(^[0-9]+$)}", myHandler)`

Thank you.

**Comment by NextGringo** [comment]
@kataras thanks for clarify...

but thats will not help me with your MVC that I try to use... don't know why you ignore thous informations... i would like to USE it with THE MVC... :(

**Comment by kataras** [comment]
MVC lookup the paths with the function's name, Go does not support any comment-like runtime information like C# or Java does.

However there are many ways to add regexp on your MVC app's paths using a middleware or add a common logic to the `BeginRequest` or just use a regexp path which will be handled by a controller `app.Controller("/user/{username:string regexp(yourREGEX_HERE)}", new (UserController))`, you have all the information you want but I will help you more, I am not ignoring your question.


There is a way to add route middlewares to your Controller via binding: 
```go
package main

import (
	"regexp"

	"github.com/kataras/iris"
)

func main() {
	app := iris.New()
        // allow only numbers, this will always throw 404 because the paths are static
        // but you got the point
	app.Controller("/", new(ExampleController), regexpMiddleware("^[0-9]+$"))

	// http://localhost:8080
	// http://localhost:8080/ping
	// http://localhost:8080/hello
	app.Run(iris.Addr(":8080"))
}

func regexpMiddleware(expr string) iris.Handler {
	r, err := regexp.Compile(expr)
	if err != nil {
		panic(err)
	}

	return func(ctx iris.Context) {
		path := ctx.Path()
		if !r.MatchString(path) {
			ctx.StatusCode(iris.StatusNotFound)
			return
		}

		ctx.Next()
	}
}

// ExampleController serves the "/", "/ping" and "/hello".
type ExampleController struct {
	// if you build with go1.8 you have to use the mvc package, `mvc.Controller` instead.
	iris.Controller
}

// Get serves
// Method:   GET
// Resource: http://localhost:8080
func (c *ExampleController) Get() {
	c.ContentType = "text/html"
	c.Text = "<h1>Welcome!</h1>"
}

// GetPing serves
// Method:   GET
// Resource: http://localhost:8080/ping
func (c *ExampleController) GetPing() {
	c.Text = "pong"
}

// GetHello serves
// Method:   GET
// Resource: http://localhost:8080/hello
func (c *ExampleController) GetHello() {
	c.Ctx.JSON(iris.Map{"message": "Hello Iris!"})
}

```
