### ISSUE TITLE
QUIC Support for TLS Server?

### ISSUE THREAD

**Issue by NextGringo** [kataras/iris#753]
Hello again,

do you plan to support QUIC for your framework? Like @go-siris does?
It would help us to switch back to Iris.

Regards

**Comment by krokite** [comment]
Isn't QUIC still experimental ?

**Comment by NextGringo** [comment]
Of course, but in many products it is already in productive use, as in some of our products.

**Comment by JermineHu** [comment]
**Iris a great server and expects it to support QUIC！Find some reference code from GitHub！Hope it  useful！**

https://github.com/lucas-clemente/quic-go

https://github.com/devsisters/goquic

https://github.com/mholt/caddy

**Comment by NextGringo** [comment]
https://github.com/devsisters/goquic is death... and not support IPv6...

**Comment by hiveminded** [comment]
Feel free to push a PR if you really need it we will approve it as an optional feature!
