### ISSUE TITLE
MVC: index not found...

### ISSUE THREAD

**Issue by NextGringo** [kataras/iris#755]
I have build my MVC like https://github.com/iris-contrib/examples/blob/86b40f592f02aa8f7cb78ee4914f33cde1b59ab2/mvc/hello-world/main.go

but the `/` url don't resolve to the IndexController the uri is not found.

**Comment by NextGringo** [comment]
@kataras @hiveminded any idear?

**Comment by kataras** [comment]
Hello,

What do you mean? It's working here, please upgrade your Iris and don't post issues every two minutes without `go run main.go` first.

**Comment by NextGringo** [comment]
@kataras I use 8.4.2 and can't in my code not call the HomeController -_- so it's not invalide...

What i do is this:
```GO
	app.Controller("/", new(HomeController), contextOwner.databaseManager)
	app.Controller("/account", new(AccountController), contextOwner.sessionsManager, contextOwner.databaseManager)
	app.Controller("/login", new(LoginController), contextOwner.sessionsManager, contextOwner.databaseManager)
	app.Controller("/api", new(ApiController), contextOwner.databaseManager)
	app.Controller("/_pay", new(PaymentController), contextOwner.databaseManager)
```
all other working execpt the HomeController.

Any why are you so unfriendly?
