### ISSUE TITLE
undefined: blackfriday with govendor 

### ISSUE THREAD

**Issue by gale93** [kataras/iris#756]
iris: 8.4.2 
go: 1.9

Using iris with [govendor package](https://github.com/kardianos/govendor), I can't get it run locally ( via `go run .. ` ) and remotly ( using heroku )

The error is the same and it is:

`vendor/github.com/kataras/iris/context/context.go:2198:9: undefined: blackfriday.Run`

**Steps to reproduce:**
-> Create new folder
-> Add in it main.go ( hello world tutorial )
-> `govendor init`
-> `govendor fetch github.com/kataras/iris`
-> `go run main.go`

I can't say much more, I don't know if i just missing something or if it's not a iris problem and i should open an issue on govendor.

**Comment by gale93** [comment]
Oh. I see it now, iris use a self-modified version of blackfriday. All I have to do is find a way to specify to govendor to use that version instead of the original one.

**Comment by gale93** [comment]
yep! Solved.
For unfortunate guys that'll have this problem, to correctly fetch the package modified dependecies just add the recursive tag -tree, ex:
`govendor fetch -tree github.com/kataras/iris`

**Comment by kataras** [comment]
Thanks @gale93 I've never used govendor before, this is a good tip for newcomers as well!

**Comment by prabowomurti** [comment]
I am still facing the issue, trying to edit the line to : 
```
buf := blackfriday.MarkdownCommon(markdownB)
```
