### ISSUE TITLE
undefined: helperFuncs

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#76]
github.com/kataras/iris/render
..\github.com\kataras\iris\render\render.go:196: undefined: helperFuncs
..\github.com\kataras\iris\render\render.go:241: undefined: helperFuncs

**Comment by koichiroo** [comment]
I had have same error.
In helpers.go, there is build tag such as `// +build go1.6`.

So, I think you build by version under go1.6 .
delete this line or build by above go1.6, you will not watch errors.

**Comment by dxvgef** [comment]
@koichiroo Thank you~

**Comment by koichiroo** [comment]
@dxvgef You're welcome!

**Comment by kataras** [comment]
Nice !
