### ISSUE TITLE
crash when use 'URLParamInt'

### ISSUE THREAD

**Issue by tfzxyinhao** [kataras/iris#760]
hi,
I find that crash when hasn't passed any params on url and try to use `URLParamInt` get url params
iris 8.4.2
```
type Admin struct {
	iris.Controller
}

func (u *Admin) GetProduct() {
	page, err := u.Ctx.URLParamInt("page") // crash here,read invalid memery
	if err != nil {
		page = 1
	}
	size, err := u.Ctx.URLParamInt("size")
	if err != nil {
		size = service.DefaultSize
	}

	list, total, err := service.GetProduct(bson.M{}, page, size)
	if err != nil {
		u.Ctx.JSON(NewErrorResponse(err.Error()))
		return
	}
	u.Ctx.JSON(service.RespData{
		"list":  list,
		"total": total,
	})
}
```

then visit http://localhost/product

```
func (ctx *context) URLParam(name string) string {
	return ctx.request.URL.Query().Get(name)
}

// URLParamInt returns the url query parameter as int value from a request,
// returns an error if parse failed.
func (ctx *context) URLParamInt(name string) (int, error) {
	return strconv.Atoi(ctx.URLParam(name))
}
```
the above is your implement, i think check it is empty is required!

**************
update 2017-09-21 0:14 +8

init router at mvc mode

```
        api := app.Party("/api")
	api.Controller("/auth", new(controller.Auth))
	api.Use(controller.TokenAuth)
	api.Controller("/a", new(controller.Admin))
```

Ctx is nil 

```
func (u *Admin) GetProduct() {
	page, err := u.Ctx.URLParamInt("page") // Ctx is nil 
	if err != nil {
		page = 1
	}
	size, err := u.Ctx.URLParamInt("size")
	if err != nil {
		size = service.DefaultSize
	}

	list, total, err := service.GetProduct(bson.M{}, page, size)
	if err != nil {
		u.Ctx.JSON(NewErrorResponse(err.Error()))
		return
	}
	u.Ctx.JSON(service.RespData{
		"list":  list,
		"total": total,
	})
}
```

*************************
2017-9-21 10:10:33 +8

case by use BeginRequest, although it's just a empty implement
```
func (u *Admin) BeginRequest(ctx iris.Context) {
	
}
```

**Comment by kataras** [comment]
You've right, the `URLParamInt` doesn't check if parameter is exist or not, I will fix it right now but on your second comment you say that `Ctx is nil` on `GetProduct()`  but this is not what I get when I ran it, could you please explain it more in order to find if this is a bug or you miss something?

**Comment by tfzxyinhao** [comment]
https://github.com/kataras/iris/blob/e7d6452ee965b91570710076e7a3847fb44fc00e/mvc/controller.go#L229

if you want to rewrite BeginRequest that you must assign ctx to your custom controller's Ctx otherwise  you get a nil pointer at the next handler

**Comment by kataras** [comment]
If you add a custom `BeginRequest` you have to call the embedded `BeginRequest` like our `SessionController` does: https://github.com/kataras/iris/blob/master/mvc/session_controller.go#L23
