### ISSUE TITLE
github.com/iris-contrib/letsencrypt cannot be used in v5

### ISSUE THREAD

**Issue by dongfengkuayue** [kataras/iris#763]
for iris-v5, in http.go file it imports `github.com/iris-contrib/letsencrypt`,but this repo is already romoved from `github.com/iris-contrib`

**Comment by dongfengkuayue** [comment]
@kataras

**Comment by hiveminded** [comment]
Use the latest ,standard, crypto package instead. You can look the source code of Iris v8 to learn how.
