### ISSUE TITLE
Get pongo2.Value from view.Value

### ISSUE THREAD

**Issue by balthild** [kataras/iris#764]
I cannot access methods of `*pongo2.Value` with `*view.Value`. Therefore, I cannot build a custom filter for pongo2. For example:

```go
import "github.com/kataras/iris/view"

func ACustomFilter(in *view.Value, param *view.Value) (out *view.Value, err *view.Error) {
	val := in.Interface() // This doesn't work
	fmt.Println(val)

	return
}
```

It should be better if `*view.Value` have implemented such a method:

```go
// github.com/kataras/iris/view/django.go

func (v *Value) GetValue() *pongo2.Value {
	return (*pongo2.Value)(v)
}
```

Then I could do:
```go
import "github.com/kataras/iris/view"

func ACustomFilter(in *view.Value, param *view.Value) (out *view.Value, err *view.Error) {
	val := in.GetValue().Interface()
	fmt.Println(val)

	return
}
```

Same with the `*view.Error`.

**Comment by kataras** [comment]
@balthild I understand, I could fix it but maybe you'll need more pongo types so I think it should be better to give you the chance to create one PR based on your needs, I will accept it, just make sure that it works :)

**Comment by kataras** [comment]
Resolved by https://github.com/kataras/iris/pull/765
