### ISSUE TITLE
Session: Support regeneration of ID

### ISSUE THREAD

**Issue by Dingo2018** [kataras/iris#768]
Sometimes it need to regenerate the Session ID so please support a function for the regeneration of the sessionID.

https://www.owasp.org/index.php/Session_fixation
http://en.wikipedia.org/wiki/Session_fixation

Thank you.

**Comment by hiveminded** [comment]
@Dingo2018 , You can already use the [SessionIDGenerator](https://github.com/kataras/iris/blob/master/sessions/config.go#L68 ) field to generate and compute a session ID fit to your needs. Take a look at "secure cookie" example too.
