### ISSUE TITLE
Lost f.Close 

### ISSUE THREAD

**Issue by gooid** [kataras/iris#770]
context/context.go 

```
func (ctx *context) ServeFile(filename string, gzipCompression bool) error {
	f, err := os.Open(filename)
	if err != nil {
		return fmt.Errorf("%d", 404)
	}
	defer f.Close()
	fi, _ := f.Stat()
	if fi.IsDir() {
		filename = path.Join(filename, "index.html")
		f, err = os.Open(filename)
		if err != nil {
			return fmt.Errorf("%d", 404)
		}
		defer f.Close()   // Add close 
		fi, _ = f.Stat()
	}
	return ctx.ServeContent(f, fi.Name(), fi.ModTime(), gzipCompression)

}
```
***defer f.Close()   // Add close***

**Comment by krokite** [comment]
`defer f.Close()` twice does not make sense.

`defer` runs at end of function always - so, you don't have to repeat that everytime, but look into your requirement properly and prepare more better code for it.

Thanks

**Comment by kataras** [comment]
This does not make sense, like @krokite noted, the `f.Close` runs at the end of the function execution and `f` is changed so it will call proper file's Close. This is an invalid propose. However  I have to inform you that double-closing files doesn't do anything, it doesn't hurt so if you add twice `defer f.Close()` on your own codebase it's ok, it will not panic or something like that.

**Comment by gooid** [comment]
Not same os.File object, Is must done.
demo.go
```
package main

import (
	"fmt"
	"os"
	"path"
	"time"
)

func DemoClose(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return fmt.Errorf("%d", 404)
	}
	defer f.Close()
	fi, _ := f.Stat()
	if fi.IsDir() {
		fmt.Println("open index.html")
		filename = path.Join(filename, "index.html")
		f, err = os.Open(filename)
		if err != nil {
			return fmt.Errorf("%d", 404)
		}
		//defer f.Close() // Add close
		fi, _ = f.Stat()
	}
	return nil
}

func main() {
	filename := "dir"
	DemoClose(filename)

	time.Sleep(30 * time.Second)  
       // Until the program exits, the "index.html" are locked.
}
```

**Comment by kataras** [comment]
I understand the scope and you've right, I'm sorry for not seen that earlier, I'm in hurry the last weeks! 
But **I don't like `defer f.Close()` twice in the same function body**. I think we can do it with more efficient way: 

```go
package main

import (
	"fmt"
	"os"
	"path"
)

func DemoClose(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return fmt.Errorf("%d", 404)
	}
	defer f.Close()
	fi, _ := f.Stat()
	if fi.IsDir() {
		fmt.Println("open index.html")
		return DemoClose(path.Join(filename, "index.html")) // <--- a better way instead of calling f.Close twice.
	}
	return nil
}

func main() {
	filename := "dir"
	DemoClose(filename)

	fmt.Println(os.Rename(path.Join(filename, "index.html"), path.Join(filename, "index1.html")))
}
```


Upgrade your iris with `go get -u github.com/kataras/iris` and it should be fixed, thank you very much @gooid for your report! Just a small note; the next time please try to explain the problem from the first place, don't wait for me to answer you, other people can fix your issue with a PR if they understand it, ok?
