### ISSUE TITLE
session with redis problem

### ISSUE THREAD

**Issue by cdren** [kataras/iris#771]
IRIS VERSION 8.4.3
GO VERSION 1.9
REDIS 4.0.2

i run the example "iris/_examples/sessions/database/redis"
every new request without cookie the console  will print an error 

> Now listening on: http://localhost:8080
> Application started. Press CMD+C to shut down.
> [ERRO] 2017/09/30 10:25 error while trying to load session values(4df5abe0-bf9c-457e-af4b-5daea4d27527) from redis: Key '4df5abe0-bf9c-457e-af4b-5daea4d27527' doesn't found
> [ERRO] 2017/09/30 10:25 error while trying to load session values(1b984cfa-6299-4314-abb5-8a12318875b6) from redis: Key '1b984cfa-6299-4314-abb5-8a12318875b6' doesn't found

**Comment by krokite** [comment]
It looks like key was not created - Have you verified and updated below settings as per your server :- 

`
db := redis.New(service.Config{
		Network:     service.DefaultRedisNetwork,
		Addr:        service.DefaultRedisAddr,
		Password:    "",
		Database:    "",
		MaxIdle:     0,
		MaxActive:   0,
		IdleTimeout: service.DefaultRedisIdleTimeout,
		Prefix:      ""})
`

**Comment by cdren** [comment]
The key  was created correctly,I can find the key in redis and it works good;
I read the source code  "sessions/provider.go"



1
![image](https://user-images.githubusercontent.com/7949490/31045725-770f18f0-a5af-11e7-80e1-93f391b1d68a.png)
2
![image](https://user-images.githubusercontent.com/7949490/31045727-84039450-a5af-11e7-8b35-adf969ad4b52.png)
3
![image](https://user-images.githubusercontent.com/7949490/31045737-baee2bec-a5af-11e7-822e-9b89fa4a637b.png)
4
![image](https://user-images.githubusercontent.com/7949490/31045740-cde99024-a5af-11e7-8a3c-1fa76dfa8eff.png)


“newSession” will load values from redis by the sid we just created，if it's not exist，the error will be print，so every new request without sid  will trigger this error;

**Comment by kataras** [comment]
@cdren Fixed, upgrade with `go get -u github.com/kataras/iris` and it should be fine now, I am not redis user myself so I depend on you for that remote store, tell me if the fix works for you!
