### ISSUE TITLE
UseGlobal: handler call order is bad

### ISSUE THREAD

**Issue by ZaniaDeveloper** [kataras/iris#778]
Hello,

There is a problem in call order of handlers passed to `app.Use()` and `app.UseGlobal` method.

Here, is tested code:
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.New()

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 1")
	})

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 2")
	})

	app.Use(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 3")
	})

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 4")
	})

	app.Use(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 5")
	})

	app.Use(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 6")
	})

	app.Get("/a", func(ctx context.Context) {
		ctx.WriteString("Hello 1 !")
	})

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 7")
	})

	app.Use(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 8")
	})

	app.Get("/b", func(ctx context.Context) {
		ctx.WriteString("Hello 2 !")
	})

	app.Run(iris.Addr(":9000"))
}
```

With `curl http://localhost:9000/a`, the effective result is
```
[INFO] 2017/10/04 23:42 PASS 7
[INFO] 2017/10/04 23:42 PASS 1
[INFO] 2017/10/04 23:42 PASS 2
[INFO] 2017/10/04 23:42 PASS 4
[INFO] 2017/10/04 23:42 PASS 3
[INFO] 2017/10/04 23:42 PASS 5
[INFO] 2017/10/04 23:42 PASS 6
```
But the expected order should be: 1, 2, 4, 7, 3, 5, 6

With the `app.UseGlobal()` at line 45 (the last one), its handler is called in first.

But strangely for `curl http://localhost:9000/b`, the effective result is
```
[INFO] 2017/10/04 23:42 PASS 1
[INFO] 2017/10/04 23:42 PASS 2
[INFO] 2017/10/04 23:42 PASS 4
[INFO] 2017/10/04 23:42 PASS 7
[INFO] 2017/10/04 23:42 PASS 3
[INFO] 2017/10/04 23:42 PASS 5
[INFO] 2017/10/04 23:42 PASS 6
[INFO] 2017/10/04 23:42 PASS 8
```
Which is the expected result.

Best regards.

**Comment by ZaniaDeveloper** [comment]
The testd code can be simplified with:
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.New()

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 1")
	})

	app.Get("/", func(ctx context.Context) {
		ctx.WriteString("Hello !")
	})

	app.UseGlobal(func(ctx context.Context) {
		defer ctx.Next()
		ctx.Application().Logger().Info("PASS 2")
	})

	app.Run(iris.Addr(":9000"))
}
```

With `curl http://localhost:9000/`, the result is:
```
[INFO] 2017/10/04 23:58 PASS 2
[INFO] 2017/10/04 23:58 PASS 1
```

**Comment by kataras** [comment]
Hello @ZaniaDeveloper , nice to have you back!

This is the exactly use of `UseGlobal`, we use `UseGlobal` to register a handler(s) in front of all other handlers, to all already registered routes, to all subdomains, even to the error handlers and to the next routes (if any), the use of `Use` is easier, it just adds handler(s) with order. You don't have to use the `UseGlobal` if you don't need it, `Use` will do the job at 99% of the cases. 

The only thing that `UseGlobal` can do that `Use` can't is to be able to import third-party packages that can register some handlers of themselves as top(first in order) handlers.

**Comment by ZaniaDeveloper** [comment]
It ok for me, but with your explanation the order is false. As i understood, `UseGlobal` prepend, do with the first test the expected order is 7,4,2,1,3,5,6 and not 7,1,2,4,3,5,6. 

In all case, prepend or append, the result is false.
