### ISSUE TITLE
About render middleware Funcs parameters

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#78]
Render middleware Funcs parameters to add function can not be compiled, if I remove the template file in the function call code can be compiled. Using the template variable to add the function does not have this problem.

**Comment by kataras** [comment]
Hello, can you give me a snippet about your problem?

**Comment by kataras** [comment]
@dxvgef  if your problem solved please close this issue

**Comment by dxvgef** [comment]
I'm trying, because you just updated the render

**Comment by kataras** [comment]
No I made it yesterday, but you didn't read the header of the render package, no problem I'm waiting, thanks for your interest!

**Comment by dxvgef** [comment]
I read the new render document to solve the problem, thank you for your prompt!
