### ISSUE TITLE
Websocket: time.Ticker cause memory leak

### ISSUE THREAD

**Issue by jerson** [kataras/iris#791]
According to the golang documentation, time.Ticker does not allow to use the GC correctly

    // Ticker cannot be recovered by the garbage collector; it "leaks".

see links:
https://github.com/golang/go/commit/a3985e400f1afe6f6640b03dceb4ef8396a2763a
https://github.com/golang/go/issues/11662

note: use time.Sleep can solve the problem

**Comment by kataras** [comment]
Hey @jerson thanks for that but I already know that and I have to notice that;

> Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. Note that this leaks associated resources; **use NewTicker and Stop to avoid that**. 

Iris websocket **doesn't use the `Tick` method** inside the `connection.go` , we use the channel as it's, so we don't have the problem you described, we also `Stop` it, look:

https://github.com/kataras/iris/blob/master/websocket/connection.go#L307 
and for `Stop` ; https://github.com/kataras/iris/blob/master/websocket/server.go#L382

**Comment by jerson** [comment]
im using iris websocket on my server, just spot the difference

   time.NewTicker // does not allow the garbage collector to remove the go routine

see reports from my server before and after

![monitoreo setbeat com_3001_dashboard_db_proyectos-go_refresh 30s orgid 1 var-job ws var-interval 10m from now-24h to now](https://user-images.githubusercontent.com/325780/31822789-88311faa-b56f-11e7-9f06-36d70ffa3131.png)

**Comment by kataras** [comment]
Hmm that's strange, does the Go team knows that? I will re-open your PR and accept that, if that fixes the problem no problem, `time.Sleep` seems more simple in that use case as well so I assume that you know what you're doing, nice job!

**Comment by jerson** [comment]
Thanks @kataras,
currently all working properly and it seems that everything is stable
<img width="639" alt="screen shot 2017-10-20 at 12 02 38" src="https://user-images.githubusercontent.com/325780/31833011-cc0007d6-b58e-11e7-8f78-7fbc47fae625.png">
