### ISSUE TITLE
audio/mpeg3 does not appear to be a valid registered mime type

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#798]
Hi, Triggering a Ctx.SendFile on an mp3 causes the download to be proceeded with attachment type as audio/mpeg3.

I think it should be audio/mpeg:

Refer: http://www.iana.org/assignments/media-types/media-types.xhtml#audio

**Comment by kataras** [comment]
Hey, that's easy to be fixed, the new version will have the "audio/mpeg" registered to `.mp3` but audio/mpeg3 is not false type for that kind of file.

- https://github.com/kataras/iris/blob/master/core/router/mime.go#L238

- https://github.com/kataras/iris/blob/master/core/router/mime.go#L544

## How to change/ or add new mime types, even custom one:

```go
import ""mime"
// ...
mime.AddExtensionType(".mp3","audio/mpeg")
```
