### ISSUE TITLE
video file can't play on webkit

### ISSUE THREAD

**Issue by WingGao** [kataras/iris#800]
code
```go
app.StaticServe(conf.MediaPath, "/uploads")
```
log
```
[INFO] 2017/11/04 20:30 200 27.458326ms 192.168.2.1 GET /uploads/2017-11/demo.mp4
[ERRO] 2017/11/04 20:30 while trying to serve content to the client. Trace write tcp 192.168.2.1:7031->192.168.2.1:65212: write: broken pipe
[INFO] 2017/11/04 20:30 404 7.616061ms 192.168.2.1 GET /uploads/2017-11/demo.mp4
```
The safari will send two request when the video is open, but the second one will return an err.
It works fine on Chrome but failed on webkit (safari).

**Comment by kataras** [comment]
`app.StaticServe` uses gzip compression and does the exactly same thing as `net/http` does, so the same problem occurs with the standard library as well, no surprises. Did you try with `app.StaticWeb` instead?

**Comment by WingGao** [comment]
Thanks!, `app.StaticServe` works great! 
`app.StaticServe` may not support http header with `Range: xxx`

**Comment by kataras** [comment]
Thank you for your feedback, you're awesome and very polite!
You mean `app.StaticWeb` worked, right? I'll improve the overall static file serving, we have already a StaticHandler a builder for that, it needs to be documented a little more in order to replace the `ServeStatic`.
