### ISSUE TITLE
use app.StaticWeb to build a static handler will allways return 301

### ISSUE THREAD

**Issue by WingGao** [kataras/iris#804]
Code:
```go
app.StaticWeb("/uploads", dirPath)
```
When you open a folder `localhost/uploads/afolder` or a index file `localhost/uploads/afolder/index.html`, it always return a `301`to`/uploads/afolder`, and browser will show `ERR_TOO_MANY_REDIRECTS`
But use`DisablePathCorrection=true` will solve this problem.
```go
appConf := iris.Configuration{
		DisablePathCorrection: true,
	}
app.Run(iris.Addr(conf.Addr), iris.WithConfiguration(appConf))
app.StaticWeb("/uploads", dirPath)
```

**Comment by rebootcode** [comment]
**What is your `dirPath`?**

This is right way though:- 
```
app.StaticWeb("/uploads", "./uploads")
```
Now, access:- `http://localhost/uploads/example.png` or any file, it will open perfectly.

Check you `dirPath` variable to find your error.

**Comment by WingGao** [comment]
@rebootcode  dit path is an absolute path `/User/xxxx/a/b`

**Comment by rebootcode** [comment]
@WingGao

Try set the path from the location where app is running, i.e, if app is running at `/User/xxxx/go-server` and your upload directory is at `/User/xxxx/go-server/uploads` and your app is running at `/User/xxxx/go-server` than set the code like below :- 

`app.StaticWeb("/uploads", "./uploads")`

If your app Upload folder is at `/User/xxxx/Downloads/uploads` and your app is running at `/User/xxxx/go-server` than set your code as:- 

`app.StaticWeb("/uploads", "../Downloads/uploads")`

**Also, make sure your app has permission to view provided folders.**

**Comment by WingGao** [comment]
@rebootcode I resove use this code
```go
appConf := iris.Configuration{
		DisablePathCorrection: true,
	}
app.Run(iris.Addr(conf.Addr), iris.WithConfiguration(appConf))
```

**Comment by kataras** [comment]
Yes @WingGao `iris.Run` goes always last, it's blocks and serves your applications, as all examples shows ;p, please close the issue when you can

**Comment by kataras** [comment]
Yes @WingGao `iris.Run` goes always last, it blocks and serves your application, as all examples shows ;p, please close the issue whenever you can and not problem, we all make mistakes
