### ISSUE TITLE
TollBoth Middleware

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#805]
From Example below taken from https://github.com/iris-contrib/middleware/blob/master/tollboothic/_examples/limit-handler/main.go#L16:23

```
package main
import (
	"github.com/kataras/iris"
	"github.com/didip/tollbooth"
	"github.com/iris-contrib/middleware/tollboothic"
)
func main() {
	app := iris.New()
	limiter := tollbooth.NewLimiter(1, nil)
	// or create a limiter with expirable token buckets
	// This setting means:
	// create a 1 request/second limiter and
	// every token bucket in it will expire 1 hour after it was initially set.
	// limiter := tollbooth.NewLimiter(1, &limiter.ExpirableOptions{DefaultExpirationTTL: time.Hour})

	app.Get("/", tollboothic.LimitHandler(limiter), func(ctx iris.Context) {
		ctx.HTML("<b>Hello, world!</b>")
	})

	app.Run(iris.Addr(":8080"))
}
```

It limits `1 request per second`.

Can we do limit based on minute? i.e, `1 request per minute` ?

**Comment by kataras** [comment]
@rebootcode Hello, this is easy, just pass 60 (60 seconds = 1 minute), the default duration is "second" but you can change it as well.  The comments the iris' example provides you can see the `tollbooth.NewLimiter(1, nil)` , the second argument can accept a `limiter.ExpirableOptions`,  it has a field of `DefaultExpirationTTL`, see at; https://github.com/didip/tollbooth/blob/master/limiter/limiter_options.go#L8.

However, the most logical thing to do is to ask the most responsibile person to answer you,  @didip, the author of the didip/tollbooth/](https://github.com/didip/tollbooth/) package.

**Comment by kataras** [comment]
@rebootcode Hello, this is easy, just pass 60 (60 seconds = 1 minute), the default duration is "second" but you can change it as well.  You can see the `tollbooth.NewLimiter(1, nil)` , the second argument can accept a `limiter.ExpirableOptions`,  it has a field of `DefaultExpirationTTL`, see at; https://github.com/didip/tollbooth/blob/master/limiter/limiter_options.go#L8.

However, the most logical thing to do is to ask the most responsibile person to answer you,  @didip, the author of the [didip/tollbooth/](https://github.com/didip/tollbooth/) package, you didn't had to open a new issue for this in the core of the framework, next time please open issues on their relative repository, thank you very much!

**Comment by rebootcode** [comment]
**I am sorry, you are right!**

I didn't realize, this was vendor package issue.

Closing here.
