### ISSUE TITLE
Content size mismatch with static assets

### ISSUE THREAD

**Issue by Velocity-** [kataras/iris#809]
Using static asset serving sends the wrong content-length to the browser, resulting in Chrome loading indefinitely.

Code sample:
```go
	app := iris.New()

	// Set-up view loading from ./views directory
	tmpl := iris.HTML("./views", ".gohtml")
	tmpl.Reload(true)
	app.RegisterView(tmpl)

	// Setup static files.. (if no route matches, will try assets)
	assetHandler := app.StaticHandler("./static", false, true)
	app.SPA(assetHandler)

	// .. Finally run :)
	app.Run(iris.Addr(config.Server.Address + ":" + config.Server.Port))
```

When loading resources (css, etc) Chrome prints:
`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

**Comment by Velocity-** [comment]
Have the feeling this was caused by d77c17336750a4aea43dc55760d4509dff88cbdc 🤔

**Comment by Velocity-** [comment]
This only seems to be happening on my Windows 10 machine, not on my Macbook.. I'll see if I can figure it out tomorrow.

**Comment by kataras** [comment]
@Velocity- Why you use `SPA` ? Your use case needs a `app.StaticWeb` or a wildcard path parameterized path;

```go
assetHandler := app.StaticHandler("./static", false, true)
app.HandleMulti("GET HEAD", "/{f:path}", assetHandler)
```

And you're done, `SPA` will be deprecated.
