### ISSUE TITLE
Recommendations for session redisstore

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#81]
I very much hope that session can be stored in redis,now session can only be stored in memory?
And uses redis to store the cache Middleware.

**Comment by kataras** [comment]
Yes, sessions now stored only on memory, I will create a redisstore also, this is a feature, nice for adding to the issues!

**Comment by dxvgef** [comment]
when to support redis? I Want to use Iris production as soon as possible

**Comment by kataras** [comment]
Redisstore on sessions will be the first of the next features, if you want give me some code snippets and example on how you imagine to write/declare/howtouse redis with sessions in order to make it works as you are expected!

**Comment by kataras** [comment]
Soon, I already did some work on this, expect it the next couple days :)

**Comment by dxvgef** [comment]
@kataras Thank you for your work and look forward to the new features of Iris.

**Comment by kataras** [comment]
@dxvgef Ready, check https://kataras.gitbooks.io/iris/content/package-sessions.html and https://github.com/iris-contrib/examples/blob/master/sessions/redisstore/main.go

**Comment by dxvgef** [comment]
@kataras Why isn't session/providers/redis in the master branch?I use the get -u go command to get the version is still 2.0.0

**Comment by kataras** [comment]
It will be at the next commit. Master has a more stable version on it, redisstore is not tested by the community yet, when it does and I understand that it's stable I will push it to master branch.
