### ISSUE TITLE
How to set multi-languagefile in i18n?

### ISSUE THREAD

**Issue by syssam** [kataras/iris#815]
Could you provide an explicit way to set multi-languagefile in i18n at runtime?
The document only mention that key(string):value(string)

**Comment by speedwheel** [comment]
@syssam First of all did you check this [example](https://github.com/kataras/iris/blob/master/_examples/miscellaneous/i18n/main.go)?

If that still didn't help with your issue, can you show an example on how you view it: Iris code + language file + html?

**Comment by syssam** [comment]
@speedwheel 
Yes.I check this example.
you may be misunderstanding my idea.

For example, I going to "auth" page, then I want to load locale_common_en-US.ini and locale_auth_en-US.ini

However, the example only provide key(string):value(string), not key(string):value(map)

how can I do this, thanks a lot

**Comment by kataras** [comment]
@syssam  @speedwheel Done: just separate the files by comma, the API didn't change.
Example: https://github.com/kataras/iris/blob/master/_examples/miscellaneous/i18n/main.go#L45

Now you can also use more than one middleware to support more language files as it goes, the child will have the parent's values language's keys as well, (i.e /multi has the `globalLocale` as well because of the `app.Use`),  thank you for your feature request and have fun!

**Comment by syssam** [comment]
@kataras great, thank you for your quick response.

**Comment by syssam** [comment]
I think that, it should be provide a api, like setMessage, it will be merge the same key.

Why I say that, becuase, "i18n.New" should init on the start, and put on the "app.Use".
I would not like set agian on the new controller,  and put on the "app.Use".
Do you think so?
It's only my humble opinion.

**Comment by kataras** [comment]
@syssam You're welcome mate, I don't understand your question but the `SetMessage` you're referring to, is already public in the `github.com/iris-contrib/i18n` library which is used on the `kataras/iris/middleware/i18n` middleware. Those packages work "globally" so if you call `SetMessage` from the `iris-contrib/i18n` those locales will be available on the middleware as well.

I don't understand your second question,  what do you mean by `and put on the "app.Use" -- I would not like set again on the new controller, and put on the "app.Use"` Please give examples, you don't have to register them on `app.Use`, there are middleware, register the global locale on `app.Use` and the rest via routes or group of routes (`app.Party`).

**Comment by syssam** [comment]
@kataras Ok, I miss it. thanks
