### ISSUE TITLE
StaticWeb TOO_MANY_REDIRECTS if filename contains '#' character

### ISSUE THREAD

**Issue by nsuper** [kataras/iris#822]
Example URL:
`http://localhost:8080/public/css/#1.css`

CURL:
```
curl http://localhost:8080/public/css/#1.css

HTTP/1.1 301 Moved Permanently
Location: /public/css
Date: Sun, 26 Nov 2017 02:19:39 GMT
Content-Type: text/plain; charset=utf-8

<a href="/public/css">Moved Permanently</a>.

<a href="/public/css">Moved Permanently</a>.

```

Google Chrome:
```
localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

Firefox:
```
The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by kataras** [comment]
What did you expected instead? the `#` symbol is not part of the server's url routing mechanism, it's used only for client-side things, did you use `#` for other reasons? If yes please tell me about those in order to implement something that will give you a more complete solution

**Comment by nsuper** [comment]
I'm writing a Simple File Browser. I think '#' is a valid character.

Invalid characters for filename:
```
Linux: / and \0
OSX: : and \0
Windows: \, /, ?, :, *, ", >, <, and |
```

**Comment by davidchalifoux** [comment]
Yeah I'm 99% positive that using '#' in api routing is not good practice and potentially not possible. I've only seen it used for routing on the frontend.

**Comment by nsuper** [comment]
Use `html.tempate.URL`
