### ISSUE TITLE
Any idea? Bootstrap proyect structure using controllers instead handlers (question)

### ISSUE THREAD

**Issue by AgustinJimenez** [kataras/iris#823]
Hello, i'm new using iris, my english is't so good.
Now i'm trying to manage bootstrap proyect structure (iris\_examples\structuring\bootstrap) using controllers instead handlers, i'm not a expert but i need to find a way to start and keep sessions across controllers, i tried to use user_controller (iris\_examples\mvc\login) to manage users sessions, but does't work on this case. 

my routes.go look like this, i'm not sure if this is a good stuff.
```
frontendRoutes := b.Party("/")
{
	frontendRoutes.Controller("/", new(PagesControllers.HomeController))
	frontendRoutes.Controller("/", new(UserControllers.UserController), b.Sessions)
		
	backendRoutes := frontendRoutes.Party("/admin", SomeMiddleware )
	{
		backendRoutes.Layout("/views/layouts/admin.html")
		backendRoutes.Controller("/", new(AdminControllers.DashboardController))
	}
}
```

**Comment by kataras** [comment]
I dont understand what is not working, @speedwheel any ideas?

**Comment by AgustinJimenez** [comment]
This is my repo https://github.com/AgustinJimenez/iris_test1 just need mysql, database configuration (libraries\xorm\xorm_mysql.go)

**Comment by speedwheel** [comment]
@AgustinJimenez pass the `b.Sessions` to all the controllers where you need access to the session.

**Comment by AgustinJimenez** [comment]
In this case, on post register i create user and then like login example i set session data, then on the next route, 'inside' admin dashboard session data aren't there.
```
func (this *UserController) PostRegister() mvc.Result {
	new_service := services.UserService{}
	new_user, err := new_service.Create(this.Ctx.FormValue("password"), datamodels.User{

		Firstname: this.Ctx.FormValue("first_name"),
		Lastname:  this.Ctx.FormValue("last_name"),
		Username:  this.Ctx.FormValue("username"),
		Email:     this.Ctx.FormValue("email"),
	})
	this.Session.Set(userIDKey, new_user.Id)// <--------------SESSION SET
	return mvc.Response{
		Err: err,
		Path: "/admin",
	}
}

func (this *UserController) GetAdmin() mvc.Result {

	fmt.Println("USER SESSION user_id AND isLoggedIn =====>", this.getCurrentUserID(), this.isLoggedIn()) // <----------not saved
	return mvc.View{
		Name:   "users/resources/views/backend/dashboard/index.html",
		Data:   context.Map{"Title": "User Registration"},
		Layout: "core/resources/templates/admin/index.html",
	}
}
```

**Comment by speedwheel** [comment]
on this line:
```go
backendRoutes.Controller("/", new(UserControllers.UserController))
```
try to change it to:
backendRoutes.Controller("/", new(UserControllers.UserController), b.Sessions))

**Comment by AgustinJimenez** [comment]
Maybe i tried that before.
![captura](https://user-images.githubusercontent.com/21246906/33438617-286e96e4-d5ca-11e7-96d2-4c856f832c3e.PNG)
