### ISSUE TITLE
[question] difference between `defer` and `iris.RegisterOnInterrupt` for db.close

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#829]
In [badger example](https://github.com/kataras/iris/blob/master/_examples/sessions/database/badger/main.go#L19:7), I found `iris.RegisterOnInterrupt` function used to close the `db` connection.

It left me thinking if there is any difference between them or have an advantage in using  `iris.RegisterOnInterrupt` over `defer`

### iris.RegisterOnInterrupt

```
db, err := badger.New("./data")
	if err != nil {
		panic(err)
	}

	// close and unlock the database when control+C/cmd+C pressed
	iris.RegisterOnInterrupt(func() {
		db.Close()
	})
```
# vs

### defer db.Close()

```
        db, err := badger.New("./data")
	if err != nil {
		panic(err)
	}
	defer db.Close()
```

All I can guess is using  `iris.RegisterOnInterrupt`  may have 1 disadvantage and that is if program exits on panic, the `db` won't be closed.

**But since the code was for `badger` which runs on memory, it could be a good idea to only close on "Interrupt" and not in any other ways.**

Is that the reason to choose ?  `iris.RegisterOnInterrupt` for `badger` ?

**Comment by kataras** [comment]
Yes that's the reason and you guess correctly, `defer` will be executed when program ends, in the other hand `RegisterOnInterrupt` will be fired when closing the program manually (via ctrl/cmd+C). I use both `defer` and `RegisterOnInterrupt` for closing any open database connections or file-based storage, it doesn't hurt.
