### ISSUE TITLE
Use urlpath in template with MVC

### ISSUE THREAD

**Issue by euclid1990** [kataras/iris#832]
I have a `AppController` with following actions: 
```
func (c *AppController) Get() mvc.View {
	...
}

func (c *AppController) GetUser() mvc.View {
	...
}
```
But, how to print route to it with `urlpath` helper in template.
```go
// Define routing
app.Controller("/", new(controllers.AppController))
```

`{{ urlpath "mynamedroute" "pathParameter_ifneeded" }}` ?
What is mynamedroute and pathParameter_ifneeded in this case ?

Can anyone help me ? 😢

**Comment by rebootcode** [comment]
what are you trying to do ?

**Comment by euclid1990** [comment]
@rebootcode I want to embed link to action in HTML template

**Comment by kataras** [comment]
Hey @euclid1990 ,

The default route name (if you don't change it, you can't do it with the current MVC implementation but you will be able on the new release I'm coding the last weeks) is the subdomain(if any)+method+registered path, look [here](https://github.com/kataras/iris/blob/master/core/router/route.go#L54).

Yours `mynamedroute` is: "GET/"  for your `Get() mvc.View` controller and "GET/user" for your `GetUser() mvc.View`.

**Comment by euclid1990** [comment]
@kataras Thank you for useful information !

**Comment by kataras** [comment]
You're welcome @euclid1990 , have fun!

**Comment by euclid1990** [comment]
@kataras I have one more question, If I have method as following:
```go
func (c *AppController) GetUserList() mvc.View {
	...
}
```
What is the link(url) to this action ? I have tried http://site.com/user-list or http://site.com/userlist or http://site.com/user_list , but it not available 😂

**Comment by kataras** [comment]
@euclid1990 it's `http://site.com/user/list`, readme has a good example of MVC and explains that every word starting with uppercase and it's not a "reserved word" (like `By` and `ByWildcard` with input parameters) then it's a sub route of the controller.

**Comment by euclid1990** [comment]
@kataras Thank you for your kind support! ❤️

**Comment by kataras** [comment]
@euclid1990 Always , thank you for your participation in the community!

**Comment by kataras** [comment]
@euclid1990 From now on, if you upgrade with `go get -u github.com/kataras/iris` you can change the name of a route created by controller activator or register custom ones. See below:

```go
func (c *AppController) AfterActivation(a AfterActivation) {
	// change automatic parser's route change name.
       route := a.GetRoute("GetUserList")
       route.Name = "your custom name that you want to use for reverse routing"
}
```

**Comment by euclid1990** [comment]
@kataras: thank you

**Comment by kataras** [comment]
You're welcome, happy new year!
