### ISSUE TITLE
GetCookie after SetCookie the result is empty string

### ISSUE THREAD

**Issue by wuhong40** [kataras/iris#834]
code:
ctx.SetCookieKV("name", "value")
ctx.GetCookie("name") // the output is ""

and  after request there is a cookie("name") with value ("value)

**Comment by rebootcode** [comment]
are you trying to get the cookie in the same request?

Please share full code.

**Comment by kataras** [comment]
@wuhong40 , Cookies are not context's local storage, use `context.Values().Set/Get` to store values that you want to retrieve from the same request lifecycle, cookies are stored when response sent to the client and can be retrieved at the next request.
