### ISSUE TITLE
ctx.ViewData(key,value) alternative for HTML output

### ISSUE THREAD

**Issue by krokite** [kataras/iris#836]
I could not find `iris` support for sharing `html` un-esccaped string with `ctx`

Currently, I had to hack code to print output in HTML :- 

go file :- 

```
ctx.ViewData("content", "<p>This is HTML content.</p><br><h3>Another String</h3>")
```
template file.
```
<script>
    document.write(unescape({{ .content }}))
</script>
```

But, I am looking for simple way to print data without `unescape` in `javascript`

**Comment by speedwheel** [comment]
@krokite I don't know if this is the best way, but this is how I do it and it works:
 ```go
ctx.ViewData("content", template.HTML("<p>This is HTML content.</p><br><h3>Another String</h3>"))

**Comment by kataras** [comment]
@krokite  and @speedwheel correct, this is the right way, this is the go way. If you use the `iris.HTML` view engine, which is an improvement version of the `html/template`, you should the `template.HTML` to bind a "secure" html string to the view template.
