### ISSUE TITLE
response header lost while using default responseWriter

### ISSUE THREAD

**Issue by DukeGatto** [kataras/iris#838]
can't add header after `context.Write()` and other similar funcs which with the default writer, those headers will be removed after handlefunc's return.

especially in func `context.WriteGzip()`, data will respond as gzip body but without header `content-encoding: gzip`, users have to add additional header before writing their gzip body.

but this problem won't happen when the writer is replaced with gzipWriter, even with gzip disabled.

the reason seems to be in the package `net/http`, it also occurred in the server I built based on this package

**Comment by kataras** [comment]
Yes @DukeGatto but why is that a problem with this behavior? I believe that this is an advandage, by-design, it's the best thing to make sure that you know when your response is sent to the client. However for advanced scenarios and not too common: Iris has a `context#ResponseRecorder` that you can use if you want to write something and after override it or modify it later on.

**Comment by DukeGatto** [comment]
it's easy to understand the "re-write" part is intent designed

and sorry for my description(and the title) maybe wasn't precise enough and seems let you misled, the func (or method) I once said is `(ctx *context) WriteGzip(b []byte) (int, error)`

now here is the situation I once met
![gzip](https://user-images.githubusercontent.com/19605723/33975981-1b8d15aa-e0cd-11e7-9a17-1c2859afedd9.png)

the header added by https://github.com/kataras/iris/blob/master/context/context.go#L1913 was removed

**Comment by kataras** [comment]
Yes it didn't use the `ctx.GzipResponseWriter()`, now it's fixed **and you can also add headers after the Write method (when you use GzipResponseWriter or ResponseRecorder)**.

Upgrade with `go get -u github.com/kataras/iris`, example added as well: https://github.com/kataras/iris/blob/master/_examples/http_responsewriter/write-gzip/main.go

Thank you @DukeGatto !
