### ISSUE TITLE
Form and Validation

### ISSUE THREAD

**Issue by joefazee** [kataras/iris#84]
Do we have any plan for form and validation?

Coming from a PHP background i think a framework like Laravel does a great thing with forms and validation. We can borrow ideas from such framework.

I am still learning go but i will start using the framework to create small projects and provide feedback as much as i can.

**Comment by kataras** [comment]
I was  also php,.net,java ee,nodejs boy and finally go, I ensure you that we took the right choice:) 

Form validation is a feature, but you can always use third party packages for form validations inside the iris' handler. 
Also I am recommending you to read the [iris book](https://www.gitbook.com/book/kataras/iris/details), for example, we have a `context.ReadForm(&yourobject{})` with this you can a bind a validator and if validated then pass the data to the database and so on

**Comment by ryanbyyc** [comment]
Essentially what I do is parse the form data into context.ReadForm, and then call myForm.Validate() on it using https://gopkg.in/bluesuncorp/validator.v8 - less is more!

**Comment by kataras** [comment]
Exactly this I was meaning. Nice!
