### ISSUE TITLE
how to use hero template engine with iris? 

### ISSUE THREAD

**Issue by aisq2008** [kataras/iris#840]
I want to use hero template engine with iris in my project , but i don't know which is the best way to  use  them, somebody could write an example in folder __examples ?, thank you!

hero project address : https://github.com/shiyanhui/hero

**Comment by kataras** [comment]
Hello @aisq2008 , at your commands.

Although you don't need an example for this but I've just created one you, it's based on the sample example that the hero package has on its repository so you can easy follow the two small changes you have to do:) 

See here: https://github.com/kataras/iris/tree/master/_examples/http_responsewriter/hero and have fun!

**Comment by aisq2008** [comment]
thank you very much
