### ISSUE TITLE
the foulest frame of a wolf

### ISSUE THREAD

**Issue by dari28** [kataras/iris#841]
the foulest frame of a wolf

**Comment by dari28** [comment]
$ go build
# gopkg.in/kataras/iris.v5
../../../go/src/gopkg.in/kataras/iris.v5/configuration.go:624:15: unknown field 'CookieLength' in struct literal of type SessionsConfiguration
../../../go/src/gopkg.in/kataras/iris.v5/configuration.go:625:15: unknown field 'DecodeCookie' in struct literal of type SessionsConfiguration
../../../go/src/gopkg.in/kataras/iris.v5/context.go:22:2: imported and not used: "github.com/iris-contrib/formBinder" as formbinder
../../../go/src/gopkg.in/kataras/iris.v5/context.go:417:26: undefined: formBinder
../../../go/src/gopkg.in/kataras/iris.v5/context.go:1115:28: cannot convert nil to type sessions.Sessions
../../../go/src/gopkg.in/kataras/iris.v5/context.go:1116:3: cannot use nil as type sessions.Session in return argument
../../../go/src/gopkg.in/kataras/iris.v5/context.go:1119:17: cannot convert nil to type sessions.Session
../../../go/src/gopkg.in/kataras/iris.v5/context.go:1120:15: cannot use ctx.framework.sessions.StartFasthttp(ctx.RequestCtx) (type *sessions.Session) as type sessions.Session in assignment
../../../go/src/gopkg.in/kataras/iris.v5/context.go:1127:33: cannot convert nil to type sessions.Session
../../../go/src/gopkg.in/kataras/iris.v5/iris.go:236:28: not enough arguments in call to sessions.New
        have ()
        want (sessions.Config)
../../../go/src/gopkg.in/kataras/iris.v5/iris.go:236:28: too many errors

**Comment by dari28** [comment]
what it is and how it happened that I can not edit my project due to the fact that there are a lot of mistakes in this accursed iris
not when do not use it !!!!!!!

**Comment by kataras** [comment]
@dari28 Keep your self calm and read the Code Of Conduct. Use the http://gopkg.in/kataras/go-sessions.v0 instead of `github.com/kataras/go-sessions`. I'm happy that you use old versions of Iris but you can upgrade yourself to v8, it has a lot of more features plus http/2.
