### ISSUE TITLE
Enable http2

### ISSUE THREAD

**Issue by IPrototypeI** [kataras/iris#842]
Hello guys I am sry for open this issue but I am new in golang and want to start with this framework. I couldn't find how to enable http2 for this framework in the documentation.

Which steps I have to follow ? Maybe anybody have a link for me.

**Comment by kataras** [comment]
Hello @IPrototypeI HTTP/2 is enabled when you serve your web server with TLS/SSL (HTTPS). 

You can serve using https with the following runners: 

- `iris.TLS`: https://github.com/kataras/iris/blob/master/iris.go#L549
- `iris.AutoTLS`: https://github.com/kataras/iris/blob/master/iris.go#L592
- `iris.Listener`: https://github.com/kataras/iris/blob/master/iris.go#L477

For example: `app.Run(iris.TLS("127.0.0.1:443", "mycert.cert", "mykey.key"))` 

You can see examples of all those by navigating at: https://github.com/kataras/iris/tree/master/_examples/http-listening

You can levarage the `Push` feature at any case; `ctx.ResponseWriter().Push(...)`. Example of a simple `Push` of a javascript library is shown here: https://github.com/kataras/iris/blob/master/_examples/websocket/secure/main.go#L40

If you going production then you may want to use something like `nginx` or `caddy` to serve more than one web applications on PORT 80. You can view a caddy example here: https://github.com/kataras/iris/tree/master/_examples/tutorial/caddy

You're welcome to our community!

**Comment by IPrototypeI** [comment]
Hello Kataras awesome
thank you very much for your help.
