### ISSUE TITLE
CROS Middleware is not working

### ISSUE THREAD

**Issue by januslinhc** [kataras/iris#847]
I have followed the example code stated on the official page:

Server Port: 80
Server Script:
`app.WrapRouter(cors.WrapNext(cors.Options{
		AllowedOrigins:   []string{"*"},
	 	AllowCredentials: true,
	 }))`

Client Port: 8081

When I post request from the client side, it throws an error and stated: "Response to the preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

<img width="1078" alt="2017-12-23 9 03 50" src="https://user-images.githubusercontent.com/4537368/34319778-2682de86-e825-11e7-98b4-e990975a8c13.png">

**Comment by kataras** [comment]
Hello @januslinhc , could you please post a sample code that reproduces this? because the example is working well and I my guess showcases I made to resolve this are also working as expected

**Comment by januslinhc** [comment]
Hi @kataras,

Thank you for your reply.

There is my server script:
`// file: main.go

package main

import (
	"time"
	"fmt"
	"github.com/kataras/iris"
	"payment/services"
	"payment/web/controllers"
	"github.com/kataras/iris/sessions"
	r "gopkg.in/gorethink/gorethink.v4"		
	"github.com/iris-contrib/middleware/cors"
	"github.com/kataras/iris/middleware/logger"	
)

var session *r.Session

func init() {
	var err error
	session, err = r.Connect(r.ConnectOpts{
		Address:  "localhost:28015",
		Database: "test",
	})
	if err != nil {
		fmt.Println(err)
		return
	}
}

func main() {
	app := iris.New()	
	
	app.Use(logger.New())

	app.Logger().SetLevel("debug")

	// Load the template files.
	tmpl := iris.HTML("./web/views", ".html").
		//Layout("shared/layout.html").
		Reload(true)

	app.RegisterView(tmpl)

	app.StaticWeb("/static", "./web/public")

	app.OnAnyErrorCode(func(ctx iris.Context) {
		ctx.ViewData("Message", ctx.Values().
			GetStringDefault("message", "The page you're looking for doesn't exist"))
		ctx.View("shared/error.html")
	})

	sessManager := sessions.New(sessions.Config{
		Cookie:  "JanusInvoiceSystem",
		Expires: 24 * time.Hour,
	})

	staffService := services.NewStaffService(session)

	app.Controller("/auth", new(controllers.AuthController),
	staffService,
	sessManager,
	)

	// Create our repositories and services.
	
	
	app.WrapRouter(cors.WrapNext(cors.Options{
		 	AllowedOrigins:   []string{"*"},
			 AllowCredentials: false,
		 }))

	app.Run(
		iris.Addr(":80"),
		iris.WithoutVersionChecker,
		iris.WithoutServerError(iris.ErrServerClosed),
		iris.WithOptimizations, // enables faster json serialization and more
	)
}
`

And for the client side script, I used VueJS:

`
this.$http
            .post(
              "/auth",
              {
                email: that.form.email,
                password: that.form.password
              },
              {
                emulateJSON: true
              }
            )
            .then(
              response => {
                if (response.body.result == false) {
                  that.alert("Alert", response.body.msg);
                } else {
                }
              },
              response => {
                that.alert("Error", "Error, please try again later.");
              }
            );
`

Thanks.

**Comment by kataras** [comment]
@januslinhc Can you please try the below and tell me your results?

Comment the lines about the "app.WrapRouter" and replace them with:

```go
app.UseGlobal(func(ctx iris.Context){
   ctx.Header("Access-Control-Allow-Origin", "*")
   ctx.Next()
})
```

So simple, if that works for you then we will have to see what's wrong in your application because still `cors` is working here (you may need to clear your browser's cache for new tries), this is very simple scenario, thank you very much, I'm waiting!

**Comment by januslinhc** [comment]
Hi @kataras 
I have tested with your code, and it still not works. Since the client will first send the OPTIONS request to the server before the POST request, however, the server response 404 not found error.

**Comment by kataras** [comment]
You're welcome @januslinhc , happy to help you but can you tell me what was the problem, the browser's cache from previous tries?
