### ISSUE TITLE
Cannot resolve dependency:github.com/dgraph-io/badger: commit='d8b951787ebe5c42286475df8a3dea25045bda1a', branch='master', urls=[https://github.com/dgraph-io/badger.git, git@github.com:dgraph-io/badger.git

### ISSUE THREAD

**Issue by jossion-pan** [kataras/iris#848]
Cannot resolve dependency:github.com/dgraph-io/badger: commit='d8b951787ebe5c42286475df8a3dea25045bda1a', branch='master', urls=[https://github.com/dgraph-io/badger.git, git@github.com:dgraph-io/badger.git

**Comment by kataras** [comment]
I've just did `go get -u githun.com/kataras/iris` and all works like a charm, so I asssume that you use the `dep` tool from `golang` organisation, the commit exists so it shouldn't fire this error, here's the commit: https://github.com/dgraph-io/badger/commit/d8b951787ebe5c42286475df8a3dea25045bda1a

You have to post this issue on the `dep` tool repository, Iris has nothing to do with it, although I could update the `badger` to its latest release (it was unstable this is why I didn't do it so far)
