### ISSUE TITLE
Miss the method StaticFS(relative string, systemPath string, stripSlashes int) for iris

### ISSUE THREAD

**Issue by cxjava** [kataras/iris#85]
I think the iris miss the method StaticFS(relative string, systemPath string, stripSlashes int), because on page [Static files](https://kataras.gitbooks.io/iris/content/static-files.html) have this method.
```
// Static registers a route which serves a system directory
// it generates an index page to view the directory's files
StaticFS(relative string, systemPath string, stripSlashes int)
```

**Comment by kataras** [comment]
Oh you're right , upgrade Iris with ` go get -u github.com/kataras/iris`. I forgot to add it to the default (iris.) station! Thanks you!!
