### ISSUE TITLE
List registered  routes

### ISSUE THREAD

**Issue by lightglitch** [kataras/iris#851]
Can we list all registered routes and parameters to generate documentation for example?

**Comment by kataras** [comment]
Yes of course, `app.GetRoutes()` will give you a slice of *Route, each `*Route` has a func named `Tmpl()` this returns a `macro.Template` which contains the field `Params`, `Params` is a slice of `macro.TemplateParam` which contains all the information you need about the path parameters, you could also use the `Tmpl().Src` to get the unparsed route's path string`
