### ISSUE TITLE
Question: Logger for 404 errors

### ISSUE THREAD

**Issue by theoptz** [kataras/iris#86]
Hello,
I don't see 404 errors in output of logger middleware. How i can fix it?

Thanks

**Comment by kataras** [comment]
Yes logger doesn't logs for errors like 404, only for panics, you recommend logs to these kind of errors also ?

**Comment by theoptz** [comment]
Yes, now i can see 404 errors in log. 
But i've lost context of request. In my middleware i save ip, authorization header and some other headers in context
```
func initContext(ctx *iris.Context) {
	ip := string(ctx.Request.Header.Peek("X-Forwarded-For"))
	if ip == "" {
		ip = strings.Split(ctx.RemoteAddr(), ":")[0]
	}

	ctx.Set("ip", ip)

    // ... some other code
	ctx.Next()
}
```

and in this case all of this keys are empty
```
   ctx.Get("ip")
```

Is it possible to get these keys from context?

**Comment by kataras** [comment]
Yes, ofcourse! ```ctx.RemoteAddr()``` already gives you the real ip (checking for X-Fowarded-For also)  no need to do it yourself :P 
```ctx.RequestIP()``` gives you the IP without checking for X-Fowarded-For.

**Comment by theoptz** [comment]
thanks)

i use custom logger function which works like a default logger middleware
i need it for custom format of my log file

i use this code:

```
iris.OnError(404, func(ctx *iris.Context) {
    errorLogger.Serve(ctx)
    ctx.Write("My Custom 404 error page content")
})
```

and when i try to get values from context in logger function i can't get values which have been stored in context in previous middlewares

Here is part of my logger
```
type appLogger struct{}

func (l *appLogger) Serve(ctx *iris.Context) {
	t1 := time.Now()
	ctx.Next()
	deltaT := time.Since(t1)

	//...

	// here i can't get token value
	token, ok := ctx.Get("token").(string)
	if !ok || token == "" {
		token = "-"
	}

	//... log
}
```



here is a middlewares which i use
```
func getToken(h string) string {
	tokenParts := strings.Split(h, " ")
	if len(tokenParts) != 2 || tokenParts[0] != "Bearer" || tokenParts[1] == "" {
		return ""
	}

	return tokenParts[1]
}

func initContext(ctx *iris.Context) {
	// ...
	token := getToken(string(ctx.Request.Header.Peek("Authorization")))
	ctx.Set("token", token)

        // ...
	ctx.Next()
}
```

is there any way to get token value from context on 404 error?

**Comment by kataras** [comment]
Yes, you 're right good. `ctx.Set("key","value")` and ` val := ctx.GetString("key")` its not the problem, I think that you have to send me the full code, how you declare middleware, which one fist and all that, because I think that you, by falt, execute the ctx.Get()  and after the .Set()
