### ISSUE TITLE
Can't install iris with go get.

### ISSUE THREAD

**Issue by doubledare704** [kataras/iris#860]
~/go/src/example$ go get -u github.com/kataras/iris
package github.com/kataras/iris: no Go files in /home/alexey/GO/src/github.com/kataras/iris
 maybe i have some env issues?
echo $GOROOT
/usr/local/go
echo $GOPATH
/home/alexey/GO
$PATH has go links to bin folder

**Comment by kataras** [comment]
Hello @doubledare704 , I don't know why but you had a folder named /kataras/iris with empty go files before installing Iris, maybe you have to delete the "$GOPATH/src/github.com/kataras" manually and execute `go get -u github.com/kataras/iris` again, it seems that you messed up with your gopath :)

**Comment by doubledare704** [comment]
ok, thank you, I will recheck
