### ISSUE TITLE
Dependency issue with satori/go.uuid

### ISSUE THREAD

**Issue by NSmithUK** [kataras/iris#861]
A backwards breaking change has been commit to master in the `github.com/satori/go.uuid` dependency, which has resulted in `core/errors/errors.go` no longer being able to compile.

Iris' Gopkg.toml has
```
[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"
```

... so it's pulling in the change when I `dep ensure`, resulting in the build failing with `iris/core/errors/errors.go:35:22: multiple-value uuid.NewV4() in single-value context`.

**Comment by kataras** [comment]
We have "github.com/satorigo.uuid" vendored in the `/vendor` folder because it's being used by our session manager's various databases, but you're using the `dep` tool with Iris, keep note that the vendors are hard-maden here, I never use the `dep` tool. We've just create `gopkg.toml` and `.lock` files thinking that it will be easier for `dep` users to use Iris but we have to maintain the versions as well, so here we just have to tell it what "commit" to fetch, I push a commit for that, thank you very much!

**Comment by kataras** [comment]
We have "github.com/satori/go.uuid" vendored in the `/vendor` folder because it's being used by our session manager's various databases, but you're using the `dep` tool with Iris, keep note that the vendors are hard-maden here, I never use the `dep` tool. We've just create `gopkg.toml` and `.lock` files thinking that it will be easier for `dep` users to use Iris but we have to maintain the versions as well, so here we just have to tell it what "commit" to fetch, I push a commit for that, thank you very much!

**Comment by singlewind** [comment]
@kataras , I thought you have fixed this issue with @satori by add a tag named v1.2.0
When I install via `go get`, it will install 10.0.2 for me correctly. When I `dep init` and `dep ensure`, it will install 10.0.0 in my vendor folder. I tried to edit my `Gopkg.toml` to upgrade the version. It gives me error bellow:

```
v1.2.0: Could not introduce github.com/satori/go.uuid@v1.2.0, as it is not allowed by constraint v1.2.0 from project github.com/kataras/iris.
v1.1.0: Could not introduce github.com/satori/go.uuid@v1.1.0, as it is not allowed by constraint v1.2.0 from project github.com/kataras/iris.
v1.0.0: Could not introduce github.com/satori/go.uuid@v1.0.0, as it is not allowed by constraint v1.2.0 from project github.com/kataras/iris.
master: Could not introduce github.com/satori/go.uuid@master, as it is not allowed by constraint v1.2.0 from project github.com/kataras/iris.
```
How can I manually fix the issue?

**Comment by kataras** [comment]
@singlewind Hey could you upgrade with `go get -u github.com/kataras/iris` and try again? Or go to the `Gopkg.lock` of the kataras/iris folder and edit the github.com/satori/go.uuid entry, change the "master" with "v1.2.0", the result should be something like this:

```yml
[[projects]]
  branch = "v1.2.0" // <--- this was "master", change it to "v1.2.0"
  name = "github.com/satori/go.uuid"
  packages = ["."]
  revision = "f58768cc1a7a7e77a3bd49e98cdd21419399b6a3"
```

Please write down the results, thank you very much!

-----
I don't understand: what do you mean "it will install 10.0.0 in my vendor folder", the latest Iris release is the 10.0.2 in the releases tags so even if you vendoring Iris using a third-party tool (which I don't recommend, you can just  copy-paste the iris folder with its two non-vendored dependencies, the kataras/golog and the iris-contrib/httpexpect). it should take that instead, can you explain to me please, maybe it was a typo inside your comment.

**Comment by singlewind** [comment]
@kataras , It works today when I upgrade dep. It gives me the 10.1.0 of iris version you have released. Still not sure what cause it. Yesterday, dep just keep install 10.0.0 instead of 10.0.2.

**Comment by kataras** [comment]
Yes, that's why I am not recommending that kind of 3rd-party tools...

**Comment by robert-li-sphinx** [comment]
I use govendor fetch , but can not compile this error too...

**Comment by robert-li-sphinx** [comment]
the error is same as NSmithUK

**Comment by kataras** [comment]
Why is this an iris problem and not `govendor`'s issue I still don't understand my friends... be careful what tools you're using and for what purpose please

**Comment by robert-li-sphinx** [comment]
sorry, I didn't get your point, or is there anything misunderstood ? In uuid package, the api looks like this below:
```
// NewV4 returns random generated UUID.
func NewV4() (UUID, error) {
	return global.NewV4()
}

```
but in iris, we use this api like this:
```
uuid.NewV4().String()
``` 
so, should we need to check the error code?

**Comment by kataras** [comment]
What do you mean by `but in iris, we use this api like this...` ? 

Let iris do its things, it knows, you can use whatever version of "x" library you like to, these are not coupled, iris is not coupled to `uuid`, it doesn't accepts any `type` of this package.

Iris has a dependency, which depends on the previous `uuid` library, if we replace the `vendor` the new one, the dependency will break, so the particular session database (badger db or bold db if I'm remembering correctly) will break. We can modify the source code of the dependency to use the latest `uuid` API but it's better to wait a week for the badger (or boltdb) to make the update.

**Comment by robert-li-sphinx** [comment]
ok，i got your point. Did you mean "iris" and "boltdb" depend on old version of uuid, if we update uuid with new version , and modify iris/core/errors/errors.go:35:22 with newer id, _ := uuid.NewV4(), the compile of iris will go weill, but the boltdb will break......so we have to wait for the boltdb to make update ?

**Comment by kataras** [comment]
Wait, I push the latest version, if something breaks feel responsible to notify me back, ok ?

**Comment by robert-li-sphinx** [comment]
I meant  in iris  iris/core/errors/errors.go, our code looks like this:
```
// New creates and returns an Error with a pre-defined user output message
// all methods below that doesn't accept a pointer receiver because actually they are not changing the original message
func New(errMsg string) Error {
	return Error{
		ID:      uuid.NewV4().String(),
		Message: Prefix + errMsg,
	}
}
```
but we should  define like this:
```
/ New creates and returns an Error with a pre-defined user output message
// all methods below that doesn't accept a pointer receiver because actually they are not changing the original message
func New(errMsg string) Error {
	id, _ := uuid.NewV4()
	return Error{
		ID:      id.String(),
		Message: Prefix + errMsg,
	}
}
```

**Comment by robert-li-sphinx** [comment]
ok, i am glad to do that :)

**Comment by kataras** [comment]
You have right, I already did that and revert it a month ago because a dependency was not updated with the latest API and I dont want to duplicate things because of the /core/errors package, it's so essential thing, not a big deal at all. Done, test it please and tell me the results, on the future if you or any other developer have any problem with that library we will refer here.
