### ISSUE TITLE
strange error: cannot use Configuration literal

### ISSUE THREAD

**Issue by rightjoin** [kataras/iris#863]
Documentation for the Iris project can be found at
<https://iris-go.com/v8/recipe>.

Love iris? Please consider supporting our collective:
👉  https://opencollective.com/iris/donate

I am running go 1.9.2
I installed iris using go get -u github.com/kataras/iris and 
go get github.com/kataras/iris/...

I created a simple application with a controller. But getting a strange error when I run it:

```
go run main.go
# gopkg.in/kataras/iris.v8
../../../gopkg.in/kataras/iris.v8/configuration.go:513:5: cannot use Configuration literal (type *Configuration) as type "github.com/kataras/iris/context".ConfigurationReadOnly in assignment:
	*Configuration does not implement "github.com/kataras/iris/context".ConfigurationReadOnly (missing GetPostMaxMemory method)
../../../gopkg.in/kataras/iris.v8/go19.go:117:15: undefined: mvc.Controller
../../../gopkg.in/kataras/iris.v8/go19.go:148:6: undefined: mvc.C
../../../gopkg.in/kataras/iris.v8/iris.go:206:12: cannot use app.config (type *Configuration) as type "github.com/kataras/iris/context".ConfigurationReadOnly in return argument:
	*Configuration does not implement "github.com/kataras/iris/context".ConfigurationReadOnly (missing GetPostMaxMemory method)
```

Here is how my main.go looks like:

```
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/logger"
	"github.com/kataras/iris/middleware/recover"
)

func main() {
	app := iris.New()

	app.Use(recover.New())
	app.Use(logger.New())

	// static assets
	app.StaticServe("./assets", "/")

	// view engine
	app.RegisterView(iris.HTML("./templates", ".html").Layout("layouts/layout.html").Reload(true))

	// controllers
	app.Controller("/testing", new(TestController))

	app.Run(iris.Addr(":8081"))
}
```
I have reinstalled iris. I also cleared my pkg directory.
Any idea how I can get past this issue?

**Comment by speedwheel** [comment]
You've not re-installed Iris, these issues that you're describing are a result of a half updated Iris and half not, please remove your `%GOPATH%/src/github.com/kataras/iris` folder and re-execute `go get -u github.com/kataras/iris`, let it finish this time.

Also, the https://iris-go.com contains recipe and documentation for the **latest iris version**.

You are using an older version of Iris in your code block, please update your code according to the latest API changes. Please read the changelogs before updating to a major 2018 updated version, they are written for us:
 [HISTORY.md](https://github.com/kataras/iris/blob/master/HISTORY.md#mvc)

```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/logger"
	"github.com/kataras/iris/middleware/recover"
)

func main() {
	app := iris.New()

	app.Use(recover.New())
	app.Use(logger.New())

	// static assets
	app.StaticServe("./assets", "/")

	// view engine
	app.RegisterView(iris.HTML("./templates", ".html").Layout("layouts/layout.html").Reload(true))

	// controllers, 
	mvc.New(app.Party("/testing")).Handle(new(TestController))

	app.Run(iris.Addr(":8081"))
}
```

**Comment by rightjoin** [comment]
Executed:
rm -rf $GOPATH/pkg/*

**Comment by rightjoin** [comment]
rm -rf $GOPATH/src/github.com/kataras/*

**Comment by rightjoin** [comment]
```
rm -rf $GOPATH/pkg/*
rm -rf $GOPATH/src/github.com/kataras
go get -u github.com/kataras/iris
```

Still getting the same error!
```
go run main.go
# gopkg.in/kataras/iris.v8
../../../gopkg.in/kataras/iris.v8/configuration.go:513:5: cannot use Configuration literal (type *Configuration) as type "github.com/kataras/iris/context".ConfigurationReadOnly in assignment:
	*Configuration does not implement "github.com/kataras/iris/context".ConfigurationReadOnly (missing GetPostMaxMemory method)
../../../gopkg.in/kataras/iris.v8/go19.go:117:15: undefined: mvc.Controller
../../../gopkg.in/kataras/iris.v8/go19.go:148:6: undefined: mvc.C
../../../gopkg.in/kataras/iris.v8/iris.go:206:12: cannot use app.config (type *Configuration) as type "github.com/kataras/iris/context".ConfigurationReadOnly in return argument:
	*Configuration does not implement "github.com/kataras/iris/context".ConfigurationReadOnly (missing GetPostMaxMemory method)
```

**Comment by rightjoin** [comment]
```
rm -rf $GOPATH/gopkg.in/kataras
```

Leftovers were in gopkg directory. Above fixed it.

**Comment by ryzzn** [comment]
I've the same issue.

Because I use gopkg.in/kataras/iris.v8, the code in v8 branch there's code need include package from github.com/kataras/iris which contains codes in master branch. So if they don't match each other the issue would come out. 

```
cd $GOPATH/src/github.com/kataras/iris && git checkout v8
```
would fix this problem. I don't think it's the best way but it just works.

**Comment by kataras** [comment]
That's the correct way @ryzzn , we don't use `gopkg.in` anymore, the only versions with `gopkg` are the v5 and v6 actually, you will have to use  the `git checkout $version` and that's better, you will be fine because we have a "vendor" folder and branches on `iris-contrib/middleware` and `iris-contrib/examples` as well. Although if I was you I would upgrade to v10, it doesn't contain any tremendus breaking change and it's better to use the latest version because you can ask for support any time on the [chat](https://chat.iris-go.com) and I can answer faster without having to change my workspace.
