### ISSUE TITLE
About context#View and ViewData

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/iris#865]
```go
func(ctx iris.Context) {
    ctx.ViewData("One", "This is a single value")
    ctx.View("item.html", itTypeStruct{Name: "iris" ,Author:"kataras"})
}
```
```html
In html {{ .One }}  Name:{{ .Name }} Author: {{ .Author }}
```
It will find One from itTypeSturct. I think the merger is better

In addition, another way I expect

**Example 1**

```go
func(ctx iris.Context) {
    ctx.ViewData("Before", "This is the Before value")
    ctx.View("item.html", itTypeStruct{Name: "iris" ,Author:"kataras"}) 
    ctx.ViewData("After", "This is the After value")
}
```
In html
```html
Before: {{ .Before }} Name:{{ .Name }} After:{{ .After }}
```

**Example 2**

```go
func(ctx iris.Context) {
    // I think using empty strings is not elegant
    ctx.ViewData("Single" : "Single Value")

    // struct
    ctx.ViewData(itTypeStruct{
        Name : "iris",
        Author: "kataras",
    })
    
    // k v map
    ctx.ViewData(iris.Map{
        "Author": "The same variable name, the value of the last binding over the previous",
        "Other" : "Other value",
    })

    // context.View Can be used anywhere
    ctx.View("tpl.html", iris.map{ "MapKey" : "This is mapKey value"})
    ctx.View("tpl.html", itTypeStruct{Item: "This is Item value"})
}
```

In html
```html
Other: {{ .Other}} 
Name:{{ .Name }} 
Author:{{ .Author }} 
Single: {{ .Single }} 
MapKey :{{ .MapKey }}
Item: {{ .Item }}
```

output value
```html
Other: Other value
Name: iris
Author: The same variable name, the value of the last binding over the previous
Single: Single Value
MapKey : This is mapKey value
Item: This is Item value
```
What do you think @kataras  ?

**Comment by kataras** [comment]
Look, things are simple:

`ctx.ViewData` is used for key-value template binding, it can be used to set values to the template from previous handlers and after the last handler can just fire the `ctx.View("templateFile.html")`.

`ctx.View("templateFile.html", struct or iris.Map or anything)` can be used to override any `ctx.ViewData` and fire the template with the struct or iris.Map or anything binding data. 

You can use whatever suits you better, if you need to add bindings before the main handler then go for `ctx.ViewData`, if you are rendering the template in the same handler then you can use both `ctx.ViewData` and `ctx.View` directly. I don't understand the confusion

**Comment by Zeno-Code** [comment]
Wait for me to think, I did find some problems, perhaps in mvc

```go
// 1
func (c *MyController) Get (ctx iris.Context) mvc.Result{
    ctx.ViewData("Single", "This is single value")
    ctx.ViewData("", myStruct{Name: "zeno"})
    return mvc.View{
        Name:   "testTpl",
    }
}
```
or
```go
// 2
func (c *MyController) Get (ctx iris.Context) mvc.Result{
    ctx.ViewData("Single", "This is single value")
    return mvc.View{
        Name:   "testTpl",
        Data: myStruct{Name: "zeno"},
    }
}
```
The value I expect
In tpl
```html
{{ .Single }} 
{{ .Name }}
```
Output: 
This is single value
zeno

//1 Error : can't evaluate field Single in type myStruct

//2 I have to use {{  .Data.Name }} to get the Name value if nolayout
//2 If use layout , {{ .Name}} tag in layout.html return "zeno" , in yield must be {{ .Data.name }}

**Comment by kataras** [comment]
In the mvc you return the `mvc.View`, in handlers the `ctx.View` or any other function that it renders should be the latest one call, if you write to the response writer you cannot re-write it or change any other headers (although you can do it with the `ctx.Recorder()` but it's not a common use). I'm going to sleep now because I'm asleep for a whole day almost, giving you time to think and report any issues you may found, I'm using mvc a lot and I couldn't find anything but I'm here to discuss anything with you, ok my friend?

**Comment by Zeno-Code** [comment]
Good dreams
I will test again
I am a bit confused now
