### ISSUE TITLE
 golog need add “funcname ，filepath”，thank u god

### ISSUE THREAD

**Issue by 5nn** [kataras/iris#867]
golog need add func or file path ，thanks

**Comment by kataras** [comment]
Hello @5nn  and welcome to Iris, to be honest I didn't understand your demant, you can already write logs to file or add more writers or change the existing. Please post a complete use case and a good example of your needs at the golog repository itself  https://github.com/kataras/golog. Thank you very much!

**Comment by 5nn** [comment]
example:

iris -->   [WARN] this is an warning message.

I need this:

-->   main.go --func main() --- line 22  ---  [WARN] this is an warning message.

I`m a new go funs, I don't know how to set it ,help me .thank u .

**Comment by 5nn** [comment]
main.go -- func main() --  line 22-- 2018/01/07 18:49:01.1111 :This is a warning message

**Comment by celsosz** [comment]
```
pc, fn, line, _ := runtime.Caller(1)
s := fmt.Sprintf("[assertion failed] line %d (%s) (%s)", line, runtime.FuncForPC(pc).Name(), fn)
```

**Comment by kataras** [comment]
@5nn Golog supports message hijacking, so you can output with your own format like @celsosz , a good example of this is the below (you can modify it to your specific needs):

```go	
import (
    "runtime"
    "fmt"

    "github.com/kataras/golog"
)
// [...]
app.Logger().Handle(func(l *golog.Log) bool {
		prefix := golog.GetTextForLevel(l.Level, true)
		pc, fn, line, _ := runtime.Caller(6)
		message := fmt.Sprintf("%s line %d (%s) (%s) %s: %s",
			prefix, line, runtime.FuncForPC(pc).Name(), fn, l.FormatTime(), l.Message)

		if l.NewLine {
			message += "\n"
		}

		fmt.Print(message)
		return true
	})
```
// [...]

**Comment by kataras** [comment]
@5nn Golog supports message hijacking, so you can output with your own format like @celsosz , a good example of this is the below (you can modify it to your specific needs):

```go	
import (
    "runtime"
    "fmt"

    "github.com/kataras/golog"
)
// [...]
app.Logger().Handle(func(l *golog.Log) bool {
	prefix := golog.GetTextForLevel(l.Level, true)
	pc, fn, line, _ := runtime.Caller(6)
	message := fmt.Sprintf("%s line %d (%s) (%s) %s: %s",
		prefix, line, runtime.FuncForPC(pc).Name(), fn, l.FormatTime(), l.Message)

	if l.NewLine {
		message += "\n"
	}

	fmt.Print(message)
	return true
})
// [...]
```

**Comment by 5nn** [comment]
thank ,good job !!

**Comment by kataras** [comment]
You're welcome mate, comment if you have any further questions!
