### ISSUE TITLE
No PostValueDefault for PUT method

### ISSUE THREAD

**Issue by mich4s** [kataras/iris#870]
When i try to do put method i can't get values from request header, only from request params, but when i do post method it's contravise. It's quite annoing, because i have to setup different headers on client app. Maybe this could be fixed to work on request headers in both methods?

**Comment by kataras** [comment]
Hey @mich4s , your title and your post body is bit confusing for me (request headers and post body-params are not the same thing), could you please give us some code snippets and write what did you saw and did you expect to see instead?

**Comment by kataras** [comment]
Hey @mich4s , your title and your post body is a bit confusing, at least to me (request headers and post body-params are not the same thing), could you please give us some code snippets and write what did you saw and did you expect to see instead?

**Comment by kataras** [comment]
@mich4s Please close the issues you opened when you release that it's not a repo's problem. I re-tested it and it works like a charm, headers and post values are parsed correctly in both POST and PUT requests.
