### ISSUE TITLE
why iris aways new a file named "iris.yml" in my mac' user root path.feel so bad ...!

### ISSUE THREAD

**Issue by 5nn** [kataras/iris#871]

**Comment by kataras** [comment]
This is used for global configuration across multiple Iris instances, that configuration is filled with the default options, like `app.Run(iris.Addr("..."))` without second argument(s).  If you pass `app.Run(iris.Addr("..."), iris.WithConfiguration(iris.YAML("~"))` then it uses that configuration file.

**Comment by kataras** [comment]
This is used for global configuration across multiple Iris instances, that configuration is filled with the default options, like `app.Run(iris.Addr("..."))` without second argument(s).  If you pass `app.Run(iris.Addr("..."), iris.WithConfiguration(iris.YAML("~")))` then it uses that configuration file for the app's options.
