### ISSUE TITLE
[ERRO] 2018/01/13 12:33 html/template: cannot Parse after Execute

### ISSUE THREAD

**Issue by little-pan** [kataras/iris#872]
// The case when concurrent access!
// 
// - go version go1.9.1 windows/amd64
// - Iris-10.0.0
// 
// template config
tpl := iris.HTML(configuration.TplBae, Tpl_suffix)
// reload templates on each request (development mode!)
tpl.Reload(true)

**Comment by kataras** [comment]
Of course it can't parse after execute, this is `html/template` thing and it's normal behavior, but it `parses` the file on **each request because you have .Reload(true)** if you disable it(as you **MUST** do on production) then you're are fine, the templates are parsed once.

**Comment by little-pan** [comment]
Then the method Reload() should be  deprecated, or we can sync road and execute if reload is true in dev mode.

**Comment by kataras** [comment]
Why deprecated man? It's not created to be used like that, it's inside the `html/template` we can't add lockers there lol

**Comment by little-pan** [comment]
No problem in product environment, but it is unavailable in dev mode! In dev mode(set Reload(true))， it's not convenient to modify template file that can lead to parse error! So ... the method Reload() should be deprecated, or we can sync road and execute if reload is true in dev mode.

I had sync the block following, it's work **in dev mode**.
// 
// ExecuteWriter executes a template and writes its result to the w writer.
func (s *HTMLEngine) ExecuteWriter(w io.Writer, name string, layout string, bindingData interface{}) error {
	// reload the templates if reload configuration field is true
	if s.reload {
                // ensure that work in dev mode only!
		**s.muReload.Lock()
		defer s.muReload.Unlock()**
		if err := s.Load(); err != nil {
			return err
		}
	}

	layout = getLayout(layout, s.layout)

	if layout != "" {
		s.layoutFuncsFor(name, bindingData)
		name = layout
	} else {
		s.runtimeFuncsFor(name, bindingData)
	}

	return s.Templates.ExecuteTemplate(w, name, bindingData)
}
