### ISSUE TITLE
Please make a release tag for v10.0.1

### ISSUE THREAD

**Issue by zcong1993** [kataras/iris#875]
```ini
[[constraint]]
  name = "github.com/iris-contrib/middleware"
  version = "10.0.0"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.0.0"
```

`dep` use the latest release by default, now is `v10.0.0`

so it always trigger the version checker

**Comment by kataras** [comment]
Yes if you're using `dep` with automatic update I have to create a new release for each version or you can simple disable version checker by `app.Run(..., iris.WithoutVersionChecker)`, tag `v10.0.1` created.
