### ISSUE TITLE
Basicauth expiration

### ISSUE THREAD

**Issue by martinnagelberg** [kataras/iris#879]
The original function doesn't read the expiration time from de config so it doesn't work. I added it below.
```

func New(c Config) context.Handler {
	config := DefaultConfig()
	if c.Realm != "" {
		config.Realm = c.Realm
	}
	config.Users = c.Users
        config.Expires = c.Expires
	b := &basicAuthMiddleware{config: config}
	b.init()
	return b.Serve
}
```

**Comment by kataras** [comment]
Oh you've right, what a mess, thank you very much, I fixed it but you can push a [PR](https://github.com/kataras/iris/pulls) in the future as well, it was a real issue :) Thank you very much @martinnagelberg !
