### ISSUE TITLE
Get form data is not working

### ISSUE THREAD

**Issue by SoldierCorp** [kataras/iris#881]
I'm trying with something very simple, get the information from a slack command of an app I'm building, the example from the website it's actually working https://iris-go.com/v10/recipe#Read Form90 but when I receive data from slack, is not and this error always appear.

    ➜  slack-app go run iris.go
    [DBUG] 2018/01/19 22:10 POST: /prices -> main.main.func1() and 2 more
    [DBUG] 2018/01/19 22:10 Application: running using 1 host(s)
    [DBUG] 2018/01/19 22:10 Host: addr is :8080
    [DBUG] 2018/01/19 22:10 Host: virtual host is localhost:8080
    [DBUG] 2018/01/19 22:10 Host: register startup notifier
    [DBUG] 2018/01/19 22:10 Host: register server shutdown on interrupt(CTRL+C/CMD+C)
    Now listening on: http://localhost:8080
    Application started. Press CMD+C to shut down.
    [WARN] 2018/01/19 22:10 Recovered from a route's Handler('main.main.func1')
    At Request: 200 /prices POST ::1
    Trace: reflect.Value.Interface: cannot return value obtained from unexported field or method

    /usr/local/go/src/runtime/asm_amd64.s:509
    /usr/local/go/src/runtime/panic.go:491
    /usr/local/go/src/reflect/value.go:942
    /usr/local/go/src/reflect/value.go:931
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/utils.go:18
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/binder.go:371
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/binder.go:361
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/binder.go:271
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/binder.go:165
    /Users/myuser/go/src/github.com/kataras/iris/vendor/github.com/iris-contrib/formBinder/binder.go:153
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:1972
    /Users/myuser/go/src/slack-app/iris.go:32
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:900
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:1172
    /Users/myuser/go/src/github.com/kataras/iris/middleware/logger/logger.go:50
    /Users/myuser/go/src/github.com/kataras/iris/middleware/logger/logger.go:31
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:900
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:1172
    /Users/myuser/go/src/github.com/kataras/iris/middleware/recover/recover.go:56
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:913
    /Users/myuser/go/src/github.com/kataras/iris/context/context.go:1070
    /Users/myuser/go/src/github.com/kataras/iris/core/router/handler.go:219
    /Users/myuser/go/src/github.com/kataras/iris/core/router/router.go:70
    /Users/myuser/go/src/github.com/kataras/iris/core/router/router.go:147
    /usr/local/go/src/net/http/server.go:2619
    /usr/local/go/src/net/http/server.go:1801
    /usr/local/go/src/runtime/asm_amd64.s:2337

**code**

        package main

    import (
      "github.com/kataras/iris"

      "github.com/kataras/iris/middleware/logger"
      "github.com/kataras/iris/middleware/recover"
    )

    type Student struct {
      channel_id string
      channel_name string
      command string
      response_url string
      team_domain string
      team_id string
      text string
      token string
      trigger_id string
      user_id string
      user_name string
    }

    func main() {
      app := iris.New()
      app.Logger().SetLevel("debug")
      app.Use(recover.New())
      app.Use(logger.New())

      app.Post("/prices", func(ctx iris.Context) {
        student := Student{}
        err := ctx.ReadForm(&student)
        if err != nil {
          ctx.StatusCode(iris.StatusInternalServerError)
          ctx.WriteString(err.Error())
        }

        ctx.Writef("Student: %#v", student)
      })

      app.Run(iris.Addr(":8080"))
    }

Do you have any idea?

**Comment by Zeno-Code** [comment]
```go
    student := &Student{}
    err := ctx.ReadForm(student)
```

**Comment by SoldierCorp** [comment]
Same error

**Comment by SoldierCorp** [comment]
This is the soluion

    ChannelId string `form:"channel_id"`
    ChannelName string `form:"channel_name"`

**Comment by kataras** [comment]
Yes @SoldierCorp This is a general rule, go cannot set unexported fields using reflection, so `ReadForm` couldn't work if you have lowercase fields,, not only in Iris but everywhere, examples like [this](https://github.com/kataras/iris/blob/master/_examples/http_request/read-form/main.go) shows you the way :) Please read the examples before opening a new issue, thank you very much and don't hesitate to ask more!
