### ISSUE TITLE
Soluce to `AllowedMethods` option for CORS middleware

### ISSUE THREAD

**Issue by ZaniaDeveloper** [kataras/iris#884]
Hello,

I found the problem with `AllowedMethods` option.
Actually, this option works (unlike that the comments in source codes).

The problem comes from the non-existence of a routing for `OPTIONS` HTTP method.

First i used:
```go
	app := iris.New()

	app.UseGlobal(New(app, Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"PUT"},
	}))

	app.Put("/put", func(ctx iris.Context) { /* SOMETHING */ })

…
```

It didn't work, when i tried:
 `curl -XOPTIONS http://localhost:3000/req/put`

it returned a `404/Not Found` status

Therefore, `PUT` route wasn't called in cross domain, cause `OPTIONS` method returns 404 status.

But after that, i did this:
```go
	app := iris.New()

	app.UseGlobal(New(app, Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"PUT"},
	}))

	app.Put("/put", func(ctx iris.Context) { /* SOMETHING */ })

	// I added route for `OPTIONS` http method
	app.Options("/put", func(ctx iris.Context) {})

…
```

And it works.

To fix up that, it seems that `app.UseGlobal` middlewares should be called even there is no route found and if the middleware calls `ctx.Next()`, so it really send a 404 HTTP status to web client.

That's destined to `app.UseGlobal` not for `app.Use`, or the API shoud be extended to a new method `app.UseDefault` or `app.UseFinally` (like `finally` in a `try/catch/finally` block) which will be called in such situation.

Then, the cors middleware should check the route existence when `OPTIONS` HTTP method is called, like that:
```go
middleware_to_use_by_website_developpers := func(ctx context.Context) {
    defer ctx.Next()

    if ctx.Method() != "OPTIONS" {
        return
    }

    uri := ctx.Request().RequestURI
    method := ctx.GetHeader("Access-Control-Request-Method")

    if RouteExists(uri, method) {
        cors_middleware(ctx) // Call the original CORS middleware
    }
}
```

Another thing, for a fully use of `github.com/rs/cors` package, i recommends a new function in CORS middleware for Iris with signature `func NewAllowAll() context.Handler` that use `cors.AllowAll()` function of `github.com/rs/cors` package, implemented like that:
```go
func NewAllowAll() context.Handler {
	return handlerconv.FromStdWithNext(cors.AllowAll().ServeHTTP)
}
```

**Comment by kataras** [comment]
Hello @ZaniaDeveloper and happy new year, happy to hear from you again!

I assume that you're speaking about the third-party `cors` middleware which converted to iris and it's located at another repository: https://github.com/iris-contrib/middleware

Please feel free to push any fixes there via PR and I will accept those, personally I am simply setting the header for allowing external origins by `ctx.Header("Access-Control-Allow-Origin", "*")` and it's fine, the `cors` middleware should work depending on other users' comments but you're free to make any necessary changes to be compatible with your needs as well.

**Comment by ZaniaDeveloper** [comment]
Hi, happy new year.

Ok, i'm going to push this issue into (https://github.com/iris-contrib/middleware) repository.

**Comment by ZaniaDeveloper** [comment]
iris-contrib/middleware

**Comment by ZaniaDeveloper** [comment]
Redirected issue to: iris-contrib/middleware#32

**Comment by ZaniaDeveloper** [comment]
There is a part in Iris to fix up this issue, so i have to reopen.

**Comment by ZaniaDeveloper** [comment]
Details of work is in PR.
