### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by krubenrc** [kataras/iris#888]
Hello, when i use autoTLS and i connect from gtmetrix this return me a error about tls handshake.

The error say:  http: TLS handshake error from 71.19.144.227:60036: tls: client offered an unsupported, maximum protocol version of 300

please, do you can help me about this?

Thank you very much in advance!

**Comment by kataras** [comment]
This is an error from the client-side @krubenrc, you have to configure the server to accept that protocol, read more at the https://leysencrypt.org about its protocols, I can't help enough on this, I'm sorry :/

**Comment by kataras** [comment]
This is an error from the client-side @krubenrc, you have to configure the server to accept that protocol or change the client to be compatible with the standards, like the web browsers and tools like postman do, read more at the https://leysencrypt.org about its protocols, I can't help enough on this, I'm sorry :/
