### ISSUE TITLE
Possible memory leak in sessions

### ISSUE THREAD

**Issue by waltrapa** [kataras/iris#889]
HI.

go version go1.9.2 linux/amd64

Im get [https://github.com/kataras/iris/blob/master/_examples/sessions/standalone/main.go](url)

Build and run on pid 4270

# cat /proc/4270/status | grep Vm
VmPeak:	  982872 kB
VmSize:	  920792 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   15940 kB
VmRSS:	   15940 kB
VmData:	  111700 kB
VmStk:	     132 kB
VmExe:	    5040 kB
VmLib:	    2360 kB
VmPTE:	     192 kB
VmPMD:	      24 kB
VmSwap:	       0 kB

Run bombardier:
bombardier -c 128 -n 20000000 http://127.0.0.1:8080/get

And at end bombardier:
# cat /proc/4270/status | grep Vm
VmPeak:	15931192 kB
VmSize:	15931192 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	14632484 kB
VmRSS:	14632484 kB
VmData:	14795060 kB
VmStk:	     132 kB
VmExe:	    5040 kB
VmLib:	    2360 kB
VmPTE:	   28820 kB
VmPMD:	      80 kB
VmSwap:	       0 kB

Im waiting "Expires: time.Hour * 2," and "cat /proc/4270/status | grep Vm" result same.

**Comment by kataras** [comment]
You're waiting 2 hours and after getting the mem stats or you just getting them when the sessions are in the memory, even if not used, try with a smaller `Expires` configuration option like 2 minutes, wait 2-3 minutes and re-execute them, sessions are removed from memory I can't find where you think there is a memory leak, can you please provide me more information or try other session manager and tell me if you see different results? (Iris' sessions should be lighter and faster based on my own tests, at my own machine)

**Comment by waltrapa** [comment]
Hi again.

Test machine:
Ubuntu 17.10 x86_64
16Gb of RAM
go version go1.9.2 linux/amd64

All tests set: Expires: time.Minute * 2
For massive http gets im used [https://github.com/codesenberg/bombardier](url)

https://github.com/kataras/iris/blob/master/_examples/sessions/standalone/main.go
After build and run:
cat /proc/2152/status | grep Rss
RssAnon:	    5572 kB
RssFile:	    9696 kB
RssShmem:	       0 kB

bombardier -c 128 -n 5000000 http://127.0.0.1:8080/get
At finish bombardier:
RssAnon:	 3693520 kB
RssFile:	   10568 kB
RssShmem:	       0 kB


After 3 mins:
cat /proc/2152/status | grep Rss
RssAnon:	 3698924 kB
RssFile:	   10588 kB
RssShmem:	       0 kB


https://github.com/kataras/iris/blob/master/_examples/sessions/database/badger/main.go
After build and run:
cat /proc/2750/status | grep Rs
RssAnon:	   18768 kB
RssFile:	   10596 kB
RssShmem:	       0 kB

bombardier -c 128 -n 5000000 http://127.0.0.1:8080/get
At finish bombardier:
cat /proc/2750/status | grep Rss
RssAnon:	 3649668 kB
RssFile:	   12064 kB
RssShmem:	       0 kB

After 3 mins:
cat /proc/2750/status | grep Rss
RssAnon:	15116760 kB
RssFile:	    6580 kB


https://github.com/kataras/iris/blob/master/_examples/sessions/database/file/main.go
set at line 14: db, _ := file.New("/dev/shm/test_sess/", 0755)
After build and run:
cat /proc/3233/status | grep Rss
RssAnon:	    3020 kB
RssFile:	    9128 kB
RssShmem:	       0 kB

bombardier -c 128 -n 5000000 http://127.0.0.1:8080/get
At finish bombardier:
cat /proc/3233/status | grep Rss
RssAnon:	 4383404 kB
RssFile:	   10344 kB
RssShmem:	       0 kB

After 3 mins in terminal many msgs:
[ERRO] 2018/01/28 14:51 error while destroying and removing the session file: remove /dev/shm/test_sess/e7bc2888-38e3-4a29-870e-e5ae4e2675d3: no such file or directory
ls -ltra /dev/shm/test_sess/

Start(ctx).GetString()

I think the "problem" may be that sess.Start(ctx).GetString() writes data into memory, but it's just a query to know if that session has been made to login.

My previous experience with sessions is limited to python3 + gunicorn + beaker.
In beaker for login, a example:
s = request.environ.get('beaker.session')
s['usr'] = username
s.save()   <--- this put into session store

Thank u and sorry for my bad English.

**Comment by waltrapa** [comment]
Well, after reviewing the source of the sessions I have come to the conclusion that the correct thing in my case is to use ctx.Request().Cookie(cookie_name)

Maybe the documentation is a bit ambiguous in this regard.
But it works correctly. Sorry for the inconvenience.

Thank u again.

**Comment by kataras** [comment]
Hey @waltrapa , you can use `ctx.GetCookie(cookie_name)`, `ctx.SetCookieKV(cookie_name, cookie_value)`, `ctx.RemoveCookie(cookie_name)` and `ctx.SetCookie(*http.Cookie)` as well. I see so in your case you've just wanted cookies, no problem you did well, you interested on it and I'm very grateful for this, hope that you will do the same if you find something in the future as well, even if it's not correct, post it :)
