### ISSUE TITLE
Problem installing iris package: main redeclared in this block

### ISSUE THREAD

**Issue by psybox** [kataras/iris#892]
PS C:\go\src> go version
go version go1.9.2 windows/amd64

I am using Windows 10 and executing on PowerShell:

PS C:\go\src> go get -u -v github.com/gauravtiwari/go_iris_app
github.com/gauravtiwari/go_iris_app (download)
github.com/kataras/iris (download)
github.com/kataras/golog (download)
github.com/kataras/pio (download)
github.com/hashicorp/go-version (download)
github.com/gauravtiwari/go_iris_app
C:\Users\liberato\go\src\github.com\gauravtiwari\go_iris_app\basic.go:17:6: main redeclared in this block
        previous declaration at C:\Users\liberato\go\src\github.com\gauravtiwari\go_iris_app\app.go:10:6
PS C:\go\src>

And there is nothing from github on c:\go\src:

PS C:\go\src> ls

    Directory: C:\go\src

Mode                LastWriteTime         Length Name

d-----        11-Dec-17  11:24 AM                archive
d-----        11-Dec-17  11:25 AM                bufio
d-----        11-Dec-17  11:24 AM                builtin
d-----        11-Dec-17  11:25 AM                bytes
d-----        11-Dec-17  11:24 AM                cmd
d-----        11-Dec-17  11:24 AM                compress
d-----        11-Dec-17  11:24 AM                container
d-----        11-Dec-17  11:24 AM                context
d-----        11-Dec-17  11:24 AM                crypto
d-----        11-Dec-17  11:24 AM                database
d-----        11-Dec-17  11:24 AM                debug
d-----        11-Dec-17  11:25 AM                encoding
d-----        11-Dec-17  11:24 AM                errors
d-----        11-Dec-17  11:24 AM                expvar
d-----        11-Dec-17  11:25 AM                flag
d-----        11-Dec-17  11:25 AM                fmt
d-----        11-Dec-17  11:24 AM                go
d-----        29-Jan-18   2:41 PM                go_iris_app
d-----        11-Dec-17  11:24 AM                hash
d-----        11-Dec-17  11:25 AM                html
d-----        11-Dec-17  11:25 AM                image
d-----        11-Dec-17  11:24 AM                index
d-----        11-Dec-17  11:25 AM                internal
d-----        11-Dec-17  11:25 AM                io
d-----        11-Dec-17  11:25 AM                log
d-----        11-Dec-17  11:25 AM                math
d-----        11-Dec-17  11:25 AM                mime
d-----        11-Dec-17  11:25 AM                net
d-----        11-Dec-17  11:25 AM                os
d-----        11-Dec-17  11:25 AM                path
d-----        11-Dec-17  11:25 AM                plugin
d-----        11-Dec-17  11:25 AM                reflect
d-----        11-Dec-17  11:25 AM                regexp
d-----        11-Dec-17  11:25 AM                runtime
d-----        11-Dec-17  11:25 AM                sort
d-----        11-Dec-17  11:25 AM                strconv
d-----        11-Dec-17  11:25 AM                strings
d-----        11-Dec-17  11:25 AM                sync
d-----        11-Dec-17  11:25 AM                syscall
d-----        11-Dec-17  11:25 AM                testing
d-----        11-Dec-17  11:24 AM                text
d-----        11-Dec-17  11:25 AM                time
d-----        11-Dec-17  11:25 AM                unicode
d-----        11-Dec-17  11:24 AM                unsafe
d-----        11-Dec-17  11:24 AM                vendor
-a----        25-Oct-17   6:31 PM            407 all.bash
-a----        25-Oct-17   6:31 PM            726 all.bat
-a----        25-Oct-17   6:31 PM            385 all.rc
-a----        25-Oct-17   6:31 PM           2632 androidtest.bash
-a----        25-Oct-17   6:31 PM           2049 bootstrap.bash
-a----        25-Oct-17   6:31 PM           1818 buildall.bash
-a----        25-Oct-17   6:31 PM            521 clean.bash
-a----        25-Oct-17   6:31 PM            565 clean.bat
-a----        25-Oct-17   6:31 PM            380 clean.rc
-a----        25-Oct-17   6:31 PM           1519 cmp.bash
-a----        25-Oct-17   6:31 PM           2017 iostest.bash
-a----        25-Oct-17   6:31 PM           6255 make.bash
-a----        25-Oct-17   6:31 PM           3889 make.bat
-a----        25-Oct-17   6:31 PM            553 Make.dist
-a----        25-Oct-17   6:31 PM           2942 make.rc
-a----        25-Oct-17   6:31 PM           1250 naclmake.bash
-a----        25-Oct-17   6:31 PM           1211 nacltest.bash
-a----        25-Oct-17   6:31 PM            853 race.bash
-a----        25-Oct-17   6:31 PM           1037 race.bat
-a----        25-Oct-17   6:31 PM           1668 run.bash
-a----        25-Oct-17   6:31 PM           1134 run.bat
-a----        25-Oct-17   6:31 PM            405 run.rc

**Comment by kataras** [comment]
Hello @psybox , I don't undestand why you post that here? It's not even my project ;p. It's just an example made by another person, and its repository is at https://github.com/gauravtiwari/go_iris_app. It is running perfect, but the error you get is because it has two examples, one with Iris and one with the net/http package, so you can see the differences. You just run `go run app.go` and it runs, so simply...
