### ISSUE TITLE
`Charset` is not a global configuration

### ISSUE THREAD

**Issue by imkos** [kataras/iris#894]
code:
```
app.Configure(iris.WithConfiguration(iris.Configuration{
		Charset: "UTF-8",
	}))
```
or

```
app.Run(iris.Addr(":5060"), iris.WithoutStartupLog, iris.WithCharset("UTF-8"))
```

example:
```
func Hello_test(c context.Context) {
	c.Text("Hi!")
       //c.JSON(....)
       //c.HTML(....)
}
```

not use ctx.Application().ConfigurationReadOnly().GetCharset()

**Comment by kataras** [comment]
They use `ctx.ContentType(ContentTextHeaderValue)` , which adds the charset, if missing based on the ` ctx.Application().ConfigurationReadOnly().GetCharset()`

```go
	// if doesn't contain a charset already then append it
	if !strings.Contains(cType, "charset") {
		if cType != ContentBinaryHeaderValue {
			charset := ctx.Application().ConfigurationReadOnly().GetCharset()
			cType += "; charset=" + charset
		}
	}
```

Did you test a code snippet before open the issue?

**Comment by kataras** [comment]
Why?

They make use of the `ctx.ContentType(ContentTextHeaderValue)` , which adds the charset(if missing), based on the ` ctx.Application().ConfigurationReadOnly().GetCharset()`.

```go
	// if doesn't contain a charset already then append it
	if !strings.Contains(cType, "charset") {
		if cType != ContentBinaryHeaderValue {
			charset := ctx.Application().ConfigurationReadOnly().GetCharset()
			cType += "; charset=" + charset
		}
	}
```

Take a look:

![](https://user-images.githubusercontent.com/22900943/35761217-e8ecbe22-088e-11e8-8158-bb3e8a7cb4af.png)


I'm wondering, what made you to open an issue like that without test and make me to come back to my office from another town to "fix" an invalid issue?...  All context methods that have to do with content type, like the `HTML`, `JSON`, `XML`, `Markdown` make use of that configuration field. 

Please @imkos  test your case before open any other issue in the future, don't hesitate to ask anything --just test it before or provide a valid code snippet.

**Comment by imkos** [comment]
Before app.Run(....)

```
app.Use(iris.Gzip)
```

Please test again.

**Comment by kataras** [comment]
Works, again no issues here.
