### ISSUE TITLE
Wrong benchmark results ? [QUESTION]

### ISSUE THREAD

**Issue by wsantos** [kataras/iris#9]
I ran the benchmark and I don't see that much difference between iris and gonic-gin, what I'm doing wrong ?

Hardware: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - MacOS el captain - Go 1.6
Command: `go test -v -bench=.`
```
BenchmarkGin_GithubAll 	   30000	     57261 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GithubAll	   30000	     53456 ns/op	       0 B/op	       0 allocs/op
```

**Comment by kataras** [comment]
Sorry for late, I was coding I know, I had an issue at the last commits but finaly I totally fix it and make it even faster, update it with 'go get -u github.com/kataras/iris' and test again, post the results here!

**Comment by wsantos** [comment]
Command: `go test -bench=.`

```
   Gin: 55952 Bytes

#GithubAPI Routes: 203
   Iris: 85032 Bytes

PASS
BenchmarkGin_GithubAll 	   30000	     58637 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GithubAll	  100000	     23873 ns/op	       0 B/op	       0 allocs/op
ok  	github.com/kataras/iris	5.016s
```

How can I do the bench with different iris start ? `iris.New` /  `iris.Custom`

**Comment by kataras** [comment]
Just change the iris.New with the commented line is on top, look, here: https://github.com/kataras/iris/blob/master/benchmark_github_test.go#L350 . All big companies use cache do not disable it if you don't have memory problems ( which you can set CacheMaxItems to prevent high memory usage, 1kk of fast requests are only takes 3mb of ram )
