### ISSUE TITLE
validations for structs and individual fields

### ISSUE THREAD

**Issue by majidbigdeli** [kataras/iris#903]
iris is a great  framework .I love Iris very much.Thanks for making iris.
I use [https://godoc.org/gopkg.in/go-playground/validator.v9](https://godoc.org/gopkg.in/go-playground/validator.v9) Can you implement it in iris?
It is important for  server side validation.
I can not speak English well.
i am Iranian

**Comment by kataras** [comment]
You can use it directly within Iris, the `*Request` is the `ctx.Request()` and the `ResponseWriter` is the `ctx.ResponseWriter()`. Please tell me what you expected to see and what did you see instead in order to ask something like this?

**Comment by kataras** [comment]
@majidbigdeli this is also asked before, twice, you may want to take a look at: https://github.com/kataras/iris/issues/84 , write a code snippet with that `validator` and you may want to make a PR to the [_examples](https://github.com/kataras/iris/tree/master/_examples/http_request) folder so you can help other developers that may have the same question as you did in the future :)

Thank you for your nice words about Iris, don't worry about english speaking, I'm not a native speaker too, you will not be criticized here as I don't allow racist comments in my projects :)

**Comment by majidbigdeli** [comment]
@kataras in the asp.net DataAnnotations provides a built-in set of validation attributes that you apply declaratively to any class or property. (It also contains formatting attributes like DataType that help with formatting and don't provide any validation.)

 the Movie class to take advantage of the built-in Required, StringLength, RegularExpression, and Range validation attributes.  

```
public class Movie
{
    public int ID { get; set; }

    [StringLength(60, MinimumLength = 3)]
    [Required]
    public string Title { get; set; }

    [Display(Name = "Release Date")]
    [DataType(DataType.Date)]
    public DateTime ReleaseDate { get; set; }

    [Range(1, 100)]
    [DataType(DataType.Currency)]
    public decimal Price { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
    [Required]
    [StringLength(30)]
    public string Genre { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
    [StringLength(5)]
    [Required]
    public string Rating { get; set; }
}
```
The validation attributes specify behavior that you want to enforce on the model properties they're applied to. The Required and MinimumLength attributes indicates that a property must have a value; but nothing prevents a user from entering white space to satisfy this validation. The RegularExpression attribute is used to limit what characters can be input. In the code above, Genre and Rating must use only letters (white space, numbers and special characters are not allowed). The Range attribute constrains a value to within a specified range. The StringLength attribute lets you set the maximum length of a string property, and optionally its minimum length. Value types (such as decimal, int, float, DateTime) are inherently required and don't need the [Required] attribute.

Having validation rules automatically enforced by ASP.NET helps make your app more robust. It also ensures that you can't forget to validate something and inadvertently let bad data into the database.
Notice how the form has automatically rendered an appropriate validation error message in each field containing an invalid value. The errors are enforced both client-side (using JavaScript and jQuery) and server-side (in case a user has JavaScript disabled).
You might wonder how the validation UI was generated without any updates to the code in the controller or views. The following code shows the two Create methods.
```

// GET: Movies/Create
public IActionResult Create()
{
    return View();
}

// POST: Movies/Create
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Create(
    [Bind("ID,Title,ReleaseDate,Genre,Price, Rating")] Movie movie)
{
    if (ModelState.IsValid)
    {
        _context.Add(movie);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    return View(movie);
}
```
The first (HTTP GET) Create action method displays the initial Create form. The second ([HttpPost]) version handles the form post. The second Create method (The [HttpPost] version) calls ModelState.IsValid to check whether the movie has any validation errors. Calling this method evaluates any validation attributes that have been applied to the object. If the object has validation errors, the Create method re-displays the form. If there are no errors, the method saves the new movie in the database. In our movie example, the form isn't posted to the server when there are validation errors detected on the client side; the second Create method is never called when there are client side validation errors. If you disable JavaScript in your browser, client validation is disabled and you can test the HTTP POST Create method ModelState.IsValid detecting any validation errors.

**Thanks again for the Iris. Iris It is the best framework**

**Comment by kataras** [comment]
We can't do that way because the Go language has some  limitations that you may not be aware of, i.e generics and annotations are missing from the language. You can do server-side validation using the package you sent me before, about client-side validation almost every frontend framework has a validation options and if not then I'm sure you can find a client-side javascript library that does its job better that you can do alone.
