### ISSUE TITLE
Unable to use iris-go.com

### ISSUE THREAD

**Issue by BartWillems** [kataras/iris#905]
When visiting [iris-go.com](https://iris-go.com), I get presented with this error:

``` md
# Sorry about that...
An extension caused this webpage to stop working. Please disable any extensions that might block ads to continue.
```
I'm using firefox 58, no blockers active on your page..

**Comment by kataras** [comment]
I'm using firefox 58 as well, no blockers and it works, so stop the "crap" and don't "+1" your self for the shake, star Iris before propaganda at least...
