### ISSUE TITLE
Unable to use iris-go.com

### ISSUE THREAD

**Issue by BramVer** [kataras/iris#906]
I am unable to use the [iris-go website](https://iris-go.com/) on Firefox because it keeps telling me I am running some sort of adblocker (strange reason to block access to the site in the first place).

I am running Firefox 59.0 and have only had this issue with the iris-go website.
![image](https://user-images.githubusercontent.com/16743200/36195769-e14864c6-116e-11e8-9739-b01bda0fca08.png)

As you can see I listed all of my extensions where uBlock Origin is the only adblocker I run and even that is disabled. I try this in Firefox Private mode where all extensions are turned off by default as well, and still the same issue. It shows for half a second or so and then blocks the rest of the page.
What's happening?

![image](https://user-images.githubusercontent.com/16743200/36195540-1596f9e6-116e-11e8-82d6-46ff1713e1a6.png)

**Comment by BartWillems** [comment]
🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔  I too have this issue!!! 🤔 🤔 🤔

**Comment by Zeno-Code** [comment]
I think it is because logo.png is too big
![qq 20180214182348](https://user-images.githubusercontent.com/25820304/36199357-4d6f4e04-11b4-11e8-8260-bc92dc518e75.jpg)

**Comment by kataras** [comment]
Hmm thats strange, does anyone has this issue too? Because I tested it and everybody I asked say that everything runs smoothly. About the ads, when you dont donate that happens, i dont prefer this way too, you are not the only one but all of us.

**Comment by BartWillems** [comment]
Boooooooooooo 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 👎 😡 😡 😡 😡 😡 😡

**Comment by BramVer** [comment]
@kataras Three people who I've shown this to, confirm the same issue on firefox, very strange that you don't experience an issue with that.
Also, are you saying I have to pay in order to use your website? Donating isn't even possible without access to the website 🤔

**Comment by el-davo** [comment]
I can get to the website, but this page is completely unusable - https://iris-go.com/v10/recipe. It seems to be full of adds and causes my computer to hang, cant scroll cant click any of the links

**Comment by kataras** [comment]
@el-davo it's fixed, please retry clear ur cache i am in travel now
