### ISSUE TITLE
ctx.View optionalViewModel should merged with existed viewData

### ISSUE THREAD

**Issue by syklevin** [kataras/iris#908]
During call ctx.View() func and passing a iris.Map as optionalViewModel, then this bindingData would be used directly into render view.

My user case is, i have a middleware set SEO fields such as title, meta keywords, etc into ctx.ViewData() which are the default values used in all views; and these viewData could be merged with optionalViewModel set in each route handle func.

Thanks

**Comment by kataras** [comment]
Hello @syklevin you can already do it by receiving the view data passed on previous handlers via `ctxGetViewData()` which returns a `map[string]interface{}`, add your values to that map and pass it into your main `ctx.View`, tell me your thoughts (if we do something for merged as you suggested we will slow the function but we can always make a new one for your needs if my suggestion doesn't work for you)

**Comment by kataras** [comment]
Hello @syklevin you can already do it by receiving the view data passed on previous handlers via `ctx.GetViewData()` which returns a `map[string]interface{}`, add your values to that map and pass it into your main `ctx.View`, tell me your thoughts (if we do something for merged as you suggested we will slow the function but we can always make a new one for your needs if my suggestion doesn't work for you).

Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @syklevin you can already do it by receiving the view data passed on previous handlers via `ctx.GetViewData()` which returns a `map[string]interface{}`, add your values to that map and pass it into your main `ctx.View`, tell me your thoughts (if we do something for merged as you suggested we will break the existing applications and we don't want that, right? But we can always make a new one for your needs if my suggestion doesn't work for you).

Thanks,
Gerasimos Maropoulos

**Comment by syklevin** [comment]
Thank you for the quick reply and the suggestion. I just lose sight of the ctx.GetViewData() func which could get works done.

I totally agree with you that we shouldn't make unnecessary API & behavior changes, thus I suggest the way to minimize impact. it just got some extra fields didn't need in the views, but would not break the existing applications.

A little bit confusing me is that if I don't pass optional viewData, I could got the existed data, but i loss it when passing extra viewData into a view. I just wonder if merged with existed data is a more idiomatic way.

Thanks again for the great library, I learn a lot from this and love it.
