### ISSUE TITLE
How to get the template file syntax error message?

### ISSUE THREAD

**Issue by dxvgef** [kataras/iris#91]
I customize the Logger, but I don't know how to get the error details of the the Iris 500 error from iris.Context.
And I can't catch render's error by iris.OnError().
Thank you for your work!

**Comment by kataras** [comment]
Hello @dxvgef , thanks for your interest, you can refer [here](https://github.com/kataras/iris/issues/86), if you don't find your answer post again, thanks!

**Comment by dxvgef** [comment]
Hi @kataras , thanks for your help, I have read this document, but only about 404 errors, I hope to catch the details of the 500 error and render's error in Iris.Error ().

**Comment by dxvgef** [comment]
Hi @kataras Do you have plans to support this feature?

**Comment by kataras** [comment]
@dxvgef  Hello, can you tell me  if that works? (it should works)
```go

package main

import (
	"github.com/kataras/iris"
)

func main() {

	iris.OnError(iris.StatusInternalServerError, func(ctx *iris.Context) {
		ctx.Write(iris.StatusText(iris.StatusInternalServerError)) // Outputs: Not Found
		ctx.SetStatusCode(iris.StatusInternalServerError)          // 404
		iris.Logger().Printf("http status: 500 happened!")
	})

	iris.OnError(iris.StatusNotFound, func(ctx *iris.Context) {
		ctx.Write(iris.StatusText(iris.StatusNotFound)) // Outputs: Internal Server Error
		ctx.SetStatusCode(iris.StatusNotFound)          // 500

		iris.Logger().Printf("http status: 404 happened!")
	})

	// emit the errors to test them
	iris.Get("/500", func(ctx *iris.Context) {
		ctx.EmitError(iris.StatusInternalServerError) // ctx.Panic()
	})

	iris.Get("/404", func(ctx *iris.Context) {
		ctx.EmitError(iris.StatusNotFound) // ctx.NotFound()
	})

	println("Server is running at: 80")
	iris.Listen(":80")

}


```
> If I don't understand your question, please provide more information about it

**Comment by dxvgef** [comment]
I want to get detailed error information presented in iris.OnError function in the template file, but an error rendering template file, it will not throw any errors

**Comment by dxvgef** [comment]
@kataras , When the process starts, change the template file into the wrong syntax {{test}}, console output panic information "test", but I can not get this information in iris.OnError function, I want to record it to a log file for tracking error.
Thank you for your work and help me!
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{{test}}
</body>
</html>
```

**Comment by kataras** [comment]
To take render's errors you do
```go
... func(ctx* iris.Context){
 err := ctx.Render("mypage",nil)
 if err != nil {
    println(err.Error())
 }
}
```

You can do it by making a middleware which will run after the handler and check if the body has http 200 status or not, and printout the body which is the render's error on these sittuations. 

Why you closed the issue did you find a working solution for you?

**Comment by dxvgef** [comment]
@kataras ctx.html () function if rendering the template file with the wrong syntax, will trigger the panic, will not return to error, so I can not record the value of this error type.
I'm going to write a more detailed issue.

**Comment by kataras** [comment]
No, wait I will give you a solution on 2 minutes.

**Comment by dxvgef** [comment]
@kataras Ok, thank's

**Comment by kataras** [comment]
Man I show the code again, it returns an error on `ExecuteTemplate` please look again

**Comment by kataras** [comment]
But the panic is here: https://github.com/kataras/iris/blob/development/render/render.go#L199 on loading templates, you want to return an error ? why? the templates are loading BEFORE server's run, so you should get panics not errors..

**Comment by dxvgef** [comment]
First, I started the process of iris ready to render a template file:
``` go
type Index struct{}

func (this *Index) Main(ctx *iris.Context) {
	log.Println("executed hander")
	tplFile := "index"
	tplData := make(map[string]interface{})
	ctx.HTML(200, tplFile, tplData)
}
```

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

</body>
</html>
```

Now, I change the code template file, written into the error code:
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{{test}}
</body>
</html>
``` html

When the request again, it will trigger panic, does not return error variable type,
And iris.OnError () function does not catch the exception.
More seriously, this Main() function will perform multiple, causing panic but also trigger many times.
The Main() function will be executed multiple times, also triggers many times panic, you can see the output "executed handler"

**Comment by kataras** [comment]
And you get the panic before server starts, right?

**Comment by dxvgef** [comment]
@kataras No, I started to change after the template file

**Comment by kataras** [comment]
```go
// main.go
package main

import (
	"github.com/kataras/iris"
)

type mypage struct {
	Title   string
	Message string
}

func main() {
	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("mypage", mypage{"My Page title", "Hello world!"}) 
	})

	iris.Listen(":8080")
}

```

```html
<!-- templates/layout.html -->
<html>
  <head>
    <title>My Layout</title>

  </head>
  <body>
    <!-- Render the current template here -->
    {{ yield }}
  </body>
</html>

```

And this here is the error on **Title**
```html
<!-- mypage.html -->
<h1> Title: {{Title}} <h1> 
<h3> Message : {{.Message}} </h3>


```

Outputs BEFORE server's run:
```
panic: template: mypage:1: function "Title" not defined
oroutine 1 [running]:
panic(0x8f2000, 0xc082138430)
	C:/Go/src/runtime/panic.go:464 +0x3f4.....
```

What else do you do and it doesn't panics before server's run ?

**Comment by dxvgef** [comment]
It triggers panic before the service is running, but I was running after the service changed the template file

**Comment by kataras** [comment]
Aaa you change the file when the server is running, this is wrong. You should turn off the IsDevelopment config. This template system is not created to catch compilation errors and return them as normal errors

```go
iris.Config().Render.IsDevelopment = false
```

**Comment by dxvgef** [comment]
Before running Service:
``` go
func main() {
	app := iris.New()
	app.Get("/", func(ctx *iris.Context) {
		log.Println("executed hander")
		ctx.HTML(200, "index", nil)
	})
	var renderOptions iris.RenderConfig
	renderOptions.IsDevelopment = true
	app.SetRenderConfig(&renderOptions)
	app.Listen(":9090")
}
```

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

</body>
</html>
```

After the service is running，
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{{call test}}
</body>
</html>
```

**Comment by kataras** [comment]
Note that you could just do that: ` app.Config.Render.IsDevelopment = true` . Turn off this option to disable compilation when the server is running.

**Comment by dxvgef** [comment]
Ok, this parameter can be set to false to avoid this problem, but inconvenience debugging when developing a template file, every time I change the template file need to re-run

**Comment by kataras** [comment]
Yes because of that you have the option of `app.Config.Render.IsDevelopment = true` but if you make syntax mistakes it can't simple let it continue... Previous Iris implemantation was watching the directory for changes and tried to compile them and if error happened then the template simple was't be loaded, but with the new renderer this is not hapenning, it just panics you have to be careful on html syntax

**Comment by dxvgef** [comment]
Ok, but I feel this is not convenient, I used other golang framework no such problems, they can get the template syntax errors after startup, but still thank you for the development of this project.
You can refer this project and try to reproduce the problem:
[tango](https://github.com/lunny/tango)

**Comment by kataras** [comment]
tango is not comparable with Iris man... but if you you insist I can create an option inside the RenderConfig, wait I will answer you again, please edit your comment, see their code and see iris'...  :P

**Comment by dxvgef** [comment]
@kataras I think the tango's [Recovery middleware](https://github.com/lunny/tango/wiki/Recovery) is used to solve this problem similar, you can refer to it.

**Comment by kataras** [comment]
@dxvgef  If you really see the examples you had see that Iris has [recovery middleware](https://github.com/iris-contrib/examples/blob/master/middleware_recovery/main.go)  also...

**Comment by kataras** [comment]
You can use https://github.com/iris-contrib/examples/blob/master/middleware_recovery/main.go for recovery , but I'm preparing the renderer wich it will solve your issue without need of any middleware

**Comment by dxvgef** [comment]
@kataras Great! I'm going to try this middleware!

**Comment by kataras** [comment]
@dxvgef  No need, it's ready :P  `go get -u github.com/kataras/ris ` 
now the

```go
err := ctx.HTML...
```
is working after server's run if you have `Render.IsDevelopment = true `

**Comment by dxvgef** [comment]
@kataras I appreciate your enthusiasm and rapid iteration of this project! I've used the tango, and now want to try iris, hope this project getting better and better!

**Comment by kataras** [comment]
@dxvgef  Thanks you man, I left behind all my previous part time jobs and university for Iris...  so you understand :)

**Comment by dxvgef** [comment]
@kataras My God! You're great! good luck!

**Comment by dxvgef** [comment]
@kataras I want to try to add FormValueInt () and FormValueString () function like, I can fork the project to develop these features and try to submit pull request?How to name these functions?

**Comment by kataras** [comment]
@dxvgef  It's already there by the name 'PostFormValue' https://github.com/kataras/iris/blob/development/context_request.go#L136 , it returns string, no need to have more forms of this, keep the things simple as possible.

**Comment by dxvgef** [comment]
Ok~~

**Comment by kataras** [comment]
But thanks for your interest, if you have any ideas just post it , no need to worry by yourself where and what :P
