### ISSUE TITLE
Unable to create return value of type view.Value in custom filter

### ISSUE THREAD

**Issue by neenar** [kataras/iris#912]
```go
import (
	"github.com/kataras/iris/view"
	"github.com/flosch/pongo2"
)

templates := iris.Django("./assets", ".jinja2")
templates.AddFilter("test",
	func(in *view.Value, param *view.Value) (out *view.Value, err *view.Error) {
		out = (*view.Value)(pongo2.AsValue("test"))
		return
	},
)
```
doesn't work because of: `cannot convert "github.com/flosch/pongo2".AsValue("test") (type *"github.com/flosch/pongo2".Value) to type *view.Value`.

```go
out = &view.Value{reflect.ValueOf("test"), false}
```
doesn't work because of: `implicit assignment of unexported field 'val' in view.Value literal`.

**Comment by kataras** [comment]
`view.AsValue` && `view.AsSafeValue`  added by @neenar at: https://github.com/kataras/iris/pull/913
