### ISSUE TITLE
Assistance with changes (version changes)

### ISSUE THREAD

**Issue by ericreis** [kataras/iris#914]
Hello everyone,

I used to have an example project that had this code:

**main.go:**
```
package main

import (
	"github.com/ericreis/script-runner/server/controllers"
	"github.com/ericreis/script-runner/server/services"
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")

	scriptService := services.NewScriptService()

	app.Controller(
		"/api/script",
		new(controllers.ScriptController),
		scriptService,
	)

	app.Run(
		iris.Addr("localhost:8080"),
		iris.WithoutVersionChecker,
		iris.WithoutServerError(iris.ErrServerClosed),
		iris.WithOptimizations,
	)
}
```

**script_controller.go:**
```
package controllers

import (
	"github.com/ericreis/script-runner/server/models"
	"github.com/ericreis/script-runner/server/services"
	"github.com/kataras/iris"
)

// ScriptController is the /api/script controller
type ScriptController struct {
	iris.C
	ScriptService services.ScriptService
}

// Get return a list of all the scripts
// [GET] /api/script/
func (c *ScriptController) Get() (msg string) {
	return "GET ALL SCRIPTS"
}

// PostNew creates a new script
// [POST] /api/script/new
func (c *ScriptController) PostNew() (script models.Script) {
	err := c.Ctx.ReadJSON(&script)
	if err != nil {
		c.Ctx.StatusCode(400)
	}
	c.ScriptService.CreateScript(&script)
	return script
}
```

I updated iris to version 10.2.1 and it stopped working (unfortunately I can't remember which version I was using when I made this). I think that the changes were:

- iris.C changed for Ctx iris.Context
- changes to app.Controller(...) method since I am receiving this error: app.Controller undefined (type *iris.Application has no field or method Controller)

I searched in the examples but I haven't managed to find an example that match the code above. I was wondering if someone could help me understand the changes that were made that made this stopped working in order for me to write a new example that works in this version.

**Comment by kataras** [comment]
You had version 8, there are couple of things changed in version 10, which are described (as always) with examples, old and new and some images, so it's very easy to convert your old code with find and replace.

Read here: https://github.com/kataras/iris/blob/master/HISTORY.md#mo-01-january-2018--v1000

**Comment by ericreis** [comment]
Thank you so much @kataras. I knew there was an example somewhere because the iris documentation is one of the best (if not the best) documentation I've seen. I managed to look at the example you mentioned but I couldn't realize that it has the same behavior as my example. Thank you so much for the quick reply.
