### ISSUE TITLE
Ratelimiting?

### ISSUE THREAD

**Issue by sinnlosername** [kataras/iris#915]
Hi!

Is there a ratelimit for iris? If not, could you add one?

**Comment by kataras** [comment]
Hello @sinnlosername, of course we have an example of ratelimiting and for almost every thing you will ever need with Iris + Go :P It's located at [_examples/experimental-handlers/tollboothic/limit-handler](https://github.com/kataras/iris/blob/master/_examples/experimental-handlers/tollboothic/limit-handler/main.go)!

-----

Happy coding!
