### ISSUE TITLE
Set default hostname to work on long subdomains like sub2.sub1.domain.com

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#916]
Hi,

i have the problem that i have a host like `sub2.sub1.domain.com` and working with docker but that does not change something.

I have some subdomains like `www, profile, dl` but when i work with them 
this will not work:

```
app.SubdomainRedirect(app, www)
```

so what will the best way to do it the correct way?

**Comment by Dexus** [comment]
To make it clearer, I don't want to specify the listener with hostname, because that causes more problems.
But I would like to adjust the hostname according to the fact that it will later be reachable.

**Comment by kataras** [comment]
So the subdomains works, `app.Subdomain("sub2.sub1")` or `app.Party("sub2.sub1.")` but the `SubdomainRedirect` doesn't on your case, this function was created to help you navigating mostly between `www` and root domain and visa-versa, although it's designed and tested with mutli-subdomains redirection as well, can you post some code?

**Comment by Dexus** [comment]
Hello @kataras the problem will not only affect long subdomains, but also domains ending on ".co.uk" and other similar domains. Because the root domain here would be "co.uk". However, you don't get a FirstClass domain there but a SecondClass domain.

Here my example code:
```Go
app := iris.Default()
//routes.RegisterRoutes(app)

www := app.Subdomain("www") // <- same as app.Party("www.")
	www.Get("/", func(ctx iris.Context) {
		ctx.Writef("This will be executed.")
	})

	// www is an `iris.Party`, use it like you already know, like grouping routes.
	www.PartyFunc("/users", func(p iris.Party) { // <- same as www.Party("/users").Get(...)
		p.Get("/", func(ctx iris.Context) {
			ctx.Writef("This user will be executed.")
		})
		p.Get("/login", func(ctx iris.Context) {
			ctx.Writef("This login will be executed.")
		})
	})

	// redirects mydomain.com/%anypath% to www.mydomain.com/%anypath%.
	// First argument is the 'from' and second is the 'to/target'.
	sub1 := app.Subdomain("sub1")
	sub2 := sub1.Subdomain("sub2")
	app.SubdomainRedirect(app, www)
	app.SubdomainRedirect(sub1, www)
	app.SubdomainRedirect(sub2, www)
app.Run(iris.Addr(":80"))
```

This also does not want to work as described in the comments (original from the examples).

Because it also affects other regular domains and not only "subdomains" I would recommend to allow a configuration of the "root domain/host".

**Comment by kataras** [comment]
@Dexus the domain comes from the `address` you start the server, so if you do `iris.Addr(":80")` , the root domain is something like `localhost` or `127.0.0.1` or the ipv6 address, did you try to put the domain there, it works normally, for example on `iris-go.com, comments.iris-go.com, github.comments.iris-go.com (private)` and so on

**Comment by kataras** [comment]
@Dexus the domain comes from the `address` you start the server, so if you do `iris.Addr(":80")` , the root domain is something like `localhost` or `127.0.0.1` or the ipv6 address, did you try to put the domain there i.e `iris.Addr("example.co.uk:80")` and try again? it works normally but I am not 100% sure for that because I have to check the code and maybe I will provide an option for that if you don't do a PR until then (I'm very busy the last week so I couldn't get into this), for example the `iris-go.com, comments.iris-go.com, github.comments.iris-go.com (private)` and so on are working just fine.
