### ISSUE TITLE
DisablePathCorrection not working

### ISSUE THREAD

**Issue by ninkuhack** [kataras/iris#920]
Hi Kataras and all,
I need to handle the relative path "/products/" (method Get, not auto redirect to the path "/products"), and I read in some posts, you said we need to set DisablePathCorrection is true in configuration, then we can handle manually the paths, but it not working.
Could you or anyone help me?

**Comment by kataras** [comment]
No, docs don't say exactly that, if you search on previous question about this, you will see that it's just giving you the option to not match the `/route/`  and handle the error manually (this is different from matching the `/route/`) Iris will never match such as routes, see for example the `api.github.com` it uses the same logic, it's standard, it's wrong if you used to code your routes in other frameworks with trailing slash, see [the issue 820](https://github.com/kataras/iris/issues/820).
