### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by vincentri** [kataras/iris#922]
Hello,

I got error cors. I follow all the tutorial about iris and etc but still failed. Someone can help me?

here is my code:

package main

import (
	CO "ocean/config"
	C "ocean/controllers"
	"os"

	"github.com/kataras/iris"
	"github.com/kataras/iris/middleware/recover"

	"github.com/iris-contrib/middleware/cors"
)

func main() {
	app := iris.New()

	crs := cors.NewPartyMiddleware(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "HEAD", "POST", "PUT", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "content-type", "X-Requested-With", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization", "Screen"},
		AllowCredentials: true,
	})

	app.Use(recover.New())
	CO.Init()

	app.RegisterView(iris.HTML("./views", ".html"))
	app.StaticWeb("/", "./public")

	api := app.Party("/v1")
	api.ConfigureParty(crs)
	{
		api.Get("/booting", C.Booting)
	}

	app.Run(
		iris.Addr(os.Getenv("PORT")),
		iris.WithoutVersionChecker,
		iris.WithoutServerError(iris.ErrServerClosed),
		iris.WithOptimizations, // enables faster json serialization and more
	)
}

I use Vue Js for the client side. I insert headers value for Authorization and error but if I comment the headers value it's work. Please help me

**Comment by kataras** [comment]
Hello @vincentri , thanks for your post but this is not the place to report bugs about a middleware that **is not part of the core framework** and also it's duplicate, it posted a week ago, at the future please post them in the correct repo where you `go get` them, i.e https://github.com/iris-contrib/middleware. 

This could work by using the `WrapRouter` method instead:
```go
app.WrapRouter(cors.WrapNext(cors.Options{
	AllowedOrigins:   []string{"*"},
	AllowCredentials: true,
}))
```
as explained at the example's comment :https://github.com/iris-contrib/middleware/blob/master/cors/_example/main.go#L45  but I assume that you want it for specific routes only so you're not looking for that.

------

/ref @ZaniaDeveloper pushed a PR that promised to fix that, a week ago: https://github.com/kataras/iris/issues/884

The simplest way to "fix" that is by using a custom middleware, the only thing you want is to give access for other domains, right? Easy: 

```go
import "github.com/kataras/iris"

func main() {
    allowAllOrigins:= func(ctx iris.Context) {
	ctx.Header("Vary", "Access-Control-Request-Method")
        ctx.Header("Access-Control-Allow-Origin", "*") // <- HERE
    }

    app := iris.New()
    app.Use(allowAllOrigins)

    // your routes here
    app.Run(iris.Addr(":8080"), iris.WithOptimizations)
}
```

**Comment by vincentri** [comment]
Hello Kataras, 

Thank you for the reply. None of the above solution works.

if I use this:

app.WrapRouter(cors.WrapNext(cors.Options{
	AllowedOrigins:   []string{"*"},
	AllowCredentials: true,
}))

the result is same no Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

and if I use this

import "github.com/kataras/iris"

func main() {
    allowAllOrigins:= func(ctx iris.Context) {
	ctx.Header("Vary", "Access-Control-Request-Method")
        ctx.Header("Access-Control-Allow-Origin", "*") // <- HERE
    }

    app := iris.New()
    app.Use(allowAllOrigins)

    // your routes here
    app.Run(iris.Addr(":8080"), iris.WithOptimizations)
}

the result is blank screen..

Please Help Me!

**Comment by kataras** [comment]
@vincentri 

I added a new version of cors middleware, revert the changes maden by the "fallback handlers" made by @ZaniaDeveloper  (he didn't respond to your issue, so there was not a solution in reality, we must be responsible for features we add in Iris) so things like `ConfigureParty`, `AddFallbackHandler`, `GetFallhackStack` and `NewPartyMiddleware` are not needed **just use .Use anywhere** and it should work as expected now. I also added a new feature `Party#AllowMethods` which can clone routes on specific methods, i.e OPTIONS for preflight, please verify that something like this is working for you:

```go
package main

import (
CO "ocean/config"
C "ocean/controllers"
"os"

"github.com/kataras/iris"
"github.com/kataras/iris/middleware/recover"

"github.com/iris-contrib/middleware/cors"

)

func main() {
app := iris.New()

crs := cors.New(cors.Options{
	AllowedOrigins:   []string{"*"},
	AllowedMethods:   []string{"GET", "HEAD", "POST", "PUT", "OPTIONS"},
	AllowedHeaders:   []string{"Accept", "content-type", "X-Requested-With", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization", "Screen"},
	AllowCredentials: true,
})

app.Use(recover.New())
CO.Init()

app.RegisterView(iris.HTML("./views", ".html"))
app.StaticWeb("/", "./public")

//                     or api.Use(crs) 
api := app.Party("/v1", crs).AllowMethods(iris.MethodOptions)

api.Get("/booting", C.Booting) 

app.Run(
	iris.Addr(os.Getenv("PORT")),
	iris.WithoutVersionChecker,
	iris.WithoutServerError(iris.ErrServerClosed),
	iris.WithOptimizations, // enables faster json serialization and more
)
}

```
