### ISSUE TITLE
newbie with mvc and xorm

### ISSUE THREAD

**Issue by likebrain** [kataras/iris#923]
hey, iam new on golang and iris. 
Thanks for this awesome project :) 

I need some help to get the DependencyInjection in MVC working.
I would like to have a xorm instance inside of my Service Struct and use this Service inside of my Controllers.

Here my code:

**Main**
```golang
db := newDatabase("test:test@/testdb?charset=utf8")
repo := services.NewUserService(db)

//Controllers
myApp := mvc.Configure(app.Party("/"), registerBackendRoutes)
myApp.Register(repo)
```

**Service**
```golang
//UserService is our Interface.
type UserService interface {
	GetUserList() (map[int64]model.Mandant, error)
}

//NewUserServicereturns a new User repository
func NewUserService(db *xorm.Engine) UserService {
	return &userService{
		DB: db,
	}
}

// userService is our struct.
type userService struct {
	DB *xorm.Engine
}

//GetUserList load all Users
func (i *userService) GetUserList() (map[int64]model.User, error) {
	users := make(map[int64]model.User)
	err := i.DB.Find(&users)
	return users, err
}


```
**Controller**
```golang
// DashboardController is our controller.
type DashboardController struct {
	Service services.UserService 
}

// Get Renders the DashboardPage
func (c *DashboardController) Get() mvc.Result {
	data, _ := c.Service.GetUserList()
	fmt.Print(data)

	return mvc.View{
		Name: "be/dashboard.html",
		Data: map[string]interface{}{
			"Title":     "Hello Page",
			"MyMessage": "Welcome to my awesome website",
		},
	}
}
```
**Error**
```
[WARN] 2018/03/09 11:27 Recovered from a route's Handler('github.com/kataras/iris/mvc.(*ControllerActivator).handlerOf.func1')
At Request: 200 /dashboard GET 127.0.0.1
Trace: runtime error: invalid memory address or nil pointer dereference
```

It will crash here because c.Service is empty:
data, _ := c.Service.GetUserList()

what am I doing wrong ?

**Enviorment**
> Go: go version go1.10 linux/amd64
> Iris : 10.2.1
> Ubuntu 16.4

**Comment by likebrain** [comment]
Hey,
i found a solution :)

I was a bit confused about the following statement in the [Examples](https://github.com/kataras/iris/blob/dc589d9135295b4d080a9a91e942aacbfe5d56c5/_examples/mvc/overview/main.go#L25):

```golang
	// Serve our controllers.
	mvc.New(app.Party("/hello")).Handle(new(controllers.HelloController))
	// You can also split the code you write to configure an mvc.Application
	// using the `mvc.Configure` method, as shown below.
	mvc.Configure(app.Party("/movies"), movies)
```
I thought mvc.Configure would be enough but... 
I change my code to "New" Syntax and everything working fine:

**From**
```golang
app := iris.New()
//Controllers
myApp := mvc.Configure(app.Party("/"), registerBackendRoutes)
myApp.Register(repo)
```

**To**
```golang
app := iris.New()
//Controllers
myApp := mvc.New(app.Party("/"))
myApp.Register(repo).Configure(registerBackendRoutes)
```
but it should be the same bahvior ?

https://github.com/kataras/iris/blob/dc589d9135295b4d080a9a91e942aacbfe5d56c5/mvc/mvc.go#L69

What is my misstake ?

**Comment by kataras** [comment]
> Did I understand correctly that I have to call Register on the Parent Party.
After that i add my Child Partys. (It´s a Clone of the ParentParty with Dependencys)
If i Register after adding the Child-Partys, the Cloning is already done and the childs dont have the parent dependencys ?

Yes, children inherites the dependencies, that's the reason that an mvc application can create more mvc applications and so on and that's very important to remember, it can make your code very much better, but you can make a new "mvc application" for a children path with new dependencies, no problem at all. 

-----

I think you can code it better but I don't really understand your app's logic entirely, do you mind chat with me on the https://chat.iris-go.com? The examples provide you very good sense and different ways to work with mvc (maybe that's confused you?), we have "full examples" like the `mvc/login` and a `/tutorial` for Vue.js + MVC.
