### ISSUE TITLE
vendoring broken?

### ISSUE THREAD

**Issue by Ascendance** [kataras/iris#926]
Hello!

Today I updated my vendors folder using govendor and...

Unfortunately for Iris it came back with this: 

```
Error: Different Canonical Packages for golang.org/x/sys/unix
	github.com/kataras/iris/vendor/golang.org/x/sys/unix
	golang.org/x/sys/unix

github.com/kardianos/govendor/context.(*Context).Alter
	/Users/demonfuse/GoProjects/src/github.com/kardianos/govendor/context/modify.go:687
github.com/kardianos/govendor/run.(*runner).Modify
	/Users/demonfuse/GoProjects/src/github.com/kardianos/govendor/run/modify.go:152
github.com/kardianos/govendor/run.(*runner).run
	/Users/demonfuse/GoProjects/src/github.com/kardianos/govendor/run/run.go:98
github.com/kardianos/govendor/run.Run
	/Users/demonfuse/GoProjects/src/github.com/kardianos/govendor/run/run.go:44
main.main
	/Users/demonfuse/GoProjects/src/github.com/kardianos/govendor/main.go:35
runtime.main
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/asm_amd64.s:2337
```

The previous version of Iris worked fine. Wondering if this is an issue. 

Thanks!

**Comment by kataras** [comment]
Hmm I will investigate it right now on a remote machine, do you tried on windows or unix?

**Comment by kataras** [comment]
No, `go get -u github.com/kataras/iris` and `dep` works fine, so I'm assuming thats a problem of `govendor`, but we can try to upgrade the `golang.org/x/sys/uix` vendor and check again, are you into this?

**Comment by Ascendance** [comment]
I'm testing on macOS High Sierra but eventually it will be Unix, dockerized, Alpine with nothing but Go runtime. 

Sure. I'll see what I can do. `go get -u github.com/kataras/iris` works fine. I'm just lazy and govendoring saves me like 2 seconds.

**Comment by kataras** [comment]
OK, I'm testing manually the upgraded `golang.org/x/sys` vendor on my remote machine and if that works I push a commit here and I will ask you to retry, please stay tuned for the next 5 mins

**Comment by kataras** [comment]
OK, can you try now? (if not works then it's govendor's issue and you can try just `go get -u`, the iris' vendor is enough (it just doesn't contain the iris-contrib/httpexpect and katras/golog and protobuf that badger sessiondb is using but I will add them now, both iris-contrib/httpexpect and kataras/golog are stable now so we should be fine)

**Comment by kataras** [comment]
OK, can you try now? (if not works then it's govendor's issue and you can try just `go get -u`), the iris' vendor is enough (it just doesn't contain the iris-contrib/httpexpect and katras/golog and protobuf that badger sessiondb is using but I will add them now, both iris-contrib/httpexpect and kataras/golog are stable now so we should be fine)

**Comment by Ascendance** [comment]
Hmm.... Now I am getting a bunch of other errors. I have tried deleting the vendor folder then `govendor init` and `govendor fetch +all`. Iris comes back with cannot find packages:

```
vendor/github.com/kataras/iris/middleware/logger/logger.go:11:2: cannot find package "github.com/ryanuber/columnize" in any of:
	/go/src/github.com/Ascendance/N2X/vendor/github.com/ryanuber/columnize (vendor tree)
	/usr/local/go/src/github.com/ryanuber/columnize (from $GOROOT)
	/go/src/github.com/ryanuber/columnize (from $GOPATH)
vendor/github.com/kataras/iris/core/netutil/tcp.go:11:2: cannot find package "golang.org/x/crypto/acme/autocert" in any of:
	/go/src/github.com/Ascendance/N2X/vendor/golang.org/x/crypto/acme/autocert (vendor tree)
	/usr/local/go/src/golang.org/x/crypto/acme/autocert (from $GOROOT)
	/go/src/golang.org/x/crypto/acme/autocert (from $GOPATH)
```

**Comment by kataras** [comment]
OK if that's only two then it's easy but I can't understand, the `golang.org/x/crypto/acme/autocert` is vendored at `kataras/iris/vendor/golang.org/x/crypto/acme/autocert`, so why it shows you that?

**Comment by kataras** [comment]
My recommendation is never use tools like that, I vendor the whole iris project by myself (I made it to have a smaller size than the dep tool and relatives...) but if you have to use one then use the `github.com/golang/dep` iris has the fetch configuration for this tool in order to make it easier for `dep` users.

**Comment by Ascendance** [comment]
Yaas fixed! 💥 Apparently govendor remote fetch is _somewhat_ broken. `govendor add +external` is the only option that works... for now.

**Comment by kataras** [comment]
OK @Ascendance thank you very much for your issue report and your time, this is good, even if it's not Iris problem, other `govendor` users can see what command works
