### ISSUE TITLE
Performance tuning guidelines in a broader perspective

### ISSUE THREAD

**Issue by Puffton** [kataras/iris#933]
It might be slightly out of scope for this project, but it would be awesome with some performance tuning guidelines in a broader perspective, since this framework is so focused on performance. Especially on the backend, disregarding front-end frameworks.

For example, how to configure postgres and iris for optimal performance together; concurrent open connections relative to hardware, recommended file systems/operating systems etc. Just some pointers from the experience of developing Iris might get us Iris-newbies a long way.

Keep the great work up!

**Comment by speedwheel** [comment]
Hello @Puffton. You can check the iris code base and can some ideas from there to incorporate inside your project. Try to make the implementation by yourself and post the code here and we might come up with suggestions how to improve the code, it will be easier if you post some code that you've tried.

Just go with the standard implementation for the database that you can find in the corresponding repo and you should be just fine.

Check the examples [here](https://github.com/lib/pq/blob/master/example/listen/doc.go), this is the most popular repo for postgres in golang.

Further things that you can do to improve performance in your app:
1. Make use of ctx.Values() for storing and retrieving the session's values when multiple middlewares are involved in one request inside a route.
2. Iris uses the sync.Pool to reduce memory allocations
3. Iris uses []byte whenever it can
4. Iris pre-calculates a lot of things before server actually is up and running
5. Iris has a unique router which is based on a mix of algorithms trie for saving binary with seek parameterized and wildcards, while supports things like /static, /{parameter:string} and wildcard /{param:path} in the same time. To be honest I've never seen code like that before anywhere, you will learn a lot by looking into that
6. Iris' router's famous macro  and custom interpreter , i.e `{param:int else 500}` are pre-calculated before server ran so they run at maximum speed and they're just beautiful
7. Sessions performance is also fast, no locks involved. 
Use slice whenever you can*  look the `core/memstore` to learn how you can change a slice using its pointer for the best performance . (*if the records are millions, `map` is worth using instead, look the router again),

So Iris has already take care of most things to make everything really fast, so you can focus on your app logic.

**Comment by speedwheel** [comment]
Hello @Puffton. You can check the iris code base and grasp some ideas from there to incorporate inside your project. Try to make the implementation by yourself and post the code here and we might come up with suggestions how to improve the code, it will be easier if you post some code that you've tried.

Just go with the standard implementation for the database that you can find in the corresponding repo and you should be just fine.

Check the examples [here](https://github.com/lib/pq/blob/master/example/listen/doc.go), this is the most popular repo for postgres in golang.

Further things that you can do to improve performance in your app:
1. Make use of ctx.Values() for storing and retrieving the session's values when multiple middlewares are involved in one request inside a route.
2. Iris uses the sync.Pool to reduce memory allocations
3. Iris uses []byte whenever it can
4. Iris pre-calculates a lot of things before server actually is up and running
5. Iris has a unique router which is based on a mix of algorithms trie for saving binary with seek parameterized and wildcards, while supports things like /static, /{parameter:string} and wildcard /{param:path} in the same time. To be honest I've never seen code like that before anywhere, you will learn a lot by looking into that
6. Iris' router's famous macro  and custom interpreter , i.e `{param:int else 500}` are pre-calculated before server ran so they run at maximum speed and they're just beautiful
7. Sessions performance is also fast, no locks involved. 
Use slice whenever you can*  look the `core/memstore` to learn how you can change a slice using its pointer for the best performance . (*if the records are millions, `map` is worth using instead, look the router again),

So Iris has already take care of most things to make everything really fast, so you can focus on your app logic.

**Comment by Puffton** [comment]
Cool, thanks a lot for the extensive answer!

I guess I should provide some background: I already have a site in production using another Go framework, and I'm contemplating switching to Iris. I ditched sessions in favor of JWT for improved scalability, and I'm really just exposing a JSON REST API and serving static files, letting JavaScript do the heavy work in the front end.

What I was thinking about was, no matter how optimized Iris is, a chain is only as strong as its weakest link. I imagine the context in which Iris operates also has to be tweaked in order deliver optimum performance. For example choice of file system and db engine configuration (page size, transaction log location etc.).

It seems max_connections in postgres is 100 out of the box, and since Go 1.5 GOMAXPROCS is also set properly, so that shouldn't be a problem, but the postgres documentation also says "PostgreSQL ships with a basic configuration tuned for wide compatibility rather than performance."

What I meant was that it would be interesting to see some general pointers when it comes to assembling a "full backend stack" based on Iris. I guess Linux and an open source RDBMS is the most common combination to run with Iris? A subpar Go framework with a well tuned system will likely outperform Iris in many real world cases, just tweaking the page size in postgres to match the disk block size can improve db performance by as much as 30%.
