### ISSUE TITLE
Router fails with multiple consecutive arguments

### ISSUE THREAD

**Issue by plassa-b** [kataras/iris#940]
Hi there,

I'm on versions `10.4.0`
Just found out that some unusual routes with multiple consecutive arguments fail to match in some specific cases. I have the following main: 
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Handle("GET", "/api/v1/{resource}", func(ctx iris.Context) {
		ctx.HTML(ctx.Path())
	})
	app.Handle("GET", "/api/v1/{resource}/{id}", func(ctx iris.Context) {
		ctx.HTML(ctx.Path())
	})
	app.Handle("GET", "/api/v1/foo/{id}/bar", func(ctx iris.Context) {
		ctx.HTML(ctx.Path())
	})
	app.Run(iris.Addr(":8080"))
	return
}
```

Then, when I do a GET request on `/api/v1/foo` I get a `/api/v1/foo`, which is correct.

When I do a GET on `/api/v1/foo/id/bar` I get a `/api/v1/foo/id/bar` which is correct too.

But when I do a GET on `/api/v1/foo/id` I get a `Not found` where I should have a match with `/api/v1/{resource}/{id}`

Note that if I remove the third handle, the route `/api/v1/{resource}/{id}` works correctly, which lets me think there is some kind of conflict between the both of them.

**Comment by kataras** [comment]
Yes, something like `http://localhost:8080/api/v1/hey/hi` works but `foo/id` no, you have to use `wildcards` this is not a bug.

**Comment by joselfr** [comment]
Hi,

Still don't understand why the example code doesn't work.

`/api/v1/foo/id` should match:

```
	app.Handle("GET", "/api/v1/{resource}/{id}", func(ctx iris.Context) {
		ctx.HTML(ctx.Path())
	})
```

**Comment by plassa-b** [comment]
@kataras Could you take a second look ?
