### ISSUE TITLE
How can i add Cache-Control haader to static files.

### ISSUE THREAD

**Issue by turkishdeveloper** [kataras/iris#941]
I am trying to add Cache-Control header to static files. How can i do this. İ didnt see in the documents. I am using this code for serving static files. 

// Static files serving...
app.Favicon("server/public", "/home/")
app.StaticWeb("server/public", "/home/")

**Comment by kataras** [comment]
We have a `github.com/kataras/iris/cache` package for this, for StaticCache (with `Cache-Control` header) you can see the `cache.StaticCache` function there: https://github.com/kataras/iris/blob/master/cache/browser.go#L56
