### ISSUE TITLE
Third party socket.io

### ISSUE THREAD

**Issue by khaydarov** [kataras/iris#942]
Hi there!

There is a problem with socket.io connection. I cloned whole example from documentation to test it, and it seem that it is doesn't work

```
WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=3&transport=websocket&sid=uI17afcUXrTNwb8nPsUR' failed: Error during WebSocket handshake: Unexpected response code: 301
```

I don't know how to figure it out. Any ideas? Thank you!

**Comment by kataras** [comment]
This is socket.io thing but this is **expected log there**, the example works fine, the chat works without connection errors. This happens because of the permant redirection of the socket.io's payload. Test it and you'll see :)
