### ISSUE TITLE
Go dep, Iris and updates

### ISSUE THREAD

**Issue by Puffton** [kataras/iris#943]
An excerpt from when I start Iris:
? A new version is available online[10.5.0 > 10.4.0]. Type '?' for help.
? A new version is available online[10.5.0 > 10.4.0]. Type '?' for help.
Release notes: https://github.com/kataras/iris/blob/master/HISTORY.md#sa-24-march-2018--v1050.
Update now? Yes

1. The first line is printed twice.

2. In the case that go dep is used in the project, Iris disregards it, effectively installing duplicate dependencies. An alternative could be to look for a "Gopkg.toml"-file, modify it and "dep ensure"? Or disable automatic updates when this file is available.

EDIT:

3. That the updater triggers is no guarantee that the update is available yet. The 10.5.0 update is not available on "go dep" for example, but is available using Iris own system.

**Comment by kataras** [comment]
The Iris' update works as expected because it works with `go get`, the `dep` doesn't because it works with git releases and trees, the `v10.5.0` doesn't have any of them this is why you can't update to v10.5.0 from `dep` but that should be fixed now that I added the current version to the [releases](https://github.com/kataras/iris/releases). Could you please try again?

**Comment by kataras** [comment]
About the doublicate line, it doesn't show to me neither to some servers that I manage of, can you please screenshot and post here? It's nothing but it's good to fix it.

**Comment by kataras** [comment]
About the duplicated line, it doesn't show to me neither to some servers that I manage of, @Puffton  can you please screenshot and post here? It's nothing but it's good to fix it.

**Comment by Puffton** [comment]
I'm in the middle of my migration to Iris and I must have changed something, because I can't reproduce the double lines error. The text in my first post is copied straight from the terminal, so I'm quite sure it was there last night.

Yeah, a duplicate line is a minor thing, I just thought it could be that underlying code was running twice, which could potentially be non-minor. Anyhow, the Iris code is completely unchanged, so it must have been something in my own code that provoked it (possibly a bug in my code or an unexpected use-case in Iris). Will let you know if it happens again.

**Comment by kataras** [comment]
OK, closing for now post if you find anything new, thank you a lot @Puffton for your time
