### ISSUE TITLE
In the Simple Server example code has some error

### ISSUE THREAD

**Issue by brookxs** [kataras/iris#947]
In the version 10.5.0
when I build the main.go, there has some error found
```shell
# command-line-arguments
./main.go:17: undefined: iris.Context
./main.go:21: undefined: iris.Context
./main.go:25: undefined: iris.Context
./main.go:26: undefined: iris.Map
```

I check the source code iris.go and not found yet. I find it in the package context, so I use `context.Context` and `context.Map` instead. 
I build again, It work.

**Comment by brookxs** [comment]
I got it through FAQ, the go version must greater than 1.9.

**Comment by kataras** [comment]
Exactly, you can use 1.9 as well but you should consider the aliases used in the examples and in the docs, go >= 1.9  is recommended.
