### ISSUE TITLE
how to pass orm to controllers / models

### ISSUE THREAD

**Issue by syssam** [kataras/iris#949]
Do Iris  provide some method to pass orm to controllers / models, like Session *sessions.Session dependency function ?
Or I need write a function to create it.

**Comment by kataras** [comment]
There is an example of that exactly you're asking for but you don't need example, you can bind anything you find useful for your web controller: https://github.com/kataras/iris/tree/master/_examples/mvc/session-controller

**Comment by syssam** [comment]
Yes, I found this example, however, how can I bind something on outside of the controller?

**Comment by kataras** [comment]
what do you mean by "binding something on outside of the controller"? Could you please provide a code-snippet of your idea?

**Comment by syssam** [comment]
Sorry, I miss it.
Like a  DI, a service Provider, I can register some service and get registered service from the DI container.
When I call the get registered service, it will be call the init method, if the service have not call before.

**Comment by kataras** [comment]
You do it with the `Register`, each mvc iris app/group contains its own DI container and a shared one (which is the `hero.Register`).


Look https://github.com/kataras/iris/blob/master/_examples/mvc/login/main.go#L56 on how to register a service i.e a `UserService`, which is binding to the `UserController` at: https://github.com/kataras/iris/blob/master/_examples/mvc/login/web/controllers/user_controller.go#L32 (interface, iris is smart enough to match a value with a struct field which expects an interface of)
