### ISSUE TITLE
route is not found when method is empty for using the native http.Handler

### ISSUE THREAD

**Issue by cxjava** [kataras/iris#95]
when I read the chapter [Using native http.Handler](https://kataras.gitbooks.io/iris/content/using-native-httphandler.html), I follow the example, and write the code like below:
```go
package main

import (
	"net/http"

	"github.com/kataras/iris"
)

func main() {
	//"" means ANY(GET,POST,PUT,DELETE and so on)
	iris.Handle("", "/path", iris.ToHandler(nativehandler{}))
	// works fine for this line
	// iris.Handle("GET", "/path", iris.ToHandler(nativehandler{}))

	iris.Listen(":8080")
}

type nativehandler struct{}

func (_ nativehandler) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	res.Write([]byte("hi"))
}
```
The expect response from the **http://127.0.0.1:8080/path** for method **GET** is **hi**, but actually is **404 not found**, Is it a bug? or I misunderstood the sentence "//"" means ANY(GET,POST,PUT,DELETE and so on)"

I am using the newest version of Iris.

**Comment by kataras** [comment]
It was this way but after version v2, this changed. I see that you need it or docs for native handler are old, anyway this is reimplemented (fixed) now :)
