### ISSUE TITLE
html question

### ISSUE THREAD

**Issue by 727023460** [kataras/iris#955]
I get lots of rows , how to show it in web
other language can get rows and  in html file use for  to  traversal 

I want to see the value of a where  in 
```
func greet(ctx iris.Context) {
	a : = 5
}
```
how to print it

**Comment by kataras** [comment]
@727023460 These all are explained in the [_examples](_examples) folder, please take a look them, Iris contains a lot of examples, as far as we know we have so many examples that no other any go library hosted in github has so far. It's sad that I have to answer to the same questions every single time.

I quite don't understand either, you mean print via html template(ctx.ViewData(key, value) and ctx.View(templateFilename)) or print via html text(ctx.HTML) or print via raw string (ctx.Writef) ?
