### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by turkishdeveloper** [kataras/iris#957]
Hi,

I have been using your system for about 1-2 months and you have done a great job. But it is easy to get lost among the documents. In addition, documentation is missing in many places. But still I love this project.

I think it should be possible to build a previously rendered structure for the view. For example, I want to develop a project for 5 different countries in 2 different languages. I have one template file. Now I can easily render them with ctx.View.  However, I only want to render them once and transfer them to ram, and then I want to send from ram. 

It must be easy but i dont know how can i do this.

**Comment by kataras** [comment]
Hello @turkishdeveloper and welcome!

If it's not a problem could you please point us what is not documented so we can contribute to it? Every exporter function or struct contains godoc comments, every feature that I remember contains examples :P 

Apart from that, your feature request is already implemented inside Iris, you want embedded templates(template files into ram, not in files), this can be already done using the `view#Binary(Asset, AssetNames)` example scan be found at [_examples/view/embedding-templates-into-app](https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app).

**Comment by kataras** [comment]
Hello @turkishdeveloper and welcome!

If it's not a problem could you please point us what is not documented so we can contribute to it? Every exported function or struct contains godoc comments, every feature (that I remember:P) contains examples as well.

Apart from that, (I think(?)) your feature request is already implemented inside Iris, you want embedded templates(template files into ram, not in files), this can be already done using the `view#Binary(Asset, AssetNames)` examples can be found at [_examples/view/embedding-templates-into-app](https://github.com/kataras/iris/tree/master/_examples/view/embedding-templates-into-app).

Please try this solution and tell me if that works for you or what I can do to help you instead, thank you for power-up your projects using the Iris web framework, we all do!

**Comment by Puffton** [comment]
iris.WithOptimizations is described very briefly. I missed the rationale behind introduction the option (as opposed to always enabling optimizations) as well as potential drawbacks I could face if I did enable them.
