### ISSUE TITLE
Route handler error handling

### ISSUE THREAD

**Issue by Puffton** [kataras/iris#960]
I really like the error handling in route handlers in Echo (https://github.com/labstack/echo), the framework I migrated from.

The route handler itself returns the error, which is handled within the framework. The error struct could be extended to include the http error code as well.

So rather than, for example:
```go
c.Values().Set("error", err.Error())
c.StatusCode(http.StatusInternalServerError)
return
```

You would have:
```go
return iris.NewError(http.StatusInternalServerError, err.Error())
```

Is the current way better in terms of performance, or?

**Comment by kataras** [comment]
You can already do that... what do you like from echo are you going to drive me crazy?

**Comment by kataras** [comment]
About your questions @Puffton :

Yes it has performance cost of course and echo's do it with a heavy way that not need at all but they do it like they learnt, in Iris you can return and **accept** values with the `hero` feature which is a lot faster than anything else development in Go for web so far, see [_examples/README.md](https://github.com/kataras/iris/tree/master/_examples).  But normal iris handlers can't do that of course, you manage the data sent, not "magic behind the scenes", if you like magic go with the Iris `mvc` and `hero handlers` instead.
