### ISSUE TITLE
Is there any method to get all http headers dump or get the raw http header like http.Request

### ISSUE THREAD

**Issue by robert-li-sphinx** [kataras/iris#967]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

I have some thing to debug on server side, which is written in iris and golang.
now, i have some strange request to debug, and i need to dump to see the all headers of one http request. So, as the best web framework , does iris have some method to easily dump the headers ?

**Comment by kataras** [comment]
Headers are just [map[string][]string underline]((https://golang.org/pkg/net/http/#Header), so you can use the `ctx.Request().Header` to print those somewhere, no special knowedge needed here, just print them like a normal `map`, you can even use the `fmt.Spritnf` method.

**Comment by kataras** [comment]
Headers are just [map[string][]string underline](https://golang.org/pkg/net/http/#Header), so you can use the `ctx.Request().Header` to print those somewhere, no special knowedge needed here, just print them like a normal `map`, you can even use the `fmt.Spritnf` method.

**Comment by kataras** [comment]
Headers are just [map[string][]string underline](https://golang.org/pkg/net/http/#Header), so you can use the `ctx.Request().Header` to print those somewhere, no special knowedge needed here, just print/store them like a normal `map`, you can even use the `fmt.Sprintf` method.

**Comment by robert-li-sphinx** [comment]
Great! Maybe we can add this info into the document: https://iris-go.com/v10/recipe? Just for someone else  like me. Because before issues this issue, I didn't found this info in the document .

**Comment by kataras** [comment]
Nice that helped you @robert-li-sphinx , actually it's already here: https://github.com/kataras/iris/tree/master/_examples#how-to-read-from-contextrequest-httprequest (look the tip, it also exist as a comment on the examples theirselves) but we can add it anywhere you like if you think that these are not enough

**Comment by robert-li-sphinx** [comment]
as an iris usage info, I think we should add this document into the recipe, which is though as an central knowledge base.
