### ISSUE TITLE
Does websocket server side use heartbeat to find client still online?

### ISSUE THREAD

**Issue by loveumore** [kataras/iris#970]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples/websocket>.

Does websocket server side use heartbeat to find client still online? If so, what's the time interval and deadline?

**Comment by kataras** [comment]
Hearbeat is used to make the http connection "alive" and not dead, this is not implemented inside the library but you can do it manually, i.e send every 20 seconds an empty message to the client, nothing more, it's easy.

**Comment by kataras** [comment]
If client is offline, server is notified by the `conn.OnDisconnect`, this event is fired on manual disconnection or network issue, so you are ok with the "client still online" thing you asked for.
