### ISSUE TITLE
Your still have problem described here: #956

### ISSUE THREAD

**Issue by MegaGamesUkraine** [kataras/iris#971]
It is not about my code, it is about CORE iris code.

So HTMLEngine.ExecuteWriter is called PER REQUEST.

Here is HTMLEngine.ExecuteWriter body:
`
func (s *HTMLEngine) ExecuteWriter(w io.Writer..., bindingData interface{}) error {
	...
	if layout != "" {
		s.layoutFuncsFor(name, bindingData)
		name = layout
	} else {
		s.runtimeFuncsFor(name, bindingData)
	}

	return s.Templates.ExecuteTemplate(w, name, bindingData)
}
`

So on EVERY REQUEST you get HTMLEngine.layoutFuncsFor or HTMLEngine.runtimeFuncsFor call.
So, at least you update "render" implementation with bindingData in the closure:

`
"render": func(fullPartialName string) (template.HTML, error) {
buf, err := s.executeTemplateBuf(fullPartialName, >>>>binding<<<<)
return template.HTML(buf.String()), err
},
`

So the function list is persist. but function implementation (and come context data in closure) is not.

**Comment by kataras** [comment]
You wrote that issue for the second time, meanwhile I told you that it's fine, we need the `binding` on those functions, they are dynamic, they must be initialized on every request for the specific template and binding data, iris renders templates faster than any other alternative.

Please @MegaGamesUkraine push a PR if you think that we have a problem here, I think not.

5 days and still nothing from your side, closed, there is not actual issue.
