### ISSUE TITLE
iris.WithPostMaxMemory(10<<20) 不起作用

### ISSUE THREAD

**Issue by ciyool** [kataras/iris#979]
app.Run(iris.Addr(":8080"), iris.WithPostMaxMemory(10<<20))
使用了这样的配置，但是仍旧可以上传超过10MB的文件，尝试了上传大于100MB，可以上传成功。

**Comment by motecshine** [comment]
@kataras  `iris.WithPostMaxMemory(10<<20)` dosent  take effect

**Comment by kataras** [comment]
Thanks for the translation @motecshine!!

@ciyool , can you try this example: https://github.com/kataras/iris/blob/master/_examples/http_request/upload-file/main.go#L72 and tell me if works for you or no? I've tested it and it works, so perhaps you can share your code snippet with us?

**Comment by 727023460** [comment]
i have try your  example , dosent take effect  too

**Comment by ciyool** [comment]
@kataras 
I tried https://github.com/kataras/iris/blob/master/_examples/http_request/upload-file/main.go#L72，dosent take effect too.
pc OS : windows 7 Ultimate, x64
golang version : go version go1.10.1 windows/amd64

**Comment by kataras** [comment]
@727023460 @ciyool Yes, you have to use the ` iris.LimitRequestBodySize(maxSize)` middleware or `ctx.SetMaxRequestBodySize(maxSIze)`

```go
maxSize := 10 << 20

// Handle the post request from the upload_form.html to the server
	app.Post("/upload", iris.LimitRequestBodySize(maxSize), func(ctx iris.Context) {
		// Get the file from the request.
		file, info, err := ctx.FormFile("uploadfile")

		if err != nil {
			ctx.StatusCode(iris.StatusInternalServerError)
			ctx.HTML("Error while uploading: <b>" + err.Error() + "</b>")
			return
		}

		defer file.Close()
		fname := info.Filename

		// Create a file with the same name
		// assuming that you have a folder named 'uploads'
		out, err := os.OpenFile("./uploads/"+fname,
			os.O_WRONLY|os.O_CREATE, 0666)

		if err != nil {
			ctx.StatusCode(iris.StatusInternalServerError)
			ctx.HTML("Error while uploading: <b>" + err.Error() + "</b>")
			return
		}
		defer out.Close()

		io.Copy(out, file)
})

app.Run(iris.Addr(":8080"), iris.WithPostMaxMemory(maxSize))
```

Another solution is to check if the client sent the file request with a `Content-Length` header, extract it, check the value manually and fire a custom error, and if the client didn't send the header `Content-Length` then make sure that it will not send more data than you can accept using the `ctx.SetMaxRequestBodySize` (this will throw "reset connection" on most clients, so you don't have the chance to write a custom error message). You can also add a check on client-side using javascript before send the file.

I'll update the example and I'll add a built'n function to check the "Content-Length" to make your life even easier :)
