### ISSUE TITLE
Has deleted cors.WrapNext?

### ISSUE THREAD

**Issue by ByLuxury** [kataras/iris#989]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
Hey @ByLuxury, please post issues relative to their repository,  this question should belong to the [iris-contrib/middleware](https://github.com/iris-contrib/middleware).  Yes this was changed a long time ago by ago, its [example](https://github.com/iris-contrib/middleware/blob/master/cors/_example/main.go#L17) was also updated, it it's just a middleware now with `Party#AllowMethods(iris.MethodOptions)` helper.
