### ISSUE TITLE
Render partials lookup seems based on the view rather than layout

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#99]
After doing a bit of testing, it looks like the partial lookup seems to be based on the view instead of the layout.

Attempt one - default layout, rendering view my/dashboard:
`template: layouts/default:399:2: executing "layouts/default" at <yield>: error calling yield: template: my/dashboard:4:2: executing "my/dashboard" at <partial "sidebar">: error calling partial: html/template: "sidebar-my/dashboard" is undefined`

Attempt two - default layout, rendering view my/profile:
`template: layouts/default:399:2: executing "layouts/default" at <yield>: error calling yield: template: my/profile:18:2: executing "my/profile" at <partial "sidebar">: error calling partial: html/template: "sidebar-my/profile" is undefined`

Attempt three - public layout, rendering view public/login:
`template: layouts/public:36:3: executing "layouts/public" at <yield>: error calling yield: template: public/login:3:2: executing "public/login" at <partial "sidebar">: error calling partial: html/template: "sidebar-public/login" is undefined`

**Comment by kataras** [comment]
Iris' renderer is based on html/template nothing more (for now). Can you explain it better with code snippets or make a pull request to the [iris-contrib/examples](https://github.com/iris-contrib/examples) in order to solve this together?

**Comment by ryanbyyc** [comment]
Consider the following handler and view (template):

```go
func (homeGetHandler) Serve(c *iris.Context) {
	c.Render("public/home", nil, iris.HTMLOptions{Layout: "layouts/public"})
}
```
```html
{{partial "sidebar"}}
<ul>
  <li><a href="/register">Register</a></li>
  <li><a href="/login">Login</a></li>
</ul>
```

Right now, the error returned is `template: layouts/public:36:3: executing "layouts/public" at <yield>: error calling yield: template: public/home:3:2: executing "public/home" at <partial "sidebar">: error calling partial: html/template: "sidebar-public/home" is undefined`

It appears that it is looking for the template which in this case is `fullPartialName := fmt.Sprintf("%s-%s", partialName, name)` https://github.com/kataras/iris/blob/development/render/render.go#L305

What I am looking for is a way to lookup partials based on the **layout** instead of the template. For instance, a new layout Func that looks in the layouts rather than the templates.

Something like: `{{ LayoutPartial "sidebar" }}` which would render `layouts/sidebar-public.html` instead of `sidebar-public/home`

**Comment by kataras** [comment]
I'm not sure if I understand it well, I don't know why, you have a ./templates/layouts/public.html and the public/home.html, inside your ./templates/layouts/public.html you have the {{partial "sidebar" }} and {{ yield }} (for ./templates/public/home.html) right?

**Comment by ryanbyyc** [comment]
That's just my Renderconfig:
```language:go
&iris.RenderConfig{
			Directory:  "app/web/views",
			Asset:      nil,
			AssetNames: nil,
			Layout:     "layouts/default",
			Extensions: []string{".html"},
			Funcs: []template.FuncMap{
				template.FuncMap{"user": users.User},
				template.FuncMap{"profilelink": users.ProfileLink},
			}
```

This allows for view structures such as:
app/web/views/**layouts**/default.html
app/web/views/**layouts**/public.html
app/web/views/**layouts**/sidebar-default.html
app/web/views/**layouts**/sidebar-public.html
app/web/views/**layouts**/css-public.html
app/web/views/**layouts**/css-default.html

My views are located such as:
app/web/views/**public**/home.html
app/web/views/**public**/register.html
app/web/views/**public**/login.html
app/web/views/**groups**/home.html
app/web/views/**events**/home.html
app/web/views/**events**/create.html

What I need is a layout function to look in "layouts".

**Comment by kataras** [comment]
The problem is that if you  put this code you wrote in the `RenderConfig.Funcs` isn't working as expected?

**Comment by ryanbyyc** [comment]
My thanks! Now that the new `{{ render "..." }}` func exists, this has satisfied my needs.

Examples can be seen here: 
https://github.com/iris-contrib/examples/tree/master/templates_2
