### ISSUE TITLE
package leveldb is not available

### ISSUE THREAD

**Issue by rebootcode** [kataras/iris#990]
Hi, I just upgraded my iris, and there is no leveldb package any more.

Does IRIS no more supports `leveldb` ?

**Comment by kataras** [comment]
You mean for the session storage? No leveldb is deprecated, use `badger` (which is the fastest based on my benchmarks) and `bolt` which is `leveldb`'s descendant, you can always use `redis` as well.

**Comment by rebootcode** [comment]
Yup for session! I am already using badger for storing other persistent information. I have now switched to boltdb for session storage.

I hope, there is not much performance issue. 

Thanks for the reply @kataras . Really appreciate it a lot.

**Comment by kataras** [comment]
Actual, even the boltdb is faster than leveldb, so you should be fine, you're very welcomed @rebootcode !
