### ISSUE TITLE
I want emit message to specific room by websocket.  but not working example document.

### ISSUE THREAD

**Issue by whiteprimrose** [kataras/iris#991]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

Hello. I want emit to specific room. but not working document example. 

This is the same symptom of the link : https://stackoverflow.com/questions/46271256/websocket-message-to-specific-room-golang-kataras-iris

**Comment by kataras** [comment]
Did you tried to move the `c.OnMessage` before the `c.To...Emit` ?

**Comment by whiteprimrose** [comment]
Attach the code. Please point out if you have a strange code.

server code : https://play.golang.org/p/xM8C7doEAS3
template code : https://jsfiddle.net/9b9uxowq/

**Comment by kataras** [comment]
The problem was caused by a third-party contributor a long time ago, I fixed it for good, I'm truly sorry for that.
