### ISSUE TITLE
Pug template subdirrectory and layout

### ISSUE THREAD

**Issue by ignishub** [kataras/iris#994]
> template: layout.pug:1:1491: executing "layout.pug" at <yield>: error calling yield:
> yield was called, yet no layout defined

I have this error when i am trying to render template from subdirrectory when i have layout file . He jsut cant find my file

**main.go**
```
        pug := iris.Pug("./content/pages", ".pug")
	pug.Layout("layout.pug")
	pug.Reload(*config.Debug)
	server.RegisterView(pug)
```
**admin.go**

```
func pagesNew(c iris.Context) {
	c.View("admin/page.pug")
}
```

**folder with templates**

```
│   index.pug
│   layout.pug
│   login.pug
│   page.pug
│   register.pug
│
└───admin
        page.pug
        page_list.pug
```

**Comment by kataras** [comment]
Hello @ignishub,

Can you please post a small example that I can reproduce this issue on my machine?

**Comment by ignishub** [comment]
Sorry....i updated Iris and problem was solved. Its just my old dep copy. 

:c

Thanks for answer!

**Comment by kataras** [comment]
You're welcome, no problem!
