### ISSUE TITLE
Goroutine panic. If there is two handlers with same URI-SOURCE-prefix ( "/invoices" and "/invoices_2")

### ISSUE THREAD

**Issue by koltsovb** [kataras/iris#995]
Example:
curl 127.0.0.1:8080/invoices

package main

import (
	"log"

	"github.com/kataras/iris"
)

func main() {
	log.Println("")

	app := iris.New()

	//party_2 := app.Party("/invoices_2")
	//party_2.Get("/{id:int}", Invoice_2)

	party := app.Party("/invoices")

	party.Get("/", Invoice)
	party.Get("/id/{id:int}", Invoice)

	app.Run(iris.Addr(":8080"), iris.WithoutVersionChecker, iris.WithoutStartupLog)
}

func Invoice(ctx iris.Context) {
	route := ctx.GetCurrentRoute() // route will be nil, if uncomment lines 14,15
	p := route.Path()
	m := route.Method()

	ctx.JSON("invoices " + p + " " + m)
}

func Invoice_2(ctx iris.Context) {
	route := ctx.GetCurrentRoute()
	p := route.Path()
	m := route.Method()

	ctx.JSON("invoices_r2 " + p + " " + m)
}

Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
The problem is the `GetCurrentRoute`, if you remove this, the router works fine, so the title is not described the problem exactly but thank you for opening this out, I'll investigate it more and fix the `GetCurrentRoute` there.

**Comment by kataras** [comment]
Fixed @koltsovb :), upgrade with `go get -u github.com/kataras/iris`, thank you for the bug report!

**Comment by koltsovb** [comment]
Thank, very quickly
