### ISSUE TITLE
Websockets over redis

### ISSUE THREAD

**Issue by kamilgregorczyk** [kataras/iris#997]
Hi, could you provide some tutorial on how to create proper websocket func. with redis as a backend? 
With 2 or more instances there's a chance that some clients won't receive updates.

**Comment by kataras** [comment]
Can you give me a code snippet that I can reproduce so I can help you please?

**Comment by kamilgregorczyk** [comment]
Imagine you have two instances running on kubernetes/ docker swarm or anything else. Load gets balanced between these two instances.  

When a client connects through websockets to instance A then it's going to receive updates which are produced by instance A. If at some point other client connects through websockets to instances B, to the same room then client A is not going to receive any updates. Redis Has  pub/sub functionality which makes it scalable.

Django channels has a plugin which uses Redis as a backend for websockets.  I like go but from what I see  iris hasn't been created by needs of some companies but by hobbyists which is fine but I don't feel safe to use iris :| not mentioning about that stuff which stashing commits, or removing iris from other repositories
