### ISSUE TITLE
SUPPORT HTTP/2 ??

### ISSUE THREAD

**Issue by 5nn** [kataras/iris#998]
Examples for the Iris project can be found at
<https://github.com/kataras/iris/tree/master/_examples>.

Documentation for the Iris project can be found at
<https://godoc.org/github.com/kataras/iris>.

Love iris? Please consider supporting the project:
👉  https://iris-go.com/donate

Care to be part of a larger community? Fill our user experience form:
👉  https://goo.gl/forms/lnRbVgA6ICTkPyk02

**Comment by kataras** [comment]
Of course, Iris was the first Go web framework that embraced HTTP/2 with SSL support. You can even use the `Push` for some months now, look [here](https://github.com/kataras/iris/blob/master/_examples/websocket/secure/main.go#L40) for example.
